### ISSUE TITLE
Feature request - Encoding Feedback

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#10]
From what I can see, I don't really get any feedback on individual encodes.  Because this system just replaces files in place, I'm quite nervous about letting it rip across my whole library. In particular, I don't want to lose any of the associated tracks, subtitles, audio etc within my files and I'm not convinced a handbreak plugin is going to be nice to me.  

 Common sense testing aside, I think it would be awesome to provide some method of feedback like a before after scenario e.g.

Original --------> New
h264 video ----> HEVC Video
Subtitle Eng ---> Unchanged
Audio Track 1 --> Unchanged
Chapter Marks -> Unchanged

etc

Probably a better way to display it though.

**Comment by Xe138** [comment]
I have the same concern about the direct replacement of files.  I'd like to be able to have a manual import option to allow for verifying results before replacing the original copies.  This may relate to my renaming request: #1.

A possible solution could be transcoded files being moved to a temporary folder.  After being manually verified, radarr/sonarr can be used to import the files back into the library.

**Comment by Tharic99** [comment]
That was some of my concern on Discord yesterday with regards to how I have HBBatch Beast running currently as a "man in the middle" type scenario for my files. Because HBB supports the option for an output location it alleviates that concern about direct replacement of files. It's not so much a concern about the app itself as a configuration issue. Whoops, I loaded the wrong plug-in and let it run for 12 hours before I went to bed and it downgraded all of my video or stripped out the subtitles, etc.

**Comment by marshalleq** [comment]
Thanks guys, obviously we share some of the same concerns, thinking about it this is probably two topics as per below - what do you think?
Topic 1 - A focus on providing feedback on what _did_ happen (which I called encoding feedback, but probably should have been named encoded feedback)
Topic 2 - A focus on providing feedback on what is _going_ to happen (testing, validation, non-destructive encoding etc)

What do you think?

**Comment by Xe138** [comment]
> Thanks guys, obviously we share some of the same concerns, thinking about it this is probably two topics as per below - what do you think?
> Topic 1 - A focus on providing feedback on what _did_ happen (which I called encoding feedback, but probably should have been named encoded feedback)
> Topic 2 - A focus on providing feedback on what is _going_ to happen (testing, validation, non-destructive encoding etc)
> 
> What do you think?

I agree.

**Comment by HaveAGitGat** [comment]
Simple file history added in v1.005.

Keeps track of:
Date
Size
Streams
![image](https://user-images.githubusercontent.com/43864057/67982980-a390c080-fc1b-11e9-87e7-19652d41b4d2.png)

Will be formatted better in future but it's a start.

There's already an issue open for an output directory.  I'll open a new issue for file verification.

> Topic 2 - A focus on providing feedback on what is going to happen (testing, validation, non-destructive encoding etc)

Not sure it's possible to do this. You don't know how ffmepg or HandBrake will react until it's actually processed a file (and there are millions of ways people can do that.)
