### ISSUE TITLE
output folder should be auto-ignored from source

### ISSUE THREAD

**Issue by Zixim** [HaveAGitGat/Tdarr#100]
This is certainly not core functionality, but worth mentioning I think?

It could potentially lead to an near-infinity transcoding loop, 
resulting in a 1 byte video file at the end of the universe.
💥💥💥

**Comment by HaveAGitGat** [comment]
What do you mean? If the output folder was ignored then plugins wouldn’t work properly and people would not be able to do what they want with their files. Only the first plugin would work, subsequent plugins would not be used.

**Comment by Zixim** [comment]
If the output folder is a subfolder of the library, and it is not specifically ignored in the Library/source config,
wouldn't there be a possibility that Tdarr will pick up the output folder and enqueue already encoded files ?
Filters can prevent this, but still...

**Comment by HaveAGitGat** [comment]
Well that is the problem. The output folder should never be inside the library. That makes no sense. 

Folder to folder conversion (output folder) should not be mixed with direct library management (original file replaced).

**Comment by HaveAGitGat** [comment]
Also there is the option to ignore a source subfolder in the library settings. You could add your output folder there to prevent the new files being scanned.

**Comment by Zixim** [comment]
That is exactly what I did, before my OP.

Don't get me wrong, i fully agree with you, outputting to a subfolder of source is not a great idea to say the least !
I did it, because I was apprehensive of letting Tdar rip through a heap of media files without being able to revert to original. Call it beginners' anxiety.
Under normal usage, I would let Tdarr transcode & overwrite.
