### ISSUE TITLE
Allow Tdarr to Concatenate Multiple Video files together (provided they match in codec/frame dimensions etc)

### ISSUE THREAD

**Issue by andrew-kennedy** [HaveAGitGat/Tdarr#1000]
I often transcode videos that are split into multiple parts, and I have to join them using the ffmpeg `concat` demuxer. I'd love to make this part of my tdarr workflow, before or after transcoding.

**Comment by HaveAGitGat** [comment]
Moved here ty: https://github.com/HaveAGitGat/Tdarr_Plugins/issues/633
