### ISSUE TITLE
Node keeps giving error: "Failed to contact server, retrying..." when trying to transcode

### ISSUE THREAD

**Issue by Smith334** [HaveAGitGat/Tdarr#1002]
I have connected to a docker Tdarr server with a Windows Tdarr node. But when I start a transcode it says that it fails to connect to server, even though it has been communicating all this time. I have tried re-deploying the container (incase there was any new parameter updates), and redownloading the Tdarr node. I am not sure what has caused this as it was working fine a few days ago, before I did the latest update. But even though i did update, I am sure I ran a transcode after and it was successful.

I am only trying to start a single GPU worker.
The problem seems to be exactly when it the "FFmpeg Begin Command" in my flow.

Tdarr version: 2.18.01
Server: Docker (Synology NAS)
Node: Windows 11 Pro (using NVENC, RTX 3070)

I have attached both my nodes logs and the flow I am using. Any help would be appreciated. Thanks

### Node logs:
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/15324569/Tdarr_Node_Log.txt)
### My Flow:
This flow is called by another one (parent flow) that is actually linked to the library. The parent flow only calls one of the comments at the top of this flow.
[data.txt](https://github.com/HaveAGitGat/Tdarr/files/15324610/data.txt)

### Node config:
**_I dont believe the apiKey property is within the 2.17.01 version node config json. It is in 2.18.01. Maybe this is the issue?_**

![image](https://github.com/HaveAGitGat/Tdarr/assets/28813931/aef575b6-0001-484d-a976-7930cd1d3634)

### Server docker configs:
![image](https://github.com/HaveAGitGat/Tdarr/assets/28813931/2359ca04-faaf-46b2-81e5-91f616c43d5b)
![image](https://github.com/HaveAGitGat/Tdarr/assets/28813931/df55f32a-92be-4557-a5a4-0730d5674ae2)
![image](https://github.com/HaveAGitGat/Tdarr/assets/28813931/14ef2de1-3a72-4c34-803f-bb89acaabf1b)

**Comment by Smith334** [comment]
I went back to version 2.17.1 for the server and the Windows node software and now i can transcode again.

**Comment by HaveAGitGat** [comment]
Please try 2.18.02. Was related to FFprobe '-show_data' flag added in previous version, causing high RAM usage on Nodes for files with lots of extra data.
