### ISSUE TITLE
Auth setting doesnt do aynthing

### ISSUE THREAD

**Issue by ToasterUwU** [HaveAGitGat/Tdarr#1003]
**Describe the bug**
I set "auth" in the Tdarr Server settings to `true`, but nothing changes. I can still access the webui without any login, and the popup for setting a name and password never shows.

**To Reproduce**
Have a v16.x install, update to the new v18.1, set auth to true, restart server, nothing happens.

**Expected behavior**
I should see the page allowing me to set a name and password and then only be able to enter after that with these credentials.

**Screenshots**

**Please provide the following information:**
```json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "HandBrakeCLI",
  "ffmpegPath": "ffmpeg",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": false,
  "cronPluginUpdate": "",
  "auth": true,
  "authSecretKey": "SomethingSomethingSomething"
}
```

 - OS: Ubuntu
 - Browser: Firefox
  - Version 2.18.01

**Comment by HaveAGitGat** [comment]
Please update to 2.18.02 thanks.
