### ISSUE TITLE
Bump base image to newer ubuntu to get newer LLVM

### ISSUE THREAD

**Issue by aaomidi** [HaveAGitGat/Tdarr#1004]
Hardware transcoding in the docker container does not work for 7000+ AMD GPUs due to the LLVM being too old.

```
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_16
'gfx1100' is not a recognized processor for this target (ignoring processor)
'gfx1100' is not a recognized processor for this target (ignoring processor)
```

This is similar to this bug: https://github.com/ValveSoftware/steam-for-linux/issues/9077

**Comment by HaveAGitGat** [comment]
Moving under here, please try images in this comment and let me know if works for you:
https://github.com/HaveAGitGat/Tdarr/issues/902#issuecomment-2167763722
