### ISSUE TITLE
Separate Output nodes for the "Run Classic Transcode" plugin depending on if work has been done by the plugin

### ISSUE THREAD

**Issue by BjoernUsw** [HaveAGitGat/Tdarr#1005]
**Is your feature request related to a problem? Please describe.**
The Classic plugin stack would jump back to the top of the stack if a plugin has modified the working file which allowed to loop through the stack multiple times until no plugin has changes to make. This allowed for example for audio transcode plugins to only transcode one stream at a time because the file would be coming back for the next stream automatically.

Replicating this dynamic behavior in Flows is a lot more challenging because the filtering for if a file needs another run through a plugin needs to be done manually, and I don't even know how to start to check if every 5.1 or 7.1 audio stream has a matching 2.0 stream in the same language

**Describe the solution you'd like**
Adding a second output node to the Run Classic Transcode plugin would simplify this problem. One output node gets used if the plugin has made changes to the file, and the other node gets used if the node hasn't made changes. This would allow looping back to the desired location in the flow if changes have been made, or to continue further along the flow if no change has been made.

**Describe alternatives you've considered**
Currently, I have the same plugin node multiple times one after each other to account for multiple streams in need of transcoding, but this slows down the flow unnecessarily if there are less than the expected maximum of streams and has the risk of not catching all streams if a file has additional streams with for example supplementary commentary.

**Comment by HaveAGitGat** [comment]
Added:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/08f0086b-5beb-4d0b-bf98-3c82a3c176d9)


https://github.com/HaveAGitGat/Tdarr_Plugins/pull/639
https://docs.tdarr.io/docs/plugins/flow-plugins/index/classic/Run%20Classic%20Transcode%20Plugin

**Comment by jacroe** [comment]
@HaveAGitGat Since the v1 got deprecated, is there a timeline where we'll need to migrate flows using the v1 to v2?
