### ISSUE TITLE
Add the FPS counter from HandBrakeCLI to the WebGui

### ISSUE THREAD

**Issue by dennix85** [HaveAGitGat/Tdarr#1008]
**Is your feature request related to a problem? Please describe.**
Not that i know off, i looked through the open topics

**Describe the solution you'd like**
Welp like you know already, I'm a big fan of the ARC GPU's especially with AV1 encoding. 
For this process I'm a big fan of HandBrake, but to check the encoding speed, i have to refer everytime to the logs of a running a job, to see what kind of FPS is a certain task is running sadly, I would really appreciate it if you could implement the FPS from the handbrake logs to the webGUI like the ffmpeg process is been displayed on the webGUI

**Describe alternatives you've considered**
Welp I have really no clue, i think this is really only the dev could implement if possible.

**Additional context**
So the FPS's shown here in the logs 
![image](https://github.com/HaveAGitGat/Tdarr/assets/129799653/a22f4769-ff8b-4410-a009-df6034f5ac5b)

To be shown here: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/129799653/68691427-30c9-4c58-adf0-24b6d2f63c23)

Where there are all zero's now :)

**Comment by HaveAGitGat** [comment]
Added:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/1976e998-7ed1-4ee9-a7cf-fff6aec3d0a7)

If using flows then will show with the next plugin update (https://github.com/HaveAGitGat/Tdarr_Plugins/pull/652), happens hourly or if you update manually on the plugins tab.

If not using flows then will show in next Tdarr release `2.20.01`

**Comment by dennix85** [comment]
Works like a charm, I was very surprised this morning to see it actually counting 😁
Thank you very much.

**Comment by HaveAGitGat** [comment]
Great :), no problem.
