### ISSUE TITLE
HealthCheck Frequently Encounters "Too many packets buffered for output stream" Error

### ISSUE THREAD

**Issue by randomparity** [HaveAGitGat/Tdarr#101]
Running a HealthCheck on a video library, many files encounter the following error:

Too many packets buffered for output stream 0:1.

As a result, many perfectly fine video files show up in the "Health check: Error/Cancelled" tab.

A Google search suggests that the error is [well known](https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01) and can be resolved by adding the command line option "-max_muxing_queue_size 9999" to ffmpeg.

**Comment by Zixim** [comment]
Time to create your own local plugin then : 
https://github.com/HaveAGitGat/Tdarr/wiki/4---Plugins

**Comment by HaveAGitGat** [comment]
Ok I’ll have a look at this 👍

**Comment by HaveAGitGat** [comment]
@Zixim not sure what you mean by that. Plugins are separate to the health check process.

**Comment by HaveAGitGat** [comment]
Fix added in 1.102

**Comment by Zixim** [comment]
couldn't OP add `-max_muxing_queue_size 9999` to a local plugin ?

**Comment by randomparity** [comment]
You need to copy the community plugin to a local plugin and then edit the
local plugin to add the ffmpeg command-line option.  Each plugin is
different so the code is slightly different, but all plugins will create a
string for the ffmpeg command-line.  Here's an example
from Tdarr_Plugin_MC93_Migz2CleanTitle:

  // Convert file if convert variable is set to true.
  if (convert === true) {
    response.infoLog += '☒File has title metadata. Removing \n';
    response.preset = `,${ffmpegCommandInsert} -c copy -map 0
-max_muxing_queue_size 9999`;
    response.reQueueAfter = true;
    response.processFile = true;
  } else {
    response.infoLog += '☑File has no title metadata \n';
  }
  return response;
}

Dave
