### ISSUE TITLE
Duration filter in search isn't working

### ISSUE THREAD

**Issue by journeym** [HaveAGitGat/Tdarr#1010]
**Describe the bug**
Duration filter in search isn't working

**To Reproduce**
Enter search, filter for any number

**Expected behavior**
Get results

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/7759734/1f424ee1-18ac-41db-a3bc-a4b3e73de287)
![image](https://github.com/HaveAGitGat/Tdarr/assets/7759734/65670f61-5ed8-44e1-b4ec-21d4a3fb6da9)

**Please provide the following information:**
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/15438160/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/15438161/Tdarr_Server_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/15438162/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/15438163/Tdarr_Server_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [docker]
 - Browser [edge]
 - Version [latest]

**Additional context**

**Comment by HaveAGitGat** [comment]
Fixed for next version ty
