### ISSUE TITLE
[Bug/Feature request] Error: Invalid change spec language code '"und"

### ISSUE THREAD

**Issue by Maypul** [HaveAGitGat/Tdarr#1012]
**Describe the bug**
Running a new Run CLI plugin, I get error code in logs. This error does not happen, if for example, if run locally with the same program.

**To Reproduce**
Run CLI - mkvpropedit
Make sure you run following command: 
--set language="und"
You get:
Error: Invalid change spec (invalid ISO 639-2 language code '"und"') in '--set language="und"'.

**Expected behavior**
The plugin to finish the work and set the language as Undefined.

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/98578889/170c1426-e294-4169-a6cb-67a46d4fa0c2)

**Please provide the following information:**
N/A

**Additional context**
Undefined language is listed in this ISO as for example in https://www.loc.gov/standards/iso639-2/php/code_list.php
![image](https://github.com/HaveAGitGat/Tdarr/assets/98578889/61472153-fc10-459e-9ee2-de450bd70b39)
From MKVToolNix:
![image](https://github.com/HaveAGitGat/Tdarr/assets/98578889/983a11f9-bd83-47b6-8aa0-80a6f0a8f8cc)

Would love the support for it to be added, as I use this code quite often in my files.

**Comment by supersnellehenk** [comment]
Have you tried removing the double quotes? Seems it's interpreting the double quotes as part of the language code.

**Comment by Maypul** [comment]
It's possible you are right, as now it is giving me different error which I will have to troubleshoot tomorrow. Thank you for pointing it out for me. I will close this issue for now!
