### ISSUE TITLE
How to Add a New Transcoded Audio Stream with Custom Bitrate in Tdarr

### ISSUE THREAD

**Issue by psychedelicu** [HaveAGitGat/Tdarr#1016]
If you want to keep other audio streams like DTS or TrueHD and add a new transcoded audio stream with a custom bitrate, follow these steps:

**Install Plugin:**
•	Install the **Tdarr_Plugin_00td_action_add_audio_stream_codec** (Add Audio Stream Codec) plugin.

**Edit the Local downloaded Plugin**:
•	Open the plugin in the Tdarr interface.
•	Do not change the name, ID, or description of the plugin, as it will cause the plugin to fail to load.

**Replace the Code**:
•	Delete the existing code in the plugin.
•	**Replace it with the code from this link**: https://codefile.io/f/FecLfQx7dA.

This will allow you to keep your original audio streams and add a new audio stream with a custom bitrate.
Happy transcoding!

**Comment by HaveAGitGat** [comment]
Ty for sharing
