### ISSUE TITLE
ffmpeg doesn't recognize Video Toolbox

### ISSUE THREAD

**Issue by RedCelicaTRD** [HaveAGitGat/Tdarr#1018]
I have a 2018 Mac mini with an Intel processor running a Tdarr node, version 2.19.01. I have created a flow that checks for hardware acceleration before trying to transcode. I have 5 nodes with different hardware and this helps me filter them to the correct Handbrake presets I have created for each node. To do this, I am using the "Check Node Hardware Encoder" plugin. I have selected the "hevc_videotoolbox" drop down within the plugin which should pass the video file onto my Handbrake presets for Video Toolbox. The Video Toolbox plugin is the 3rd hardware check done in the flow.

A video will start going through the flow and reach the Node Hardware plugin and then it will say that "hevc_videotoolbox" is disabled. I checked the log and it looks like the Node Hardware plugin is using the following to check:

> ffmpeg -hwaccel videotoolbox -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_videotoolbox -f null /dev/null
> Checking for encoder hevc_videotoolbox with command:
> Encoder hevc_videotoolbox is disabled

If I try and run the same command outside of Tdarr I get the following output:

> [hevc_videotoolbox @ 0x7fbd43907c00] Color range not set for yuv420p. Using MPEG range.
> [hevc_videotoolbox @ 0x7fbd43907c00] Error encoding frame: -12905peed=   0x    
> Video encoding failed

I have regular Handbrake on my Mac and it does show H.265 (VideoToolbox) as being available. If I use the ffmpeg command "ffmpeg -hide_banner -hwaccels" I get the following output which means I should have the ability to use Video Toolbox, correct?

> Hardware acceleration methods:
> videotoolbox

I somehow did have one successful transcode when doing a 4K video. The ffmpeg command to check on this file was

> Checking for encoder hevc_videotoolbox with command:
> ffmpeg -hwaccel videotoolbox -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_videotoolbox -f null /dev/null
> Encoder hevc_videotoolbox is enabled
> {"enabledDevices":[{"encoder":"hevc_videotoolbox","enabled":true,"inputArgs":["-hwaccel","videotoolbox"],"outputArgs":[],"filter":""}]}
> Plugin run complete

No hardware or software changes were made between yesterday, when the single hardware check was successful, and today. I thought I had it working so I let the transcode run and didn't look at it until this morning. I then tried more videos and was unsuccessful.

Also, is there a reason that ffmpeg does a color check when it is checking hardware acceleration?

**Comment by HaveAGitGat** [comment]
It's working fine on a mac mini M2 so potentially the version of ffmpeg does not fully support the 2018 mini? Have you tried  installing FFmpeg manually and using that? (Would need to update the `ffmpegPath` in the Node config file). It's not a color check, it's just a temporary in memory input for testing the encoder is available/working.

**Comment by HaveAGitGat** [comment]
Tdarr macOS 64 bit ffmpeg builds are from here: https://evermeet.cx/pub/ffmpeg/

If it's working intermittently for some things then seems perhaps something else may be using the video encoder which then prevents it working with ffmpeg (or could be faulty chip but that's unlikely).

Could also be that the ffmpeg version no longer fully supports the 2018 mini or has trouble fully engaging it so would instead install ffmpeg with homebrew: https://formulae.brew.sh/formula/ffmpeg. Then set the ffmpeg path in the Node config to `ffmpeg` so it uses the local system ffmpeg assuming it's been added to system path (should be done automatically during homebrew install).

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bfffe848-34e8-48a2-b255-a2eec3799c3d)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/651f0e6f-2900-4040-935c-5637c76eed2f)

Add any updates/info if needed.

**Comment by RedCelicaTRD** [comment]
I finally had some free time to make the changes you suggested and I am still having issues. I have downloaded FFMPEG via brew and changed the node config to have the path only be "ffmpeg". When I try and run the command that Tdarr uses to check for VideoToolBox

> ffmpeg -hwaccel videotoolbox -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_videotoolbox -f null /dev/null

I get the following output

> ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
>   built with Apple clang version 15.0.0 (clang-1500.3.9.4)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
>   libavutil      59.  8.100 / 59.  8.100
>   libavcodec     61.  3.100 / 61.  3.100
>   libavformat    61.  1.100 / 61.  1.100
>   libavdevice    61.  1.100 / 61.  1.100
>   libavfilter    10.  1.100 / 10.  1.100
>   libswscale      8.  1.100 /  8.  1.100
>   libswresample   5.  1.100 /  5.  1.100
>   libpostproc    58.  1.100 / 58.  1.100
> Input #0, lavfi, from 'color=c=black:s=256x256:d=1:r=30':
>   Duration: N/A, start: 0.000000, bitrate: N/A
>   Stream #0:0: Video: wrapped_avframe, yuv420p, 256x256 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 30 tbn
> Stream mapping:
>   Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_videotoolbox))
> Press [q] to stop, [?] for help
> [hevc_videotoolbox @ 0x7fb34f207ec0] This device does not support the qmin option. Value ignored.
> [hevc_videotoolbox @ 0x7fb34f207ec0] This device does not support the qmax option. Value ignored.
> Output #0, null, to '/dev/null':
>   Metadata:
>     encoder         : Lavf61.1.100
>   Stream #0:0: Video: hevc, yuv420p(progressive), 256x256 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 30 fps, 30 tbn
>       Metadata:
>         encoder         : Lavc61.3.100 hevc_videotoolbox
> [hevc_videotoolbox @ 0x7fb34f207ec0] Color range not set for yuv420p. Using MPEG range.
> [hevc_videotoolbox @ 0x7fb34f207ec0] Error encoding frame: -12905
> [vost#0:0/hevc_videotoolbox @ 0x7fb34f207b80] Error submitting video frame to the encoder
> [vost#0:0/hevc_videotoolbox @ 0x7fb34f207b80] Error encoding a frame: Generic error in an external library
> [vost#0:0/hevc_videotoolbox @ 0x7fb34f207b80] Task finished with error code: -542398533 (Generic error in an external library)
> [vost#0:0/hevc_videotoolbox @ 0x7fb34f207b80] Terminating thread with return code -542398533 (Generic error in an external library)
> [out#0/null @ 0x7fb34f205f40] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
> [out#0/null @ 0x7fb34f205f40] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
> frame=    0 fps=0.0 q=0.0 Lsize=N/A time=N/A bitrate=N/A speed=N/A    
> Conversion failed!

Does this look like it is an issue from my Mac being an Intel Mac or is there something else I need to look at?

Thank you!

**Comment by HaveAGitGat** [comment]
What’s the command that was run? Should be just above that output you posted.  

Try running this on one of your files in a terminal:

```
ffmpeg -i input.mp4 -c:v hevc_videotoolbox output.mp4
```

**Comment by RedCelicaTRD** [comment]
I ran the following in terminal and received a "Conversion failed!":

ffmpeg -hwaccel videotoolbox -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_videotoolbox -f null /dev/null

I also tried to run a conversion using ffmpeg and the format you suggested and it was not successful. For some reason I have to add a pixel format in order to get a conversion to work. I modified your suggested command from:

> ffmpeg -i input.mp4 -c:v hevc_videotoolbox output.mp4

and added a pixel format to give me

> ffmpeg -i input.mp4 -c:v hevc_videotoolbox -pix_fmt yuv420p10le output.mp4

This worked, but the format I originally selected was not supported and the conversion reverted to p010le. I then ran a encoder check with ffmpg using 

> ffmpeg -h encoder=hevc_videotoolbox

and got the following output:

> Encoder hevc_videotoolbox [VideoToolbox H.265 Encoder]:
>     General capabilities: dr1 delay hardware 
>     Threading capabilities: none
>     Supported hardware devices: videotoolbox 
>     Supported pixel formats: videotoolbox_vld nv12 yuv420p bgra p010le

I tried modifying the original hardware check done by Tdarr with the pixel format information and did not receive any errors when using pixel formats nv12, p010le, and bgra. Bgra worked best of all and did not give any errors or warnings for "Color range not set for (nv12 or p010le). Using MPEG range."

> Input #0, lavfi, from 'color=c=black:s=256x256:d=1:r=30':
>   Duration: N/A, start: 0.000000, bitrate: N/A
>   Stream #0:0: Video: wrapped_avframe, yuv420p, 256x256 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 30 tbn
> Stream mapping:
>   Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_videotoolbox))
> Press [q] to stop, [?] for help
> [hevc_videotoolbox @ 0x7f7e79907b80] This device does not support the qmin option. Value ignored.
> [hevc_videotoolbox @ 0x7f7e79907b80] This device does not support the qmax option. Value ignored.
> Output #0, null, to '/dev/null':
>   Metadata:
>     encoder         : Lavf61.1.100
>   Stream #0:0: Video: hevc, bgra(pc, gbr/unknown/unknown, progressive), 256x256 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 30 fps, 30 tbn
>       Metadata:
>         encoder         : Lavc61.3.100 hevc_videotoolbox
> [out#0/null @ 0x7f7e79905c00] video:2KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
> frame=   30 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.96 bitrate=N/A speed=1.01x    

Yuv420p and videotoolbox_vld both resulted in errors:

> [hevc_videotoolbox @ 0x7fcf8d9075c0] Color range not set for yuv420p. Using MPEG range.
> [hevc_videotoolbox @ 0x7fcf8d9075c0] Error encoding frame: -12905
> [vost#0:0/hevc_videotoolbox @ 0x7fcf8d907280] Error submitting video frame to the encoder
> [vost#0:0/hevc_videotoolbox @ 0x7fcf8d907280] Error encoding a frame: Generic error in an external library
> [vost#0:0/hevc_videotoolbox @ 0x7fcf8d907280] Task finished with error code: -542398533 (Generic error in an external library)
> [vost#0:0/hevc_videotoolbox @ 0x7fcf8d907280] Terminating thread with return code -542398533 (Generic error in an external library)
> [out#0/null @ 0x7fcf8d9058c0] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
> [out#0/null @ 0x7fcf8d9058c0] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
> frame=    0 fps=0.0 q=0.0 Lsize=N/A time=N/A bitrate=N/A speed=N/A    
> Conversion failed!

**Comment by HaveAGitGat** [comment]
Thanks, so is it a case of just modifying the check or do we need to add that stuff to the actual video transcode arguments for your files being processed?

**Comment by RedCelicaTRD** [comment]
I believe it is just modifying the check. When I use the GUI version of Handbrake the transcode is successful using VideoToolBox. I believe Handbrake will properly check and use VideoToolBox, but the incorrect check is causing the plug-in to skip the transcode process.

**Comment by alexedwards565** [comment]
Having this issue using my M4 Mac Mini as a node with ffmpeg from homebrew. 

When running the test command in a terminal:
`ffmpeg -hwaccel videotoolbox -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_videotoolbox -f null /dev/null`

it outputs these errors:
`[hevc_videotoolbox @ 0xc4ec48a80] Error setting bitrate property: -12900
[vost#0:0/hevc_videotoolbox @ 0xc4f058000] [enc:hevc_videotoolbox @ 0xc4ec0d8f0] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 0xc4f050000] Error sending frames to consumers: Generic error in an external library
[vf#0:0 @ 0xc4f050000] Task finished with error code: -542398533 (Generic error in an external library)
[vf#0:0 @ 0xc4f050000] Terminating thread with return code -542398533 (Generic error in an external library)
[vost#0:0/hevc_videotoolbox @ 0xc4f058000] [enc:hevc_videotoolbox @ 0xc4ec0d8f0] Could not open encoder before EOF
[vost#0:0/hevc_videotoolbox @ 0xc4f058000] Task finished with error code: -22 (Invalid argument)
[vost#0:0/hevc_videotoolbox @ 0xc4f058000] Terminating thread with return code -22 (Invalid argument)
[out#0/null @ 0xc4f000b40] Nothing was written into output file, because at least one of its streams received no packets.`
