### ISSUE TITLE
Duplicating a libraries settings appears to duplicate some stats too

### ISSUE THREAD

**Issue by ripkurrle** [HaveAGitGat/Tdarr#1019]
**Describe the bug**
Duplicating an existing library with completed statistics copies those statistics into the new library where I believe they should be kept separate.

**To Reproduce**
1) Create a Library linked to some files
2) Perform some transcoding/health checks on the library
3) Duplicate the library
4) Select duplicated library
5) Ensure the library is pointed to a different location so it should have different stats
5) Select Options -> Scan (Fresh)
6) Wait some time for the duplicated library to show in Stats
7) Select library in Stats

**Expected behavior**
Notice that the following stats have been duplicated from the original Library
* Number of transcodes 
* Space saved 
* Number of health checks 

**Screenshots**
Original Library
![original](https://github.com/HaveAGitGat/Tdarr/assets/19253405/f7c1b8f3-d191-42de-a767-551c07e95753)

Duplicate Library
![duplicate](https://github.com/HaveAGitGat/Tdarr/assets/19253405/d5d4e261-2bbe-4b89-bb47-72392de9df73)

 - OS: Windows (for Server), Windows and Linux (Nodes)
 - Browser Chrome
 - Version 2.19.01

**Additional context**
I also tried refreshing stats but this didnt seem to changing anything. Ideally the fix would recalculate the correct values per library so the stats are correct for anyone that has been stung by this issue.

**Comment by HaveAGitGat** [comment]
Updated for next version

**Comment by ripkurrle** [comment]
Thanks, is there anyway to correct the values? I've tried directly editing the stats and library sons but refreshing or restarting the server seems to make no difference

**Comment by HaveAGitGat** [comment]
Yes, make sure to stop Tdarr server then just edit the files in `LibrarySettingsJSONDB` and save the changes. Once Tdarr starts up it will show the values that you put in.

In `LibrarySettingsJSONDB`:
```
    "totalHealthCheckCount": 2005,
    "totalTranscodeCount": 105,
    "sizeDiff": 0.5803511003032327,
```
