### ISSUE TITLE
[Feature request] Workers on different nodes

### ISSUE THREAD

**Issue by mads03dk** [HaveAGitGat/Tdarr#102]
First off: Tdarr is awesome!

I have multiple server nodes just sitting idle most of the time. Would it be possible to add some kind of multi-node-worker support? 
An example: The main Tdarr docker container is running on node1. On node2 and node3 you can then install a Tdarr-worker container. This container is then completely managed by the main Tdarr which tells the worker to transcode files some file is in queue.

I know this is a pretty huge feature to request, but i know a lot of others would enjoy this aswell.

**Comment by marshalleq** [comment]
Having something like this would be pretty amazing - I've see a few implementations of similar over the years, but having implemented within tdarr would be seriously cool.  Especially if you could use it to use multiple CPU's to encode a single file.

**Comment by mads03dk** [comment]
> .... if you could use it to use multiple CPU's to encode a single file.

I don't think this will ever be possible because of the way Handbrake works (Don't know about FFmpeg). Maybe some 3rd party software can split portions of the file to each node and then stitch everything together at last?

This is highly unlikely if you ask me :)

**Comment by clifford64** [comment]
I would also very much love this feature if possible. I have two Ryzen 2700x's in my homelab and am really only utilizing one for transcoding right now. If I could utilize the other, that would be awesome.

**Comment by HaveAGitGat** [comment]
I do have plans for this although it won’t include splitting a file between multiple machines. Firstly because HandBrake can’t do that and secondly because, although it can be done with FFmpeg, not many people would have the hardware needed to make real use of it.

**Comment by marshalleq** [comment]
Well, the only hardware you'd need is two machines really.  I just did a quick google - all of these except one seem to promise parallel encoding of single files to my reading.  So thought I'd get in quick in case any of this code can help.  If you could get that working, it would be amazing - you'd not only be the first proper encoding system out there for many types of workloads, you'd become the only proper implementation of an encoding cluster out there as well.  That is sure to turn heads!

https://github.com/jdupl/lancoder
https://github.com/nergdron/dve
https://tim.purewhite.id.au/2010/09/handbrake-encoding-cluster/
https://www.tiernanotoole.ie/2012/10/03/handbrake-cluster.html
http://blog.dustinkirkland.com/2014/07/scalable-parallel-video-transcoding-on.html
https://github.com/tiernano/handbrakecluster
There were more too!

**Comment by HaveAGitGat** [comment]
Sure I'll take a look at those thanks. A year or 2 ago I read about someone who tried something similar who ran into the issues I stated so that's the reason for my comment. Worth having a go though.

**Comment by sifotes** [comment]
https://github.com/munnerz/kube-plex

https://github.com/UnicornTranscoder/

 This type of thing exist for real time transcoding but I'm not sure what parts might be transferable.

**Comment by marshalleq** [comment]
> https://github.com/munnerz/kube-plex
> 
> https://github.com/UnicornTranscoder/
> 
> This type of thing exist for real time transcoding but I'm not sure what parts might be transferable.

Damn that’s cool.

**Comment by HaveAGitGat** [comment]
Tdarr v2 uses Tdarr_Nodes which work together:

![image](https://user-images.githubusercontent.com/43864057/105864120-e6de0880-5ff1-11eb-9ab2-723e01a8fea0.png)

Instructions here:
http://tdarr.io/docs/installation

Reopen if needed, thanks.

**Comment by smurfpandey** [comment]
The current implementation requires every node to have a copy of the file. Is it possible to transfer the media files to the worker node and then transfer it back once processed?

**Comment by theg00s3** [comment]
couldn't you just use a nfs mount?

**Comment by HaveAGitGat** [comment]
> The current implementation requires every node to have a copy of the file. Is it possible to transfer the media files to the worker node and then transfer it back once processed?

Hi, it does not require every node to have a copy of the file. It requires nodes and server to be able to access the same locations.

More info on why copying the file to the node is a bad idea here: https://github.com/HaveAGitGat/Tdar/issues/286#issuecomment-767598515


Would result in a huge amount of wasted transfer.

**Comment by smurfpandey** [comment]
I was planning to run server on pi4 & use my Windows 10 desktop as worker node. Even if I can access the file from the worker, the path would be different.

I will look at using docker to replicate the path, and see if that works.

**Comment by wsegatto** [comment]
Check the docs here. 

https://github.com/HaveAGitGat/Tdarr/tree/master/updater

Open /configs/Tdarr_Node_Config.json:

    {
    "nodeID": "QUkJYfSSD",
    "nodeIP": "0.0.0.0",
    "nodePort": "8267",
    "serverIP": "0.0.0.0",
    "serverPort": "8266",
    "handbrakePath": "",
    "ffmpegPath": "",
    "pathTranslators": [
        {
        "server": "",
        "node": ""
        }
    ]
    }
