### ISSUE TITLE
queue stalled - System limit for number of file watchers reached

### ISSUE THREAD

**Issue by HexRebuilt** [HaveAGitGat/Tdarr#1021]
**Describe the bug**
The queue no longer proceedes after the ammount of files to be checked for modification is reached.

**To Reproduce**
Have a big media library with subs and other files in it that makes the number of element go up. Or the system reads 3 times the library, thinking that the number of items is 3 times as it should be.
![image](https://github.com/HaveAGitGat/Tdarr/assets/32871843/0530584e-d023-4b96-b1e3-f596a9f3c8bd)

**Expected behavior**
The number of files shall not impact the functionality of the system

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/32871843/62a193ba-9049-4b04-bc71-872eb70799cd)

**Please provide the following information:**
- Log files  
[Server-log.txt](https://github.com/user-attachments/files/15816928/Server-log.txt)

-Worker error : none it simply no longer proceeds

 - OS: truenas scale
 - Browser chrome
 - Version 2.17.01

**Additional context**
since the docker OS is read only i cannot edit the number of watchers to be higher
![image](https://github.com/HaveAGitGat/Tdarr/assets/32871843/c247bdf5-653c-41dc-9f09-67612ab2e627)

Now i've cleared both libraries and start a fresh scan to see if the error gets fixed.

**Comment by supersnellehenk** [comment]
This is inherently related to Linux, you have to increase the max_user_watches system wide. Not just on Tdarr. You can easily set it to 512288 and never have to deal with it again. (I've got mine set to 4194304 on my Proxmox system)

**Comment by HexRebuilt** [comment]
oh good to know. than i changed it in truenas. 
![image](https://github.com/HaveAGitGat/Tdarr/assets/32871843/eecb4f9f-3f79-4109-af0d-109332274c5b)

and just like _magic_  (like you said)
![image](https://github.com/HaveAGitGat/Tdarr/assets/32871843/99c81d78-cbce-4b53-935d-0e185d33d4ce)
 fixed
