### ISSUE TITLE
burn in subtitles option?

### ISSUE THREAD

**Issue by picarica** [HaveAGitGat/Tdarr#1022]
i wanted to try burning in subtitles using tdarr for whole series i already know stream index and everything 
i have been using this with terminal, but i dont want to keep my terminal windows open and screen and stuff is not avalaible
`find . -type f -name "*.mkv" -exec sh -c 'ffmpeg -i "$1" -c:v libx265 -vf subtitles="$1:stream_index=0:force_style=PrimaryColour=\&H00ffff\&"  -c:a copy "${1%.*}.mp4" && rm "$1"' _ {} \;`

basically
`ffmpeg -i input.mkv -c:v h264_nvenc -vf subtitles=input.mkv:stream_index=0 -c:a:1 copy output.mp4`
and i wanted to redo this in tdarr i tried looking around it flows i failed.

then i saw in basic plugin stack
**ffmpeg custom arguments**
and  then i just inpuuted 
`<io> -c:v libx265 <io>-vf subtitles="<io>:stream_index=0:force_style=PrimaryColour=\&H00ffff\&" <io>-c:a copy`
which didnt worked, i wondered what does <io> really does? and is there some variable that serves as input? this sucsefully transcoded but no subtitles were present.

is there any solutions? the reason for  burning in subttiels, my android TV or my jellyfin server, not sure which but doesnt really matter, always has delayed subtitles, jellyfin doesnt have option to burn in subtitles  so this is my solution.

**Comment by HaveAGitGat** [comment]
You have `<io>` 4 times in the Tdarr input. It should only be there once, it's to separate the input and output arguments. You have no input arguments so nothing should come before it.

So try:

`<io> -c:v h264_nvenc -vf subtitles=input.mkv:stream_index=0 -c:a:1 copy`

Add to https://github.com/HaveAGitGat/Tdarr_Plugins if you have any further plugin issues ty.

**Comment by picarica** [comment]
o think the issue is what do i put into subtitles, if i run for multiple files will input.mkv even work ?

because `<io> -c:v libx264 -vf subtitles="input.mkv:stream_index=0:force_style=PrimaryColour=\&H00ffff\&" -c:a copy`
like this it just doesnt work
getting a bit confused, but thank you for fast response

![image](https://github.com/HaveAGitGat/Tdarr/assets/45492894/1b2c1ea2-af4b-4968-af04-a30a1897f974)

**Comment by picarica** [comment]
@HaveAGitGat could this issue be open again?

**Comment by HaveAGitGat** [comment]
The error is in the section above.

`Add to https://github.com/HaveAGitGat/Tdarr_Plugins if you have any further plugin issues ty.`

Please put plugin issues in the plugin repo ty.
