### ISSUE TITLE
Notification in UI when a new version is available?

### ISSUE THREAD

**Issue by stevehoek** [HaveAGitGat/Tdarr#1023]
Is there a way to get a notification when a new server version is available?  Maybe in the Server UI?
I haven't figured out how to setup Discord notifications... no docs on that available that I can find.  But even so, it only notifies on Server startup and Node connect/disconnect... would be nice to have a notification for a new version available.

**Comment by HaveAGitGat** [comment]
Hi you should see a little notification at the top of the web ui when an update is available:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6e919013-dea1-4623-932d-93f8539341d2)

Please let me know if you can't see it (in this case you'd need to be on a version below `2.20.01` to see it).
