### ISSUE TITLE
Sonarr / Radarr 'Notifier' plugins not accounting for 'modified' folder paths.

### ISSUE THREAD

**Issue by gibxxi** [HaveAGitGat/Tdarr#1025]
**Describe the bug**
The Sonarr 'Notifier' plugin seems to query the app for the 'default' file / folder naming structure based on established norms in the app, but do not take account of / recognize any show folder where the folder name has been modified by that app to be different from the default.

**To Reproduce**
I have a TV show called 'Annika'. It's recognized on TVDB as having an embedded 'year' as part of the show title; so it determines the show name as being 'Annika (2021)'. However, I also have Sonarr's default folder naming policy to include the year a show premiered tacked onto the name of the show folder by default, so 'Annika (2021)' then becomes 'Annika (2021) (2021)', which I don't want. So within Sonarr, I manually edit the folder path, removing the additional '(2021)' from the folder name and get Sonarr to move the files / move them manually & refresh the show. But this change in the folder name results in the Notifier plugin being unable to locate the show when querying Sonarr, and the transcoding of any episodes in that show to fail.

**Expected behavior**
The Notifier plugins to query the 'current' file/folder path of a given show, not the 'expected / default' path.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows
 - Browser: Firefox
 - Version: 2.20.01

**Additional context**

**Comment by HaveAGitGat** [comment]
Hi, I've moved this to the plugins repo ty:
https://github.com/HaveAGitGat/Tdarr_Plugins/issues/667
