### ISSUE TITLE
api.tdarr.io being hit approximately once every 10-12 seconds

### ISSUE THREAD

**Issue by russkinz** [HaveAGitGat/Tdarr#1027]
**Describe the bug**
Approximately every 10-12 seconds, Tdarr is hitting api.tdarr.io

**To Reproduce**
As far as I can tell: Run Tdarr
I have tried shutting down and restarting the container, as well as just restarting the container.

**Expected behavior**
Tdarr will hit api.tdarr.io approximately every 10-12 seconds.

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/68681047/08795866-206c-41c5-8772-d3c3a0c94485)

**Please provide the following information:**
N/A

 - OS: Linux LXC
 - Browser Chrome
 - Version 2.20.01

**Additional context**
N/A

**Comment by russkinz** [comment]
It appears that this is only when the Relay is on - but this is new behaviour as I have had relay on for quite some time and this has only just started happening.

**Comment by HaveAGitGat** [comment]
Hi yes the updated stats are sent to Tdarr relay no-more than once every 10 seconds if the stats are being updated during processing. Can disable it with this toggle:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5538845c-bdfa-4523-8a7c-f8977fe72cc3)

Not sure what classic/flow plugins you're using but it may be that one of the plugins was updated which updates the stats so the new stats are being sent to relay. If this is happening during idle then let me know.

**Comment by HaveAGitGat** [comment]
I've added some more logic to help ensure it only sends the request if needed, will be in next version.
