### ISSUE TITLE
ADD  "TSAC":  Very Low Bitrate Audio Compression

### ISSUE THREAD

**Issue by donatopace** [HaveAGitGat/Tdarr#1028]
**Is your feature request related to a problem? Please describe.**
Limited Hard disk Storage, Audio Quality and Low Bitrate in streaming are the first problem of all users!

**Describe the solution you'd like**
Solve problems above

**Describe alternatives you've considered**
I have found a possible solution:
TSAC is an audio compression utility reaching very low bitrates such as 5.5 kb/s for mono or 7.5 kb/s for stereo at 44.1 kHz with a good perceptual quality. Hence TSAC compresses a 3.5 minute stereo song to a file of 192 KiB.

https://bellard.org/tsac/

Thanks.

**Comment by HaveAGitGat** [comment]
Looks interesting, can read some of the comments here about it https://news.ycombinator.com/item?id=39975331:


```
This doesn't have much of a use case.
- Can't use it in telephony (obvious application for low bitrates); phone handsets and headsets don't have the power to do it in real time.

- Very small files of good quality would be useful in tiny embedded systems that have low flash space: but what systems of that type have the processing power for decoding? Very low storage more or less goes hand in hand with weak processing.

The quality is astonishing for the bit rate, though.
```

Can try it with instructions here 
https://bellard.org/tsac/ 
https://bellard.org/tsac/readme.txt

```
wget https://bellard.org/tsac/tsac-2024-04-08.tar.gz
tar -xzf tsac-2024-04-08.tar.gz
cd tsac-2024-04-08/
wget https://samples.tdarr.io/api/v1/samples/sample__-__-__libmp3lame__30s__audio.wmv
./tsac c sample__-__-__libmp3lame__30s__audio.wmv test.tsac
```

Takes the file from about 1MB to 27KB which is cool.

But yeah this is a very experimental process atm, almost no applications support playing the codec so not very practical. Would need to wait for FFmpeg to add it or for all the usual media applications to support it (Plex, Jellyfin, VLC etc).

**Comment by donatopace** [comment]
TSAC was invented by the author of "FFmpeg".

**Comment by HaveAGitGat** [comment]
Yes I saw, was just saying ffmpeg and many video players don't support the tsac audio codec yet so may take a few years for them to implement (if they ever implement it at all as needing `RTX 3090, RTX 4090, RTX A6000, A100 or H100` is impractical for most people).

**Comment by weaming** [comment]
I thought I could use it in my web browser player to reduce audio file size. 😁
