### ISSUE TITLE
[Feature request] Pause workers when outside of schedule

### ISSUE THREAD

**Issue by mads03dk** [HaveAGitGat/Tdarr#103]
An option for Tdarr to pause handbrake transcode when it's outside of it's schedule. This way workers would not continue on with it's work until it's done when outside of it's schedule. 

If workers could be paused the CPU wouldn't be at a constant 100% while it's in my active hours

**Comment by HaveAGitGat** [comment]
I mentioned this on another issue but I’m 90% sure it’s not possible to pause a transcode through NodeJS. The typical ‘press p to pause’ interaction is done through a unique terminal process which I don’t think can be emulated in node.
