### ISSUE TITLE
Flow variables don't seem to work

### ISSUE THREAD

**Issue by tyzbit** [HaveAGitGat/Tdarr#1030]
**Describe the bug**
I have a flow that retries encoding with different settings. I ensure it only retries once by setting `retry=1` using the flow variable step and check the value. However, when it checks the value the second time, it incorrectly says it doesn't match and therefore goes into an infinite loop of retries.

**To Reproduce**
- Create flow
- Add set variable step (`retry=1`)
- Run another step
- Check variable value (`retry`) and observe that even though the variable should be set, the plugin fails as if the variable was not equal

It looks like `targetValue` is the name of the variable rather than the value. If I change the variable name, both `variable` and `targetValue` show the name of the variable only.

**Expected behavior**
Tdarr performs the variable check correctly and continues the flow according to the result

**Screenshots**
<img width="1046" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/3319104/96b16631-6b62-4308-aa8d-b4142f842755">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "auth": false,
  "authSecretKey": "REDACTED"
}
```
```
{
  "nodeID": "node",
  "nodeName": "node",
  "serverIP": "localhost",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "apiKey": ""
}
```
- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

```
2024-06-17T21:25:16.096Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:Loaded plugin inputs: {
2024-06-17T21:25:16.096Z "variable": "retry",
2024-06-17T21:25:16.096Z "value": "1"
2024-06-17T21:25:16.096Z }
2024-06-17T21:25:16.097Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:Setting variable retry to 1
2024-06-17T21:25:16.097Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:Plugin run complete
```

```
2024-06-17T21:29:17.183Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:Loaded plugin inputs: {
2024-06-17T21:29:17.183Z "variable": "retry",
2024-06-17T21:29:17.183Z "condition": "==",
2024-06-17T21:29:17.183Z "value": "1"
2024-06-17T21:29:17.183Z }
2024-06-17T21:29:17.183Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:variable = "retry"
2024-06-17T21:29:17.183Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:targetValue = retry
2024-06-17T21:29:17.183Z GY0_AUPFq:Node[node]:Worker[opaque-ox]:Variable retry of value retry does not match condition == 1
```

(truncated, can provide full logs if requested)

 - OS: Linux/Docker for Tdarr, MacOS for client
 - Browser - Firefox
 - Version - 2.10.01

**Additional context**

Here's the flow config

<details><summary>Click here to expand</summary>
<pre>
{
  "name": "Basic HEVC Video",
  "description": "Basic HEVC Video",
  "tags": "",
  "flowPlugins": [
    {
      "name": "HEVC, QP20",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandSetVideoEncoder",
      "version": "1.0.0",
      "id": "780-2s5eb",
      "position": {
        "x": 1107.1656256470712,
        "y": 87.73522687195717
      },
      "inputsDB": {
        "ffmpegQuality": "20",
        "forceEncoding": "false",
        "hardwareType": "vaapi",
        "ffmpegPreset": "fast"
      }
    },
    {
      "name": "HEVC, QP22",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandSetVideoEncoder",
      "version": "1.0.0",
      "id": "2bZ8rp4Qn",
      "position": {
        "x": 945.4693937572246,
        "y": 88.61468958745476
      },
      "inputsDB": {
        "ffmpegQuality": "22",
        "forceEncoding": "false",
        "hardwareType": "vaapi",
        "ffmpegPreset": "fast"
      }
    },
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "pE6rU7gkW",
      "position": {
        "x": 19.08507321579421,
        "y": 1.8396928308681169
      },
      "inputsDB": {
        "fileAccessChecks": "true",
        "pauseNodeIfAccessChecksFail": "true"
      }
    },
    {
      "name": "Check if hevc",
      "sourceRepo": "Community",
      "pluginName": "checkVideoCodec",
      "version": "1.0.0",
      "id": "91b7IrsEc",
      "position": {
        "x": 237.90047350803593,
        "y": 1.529139833005054
      }
    },
    {
      "name": "Start",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "4Swd6qzvc",
      "position": {
        "x": 476.7142063520999,
        "y": -0.2448836755411321
      }
    },
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "450g167D8",
      "position": {
        "x": 1082.0489375085047,
        "y": 458.9080890618693
      }
    },
    {
      "name": "Replace Original File",
      "sourceRepo": "Community",
      "pluginName": "replaceOriginalFile",
      "version": "1.0.0",
      "id": "4fkfOyR3l",
      "position": {
        "x": 142.15391058376696,
        "y": 529.4541562559833
      }
    },
    {
      "name": "Set Container",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandSetContainer",
      "version": "1.0.0",
      "id": "TtKXi3Q7h",
      "position": {
        "x": 1082.0836193757996,
        "y": 200.16536980533562
      }
    },
    {
      "name": "Reorder Streams",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandRorderStreams",
      "version": "1.0.0",
      "id": "QvR-bybip",
      "position": {
        "x": 1082.085955653025,
        "y": 341.393305169562
      },
      "inputsDB": {
        "channels": "2,5.1,7.1,1",
        "languages": ""
      }
    },
    {
      "name": "Require Review",
      "sourceRepo": "Community",
      "pluginName": "requireReview",
      "version": "1.0.0",
      "id": "2Zhrm_W7S",
      "position": {
        "x": 238.69318586210477,
        "y": 401.7468830470363
      }
    },
    {
      "name": "Video Bitrate Above 6Mbps",
      "sourceRepo": "Community",
      "pluginName": "checkVideoBitrate",
      "version": "1.0.0",
      "id": "ZNi47oNW5",
      "position": {
        "x": 1023.9717215662574,
        "y": 10.025615987100744
      },
      "inputsDB": {
        "unit": "kbps",
        "lessThan": "6000"
      }
    },
    {
      "name": "New Size <= Original Size",
      "sourceRepo": "Community",
      "pluginName": "compareFileSizeRatio",
      "version": "2.0.0",
      "id": "d0KCifQpr",
      "position": {
        "x": 340.11263755657444,
        "y": 178.21288223367984
      },
      "inputsDB": {
        "greaterThan": "0",
        "lessThan": "100"
      }
    },
    {
      "name": "Set retry variable to 1",
      "sourceRepo": "Community",
      "pluginName": "setFlowVariable",
      "version": "1.0.0",
      "id": "2UEwDS_R_",
      "position": {
        "x": 611.0798004465476,
        "y": 529.6100165714049
      },
      "inputsDB": {
        "value": "1",
        "variable": "retry"
      }
    },
    {
      "name": "Check if retry variable is 1",
      "sourceRepo": "Community",
      "pluginName": "checkFlowVariable",
      "version": "1.0.0",
      "id": "o0uQpUbfh",
      "position": {
        "x": 457.15365495610274,
        "y": 352.6187170935436
      },
      "inputsDB": {
        "variable": "retry",
        "value": "1"
      }
    },
    {
      "name": "Fail Flow",
      "sourceRepo": "Community",
      "pluginName": "failFlow",
      "version": "1.0.0",
      "id": "a6V4Y8Lph",
      "position": {
        "x": 431.28814021838514,
        "y": 529.408233253366
      }
    },
    {
      "name": "Starting second transcode with lower quality",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "S-Q8zwQUr",
      "position": {
        "x": 610.9909648827519,
        "y": 436.4727911834282
      }
    },
    {
      "name": "Not HEVC",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "QrbJGy1WR",
      "position": {
        "x": 307.98488933339866,
        "y": 86.05569301482814
      }
    },
    {
      "name": "Already HEVC",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "pnwu9K5uJ",
      "position": {
        "x": 142.16031022619157,
        "y": 85.6720954341884
      }
    },
    {
      "name": "New size is less than or equal to original",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "liuOfZ1eO",
      "position": {
        "x": 302.7482677904981,
        "y": 260.6319191377358
      }
    },
    {
      "name": "Max attempts reached",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "R5qmc2I0h",
      "position": {
        "x": 431.7047804191627,
        "y": 437.8594892684539
      }
    },
    {
      "name": "New size is greater than original",
      "sourceRepo": "Community",
      "pluginName": "comment",
      "version": "1.0.0",
      "id": "Q_v9a-1ZO",
      "position": {
        "x": 457.4682030068676,
        "y": 260.7667362245106
      }
    }
  ],
  "flowEdges": [
    {
      "source": "pE6rU7gkW",
      "sourceHandle": "1",
      "target": "91b7IrsEc",
      "targetHandle": null,
      "id": "HhF4rw2DZ"
    },
    {
      "source": "TtKXi3Q7h",
      "sourceHandle": "1",
      "target": "QvR-bybip",
      "targetHandle": null,
      "id": "mSHdvupij"
    },
    {
      "source": "QvR-bybip",
      "sourceHandle": "1",
      "target": "450g167D8",
      "targetHandle": null,
      "id": "0LVv7LArg"
    },
    {
      "source": "2Zhrm_W7S",
      "sourceHandle": "1",
      "target": "4fkfOyR3l",
      "targetHandle": null,
      "id": "t1BHGrMCq"
    },
    {
      "source": "ZNi47oNW5",
      "sourceHandle": "2",
      "target": "780-2s5eb",
      "targetHandle": null,
      "id": "zY-zyE3uz"
    },
    {
      "source": "780-2s5eb",
      "sourceHandle": "1",
      "target": "TtKXi3Q7h",
      "targetHandle": null,
      "id": "7rpIXqfYU"
    },
    {
      "source": "ZNi47oNW5",
      "sourceHandle": "1",
      "target": "780-2s5eb",
      "targetHandle": null,
      "id": "6-6O5HORD"
    },
    {
      "source": "450g167D8",
      "sourceHandle": "1",
      "target": "d0KCifQpr",
      "targetHandle": null,
      "id": "OvGHPmBpY"
    },
    {
      "source": "2UEwDS_R_",
      "sourceHandle": "1",
      "target": "2bZ8rp4Qn",
      "targetHandle": null,
      "id": "3t5qshxou"
    },
    {
      "source": "2bZ8rp4Qn",
      "sourceHandle": "1",
      "target": "TtKXi3Q7h",
      "targetHandle": null,
      "id": "rdGI3FdaL"
    },
    {
      "source": "o0uQpUbfh",
      "sourceHandle": "2",
      "target": "S-Q8zwQUr",
      "targetHandle": null,
      "id": "VHjKZ9g5e"
    },
    {
      "source": "S-Q8zwQUr",
      "sourceHandle": "1",
      "target": "2UEwDS_R_",
      "targetHandle": null,
      "id": "TpBZMSlvW"
    },
    {
      "source": "91b7IrsEc",
      "sourceHandle": "2",
      "target": "QrbJGy1WR",
      "targetHandle": null,
      "id": "kp_GOVEQM"
    },
    {
      "source": "QrbJGy1WR",
      "sourceHandle": "1",
      "target": "4Swd6qzvc",
      "targetHandle": null,
      "id": "V00eR52jw"
    },
    {
      "source": "91b7IrsEc",
      "sourceHandle": "1",
      "target": "pnwu9K5uJ",
      "targetHandle": null,
      "id": "ZwMC3RxiF"
    },
    {
      "source": "pnwu9K5uJ",
      "sourceHandle": "1",
      "target": "4fkfOyR3l",
      "targetHandle": null,
      "id": "uIYQEha9t"
    },
    {
      "source": "d0KCifQpr",
      "sourceHandle": "1",
      "target": "liuOfZ1eO",
      "targetHandle": null,
      "id": "VOH97S2Y5"
    },
    {
      "source": "liuOfZ1eO",
      "sourceHandle": "1",
      "target": "2Zhrm_W7S",
      "targetHandle": null,
      "id": "fw8wVKxRw"
    },
    {
      "source": "o0uQpUbfh",
      "sourceHandle": "1",
      "target": "R5qmc2I0h",
      "targetHandle": null,
      "id": "eU83D8Rsa"
    },
    {
      "source": "R5qmc2I0h",
      "sourceHandle": "1",
      "target": "a6V4Y8Lph",
      "targetHandle": null,
      "id": "13HNUaIgQ"
    },
    {
      "source": "d0KCifQpr",
      "sourceHandle": "3",
      "target": "Q_v9a-1ZO",
      "targetHandle": null,
      "id": "Rtp13sceT"
    },
    {
      "source": "Q_v9a-1ZO",
      "sourceHandle": "1",
      "target": "o0uQpUbfh",
      "targetHandle": null,
      "id": "F4sUnnoNI"
    },
    {
      "source": "4Swd6qzvc",
      "sourceHandle": "1",
      "target": "ZNi47oNW5",
      "targetHandle": null,
      "id": "3vDE_t_BB"
    },
    {
      "source": "d0KCifQpr",
      "sourceHandle": "2",
      "target": "Q_v9a-1ZO",
      "targetHandle": null,
      "id": "Ygi_ZIf7Y"
    }
  ]
}
</pre>
</details>

**Comment by tyzbit** [comment]
If I set the value of the variable to "retry" it now successfully matches, so I can make my flow work but it does appear it's testing against the variable name and not the variable value in the `checkFlowVariable` step.

**Comment by HaveAGitGat** [comment]
You haven't entered the inputs correctly, see the examples using the `?` button.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/19d7ed3f-4d5f-45c9-a666-00a41a418720)


Set Flow Variable:

```
Variable to set.

Example

transcodeStage

You can then check this in the 'Check Flow Variable' plugin {{{args.variables.user.transcodeStage}}}
```

So in your case would enter `{{{args.variables.user.retry}}}` in `Check Flow Variable`.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/feab211f-db32-459d-9283-0ea910e6f260)

It's showing `variable = "1"` because the logging is done in the plugin but the templating is done before the data is passed to the plugin. So `{{{args.variables.user.retry}}}` has already been replaced by `1` at the time the logging happens so need to check the part above where it shows the plugin inputs before the templating happens:

```
2024-06-18T07:17:36.930Z mvZrr9WB0:Node[linux]:Worker[runny-ram]:Loaded plugin inputs: {
2024-06-18T07:17:36.930Z "variable": "{{{args.variables.user.retry}}}",
2024-06-18T07:17:36.930Z "condition": "==",
2024-06-18T07:17:36.930Z "value": "1"
2024-06-18T07:17:36.930Z }
```

**Comment by tyzbit** [comment]
Big RTFM fail on my part. Sorry for the noise, thank you for the help!

**Comment by HaveAGitGat** [comment]
No problem :). Initially the `Set/Check Flow Variable` plugins were much simpler so e.g. you'd just set/check `retry` but then it was quite practical to enable `Check Flow Variable` to check hundreds of different bits of data passed to the flow plugin (can see all the data on the `args` object [here](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/27f0f3196b8a7a5d210ae70cb49c023229fc4a69/FlowPluginsTs/FlowHelpers/1.0.0/interfaces/interfaces.ts#L124), hence the need to use `{{{args.variables.user.xxx}}}` templating to specifically check the user variables. I'll see if I can make this clearer when using the plugins as easy to miss.
