### ISSUE TITLE
Delta Database changes for Bump / UnBump

### ISSUE THREAD

**Issue by davidry** [HaveAGitGat/Tdarr#1033]
**Is your feature request related to a problem? Please describe.**
New Feature suggestion 
Currently, Clicking Bump / UnBump on the bulk transfer queue seems to update the Database for all referenced within the queue, this means clicking unbump can require an hour or so for a large database

**Describe the solution you'd like**
1/ Read the database to confirm what is currently "bumped", only update the database references required

2/ A similar Solution on the Library "Requeue all Items", only re-queuing those that aren't already in the healthcheck or transcode queue.

**Describe alternatives you've considered**
Manual Unbump per queued item, Using various filters to limit the required database updates.

**Additional context**
![image](https://github.com/HaveAGitGat/Tdarr/assets/32561343/90dea7b2-82bd-4ad9-9dde-086780fd4079)

**Comment by HaveAGitGat** [comment]
I've updated this for next version, for example when bumping all files but only 1 item actually needs to be changed:

Old:
`Updated 3367 files in 28703ms`

New:
`Updated 3367 files in 28ms`

**Comment by HaveAGitGat** [comment]
2.21.01 released
