### ISSUE TITLE
Flow: Set Video Bitrate not being applied

### ISSUE THREAD

**Issue by Jordfoz16** [HaveAGitGat/Tdarr#1034]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
I created a flow that should decrease the bitrate of the working file. When testing and setting the bitrate too 1000 (as a test), I find that this doesn't get applied. This was tested a on a file that had a bit rate of 8465 kb/s, after running the file through the pipeline I got a bitrate of 5953 kb/s.

**To Reproduce**
This is the current flow that I have been using:
<img width="479" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/17856379/49c4c49c-cafb-4bc6-a6a6-4c68a0cc7c53">

Video Bitrate Settings:
<img width="1269" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/17856379/4832fa48-332e-4dbf-bf62-6d88105c5b0d">

Video Encoder Settings:
<img width="1269" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/17856379/b07c5500-dbaf-4522-8671-27fd8bb7df3e">

**Expected behavior**
I would have expected that the output file had a final bitrate closer to 1000 kb/s as set in the Video Bitrate.

**Screenshots**
Test File before transcoding
<img width="905" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/17856379/04bb9225-09d9-4573-9e65-f6379c0dff6c">

Test File after transcoding
<img width="905" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/17856379/32f4c6eb-d23c-4948-97a8-69de012ab232">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.json](https://github.com/user-attachments/files/15915025/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/user-attachments/files/15915026/Tdarr_Server_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/user-attachments/files/15915035/Tdarr_Node_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Linux - Unraid
 - Browser Chrome
 - Version [e.g. 2.00.00]

**Comment by HaveAGitGat** [comment]
Thanks, I've made these changes: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/674

So click update plugins on the classic plugins tab, then go to flows and make sure to disable ffmpeg quality (crf) as FFmpeg makes crf overried the bitrate setting:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/acf90170-6281-459b-a994-9bc6a41a41fb)

**Comment by Jordfoz16** [comment]
Thank you, that worked

**Comment by HaveAGitGat** [comment]
Great, thanks for checking :)

**Comment by m0t0rh3ad** [comment]
@Jordfoz16 can U please share you workflow?
