### ISSUE TITLE
Not working: Fixed UI loading bug when using proxy auth with Tdarr auth disabled 

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr#1035]
I have NGNIX proxy manager and I tried enabling authentication in the proxy for tdarr access as I saw that the UI loading auth bug was fixed.  Unfortunately, I'm still seeing the problem.  I tried incognito mode to confirm caching wasn't involved but same issue.

**Comment by HaveAGitGat** [comment]
I

**Comment by HaveAGitGat** [comment]
According to this it was working fine for them so the note was based on that:
https://discord.com/channels/623392507828371476/1250517373862150394/1251912429454233610

**Comment by begunfx** [comment]
Not sure why it's still happening, but I can confirm that the accessToken is being stored in the browser and am not getting null.  I keep getting the proxy login prompt (same as before).  Might be unrelated to the issue brought up in discord?

**Comment by HaveAGitGat** [comment]
Delete the accessToken in the browser local storage. Not sure what an npm container is but are you using the official Tdarr docker image?

**Comment by begunfx** [comment]
Clarification: NPM (NGINX Proxy Manager) Docker container.  Okay.  I'll try to figure out how to delete the accessToken.  Just a note: I did use Incognito mode in Chrome - which I thought doesn't store cookies etc.

**Comment by HaveAGitGat** [comment]
Seems this is now fixed: https://discord.com/channels/623392507828371476/1250517373862150394/1254379572779286558

```
haveagitgat/tdarr_acc:dev_2.21.01_2024_06_23T10_38_43z
haveagitgat/tdarr_node_acc:dev_2.21.01_2024_06_23T10_38_43z
```

Will be in next version.
