### ISSUE TITLE
Allow to forbid file-watcher to remove already transcoded files to better handle filesystems that can disappear (like NFS)

### ISSUE THREAD

**Issue by Th3Falc0n** [HaveAGitGat/Tdarr#1037]
**Is your feature request related to a problem? Please describe.**
When using NFS as storage for a media library it can happen that tdarr starts with an empty folder and deletes all database entries for files that are already transcoded.

**Describe the solution you'd like**
I would like to be able to forbid this behaviour and allow the folder-watcher to only add or modify files, not to remove them.

**Describe alternatives you've considered**
An alternative would be to have a failsafe like other applications that don't update the database when the library folder is completely empty.

**Comment by HaveAGitGat** [comment]
Here's some info on how it worked: https://www.reddit.com/r/Tdarr/comments/1de153a/comment/l89iixa

I've updated it for next version so that if specifically the source folder is not accessible (rather than all parent paths of the file), the file will not be removed from Tdarr DB.

**Comment by HaveAGitGat** [comment]
Can try/use the images now if you want:

```
docker.io/haveagitgat/tdarr_acc:dev_2.21.01_2024_06_23T11_58_45z
docker.io/haveagitgat/tdarr_node_acc:dev_2.21.01_2024_06_23T11_58_45z
```

**Comment by HaveAGitGat** [comment]
2.22.01 released
