### ISSUE TITLE
Add option to disable a flow node without having to remove it from flow (hotkey!)

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr#1038]
It would be nice to be able to disable any flow node with a simple hot-key (like the letter "d") and re-enable again.  This would be great for quick testing of parts of a flow which would avoid having to disassemble or create hacks to do flow testing.

**Comment by HaveAGitGat** [comment]
Added with `Ctrl + D`

Will always go to the first output of a skipped plugin:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/1baf9b36-b2e1-4000-a025-8b6268d0ea1e)

**Comment by begunfx** [comment]
Awesome.  Thank you!

**Comment by HaveAGitGat** [comment]
2.22.01 released

**Comment by begunfx** [comment]
Cool!
