### ISSUE TITLE
More control over sorting by date

### ISSUE THREAD

**Issue by azcom** [HaveAGitGat/Tdarr#104]
1. When creating a plugin and selecting 'Filter by age' there is only an option for 'Exclude files older than', but I am looking to add a filter by which I can 'Exclude files younger than' a set age. Can you add a way to select either younger or older than for the age filter?

2. It appears that the queue uses the 'File Created' date of files when the queue is sorted by oldest or newest but I would like the option to be able to go by the 'File Modified' date instead should I wish. Sometimes for various reasons files can have a file modified date that is older than the creation date. I need the ability to always process the latest (by air date) media before older episodes and so the current lack of a choice between which date to use for the queue means I often have many old episodes being transcoded before the very latest ones.

Thinking about it the option to select which date to check against may be better also put into the 'filter by age' filter rather than the queue options. This would then give more control to users as they could switch and change between the two depending on the library and the plugin(s) set for them.

**Comment by HaveAGitGat** [comment]
Added in 1.102
