### ISSUE TITLE
Node freezes on "Installing plugin dependency: import-fresh"

### ISSUE THREAD

**Issue by ddenev** [HaveAGitGat/Tdarr#1040]
When node starts working, it immediately freezes on the following step:
![image](https://github.com/HaveAGitGat/Tdarr/assets/1393766/2be315ed-e368-4f07-8045-74e63e335c4b)

This is the log in Tdarr_Node_Log.txt:
```
[2024-06-26T15:17:15.521] [WARN] Tdarr_Node - Dependency not found: import-fresh at /opt/tdarr/Tdarr_Node/assets/app/plugins/node_modules/import-fresh
[2024-06-26T15:17:15.522] [INFO] Tdarr_Node - Installing plugin dependency:import-fresh
```
The 1st time this happened was after I installed Tdarr (Debian install, no Docker). There are no permission issues, Tdarr is running as 'tdarr' user and this user is the owner of all Tdarr directories.
I fixed the issue by just copying the `import-fresh` directory from the `Tdarr_Node/node_modules` directory.

The problem is - today both the Server and the Node autoupdated and now `import-fresh` is again missing in `/opt/tdarr/Tdarr_Node/assets/app/plugins/node_modules` and all my jobs are freezing again because of that.

 - OS: Debian
 - Version 2.22.1

**Additional context**
This report relates to #925 which was closed. Again, my permissions are fine.

**Comment by HaveAGitGat** [comment]
Some info here:

https://github.com/HaveAGitGat/Tdarr/issues/925#issuecomment-1843449259

Feel free to update here if that does not work for you.

**Comment by HaveAGitGat** [comment]
Id also try installing npm (can use nvm https://github.com/nvm-sh/nvm?tab=readme-ov-file#install--update-script)

```
nvm install 18
nvm use 18.x (whichever was installed)
npm install fs-extra (try installing a package to test it works)
```

Then try run Tdarr again.

**Comment by HaveAGitGat** [comment]
It uses this package to install the dependencies:

https://www.npmjs.com/package/npm

Version: ^6.14.18

As far as I'm aware they removed the ability to install dependencies programatically in later versions which is why an older version is used.

```
const npm = require('npm');

const pluginsPath = '/opt/tdarr/Tdarr_Node/assets/app/plugins/'

npm.load({
  loaded: false,
  prefix: pluginsPath,
}, () => {
  npm.commands.install(['import-fresh'], () => {

    console.log('done')

  });
});
```

So to try that script yourself you'd need to make a new test directory anywhere such as `/opt/test`

Then open a terminal in the test directory and type `npm init` and press enter through the prompts (not important).

Then run `npm i -s npm@^6.14.18`

Then save the above script in the directory as `test.js` and run `node ./test`.

Should see this output:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my b
est with it!
+ import-fresh@3.3.0
added 4 packages from 1 contributor in 1.342s
done
```

So something on your system is blocking that it seems.

Tdarr has been moving towards flows and flow plugins for almost a year and flow plugins have everything pre-installed so don't need to install any extra dependencies. I'm not able to recreate the issue you're having so would be up to someone with the issue to see what's causing it but seems to be due to some non-standard system setup which npm is not expecting so it hangs.

**Comment by ddenev** [comment]
Thank you again for the detailed response!

Indeed, I installed `npm` via `apt install`, which installed a newer version of npm, not the one you mention above. I guess that might be the issue here.

I switched to flows as you recommended and even with the 'import-fresh' missing in `Tdarr_Node/assets/app/plugins/node_modules` everything is working great now, so I guess I'll be switching to flows from now on.

Just an idea: in the default install of Tdarr, the 'Transcode Options' for a library has the 'Plugin Stack' option selected by default, which mislead me to believe that this is the recommended way to setup processing. If you make the 'Flows' option the default one, I believe that would help future users not go the wrong way and hit such issues.

Thank you again and best regards!

**Comment by HaveAGitGat** [comment]
Thanks, no I don't think that's the issue. There are many people still using the classic plugin system without issue and the deployment tests still run fine with it. From my experience this is a very rare error (maybe <1 in 1000 users) and I can't recreate the issue so would take someone with the issue to follow the above steps I mentioned to find what the cause is :). This is not related to using `apt`. It could be something like firewall is blocking a specific request, permissions, missing directory etc.
 
I keep the classic plugin enabled by default for now because it's a bit simpler for new users to use that and then learn about flows at a later date when they want to do more advanced things if that makes sense. 

So if you can try the exact steps I mentioned in the previous comment then would help fix it for you. I'll link that in the other issue so someone might try too.

**Comment by HaveAGitGat** [comment]
Here is a shell script to run the test:

So save somewhere as `test.sh`, run `chmod +x ./test.sh`, run `./test.sh`
```
#!/bin/bash

# Define directory paths
npmDir="/mnt/c/Users/h/Desktop/tdarr-compose/testNpmDir"
pluginsDir="/mnt/c/Users/h/Desktop/tdarr-compose/testPluginsDir"

# Update package lists and install Node.js
sudo apt update
sudo apt install -y nodejs

# Check Node.js version
node -v

# Navigate to root directory
cd /

# Remove existing directories if they exist
sudo rm -rf "$npmDir"
sudo rm -rf "$pluginsDir"

# Create new directories
sudo mkdir "$npmDir"
sudo mkdir "$pluginsDir"

# Create the JavaScript script for npm
echo "const npm = require('npm');

const pluginsPath = '$pluginsDir';

npm.load({
  loaded: false,
  prefix: pluginsPath,
}, () => {
  npm.commands.install(['import-fresh'], () => {

    console.log('done');

  });
});" | sudo tee "$npmDir/testscript.js" > /dev/null

# Navigate to the npm directory
cd "$npmDir"

# Initialize npm with default values
npm init --yes

# Install specific npm version
npm i -s npm@^6.14.18

# Run the custom npm script
node testscript.js
```

Should end in:
```
+ import-fresh@3.3.0
added 4 packages from 1 contributor and audited 4 packages in 1.743s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

done
```

**Comment by ddenev** [comment]
OK, so I ran the script above and got this output:
```
root@Tdarr:~# ./test.sh 
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://security.debian.org bookworm-security InRelease [48.0 kB]
Get:4 http://security.debian.org bookworm-security/main amd64 Packages [161 kB]
Get:5 http://security.debian.org bookworm-security/main Translation-en [97.1 kB]
Fetched 362 kB in 0s (792 kB/s)                                
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libnode108 node-acorn node-busboy node-cjs-module-lexer node-undici node-xtend nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libnode108 node-acorn node-busboy node-cjs-module-lexer node-undici node-xtend nodejs nodejs-doc
0 upgraded, 9 newly installed, 0 to remove and 1 not upgraded.
Need to get 15.0 MB of archives.
After this operation, 69.7 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 libc-ares2 amd64 1.18.1-3 [102 kB]
Get:2 http://security.debian.org bookworm-security/main amd64 nodejs amd64 18.19.0+dfsg-6~deb12u1 [319 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 node-xtend all 4.0.2-3 [3932 B]
Get:4 http://deb.debian.org/debian bookworm/main amd64 node-acorn all 8.8.1+ds+~cs25.17.7-2 [128 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 node-cjs-module-lexer all 1.2.2+dfsg-5 [30.1 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 node-busboy all 1.6.0+~cs2.6.0-2 [16.9 kB]
Get:7 http://deb.debian.org/debian bookworm/main amd64 node-undici all 5.15.0+dfsg1+~cs20.10.9.3-1+deb12u3 [284 kB]
Get:8 http://security.debian.org bookworm-security/main amd64 libnode108 amd64 18.19.0+dfsg-6~deb12u1 [10.5 MB]
Get:9 http://security.debian.org bookworm-security/main amd64 nodejs-doc all 18.19.0+dfsg-6~deb12u1 [3569 kB]
Fetched 15.0 MB in 0s (36.1 MB/s)    
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 22857 files and directories currently installed.)
Preparing to unpack .../0-libc-ares2_1.18.1-3_amd64.deb ...
Unpacking libc-ares2:amd64 (1.18.1-3) ...
Selecting previously unselected package node-xtend.
Preparing to unpack .../1-node-xtend_4.0.2-3_all.deb ...
Unpacking node-xtend (4.0.2-3) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../2-nodejs_18.19.0+dfsg-6~deb12u1_amd64.deb ...
Unpacking nodejs (18.19.0+dfsg-6~deb12u1) ...
Selecting previously unselected package node-acorn.
Preparing to unpack .../3-node-acorn_8.8.1+ds+~cs25.17.7-2_all.deb ...
Unpacking node-acorn (8.8.1+ds+~cs25.17.7-2) ...
Selecting previously unselected package node-cjs-module-lexer.
Preparing to unpack .../4-node-cjs-module-lexer_1.2.2+dfsg-5_all.deb ...
Unpacking node-cjs-module-lexer (1.2.2+dfsg-5) ...
Selecting previously unselected package node-busboy.
Preparing to unpack .../5-node-busboy_1.6.0+~cs2.6.0-2_all.deb ...
Unpacking node-busboy (1.6.0+~cs2.6.0-2) ...
Selecting previously unselected package node-undici.
Preparing to unpack .../6-node-undici_5.15.0+dfsg1+~cs20.10.9.3-1+deb12u3_all.deb ...
Unpacking node-undici (5.15.0+dfsg1+~cs20.10.9.3-1+deb12u3) ...
Selecting previously unselected package libnode108:amd64.
Preparing to unpack .../7-libnode108_18.19.0+dfsg-6~deb12u1_amd64.deb ...
Unpacking libnode108:amd64 (18.19.0+dfsg-6~deb12u1) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../8-nodejs-doc_18.19.0+dfsg-6~deb12u1_all.deb ...
Unpacking nodejs-doc (18.19.0+dfsg-6~deb12u1) ...
Setting up node-cjs-module-lexer (1.2.2+dfsg-5) ...
Setting up libc-ares2:amd64 (1.18.1-3) ...
Setting up nodejs-doc (18.19.0+dfsg-6~deb12u1) ...
Setting up node-xtend (4.0.2-3) ...
Setting up node-busboy (1.6.0+~cs2.6.0-2) ...
Setting up node-undici (5.15.0+dfsg1+~cs20.10.9.3-1+deb12u3) ...
Setting up node-acorn (8.8.1+ds+~cs25.17.7-2) ...
Setting up libnode108:amd64 (18.19.0+dfsg-6~deb12u1) ...
Setting up nodejs (18.19.0+dfsg-6~deb12u1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u7) ...
v18.19.0
./test.sh: line 45: npm: command not found
./test.sh: line 48: npm: command not found
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'npm'
Require stack:
- /testNpmDir/testscript.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/testNpmDir/testscript.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/testNpmDir/testscript.js' ]
}

Node.js v18.19.0
```

It seems `apt install nodejs` on Debian does not install `npm`. So I installed it with `apt install npm`.
```
root@Tdarr:~# npm -v
9.2.0
```

After running the script again, I got:
```
root@Tdarr:~# ./test.sh 
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://security.debian.org bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (18.19.0+dfsg-6~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
v18.19.0
Wrote to /testNpmDir/package.json:

{
  "name": "testnpmdir",
  "version": "1.0.0",
  "description": "",
  "main": "testscript.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm WARN saveError ENOENT: no such file or directory, open '/testPluginsDir/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/testPluginsDir/package.json'
npm WARN testPluginsDir No description
npm WARN testPluginsDir No repository field.
npm WARN testPluginsDir No README data
npm WARN testPluginsDir No license field.

+ import-fresh@3.3.0
added 4 packages from 1 contributor and audited 4 packages in 0.627s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

done
```

So, in the end, the problem does not seem to be related to `npm` as, as mentioned in  https://github.com/HaveAGitGat/Tdarr/issues/1040#issuecomment-2191871054, I still had the same issue with npm and nodejs installed.

In addition, all permissions are properly set and there is no firewall that is blocking access.

**Comment by HaveAGitGat** [comment]
Thanks, the point of installing `sudo apt install -y nodejs` in the script (or `apt install npm` in your case) is just to use it to install the `npm@^6.14.18` module that Tdarr arleady comes with, can be found in:
`Tdarr_Server\node_modules\npm`

That's good that it's working in the script with your changes.

If you change the variables to this:

```
pluginsDir="/opt/tdarr/Tdarr_Node/assets/app/plugins"
```

Does it still work?

**Comment by ddenev** [comment]
Yes, after changing the `pluginsDir` to `/opt/tdarr/Tdarr_Node/assets/app/plugins` it still runs successfully:
```
root@Tdarr:~# ./test.sh 
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://security.debian.org bookworm-security InRelease [48.0 kB]
Get:4 http://security.debian.org bookworm-security/main amd64 Packages [161 kB]
Get:5 http://security.debian.org bookworm-security/main Translation-en [97.1 kB]
Fetched 362 kB in 0s (1416 kB/s)                                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (18.19.0+dfsg-6~deb12u1).
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
v18.19.0
Wrote to /testNpmDir/package.json:

{
  "name": "testnpmdir",
  "version": "1.0.0",
  "description": "",
  "main": "testscript.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm WARN saveError ENOENT: no such file or directory, open '/opt/tdarr/Tdarr_Node/assets/app/plugins/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/tdarr/Tdarr_Node/assets/app/plugins/package.json'
npm WARN plugins No description
npm WARN plugins No repository field.
npm WARN plugins No README data
npm WARN plugins No license field.

+ import-fresh@3.3.0
added 4 packages from 1 contributor and audited 4 packages in 0.527s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

done
```

**Comment by HaveAGitGat** [comment]
Ok that's good, well I suppose next step would be to run the js script from Tdarr's perspective by calling it in a flow plugin for example.

Does the classic plugin work when running it from a flow using `Run Classic Transcode Plugin`? Or does is till hang when installing classic plugin dependencies?

**Comment by moutasem1989** [comment]
I am running Tadarr Node in Docker on a second machin. I am facing the exact same issue as it gets stuck on `Installing plugin dependency: import-fresh`. The test.sh resturns as follwing:

```
{
  "name": "testnpmdir",
  "version": "1.0.0",
  "main": "testscript.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}
```

**Comment by HaveAGitGat** [comment]
You can also install the package `import-fresh` package manually in the server plugins folder which will be pushed out to the Nodes. You can see the server plugins folder on the classic plugins tab when clicking the `i` button: 

![image](https://github.com/user-attachments/assets/dddc7e7c-5be3-4bac-92f7-12ec72f98785)

So you'd add the `import-fresh` depedency to the `node_modules` folder in there:

![image](https://github.com/user-attachments/assets/0f246935-6cff-4a5c-8ac8-425ec3b17091)

Then make sure to remove `node_modules` line from the `tdarrIgnore` file so that Tdarr server includes `node_modules` in the zip file sent to the nodes.

**Comment by Tukajo** [comment]
Also had this issue with docker Tdarr node running in a Ubuntu server connecting to a Tdarr server running in docker on a Windows machine.

I know, convolutional. The connection seems to happen as the server registers the node but I also received odd the errors users mentioned.

I'm going to give your suggestion of adding the server node modules a try tomorrow.
