### ISSUE TITLE
"Hold until" width to small.

### ISSUE THREAD

**Issue by jaycedk** [HaveAGitGat/Tdarr#1043]
**Describe the bug**
Main Page -> sub section "Status" -> "Hold until" width to small.
Can you change it to show full date time.
![image](https://github.com/HaveAGitGat/Tdarr/assets/17232146/83781f81-dbe2-4903-af9c-b4c51d439957)

OS: Unraid docker.
Tdarr version : 2.22.01
Browser : Edge, Firefox

**Comment by HaveAGitGat** [comment]
Hi you can drag the columns to make them wider/thinner. I've widened the default a bit for next version.

**Comment by jaycedk** [comment]
Thank you for fixing it 👍
