### ISSUE TITLE
Flow is failing on "moving to working directory" without a error code.

### ISSUE THREAD

**Issue by PhattestMattest** [HaveAGitGat/Tdarr#1045]
**Describe the bug**
Tdarr flow is failing on "moving to working directory" without a error code. Cant diagnose the problem since Tdarr isnt telling me what the problem is.

**To Reproduce**
Not sure how one would reproduce this but ill leave a picture of my flow for reference. Please don't mind how bad my flow is, i'm new and still learning.

**Expected behavior**
I expect it to copy the file to the working directory so the bulk of the transcoding can be done off the drive I store my media on before being moved back.

**Screenshots**
Flow: https://i.imgur.com/cQzc8JZ.png

**Please provide the following information:**
- Config files / Report / Log:  https://drive.google.com/drive/folders/1kGDEJniQKbpqHIIiBGRJPjAX6wdYPXXi?usp=drive_link

 - OS: Windows 11 23H2
 - Browser Chrome
 - Version 2.22.01

**Additional context**
Seems to happen with files that are larger in size possibly 20GB in size or greater. I don't believe its a permissions issue due to the fact that I set the drives in question permission to everyone with full access for diagnostics purposes.

**Comment by HaveAGitGat** [comment]
Seems the copy is taking too long so the worker stall detector is killing the worker. You can disable the worker stall detector on the Options tab or can increase the stall check interval. I've added additional logging for this in future.
