### ISSUE TITLE
Node Priority

### ISSUE THREAD

**Issue by nichols89ben** [HaveAGitGat/Tdarr#1046]
**Describe the bug**
Node priority not being followed or adhered to 

Messed around with the settings for awhile and haven't gotten it to stick. 2 nodes - one with all gpu workers and the other cpu works. The idea being, the flow is set up to process with gpu first then when out of gpu workers, use node 2 and use cpu workers. Havent found a way for it to flow like that. Node priority is checked, for node1 allow gpu workers to do cpu tasks checked, the tab order between the two nodes is correct, but i did try both ways. I tried editing the node config json in the local folder and changing the priority on one changes both. I tried changing the NodeJSONDB files directly, gave the gpu node priority -1 and cpu node 1, that still did not do anything. Ill also note when changing the NodeJSONDB directly the config file in the gui options doesn't reflect the same priority, the match each other.  With that it still looks like they have equal priority and when 2 files are processed node 1 gets 1 and node 2 gets one. Screenshots and log/config files attached

[Archive.zip](https://github.com/user-attachments/files/16151196/Archive.zip)

![node1](https://github.com/HaveAGitGat/Tdarr/assets/77946739/30f4b4c5-3a30-4490-9a6c-d6d0e0df8d5b)
![node2](https://github.com/HaveAGitGat/Tdarr/assets/77946739/8b40803a-6afc-4a1a-a96a-81480748e39c)

**Comment by HaveAGitGat** [comment]
Hi, if you set the priority through the config or env vars then it's overwritten (in memory) as soon as you use the UI arrows. Editing the config or DB file directly won't do anything until the Node is restarted.

Just tried and seems working fine for me:

![image](https://github.com/user-attachments/assets/6b1dad3f-7241-4168-8eaf-51bdcdbe0d7b)


In this situation `test` node is set to 3 gpu workers and `linux` is set to 1 gpu worker. `linux` does not launch any gpu workers until `test` has 3 gpu workers running.

**Comment by HaveAGitGat** [comment]
Suppose can add a option to specify if the node priority is based on worker type or not.

**Comment by nichols89ben** [comment]
> Suppose can add a option to specify if the node priority is based on worker type or not.

Thank you! So just leave the configs alone, use the arrows and restart should keep it correct? Nice, ill try the {{{args.deps.configVars.config.nodeName}}}, which config does it read, the NodeJSONDB?

Also if we could include alac in some of the flow plugins as audio options at some point it would be great.

**Comment by HaveAGitGat** [comment]
If priority is set in the Node config JSON then when the Node connects it updates the `NodeJSONDB` with that value. Sure :).

**Comment by nichols89ben** [comment]
> If priority is set in the Node config JSON then when the Node connects it updates the `NodeJSONDB` with that value. Sure :).

It seemed fine for awhile, but Ive noticed recently the node priority has flipped back again, always defaulting to the Cpu. Can you take a peek when you have a sec and see if im doing something wrong. The way I wanted to set it up was the GPU node would always be first and if it ran out of workers to then start running cpu workers. 


![CleanShot 2024-09-17 at 20 11 46@2x](https://github.com/user-attachments/assets/ba23fa90-387b-438c-946c-4ab80d7ff9b2)
[Tdarr.zip](https://github.com/user-attachments/files/17036582/Tdarr.zip)
[Archive.zip](https://github.com/user-attachments/files/17036600/Archive.zip)

**Comment by ggulla** [comment]
> > If priority is set in the Node config JSON then when the Node connects it updates the `NodeJSONDB` with that value. Sure :).
> 
> It seemed fine for awhile, but Ive noticed recently the node priority has flipped back again, always defaulting to the Cpu. Can you take a peek when you have a sec and see if im doing something wrong. The way I wanted to set it up was the GPU node would always be first and if it ran out of workers to then start running cpu workers.
> 
> ![CleanShot 2024-09-17 at 20 11 46@2x](https://github.com/user-attachments/assets/ba23fa90-387b-438c-946c-4ab80d7ff9b2) [Tdarr.zip](https://github.com/user-attachments/files/17036582/Tdarr.zip) [Archive.zip](https://github.com/user-attachments/files/17036600/Archive.zip)

Did you ever figure this out? I'm having same situation happen. Node priority should be set correctly, my GPU nodes show up first in UI.
But even if the GPU nodes are completely empty as new jobs come in it seems to always send it to the CPU node first which is last in priority list.
