### ISSUE TITLE
Delete key doesn't work with flow editor

### ISSUE THREAD

**Issue by Funtime60** [HaveAGitGat/Tdarr#1048]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
The delete key doesn't work in the flow editor. The instructions say to use backspace, but that is reserved by the browser to go back a page so it just deletes unsaved progress.

**To Reproduce**
Use the delete key in the flow editor to remove a flow node, nothing will happen.

**Expected behavior**
The selected flow node should be removed.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Win10 64bit Pro
 - Browser Firefox
 - Version 128.0 84bit

**Additional context**
This didn't used to be a problem, but it could be that there was a different option other than backspace. The fact that delete doesn't delete a flow node doesn't make sense though.

**Comment by dennix85** [comment]
Well that default function use the backspace as hotkey to go back a page is long ago replaced with left ALT + LEFT buttons on the keyboard FYI, i use firefox also and the backspace button in flows works correctly. probably you setup the backspace back up as a hot key to get back a page after it was disabled by default a wile back ago.

**Comment by HaveAGitGat** [comment]
Checked this and delete key and backspace keys are working fine to delete a flow plugin in Chrome `126.0.6478.127` and Firefox `128.0` on Windows 11 so I assume what @dennix85 says is correct.

**Comment by HaveAGitGat** [comment]
@Funtime60 just to double check, you have the flow plugin selected before deleting right? (It won't delete if just hovering over). When clicking on it you can see it's selected by the white border around it:
![image](https://github.com/user-attachments/assets/649de3a5-51d5-4ac2-9975-39d1d195399f)

Else could it be that your keyboard or locale or something has a different keycode for the delete key? Tdarr uses keycode 46 which is the standard delete key code.

Go to this website and press the delete key, maybe you get a different number:
https://www.toptal.com/developers/keycode

![image](https://github.com/user-attachments/assets/330c1419-7ac2-48a7-9404-7254e53fb5bd)

Feel free to add info here and will take a look.

**Comment by Funtime60** [comment]
Sorry I made this late at night when it was more important to me so I forgot about it. Anyways, yes I do select the node and it still doesn't work. My keycode is 46 on that website. The reason this is impactful is that I forgot you could right click since the right click menu is nowhere near the nodes and sometimes are even so far away I can't find them. This has always been an issue for me, I've just been too lazy to report it.
![image](https://github.com/user-attachments/assets/9cea73b3-44ff-4d93-96c3-00dd487a5a9f)

**Comment by Funtime60** [comment]
I only have Firefox installed and I don't plan on changing. Firefox is just
more customizable.

**Comment by supersnellehenk** [comment]
This is me using the backspace & delete key in a fresh install of Firefox 128.0. https://imgur.com/a/QCqx6hM Seems like your install of Firefox is altered in some way compared to fresh? As the right click menu also appears somewhere different.
