### ISSUE TITLE
How many workers should I run?

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#105]
I was wondering how I determine how many workers I should run? I can set this option to a whole bunch, or just a few. Just wondering on how I should determine what a good number of workers for transcoding should be?

**Comment by HaveAGitGat** [comment]
Depends how much load you want your server to be under. If you’re not using it for anything else then keep on increasing the number of workers until either CPU,RAM or I/O are maxed out.

**Comment by clifford64** [comment]
The CPU pretty much maxes out with just 1 worker. I have an AMD Ryzen 2700x 8 cores 16 threads. I have it running on an ESXi host with 12 virtual CPUs assigned to the VM.

**Comment by luigi311** [comment]
It probably will max out with a single worker depending on what you are encoding too and how well that scales. If you are encoding to x265 then that will max out the cpu with just a single encode. If you are encoding to AV1 using the aom encoder then you can utilize multiple workers since the aom encoder does not scale well.

**Comment by clifford64** [comment]
I am encoding in x265, should I only be running 1 worker then, or would there be a benefit to running 3? I have been running three because it was the default on the program that I used called unmanic. Yes items would take longer to encode, but it would do multiple at a time.

**Comment by luigi311** [comment]
I would personally only use 1 so if I want to watch a TV show and all the episodes need to be encoded I can watch them one after another if the next episode finishes encoding before the episode I am watching is done playing. Maybe even 2 just in case it does not scale all the way perfectly.

**Comment by clifford64** [comment]
I did some testing with multiple files with multiple qualities and found that with 1 worker, the time would be 4 hours 15 minutes. 2 workers would be 4 hours 2 minutes. 3 workers was 3 hours 52 minutes. So I am going to stick with 3 workers for now.
