### ISSUE TITLE
 Could not find codec parameters for stream

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#1052]
**Describe the bug**
So im not sure if its a flow thing (again...) but anyway from [redacted] which tdarr doenst like.

I upload my flow and log files. As far as i know i strip everything before and order it, so it shouldnt be a flow thing? (files play fine in plex) 

If someone knows what i have to strip (and how) from the files to process them, that would be really great. It seem slike its always the same error (sometimes stream 3 or 4)

[data.txt]
[data (1).txt]

**Expected behavior**
Every media just works.

- Config files  
[Tdarr_Node_Config.json]
[Tdarr_Server_Config.json]

- Job reports:
[FppzEK9_M-log.txt]
[QN4B5qcJp-log.txt]
[VVv_BQXol-log.txt]
[1s3lEU79O-log.txt]

- Log files 
[Tdarr_Node_Log.txt]
[Tdarr_Server_Log.txt]

-Worker error

 - OS: unraid
 - Browser: chrome latest
 - Version: docker latest

**Comment by supersnellehenk** [comment]
Add the "Remove Data Stream" plugin before the ImageRemoval plugin, should function fine after that.

Data streams are usually some kind of additional metadata which a singular program can read, but throws off ffmpeg as it's invalid in a few containers.

**Comment by supersnellehenk** [comment]
Hadn't taken the time to import your flow, but you want to move the Remove_DataStreams and MigzImageRemoval to right after the Input File block.

**Comment by supersnellehenk** [comment]
Yeah my bad, it's actually an `attachment` stream causing issues in MP4. You can remove those with a Begin ffmpeg, Remove Stream by Property checking `codec_type` `includes` `attachment`, but that can screw up attached fonts for ASS/SSA subs in anime files.

The best option would be to keep MKV, as that does support attachment streams
