### ISSUE TITLE
Simplified Flow Synchronization

### ISSUE THREAD

**Issue by nichols89ben** [HaveAGitGat/Tdarr#1054]
Hello!

I’m looking for a more efficient way to share identical flows across multiple servers. I currently manage one master flow that meets all my needs. Previously, I would make an edit, then copy and replace the entire FlowsJSONDB in each of the other DB2 files, restart the servers, and everything would update seamlessly.

However, with the recent update to the SQL DB, I now have to manually paste the flow into each DB. While I’m aware of the “export to clipboard” and “paste from JSON” features for new flows, using them seems to change the flow ID and disrupts the linkage of some “go to” flows.

It would be incredibly helpful to have an “update flow from JSON” feature or the ability to edit the JSON flow directly within the UI, similar to how plugins can be edited.

Thank you!

**Comment by nichols89ben** [comment]
> This is still planned 👍

Cool, I knew you had a lot going on with the switch so I thought it could wait.

**Comment by HaveAGitGat** [comment]
In 2.24.04 when you export a flow it will export the _id so when you import several flows that depend on each other it should work fine. Is this ok?

**Comment by nichols89ben** [comment]
> In 2.24.04 when you export a flow it will export the _id so when you import several flows that depend on each other it should work fine. Is this ok?

Yes, that should work fine. I liked the ability to drop and replace the flows via the files, then start the container, keeping the libraries with the assigned flow intact. This method still makes it easy, just need to delete the old flow first and then reassign it in the library. Will changing the flow in the library, like designating a new flow, trigger a requeue? I also noticed that some of the flow plugins Migz posted earlier are now incompatible with the new version 🥴

**Comment by HaveAGitGat** [comment]
No changing a flow does not requeue files, that needs to be done manually. Which Migz plugin are you having trouble with? There haven't been any changes to the community ones in a few months.

**Comment by nichols89ben** [comment]
> No changing a flow does not requeue files, that needs to be done manually. Which Migz plugin are you having trouble with? There haven't been any changes to the community ones in a few months.

He posted them as Experimental flows in Discord awhile ago and I grabbed them. Actually the only one I use that has an error is the Check Stream one. It was a very handy way to filter all A/V/Sub streams. Lmk if you know of something I can adjust to get it going or what I could use instead. I haven't gone through updated community flows in a minute. 


[Experimental Flows.zip](https://github.com/user-attachments/files/16695426/Experimental.Flows.zip)

**Comment by HaveAGitGat** [comment]
Sorry for the delay but if you're still having trouble could you post the files not in a zip at https://github.com/HaveAGitGat/Tdarr_Plugins thanks
