### ISSUE TITLE
Ability to pause adding to stage if threshold is reached instead of pausing all nodes

### ISSUE THREAD

**Issue by ZerithZA** [HaveAGitGat/Tdarr#1055]
**Is your feature request related to a problem? Please describe.**
Currently when the cache threshold is reached you only have the ability to pause all nodes which stops Tdarr from working completely. 

**Describe the solution you'd like**
Another radio button that will allow us to stop tasks from being added to the stage area from the queue section but still allow nodes to process tasks out of the stage area. Like possibly be able to set a value to add into stage area until 200G of space is free. Then you can have the original functionality trigger to pause at  50G or 100G to stop the system from crashing or running out of free space.

**Describe alternatives you've considered**
Tried the current functionality that pauses everything.

**Additional context**
None at this point in time

**Comment by HaveAGitGat** [comment]
Staged items still need additional cache space for subsequent tasks. You can limit the number of files in the staging section by using this option which I think is what you're looking for:
![image](https://github.com/user-attachments/assets/d7643e40-cdb9-4ae5-9d9d-676189764f38)
