### ISSUE TITLE
Fix sorting on Stage area to have processing at the top

### ISSUE THREAD

**Issue by ZerithZA** [HaveAGitGat/Tdarr#1056]
**Describe the bug**
Fix the sorting on the Stage area to have tasks being processed at the top of the list instead of on the last page.

**To Reproduce**
Have more that 1 page of items in stage environment, Processing tasks will be on the last page.

**Expected behavior**
Processing tasks to be on the top of the first page like it used to be.

**Screenshots**

**Please provide the following information:**
Running in Docker using ghcr.io/haveagitgat/tdarr
Tdarr version 2.24.02

**Additional context**

**Comment by HaveAGitGat** [comment]
2.24.03 released

**Comment by ZerithZA** [comment]
Great, thanks for the fast feedback and solution.
