### ISSUE TITLE
set_mempolicy operation not permitted

### ISSUE THREAD

**Issue by chimpfacts** [HaveAGitGat/Tdarr#1058]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
When converting media using the plugin stack shown in the Screenshots, the majority of jobs will report "Set_mempolicy: Operation not permitted" and the job will fail. As of not it only appears to take effect when converting to HEVC with AC3 audio codec, although I haven't tested much further.

**To Reproduce**
Use the plugin stack as per the screenshot, the 5th plugin in the stack is set to ac3 and the "Migz Transcode" plugin is converting to mkv container with H265 video codec.

**Expected behavior**
These settings have worked for the majority of my library, the files producing this error have the same permissions and are mounted in the same way as those that are working

**Screenshots**
![image](https://github.com/user-attachments/assets/534080cd-23fa-48fc-ad72-04ecc980d24e)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.json](https://github.com/user-attachments/files/16643431/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/user-attachments/files/16643432/Tdarr_Server_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports

[uRVDAYq_wv-log.txt](https://github.com/user-attachments/files/16643433/uRVDAYq_wv-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.txt](https://github.com/user-attachments/files/16643434/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/user-attachments/files/16643435/Tdarr_Node_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Ubuntu VM
 - Browser Chrome
 - Version 2.24.03

**Comment by HaveAGitGat** [comment]
```
tdarr-ffmpeg -i "/anon_klcii9/anon_pc7dqi anon_92jkgl - anon_ecna6h - anon_u2wnza anon_oo1oip anon_opd9rw anon_csv8jq - anon_6w6x7.mkv" -map 0 -c:v libx265 -b:v 5296k -minrate 3707k -maxrate 6884k -bufsize 10592k -c:a copy -c:s copy -max_muxing_queue_size 9999 "/anon_klcii9/anon_pc7dqi anon_92jkgl - anon_ecna6h - anon_u2wnza anon_oo1oip anon_opd9rw anon_csv8jq - anon_3uqg6n.mkv"
```
You could try running this command manually in a terminal inside the container (without the anonymization) but if it's working fine on other files then not much we can do other than upload the file with ffmpeg bug report: https://ffmpeg.org/bugreports.html

For those particular files I'd perhaps try running through a Handbrake preset. You could make a flow to do this automatically like this:

![image](https://github.com/user-attachments/assets/a7d1e787-8fcf-4561-94da-797219e069db)
