### ISSUE TITLE
Set Video Resolution Flow Plugin using wrong video axis for target resolution

### ISSUE THREAD

**Issue by gibxxi** [HaveAGitGat/Tdarr#1059]
**Describe the bug**
Tdarr/FFMpeg analyses an input file and sets the video's resolution based on the vertical resolution, which is how it should be. However, the 'Set Video Resolution' flow plugin bases it's resizing on the width of the video, which results in an encoding loop if setting limits on what 'p' rating / resolution you desire for videos that are not true 16:9 aspect ratio.

**To Reproduce**
Attempt to encode a video at a set resolution (e.g: 720p) with a file whose resolution is not true 16:9, where the output result for the vertical axis will result in a size above 720p, and the file will be put through the encoding process again, but the resolution will not change, as Tdarr/FFMpeg has determined the width of the file is correct for 720p (1280), but the 'Set video resolution' flow plugin will disagree as it's using height to calculate it's desired output (720p). The file will then end up in a re-encoding loop, where it can be re-encoded up to 6 times.  

**Expected behavior**
The 'p' resolution rating of a video file should be calculated on the vertical resolution, never the horizontal resolution, therefore the 'Set Video Resolution' flow plugin should also be following the same analysis method that Tdarr/FFMpeg is, to determine the resolution and desired resizing and/or re-encoding of the file.

**Comment by HaveAGitGat** [comment]
Moving to https://github.com/HaveAGitGat/Tdarr_Plugins/issues/693

> Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins
