### ISSUE TITLE
Schedule number of workers per library

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#106]

**Comment by mbc0** [comment]
this would be great! I run single encode jobs all day, it would be nice to increase that overnight during server 'idle' time!

**Comment by emilio215** [comment]
had some libraries where i wanted a cpu encode and others where i wanted a gpu encode. can schedule 2 workers, but there's a chance still of ending up with 2 cpu encodes or 2 gpu encodes depending on how quickly one task finishes.

**Comment by HaveAGitGat** [comment]
Added to July to-do on Discord
