### ISSUE TITLE
Library alternation seems broken since recent update

### ISSUE THREAD

**Issue by bassterror** [HaveAGitGat/Tdarr#1060]
I didn't catch it immediately, but since one of the last updates "Library alternation" doesn't seem to work properly.
The sorting of the queue is by "Newest (Scanned)".
![image](https://github.com/user-attachments/assets/c97fb70b-a2b9-4a52-9111-0e6f797930bc)
As you can see, the sorting in the queue looks OK, but what it happens is that when it pulls the next file it just moves file 7 to position 1. As a result it just processes one library. This wasn't like this before. I'm not sure that I changed anything or maybe my understanding of the feature is not accurate.

[Tdarr_Server_Log.txt](https://github.com/user-attachments/files/16646616/Tdarr_Server_Log.txt)

 - OS: Linux
 - Browser: Brave
 - Version: 2.24.04

**Comment by HaveAGitGat** [comment]
Hmm was a bit of an interesting problem but fixed for next version thanks:
![image](https://github.com/user-attachments/assets/aa972ff6-0ab1-498e-9cd3-d94521a6da4f)

**Comment by HaveAGitGat** [comment]
`2.24.05` released
