### ISSUE TITLE
Sorting by ratio size sorts by string not by number

### ISSUE THREAD

**Issue by Jacob-Lasky** [HaveAGitGat/Tdarr#1061]
**Describe the bug**
The old size / new size ratio seems to be a string and not a float. I sorted by size and get 0, 100, ... 150, 22, etc.
![image](https://github.com/user-attachments/assets/3ae91a9a-e828-4e6e-b648-2c47a37f3b33)
![image](https://github.com/user-attachments/assets/500fd8a8-a7b3-40a6-a73e-33a95b8419ef)

**To Reproduce**
Click "Ratio" in any of the tabs
![image](https://github.com/user-attachments/assets/28ecd40d-bc51-4d8f-8c3e-e1ca7ed86743)

**Expected behavior**
I expected the ratio to be sorted by value, 0 --> 10 --> 20 --> ... --> 90 --> 100

**Screenshots**
Attached above

 - OS: UnRAID
 - Browser: Chrome
 - Version: 2.24.04

**Comment by HaveAGitGat** [comment]
Seems the data I was using was working fine:

![image](https://github.com/user-attachments/assets/ef226de7-3884-48a9-af83-e339d57e1bde)

![image](https://github.com/user-attachments/assets/168c3f3e-aa30-49b9-beb5-db72904943e3)

But yes after playing around with more values it wasn't right, updated for next version ty.

**Comment by HaveAGitGat** [comment]
`2.24.05` released
