### ISSUE TITLE
Multi CPU system dell poweredge T440 and I cannot use more then 1 CPU for CPU transcoding

### ISSUE THREAD

**Issue by codys76** [HaveAGitGat/Tdarr#1062]
**Describe the bug**
I can only utilize 50% of my CPU power. In unraid when I run tdarr node with no CPU pinning, only the cores on CPU 0 are pegged to 100% but the other cores have little or no usage. When I pin ONLY the cores for CPU 1 it will use those cores with no issues, but when I try to use both, it will only pick 1 CPU and use those cores only. I would Ideally like it to utilize both CPU's if possible 

<img width="584" alt="bug" src="https://github.com/user-attachments/assets/fadecdde-0105-41ee-a0bc-2d01814b8267">
<img width="629" alt="bug2" src="https://github.com/user-attachments/assets/493f4cfe-ccd5-44c0-b58f-206cd1c95736">

 - OS: Unraid
 - Browser Chrome
 - Version 6.12.11

**Comment by HaveAGitGat** [comment]
It depends what you're running at that time. It may be that a single threaded operation is occurring which will only be able to use one thread (such as audio operations or disk I/O). Check the job report when the worker is running: https://docs.tdarr.io/docs/other/job-reports

Is it the same when you run multiple workers?

![image](https://github.com/user-attachments/assets/b3077d50-7ea1-4acf-a9a2-3fa26e6e6975)

Tdarr itself doesn't do any CPU pinning.
