### ISSUE TITLE
UI filters now require case-match

### ISSUE THREAD

**Issue by jacroe** [HaveAGitGat/Tdarr#1063]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
Beginning with possibly the 2.24.04 release, filters in the Status tables now require an exact case match. I may be wrong, but I don't believe this was required before. And I feel confident that this is a bug since the release notes say "to not require exact match".

As an example, when filtering for "the" in the File(CSV) column, I may get results like `Diners, Drive-ins and Dives - 29x15 - Piling On the Pork.mkv`. But when filtering for "The", I get results for `Kevin Can F-k Himself - 02x07 - The Problem.mkv`. Neither result appears in the alternate case.

**To Reproduce**

1. Note the casing of a value in the File(CSV), Codec, Resolution, or Size columns on the Transcode Queue tab. (N.b. this occurs on at least the Transcode Queue, Transcode Success, Transcode Error, and Health Check Healthy tabs. It might occur on all of them, but I didn't have the data staged to test the others.)
2. Filter by the inverse of the casing, e.g. "1080p" would become "1080P"
3. The result set does not include the previously noted items.

Another note: the Library column does not seem to be affected by this; it filters in a case-insensitive manner.

**Expected behavior**
Filters should be case-insensitive when producing result sets. "hevc" and "HEVC" and "heVc" should give the same results.

**Screenshots**
![Screenshot from 2024-08-22 01-01-59](https://github.com/user-attachments/assets/781ce83d-7629-4040-9c04-3451252eb007)
![Screenshot from 2024-08-22 01-01-51](https://github.com/user-attachments/assets/211e3881-e846-4c4b-8c54-85b4d68b3b0a)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

`Tdarr_Server_Config.json`:
```json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "auth": false,
  "authSecretKey": "[REDACTED]"
}
```

`Tdarr_Node_Config.json`:
```json
{
  "nodeName": "[REDACTED]",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "apiKey": ""
}
```

- Job reports: https://docs.tdarr.io/docs/other/job-reports
N/A

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
N/A

- Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
N/A

 - OS: Docker on Ubuntu
 - Browser: Firefox v129.0.2 on Ubuntu
 - Version: 2.24.05

**Additional context**
Please let me know if I can provide any extra, but I can't think of anything at the moment.

**Comment by HaveAGitGat** [comment]
Hi this is intentional so exactly what is needed can be searched for filenames in the queues.

**Comment by HaveAGitGat** [comment]
The issue is that with large libraries it may be necessary to search for an exact match else you get a lot of unwanted results. In the next feature release I'll add an option/way to enable exact match but for now it will keep the previous behaviour of case insensitivity. I've released a patch to latest that resolves this.
