### ISSUE TITLE
ffprobe is only executable by owner

### ISSUE THREAD

**Issue by patsoffice** [HaveAGitGat/Tdarr#1064]
**Describe the bug**
The tdarr node's distribution has the ffprobe binary only executable by owner. That means that if tdarr node is installed by root but runs as a non-root user, it can't execute ffprobe.

**To Reproduce**
Grabbing the latest Tdarr_Node ZIP file and extracting the contents:

root@tdarr-node-151:/tmp/node# wget https://f000.backblazeb2.com/file/tdarrs/versions/2.24.05/linux_x64/Tdarr_Node.zip
root@tdarr-node-151:/tmp# mkdir node
root@tdarr-node-151:/tmp# cd node/
root@tdarr-node-151:/tmp/node# unzip -q ../Tdarr_Node.zip

Listing the ffprobe binary:

root@tdarr-node-151:/tmp/node# ls -l ./node_modules/@ffprobe-installer/linux-x64/ffprobe
-rwxr--r-- 1 root root 78926144 Aug 22 12:24 ./node_modules/@ffprobe-installer/linux-x64/ffprobe

**Expected behavior**
The permissions for this file should be 755, not 744.

**Screenshots**
N/A

**Please provide the following information:**
This has only been checked on Linux but may also affect other platforms.

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
I don't think that's quite right. If I create a non-root testuser I can unzip and run it fine as that user.

```
unzip -q ../Tdarr_Node.zip

ls -l ./node_modules/@ffprobe-installer/linux-x64/ffprobe
-rwxr--r-- 1 testuser testuser 78926144 Aug 22 12:24 ./node_modules/@ffprobe-installer/linux-x64/ffprobe

 ./node_modules/@ffprobe-installer/linux-x64/ffprobe
ffprobe version N-66595-gc2b38619c0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2023 the FFmpeg developers
```

It seems in your case you are unzipping as root and then running as non-root?

```
sudo unzip -q ../Tdarr_Node.zip

 ls -l ./node_modules/@ffprobe-installer/linux-x64/ffprobe
-rwxr--r-- 1 root root 78926144 Aug 22 12:24 ./node_modules/@ffprobe-installer/linux-x64/ffprobe

 ./node_modules/@ffprobe-installer/linux-x64/ffprobe
bash: ./node_modules/@ffprobe-installer/linux-x64/ffprobe: Permission denied
```

**Comment by patsoffice** [comment]
I updated the initial bug report and title to reflect the real issue.

**Comment by HaveAGitGat** [comment]
Sure I'll update that for next version

**Comment by HaveAGitGat** [comment]
Updated for next version.
