### ISSUE TITLE
Backup Zipping - Operation Percentage Calculations

### ISSUE THREAD

**Issue by LanceMcCarthy** [HaveAGitGat/Tdarr#1066]
## Describe the bug

I think there might have been a mistake in how the backup operation progress reporting is being done. Instead of using the total count, the right half of the progress completion rate is using a `currentItemIndex +1` value for the right half.

Here is a one-screenshot explanation :)

![image](https://github.com/user-attachments/assets/92c68d82-12af-4438-a61e-f89355e11f8e)

I suspect something like this pseudocode is happening by accident:

```csharp
var percentComplete = (currentWorkItemIndex / currentWorkItemIndex + 1 ) * 100;
```

If you can show me where this code is, I'm happy to open a pull request if you don't have time to work on it right now.

## To Reproduce
Update to v2.24.05 and observe the backup operation progress reporter.

## Expected behavior
The right half of the operation should be the total number of items to work on, so that the "percent complete" is accurate. Pseudo code again:

```csharp
var percentComplete = (currentWorkItemIndex / totalItemCount - 1 ) * 100;
```

## System Info
 - OS: Windows 11
 - Browser: n/a -> this occurs in the tray app window (WPF?)
 - Version:  v2.24.05

**Comment by HaveAGitGat** [comment]
It’s just entries processed/total where total is the total files found so far. It’s the way `archiver` does it as it’s more performant to do it that way. It could take a few minutes to find and count all the files to be zipped (e.g. on a slow HDD with thousands of sub/directories) so it’s quicker for it to just process files as it finds them, I assume that’s why they did it that way.

**Comment by LanceMcCarthy** [comment]
Ah, okay, that explains the +1, it's all incremental. Maybe I guess my suggestion then would to be to just remove the % column. It makes no sense in this context because it will show 99% complete even though it might only be 5% completed.

Thanks for following up.

**Comment by HaveAGitGat** [comment]
Sure I'll just change it to found: x, processed: x.

I assume that was the pre-migration backup? Once the migration is completed, the backup only zips up relatively few files so the per-file status is less significant.

**Comment by LanceMcCarthy** [comment]
Ah, sorry, I didn't realize this was a migration operation or I would have added that in the initial message.

Yes, this is after applying the latest update, 2.24.05 (I think my previous version was 2.20.01)
