### ISSUE TITLE
Flow editor plugin popup dialog should be modal - data loss bug

### ISSUE THREAD

**Issue by rgreen83** [HaveAGitGat/Tdarr#1067]
**Describe the bug**

When you are on the flow editing page and double click a plugin to bring up the dialog for editing it, the dialog doesn't capture all input - even when you are in a text box. 

**To Reproduce**

The main issue is that when typing in the text box the delete key is not captured and instead is passed to the underlying page thus deleting the plugin you are working on. You could then see the expected save changes button, since you opened the plugin to edit it and thus expect to have a change to save, you have just committed the deletion of that plugin from the flow. This is likely to be noticed in a small simple flow, but on a larger complicated one this could be unnoticed and perhaps not even for some time and would be frustrating until one figures out why their flow stopped working.

**Expected behavior**

IMHO the dialog should be modal and capture all normal keyboard input upon opening as capturing only when inside text box would be insufficient as there would still be a chance of deleting a plugin by accident. Even less if captured when the dialog is open but you have not selected a text box yet, for example backspace will also delete your plugin in this instance (luckily backspace is captured when inside text box).

OS: Win11
Browser: chrome
Version: 2.24.05

**Comment by HaveAGitGat** [comment]
Updated for next version ty
