### ISSUE TITLE
Question / Custom Plugin : Handbrake Preset 'Custom'

### ISSUE THREAD

**Issue by Nonobis** [HaveAGitGat/Tdarr#107]
Hello,

How and Where put a custom preset exported as json ?
I have tried with this syntax ... but it's not working. I am on unraid
My json is in "Local Plugins" template folder ..

response.preset = '--preset-import-file "./Custom_MULTI.json" -Z "H_265_MKV_MULTI" --all-audio --all-subtitles -e nvenc_h265'

Thanks

**Comment by HaveAGitGat** [comment]
Hi, you need to put the full path to the json file.

The plugins are inside the Tdarr user documents folder /home/Tdarr/Documents

`response.preset = '--preset-import-file "/home/Tdarr/Documents/Tdarr/Plugins/Local/Custom_MULTI.json" -Z "H_265_MKV_MULTI" --all-audio --all-subtitles -e nvenc_h265'`


Hope that helps
