### ISSUE TITLE
Alpine linux node not starting

### ISSUE THREAD

**Issue by journeym** [HaveAGitGat/Tdarr#1070]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
I've been experimenting with alpine to setup dedicated node.
For now im stuck on this error Unable to find Tdarr main.js file

**To Reproduce**
Install alpine 
apk add libc6-compat
start updater
run Node from console

**Expected behavior**
Node should start

**Screenshots**
![image](https://github.com/user-attachments/assets/5dfe9aed-c187-4b91-a1c3-2450ef17de26)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

This is a clean install, configs are default, no logs written

 - OS: 
3.19.2
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.2
PRETTY_NAME="Alpine Linux v3.19"
 - Browser -
 - Version latest

**Additional context**

**Comment by journeym** [comment]
ok so it seems i need some sort of dependencies list for alpine, i searched the issues here and was unable to find anything.

**Comment by journeym** [comment]
It's even worse for a clean alpine docker container
![image](https://github.com/user-attachments/assets/58a907ba-3742-46a1-a35b-64722cf30457)

**Comment by HaveAGitGat** [comment]
Why not just run the standard Tdarr docker container using Alpine docker?

Quite a few issues with trying to run on Alpine such as the one you have or if you install nodejs in the alpine image you can then run `node ./srcug/main.js` but you'll get further errors from other dependencies:

```
 [INFO] Tdarr_Server - Initializing DB
Segmentation fault (core dumped)
```

**Comment by HaveAGitGat** [comment]
I'm not sure it's possible run on Alpine linux due to dependencies not supporting it (or a bunch of extra stuff may be needed, not sure what), so best to run the normal docker image when using Alpine. If anyone finds out what's needed then feel free to update here. Working fine on ubuntu, arch, mint etc

**Comment by c-harris** [comment]
i know you closed it, but the only other broken dep was sqlite3, after updating/rebuilding the node_module. I was able to get it running on alpine 3.20
