### ISSUE TITLE
Unraid Backup/Restore Appdata backups killing Tdarr internal node connections?

### ISSUE THREAD

**Issue by dbaggett262** [HaveAGitGat/Tdarr#1073]
For the past couple of months now, after my weekly overnight Unraid appdata backups, the Tdarr docker gets restarted after it's backed up as it should, but can no longer find the internal node to connect to. I've tried manually setting the version tag to several versions (I usually don't have a version tag set, as I want the latest version installed on updates), including 'latest', but I had to go back to 2.23.01 to get things working again.

[Tdarr_Node_Log.txt](https://github.com/user-attachments/files/16852778/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/user-attachments/files/16852779/Tdarr_Server_Log.txt)

 - OS: Unraid 6.12.13

**Comment by dbaggett262** [comment]
I spoke too soon... yeah, I got Tdarr back up on 2.23.01, but all of my settings were back to default, even my Tdarr Pro key wasn't loaded. Luckily, going through my backups, I was able to restore my last 2.23.01 backup from 8/12 and got everything back more-or-less how it was yesterday; the only thing is that I had to rescan my libraries and Tdarr is going through a few hundred files that had been previously handed between the 12th and yesterday, but it's not having to recode them.

**Comment by HaveAGitGat** [comment]
`2.24.01` only came out about 3 weeks ago so if it's been happening for a couple of months then it wouldn't be that, and yeah `2.24.01` has a large data migration so if you downgrade to `2.23.01` then none of the data will load.

Have you verified that both the node and server are running when the container has restarted? Could be that the restart config is not starting both.

**Comment by dbaggett262** [comment]
> `2.24.01` only came out about 3 weeks ago so if it's been happening for a couple of months then it wouldn't be that, and yeah `2.24.01` has a large data migration so if you downgrade to `2.23.01` then none of the data will load.
> 
> Have you verified that both the node and server are running when the container has restarted? Could be that the restart config is not starting both.

Thing is, I've been having that issue since before 2.24.01; trying to remember back to July/the beginning of August and what I had to do to get things working again, but I do believe that, even back that far, 2.23.01 is the most current version where I didn't have the issue after an Unraid backup.

**Comment by HaveAGitGat** [comment]
Btw it's the node that connects to the server, not vice versa.

```
[2024-09-03T12:26:30.656] [INFO] Tdarr_Node - Node connected & registered
[2024-09-03T12:26:30.861] [INFO] Tdarr_Node - Downloading plugins from server
```

Seems the node connected fine from the node log, or is that timestamp much older? 

If you check the unraid container logs live you should be able to see if they're both running as they'll both be producing logs right?

Can also run `docker ps` to get the container id and then run `docker exec -it idxxx bash` to open a terminal in the container and then run `top` to see what's running.

```
    260 abc       20   0   11.0g 149464  46848 S   1.7   1.9   1:28.58 Tdarr_Server                                                                          
    262 abc       20   0  794180  82304  38528 S   0.7   1.0   0:16.37 Tdarr_Node   
```

**Comment by dbaggett262** [comment]
> ```
> 24-09-03T12:26:30.656] [INFO] Tdarr_Node - Node connected & registered
> [2024-09-03T12:26:30.861] [INFO] Tdarr_Node - Downloading plugins from server
> ```
> 
> 
>     
>   
> 
> Seems the node connected fine from the node log, or is that timestamp much older?

Those particular timestamps are after the last time I forced the 2.23.01 install (I did it a couple of times, in addition to trying other versions between 2.23.01 and 2.24.01) and I was able to get back into the GUI, right before posting this bug report.

**Comment by HaveAGitGat** [comment]
Try `2.25.01` and reopen if you still have this issue ty
