### ISSUE TITLE
tdarr dependency on libtesseract4 which is obsolete and no longer exists in current stable debian or derivatives. who all use libtesseract5 instead

### ISSUE THREAD

**Issue by taltamir** [HaveAGitGat/Tdarr#1076]
**Describe the bug**
tdarr does not work with libtesseract5.
it requires libtesseract4 which has been obsoleted and even outright deleted from the app repos of debian and its child distros.

I initially reported this as the far more mild issue which is:
tdarr automatic configuration of dependencies will automatically attempt to locate and load `libtesseract.so.4` instead of `libtesseract.so`
however, manually configuring it to locate either `libtesseract.so` or `libtesseract.so.5` causes it to fail due to being incompatible with that version.

**original bug report**
when installing tdarr node as per instructions found here:
https://docs.tdarr.io/docs/installation/windows-linux-macos

you can leave the paths blank (at least on linux) for the locations of the optional tools and it will automatically find all of them.
except for libtesseract which will give the following error:
```
[2024-09-09T13:33:33.139] [WARN] Tdarr_Node - Scanner test 4: CCExtractor not working:"/home/t/apps/tdarr/tdarr/Tdarr_Node/assets/app/ccextractor/ccextractor: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory\n" 
CCExtractor is only used to detect closed captions in video files. If you are not needing to detect closed captions, you can ignore this message.
```
this is because it is looking for an outdated version.

The instructions say to use
`sudo apt-get install libtesseract-dev (Optional - if wanting to use CCExtractor to check files for closed captions)`
this creates the files:
```
/usr/lib/x86_64-linux-gnu/libtesseract.so
/usr/lib/x86_64-linux-gnu/libtesseract.so.5
/usr/lib/x86_64-linux-gnu/libtesseract.so.5.0.3
```
The node however is trying and failing to locate `libtesseract.so.4` which is an outdated version.

I believe that it should be aiming for `libtesseract.so` without a version number.

**To Reproduce**
1. use updater file to download latest version of tdarr node
4. use ``sudo apt-get install libtesseract-dev`
5. configure IP and port of server
6. run tdarr node

**Expected behavior**
locate version 5 of tesseract. instead of failing to locate version 4.

**Please provide the following information:**
 - OS: LMDE6 (linux mint debian edition 6)
 - Browser: N/A
 - Version: 2.24.05

[Tdarr_Node_Config.json](https://github.com/user-attachments/files/16935191/Tdarr_Node_Config.json)
[Tdarr_Node_Log.txt](https://github.com/user-attachments/files/16935192/Tdarr_Node_Log.txt)

**Comment by taltamir** [comment]
the config file is a bit off.
as it automatically deletes the line
`"ccextractorPath": "",`
from the config file when it fails to find that path.

**Comment by taltamir** [comment]
oddly enough. specifying the exact path of tesseract5 gives this error:
`[2024-09-09T14:17:18.144] [WARN] Tdarr_Node - Scanner test 4: CCExtractor not working:"Unable to run CCExtractor exit code 1" `
so, maybe the issue is not just not finding v5. but also not being compatible with it?

Looking at debian packages:
https://packages.debian.org/buster/libtesseract4
https://packages.debian.org/stable/libtesseract5
https://packages.debian.org/stable/libtesseract-dev

the current stable version (bookworm) simply does not have libtesseract4 anymore. it only has v5. and I am not seeing a way to install v4 on it.

**Comment by taltamir** [comment]
> Hi there
> 
> you should be able to install it with this command from the backports:
> 
> apt install -t bookworm-backports libtesseract-dev=lts-4

Thank you. this does not seem to work. saying it is not found.

**Comment by dennix85** [comment]
i saw that it isnt in the backports i removed the comment so others dont get confused 


did you try to build it from source ?

**Comment by taltamir** [comment]
> https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.1
> 
> you can find here the latest 4 version

thank you. the latest v4 source code is actually:
https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.3

I have not tried compiling it from source yet... I will look into it as a possible workaround for now.

**Comment by HaveAGitGat** [comment]
Working fine in the Docker container:
```
[INFO] Tdarr_Server - Scanner test 4: CCExtractor working
```

CCExtractor is a 3rd party application: https://github.com/CCExtractor/ccextractor

So for any questions on compatibility/deps etc would need to ask on their as they handle that. Tdarr itself does not "try to find" `libtesseract`, it's just executing CCExtractor which is then resulting in that error on your machine.

But yeah it's a bit of an odd project as the docs https://ccextractor.org/public/general/downloads/ say to check GitHub for the latest releases, but there haven't been any releases since December 2021, but there have been updates to the codebase.

**Comment by HaveAGitGat** [comment]
On `Ubuntu 22.04.5 LTS` installing `libtesseract-dev` is enough to run both the Docker and native package CCExtractor binaries.

**Comment by taltamir** [comment]
please reopen this this bug.

> On `Ubuntu 22.04.5 LTS` installing `libtesseract-dev` is enough to run both the Docker and native package CCExtractor binaries.

Ubuntu 22.04.05 is a _2 year old version of ubutuntu that has libtesseract 4._
Try using Ubuntu 24.04.1 LTS
you will find it only has libtesseract 5.
https://ubuntu.pkgs.org/24.04/ubuntu-universe-amd64/libtesseract-dev_5.3.4-1build5_amd64.deb.html

tdarr is not compatible with tesseract5 only with tesseract4.
This means tdarr ccextract can only work with older versions of linux.

**Comment by HaveAGitGat** [comment]
@taltamir have you tried building latest CCExtractor from source and seeing if it works with your OS version?

**Comment by dennix85** [comment]
Well i have setup a new ubuntu machine to do some more testing with arc gpu's.. 
I can confirm that installing ccextractor via apt in 24.04 works, and tdarr can use that binary if you really need the functionality. 
no complaints about tesseract or etc.. You need to add an extra line to your node or server config tho.

**Comment by HaveAGitGat** [comment]
Ok that's good so does this still need to be re-opened?

**Comment by taltamir** [comment]
> Ok that's good so does this still need to be re-opened?

After some thought, I think yes, but at a lower priority.

Rather than tdarr not being compatible with current libtesseract.
The actual issue is that tdarr is bundled with an outdated version of ccextractor, and it is said outdated ccextractor version is not compatible with current libtesseract.

The ccextractor that comes bundled with tdarr node in `/Tdarr_Node/assets/app/ccextractor` is outdated version that is not compatible with 2024 LTS release / debian 12 / various derivatives. It only works on 2022 LTS release

dennix85 presented a workaround. instead of trying futilely to get the bundled ccextractor to work, ignore or delete it and instead configure tdarr to use your OS' version of ccextractor from its repo.
I tested it and this workaround works. So it lowers the priority a lot.

But while this workaround is great. there is still the fact that by default node comes with a bundled nonfunctional (for current LTS) ccextractor and tries to use said nonfunction ccextractor.

Ideal solution:
update bundled ccextractor to latest stable version and also bundle it with the required libtesseract. that way it will work on all systems without any configuration.

this has the advantage of consistent ccextractor versions for all nodes / OS.

Non ideal but possible solutions:
1. just update the bundled ccextractor to latest stable version and nothing else.
this will fix 2024 LTS but probably break 2022 LTS.

2. just remove the bundled ccextractor. forcing the use of the system version instead.

3. just add documentation about this issue. with the solution:
if bundled ccextractor does not work, don't try to fix the missing dependencies.
instead install ccextractor from os repo and point tdarr at that version.

**Comment by jwmann** [comment]
I had this issue and solved it by installing my own ccextractor into Debian like suggested.

I also had issues getting the package from apt-get because there's technically no official package for `bookworm`
I found [this page](https://debian.pkgs.org/12/multimedia-main-amd64/ccextractor_0.94-dmo4_amd64.deb.html#download) which had the following instructions.

```
# 1. Add the following line to /etc/apt/sources.list:
deb http://www.deb-multimedia.org bookworm main

# 2. Update the package index:
sudo apt-get update -oAcquire::AllowInsecureRepositories=true

# 3. Install GPG key of the repository:
sudo apt-get install deb-multimedia-keyring

# 4. Install ccextractor deb package:
sudo apt-get install ccextractor
```

Once it was installed, I went into the configs as mentioned as updated the path for ccextractor to point to the new binary location (you can find that with `which ccextractor`)

**Comment by evansharp** [comment]
>You need to add an extra line to your node or server config tho.
...
> instead configure tdarr to use your OS' version of ccextractor from its repo
...
> I went into the configs as mentioned and updated the path for ccextractor
...

For those of us who got here from Google, could this issue end with a link to docs or instructions on which config value to change?

**Comment by dennix85** [comment]
"ccextractorPath": "ccextractor",
Or
 "ccextractorPath": "/your/path/to/ccextractor",

You add this to your node config and server config
