### ISSUE TITLE
Hold until a specified time

### ISSUE THREAD

**Issue by erviker** [HaveAGitGat/Tdarr#1079]
**Is your feature request related to a problem? Please describe.**
We like to hold all transcode to start at a specific time a day like everyday at 00.00 

**Describe the solution you'd like**
Option to do X amount of time like now or set cron style interval / every day at time

**Comment by HaveAGitGat** [comment]
Surely the library schedule option would be better suited for this use case?

**Comment by HaveAGitGat** [comment]
The library schedules and node schedules cover this use case so don't think this is needed.
