### ISSUE TITLE
Completed files being saved to folder names with missing characters

### ISSUE THREAD

**Issue by azcom** [HaveAGitGat/Tdarr#108]
Some folder names end up with part (a letter or a few letters) of the name missing from the start of them when the transcoded output files are written back to the source directory. I'm on Windows where every library source folder is a UNC network path, cache folder is local and F2F turned off. It first did it on my TV library when I was using F2F with a local output and would omit the first 4 characters from the folder name, but that doesn't appear to have happened since I have turned F2F off. Now it's happening on my Movies library but with F2F off anyway and only omitting the first character not 4 of them. For example 'Downton Abbey (2019)' as the original folder label ends up in a folder written out as 'ownton Abbey (2019)'.

This bug appears to be happening on every transcode from my 'Movie' library right now although those in my TV library are ok at this time.

I would expect the output file to be written back to the original folder where the source file had been located, overwriting it. As you can see in the screenshot below the original is deleted from the source folder and the new file (correctly named) placed in a new folder with the first character missing from the folder name.

![Tdarr_001_Source_and_Output](https://user-images.githubusercontent.com/1648100/70901591-00411280-1ff3-11ea-9886-729ad4260fba.PNG)
Source  and Output folders after transcode has completed.

![Tdarr_002_Movies_DB_Settings](https://user-images.githubusercontent.com/1648100/70901592-00411280-1ff3-11ea-9fa4-680c967af417.PNG)
Settings for the 'Movie' library as they show in the Database.

- OS: Windows 10
- Browser: Chrome
- Version: Beta 1.101

**Comment by HaveAGitGat** [comment]
Ok thanks I'll investigate this.

**Comment by azcom** [comment]
@HaveAGitGat 
Thanks, but I have not experienced this behaviour for a while as I have since removed some libraries and reset the database several times so cannot reproduce this currently.

**Comment by HaveAGitGat** [comment]
Ok great. Let me know if you encounter it again as I have had no other reports of this.
