### ISSUE TITLE
File path char length limit on Win 10 systems (Re:631)

### ISSUE THREAD

**Issue by quadcom** [HaveAGitGat/Tdarr#1082]
Server/Node: v2.25.01

After getting a Docker container on a Debian12 system up and running, I expanded with an external node on my Win10 workstation. I ran into issues with certain files, and the troubleshooting I did led me to find another GIT bug report on this issue from some time ago (https://github.com/HaveAGitGat/Tdarr/issues/631).

This is still an issue, not necessarily with Linux-based server/node installations but with Windows 10 systems running nodes. 

Windows 10 did add support for file paths longer than 260 characters. What they neglected to do was update explorer.exe to also support the now +32k chars limit. The Windows 10 explorer.exe is still limited to 260 characters. This includes folder characters, as the limit applies to the entire path of a file.

The Docker server/node running on Debian 12 works fine, pulling files from an Unraid share (also Linux) and replacing the files when processing is complete. The Windows system, however, fails for specific files, and there were no details in the log files that would explain why. I finally deduced that it was a file name char limit when I tried to create the file on the Unraid server through a mapped volume in the Windows workstation. It would not allow more than 247 chars in the file name.

This issue is 'apparently' resolved in Windows 11 as the explorer executable in Win11 is updated and can handle longer file paths.

I have to join the others that question the need for what appears to be superfluous chars in the file paths. I get that you would want to keep things organized. But that could be satisfied more simply. The node ID doesn't need to be six chars; you could use only three chars and have a suitable number of IDs. That is unless someone does consider trying to use more than 238,328 unique IDs that using three chars would provide. As far as nested folders are concerned, that could also be skipped, saving another 12 or so chars from the file path.

One frustrating part of my troubleshooting was loading the log for the failed items. The verbose mode fills the log files with a ton of repeated content. Loading the log would cause the browser (both FF and CH) to freeze. Eventually, it would wake up and show the log page only to immediately trigger a complete refresh of the browser window, thus clearing the log file display. A solution would be to write the log file in realtime to the cache DIR for that specific video on that specific node. It would also help if the log files contained simplified output rather than all the repeated content that takes up +90% of the log which doesn't contain anything of value.

In the meantime, the only workaround is to let the files fail and then at the end, disable the Windows node and have the Linux node process the remaining queue. It will result in the Windows node going through the entire process including transcoding the file only to fail at the end. So it's doing a lot of work it doesn't need to do. Currently I see no way of filtering out files that would fail the char limit from being processed or assigning them to a specific node (the non-win node in this case).

**Comment by HaveAGitGat** [comment]
Moving under here: https://github.com/HaveAGitGat/Tdarr/issues/938
