### ISSUE TITLE
resolution sort inaccurate

### ISSUE THREAD

**Issue by root1657** [HaveAGitGat/Tdarr#1085]
Sorting the queue on the resolution column results in inaccurate sort. Seemingly it simple sorts based on the first numbers, but doesn't understand the missing leading zeros, etc. Expected behavior of that sort should be to put them in order of least to greatest (or vice versa) resolution rather than a number sort.

![Capture](https://github.com/user-attachments/assets/3bed3a8a-9d38-4017-8a75-f88fcd82c32a)

**Comment by HaveAGitGat** [comment]
If you use the `Sort queue by` then it should work fine
![image](https://github.com/user-attachments/assets/456a8d09-1044-4bef-85a3-07d121dfe2af)

The table column sort works a bit differently but will fix that when I get time ty

**Comment by HaveAGitGat** [comment]
Fixed for next version: 
![image](https://github.com/user-attachments/assets/589d9afc-53d8-403e-ad8a-843ff830ef06)

**Comment by root1657** [comment]
Thank you Sir, look forward to the fix! (knew about the queue sort, needed the column sort to figure out what to bump and what to replace ahead of time) Great product so far, happy to support!
