### ISSUE TITLE
Stats -> Worker Verdict History hover text

### ISSUE THREAD

**Issue by Rycochet** [HaveAGitGat/Tdarr#1088]
Looking at the Stats page it's nice to see how much work has been done, but the hover *total* text isn't the most useful:

<img width="161" alt="image" src="https://github.com/user-attachments/assets/f7809b78-e3ea-4d52-b86e-1571dbbea97b">

The problem with this is that a file can be counted twice in the total, once as a Healthcheck and once as a Transcode.

I feel it would be somewhat more useful to have them in order (Healthcheck before Transcode) and with two separate totals, something like this:

```
2024/09/22 03:00

Healthcheck Success     540
Healthcheck Error       0
Healthcheck Total       540

Transcode Success       700
Transcode Error         168
Transcode Not Required  2
Transcode Total         870

Total                   1410
```

For my use-case I'm after a (very) rough estimate of how long certain libraries will take to complete, while Healthchecks are extremely quick and not relevant to that 🙂

**Comment by HaveAGitGat** [comment]
Added for next version:
![image](https://github.com/user-attachments/assets/9d5f9279-6922-4cae-bc18-214acba3eed1)
