### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by phyzical** [HaveAGitGat/Tdarr#1090]
Hey, just wondering why no changelog is available 

Just working on improving my visibility of what i'm pushing out when an update happens, my extractor uses the following to find changelog's
* releases changelog
* tag changelog
* changelog file

This is the first project i've come across that doesn't use any of the 3 above?

Just wondering is one of the 3 above could be supported? 

thanks!

**Comment by HaveAGitGat** [comment]
The release info is found below downloads https://home.tdarr.io/download/ or can use a  post to https://api.tdarr.io/api/v2/versions

`curl -X POST https://api.tdarr.io/api/v2/versions`

Let me know if doesn't work for you

**Comment by phyzical** [comment]
Thanks, thatll do the job.

**Comment by HaveAGitGat** [comment]
Great :)

**Comment by phyzical** [comment]
@HaveAGitGat just got around to having a crack, if you wanted to add some logic for your private workflow to update inwards towards the public facing one the following command should do the job

```
curl -X POST https://api.tdarr.io/api/v2/versions | jq -r 'del(.latest) | to_entries | map("## \(.key) - \(.value.date)\n\n\(.value.notes | map("- \(. | gsub("\n"; " "))") | join("\n"))\n") | join("\n\n")' > changelog.md 
```
results in the following 
![image](https://github.com/user-attachments/assets/6318ef41-8df3-467e-a99c-13acf4db85f0)
