### ISSUE TITLE
Classic Plugin: Remove Non English Audio - Nothing Happens.

### ISSUE THREAD

**Issue by linkthepirate** [HaveAGitGat/Tdarr#1091]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**

Trying to set up this flow to remove non-english audio but (unlike my other known working good flows), it never does anything. Never comes up in healthcheck queue or anything. Is there something I'm missing? All the checks seem to be like codec related or some other technical thing. 

**To Reproduce**

Input file > ffmpeg begin > classic plugin: tdarr_Plugin_sdf5_Thierrrry_Remove_non_english_audio > ffmpeg: execute > Replace original

**Expected behavior**

File jumps straight into the ffmpeg, removes any non-english track, resolves.

**Screenshots**

![Screenshot_20240929_075341](https://github.com/user-attachments/assets/f1329f68-64a9-43d8-93f2-e8f46a31cbf7)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Standard shipped files for Docker, I've not touched.

- Job reports: https://docs.tdarr.io/docs/other/job-reports
n/a

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.txt](https://github.com/user-attachments/files/17179305/Tdarr_Server_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
n/a

 - OS: [e.g. Linux] Docker
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 2.00.00] 2.25.01

**Additional context**
![Screenshot_20240929_074456](https://github.com/user-attachments/assets/6f9ffb26-a9c1-451a-883e-548f5d516b4a)
![Screenshot_20240929_074507](https://github.com/user-attachments/assets/ab11698c-b1eb-4c8d-bc1f-d26cfdc2801e)
![Screenshot_20240929_075341](https://github.com/user-attachments/assets/e13e2b40-cbbb-4aee-961a-2a017ba18621)

**Comment by supersnellehenk** [comment]
Did you check the succeeded or errored queues as well? It has probably ran already.

For a classic plugin, you don't need the ffmpeg begin & execute blocks around it. So just input, classic plugin, replace original.

**Comment by linkthepirate** [comment]
> Did you check the succeeded or errored queues as well? It has probably ran already.
> 
> For a classic plugin, you don't need the ffmpeg begin & execute blocks around it. So just input, classic plugin, replace original.

I will remove those - but yes I've checked them all.

**Comment by linkthepirate** [comment]
It's like it just doesn't see it: 
![image](https://github.com/user-attachments/assets/c173c269-493c-40b0-9a75-9954faa7d4d9)
![image](https://github.com/user-attachments/assets/fa537401-e700-4d27-8e25-621510019603)

**Comment by HaveAGitGat** [comment]
Do you mean folders with hyphens in them aren't scanned? 

![image](https://github.com/user-attachments/assets/bb69239b-bd86-4be4-a045-4af3152f47c1)

Working fine for me here with `-`. Maybe it was a weird type of hyphen?

**Comment by HaveAGitGat** [comment]
Feel free to reopen with job report if it happens again ty.
