### ISSUE TITLE
AMD GPU docker compose 

### ISSUE THREAD

**Issue by icf20** [HaveAGitGat/Tdarr#1092]
https://docs.tdarr.io/docs/installation/docker/run-compose the documentation dont provide any example for AMD GPU

**Comment by dennix85** [comment]
Should be same process as intel gpu's 
if using docker run you can add: 
--device=/dev/dri
if using compose 
/dev/dri:/dev/dri

some gpu's also require: 
--device=/dev/kfd

**Comment by icf20** [comment]
> Should be same process as intel gpu's if using docker run you can add: --device=/dev/dri if using compose /dev/dri:/dev/dri
> 
> some gpu's also require: --device=/dev/kfd
> 
> The example compose file should do fine with all brands (Intel, AMD, Nvidia) As long as you have the correct drivers etc setup on your host
> 
> Do note, quality can be poor with amd card's

amd drive dont exist

**Comment by dennix85** [comment]
what do you mean amd driver dont exist?

**Comment by icf20** [comment]
replacing the nvidia with amd give a error that amd driver dont exist, for that reason i ask for a amd example

**Comment by dennix85** [comment]
the compose file as is should work normally 
as long as the gpu is visible, and accessible and useable on the host should work with the gpu, 
might wanna try adding: 
/dev/kfd:/dev/kfd

What GPU is used btw ?

**Comment by dennix85** [comment]
tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/London
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=MyExternalNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6

    volumes:
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media
      - /transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
      
 This should be all without the nvidia stuff

**Comment by icf20** [comment]
i copied the example compose and replaced nvidia with amd


deploy:
      resources:
        reservations:
          devices:
          - driver: _amd_
            count: all
            capabilities: [gpu]

**Comment by dennix85** [comment]
so you have it working now ?

**Comment by icf20** [comment]
> so you have it working now ?

i am strugling to check if it uses the GPU or not

**Comment by dennix85** [comment]
try vainfo inside the container 
if it shows values its good 
if it errors out, then its not working yet

**Comment by icf20** [comment]
> try vainfo inside the container
```

VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
is there any way to convert all file to VP9 ?

**Comment by dennix85** [comment]
Yes you can with custom arguments for ffmpeg, handbrake, or create an custom Plugin that does vp9

**Comment by HaveAGitGat** [comment]
If you go on the help tab and type `-encoders` it will show the encoders available. Can then use `Tdarr_Plugin_00td_action_handbrake_ffmpeg_custom` plugin to run a custom command like `<io>-map 0 -c copy -c:v libx265`
