### ISSUE TITLE
Is it possible to specify loction of appsDir?

### ISSUE THREAD

**Issue by plinss** [HaveAGitGat/Tdarr#1094]
On Linux machines it's common to install software on a read-only partition, e.g. `/usr/lib/tdarr-server` and have applications store their data in a different partition, e.g. `/var/lib/tdarr-server`. Unfortunately, Tdarr identifies its `appsDir` based on its install location (one level higher, in this case `/usr/lib` and creates `configs`, `logs` there, and a `Tdarr` directory next to the binary.

It would be helpful if one could specify the location of the `appsDir` via a command-line argument or environment variable.

Ideally the location of the configuration and logs could also be specified, on Linux those would typically be in `/etc/tdarr-server` and `/var/log/tdarr-server`. 

One solution would be to add a command-line argument or environment variable to specify the full path of the config file, and specify the location of the logs and data directories in the config file. Alternatively, the data storage directory could be based on the home directory of the user Tdarr is running as (which will typically be `/var/lib/tdarr-server` on Linux).

(The server also appears to write a 'last-run' file to the config dir, this should be stored elsewhere, like in the appsDir.) 

--

FWIW, my current work-around is to install the server in `/usr/lib/tdarr-server/bin` and create links `/usr/lib/tdarr-server/configs` -> `/etc/tdarr-server`, `/usr/lib/tdarr-server/logs` -> `/var/log/tdarr-server`, and `/usr/lib/tdarr-server/bin/Tdarr` -> `/var/lib/tdarr-server`.

**Comment by HaveAGitGat** [comment]
You can use env variable `rootDataPath` which should work. Was only added in the last version so was still checking some things with it. Let me know if works for you, worked for me on a read only folder. The appsDir will always be the parent folder of the apps location so that won't change.

**Comment by plinss** [comment]
The `rootDataPath` works well for the server (it still expects the configs and logs directory to be under that path, but that can be dealt with via links). 

However the node still tries to create a `configs` directory in the `appsDir` (though it does eventually load the config from `rootDataPath/configs` and then it attempts to download plugins into `appsDir/node/assets/app/plugins`
