### ISSUE TITLE
Global VARS not processed in certain situations

### ISSUE THREAD

**Issue by quadcom** [HaveAGitGat/Tdarr#1095]
While this bug does reference plugins/steps. I suspect this is a processing issue and not specifically a plugin problem.

v2.26.01

I have added some global VARS (this may apply to other VAR types as well). While I can reference these in some flow steps, such as setting the -qp rate in the ffmpegCommandSetVideoEncoder step, the VAR is not referenced in other situations.

![image](https://github.com/user-attachments/assets/cc6b3100-4d52-423c-ab59-28b008f2507f)

Here is the SetVideoEncoder
![image](https://github.com/user-attachments/assets/943026aa-af73-487b-873b-37512fc77898)

The steps show the VAR being processed, and it is translated correctly into the FFMPEG string
![image](https://github.com/user-attachments/assets/8c253675-92ad-47bc-9323-df21f177f9dd)
![image](https://github.com/user-attachments/assets/adab5a7b-fe67-4f6e-8545-9236f8b7e1e9)

I then have another flow step to push metadata into the 0 stream to note the same VAR
![image](https://github.com/user-attachments/assets/4d2412aa-159b-4f98-bed3-3a2e5ce35879)

The resulting metadata string does not have the translated VAR value. The system is doing something as it removes the VAR identification string; it's just not replacing it with the assigned value.
![image](https://github.com/user-attachments/assets/3305f7e0-832d-4721-b2a4-7bc9aaa66a73)

**Comment by supersnellehenk** [comment]
I believe casing is important, and your variable is called `1080-CQ`. So try changing it from `1080-cq` to `1080-CQ`

**Comment by quadcom** [comment]
Good catch! I thought I had copy/paste the var but alas, it was a different case.

Changed those, I keep an eye on it going forward and update the report.

**Comment by quadcom** [comment]
Yup, stung by the case bug!
