### ISSUE TITLE
[Feature request] Enable Server-to-Client File Transfer to Simplify Setup

### ISSUE THREAD

**Issue by stephane-archer** [HaveAGitGat/Tdarr#1099]
Currently, both the Tdarr server and all connected clients must have direct access to the media files. This setup requires configuring "Path translators" to ensure the server can properly instruct the clients on file locations, especially in environments with different file systems or operating systems.

I propose allowing the Tdarr server to handle file transfers by sending the media files directly to the clients. This change would mean only the server needs access to the media files, eliminating the need for configuring path translators on the clients and simplifying the overall setup process.

This also removes the need for mounting media drives on each client

Thank you for considering this improvement.

**Comment by stephane-archer** [comment]
This also removes the need for mounting media drives on each client

**Comment by stephane-archer** [comment]
> From a network transfer point of view, using a system where all the Tdarr devices can access the same network shares is far more efficient and will save a lot of time when processing large libraries.

I see...

**Comment by HaveAGitGat** [comment]
Hi @stephane-archer , this is actually possible with a new node type I've been working on that will be in the next version, `Unmapped Nodes` for Tdarr Pro members.

https://docs.tdarr.io/docs/nodes/nodes#unmapped

Flow tutorial ` Chapter 8: Unmapped Nodes`.

It's working well for me but I'm checking checking feedback with others. Can try it with:

````
docker.io/haveagitgat/tdarr_acc:dev_2.27.01_2024_10_17T02_06_08z
docker.io/haveagitgat/tdarr_node_acc:dev_2.27.01_2024_10_17T02_06_08z

{
    "win32_x64": {
      "Tdarr_Server": "https://storage.tdarr.io/dev/versions/2.27.01/win32_x64/Tdarr_Server_2024_10_17T02_06_08z.zip",
      "Tdarr_Node": "https://storage.tdarr.io/dev/versions/2.27.01/win32_x64/Tdarr_Node_2024_10_17T02_06_08z.zip"
    },
    "linux_x64": {
      "Tdarr_Server": "https://storage.tdarr.io/dev/versions/2.27.01/linux_x64/Tdarr_Server_2024_10_17T02_06_08z.zip",
      "Tdarr_Node": "https://storage.tdarr.io/dev/versions/2.27.01/linux_x64/Tdarr_Node_2024_10_17T02_06_08z.zip"
    },
    "linux_arm64": {
      "Tdarr_Server": "https://storage.tdarr.io/dev/versions/2.27.01/linux_arm64/Tdarr_Server_2024_10_17T02_06_08z.zip",
      "Tdarr_Node": "https://storage.tdarr.io/dev/versions/2.27.01/linux_arm64/Tdarr_Node_2024_10_17T02_06_08z.zip"
    },
    "darwin_x64": {
      "Tdarr_Server": "https://storage.tdarr.io/dev/versions/2.27.01/darwin_x64/Tdarr_Server_2024_10_17T02_06_08z.zip",
      "Tdarr_Node": "https://storage.tdarr.io/dev/versions/2.27.01/darwin_x64/Tdarr_Node_2024_10_17T02_06_08z.zip"
    },
    "darwin_arm64": {
      "Tdarr_Server": "https://storage.tdarr.io/dev/versions/2.27.01/darwin_arm64/Tdarr_Server_2024_10_17T02_06_08z.zip",
      "Tdarr_Node": "https://storage.tdarr.io/dev/versions/2.27.01/darwin_arm64/Tdarr_Node_2024_10_17T02_06_08z.zip"
    }
  }

```

**Comment by HaveAGitGat** [comment]
2.27.01 released
