### ISSUE TITLE
Feature Request - Pause Library 

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#11]
Hey there,

I'm wondering if it's possible to have an option to basically put an entire library on PAUSE. I'd like to NOT have to delete the library if I don't want it running right then for whatever specific reason but I'd also like to simply pause it. 

For now, I've been using the schedule to hack this and forcing the time to 01 to 02 only, but a pause would be easier and more logical.

**Comment by marshalleq** [comment]
Yes, this would be great, and I'm sure easy to implement.

**Comment by HaveAGitGat** [comment]
Added in 1.002
