### ISSUE TITLE
[Feature request] create video proxy with Tdarr

### ISSUE THREAD

**Issue by stephane-archer** [HaveAGitGat/Tdarr#1100]
could Tdarr automatically create a "Proxy" directory (if it doesn’t already exist) in the same location as the source media and output the transcoded files there? This would keep the original media and the transcoded versions organized in a consistent structure.

**Comment by HaveAGitGat** [comment]
Hi yes you can create a flow to do that. Check if the proxy file exists using `Check File Exists`, if not, transcode the file and move the result to where the proxy should be.
