### ISSUE TITLE
Sort on Old size column does not work

### ISSUE THREAD

**Issue by wnypoker** [HaveAGitGat/Tdarr#1102]
**Describe the bug**
Sort on Old size column does not work, see screenshot

**To Reproduce**
sort the Transcode: Success/Not Required  queue based on Old file size

**Expected behavior**
list of files should be displayed in requested sort order

**Screenshots**
https://i.imgur.com/pHS5Vaf.png

 - OS: Linux
 - Browser all browsers
 - Version 2.26.01

**Comment by HaveAGitGat** [comment]
Hi, this option only applies if the file has been transcoded. If you're looking to explore existing file size then it can be done on the search tab, have your tried there?

**Comment by HaveAGitGat** [comment]
Updated for next version:
![image](https://github.com/user-attachments/assets/de368272-be42-429e-9fd7-d6a17eecc031)
