### ISSUE TITLE
Tdarr_Updater option to match a specific server version for nodes (input IP of server to check).

### ISSUE THREAD

**Issue by taltamir** [HaveAGitGat/Tdarr#1104]
Tdarr_Updater settings are kept in `Tdarr_Updater_Config.json`
in it you can configure the target node version via `requiredVersion` which can be set to either `"latest"` or a specific numerical version such as, for example `"2.26.01"`.

latest is problematic because the server might not be the latest version. For example currently the version on truenas docker image is `"2.26.01"` while the latest version is `"2.27.02"`. All my systems upgraded to `"2.27.02"` and then refused to work due to version mismatch between node and server. So I had to go and manually downgrade all of them to  `"2.26.01"`. And when docker will update I will need to manually go through every system and adjust it to the current version.

**Describe the solution you'd like**

Add the following possible values to `requiredVersion` for the node:
1. `localserver` which uses the same version value as the one being downloaded for server by tdarr_updater
2. `serverip` which consults the input from an additional two lines for `serverToMatchIP` and `serverToMatchPort`.

If using `localserver` just grab the value from the same json.
If using `serverip` then connect to the server at that ip and ask it what version it is, then use that version as the target version for node update.

========
Here is an example of my current `Tdarr_Updater_Config.json` on a node
```
{
  "platform_arch": "default",
  "modules": {
    "Tdarr_Node": {
      "enabled": true,
      "requiredVersion": "2.26.01",
      "currentVersion": "2.26.01"
    },
    "Tdarr_Server": {
      "enabled": false,
      "requiredVersion": "latest",
      "currentVersion": ""
    }
  }
}
```

Here is what I think it should be instead:
```
{
  "platform_arch": "default",
  "modules": {
    "Tdarr_Node": {
      "enabled": true,
      "requiredVersion": "serverip",
      "serverIP": "192.168.1.200",
      "serverPort": "9001",
      "currentVersion": "2.26.01"
    },
    "Tdarr_Server": {
      "enabled": false,
      "requiredVersion": "latest",
      "currentVersion": ""
    }
  }
}
```

**Comment by HaveAGitGat** [comment]
On the Options tab is `Auto update non-Docker nodes`. Non Docker nodes will automatically match the server they're trying to connect to https://docs.tdarr.io/docs/other/auto-updates

**Comment by taltamir** [comment]
> On the Options tab is `Auto update non-Docker nodes`. Non Docker nodes will automatically match the server they're trying to connect to https://docs.tdarr.io/docs/other/auto-updates

@HaveAGitGat

1. `Auto update non-Docker nodes` does not appear to actually work on my systems (mint 22. based on ubuntu noble)

2. even if it worked, it could cause an undesirable vacillation between versions if Updater is run automatically.

For example, every one of my node computers performs on startup:
step 1. run Tdarr_Updater
step 2. run Tdarr_Node

This would results in

> Tdarr_Updater Downloads and installs v27 node
> Tdarr_Node v27 Tries to connect to v26 server, is told to change version
> Tdarr_Node v27 Downloads and installs v26 node. then self terminates and runs node v26
> Tdarr_Node v26 connects to server v26.

On every reboot it would first upgrade to v27 and then downgrade to v26.

**Comment by HaveAGitGat** [comment]
Think I saw your reply somewhere but yeah there’s not need to run the updater yourself and then run the node. Just run the node and then it will run the updater itself if need be.
