### ISSUE TITLE
Adjust Folder Scan Interval

### ISSUE THREAD

**Issue by ansuz07** [HaveAGitGat/Tdarr#111]
First and foremost - thank you for this.  This is a great addition to my stack and I'm loving it so far.

The one issue I've got is that I'm running Tdarr on a machine that is BM Ubuntu running Docker, with fstab mounts to my unRAID server (which houses my media).  Unfortunently, the folder scan feature is just murder on my unRAID box - I'm seeing 30% CPU usage in unRAID due to the frequent scanning.

Would it be possible to customize how frequent the folder scan runs so I can lower the CPU impact?  Once every 30 min would be more than frequent enough - I don't need Tdarr running real time.

Thanks in advance, whatever the answer might be :).

**Comment by HaveAGitGat** [comment]
Absolutely, I'll add this option in.

**Comment by HaveAGitGat** [comment]
Added in for 1.103 later this week. Option is under the library source settings.

![image](https://user-images.githubusercontent.com/43864057/72749744-c1cee280-3bb2-11ea-950f-bfe00189fcf6.png)
