### ISSUE TITLE
Tdarr seems to be using additional non-existent sub directory for output file

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#1118]
Recently transcodes have started failing. In looking into this I observed the following:

The transcode failed and I didn't see any obvious error - 
[XWbwdE4hGE-log.txt](https://github.com/user-attachments/files/17704536/XWbwdE4hGE-log.txt)

I run tdarr node in a docker container so I extracted the tdarr-ffmpeg command and entered the container to paste the command and see if any additional clues were output.

```
root@5912995323c8:/# tdarr-ffmpeg -c:v h264_cuvid -i "/Videos/Movies/The Game (1997).mp4" -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 1301k -minrate 910k -maxrate 1691k -bufsize 2603k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d "/tmp/The Game (1997)-TdarrCacheFile-oxAlAgbgL.mkv"
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
...
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2018-02-03T11:44:21.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
/tmp/tdarr-workDir2-XWbwdE4hGE/The Game (1997)-TdarrCacheFile-oxAlAgbgL.mkv: No such file or directory
```

Now, /tmp is normally the work directory that I have configured for tdarr to operate in but notice the additional subdirectory of tdarr-workDir2-XWbwdE4hGE. If I redo the command and remove that component the transcode works!

**To Reproduce**

Happens when I requeue the transcode. Seems to be happening on all files now.

**Expected behavior**

Transcode to succeed.

**Please provide the following information:**

[tdarr.conf.tar.gz](https://github.com/user-attachments/files/17704718/tdarr.conf.tar.gz)

 - OS: Synology DSM 7.2
 - Browser Brave
 - Version 2.27.02

**Comment by HaveAGitGat** [comment]
Tdarr automatically creates and cleans up the `workDir2` folder so you'd need to create that manually when running the command.

At this point Tdarr verifies the cache folder `/tmp/tdarr-workDir2-XWbwdE4hGE` exists:
```
2024-11-09T17:26:41.522Z XWbwdE4hGE:Node[Earth]:Worker[common-cow]:Checking files can be accessed
2024-11-09T17:26:41.523Z XWbwdE4hGE:Node[Earth]:Worker[common-cow]:Relevant paths can be accessed
```

The error in the log is:

```
2024-11-09T17:26:42.793Z [AVHWDeviceContext @ 0x56248aff49c0] cu->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
2024-11-09T17:26:42.793Z 
2024-11-09T17:26:42.793Z Stream mapping:
2024-11-09T17:26:42.793Z   Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))
2024-11-09T17:26:42.793Z   Stream #0:1 -> #0:1 (copy)
2024-11-09T17:26:42.793Z Error while opening decoder for input stream #0:0 : Generic error in an external library
```

So this error is to do with the container not being able to use the GPU for nvenc encoding, usually related to driver or container config.

**Comment by adefaria** [comment]
Hmmm, I was having problems with Nvidia drivers and the docker runtime for nvidia that have since been resolved. That may explain why this problem went away for me.
