### ISSUE TITLE
Run as Service/Background Process on Windows

### ISSUE THREAD

**Issue by Flippage** [HaveAGitGat/Tdarr#112]
Is it possible to run Tdarr as a service or background process on Windows 10?

When I launched Tdarr, I just have a CMD window sitting on the screen all the time. I use my server PC as my HTPC media player as well, so it'd be awesome if I could run this behind the scenes like Sonarr/Radarr.

Probably on your roadmap, but figured I'd ask anyway.

**Comment by HaveAGitGat** [comment]
Sure, I believe someone has written some steps to running it as a service. I'll have a look later today to see if I can find them and update this.

**Comment by HaveAGitGat** [comment]
It seems the steps I was referring to are for Linux. I'll need to come up with some new steps for Windows.

**Comment by HaveAGitGat** [comment]
Please see the following guide I've made for running as a service:

https://github.com/HaveAGitGat/Tdarr/wiki/Running-as-a-service-(Windows,-Linux,-macOS)

**Comment by Flippage** [comment]
Awesome. Thanks a lot. Looking forward to watching Tdarr progress.

**Comment by Flippage** [comment]
Hey @HaveAGitGat 

I tried the steps you posted and I got this error:
![image](https://user-images.githubusercontent.com/10948118/74097385-6c577700-4b5b-11ea-9bb5-1c233177a1ee.png)

Any idea how to fix? It doesn't create the Tdarr service at this stage.

**Comment by Flippage** [comment]
Nevermind, it's my fault.

I didn't download the JS files, but the webpage with the JS files linked on them.

Disregard. It's working fine with the proper JS files.

**Comment by Flippage** [comment]
Ok, after installing it as a service, when I access it through the web browser, either on the local machine or on LAN, it doesn't load correctly and none of the links work right.
![image](https://user-images.githubusercontent.com/10948118/74097944-0ae6d680-4b62-11ea-9e30-dd395072d5f8.png)

Clicking the links at the top just adds C:\ drive paths to the URL. Nothing loads on the page.

**Comment by HaveAGitGat** [comment]
Yeah some people have had issues with that method so I put the pm2 method first in the wiki:

https://github.com/HaveAGitGat/Tdarr/wiki/Running-as-a-service-(Windows,-Linux,-macOS)

Using pm2:

Download the pm2 config file and place it next to main.js in the 'Tdarr/Bundle' folder: https://github.com/HaveAGitGat/Tdarr/blob/master/ecosystem.config.js

Open a terminal in 'Tdarr/Bundle' and install pm2: npm install pm2 -g

Start Tdarr: pm2 start ecosystem.config.js

To stop Tdarr, run: pm2 stop Tdarr

Logs are stored inside .pm2\logs inside your home folder.

**Comment by Flippage** [comment]
I can only get through step 2 with that.

I installed pm2 with the command above, in my C:\tdarr\ folder, and then I can't run PM2 after that:
![image](https://user-images.githubusercontent.com/10948118/74098369-4932c480-4b67-11ea-9f80-5a65a4d1344c.png)

Any other ideas?

**Comment by HaveAGitGat** [comment]
Looks like you haven’t installed pm2 if that’s the case. What happens when you run:

`npm install pm2 -g`

You can run that command from anywhere.

**Comment by Flippage** [comment]
I definitely installed it. Not sure if it requires a full system reboot after installation?

That result was after running, but just to confirm:
![image](https://user-images.githubusercontent.com/10948118/74098584-fa3a5e80-4b69-11ea-890d-5940f30e23a4.png)

**Comment by HaveAGitGat** [comment]
Doesn’t normally require a restart but might be worth a shot. 

Else you need to find pm2.exe on your system and add it as a Windows path variable so it can be accessed from the terminal:
https://www.computerhope.com/issues/ch000549.htm

Then everything should work fine

**Comment by Flippage** [comment]
OK, I got it running by using VNC to install it as the primary admin account instead of via Remote Desktop.

I can load it via the browser now which is cool.

Next problem though is every 5 - 10 seconds, it spawns about 4 GIT windows briefly. That's not ideal as this is our Plex server which is hooked up to the TV and running Plex Media Player.

I can't have windows popping up every 5 seconds, my wife will kill me.

Thoughts? I may just be asking too much at the moment, and might need to wait until you're out of Beta or something. Let me know if you want me to keep passing this info on or not. I don't want to waste your time.

I appreciate the help.

**Comment by Flippage** [comment]
Also, minor nitpick but, PM2 doesn't seem to make it start as a service by itself.

It looks like we still need to generate a template in PM2, and then use NSSM to run PM2 as a service at startup, which loads that template.

See the same link you sent me (Section 2 is about creating a Windows service):
https://blog.cloudboost.io/nodejs-pm2-startup-on-windows-db0906328d75

**Comment by HaveAGitGat** [comment]
Sorry I hit the sack. 

Not sure how to hide those terminals (or if it’s even possible to). They don’t come up normally, even in development. 

Have you thought about using Docker for Windows?

**Comment by HaveAGitGat** [comment]
If you’re unfamiliar with Docker, I’ve created this tool to help configure the Docker run command:

http://tdarr.io/tools

I’ll look into new methods to run as a service

**Comment by HaveAGitGat** [comment]
Closing this as it will be covered by Tdarr Desktop Launcher in:
https://github.com/HaveAGitGat/Tdarr/issues/157

**Comment by HaveAGitGat** [comment]
FYI for anyone else, in Summer 2023 Tdarr Desktop Tray was added with option to run on startup so don't need to use this.
