### ISSUE TITLE
Image Based Subtitle in video, Crash encoding

### ISSUE THREAD

**Issue by Nonobis** [HaveAGitGat/Tdarr#114]
2019-12-16: Please note I'm on a 2 week break. Sorry for the inconvenience.

**Describe the bug**
MP4 with specific subtitle not converting.

Command:

/home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg -c:v h264_cuvid -i '/home/Tdarr/Media/movies/San Andreas.mp4' -map 0 -c:v hevc_nvenc -pix_fmt p010le -rc:v vbr_hq -qmin 0 -cq:v 30 -b:v 2000k -maxrate:v 4000k -preset slow -rc-lookahead 32 -spatial_aq:v 1 -aq-strength:v 8 -a53cc 0 -c:a copy -c:s copy -dn '/home/Tdarr/cache/San Andreas-TdarrCacheFile-e5RnTIS1.mkv'

ffmpeg version 3.4.5 Copyright (c) 2000-2018 the FFmpeg developers

built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

configuration: --prefix=/home/z/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/z/ffmpeg_build/include --extra-ldflags=-L/home/z/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/z/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree

libavutil 55. 78.100 / 55. 78.100

libavcodec 57.107.100 / 57.107.100

libavformat 57. 83.100 / 57. 83.100

libavdevice 57. 10.100 / 57. 10.100

libavfilter 6.107.100 / 6.107.100

libswscale 4. 8.100 / 4. 8.100

libswresample 2. 9.100 / 2. 9.100

libpostproc 54. 7.100 / 54. 7.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/Tdarr/Media/movies/San Andreas.mp4':

Metadata:

major_brand : isom

minor_version : 512

compatible_brands: isomiso2avc1mp41

encoder : Lavf58.24.100

Duration: 01:54:27.03, start: 0.000000, bitrate: 9457 kb/s

Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 9159 kb/s, 23.98 fps, 23.98 tbr, 10000k tbn, 0.07 tbc (default)

Metadata:

handler_name : VideoHandler

Stream #0:1(eng): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (default)

Metadata:

handler_name : SoundHandler

Stream #0:2(fre): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s

Metadata:

handler_name : SoundHandler

Stream #0:3(eng): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s

Metadata:

handler_name : SoundHandler

Stream #0:4(fre): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)

Metadata:

handler_name : SubtitleHandler

Stream #0:5(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s

Metadata:

handler_name : SubtitleHandler

Stream mapping:

Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1 (copy)

Stream #0:2 -> #0:2 (copy)

Stream #0:3 -> #0:3 (copy)

Stream #0:4 -> #0:4 (copy)

Stream #0:5 -> #0:5 (copy)

Press [q] to stop, [?] for help

Output #0, matroska, to '/home/Tdarr/cache/San Andreas-TdarrCacheFile-e5RnTIS1.mkv':

Metadata:

major_brand : isom

minor_version : 512

compatible_brands: isomiso2avc1mp41

encoder : Lavf57.83.100

Stream #0:0(und): Video: hevc (hevc_nvenc) (Main 10), p010le, 960x540 [SAR 1:1 DAR 16:9], q=0--1, 2000 kb/s, 23.98 fps, 1k tbn, 23.98 tbc (default)

Metadata:

handler_name : VideoHandler

encoder : Lavc57.107.100 hevc_nvenc

Side data:

cpb: bitrate max/min/avg: 4000000/0/2000000 buffer size: 4000000 vbv_delay: -1

Stream #0:1(eng): Audio: aac (HE-AAC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 96 kb/s (default)

Metadata:

handler_name : SoundHandler

Stream #0:2(fre): Audio: aac (HE-AAC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 96 kb/s

Metadata:

handler_name : SoundHandler

Stream #0:3(eng): Audio: aac (HE-AAC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 96 kb/s

Metadata:

handler_name : SoundHandler

Stream #0:4(fre): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)

Metadata:

handler_name : SubtitleHandler

Stream #0:5(eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s

Metadata:

handler_name : SubtitleHandler

[matroska @ 0x55fae21ab900] Subtitle codec 94213 is not supported.

av_interleaved_write_frame(): Function not implemented

Error writing trailer of /home/Tdarr/cache/San Andreas-TdarrCacheFile-e5RnTIS1.mkv: Function not implemented

frame= 37 fps=0.0 q=23.0 Lsize= 0kB time=00:00:01.66 bitrate= 1.9kbits/s speed=2.81x

video:0kB audio:61kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

Conversion failed!

**To Reproduce**
Rip video with from netflix with "TunePat Netflix Video Downloader", or use a video with subtitle in codec 'Subtitle codec 94213 is not supported.' => Image Video Subtitle

**Expected behavior**
If possible convert file while keeping non supported subtitle codec. if i can't convert it automatically to text based subtitle, at least keep subtitle and convert normally file
Ideally a system for convert subtitle to txt subtitle is perfect :)

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Unraid 6.8.0
 - Browser : Brave Browser
 - Version 1.101

**Additional context**

**Comment by HaveAGitGat** [comment]
@Nonobis sorry this issue is out of my control (it's an issue with FFmpeg). I can't remember off the top of my head which subtitle formats ffmpeg supports with mkv (SRT I believe) but you'll need to remux the mov_text into it during the remux/transcode.

I'll see if I can put together a subtitle codec guide.

**Comment by Nonobis** [comment]
ok, when you have the time :) it's not urgent. thanks

**Comment by HaveAGitGat** [comment]
srt and pgs should be fine for mkv which you're using.

**Comment by HaveAGitGat** [comment]
There is a decent table here under "Subtitle/caption formats support" near the bottom:

https://en.wikipedia.org/wiki/Comparison_of_video_container_formats

Hope that helps.

**Comment by VladoPortos** [comment]
@HaveAGitGat  How did you solve this in the end ? I just started using tdarr but noticed that some files are not being processed because exactly this issue ?

**Comment by supersnellehenk** [comment]
> @HaveAGitGat How did you solve this in the end ? I just started using tdarr but noticed that some files are not being processed because exactly this issue ?

If you could join us on the discord, or create a new issue, I'd be glad to help ;)
