### ISSUE TITLE
[Feature Request] Pagination on queues

### ISSUE THREAD

**Issue by Nonobis** [HaveAGitGat/Tdarr#115]
**Is your feature request related to a problem? Please describe.**
More than 120 movies in queue, only 20 displayed

**Describe the solution you'd like**
Add pagination on all queues list

Thanks

**Comment by HaveAGitGat** [comment]
Are you using version 1.101?

You can change the number of items on the 'Tdarr' tab:

![image](https://user-images.githubusercontent.com/43864057/72625477-c3916f80-3940-11ea-8908-34f833542ec6.png)

**Comment by HaveAGitGat** [comment]
Does that solve the issue?

**Comment by Nonobis** [comment]
for now, but i think a real pagination system would be great ... more pratical with huge queue list (4000 movies/Tv show actually).

i don't if you are using bootstrap but bootstrap-table support pagination natively.

**Comment by HaveAGitGat** [comment]
Added for 2.00.15
