### ISSUE TITLE
Ability to clear a queue.

### ISSUE THREAD

**Issue by finish06** [HaveAGitGat/Tdarr#116]
I am using this tool purely to check for corruption, yet the transcode queue has many items in it.  It would be nice if there was a means to clear a queue via a bulk action instead of individually by item.

I wish for a clear queue option on the home page.

**Comment by Nonobis** [comment]
@finish06 : i think you can clear queue from each library "clear library", i have done this a few times while creating my local plugins.

**Comment by HaveAGitGat** [comment]
@finish06 

Sure, the current method for your use scenario is to not use any transcode/general workers and just ignore the transcode queue.

I'll add a 'Skip all' button in future to the transcode and health check queues.

**Comment by HaveAGitGat** [comment]
Added option to skip all items in transcode and health check queues. Will be in 1.103 later this week.
