### ISSUE TITLE
[Feature Request] Create systemd service for autostarting Tdarr (Linux) on boot

### ISSUE THREAD

**Issue by lordairivis** [HaveAGitGat/Tdarr#117]
**Is your feature request related to a problem? Please describe.**
Just wanted a convenient way to autostart Tdarr on system boot

**Describe the solution you'd like**
Include a .service file in installation instructions

I wanted to have Tdarr autolaunch on system boot, so I created a ```systemd``` .service file to accomplish this. Thought it might be helpful for other users not using Docker and just plain Linux.

I am using Ubuntu Server 18.04.3 LTS, for reference, but this should work the same for any ```systemd``` enabled system.

I created a systemd .service file in ```/etc/systemd/system/``` called ```tdarr.service``` filled with the following contents:

```
[Unit]
Description=Tdarr automated video re-encoder
After=network-online.target

[Service]
Environment=MONGO_URL=mongodb://localhost:27017/Tdarr
# Change to match whichever port you want the Tdarr service to listen on.
Environment=PORT=8265
Environment=ROOT_URL=http://localhost/
# Paths must be absolute. Change to match your installation.
ExecStart=/usr/bin/node /opt/Tdarr/bundle/main.js
# Change to match the user you wish to run Tdarr as.
User=tdarr

[Install]
WantedBy=multi-user.target
```
Enable the service by running ```sudo systemctl enable tdarr.service``` and then start the service with ```sudo systemctl start tdarr.service```. Tdarr should now automatically start on system boot, you can check that the service is running with ```systemctl status tdarr.service```.

Hope this saves someone some effort/time doing this themselves.

**Comment by Zixim** [comment]
it's already mentioned in the wiki, which refers to : https://github.com/HaveAGitGat/Tdarr/issues/95#issuecomment-562949868

**Comment by lordairivis** [comment]
Thanks, missed it in the wiki. It's not mentioned in the README.md installation instructions.
