### ISSUE TITLE
Feature Request - Name a Library 

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#12]
Hey there,

I'm wondering if it's possible to have an field on each library that allows us to put a Description or Name in for that library. Just something that makes it a little easier to recognize what we've got the library doing or whatever purpose. 

Right now, I've got 5 different libraries setup, each pointing to different locations and it's starting to feel a bit long and confusing at times, so I was wondering if this would help some. 

Thanks!

**Comment by marshalleq** [comment]
Great idea - be good to add a sort of colour coding on each library too, not necessarily one colour for each, more like just alternating shades of background or something.

**Comment by HaveAGitGat** [comment]
Added in 1.002
