### ISSUE TITLE
From plugins page if you right click on link and select "open new window" link reopens plugins page instead of going to github

### ISSUE THREAD

**Issue by uG7D1v8Q07N** [HaveAGitGat/Tdarr#120]
2019-12-16: Please note I'm on a 2 week break. Sorry for the inconvenience.

**Describe the bug**
More of a minor nuisance but wanted to point it out for future improvements as time permits as it doesn't behave the way most hyperlinks normally behave.

In Tdarr, if you click on "plugins" at the top, when viewing that page the github links on the far right side of the plugins, right click and select open in new tab (some users on discord says it also does this for them if they hit ctrl+click on the links), it just redirects you right back to the plugins page you are already on. If you left click on the links they work fine and will go to github. 

For example on mine the link in the plugins page will show in text that you click on the name "https://github.com/luigi311/Tdarr_Plugin_lmg1_Reorder_Streams" but if I right click on that link and select open in new tab instead of it going to that page it just goes right back to the plugins page that I am already on. If I right click on that link and select copy hyperlink it will show the hyperlink points to "http://192.168.50.9:8265/plugins/" which is the address for my tdarr plugins page. It seems to work correctly if you just left click on the links. Some people have their browsers setup to always open links in a new page (basically equivalent of always right clicking and selecting open in new tab). So for those users they might keep getting redirected back to the plugins page instead of following the link. 

**To Reproduce**
Go to plugins page, pick a github link on the right of a plugin, and right click on link and select "open link in new tab". some users on discord indicated for them that if they ctrl+click on the link it will also do this behavior of going back to the plugins page

**Expected behavior**
Links should always open the github page whether your selecting to open in new tab or left clicking or however you might interact with the link

**Screenshots**
![Tdarr link issue](https://user-images.githubusercontent.com/52573805/71624631-86dc1f00-2bb1-11ea-81f8-5a8e7fbdf12c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by HaveAGitGat** [comment]
@uG7D1v8Q07N thanks for this. That's interesting behaviour which I'll look into.

**Comment by HaveAGitGat** [comment]
Fixed for 1.103
