### ISSUE TITLE
MacOS Installation Failure

### ISSUE THREAD

**Issue by Ed-Savill** [HaveAGitGat/Tdarr#122]
Hey, I am getting an error on the node main.js command. Can anyone help me with this please?

`node main.js
/Applications/Tdarr/server/main.js:2
import '../imports/api/Methods.js';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3`

**Comment by HaveAGitGat** [comment]
@Ed-Savill what operating system are you on and what version of NodeJS are you using?

Also which folder are you running the command from?

**Comment by HaveAGitGat** [comment]
Let me know if you still have issues.

**Comment by Ed-Savill** [comment]
Hi there,

Yeah I am still having issues. I will look into it later today. Thank you for getting back to me.

**Comment by Ed-Savill** [comment]
Hi there,

I am running Node v8.17.0, Mac OS 10.14.6

I have tried running the command from Tdarr/server & Tdarr folder.

I would love to get this up and running on port 3333 if possible as well please.

**Comment by HaveAGitGat** [comment]
What command are you using to run it?

And have you tried running from the ‘bundle’ folder (not ‘Tdarr’ and not ‘server’ folders).

**Comment by Ed-Savill** [comment]
I am trying `node main.js`

Sorry, what is 'bundle' folder? I have the Tdarr folder in my Applications folder.

**Comment by Ed-Savill** [comment]
![Screenshot 2020-01-25 at 22 28 51](https://user-images.githubusercontent.com/37254436/73128077-1c58ac00-3fc2-11ea-8036-bc52a515ed5b.png)

**Comment by HaveAGitGat** [comment]
What did you download? Sounds like you downloaded the source code rather than the macOS package. You need to download this:

https://github.com/HaveAGitGat/Tdarr/releases/download/0.1-pre-alpha/Tdarr-macOS-01-pre-alpha.zip

**Comment by HaveAGitGat** [comment]
Yeah you just downloaded the source code which won’t work. Please follow the macOS installation instructions:

https://github.com/HaveAGitGat/Tdarr/wiki/2---Installation

**Comment by Ed-Savill** [comment]
Ah, I couldn't find that. The guide said relevant download, I thought it was just the latest haha! Sorry!

Let me give this a go. How can I make it run on start up?

**Comment by Ed-Savill** [comment]
Also, how can I set the port to be, 3333?

**Comment by HaveAGitGat** [comment]
Ah sorry I don’t have a working macOS machine so unfortunately have not been able to create the macOS packages for a while.

To run on start up youd need to create a startup script. More info here:
https://superuser.com/questions/229773/run-command-on-startup-login-mac-os-x

Or use Docker on macOS which makes everything easier.

**Comment by Ed-Savill** [comment]
Thank you. Yeah I will get Docker installed. I might run it on my Qnap, just want to try it in a lab first.

Is there much quality loss from converting to HEVC? 

also, I heard there can be codec issues on some client players. Is this true?

**Comment by HaveAGitGat** [comment]
It depends on the settings you use. It’s best to make some test settings and try a few videos. 

Tdarr_Plugin_075a_FFMPEG_HEVC_Generic
Tdarr_Plugin_s7x8_winsome_h265

Those are good place to start for h265/hevc for ffmpeg and handbrake.

H264 is the most universal codec. hevc/h265 should be fine with never devices but older devices might have problems.

I’ll see if I can update the macOS package this coming week.

**Comment by HaveAGitGat** [comment]
The macOS package is available for the latest version, follow these steps:

Download the relevant Tdarr-macOS zip from https://github.com/HaveAGitGat/Tdarr/releases

Extract zip, navigate to 'Tdarr\bundle\programs\server', open a terminal and run 'npm install'.

Then open a terminal in the 'bundle' folder and run the following:

export MONGO_URL=mongodb://localhost:27017/Tdarr
export PORT=8265 
export ROOT_URL=http://localhost/
node main.js

Visit localhost:8265 in a web browser to use the application. (Change 8265 to your preferred port.)
