### ISSUE TITLE
Include ffmpeg-normalize

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr#127]
I would like to normalize all my videos and including support for ffmpeg-normalize would make this a lot easier.

**Comment by luigi311** [comment]
If not is there a way to store the output of ffmpeg in a variable via a plugin?

**Comment by HaveAGitGat** [comment]
Do you mean normalize the video or audio of your videos?

You can store output by writing to a text file in the plugin. For example:

`fs.writeFileSync("output.txt, "stuff you want to write", 'utf8');`

**Comment by luigi311** [comment]
@HaveAGitGat I want to normalize audio so everything will start at the same volume level.

**Comment by luigi311** [comment]
> `fs.writeFileSync("output.txt, "stuff you want to write", 'utf8');`
How would i use this with the output of ffmpeg. The problem is you need to do a 2 pass for audio normalization, the first pass will analyze the file and spit out values on what gain parameters need to change, you then need to read those values and put them into the 2nd pass arguments. There doesnt seem to be a way to do this in a single command that ive seen yet that doesnt include the ffmpeg-normalize script.

**Comment by HaveAGitGat** [comment]
Interesting, I don't think it's possible to do this sort of thing with the current setup. You can store the output of ffmpeg in a text file but before that you'll run into problems as the way ffmpeg commands are set up in Tdarr will cause an error.

Tdarr always constructs the ffmpeg command with an input and output file but the 1st pass of your normalisation won't need an output file, which will cause an error.

So you'd either need to use a custom script to do the 1st pass and then read it with Tdarr or I'd need to do some work at a later date on how Tdarr constructs the ffmpeg command.

**Comment by luigi311** [comment]
Marking closed since its not something that can be done with the current implementation.

**Comment by HaveAGitGat** [comment]
Storing variables will soon be possible in reference to:
https://github.com/HaveAGitGat/Tdarr/issues/136

Completely custom transcode arguments will also be possible. These should allow using normalisation, crop detect etc.

**Comment by luigi311** [comment]
Looks like Jake jones implemented a plugin so I am closing this issue
