### ISSUE TITLE
Feature Request - Workers +1 / -1 Buttons

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#13]
I'm wondering if it's possible on the Tdarr tab if you could add two buttons to the left of the three bars with the circles that are +1 and -1. I've had a few times in the past two days now where I've drug the circle a bit too far to the right and added 5 workers instead of 2 for example, because it doesn't naturally stop at the increments for me. So I was curious if just adding a +1 and -1 type button would help. 

Thanks!

**Comment by HaveAGitGat** [comment]
Added in 1.002
