### ISSUE TITLE
Library file scanner "UnhandledPromiseRejectionWarning: waited 20000ms"

### ISSUE THREAD

**Issue by nyid** [HaveAGitGat/Tdarr#130]
**Describe the bug**
The library file scanner stops abruptly leaving about half of the files not added to the Tdarr library. Approximately 5000 video files available, only ~2500 are added by Tdarr.

**To Reproduce**
On existing library pointing to a directory with 5000 video files.
Scan (fresh) or Scan (Find new)

**Expected behavior**
Scan all files and add to the Tdarr library.

**Screenshots**
N/A - No web ui error occurs, can only be seen in the logs.

**Desktop (please complete the following information):**
Unraid 6.8.0
Tdarr Alpha 1.008 (tdarr_aoi)

**Additional context**
Log excerpt:

> (node:25968) UnhandledPromiseRejectionWarning: waited 20000ms
> at BatchProcess.onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:371:37)
> at Timeout._onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:222:77)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5)
> (node:25968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:25968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Server: Scanner H3veqFa0:Finished
> Server: File scanner exited

**Comment by HaveAGitGat** [comment]
Would you mind trying on the latest version (1.102)?

**Comment by nyid** [comment]
Yup my bad, I was on the dev tag for tdarr_aoi. Upgraded to 1.102 and same error occurs:

> (node:145) UnhandledPromiseRejectionWarning: waited 20000ms
> at BatchProcess.onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:371:37)
> at Timeout._onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:222:77)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5)
> (node:145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Server: Scanner 7kyjhgxS:Finished
> Server: File scanner exited

**Comment by HaveAGitGat** [comment]
Ok thanks. Based on that message I'm not sure what this relates to as I'm not familiar with BatchProcess.js and I'm not sure which function in the file scanner makes use of it.

Does it happen on a particular file at all? Perhaps either ffprobe or exiftool have unexpectedly failed on a file causing the error?

**Comment by nyid** [comment]
I tried looking for weird characters but didn't really find anything that jumped out. Is there an easy way to export a Tdarr library to csv or something similar?

**Comment by HaveAGitGat** [comment]
I think I found the issue. It's due to exiftool not being able to handle some types of files. Will work on a fix.

If you create a backup on the 'Backups' tab, it will create a zipped text file of the database in Tdarr/Backups.

**Comment by nyid** [comment]
I was about to create a backup per your comment and I just noticed that the last successful backup was January 10th. Pretty sure that is roughly the time I added the library which the file scanner barfs on. 

When I navigate to the backup page the following error appears:

>   | Status
> -- | --
> FileDB | Fetching data
> Status | Error:{}

and this error in the log:

> RangeError: Invalid string length
> at JSON.stringify (<anonymous>)
> at MethodInvocation.createBackup (server/main.js:509:22)
> at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
> at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
> at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js: 1234:12)
> at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
> at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js: 1234:12)
> at Promise (packages/ddp-server/livedata_server.js:715:46)
> at new Promise (<anonymous>)
> at Session.method (packages/ddp-server/livedata_server.js:689:23)
> at packages/ddp-server/livedata_server.js:559:43

Not sure if it's related but that's pretty coincidental.

**Comment by HaveAGitGat** [comment]
Yeah some weird things going there. 5000 items shoudln't be any where near the limit. I can only assume that something went wrong in the database when the file scanner crashed originally and it's caused subsequent problems with for example the back-up. I think I've fixed the file scanner issue but will do some more testing before the next release.

**Comment by nyid** [comment]
Just updated to 1.104. When trying a "Find new" the file scanner stops prematurely and the following error is found in the logs:

> Commencing file update scan. Deleting non-existent files and adding new files.
> Server: Commencing file update scan. Deleting non-existent files and adding new files.
> Server: Scanner ma2AGIVh launched
> Filescanner in Docker
> (node:611) UnhandledPromiseRejectionWarning: waited 20000ms
> at BatchProcess.onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:371:37)
> at Timeout._onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:222:77)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5)
> (node:611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Server: Scanner ma2AGIVh:Finished
> Server: File scanner exited

**Comment by HaveAGitGat** [comment]
Are you able to put verbose logs ON (Logs tab) and then run the scan again? Then check the logs to see which file it fails on.

**Comment by nyid** [comment]
Yeah I dug a bit more and found the scanner failed on two video files (https://pastebin.com/UX826FXy). It looks like exiftool doesn't like them. The last thing I see is FFprobe extract sucess and then roughly 30 seconds later the UnhandledPromiseRejectionWarning error. 

As I was writing this another one failed:

> FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
> 1: node::Abort() [/usr/bin/node]
> 2: 0x8cd49c [/usr/bin/node]
> 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
> 4: 0x8ce978 [/usr/bin/node]
> 5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/usr/bin/node]
> 6: 0xec9a81 [/usr/bin/node]
> 7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
> 8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
> 9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
> 10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/bin/node]
> 11: 0x1024574 [/usr/bin/node]
> 12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
> 13: 0x29a8e4040d85
> 131 (process ID) old priority 19, new priority 19
> Server: File scanner exited

This time Tdarr appears to be stuck, I can't scan the library it looks like it's still in-process of the previous scan but it clearly failed in the logs. Even after restarting Tdarr I can't start another scan on that library. Here is the file that failed: https://pastebin.com/BJ9CbRZj

**Comment by nyid** [comment]
Thank you that did the trick. 

Sorry to pile on but I just found another error, seems to be exiftool again as FFprobe says extract success. Here is the file: https://pastebin.com/L4yzksmC

> 103 (process ID) old priority 19, new priority 19
> (node:232) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
> at new Promise (<anonymous>)
> at __awaiter (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:4:12)
> at BatchProcess._end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:268:16)
> at BatchProcess.end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:260:37)
> at BatchProcess.onError (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:394:14)
> at Socket.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:75:57)
> at emitOne (events.js:116:13)
> at Socket.emit (events.js:211:7)
> at onwriteError (_stream_writable.js:411:12)
> at onwrite (_stream_writable.js:439:5)
> (node:232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
> (node:232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
> 1: node::Abort() [/usr/bin/node]
> 2: 0x8cd49c [/usr/bin/node]
> 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
> 4: 0x8ce978 [/usr/bin/node]
> 5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/usr/bin/node]
> 6: 0xec9a81 [/usr/bin/node]
> 7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
> 8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
> 9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
> 10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/bin/node]
> 11: 0x1024574 [/usr/bin/node]
> 12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
> 13: 0x366763040d85
> Server: Scanner Folder watcher:{"QETRkAZyrMEhZgTjB":{"id":"QETRkAZyrMEhZgTjB","filesToScan":[],"oldLength":0,"newLength":0}}:null
> Server: File scanner exited

**Comment by nyid** [comment]
Another https://pastebin.com/74QEGt1x.

> (node:226) UnhandledPromiseRejectionWarning: waited 20000ms
> at BatchProcess.onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:371:37)
> at Timeout._onTimeout (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:222:77)
> at ontimeout (timers.js:498:11)
> at tryOnTimeout (timers.js:323:5)
> at Timer.listOnTimeout (timers.js:290:5)
> (node:226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Server: Scanner gE6zxGqek:Finished

**Comment by nyid** [comment]
So finally got through the entire directory. Found additional files that produced the same error but didn't post them here. In summary it looks like m2ts containers, BDAV format, and VC-1 or AVC video codec makes exiftool crap out.

The one weird one is https://pastebin.com/BJ9CbRZj which is MPEG-4 HEVC with the error shown here https://github.com/HaveAGitGat/Tdarr/issues/130#issuecomment-583676164.

**Comment by HaveAGitGat** [comment]
Thanks, I've done some major work on the file scanner. I've pushed the update to the tdarr_aio dev tag if you want to give it a go.

**Comment by nyid** [comment]
Hey man sorry I've been busy, just set up a dev container. 

Definite improvement. Out of 7 video files, 3 of them scanned and added to the DB no problem. The most recent failure is on this file: https://pastebin.com/KA7CJPV6

and the error https://pastebin.com/2a8tVyVL

**Comment by HaveAGitGat** [comment]
Hmmmmm I've made a few more changes for 1.105 just released but if they don't work then I'll have to get a sample file somehow and take it to the exiftool github as it's not catching its errors which is causing everything else to crash.

**Comment by HaveAGitGat** [comment]
Please re-open if this issue persists. Thanks.

**Comment by HaveAGitGat** [comment]
Similar issue:

`Server: Scanner SShWyHfFn:Launching FFprobe on this file: /home/Tdarr/Media/Movie/Fight Back to School 3 (1993)/Fight Back to School 3 (1993) DVD.avi
Server: Scanner SShWyHfFn:Running ffmpeg on file
Server: Scanner SShWyHfFn:Running exiftool on file
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 
1: node::Abort() [/usr/bin/node]
2: 0x8cd49c [/usr/bin/node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
4: 0x8ce978 [/usr/bin/node]
5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/usr/bin/node]
6: 0xec9a81 [/usr/bin/node]
7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/bin/node]
11: 0x1024574 [/usr/bin/node]
12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
13: 0x1a45b1e40d85 `

**Comment by HaveAGitGat** [comment]
Another:

(node:169) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
at new Promise (<anonymous>)
at __awaiter (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:4:12)
at BatchProcess._end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:268:16)
at BatchProcess.end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:260:37)
at BatchProcess.onError (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:394:14)
at Socket.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:75:57)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at onwriteError (_stream_writable.js:411:12)
at onwrite (_stream_writable.js:439:5)
(node:169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
 
(node:169) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 
1: node::Abort() [/usr/bin/node]
2: 0x8cd49c [/usr/bin/node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
4: 0x8ce978 [/usr/bin/node]
5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/usr/bin/node]
6: 0xec9a81 [/usr/bin/node]
7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/bin/node]
11: 0x1024574 [/usr/bin/node]
12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
13: 0x348448140d85
Server: File scanner exited

**Comment by HaveAGitGat** [comment]
I have not seen anyone mention this error on v2:
http://tdarr.io/docs/
