### ISSUE TITLE
[Feature request] Add callbacks to plugins

### ISSUE THREAD

**Issue by zzeneg** [HaveAGitGat/Tdarr#136]
**Is your feature request related to a problem? Please describe.**
I use a plugin to merge subtitles downloaded by Bazarr into videos. Now I'd like to delete *.srt files after they were merged. As far as I understand it's not possible now because plugin code is executed before any processing.

**Describe the solution you'd like**
I'd like an ability to define callbacks in plugins - what should be done after processing is completed (success/failure).

**Comment by HaveAGitGat** [comment]
Plugins are also technically executed after processing too. Check this diagram:
![image](https://user-images.githubusercontent.com/43864057/72816615-5cd1c600-3c60-11ea-8300-4d0be1f7c821.png)

So after a file is processed, it goes back through the top of the plugin stack.

So you could do a plugin stack like this

Plugin 1 - Merge local subtitles
Plugin 2 - Delete local subtitles

That should work, right?

**Comment by HaveAGitGat** [comment]
Well, it would need to be more like this, can do it all in one plugin:

Plugin 1 - Check if srt has been merged. If not, merge srt file. If srt has been merged, delete srt file.

**Comment by zzeneg** [comment]
Single plugin will not suffice as I'd like to overwrite existing subtitles (for example if there is a newer version or manually downloaded), but I think the scheme with two plugins should work. Thanks for the idea!

**Comment by HaveAGitGat** [comment]
Great, let me know if you need further help.

**Comment by zzeneg** [comment]
If someone will be interested in this - it was not possible to do what I wanted originally, because according to that diagram the plugin must not do anything when it's executed for the second time. I had to modify it so the first plugin renames `*.srt` to something like `*.processed.srt` and merges them, and the second plugin deletes `*.processed.srt` files.
Unfortunately in case of any error during file processing I have to manually rename `*.processed.srt` back to its original name, so I still feel like callbacks will be a great feature :) Callbacks can be related only to that plugin/execution, not the whole stack/processing.

**Comment by HaveAGitGat** [comment]
Sure I can integrate some plugin `onSuccess`,  `onError` post processing functions.

**Comment by HaveAGitGat** [comment]
I've created quite a comprehensive plan for this and done about 50% already.

Firstly, 'normal' plugins will be able to have `onTranscodeSuccess` and `onTranscodeError` added to them. For example:

```
module.exports.onTranscodeSuccess = function onTranscodeSuccess(file, librarySettings, otherArguments) {
  
  console.log('Post processing, transcode success!!')

  //move file and do some stuff
  file.file = 'some/new/path'

  //update DB with new path
  var response = {
    removeFromDB: false
    updateDB:file
  }

  return response
}

module.exports.onTranscodeError = function onTranscodeError(file, librarySettings, otherArguments) {
  
  console.log('Post processing, transcode error!!')
  
   //Do some stuff, like delete file

  //remove file from DB
  var response = {
    removeFromDB: true
    updateDB:false
  }

  return reponse
}
```

The key thing about `onTranscodeSuccess` is it happens AFTER the new file has been scanned. So the `file` object contains all the properties of the new file, not the old one. There is also access to the library settings, and some otherArguments which can be added if needed (not sure what, but it's there just in case). Also, the database can be updated or files removed.


After all plugins, you can then use a `finalPostProcessing` plugin. I'm creating a new UI section so you can have multiple finalPostProcessing plugins (for example update Sonarr, move to folder, rename etc)

This should effectively allow people to handle files how they want. All of this will become even easier when customisable variables are implemented in reference to:

https://github.com/HaveAGitGat/Tdarr/issues/132
