### ISSUE TITLE
Explore using different database

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#139]
**Is your feature request related to a problem? Please describe.**

Frequent issues with MongoDB such as:

1. When starting Docker container without config, error occurs:

```
docker run -ti \
haveagitgat/tdarr_aio
```

`* Starting database mongodb...fail!`

No known cause of the above. Nothing related to permission issues as no db folder mapped.

2. Frequent permission issues related to MongoDB when starting up = unnecessary hassle.

3. MongoDB will fail to update stats/settings for some users or will randomly corrupt.

4. New users sometimes don't map MongoDB folder, meaning everything is reset during update.

5. Win/Lin/macOS users needing to install MongoDB server = unnecessary hassle.

6. 13642 segmentation fault  MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost

Explore other options.

**Comment by marshalleq** [comment]
I’m still getting challenges with stats freezing and I’ve now given up trying to fix it as it just doesn’t seem to be possible, so offering MySQL or PostgreSQL would be great.

Sent from my mobile device

On 23/01/2020, at 06:32, HaveAGitGat <notifications@github.com> wrote:

﻿

Is your feature request related to a problem? Please describe.

Frequent issues with MongoDB such as:

  1.  When starting Docker container without config, error occurs:

docker run -ti \
haveagitgat/tdarr_aio


* Starting database mongodb...fail!

No known cause of the above. Nothing related to permission issues as no db folder mapped.

  1.  Frequent permission issues related to MongoDB when starting up = unnecessary hassle.

  2.  MongoDB will fail to update stats/settings for some users or will randomly corrupt.

  3.  New users sometimes don't map MongoDB folder, meaning everything is reset during update.

  4.  Win/Lin/macOS users needing to install MongoDB server = unnecessary hassle.

Explore other options.

**Comment by sifotes** [comment]
Can confirm that the current setup for the database is causing me issues. The AIO image works fine on my dev machine, but fails as described above on a new VM.

If it helps, Fedora 31, fresh install, other containers run fine. 

Issue occurs even if database folder has 777 permissions.
Erasing the folder and recreating it has no effect.

**Comment by HaveAGitGat** [comment]
Spent quite a lot of time playing around with LowDB which I quite like. With a new database a lot of the front end would need to be re-done as the current framework doesn't support its reactive functionality with other databases. Looking at 50+ hours of work at least I'd say, not including teething issues.

**Comment by HaveAGitGat** [comment]
I think the new container solves most of the previous issues so now no real need to use something new.
