### ISSUE TITLE
Web UI overhaul

### ISSUE THREAD

**Issue by simse** [HaveAGitGat/Tdarr#140]
**Is your feature request related to a problem? Please describe.**
Tdarr is a fantastic program that seems to be very well optimised for large libraries, and it runs seemingly asynchronously so it also feels very fast. The problem is that, frankly, the UI is terrible (so sorry). It is extremely hard to navigate and do what you want sometimes.

**Describe the solution you'd like**
I'd like to overhaul it.

**Additional context**
I am quite good at designing dashboards like these, and fixing little errors that makes it easier to use. I'd like to create a pull request with a much improved UI (but sticking to the same design language). How would you (@HaveAGitGat) feel about this?

**Comment by HaveAGitGat** [comment]
Haha you should have seen the design/theme a few months ago. 

Ok, make sure to leave plenty of comments though 👍.

How long do you think it will take?

**Comment by simse** [comment]
I can only imagine... I reckon I could have something for you within a couple of weeks.

**Comment by HaveAGitGat** [comment]
It’s come a long way haha but I prioritise function over form. I was planning on doing some work on the UI in the coming weeks so handy you’ve offered.

There are some other big issues regarding things like the database (Mongo) being used which is ingrained in the framework. So it might be worth discussing those while we’re at it.

Ping me on Discord if you like:
https://discord.gg/GF8X8cq

**Comment by HaveAGitGat** [comment]
Ok well let me know if you change your mind.
