### ISSUE TITLE
FFmpeg with libfdk_aac

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr#149]
I can't use libfdk_aac with ffmpeg, it's not included in the ffmpeg configuration?

**Comment by HaveAGitGat** [comment]
Is this tdarr_aio Docker?

Make sure to pull the latest container/tag.

**Comment by Nosirus** [comment]
yes i use haveagitgat/tdarr_aio docker, updated earlier today

**Comment by HaveAGitGat** [comment]
Have you tried updating it again? There was an issue with libfdk yesterday but it was quickly resolved.

**Comment by Nosirus** [comment]
I forced the update again, i use Beta 1.103
the error:
Unknown encoder 'libfdk_aac'
my command :
-sn, -c:v copy -c:a libfdk_aac -vbr 5

**Comment by HaveAGitGat** [comment]
Sounds like your Docker has cached 1.103 and doesn’t realise there’s an update or something.

Just use 1.102
docker pull haveagitgat/tdarr_aio:1.102

**Comment by Nosirus** [comment]
i have delete et re create in Beta 1.102 but same problem
I'm using on unraid, I don't know if that helps.

**Comment by HaveAGitGat** [comment]
Was it working before? The 1.102 is the exact same before so not sure why it wouldn’t work with that.

**Comment by HaveAGitGat** [comment]
Does transcoding without using libfdk_aac work?

**Comment by Nosirus** [comment]
i didn't try fdk_aac before with ffmpeg, only handbrake but i need ffmpeg too 

all transcoding works without yes

**Comment by HaveAGitGat** [comment]
Ah sorry I thought you meant it was working before but it is not working now.

I am not familiar with fdk_aac.

I’ll need to recompile ffmpeg with it at some point.

**Comment by HaveAGitGat** [comment]
If you go on the ‘Options’ tab and use FFmpeg 3.4.5, it has fdk_aac

**Comment by Nosirus** [comment]
oh yes thank you :)

**Comment by HaveAGitGat** [comment]
The next version will have fdk_aac in ffmpeg 4.2 by default (as well as 3.4.5)
