### ISSUE TITLE
Tdarr fills up the disk

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#150]
**Describe the bug**
I ran a few transcodes on some Films overnight and when I arrived back in the morning a lot of the transcodes had failed. On further investigation it looks like the disk is full. I removed 1.102 and installed 1.103 and this seemed to resolve the issue. So unsure if Tdarr continually locks the files.

**To Reproduce**
Transcoding several films overnight.

**Expected behavior**
Tdarr files should clear up after themselves so they don't consume disk space indefinetly.

**Screenshots**
![image](https://user-images.githubusercontent.com/2647926/73264570-079b3480-41cb-11ea-9667-1eabd74f57ce.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 VM (running tdarr as a service, no docker)
 - Version: Beta 1.102

**Comment by HaveAGitGat** [comment]
Are you referring to cleaning up the original files or the cache files?

Tdarr has 2 modes of operation:

- Automatically replace original files
- Transcode files into new folder.

Cache files are automatically cleaned up when a worker finishes with the file so I’m thinking this might have been a permissions issue for you on 1.102?

**Comment by gregoryduckworth** [comment]
I was using the Tdarr to automatically replace the original files.

Where are the cache files located? As that could be the cause

**Comment by HaveAGitGat** [comment]
The cache files are located in the transcode cache:

![8E4E2A4B-DF19-4284-BA0E-FC615E3AB28C](https://user-images.githubusercontent.com/43864057/73274524-9913a200-41dd-11ea-859f-28143565152a.jpeg)

**Comment by gregoryduckworth** [comment]
Thanks! I hadn't set the `Transcode cache` folder but I have now, will keep an eye on it!

**Comment by HaveAGitGat** [comment]
Great! Re-open if you have the issue again.

**Comment by gregoryduckworth** [comment]
Tried with the transcode cache and getting the same issue:
![image](https://user-images.githubusercontent.com/2647926/73341877-6e752800-4275-11ea-9bd2-f3d574f9b653.png)

**Comment by gregoryduckworth** [comment]
It looks like if a transcode fails then it isn't cleaning up the cached file, will confirm but that is the hunch at the moment.

**Comment by HaveAGitGat** [comment]
It should clean up the cache file. Just tested on my system and it cleans up fine if cancelled/errored.

**Comment by gregoryduckworth** [comment]
I've changed to a larger disk and not had the same issue; only a few files have been left behind.

There is an issue that when a file is removed from the disk which is currently being processed then that file does not get cleaned up, but is more of an edge case.

Happy to raise that as another issue and close this one though.

**Comment by HaveAGitGat** [comment]
>when a file is removed from the disk which is currently being processed then that file does not get cleaned up

Would you mind clarifying what you mean by this? Do you mean the original file is not deleted fully? As in it goes into the recycle bin or something?

**Comment by gregoryduckworth** [comment]
Sorry it was a little unclear. What I mean is:

If the original file is removed whilst a transcode is taking place, then the partially transcoded file is left on the disk and not cleaned up.

**Comment by HaveAGitGat** [comment]
Isn't the original file normally locked by ffmpeg/handbrake during transcoding? Does the encoding error out in Tdarr or does it go into 'transcode success' when that happens?

**Comment by HaveAGitGat** [comment]
I tried to replicate this by deleting the original file on my server but it becomes a .fuse_hidden file and handbrake/ffmpeg continue operating as normal:
![image](https://user-images.githubusercontent.com/43864057/73596795-7b1ba980-451d-11ea-9a52-6823f1bddf98.png)

**Comment by gregoryduckworth** [comment]
I'll keep an eye on it but just looking through my cache folder, I had some files that were processed days ago that it hasn't cleaned up.

**Comment by gregoryduckworth** [comment]
Still haven't got to the root cause of it but here is an image of all the same file having several copies within the cache folder:
![image](https://user-images.githubusercontent.com/2647926/73744465-bc43d180-4748-11ea-8841-fe60732fa0b7.png)

**Comment by HaveAGitGat** [comment]
The cache files should be cleaned up automatically on start on 1.104  which should help a bit.

**Comment by gregoryduckworth** [comment]
Since the new startup behaviour in 1.104, I haven't had any issues with the space.

**Comment by HaveAGitGat** [comment]
Great, thanks for the update.

**Comment by fromage9747** [comment]
@HaveAGitGat To confirm, Tdarr will only clean the cached files on start up of Tdarr?

**Comment by albert118** [comment]
> @HaveAGitGat To confirm, Tdarr will only clean the cached files on start up of Tdarr?

Curious about this, too, the docs nor any guides/threads I've seen mention how the cache invalidation or expiration occur. I've noticed that my Tdarr installation will easily suck up 100GB+ when transcoding HEVC HD/UHD content on shared SSDs. Manually clearing or restarting fixes this but doesn't seem to solve the problem.

Is there a way to configure the cache aside from simply setting the location?
