### ISSUE TITLE
Update HandBrake

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr#152]
handbrake is still in version 1.2.1 it's possible to have an updated version and take advantage of codec updates ? the current version is 1.3.1

**Comment by HaveAGitGat** [comment]
Updated to 1.3.1 on Windows, will update the Docker this week.
https://github.com/HaveAGitGat/Tdarr/commit/9c99512f0469dcde88f956a6691d3d0dd88f10cc

**Comment by HaveAGitGat** [comment]
tdarr_aio updated to 1.3.1 for next release.
