### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#156]
I am getting the below error when I am trying to encode my libraries.
/bin/sh: /app/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg: Permission denied

Tdarr has been working fine. I think it recently updated and now I am experiencing this issue. I have checked the permissions on all directories and the account tdarr is running as has access to all and is the owner of them.

Any ideas?

**Comment by clifford64** [comment]
I can confirm rolling back to 1.103 fixes the issue. So I think there is a bug in the latest 1.104 version.

**Comment by HaveAGitGat** [comment]
I've updated the alpine container `tdarr` so ffmpeg should now be working fine on it. Let me know if you still have issues if/when you update.

**Comment by HaveAGitGat** [comment]
Please re-open if this issue still occurs.

**Comment by malcolmradelet** [comment]
I have this issue on 1.207
