### ISSUE TITLE
Add ability to auto update

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#157]
**Is your feature request related to a problem? Please describe.**
It would be great if the program could auto update itself if I have given it permission to, so that I don’t have to worry about making sure it is up to date.

**Describe the solution you'd like**
A checkbox in settings which gives permission for it to auto update.

**Describe alternatives you've considered** 
Could be a script within tdarr that executes on a cron job but that isn’t as user friendly.

**Comment by HaveAGitGat** [comment]
Tdarr cross-platform desktop launcher/version manager is almost done:
https://gfycat.com/distinctrarejaguar

**Comment by morpheus2n2** [comment]
Sorry to drag up old post, hows the progress going on this?

**Comment by HaveAGitGat** [comment]
Hi, I had this mostly done but ran out of steam when I encountered some issues and put it to the side. Perhaps I can give it another go after I've dealt with some other more pressing issues.

**Comment by HaveAGitGat** [comment]
Tdarr V2 now has an updater although it doesn't auto update as all distributed nodes and server need to be updated at the same time which would make things tricky.

http://tdarr.io/docs/
