### ISSUE TITLE
Some images not respecting base URL setting.

### ISSUE THREAD

**Issue by ddimick** [HaveAGitGat/Tdarr#158]
**Describe the bug**
When using a custom base URL (i.e. https://my.server/tdarr), some image URLs are still attempting to load from /images instead of /tdarr/images. For example, https://my.server/images/example_folder_browser.png from the Libraries info popup should instead be https://my.server/<base url>/images/example_folder_browser.png.

**To Reproduce**
1. Use a custom base URL.
2. Select the Libraries tab.
3. Click the "i" for the info popup.

**Expected behavior**
Base URL should prepend all links not pointing to external sites.

**Comment by HaveAGitGat** [comment]
Fixed for 1.105
