### ISSUE TITLE
ffmpeg not allowed to access shared libraries

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#159]
**Describe the bug**
When attempting to transcode some files, the following error was thrown:
```/opt/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg: error while loading shared libraries: libx265.so.179: cannot open shared object file: No such file or directory```

**To Reproduce**
I have four files that seem to be affected by the above issue.

**Expected behavior**
Transcoding to happen as it does with other files

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 1.104

**Comment by HaveAGitGat** [comment]
So just to clarify, it works fine with other files when running the same transcode arguments? Not sure that makes any sense as the libx265 library should be in the same place during each transcode.

Either way, as you're running on Ubuntu you may need to install some extra libraries manually:

`sudo apt-get install -y libx265-dev`

**Comment by gregoryduckworth** [comment]
Yeah, I tried that and libx265 is installed however it looks like Tdarr is using it's own version of the lib so doesn't know the system one exists.

**Comment by gregoryduckworth** [comment]
New files that I download all seem to suffer from the same issue now. The old ones which have been transcoded pass and nothing has changed in terms of the plugins used.

**Comment by HaveAGitGat** [comment]
Tdarr doesn't have its own version of the lib (I have not specifically added any ffmpeg libraries, only the binary). It uses libraries on the host system. 

I have just tested the Ubuntu package on Ubuntu 18.04 running an ffmpeg h265 transcode and it has worked fine:

![Screenshot from 2020-02-15 00-14-11](https://user-images.githubusercontent.com/43864057/74577721-8ee8f600-4f88-11ea-9172-971bb7a61f86.png)

So it seems your libraries have not been installed in the default location. You may need to follow some guides for moving/configuring/symlinking libraries, here's a start:

https://unix.stackexchange.com/questions/194088/how-to-check-if-a-shared-library-is-installed

**Comment by gregoryduckworth** [comment]
Thanks @HaveAGitGat, you pointed me in the right direction. I had to install ffmpeg 4 which doesn't come in the Ubuntu repositories but can be installed from https://launchpad.net/~savoury1/+archive/ubuntu/ffmpeg4.

**Comment by mdrichardson** [comment]
For anybody else that comes across this, easy copy/paste to implement @gregoryduckworth's link:

```bash
sudo add-apt-repository ppa:savoury1/graphics &&\
sudo add-apt-repository ppa:savoury1/multimedia &&\
sudo add-apt-repository ppa:savoury1/ffmpeg4 &&\
sudo apt update &&\
sudo apt install ffmpeg libx265-dev &&\
mv /<TDARR_INSTALL_PATH>/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg /<TDARR_INSTALL_PATH>/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpegBACKUP &&\
ln -s /usr/bin/ffmpeg /<TDARR_INSTALL_PATH>/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg
```
