### ISSUE TITLE
Feature Request - Tdarr Tab Info

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#16]
I'm combining a few items into one request here but they seem pretty related. All three are on the Tdarr Tab itself.

- On the Tdarr tab, in the Transcode log, when hitting the **i** button, I noticed that the text doesn't wrap out. It's all forced onto one line, like : 
> File is h264 480p!File has no title and has no subs File has no title metadata File has no subs File is in mkv container! File meets conditions!

- On the Tdarr tab, is it possible to show the before and after size on the Transcode log when hitting the **i** button?

- On the Tdarr tab, is it possible to show the date/timestamp in both the transcode and health logs? Even if it's under the **i** button.

**Comment by HaveAGitGat** [comment]
Added in 1.003
