### ISSUE TITLE
Ability to set how many backups are allowed

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#160]
**Is your feature request related to a problem? Please describe.**
At the moment it keeps a backup every night, it would be nice if it was possible to set it to keep 'X' number of backups or 'X' number of days

**Describe the solution you'd like**
As above.

**Additional context**
![image](https://user-images.githubusercontent.com/2647926/74241479-05a99900-4cd4-11ea-8556-1c3a2cab7236.png)

**Comment by HaveAGitGat** [comment]
Added for 1.105:
![image](https://user-images.githubusercontent.com/43864057/74715809-2bc7bf80-5225-11ea-9549-75d50c6db389.png)
