### ISSUE TITLE
Ensuring QuickSync is used

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#163]
Hi,

I've used the aio image and the qsv tag and priviledged set. I'm using handbrake to transcode with the following command:

```ts
-e x265 -Z "Very Fast 1080p30"
```

Is there anything I need to add to enable QuickSync, or a way to proove its working?

**Comment by HaveAGitGat** [comment]
Hi, you need to specify the qsv encoder (h264 or h264).

For example:

`-Z "Very Fast 1080p30" -e qsv_h264 --all-subtitles --all-audio`

`-Z "Very Fast 1080p30" -e qsv_h265 --all-subtitles --all-audio`

Easiest way to check it's working is to compare the ETA on a test file with qsv vs without it. `qsv_h265` should be about twice as fast as `x265` depending on the CPU.

**Comment by jleck** [comment]
Ah, d'oh! thanks, will give that a try!

**Comment by jleck** [comment]
Looks to be working, thanks!

**Comment by HaveAGitGat** [comment]
Pleased to hear it!
