### ISSUE TITLE
Edit/Update an existing plugin

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#165]
**Is your feature request related to a problem? Please describe.**
Rather than having to create a new plugin if you want to tweak one slightly, it would be nice if you can update an existing one/copy a community one and make a tweak

**Describe the solution you'd like**
Ability to edit an existing plugin

**Describe alternatives you've considered**
Manually editing the local .js file

**Comment by HaveAGitGat** [comment]
Added for 1.106:

Community:
![image](https://user-images.githubusercontent.com/43864057/77198333-b3cc0e00-6ade-11ea-92fa-cf5bdfbda056.png)

Local:
![image](https://user-images.githubusercontent.com/43864057/77198383-c8100b00-6ade-11ea-8736-4f9c70c078e4.png)

![image](https://user-images.githubusercontent.com/43864057/77198413-d5c59080-6ade-11ea-831f-acfbfb907e56.png)
