### ISSUE TITLE
Prometheus Exporter Support

### ISSUE THREAD

**Issue by alexandzors** [HaveAGitGat/Tdarr#166]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have the ability to export the stats page to a Prometheus /metrics endpoint so that they can be viewed in Grafana. All Tdarr would have to do is expose `stats` to /metrics in a Prometheus friendly format.

I monitor a lot of home services via Grafana and various data agents, would be nice to get stats from Tdarr.

URL example: localhost:8265/metrics

**Describe alternatives you've considered**
A script that can be used to export stats page to InfluxDB, though this route might be more complicated.

**Additional context**
Here is an example of a Prometheus /metrics endpoint that Prometheus can scrape for data:
![image](https://user-images.githubusercontent.com/25626115/74966668-7db74380-53e5-11ea-9b56-b02e9797fa5c.png)

PiHole dashboard example utilizing a Prometheus exporter: 
![image](https://user-images.githubusercontent.com/25626115/74970296-1b157600-53ec-11ea-9dae-76103a9f685c.png)

ref: 
https://prometheus.io/docs/instrumenting/exporters/

**Comment by HaveAGitGat** [comment]
Thanks for openening an issue. I will look at this in more detail once I'm on top of some of the in-house Tdarr issues.

**Comment by alexandzors** [comment]
No problem and no rush!

**Comment by buroa** [comment]
+1

**Comment by HaveAGitGat** [comment]
FYI just mentioned this on Discord but this probably won't be added, you can collect the info on the stats page by using this:

```
const axios = require('axios');
(async () => {
    const result = await axios.post(`http://localhost:8266/api/v2/cruddb`, {
        headers: {
            'content-Type': 'application/json',
        },
        data: {
            collection: 'StatisticsJSONDB',
            mode: 'getById',
            docID: 'statistics',
            obj: {},
        },
        timeout: 1000,

    });
    console.log(result);
})();
```

```
  data: {
    totalFileCount: 4,
    totalTranscodeCount: 650,
    totalHealthCheckCount: 8046,
    sizeDiff: 26.3105350965634,
    _id: 'statistics',
    tdarrScore: '100.0',
    healthCheckScore: '0.000',
    table2Count: 4,
    table3Count: 0,
    table4Count: 4,
    table5Count: 0,
    table6Count: 0,
    table1Count: '0',
    pies: [ [Array], [Array] ],
    streamStats: { duration: [Object], bit_rate: [Object], nb_frames: [Object] },
    avgNumberOfStreamsInVideo: 3,
    languages: { eng: [Object] },
    DBPollPeriod: '1s',
    DBFetchTime: '1s',
    DBLoadStatus: 'Stable',
    DBQueue: 0,
    table0Count: 0
  }
```

So you can map that data however needed.
Tables 0 - 6 correspond to the tables at the bottom of the tdarr tab.

**Comment by buroa** [comment]
Yikes. @HaveAGitGat you have enterprise subscriptions but don't offer prometheus metrics that companies use? I'm not sure closing this issue was your best option. Maybe take your JSON here and parse it into a prometheus exporter. It is _not_ hard.

**Comment by robertlestak** [comment]
For anyone who ends up here, I've gone ahead and implemented this: https://github.com/robertlestak/tdarr_exporter 

It's available as a docker image on docker hub - `robertlestak/tdarr_exporter`

I've also included an example k8s manifest in the repo.
