### ISSUE TITLE
Formatting issue on status

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr#169]
**Describe the bug**
The box for titles on stats is to small causing all of them to have line breaks between words making it unreadable

**To Reproduce**
Click the i to see stats of the encoding

**Expected behavior**
Readable text on the left column of the encoding information

**Screenshots**
Here is what it looks like now 
![Tdarr](https://user-images.githubusercontent.com/4695527/75117297-72eeef80-562d-11ea-8523-321a231dc8f8.png)
Here is what it should look like 
![Tdarr_Fixed](https://user-images.githubusercontent.com/4695527/75117330-a0d43400-562d-11ea-9a73-c5cc950e236a.png)

**Desktop (please complete the following information):**
 - OS: OpenSUSE
   - Browser: Firefox
 - OS: Android
   - Browser: Firefox looks the same
   - Browser: Chrome looks worse with 1 or 2 letters before it line breaks.

**Additional context**
You should also do word-break: break-word so it will try to break on whole words instead of breaking  as soon as it is out of space causing words to be split.

**Comment by HaveAGitGat** [comment]
Fixed for 1.105

**Comment by HaveAGitGat** [comment]
1.106*
