### ISSUE TITLE
Feature Request - Drilldown of stats

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#17]
It would be useful to be able to get a list of files by clicking on pie-chart segments on the stats page.  it would be useful to see what files are in each category for general library management (e.g. files in an unusual format or resolution).

**Comment by JeremyKennedy** [comment]
One use case for this is that Tdarr has found a single audio file in my media library. The container is mkv, codec is eac3. Searching for `mkv,eac3` returns a ton of results, so I'm not sure how I would be able to drill down to find that audio file.

**Comment by HaveAGitGat** [comment]
Added in 1.003
