### ISSUE TITLE
Don't run as root?

### ISSUE THREAD

**Issue by mcampbell** [HaveAGitGat/Tdarr#170]
The current processes (at least `node`, and mongo) run in the container as root.  This seems unnecessary, and a possible security nightmare.

At the very least, it causes me to have to sudo to change any processes like `nice`, etc.

Based on the `docker ps` output, it looks like some part of the init shell explicitly does this.

```
ee40c8c4ffb0        haveagitgat/tdarr_aio      "/bin/sh -c 'sudo se…" ...
```
A lot of the linuxserver.io processes share an init process which allows the user to pass in a UID/GID, eg:
```
docker create \
  --name=radarr \
  -e PUID=1000 \           <========== THIS BIT
  -e PGID=1000 \           <========== 
  -e TZ=Europe/London \
  -e UMASK_SET=022 `#optional` \
  -p 7878:7878 \
  -v path to data:/config \
  -v path/to/movies:/movies \
  -v path/to/downloadclient-downloads:/downloads \
  --restart unless-stopped \
  linuxserver/radarr
```

**Describe the solution you'd like**
Run as $USER

**Additional context**
https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b
https://hub.docker.com/r/linuxserver/radarr

**Comment by Roxedus** [comment]
That's on my todo for a PR. Currently my mind is on automated releases.

**Comment by se1exin** [comment]
Here is the workaround I have been using on my linux server, it's not great, but at least all my media doesn't end up being changed to `root`.

Basically I override the docker `CMD` to first change the permissions of the Tdarr data folder (so Tdarr can work on it without needing to be root) and then run the node process *without* `sudo`.

Note my server user and group ID is 1000, which happens to match the docker container's Tdarr user and group ID, so it works for me. I doubt it will work if your user/group IDs are not 1000.

```
docker run -it \
[other docker flags] \
haveagitgat/tdarr_aio \
	/bin/bash -c 'echo "Fixing permissions" && \
	sudo chown -R 1000:1000 $HOME/Tdarr && \
	sudo service mongodb start && \
   	echo "Mongo started, waiting 10 seconds" && \
   	sleep 10 && \
	echo "Tdarr started" && \
	MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=$ROOT_URL node --max-old-space-size=16384 $HOME/Tdarr/bundle/main.js'
```

Would be awesome if we could just pass `PUID` and `GUID` into the container, but this works for me for the time being.

**Comment by mcampbell** [comment]
Good idea.  I've done something similar by running a `chown` from my `root` crontab.  Your solution is more self-contained though.

**Comment by p2bauer** [comment]
PUID and GUID would be super useful - files still seem to be ending up as owned by root with the 1.107 release, at least on my docker install.

**Comment by Roxedus** [comment]
Correct, its not implemented yet.

**Comment by ujellyx** [comment]
Yes please.

**Comment by n0rbertg** [comment]
What would be an easy workaround for running a simple chown when the file is ready? A plugin with a configurable UID/GID would do the trick as well I guess at the end of the stack. 

I just started using tdarr and I love it, this is the only thing that brakes my current pipeline.

**Comment by marshalleq** [comment]
Maybe just use the UID/GID in the container?

On 3/05/2020, at 8:10 AM, n0rbertg <notifications@github.com<mailto:notifications@github.com>> wrote:



What would be an easy workaround for running a simple chown when the file is ready? A plugin with a configurable UID/GID would do the trick as well I guess at the end of the stack.

I just started using tdarr and I love it, this is the only thing that brakes my current pipeline.

**Comment by glahera** [comment]
I'm rebuilding a tdarr image based on lsiobase/ubuntu:bionic, I've successfully run it but it's not responding on web browser. Is there a way to enable Debug log via command line yet? I examined the code but it seems like there isn't a method for that.

**Comment by Roxedus** [comment]
Why reinvent the wheel? @HaveAGitGat is reviewing my fork, which does respect the user. 
https://github.com/Roxedus/Tdarr/tree/master/Docker_files/Ubuntu2

**Comment by glahera** [comment]
> Why reinvent the wheel? @HaveAGitGat is reviewing my fork, which does respect the user.
> https://github.com/Roxedus/Tdarr/tree/master/Docker_files/Ubuntu2

probably because it takes rather long for that review, and a debug log is really useful.

**Comment by jeff47** [comment]
> Here is the workaround I have been using on my linux server, it's not great, but at least all my media doesn't end up being changed to `root`.
> 
> Basically I override the docker `CMD` to first change the permissions of the Tdarr data folder (so Tdarr can work on it without needing to be root) and then run the node process _without_ `sudo`.

Does Tdarr already own that directory?  Seems like it should - there is a chown command right at the top of the docker fil.

**Comment by se1exin** [comment]
> Doesn't Tdarr already own that directory? Seems like it should - there is a chown command right at the top of the docker file.

Yes it owns the top level $HOME/Tdarr directory, but directories nested deeper under the folder have different user/group set (I'm not near my server at the moment so don't have the specifics sorry). From memory the incorrect perms aren't under a single directory either - so I found it simpler to just (re)chown the whole top-level folder.

> there is a chown command right at the top of the docker file.

Yep there is a `chown` command right at the top of the Dockerfile, but something between the start of the Dockerfile and the final `CMD` command is writing folders/files under $HOME/Tdarr with a different user/group. My guess at the time was there is a setup command that needs `sudo` that also writes files under $HOME/Tdarr. At the time I couldn't be bothered reverse engineering the whole Dockerfile build as I just wanted to try tdarr, so I just resorted to my hack mentioned in earlier comment.

**Comment by Draxter** [comment]
The issue is **workers** running as root, they are the ones that create output files which then end up being owned by root, even if you set PUID=1000 environment variable in your docker command. So if you let it run on your library, eventually every transcoded file will 'change' ownership to root!

Here is an example list of processes that run in the container while it's transcoding:
```
Tdarr@139e52c0823a:/$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
Tdarr        1  0.0  0.0   4624   812 ?        Ss   21:09   0:00 /bin/sh -c sudo service mongodb start &&  echo "Mongo started, waiting 10 seconds" &&  sleep 10 &&  echo "Tdarr started" &&  sudo MONGO_URL=mongodb://localhost:27017/Tdarr P
root        15  0.3  0.9 1026584 77352 ?       Sl   21:09   0:10 /usr/bin/mongod --config /etc/mongodb.conf
root        46  0.0  0.0  64812  3792 ?        S    21:09   0:00 sudo MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost node --max-old-space-size=16384 /home/Tdarr/Tdarr/bundle/main.js
root        47  0.8  1.6 1310528 133616 ?      Sl   21:09   0:25 node --max-old-space-size=16384 /home/Tdarr/Tdarr/bundle/main.js
Tdarr      163  0.0  0.0  18504  3484 pts/0    Ss   21:54   0:00 bash
root       204  1.1  0.4 879412 36148 ?        Sl   22:01   0:00 /usr/bin/node --max-old-space-size=16384 assets/app/worker1.js Hpjp6wmjOq transcode
root       210  0.7  0.3 877364 31720 ?        Sl   22:01   0:00 /usr/bin/node --max-old-space-size=16384 assets/app/worker2.js
root       216  0.0  0.0   4624   820 ?        S    22:01   0:00 /bin/sh -c /home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg  -i '/media/input_video.mkv'  -map 0 -map -0:a:1
root       217 27.8  0.5 254520 46236 ?        D    22:01   0:02 /home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg -i /media/input_video89om .mkv -map 0 -map -0:a:1 -map -0:a:2 -m
Tdarr      225  0.0  0.0  34396  2996 pts/0    R+   22:01   0:00 ps aux
```

**Comment by HaveAGitGat** [comment]
The new container is currently being tested under `haveagitgat/tdarr:pro_nightly` and seems to be working well. Everything in those containers will be moved into the tdarr and tdarr_aio containers at the end of the month.

**Comment by theg00s3** [comment]
Will the changes in the pro containers allow setting the file permission (like 644) or just the file owner?

**Comment by HaveAGitGat** [comment]
All latest Tdarr containers (pro and non-pro) now respect User/Group:
E.g.:

```
docker run -ti \
             -v /cache/:/temp \
             -v /app/:/home/Tdarr/Documents/Tdarr \
             -v /app/TdarrDB:/var/lib/mongodb \
             -p 8265:8265 \
             -e "TZ=Europe/London" \
             --network="bridge" \
             -e PUID=1000 \
             -e PGID=1000 \
             --log-opt max-size=10m \
             --log-opt max-file=5 \
             haveagitgat/tdarr
```

http://tdarr.io/tools

**Comment by HaveAGitGat** [comment]
@theg00s3 no the changes don't have implementation of that

**Comment by theg00s3** [comment]
> no the changes don't have implementation of that

I ended up modifying the "Set permissions for Unraid" plugin to do it
