### ISSUE TITLE
Use Gotify for Notifications of Errors or Finished Queues

### ISSUE THREAD

**Issue by MNTLe-DMGD** [HaveAGitGat/Tdarr#171]
**Is your feature request related to a problem? Please describe.**
Monitoring the queues and looking for errors is time consuming, as is scanning through logs etc.  It would be nice to be notified of an issue, rather than have to fire up my PC go looking for them manually.

**Describe the solution you'd like**
The feature I would like to see, is when there is and error (like a failed encode), or the transcode queue completes, a notification sent via Gotify (https://gotify.net/)

It's an excellent self hosted server that doesn't require a lot of configuration and the payload is fairly simple via the REST-API (see here: https://gotify.net/api-docs#/message/createMessage)

This could of course extend to Slack; PushBullet; Discord; Telegram, and other potential services.  Using Webhooks may be the best way to achieve this.

**Describe alternatives you've considered**
Currently, there are no real alternatives without hard coding it into a plugin, which would make it difficult for new users, unless it were "configurable" which is beyond my skill level.

If it were in a configurable plugin, it may be preferable, as it can then be added to a stack, but would not be system wide.

**Comment by Migz93** [comment]
I think possibly
https://github.com/caronc/apprise

Might be better suited, it supports multiple notification services. Rather then implement just Gotify.

**Comment by Roxedus** [comment]
> caronc/apprise

If anything, use a library for JS.

**Comment by davralin** [comment]
Might I suggest using [apprise](https://github.com/caronc/apprise)?

It's the same notification system that bazarr use.

It supports alot of notification systems, including gotify, and matrix (which I was looking for).

**Comment by HaveAGitGat** [comment]
Apprise added to Docker image in 2.18.01 just released, with "Apprise" flow plugin added too.
