### ISSUE TITLE
Use partial filename in output dir to avoid problems with other tools

### ISSUE THREAD

**Issue by crypto-vault** [HaveAGitGat/Tdarr#172]
**Is your feature request related to a problem? Please describe.**
Tdarr copies files to output using mkv (or other container type) as filename extension. This causes other programs (Plex for example) to start indexing the temporary file XXXX-Tdarrnew.mkv as being a new video file.

**Describe the solution you'd like**
Copy the file to the output with .partial extension (or similar) and when copying is finished then move it to the real final name.

**Detected issues with third party apps**
So far I've detected issues with the following apps:

Plex: Since Plex is always looking for new media with inotify, it finds the XXXX-Tdarrnew.mkv and thinks it's a second copy of the movie. It imports the Tdarr file and after it gets deleted an error is thrown in the logs reporting the file is now missing.

Tinymediamanager: It thinks the temporary XXXX-Tdarrnew.mkv is a new movie so it creates lots of metadata files like XXXX-Tdarrnew-banner.jpg, XXXX-Tdarrnew-poster.jpg, XXXX-Tdarrnew-trailer.mp4, etc

**Comment by HaveAGitGat** [comment]
Added for 1.107 
New files will end in '.partial' while being copied over.

**Comment by kocane** [comment]
@HaveAGitGat my files are not named .partial when being moved to the output folder. Is there a setting somewhere that I'm missing?
