### ISSUE TITLE
Raspbian Buster?

### ISSUE THREAD

**Issue by barbequesauce** [HaveAGitGat/Tdarr#175]
Hi - 

I'm one of the devs for [Watcher3](https://github.com/barbequesauce/Watcher3). One of my goals is to build a fully-automated system that takes starred/popular/new movies from Trakt/IMDb and gets them to a user's HTPC, with all post-processing hands-off - including remuxing/transcoding to a normalized pattern. Taking advantage of the good work done in Watcher3's upstream, we have the first half of that statement working; I am hoping to use Tdarr for the second half of the equation.

I'm attempting to follow the instructions in #95. As things stand today, Tdarr uses MongoDB 4.2 - which, best I can tell, is 64-bit only. As mentioned in #110, it would be great to get Tdarr running on a Raspberry Pi - my personal use case is Raspbian Buster, but Docker would work too; as Raspbian is 32-bit only today (and unlikely to change in the near future), MongoDB is a blocker.

Any thoughts on an alternate database? I see some exploration in #139, but not sure if that's a conversation or something more...

**Comment by barbequesauce** [comment]
Alternately - looking at [these instructions](https://medium.com/@mattalord/embedded-mongodb-4-0-on-raspberry-pi-e50fd1d65e43) - any idea what feature loss there will be if MongoDB embedded 4.0 is used?

**Comment by HaveAGitGat** [comment]
I was looking into other databases but the issue is that the framework Tdarr uses (Meteor), contains all kinds of built in features for MongoDB which removes a lot of leg work for me. It would be a lot of work to re-do everything for a different database and I don't have the time for that at the moment.

The other issue is I'm not sure Tdarr would be used very much on low powered devices as the transcodes would take days/weeks which isn't very practical.

**Comment by HaveAGitGat** [comment]
If someone mentions a `much to be used` practical case for Tdarr on a Raspberry Pi I'll re-open.

**Comment by HaveAGitGat** [comment]
Tdarr v1.99.09 (v2 preview) has Tdarr_Server, Tdarr_WebUI and Tdarr_Node modules for arm (+ macos). More info here:
https://github.com/HaveAGitGat/Tdarr/blob/master/updater/README.md

**Comment by HaveAGitGat** [comment]
V2 instructions here including Raspberry Pi (linux_arm, does not work on Raspberry Pi gen 1)):
http://tdarr.io/docs/

Please reopen if needed.

**Comment by barbequesauce** [comment]
Thank you!

**Comment by HaveAGitGat** [comment]
FYI you can now use arm containers:
https://github.com/HaveAGitGat/Tdarr/issues/110#issuecomment-821780888

**Comment by martinkeat** [comment]
Will this work on a cluster of Pi zeros?
