### ISSUE TITLE
Invalid folder

### ISSUE THREAD

**Issue by spikemixture** [HaveAGitGat/Tdarr#176]
I am setting up tdarr for the first time .
It is/will be exactly what I want.
I am using docker on a Qnap TS-1277 (Ryzen cpu)

Most, I think I have setup but the "Source" has got me beat.
No matter what I put in, the purple "invalid folder" remains. 
My media is here -     /share/CACHEDEV2_DATA/Media/
This contains several separate media folders e.g.      /share/CACHEDEV2_DATA/Media/tv

I have tried 
/share/CACHEDEV2_DATA/Media/tv
/share/CACHEDEV2_DATA/Media/
/share/CACHEDEV2_DATA/
/share/CACHEDEV2_DATA/Media
/share/CACHEDEV2_DATA/Media/tv/

some logs of some testing but no Stats showing

File scanner exited
2020-03-13T22:56:47+0800
Scanner 8B6moJLZ:Finished
2020-03-13T22:56:47+0800
Scanner 8B6moJLZ launched
2020-03-13T22:56:47+0800
Commencing file update scan. Deleting non-existent files and adding new files.
2020-03-13T22:23:22+0800
File scanner exited
2020-03-13T22:23:22+0800
File scanner exited
2020-03-13T22:23:22+0800
File scanner exited

What am i doing wrong??

**Comment by HaveAGitGat** [comment]
Hi, with Docker you have to map folders on the host to folders inside the container. The container can't 'see' the folders on the host machine without mapping.

Not sure how it's done on QNAP but use the [ tdarr.io Docker config tool](http://tdarr.io/tools) for guidance.

**Comment by spikemixture** [comment]
Thanks for the tip it took a long long while as a dozen installs did not work.

All looking good.

I am looking at re-coding all my x264 to x265 but end as MP4 .

It appear everything ends as MKV

**Comment by HaveAGitGat** [comment]
Great.

>Also Tdarr My server is set to UTC - i think

Yep you need to specify the container time zone, default in the config is UTC.

**Comment by spikemixture** [comment]
Where is the config file?
I am using Docker on a qnap NAS and settings (like Time and shared folders) can only be set on initial set up.

**Comment by HaveAGitGat** [comment]
Sorry I was referring to the Docker run command config:
![image](https://user-images.githubusercontent.com/43864057/76977135-d4546680-692c-11ea-86cf-61db69cf80b0.png)

So there should be a setting to add a timezone variable somewhere in Qnap

**Comment by HaveAGitGat** [comment]
There's an Environment section where you can do it I think:
![image](https://user-images.githubusercontent.com/43864057/77018761-911ee580-6976-11ea-897b-6d4d329a26ed.png)

From 4:52:
http://www.youtube.com/watch?v=9lREBHILjy8&t=4m52s

**Comment by spikemixture** [comment]
Thanks HAGG,

That environmental option is only in the initial install.  Cannot be added or changed after installed.

Anyway I accidentally deleted the container Station folder and did a fresh install with the right TZ.

All good now

**Comment by Pseudomax** [comment]
Hi @spikemixture, I'm also wanting to install this in a QNAP Docker Container ... but I'm very unfamiliar with the settings. Please could you let me know the steps/settings? It would be very much appreciated ... Thanks

**Comment by Pseudomax** [comment]
Just to add/update ... I have managed to install Tdarr but it won't start? I added an environment variable (Named: "TZ", Value: "Europe/London") and gave my Multimedia folder a mount point of "/Multimedia" but as I say the container briefly shows a 'green light' then stops again almost immediately. Any suggestions to what I could be doing wrong?

**Comment by daviddavo** [comment]
I have the invalid folder problem, I'm using a container with the driver `vieux/sshfs:latest`, but if I do `docker exec -it tdarr bash` I can do `cd/ls` and the files appear there.

Why is it saying "Invalid folder"?
