### ISSUE TITLE
Add option to move source files to a directory before replacing them with transcoded version

### ISSUE THREAD

**Issue by SLemons13** [HaveAGitGat/Tdarr#180]
This feature would allow for ease of automation of archiving original source files. A user could have the source file of a transcode moved to an "already transcoded" directory, where source video files can be written to tape backups/cloud backup/etc in case of the desire to re-transcode the library in the future. 
I know something similar could be achieved using an output folder, but that will require extra space to store both the source files and the transcoded files, as completed source files could not be offloaded until the entire library is finished transcoding.

**Comment by accelaptd** [comment]
I've got a lot of mpeg4 stuff hanging out on my server that I want to transcode for compatibility reasons rather than space. I want to keep the files around for the time being as this is an unfamiliar process for me and I want the security of keeping my library of difficult to replace files in addition to the convenience of using software like tdarr to make this a less manual process. I currently plan on using the output folder option in addition to manually moving the files in/out but this would be a huge upgrade for me, making it a seamlessly automated risk-free process start to finish.

**Comment by dkanzlemar** [comment]
I very much am looking for this functionality as well. I know this is an old issue, but it describes EXACTLY what I am hoping to accomplish.

**Comment by duindain** [comment]
This is a default feature of Radarr and Sonarr 'Recycling Bin' in file management

I've just started trying to use Tdarr but I won't be turn it loose on my collection without being able to check it and revert back if needed, its unfortunate based on the comments here and in the closed issue #155 that there isn't a plugin or way to accomplish this I'd personally rate it as a core v1 feature requirement

**Comment by HaveAGitGat** [comment]
Added to Tdarr Flow so you can just use the copy to directory plugin e.g.:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bb1cbcd2-8cfc-4529-8b11-49b07964d6bf)

**Comment by HaveAGitGat** [comment]
Beta released the other day, feel free to reopen if you have any issues.

**Comment by varunkotian** [comment]
Is there a way to delete the copied file at the end? I want to copy the file to the transcoding machine before transcoding. After transcoding, I want to replace the file on my NAS and then delete the copied file. Right now, the Replace Original File only deletes the original file and not the copied file.

**Comment by dennix85** [comment]
move to folder for ur end product that you have encoded, then u use the set original file plugin to call the file u started with, then u can do delete file..

**Comment by varunkotian** [comment]
I have the flow this way: 
<img width="689" height="822" alt="Image" src="https://github.com/user-attachments/assets/3914296f-9972-41b6-89c4-92548193035b" />

What should I change? I did not understand what you meant. I am new to this Flow.
