### ISSUE TITLE
Add bitrate cutoff to filters

### ISSUE THREAD

**Issue by tommyjohn81** [HaveAGitGat/Tdarr#181]
It would be great to have a bitrate cutoff in the transcode decision maker, I dont wan't to re-encode files if they are below a certain bitrate, so tdarr should check and skip these files.

**Comment by suodrazah** [comment]
Direct bitrate cutoff, or this could also be achieved with a mb/hour slider.

**Comment by HaveAGitGat** [comment]
Please see here:
https://github.com/HaveAGitGat/Tdarr/issues/244
