### ISSUE TITLE
UNRAID reboot wipes database

### ISSUE THREAD

**Issue by nicholasfoote** [HaveAGitGat/Tdarr#185]
Whenever my unraid server reboots, Tdarr's database is completely wiped. I have to make the libraries again, setup the transcode ID and media location, and scan the whole library again.

If you aren't able to resolve that generally, are you able to add a database backup cron so I can at least restore it from the latest backup when it does happen?

I don't have the most reliable power, so I end up having to rescan my entire 50K item library about weekly. If I don't re-scan it, it won't find new media as it's added.

**Comment by marshalleq** [comment]
Seems like an issue with persistent storage or something?  Does this happen for any other dockers?  Is it read only?  I know this can work as most others don't have same issue as you as far as I know - so I reckon it's something you could fix...

**Comment by Marthisdil** [comment]
not happening in my unraid.

**Comment by Roxedus** [comment]
Did you go from the non-aio version, to the aio version?

**Comment by HaveAGitGat** [comment]
I'm not sure if you've used Docker containers before but data inside the container is not persistent when the container is updated.

You need to make sure the Tdarr documents and database folders are mapped to a persistent storage location on your host. So the following two folders inside the container need to be mapped to the host as mentioned in the installation instructions in the [wiki](https://github.com/HaveAGitGat/Tdarr/wiki/2---Installation):

`/home/Tdarr/Documents/Tdarr`
`/var/lib/mongodb`

Tdarr already has a daily backup and restore process - there's a whole tab dedicated to it:
![image](https://user-images.githubusercontent.com/43864057/77592627-7aced780-6eea-11ea-8644-1a382530597b.png)


Backups are stored in the container path `/home/Tdarr/Documents/Tdarr/Backups`. There is no need for a cron job.

**Comment by HaveAGitGat** [comment]
Please re-open if you still need help with this.
