### ISSUE TITLE
Option to Move/Delete Failed files

### ISSUE THREAD

**Issue by Phillips57** [HaveAGitGat/Tdarr#186]
As tdarr is running it records files that have failed either Health Check or Transcode.

What I'd like, is to have the ability within tdarr to either Move the failed file to another location, or Delete the failed file from its current location.

This would enable my Media Download tools to spot the deleted/moved file and attempt to download another version.

This could be setup as either a Manual action to be confirmed within tdarr and/or a defined automated action to be performed when a failed Health Check or Transcode is encountered.

**Comment by HaveAGitGat** [comment]
I don't think it would make sense to have it for transcodes. The original file may be perfectly fine so there's no need to delete it just because of an incorrect transcode setting.

Could add it for failed health checks though.

**Comment by korzynski** [comment]
While a simple option to move or delete would be wonderful, why not also provide the ability to pass the files as an argument to any arbitrary command or script? This would allow users to process the files however they want, whether they move or delete them, send them to some other tool for additional processing, etc.

**Comment by HaveAGitGat** [comment]
@korzynski  Tdarr plugins already allow that: https://github.com/HaveAGitGat/Tdarr_Plugins

**Comment by HaveAGitGat** [comment]
Option to delete unhealthy files has been added to 2.00.14
![image](https://user-images.githubusercontent.com/43864057/153121245-864bf95d-d75b-48c3-9057-c9551c7d09cb.png)

**Comment by jacz24** [comment]
Sorry to dig this back up but. Delete seems to be a health check exclusive option. I would love this feature for failed transcodes. 99% of my library transcoded fine and 100% passed the health check. For whatever reason it can't transcode the 1%. Which makes me want to delete it as it's functionally unviewable. 

I get this is a transcode error somewhere in the pipeline but that's the point for me. If it can't be transcoded then it shouldn't exist. Is plugin support the only way to fix this? It seems pretty useful for the most part but I suppose its a fairly unrequested feature. If plugin support is the way I will work with it but I'm wondering if i'm missing something,
