### ISSUE TITLE
Tdarr Permissions Error with 3.4.5 Compatibility turned on

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#187]
I recently tried turning on FFMPEG 3.4.5 compatibility as I keep having random transcodes failing every 5-10 or so. This didn't happen previously when TDARR was using an older version of FFMPEG.

When turning on this compatibility, transcodes fail instantly with a permissions error. Turning this, off, transcodes work. So it doesn't seem to be a permissions error on the actual file itself. I have TDARR running as my user account in a docker container. I did try restarting the container after enabling this option.

Any Suggestions?

**Comment by HaveAGitGat** [comment]
Which container are you running?

**Comment by clifford64** [comment]
Tdarr with Mongo DB.

**Comment by HaveAGitGat** [comment]
Ok so that container is running alpine and FFmpeg hasn’t changed in that in a long time (several months). 

FFmpeg 3.4.5 is for running NVENC (hardware transcoding) which is only supported in tdarr_aio as mentioned in the setup instructions. 3.4.5 won’t work in the tdarr container. 

Do the files work when they’re requeued?

**Comment by clifford64** [comment]
Yeah, files work fine when re-queued. If I have a bunch still sitting in the queue, it is possible they will fail again or other files fail. I just have to remember to go back in and re-queue every so often if I download something.

**Comment by HaveAGitGat** [comment]
Are your files on a network drive? Seems like something is stopping ffmpeg reading the files part way through the transcode. Perhaps try turning off the worker stall detector on the 'Options' tab as that cancels any items which don't progress in 5 minutes.

**Comment by clifford64** [comment]
I don't have "auto-cancel stalled workers" turned on.

**Comment by HaveAGitGat** [comment]
> Are your files on a network drive?

**Comment by clifford64** [comment]
No, they are stored on a secondary drive attached to my Tdarr VM. Essentially, I have an ESXi host with a SAN attached to it. I have a VM that hosts all of my docker containers. Plex, Tdarr, etc... The VM has a boot  drive and a secondary drive that hosts all of my media.

**Comment by HaveAGitGat** [comment]
Perhaps try tdarr_aio as that is the more stable version with different ffmpeg versions to test.

Create a backup on the 'Backups' tab. Ensure that you have a copy of the backup stored in `/home/Tdarr/Documents/Tdarr/Backups` inside the container (the Tdarr folder should be mapped to somewhere on your host).  Start the tdarr_aio container and restore from that backup.

https://github.com/HaveAGitGat/Tdarr/wiki/2---Installation

**Comment by HaveAGitGat** [comment]
I'll be replacing tdarr with tdarr_aio at some point (so the 2 containers will be the same) so I can just focus on one container rather than having an alpine and ubuntu container. Should fix or at least make it easier to troubleshoot problems like this.

**Comment by clifford64** [comment]
After updating Tdarr so it is now the aio version, I am still having transcode failures. This time I am getting an error though.

frame=26400 fps= 90 q=29.6 size= 42496kB time=00:14:41.26 bitrate= 395.0kbits/s speed=3.01x

Segmentation fault (core dumped)
