### ISSUE TITLE
Restarting container restarts transcoding

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#188]
Hi,

Not entirely sure whether this is a bug, or I used to dream it did it before! When I restart the container, the items currently being processed start again from 0%. I have nightly backups at 6am, and wondered why the same file was processing every day (its a big file!).

**Comment by HaveAGitGat** [comment]
Hi, this is not a bug. If an encode is stopped for any reason such as being cancelled, shutdown or restarted then Tdarr restarts it from the beginning the next time that task is processed. Segmented transcoding isn't supported.

**Comment by jleck** [comment]
Ah, fair enough. Thanks!
