### ISSUE TITLE
Remuxing mkv is not working

### ISSUE THREAD

**Issue by spikemixture** [HaveAGitGat/Tdarr#189]
I have been putting some very long hours trying to get TDARR up and going.

Yesterday after something screwed up my setup I removed and started again.

I am using Docker on a Qnap 1277.

I installed and uninstalled it 20+ times (yes really) today to get it working.
Finally removed Container Station and installed from scratch to get where I am.

I am using Beta 1.106.

What i am trying to do is have tadarr go through my recently d/l media which is all  MKV some h264 and some h265.

I have created my own plugins to do this.
1. **Remux** all h264 and h265 tv shows that are under 500mb to mp4
2. **Convert** h264 shows (MKV) that are over 500mb to 720p and h265 in mp4

So the end result will be all tv shows under 500mb (and some under 1gb) in 720p (or lower)
**_So converting is working but the remux is not_**

**_var fs = require('fs');
    var path = require('path');
    if (fs.existsSync(path.join(process.cwd() , '/npm'))) {
    var rootModules = path.join(process.cwd() , '/npm/node_modules/')
    } else{
    var rootModules = ''
    }
   
    const importFresh = require(rootModules+'import-fresh');
    const library = importFresh('../methods/library.js')
      
    module.exports.details = function details() {

          return {
            id: "6KbcXUzJS",
            Name: "1. REMUX mkv <500",
            Type: "Video",
            Operation: "Remux",
            Description: "Remux all 264 and 265 under 500mb mkv to mp4",
            Version: "",
            Link: ""
          }
        }

    module.exports.plugin = function plugin(file) {
        
        
          //Must return this object at some point
        
          var response = {
        
             processFile : false,
             preset : '',
             container : '.mkv',
             handBrakeMode : false,
             FFmpegMode : true,
             reQueueAfter : true,
             infoLog : '',
        
          }

          response.infoLog += "" + library.filters.filterBySize(file,0.0,0.5).note + library.filters.filterByCodec(file,"include","hevc,h264").note
        
          
          if((true &&library.filters.filterBySize(file,0.0,0.5).outcome === true &&library.filters.filterByCodec(file,"include","hevc,h264").outcome === true) || file.forceProcessing === true){

             
              response.preset = ', -map 0 -c copy'
              response.container = '.mp4'
              response.handBrakeMode = false
              response.FFmpegMode = true

              response.reQueueAfter = true;
              response.processFile = library.actions.remuxContainer(file, 'mp4').processFile
              response.infoLog +=  library.actions.remuxContainer(file, 'mp4').note
              return response
        
        
             }else{

              response.processFile = false;
              response.infoLog += library.actions.remuxContainer(file, 'mp4').note
              return response
        
        
             }
        }_**

**Comment by HaveAGitGat** [comment]
Hi, are you able to go into a bit of detail on how it doesn't work for you?

**Comment by spikemixture** [comment]
Not much I can add. 

The titles that are under 500mb and h264 do not get remuxed from .mkv to .mp4

The titles getting converted from mkv to mp4 that are over 500mb are getting done.
But they are converting. 
The under 500mb I just want remux (mkv to mp4)

**Comment by HaveAGitGat** [comment]
Sure there is:

Do the files move from the queue to the transcode success or transcode error tabs?

For either, what does the info 'i' button show for the success/error log on those tabs. 

Also, what codec are the files in? I can see the plugin says to include h264 and hevc. Might the files be in something else?

**Comment by spikemixture** [comment]
Thanks HAGG,  
hows this?


"HealthCheck": "Success",
  **"TranscodeDecisionMaker": "Transcode error",**
  "cliLog": "Command: \r\n/home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg  -i '/media/tv/Schitt'\"'\"'s Creek/Schitt'\"'\"'s Creek - S06E12 - The Pitch WEBRip-480p.mkv'  -map 0 -c copy '/media/backup/tmp/Schitt'\"'\"'s Creek - S06E12 - The Pitch WEBRip-480p-TdarrCacheFile-lbVnjw55-.mp4' \r\nffmpeg version N-95955-g12bbfc4 Copyright (c) 2000-2019 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)\n  configuration: --prefix=/home/z/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/z/ffmpeg_build/include --extra-ldflags=-L/home/z/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/z/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree\n\r\n  libavutil      56. 36.101 / 56. 36.101\n  libavcodec     58. 64.101 / 58. 64.101\n  libavformat    58. 35.101 / 58. 35.101\n  libavdevice    58.  9.101 / 58.  9.101\n  libavfilter     7. 67.100 /  7. 67.100\n  libswscale      5.  6.100 /  5.  6.100\n  libswresample   3.  6.100 /  3.  6.100\n  libpostproc    55.  6.100 / 55.  6.100\n\r\nInput #0, matroska,webm, from '/media/tv/Schitt's Creek/Schitt's Creek - S06E12 - The Pitch WEBRip-480p.mkv':\n  Metadata:\n    encoder         : libebml v1.3.5 + libmatroska v1.4.8\n    creation_time   : 2020-03-25T04:11:23.000000Z\n  Duration: 00:21:53.30, start: 0.000000, bitrate: 1204 kb/s\n\r\n    Stream #0:0: Video: h264 (High), yuv420p(progressive), 720x404 [SAR 404:405 DAR 16:9], Closed Captions, SAR 254:255 DAR 3048:1717, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)\n    Metadata:\n      BPS-eng         : 1012780\n      DURATION-eng    : 00:21:53.271000000\n      NUMBER_OF_FRAMES-eng: 31487\n      NUMBER_OF_BYTES-eng: 166256901\n      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit\n      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-25 04:11:23\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n    Stream #0:1(eng): Audio: aac (LC), 44100 Hz, stereo, fltp (default)\n    Metadata:\n      BPS-eng         : 189588\n      DURATION-eng    : 00:21:53.297000000\n      NUMBER_OF_FRAMES-eng: 56559\n      NUMBER_OF_BYTES-eng: 31123290\n      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit\n      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-25 04:11:23\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n    Stream #0:2(eng): Subtitle: subrip (default)\n    Metadata:\n      BPS-eng         : 151\n      DURATION-eng    : 00:21:17.975000000\n      NUMBER_OF_FRAMES-eng: 547\n      NUMBER_OF_BYTES-eng: 24218\n      _STATISTICS_WRITING_APP-eng: mkvmerge v22.0.0 ('At The End Of The World') 64-bit\n      _STATISTICS_WRITING_DATE_UTC-eng: 2020-03-25 04:11:23\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n\r\n[mp4 @ 0x5565036c7fc0] Could not find tag for codec subrip in stream #2, codec not currently supported in container\n\r\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\nStream mapping:\n  Stream #0:0 -> #0:0 (copy)\n  Stream #0:1 -> #0:1 (copy)\n  Stream #0:2 -> #0:2 (copy)\n\r\n    Last message repeated 1 times\n\r\n",
  "bumped": false,
  "history": "-------------------------------------\nDate:2020-03-26T06:01:02.286Z\nSize:0.1978GB\nStreams:\n<table className=\"streamsTable\"><tbody><tr><td><p>h264</p></td><td><p>video</p></td><td><p>-</p></td><td><p>-</p></td><td><p>-</p></td></tr><tr><td><p>aac</p></td><td><p>audio</p></td><td><p>-</p></td><td><p>eng</p></td><td><p>-</p></td></tr><tr><td><p>subrip</p></td><td><p>subtitle</p></td><td><p>-</p></td><td><p>eng</p></td><td><p>-</p></td></tr></tbody></table>",
  "lastHealthCheckDate": "2020-03-26T06:01:32.169Z",
  "lastTranscodeDate": "2020-03-26T06:01:55.957Z",
  "tPosition": 0,
  "hPosition": 0

**Comment by Migz93** [comment]
`Could not find tag for codec subrip in stream #2, codec not currently supported in container`
That specific file failed because one of the streams within the plugin isn't supported in mp4.

Is this a plugin you created yourself? Or using Tdarrs plugin creator?

**Comment by HaveAGitGat** [comment]
> hows this?

To be fair, you didn’t directly answer any of my questions. Instead you posted a snippet from a different part of the application.

Regardless, the log shows that the subrip subtitle codec of your files is not supported in mp4.

So you can:
- Convert the subtitle codec
- Remove the subtitles
- Use a different container

More info on codecs/containers here:
https://en.m.wikipedia.org/wiki/Comparison_of_video_container_formats

**Comment by spikemixture** [comment]
> `Could not find tag for codec subrip in stream #2, codec not currently supported in container`
> That specific file failed because one of the streams within the file isn't supported in mp4.
> 
> Is this a plugin you created yourself? Or using Tdarrs plugin creator?

This one I created. 
As I just want files less than 500mb that are mkv to be remuxed as mp4

**Comment by HaveAGitGat** [comment]
> This one I created.

I’m 99% sure you used the Tdarr plugin creator GUI for that which is on the contrary to coding it yourself which is what Migz was getting at. He was trying to determine if it was a bug in your code or one in Tdarr’s code but it is neither. It’s a container/codec compatibility issue unfortunately. 

I normally just remove subs so that there’s no issue with mp4 containers and then I use Bazarr for non-embedded subs.

**Comment by spikemixture** [comment]
Thanks for the feedback and replies.

I may try some other plugin that will remove the subtitles.

Although I use a program called MCEBuddy that simply changes from MKV to mp4.

Tdarr does more but just not one of my daily "automations"

**Comment by HaveAGitGat** [comment]
This will remove subtitles:

Tdarr_Plugin_x7ab_Remove_Subs 

So you’ll need to put that above the remux plugin in your stack. 

Ideally down the line there’d be an option to automatically convert subtitle codecs when remuxing (if the user wants that).

**Comment by spikemixture** [comment]
> **Ideally down the line there’d be an option to automatically convert subtitle codecs when remuxing (if the user wants that).**

yep

**Comment by spikemixture** [comment]
> So you’ll need to put that above the remux plugin in your stack.
**Of which "remux plugin" do you speak?**

**Comment by HaveAGitGat** [comment]
@spikemixture not sure if you still use this but FYI this is how to create a remux plugin:
![image](https://user-images.githubusercontent.com/43864057/144358689-8bec9215-1872-4f61-a7df-e2013d02ba66.png)
![image](https://user-images.githubusercontent.com/43864057/144358737-96cf2f97-3e1a-4e0f-8959-a38d249c1e4e.png)
