### ISSUE TITLE
Feature Request - Enhanced worker Info

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#19]
It would be super great to add a bit more info to the worker windows.  E.g. in handbrake I can usually see things like how long it's been running for / time remaining and estimated output size.  Probably some other things can be done too, like listing the original file size.

**Comment by Torqu3Wr3nch** [comment]
Seconded. Info doesn't necessarily have to come from Handbrake itself- could simply be a running ETA based on time running and current progress.
