### ISSUE TITLE
UI Work

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#190]
Hi,

I work in software development, specialising in JS (react and node for the most part). Would you be open to some PRs? I'd probably start with improving the frontend UI, unless you wanted help in a particular area?

**Comment by HaveAGitGat** [comment]
Which parts are you looking to change/improve?

**Comment by jleck** [comment]
Hi,

I was thinking of starting with the general layout and styling, adding some consistent padding etc. I would probably look at the build process to remove the inline CSS.

**Comment by HaveAGitGat** [comment]
Sure that’s fine. Keep the PRs small and the comments detailed please 👍.
