### ISSUE TITLE
CUDA support where possible

### ISSUE THREAD

**Issue by vegovs** [HaveAGitGat/Tdarr#192]
Allow tdarr to use GPU when possible.

**Describe the solution you'd like**
If GPU is available, and ffmpeg has CUDA support for selected transcoding config, use GPU. :) 

**Additional context**
Here is a link to [NVIDIA FFmpeg Transcoding Guide](https://devblogs.nvidia.com/nvidia-ffmpeg-transcoding-guide/)

**Comment by Migz93** [comment]
Tdarr already supports using NVENC & NVDEC? You just have to select/create a plugin with the relevant commands to use it.

**Comment by HaveAGitGat** [comment]
Docker container tdarr_aio and Tdarr for Windows already support hardware transcoding and there are numerous plugins for nvenc to draw inspiration from.

For unraid follow these steps first:Enable NVENC: https://forums.unraid.net/topic/77813-plugin-linuxserverio-unraid-nvidia/
