### ISSUE TITLE
[Request] Split plugins between filter and action

### ISSUE THREAD

**Issue by nininhocovre** [HaveAGitGat/Tdarr#193]
**Is your feature request related to a problem? Please describe.**
Let's suppose I create a plugin that does the transcoding I want but I have one library I would like to transcode all videos and one other library that I only want to transcode the files larger than 2 GB.
Currently, I would have to create a plugin without the filter and another plugin with the filter.

**Describe the solution you'd like**
Remove the filter option from creating a new plugin and have it on the library configuration to filter for size or codec the plugin.
This way the plugin would have the action(transcode, remux) and on the library I could have a filter (or maybe can have filter plugins) for which files I want to process. So in the case, I mentioned I would need only one plugin and I could filter the files on the library config.

**Additional context**
This way the plugins could be more generic like focusing on transcodes, since the community plugins are somehow very specific to the author's use case but if you want some minor change you need to copy and edit the plugin, which can be difficult for someone without a coding background.

**Comment by HaveAGitGat** [comment]
Actions and filters used to be separate. If you create a plugin with Operation ‘Filter’ then you can use it separate to the action. 

I added a new plugin category ‘Filters’ in the plugin browser in the last update and would like to add a bunch of filters in the future.

**Comment by HaveAGitGat** [comment]
I added a filter example last month:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Tdarr_Plugin_bbbb_Filter_Example.js
