### ISSUE TITLE
Number of Transcoding threads based on action taken

### ISSUE THREAD

**Issue by OuticNZ** [HaveAGitGat/Tdarr#197]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem.  It's an idea to improve the efficiency of the transcoding queue.  

**Describe the solution you'd like**
Different transcode actions have differing constraining factors about them, i.e. a container remux really only taxes the CPU/DISK, while a transcode operation may impact CPU/GPU.  Is there a way to have transcode threads based on the type of transcode.  This setup is only useful if you are processing a large collection for the first time.  I want 4 threads to move video to first stream.  4 threads for audio cleaning,  I then want 2 threads for GPU transcoding and 1 for CPU transcoding.  

**Describe alternatives you've considered**
You can achieve this by running multiple passes over the files.  And as I'm typing this up I'm questioning the value of being able to do this vs just running more transcoding threads as they are.  But I thought I'd throw it out there anyway.    

**Additional context**
None.

**Comment by OuticNZ** [comment]
Further to this I've done a picture to help illustrate.  While files are being copied essentially the CPU/GPU are idle this is down time for encoding.   By assigning tasks to different thread worker pools you can keep the CPU/GPU always busy.   Maybe the answer is just run more transcode threads in the current setup.  But I thought this idea was interesting.

Worker Pool 1 - GPU based actions
Worker Pool 2 - Responsible for copying completed files to the correct locations
Worker Pool 3 - CPU based actions
Worker Pool 4 - Unassigned

![image](https://user-images.githubusercontent.com/30253830/78597177-24c24280-78a1-11ea-9973-119f4e036d95.png)

**Comment by HaveAGitGat** [comment]
Sure this is a nice idea but would complicate things a lot both on the user interface and the backend. Some people have enough trouble as it is with the 3 worker types available already. Remuxing and manipulating audio are generally quick processes which only take a couple of mins depending on drive speed. 

I think it's uncommon to be mixing GPU and CPU transcoding as they both have very different aims  in terms of speed/quality/time.

This is definitely a feature which would only benefit a small number of power users and would require large parts of the application to be re-done so it's not a priority for me but perhaps at a later stage in the project.
