### ISSUE TITLE
pause and resume transcodes without canceling workers.

### ISSUE THREAD

**Issue by emilio215** [HaveAGitGat/Tdarr#199]
**Describe the solution you'd like**

pause and resume transcodes without canceling a task altogether.

**Describe alternatives you've considered**
i've managed to accomplish this with  a MS supplied executable called pssuspend

https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend

my .bats look like

##suspend
pssuspend handbrakecli.exe

##resume
pssuspend handbrakecli.exe -r

works with the ffmpeg exe as well.

while a process is suspended the UI in tdarr works as you'd expect it to

the only issues i've encountered with this is that, handbrakecli encodes from a network drive sometimes fail to resume and those tasks get canceled and skipped.

**Comment by HaveAGitGat** [comment]
Thanks for having a go - like you say it's not the most elegant/reliable solution which is why I've avoided methods like this. Also it's not cross-platform although there are some similar tools for other operating systems. Some food for thought though.

**Comment by Wdavery** [comment]
Would love to see some sort of pause functionality added. Could be quite handy.

**Comment by hapklaar** [comment]
Me too! Would be really useful to be able to pause operations, for example when wanting to game.

PS thanks for this amazing piece of software I just discovered today ;)

**Comment by hapklaar** [comment]
@HaveAGitGat I just found this button, but can't turn it off. Could this be used for it?

**Comment by HaveAGitGat** [comment]
@hapklaar which button?

**Comment by HaveAGitGat** [comment]
Will close this as a straightforward cross-platform method is currently not achievable.

**Comment by OddBloke** [comment]
For anyone else who winds up here, a quick hack I've found for Docker is:

**Comment by OddBloke** [comment]
For anyone using Docker looking for a quick hack, you can use the `STOP` signal to pause ffmpeg's execution:

```
docker exec <container_name> pkill --signal STOP ffmpeg
```

and `CONT` to resume it:

```
docker exec <container_name> pkill --signal CONT ffmpeg
```
