### ISSUE TITLE
Information popup "undefined"

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#2]
The information popup for successfully completed transcodes shows "undefined".

**Comment by HaveAGitGat** [comment]
Hi @Xe123 yes that’s how it should be for the moment but I’ll make it more presentable soon.

If the transcode is “Passed” then it shows the reason why in that box. For example “File is already in correct codec”.


Transcode success shows nothing as there is not really any information to show :)

**Comment by HaveAGitGat** [comment]
Fixed for next release
