### ISSUE TITLE
Only overwrite file if transcode size is lower

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#201]
It would be great if we could have a feature to disable overwriting of the original file if the transcoded file is larger. I’m using an nvidia card and occasionally the hevc is larger than the h264 source.

**Comment by HaveAGitGat** [comment]
I don’t think this a good feature to have because there’s no point spending hours transcoding a file and then for that processing time to be wasted and the new file discarded.

It’s far better to set a maximum bitrate so the new file is guaranteed to be smaller than the old file. I’m working on a new default-enabled plugin with this functionality. There is also `Tdarr_Plugin_MC93_Migz1FFMPEG ` which you can tweak to your liking. Change the target bitrate on line 78 as it by default aims for a 50% bitrate.

**Comment by jleck** [comment]
This would be kind of a file safe, but I have setup plugins now and it does seem better.

However, it seems to be making my system crawl, even when the CPU isn't pegged. I'm not sure, but I'm wondering if its something to do with the speed of my unraid array.

Is there any way in plugins to change the path to be used? Then I could copy the file to the cache disk before processing.

**Comment by Migz93** [comment]
@jleck Why don't you just change the cache location for your libraries to be on your cache disk?

**Comment by jleck** [comment]
Do you mean in tdarr? That just changes the output, the input still stays as the array (AFAIK)

**Comment by Migz93** [comment]
The "Transcode Cache" location is where files are copied to temporarily to be worked on by tdarr, once that plugin is complete they are either moved to the original location or to the output folder.
"Transcode Cache" does exactly what you want it to.

**Comment by jleck** [comment]
I don't think that's true. Take for example the current command being run:

```
/home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg -i /mnt/user/movies/The Nutcracker and the Four Realms (2018)/The Nutcracker and the Four Realms (2018).mkv -map 0 -map -0:s:0 -map -0:s:1 -map -0:s:2 -c copy -max_muxing_queue_size 4096 /home/Tdarr/cache/The Nutcracker and the Four Realms (2018)-TdarrCacheFile-BnyqBlgYc.mkv
```

`/mnt/user` is my array.

**Comment by Migz93** [comment]
@HaveAGitGat can you confirm? I was under the impression that files were copied to the transcode cache first before being worked on?

**Comment by jleck** [comment]
You can see from the ffmpeg commands that it runs, the input is always the original file location. I wouldn't think its a good idea to copy by default, that would add an unnecessary time penalty.

**Comment by Migz93** [comment]
Just because it does that currently doesn't mean that's the intended function.

So you want a feature to be able to copy the files to cache before being worked on, but then you don't want it because it would add an unnecessary time penalty?

**Comment by jleck** [comment]
> by default

It would be useful when reading from a slow location. If you have you good enough read speed it wouldn't be of any help.

**Comment by jleck** [comment]
I've done a bit more investigating, and I think I have an erroring disk in my array, which is causing very slow read speeds and locking up. This shows up more with tdarr as its reading at a higher rate than playing back the file.

It would still be useful to be able to move the complete file over over to the cache disk before transcoding, as then my array wouldn't have to stay spinning during transcoding.

I've however moved to only transcoding overnight, so I will close this issue.
