### ISSUE TITLE
Allow plugin to gracefully error and keep infoLog

### ISSUE THREAD

**Issue by OuticNZ** [HaveAGitGat/Tdarr#205]
**Is your feature request related to a problem? Please describe.**
Currently if a plugin detects and error it either must throw an exception or set response.processFile to false.  Neither really provide match clarity.  When response.processFile is set to false the file just ends up in Transcode Success/Not Required which isn't correct, and if you throw an Error exception you lose all your response.infoLog output.  

**Describe the solution you'd like**
Allow a response return status to indicate that the plugin errored and place the file into the transcode error/cancelled tab.  Keep the response.infoLog output as well.  

**Describe alternatives you've considered**
I'm currently using throw new Error.  But I lose the infoLog detail for that job.  

`throw new Error('\nERROR: ${err.name}\n\n ${err.message}\n${errormsg}');`

**Comment by HaveAGitGat** [comment]
How about a new response key for if there has been an error in the plugin or not?

For example:
![image](https://user-images.githubusercontent.com/43864057/80312752-eb655e80-87de-11ea-9bba-00e58bb35704.png)

![image](https://user-images.githubusercontent.com/43864057/80312729-b1945800-87de-11ea-82d0-97c9d85605fb.png)

**Comment by HaveAGitGat** [comment]
Obviously the above wouldn't fire if there's a genuine error so it would be best to wrap the plugin function in a try/catch block and use it:
![image](https://user-images.githubusercontent.com/43864057/80314164-be697980-87e7-11ea-8703-4a89b3b82ea6.png)

**Comment by HaveAGitGat** [comment]
This was added last year, should work now.
