### ISSUE TITLE
Tdarr "thorough" health check does not detect files with known decode errors

### ISSUE THREAD

**Issue by TheFeshy** [HaveAGitGat/Tdarr#206]
**Describe the bug**
I happened to be working on a similar program to monitor a library and run each video through ffmpeg as a health check, much like Tdarr does. So I have some test videos with errors I have introduced (hex edited a few frames with garbage and/or deletions) that I was using as test files.  I added these to a library in Tdarr, set the health check to "thorough", and did a "Scan (Fresh)" on the library.  All videos (except the empty one which was found to be an error by ffprobe) show status "Successful" in the Stats "Health" page.

I can manually verify the errors are found with ffmpeg:

```
$>ffmpeg -i ~/Projects/videoverify/test/testdata/bad1_480.mp4 -v error -f null -max_muxing_queue_size 9999 -"
[aac @ 0x556ec4ca3e00] channel element 0.0 is not allocated
Error while decoding stream #0:1: Invalid data found when processing input
[aac @ 0x556ec4ca3e00] channel element 0.0 is not allocated
Error while decoding stream #0:1: Invalid data found when processing input
[h264 @ 0x556ec4dbb7c0] error while decoding MB 5 11, bytestream -6

```

**To Reproduce**

1. Download my test videos [here](https://drive.google.com/file/d/1DS2vk2GFAtAd-pv1fTheDuBYjC0-P_sg/view?usp=sharing) (videos are 5 second clips from the CC licensed "Big Buck Bunny" and are legal to share), or make your own by hex-editing a short video clip and doing some random damage

2. Extract them to a folder

3. Add the folder to Tdarr as a library, being certain to set health checks to "thorough"

4. Choose "Scan (Fresh)" from the library

5. Observe the stats - one error, representing the zero-length file that failed ffprobe, 4 "success" files representing healthy video files

**Expected behavior**
Two of the video files should be identified in stats as having health errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Docker (latest haveagitgat/tdarr_aio) running on Arch linux
 - Browser: Firefox
 - Version: Beta 1.108

**Additional context**
ffprobe error shows up in the log, ffmpeg error check only shows "completed" in log.

**Comment by HaveAGitGat** [comment]
Hi, files are only marked as corrupt if HandBrake/FFmpeg give a non-zero exit. Could start parsing the output for specific errors as you’ve suggested.

**Comment by TheFeshy** [comment]
I'm not familiar with handbrake's check, but I have seen ffmpeg return hundreds of errors, but a successful (zero) error code.  The only time I recall it returning an error code is if it can't read the header - and that's already caught by ffprobe.

**Comment by HaveAGitGat** [comment]
I've had FFmpeg error out due to bad/glitchy frames half way through a file so it does provide some use as it is. 

Also there is the issue that some errors don't really have any effect on the transcode process so it depends on how thorough the check needs to be.

There's a nice list of errors here so could add those in:
https://ffmpeg.org/doxygen/3.1/group__lavu__error.html

**Comment by HaveAGitGat** [comment]
This has been amended for 1.109

This file contains a list of ffmpeg errors which output will be checked for:
https://github.com/HaveAGitGat/Tdarr/blob/66af948f7e419072ae692dfbcfe7f2f0c31d6844/private/ffmpegErrors.js
