### ISSUE TITLE
Increase memory usage ?

### ISSUE THREAD

**Issue by extremeshok** [HaveAGitGat/Tdarr#208]
More of a question, is there a way to increase memory usage to speed up the transcode process ??

I am already using a ram drive (/dev/shm) for the transcode cache

I still have 220GB of memory free..

**Comment by HaveAGitGat** [comment]
Hi, this is not possible. HandBrake and FFmpeg are optimised to use a certain amount of RAM depending on file/transcode conditions. Additional RAM will make no difference as the bottleneck will be disk i/o, network, CPU etc.
