### ISSUE TITLE
ffprobe side_data

### ISSUE THREAD

**Issue by NowyQuei** [HaveAGitGat/Tdarr#209]
Hi

I wanna convert original UHD with HDR content to x256 but for that i need the side_data informations from ffprobe.
For example:
ffprobe -loglevel quiet -read_intervals "%+#2" -select_streams v:0 -show_entries side_data "${INPUT}" | egrep -m 1 -A 10 'Mastering display metadata' | grep -v 'Mastering display metadata'
ffprobe -loglevel quiet -read_intervals "%+#2" -select_streams v:0 -show_entries side_data "${INPUT}" | egrep -m 1 -A 2 'Content light level metadata' | grep -v 'Content light level metadata'

This infos are needed to bypass HDR informations from original source to the converted MP4 or MKV file.

maybe the informations are already covered but they seems not to be in the example on the page:
https://github.com/HaveAGitGat/Tdarr_Plugin_nc7x_Example

by the way it would be perfect if we can run ffprobe by ourself with own settings.

**Comment by HaveAGitGat** [comment]
Hi, ffprobe can be accessed inside a plugin like this:

```
const fs = require("fs");
const path = require("path");
let rootModules;
if (fs.existsSync(path.join(process.cwd(), "/npm"))) {
    rootModules = path.join(process.cwd(), "/npm/node_modules/");
} else {
    rootModules = "";
}

const ffprobePath = require(rootModules + 'ffprobe-static').path;
//do something with ffprobe
```

I have updated the plugins readme with this.
