### ISSUE TITLE
Feature Request - Worker Queue Current # out of Total #

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#21]
On the Tdarr tab, for each worker queue, is it possible to show the number of the current item and the number of items in the entire queue? Currently the queue just shows up to 20 so i'm wondering if somewhere in the actual worker boxes itself, could the item display like:

1 of 2,341
2 of 2,341
3 of 2,341

If you had three workers running.

**Comment by marshalleq** [comment]
Great idea.

**Comment by Torqu3Wr3nch** [comment]
I've thought the same thing. Would be nice to know where we are in the stack. In the meantime, I look in the "Stats" section.

**Comment by HaveAGitGat** [comment]
Added in 1.003
