### ISSUE TITLE
Windows v1.108 Install - Missing fibers.node. Cant Install

### ISSUE THREAD

**Issue by townsmcp** [HaveAGitGat/Tdarr#211]
**Describe the bug**
Cant install v1.108 in Windows 10. Error message when trying to install.

**To Reproduce**
- Install Mongo from the install instructions link
- Install node.js 8 as per instructions
- Load command prompt as Administrator
- Paste the install text. Getting the following error message:

> C:\Users\james\Downloads\Tdarr-Windows\bundle>set MONGO_URL=mongodb://localhost:27017/Tdarr
> 
> C:\Users\james\Downloads\Tdarr-Windows\bundle>set PORT=8265
> 
> C:\Users\james\Downloads\Tdarr-Windows\bundle>set ROOT_URL=http://localhost/
> 
> C:\Users\james\Downloads\Tdarr-Windows\bundle>node --max_old_space_size=8152 main.js
> ## There is an issue with `node-fibers` ##
> `C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\bin\win32-x64-72\fibers.node` is missing.
> 
> Try running this to fix the issue: C:\Program Files\nodejs\node.exe C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers/build
> Error: Cannot find module 'C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\bin\win32-x64-72\fibers'
> Require stack:
> - C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\fibers.js
> - C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\boot.js
> - C:\Users\james\Downloads\Tdarr-Windows\bundle\main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:526:27)
>     at Module.require (internal/modules/cjs/loader.js:666:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\fibers.js:14:39)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Module.require (internal/modules/cjs/loader.js:666:19)
> C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\fibers.js:23
>                 throw new Error('Missing binary. See message above.');
>                 ^
> 
> Error: Missing binary. See message above.
>     at Object.<anonymous> (C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers\fibers.js:23:9)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Module.require (internal/modules/cjs/loader.js:666:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\boot.js:1:13)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> 
> C:\Users\james\Downloads\Tdarr-Windows\bundle>

Ive tried running the following as suggested in the error message:

> C:\Program Files\nodejs\node.exe C:\Users\james\Downloads\Tdarr-Windows\bundle\programs\server\node_modules\fibers/build
No joy.
The error message states fibers.node should be inside directory 'win32-x64-72' however that directory doesnt exist. There is only 'win32-x64-57' and win32-x64-64'.

**Expected behavior**
Install Tdarr.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Additional context**
I am running NVM for Windows and therefore have NodeJS installed with version 8 and 12 (other apps require 12). However, using NVM, I have set default NodeJS version to 8 but this still isnt working. Followed instructions found here:
https://medium.com/appseed-io/how-to-run-multiple-versions-of-node-js-with-nvm-for-windows-ffbe5c7a2b47

**Comment by HaveAGitGat** [comment]
Are you sure version 8 is being used? What happens when you input `node -v` before running the Docker run command?

**Comment by townsmcp** [comment]
In the end I went with adding a container into Docker (running on Windows 10 WSL 2). Seems ot be working well so far so closing this thread.
