### ISSUE TITLE
Forcing changing container without changing codec.

### ISSUE THREAD

**Issue by RafalGoslawski** [HaveAGitGat/Tdarr#213]
I can't seem to find a plugin that would change the container (i.e. mkv -> mp4) when the codec is already correct. Am I missing something, or is there no such option right now?

**Comment by HaveAGitGat** [comment]
On the Plugins tab you can use the plugin creator to make a ‘Remux container ‘ plugin.

**Comment by RafalGoslawski** [comment]
Thanks HaveAGitGat! Exactly what I was looking for. 

On the side note, the option and information seems a bit hidden. 
```
Remux container

This action has a built-in filter. Additional filters can be added above.
```
This is only visible after selecting 2 separate dropdown options. Might need a UX improvement (I only looked for filters in add filter section).
