### ISSUE TITLE
nice + ionice

### ISSUE THREAD

**Issue by pefman** [HaveAGitGat/Tdarr#220]
**Is your feature request related to a problem? Please describe.**
my problem is that sub processes to tdarr is using all the available resources such as cpu and io load.

**Describe the solution you'd like**
The option to throw in arguments such as nice and ionice to avoid an overloaded system.

**Describe alternatives you've considered**
haven't tried anything honestly.

**Comment by theg00s3** [comment]
Doesn't the low cpu priority toggle already do nice?

**Comment by HaveAGitGat** [comment]
Yes the low cpu priority toggle already does this although it will have no effect running inside a Docker container. It's best to pin cores when running a Docker container.

**Comment by pchang388** [comment]
I stumbled upon this issue, but @HaveAGitGat this doesn't address disk io specifically. 

Looking at other apps like sabnzbd as an example, they provide the ability to set lower priority for `ionice` parameters. For users like me using docker compose and a network share/NFS, what is the recommended way to lower priority ( or throughput ) of disk IO usage?

Example from [sabnzbd](https://digiex.net/threads/fine-tune-sabnzbd-to-stop-cpu-hdd-abuse-when-running-other-apps-plex-xbmc.12083/)
