### ISSUE TITLE
Misspelled Word - "Heath check"

### ISSUE THREAD

**Issue by joshualouden** [HaveAGitGat/Tdarr#222]
**Describe the bug**
On page /tdarr/ worker displays misspelled word, as "Heath check". 

**To Reproduce**
Visit /tdarr/, and set a worker. 

**Expected behavior**
The verbiage should be "Health check".

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks. Fixed in: https://github.com/HaveAGitGat/Tdarr/commit/25ea95a52da3305a68e0caca3bee21651ee3b6a0
