### ISSUE TITLE
Latest version fills up the entire disk with journal logs

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#224]
**Describe the bug**
Since upgrading to version 109, my virtual machine journal logs fill up the space on the disk

**To Reproduce**
Ubuntu 18.04 running 109 fills up the entire disk, 108 doesn't experience the same issue.

**Expected behavior**
Disk doesn't fill up

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 109

**Comment by HaveAGitGat** [comment]
The logs should only take up 3 MB - one main log with 2 backups.

https://github.com/HaveAGitGat/Tdarr/blob/2f3e67ea6ea7447550e9d90dc1a973e9f7a151a9/server/logger.js#L10

How large are the logs?

**Comment by HaveAGitGat** [comment]
Please reopen if you still have issues with this.
