### ISSUE TITLE
QSV in Windows

### ISSUE THREAD

**Issue by cappannonno** [HaveAGitGat/Tdarr#225]
Since I'm not seeing it in the readme, I'll ask here.
I cannot understand if qsv is working on windows and, if not, a workaround could be with WSL docker. Can you help me?
Thanks for the incredible work you do :)

**Comment by HaveAGitGat** [comment]
You can use task manager to see if QSV is working on Windows. If it's working then the GPU will show activity in the Encode and Decode sections.
