### ISSUE TITLE
Expand foldersToIgnore to include files as well

### ISSUE THREAD

**Issue by gregoryduckworth** [HaveAGitGat/Tdarr#227]
**Is your feature request related to a problem? Please describe.**
I use Sonarr which renames files to include the format either x264/x265 this happens at a file level rather than the folder, so it would be nice if these could be ignored.

**Describe the solution you'd like**
Add option to have filesToIgnore.

**Describe alternatives you've considered**
Renaming the folders to include the format.

**Comment by HaveAGitGat** [comment]
![image](https://user-images.githubusercontent.com/43864057/87089866-5992bc80-c237-11ea-84d0-58c3cb717cb5.png)

This box allows file names to be ignored too, does that work for you?

**Comment by HaveAGitGat** [comment]
Feel free to re-open if it's not working. Just tested and it seems to be working fine.
