### ISSUE TITLE
Closed captions plugin. doesn't recognize the CC608 closed captions. Handbrake does identify them

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#228]
**Describe the bug**
The plugin: Remove Closed Captions: Tdarr_Plugin_x7ac_Remove_Closed_Captions.js 
doesn't recognize the CC608 closed captions and therefor doesn't remove them.
Plex does shows it as (unknown) closed captions
Mediainfo doesn't report it.
Handbrake shows it as (english) Closed Caption CC608.

**To Reproduce**
I can provide a sample file

**Expected behavior**
The plugin to recognize this closed caption and start the removal action.

**Comment by HaveAGitGat** [comment]
At what point do the closed captions start? Tdarr only checks the first second of video (else scanning files would take days) so I suspect it's that the closed captions don't start until a few mins into the media.

**Comment by michpas** [comment]
Hi. Thanks for the reply. Actually, the closed captions start immediate with the video
I will add link to a sample file. Hope this provides helpful insight into why this Closed Caption is not recognized.
https://ufile.io/ackb4j1u
Sorry, it is a rather large file. Hope that is ok.

**Comment by HaveAGitGat** [comment]
Sorry I missed that (also not sure if the file is protected) but let me know if you have a drm-free sample and I'll take a look. Thanks.

**Comment by HaveAGitGat** [comment]
Feel free to reopen.
