### ISSUE TITLE
Hard links instead copying

### ISSUE THREAD

**Issue by simse** [HaveAGitGat/Tdarr#229]
**Is your feature request related to a problem? Please describe.**
My problem is that when processing files it takes longer to move them around than actually processing. It also appears to move the files back and forth between the processing folder and library.

**Describe the solution you'd like**
Allow users to enable hard linking instead of copy.

**Describe alternatives you've considered**
None

**Additional context**
Allowing hard links would reduce processing time for my library significantly, and also reduce I/O. It should also be quite simple to implement.

**Comment by Migz93** [comment]
Hard links are not something tdarr would ever use?
Hard links are for when you want a copy of a file somewhere else without taking up twice the space. Tdarr never has or wants a copy of a file so hard links aren't a thing. 

I think what you mean is you want it to instantly move it rather then copy it but that's how it works for me:
When a file in my source library is up to be worked on, its read directly from the source and written into the cache location. No extra IO there. Once the plugin has finished the file is moved back to the source location, verified that this is an instant move and not a copy. No extra IO there. 

How are you running tdarr? In a container? 
If so what paths have you mapped through and what paths are you using for your library and for your cache?

**Comment by simse** [comment]
> verified that this is an instant move and not a copy

That means that it _is_ in fact hard linking. Thanks for letting me know, I'll fix the container mapping.

**Comment by Migz93** [comment]
No problem
