### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by nyid** [HaveAGitGat/Tdarr#23]
Hello! I'm using Tdarr docker container with Unraid. The application unexpectedly crashed and the container is no longer running. This is the last bit in the log:

> <--- Last few GCs --->
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 
> [1:0x5569dccd80e0] 82052488 ms: Scavenge 1160.6 (1219.3) -> 1144.9 (1219.3) MB, 3.4 / 0.0 ms (average mu = 0.121, current mu = 0.060) allocation failure
> [1:0x5569dccd80e0] 82052602 ms: Scavenge 1160.6 (1219.3) -> 1144.9 (1219.3) MB, 3.5 / 0.0 ms (average mu = 0.121, current mu = 0.060) allocation failure
> [1:0x5569dccd80e0] 82052838 ms: Scavenge 1160.9 (1219.8) -> 1145.4 (1219.8) MB, 3.3 / 0.0 ms (average mu = 0.121, current mu = 0.060) allocation failure
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> 0: ExitFrame [pc: 0xa843025be1d]
> 1: StubFrame [pc: 0xa84302840b1]
> Security context: 0x36031851e6e9 <JSObject>
> 2: onread(aka onStreamRead) [0x2f9548c55361] [internal/stream_base_commons.js:87] [bytecode=0x37fc637c9a9 offset=0](this=0x0f98f252fa81 <TCP map = 0x1fe978ae19a1>,nread=65536,buf=0x179a78804a09 <Uint8Array map = 0x11dafdc0e4e9>)
> 3: InternalFrame [pc: 0xa843020ee75]
> 4: EntryFrame [pc: 0xa84302092c1]
> 
> ==== Detail...

I restarted it and runs for a bit then crashes within a couple minutes. This was one of the following crashes:

> 
> <--- Last few GCs --->
> 
> [1:0x55cdb8d260e0] 105883 ms: Mark-sweep 1390.1 (1427.3) -> 1389.7 (1431.3) MB, 598.9 / 0.0 ms (average mu = 0.144, current mu = 0.086) allocation failure scavenge might not succeed
> [1:0x55cdb8d260e0] 106477 ms: Mark-sweep 1393.0 (1431.3) -> 1392.8 (1431.8) MB, 575.1 / 0.0 ms (average mu = 0.091, current mu = 0.031) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> 0: ExitFrame [pc: 0x1dfce44c2ee1]
> Security context: 0x1caa8ef1e6e9 <JSObject>
> 1: stringSlice(aka stringSlice) [0x3aa100c13429] [buffer.js:~589] [pc=0x1dfce46b1e2f](this=0x01b52b8826f1 <undefined>,buf=0x12ff689fcac1 <Uint8Array map = 0x33f584355501>,encoding=0x1caa8ef3dd31 <String[4]: utf8>,start=5213310,end=5213325)
> 2: deserializeObject(aka deserializeObject) [0x6769c628521] [/app/Tdarr/bundle/programs/server/npm/node_modules/...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

The application was running just fine when my only library was a test directory of about 20 movies. The issue started when I created new libraries pointing towards my full content. Is there a way to increase the JavaScript heap size?

**Comment by HaveAGitGat** [comment]
Hi, thanks for opening an issue.

How much memory do you have on your system? Tdarr server is configured to use up to 4GB RAM which should be able to handle a library of 300,000 files or so.

**Comment by nyid** [comment]
My server has 64 GB of memory total. Without the Tdarr container running I hover around 8GB used, so roughly 56GB available.

**Comment by HaveAGitGat** [comment]
Ok thanks. Are you on the latest version? It should show 1.003 in the top right. And how many files did you scan?

**Comment by nyid** [comment]
No problem! I am fairly certain I'm on 1.003, the application doesn't stay up long enough for me to pull the web interface up to check. It's the latest container from docker hub. I can blow the db away to verify if you need me to, I left it as-as in case you wanted me to troubleshoot anything. Before I had issues, I set up two libraries which combined would have been about 36,000 files.

**Comment by HaveAGitGat** [comment]
Sorry thought you might have had time to see the version number.

I hate to say it but what I’d suggest doing is deleting the container and MongoDB data and then make sure to install Tdarr from the CA store using the template instead of directly from DockerHub.

Should hopefully resolve your issue. Haven’t had any RAM issue reports like yours since I changed things a few weeks ago so hopefully doing a fresh install using the CA template will fix the issue.

**Comment by nyid** [comment]
No worries, I can do that. Only reason I haven't reinstalled was if you had me perform any troubleshooting. By the way it was installed with the CA template. Thanks! I will report back if the same issues occur.

**Comment by HaveAGitGat** [comment]
Ok thank you, much appreciated!

**Comment by nyid** [comment]
I deleted and recreated an empty db, reinstalled Tdarr from the CA template. Added a library with about 5000 files, health scanned all and went fine. Then I added another library with about 30,000 files, seemed to be working fine, health scanned about 20,000 the last time I looked. Just checked and it crashed again.

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 
> <--- Last few GCs --->
> 
> [1:0x55caf63670e0] 7311072 ms: Scavenge 1194.2 (1245.7) -> 1190.4 (1254.7) MB, 8.5 / 0.0 ms (average mu = 0.320, current mu = 0.382) allocation failure
> [1:0x55caf63670e0] 7311132 ms: Scavenge 1202.2 (1254.7) -> 1193.8 (1260.2) MB, 5.4 / 0.0 ms (average mu = 0.320, current mu = 0.382) allocation failure
> [1:0x55caf63670e0] 7311164 ms: Scavenge 1206.0 (1260.2) -> 1193.6 (1264.7) MB, 5.1 / 0.0 ms (average mu = 0.320, current mu = 0.382) allocation failure
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> 0: ExitFrame [pc: 0x1ff42b5be1d]
> Security context: 0x18cbc911e6e9 <JSObject>
> 1: /* anonymous */ [0x2543956769d1] [packages/meteor.js:~1277] [pc=0x1ff43c94f92](this=0x254395677031 <ChildProcess map = 0x1195e7a21c01>)
> 2: arguments adaptor frame: 2->0
> 3: emit(aka emit) [0x254395677229] [internal/child_process.js:~831] [pc=0x1ff43cb05d2](this=0x3655209026f1 <undefined>,event=0x365520906ab9 <String[7]: message>,message=0x2f7197...

**Comment by HaveAGitGat** [comment]
Thanks for the update! I’ve been poking around and there seems to be an issue in some circumstances when hitting the 30,000 file mark or so. I’m just testing a fix on my 200,000 file test library. It’s currently on 45,000 files so seems to be working but will let you know if/if not/when it gets to 200,000.

**Comment by HaveAGitGat** [comment]
Just to an update to let you know I ran it overnight and it got to about 110,000 files and then crashed because I ran out of disk space (I only had a few GB free on my test machine SSD). Doing another test now, should be done in a few hours or so, will update then.

**Comment by HaveAGitGat** [comment]
I’ve increased the RAM limit to 16GB which should be good for up to 180,000 files or so.

Obviously that’s a ridiculous amount of RAM to be using so it’s more of a temporary solution for those who have a lot of files as I want to improve the RAM strategy in future. 

I’ll push the update later today 👍

**Comment by HaveAGitGat** [comment]
The update is now available. Let me know if you still have any issues.

**Comment by nyid** [comment]
Initial tests look good! Started back up around 24k files health scanned and continuing where it left off.  I will play around with it for a day or so and let you know.

**Comment by nyid** [comment]
Been running non-stop since my last comment and no issues. Thanks for all your help!! I'll close this issue but feel free to ping me if you need any assistance testing something out.
