### ISSUE TITLE
create /config folder for docker

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#230]
**Is your feature request related to a problem? Please describe.**
Great if a config folder can be used (that can be mapped) so that any local plugins and backups can be stored/retrieved from there; This will allow the easy backup and re-creation of the total docker without losing config.

**Describe the solution you'd like**
enable the storage of all config (incl. local plugins, libraries and backups) to /config folder, so that user can make a mapping of /config to docker/config/tdar. 

**Describe alternatives you've considered**
Extracting backup information from docker container, but is very manual

**Additional context**

**Comment by Roxedus** [comment]
The mount `/home/user/Documents/Tdarr` serves as that.

**Comment by HaveAGitGat** [comment]
Yes you need to map the above folder.  For example, on Windows:

 `-v C:\Users\user\Documents\Tdarr:/home/Tdarr/Documents/Tdarr ^`

Please re-open if you still need help.
