### ISSUE TITLE
[Feature request] plugin: subtitle text to capture color code to correct for LG Oled HDR display

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#231]
**Is your feature request related to a problem? Please describe.**
The LG Oled televisions in HDR movies will display the srt subtitles in bright white. 
This is too much white. by adding a font color tag to every line, this can be corrected.
For example making the srt display dark grey,
<font color="#808080">subtitle text here</font>

**Describe the solution you'd like**
Would it be possible to have a plug that takes all srt files in the folder of the movie
and adds a font color desired color tag to every line and writes the srt back under different title to the disk.

**Describe alternatives you've considered**
Manually using subtitle edit.

**Additional context**

**Comment by HaveAGitGat** [comment]
If you're still wanting this then please add it on the Tdarr Plugins repo:
https://github.com/HaveAGitGat/Tdarr_Plugins
