### ISSUE TITLE
tdarr lists and stats empty

### ISSUE THREAD

**Issue by PVTD** [HaveAGitGat/Tdarr#233]
**Describe the bug**
All lists (Transcode queue, success, error, health check etc.) and stats suddenly appear empty.

**To Reproduce**
Force close tdarr (eg. the ingenious AuToMaTiC windows updates...) or fiddle around with folders (add, delete, update) at random times.

**Expected behavior**
Well, it shouldn't clear ;)

**Screenshots**
Lists: https://i.imgur.com/AVSXrcN.png
Stats: https://i.imgur.com/riNt4R2.png

**Desktop (please complete the following information):**
 System 1:
- Windows 10 LTSC 1809 x64
- Chrome (latest)
- Ryzen 7 1700, 32gb ram, GTX1080
System 2:
- Windows 10 Pro 1909 x64
- Edge (latest)
- Dual Xeon E5-2630L, 64gb ram, GTX1060 & GTX1080

**Additional context**
The only way to fix it is by resetting the DB, but that polls the drives more due to repeated health checks and verification if the video is already in correct format or not.
**NOTE:** Both instances on both PCs pull the video files from a secondary server using SMB.
This is achieved by simply using the remote IP (eg. \\192.168.0.69\Pool\Data). The server runs Windows 10 x64 using DrivePool for drive pooling.

**Comment by HaveAGitGat** [comment]
Hmmm this seems to be due to an error in the client table generation. It has been added to the July to-do found in the discord.
