### ISSUE TITLE
[FEATURE REQUEST] Add VMAF to tdarr

### ISSUE THREAD

**Issue by likeadoc** [HaveAGitGat/Tdarr#234]
VMAF [¹](https://github.com/Netflix/vmaf) is a perceptual video quality assessment  machine learning algorithm developed by Netflix. 

Integrating VMAF into tdarr would enable state of the art quality control of encodes &  would make the creation of quality controlled encodes through tdarrs individual plugin system possible (i.e. transcode with varying parameters until a certain perceptual quality is obtained.)

VMAF is available as a python library and can be used as a filter in ffmpeg [²](https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md) (configured during compile)

For a reference implementation in docker please see
https://github.com/Schrodinger3000/VMAF-FFmpeg
https://github.com/Netflix/vmaf/blob/master/Dockerfile
https://github.com/five82/ffmpeg-git
https://github.com/leandromoreira/docker-ffmpeg-vmaf

**Comment by HaveAGitGat** [comment]
Hmmm interesting. I've added it to the longer term goals in the Discord to-do.
