### ISSUE TITLE
Transcode issue.

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#235]
**Describe the bug**

Windows 10 system, Beta 1.1092 version of Tdarr

I am trying to use handbrake to transcode to H.265

All of the video files are immediately going to "Error/Cancelled". 

CLI argument: -Z “H.265 MKV 1080p30”

**To Reproduce**
N/A

**Expected behavior**
Should obviously transcode to H.265

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Beta 1.1092

**Additional context**

**Comment by HaveAGitGat** [comment]
On the transcode error tab each file will have an 'i' info button which you can press for error information. Please paste the contents here.

**Comment by HaveAGitGat** [comment]
Please re-open with the error log on the 'i' button if you're still having this issue.
![image](https://user-images.githubusercontent.com/43864057/89937806-dd184280-dc15-11ea-9a83-38efe0e5f9ad.png)
