### ISSUE TITLE
Sort or Filter by Codec

### ISSUE THREAD

**Issue by ionred** [HaveAGitGat/Tdarr#236]
**Is your feature request related to a problem? Please describe.**
Sometimes when I've made a change to a plugin I will requeue my entire library.

**Describe the solution you'd like**
It would be convenient to have an option to sort by codec. (A-Z, Z-A). Or, perhaps, to filter by codec for the queue (temporarily)

**Comment by HaveAGitGat** [comment]
Why would you need this? If a file is in the correct codec it will be skipped. If it's in the wrong codec it will be transcoded. What benefit would adding 'sort by codec' give?

**Comment by ionred** [comment]
Trying to clear the queue of things quickly that don’t need to be there.

**Comment by HaveAGitGat** [comment]
Ok I suppose some people may find that useful although it doesn't make any real difference to how quickly the queue is processed. Adding it to the July to-do on Discord.
