### ISSUE TITLE
File Scanner crashing, when doing a fresh or find new library scan

### ISSUE THREAD

**Issue by Saorn** [HaveAGitGat/Tdarr#237]
**Describe the bug**
The file scanner is exiting when I try to do a fresh scan or find new scan on a library.  This prevents the full contents of the subfolders to be added to the transcode/health check queues for processing.  This is also preventing Tdarr from picking up new media as it's added.

**To Reproduce**
Create a new library, point it to a folder containing media and hit fresh scan.

**Expected behavior**
file scanner to scan contents of folder and subfolders and add them to the transcode and health check queues

**Screenshots**
snippet from the log when the error occurs
(node:68) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
at new Promise (<anonymous>)
at __awaiter (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:4:12)
at BatchProcess._end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:268:16)
at BatchProcess.end (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:260:37)
at BatchProcess.onError (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:394:14)
at Socket.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/batch-cluster/dist/BatchProcess.js:75:57)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at onwriteError (_stream_writable.js:411:12)
at onwrite (_stream_writable.js:439:5)
(node:68) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

(node:68) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

1: node::Abort() [/usr/bin/node]
2: 0x8cd49c [/usr/bin/node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
4: 0x8ce978 [/usr/bin/node]
5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/usr/bin/node]
6: 0xec9a81 [/usr/bin/node]
7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/usr/bin/node]
9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/usr/bin/node]
11: 0x1024574 [/usr/bin/node]
12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]
13: 0x22d619d40d85
[32m[2020-06-19T20:13:54.571] [INFO] tdarr - [39mFile scanner exited

**Desktop (please complete the following information):**
 - OS: unRAID 6.8.3
 - Browser: Chrome
 - Version: 83

**Additional context**
I've been using Tdarr for months now.  I've been playing around with adding and removing libraries quite a few times and never had this problem with the file scanner before.

In my attempts to troubleshoot the issue,  I have completely removed the docker and the appdata directories and did a fresh install and only created one new library and pointed it to a media folder and it exited with the error above.  I'm guessing I have acquired some new media that the file scanner just doesn't want to scan and it keeps barfing when it tries to analyze the file.

**Comment by HaveAGitGat** [comment]
Issue with ExifTool here:
https://github.com/HaveAGitGat/Tdarr/issues/130

No response to my issue though.
