### ISSUE TITLE
Filter by resolution

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#238]
**Is your feature request related to a problem? Please describe.**
I want to reduce the size of my 1080p and lower content, but I don't want to touch my 2160p content.

**Describe the solution you'd like**
The ability to filter out content above or below a certain resolution

**Comment by HaveAGitGat** [comment]
If you use the plugin creator GUI on the plugins tab then there’s an option to add a resolution filter.
