### ISSUE TITLE
Tdarr slave

### ISSUE THREAD

**Issue by PeteB1983** [HaveAGitGat/Tdarr#239]
this is an amazing app - and just what i was looking for (and failing to make in a bash script)
I am sure i am not alone in having a large library, and transcoding can be time consuming, especially if running on a lower powered machine.

It would be amazing to have a slave docker to run on other machines that was fed files by the master.
so for instance you would have a schedule for the overall slave app and numbers of workers but thats all, so it could wake up on schedule and contact the main tdarr instance, which would then send it jobs.  

meaning you could run tdarr on a slower machine and have a main pc join in over night or similar?

**Comment by HaveAGitGat** [comment]
Hi yes that is covered here: https://github.com/HaveAGitGat/Tdarr/issues/102

Will be taken into consideration when I redo the worker modules this month.

**Comment by HaveAGitGat** [comment]
Tdarr v2 uses Tdarr_Nodes which work together:

![image](https://user-images.githubusercontent.com/43864057/105864120-e6de0880-5ff1-11eb-9ab2-723e01a8fea0.png)

Instructions here:
http://tdarr.io/docs/installation

Reopen if needed.
