### ISSUE TITLE
Feature Request - Search Tab NOT results

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#24]
Would it be possible to include NOT results in the search? For example, I'd like to search by mkv and NOT 720p.

``mkv,-720p``

Perhaps putting a MINUS sign in front of the search?

**Comment by HaveAGitGat** [comment]
Added in 1.005

The NOT argument is a '!' as that is the standard syntax in most applications/languages.

E.g.

`h264,!1080p`

Will return h264 files not in 1080p
