### ISSUE TITLE
[Feature Request] Filter by bitrate

### ISSUE THREAD

**Issue by plumber-craic** [HaveAGitGat/Tdarr#244]
**Is your feature request related to a problem? Please describe.**
I want to target lossless/inefficient h265 files. It seems there are a lot of people encoding at h265 RF0, and I want to target these files for transcoding. However, since my target codec is h265, I will create a plugin loop if I don't have a way to filter for these lossless files vs the ones I have already transcoded to h265 at RF18. 

**Describe the solution you'd like**
Please add a new built-in filter for bitrate. It should be a range of bitrates between an upper and lower bound, specified by the user. This way I can have a single filter for TV, Movies and short clips if their bitrate is between X and Y. This option should be available in the Plugin Creator Filter dropdown menu. I'm not sure if bits, kilobits or megabits is the best unit, but I guess Mb works if we can provide decimals in the input, or Kb if it must be an int. Also not sure if users need a tooltip on the difference between bits and bytes.

**Describe alternatives you've considered**
FilterBySize is the only option I can think of, but it's neither elegant nor reliable. For movies I'm guessing that h265 files over 15GB are probably inefficient, and for TV shows I guess anything over 5GB is a viable candidate. 

**Additional context**
Since the [file object](https://github.com/HaveAGitGat/Tdarr_Plugins) being passed to the filters has a .bit_rate property, it seems this method would be a clone of the [filterBySize](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/9c8ac987286bff7c0b96eee1bbc6e31b8ce7e90a/methods/library/filters/filterBySize.js) method, but targetting bitrate instead of file size.

**Comment by HaveAGitGat** [comment]
This has been added to the Discord July to-do. The issue I've had in the past with bitrate is that ffprobe and exiftool often fail to get the video/audio stream bitrates. There's not much point in using the overall bitrate for filters because a file may have a terrible video bitrate (and hence meet your requirements) but there may be 15 audio streams which pushes up the overall bitrate. Adding MediaInfo to the scan process should resolve this issue.
