### ISSUE TITLE
Replacing single quotes in preset makes aformat channel_layouts not work

### ISSUE THREAD

**Issue by mjc** [HaveAGitGat/Tdarr#247]
`var presetUnix = preset.replace(/'/g, "'\"'\"'");`  makes it impossible to insert a literal `'` which is necessary for doing channel mapping for Opus.
`-af aformat=channel_layouts='"'"'7.1|5.1|stereo'"'"'` is the resulting output which is completely wrong.

https://github.com/HaveAGitGat/Tdarr/blob/99156c30d50f47cca678026c804ce98e3ab67c0e/private/worker1.js#L304

315-321 does not look like the correct way to build a command line either.  I'll investigate and toss up a PR if I find the right way.  JavaScript isn't my specialty.

EDIT: looks like I could pass an array to the forked process.

**Comment by HaveAGitGat** [comment]
Did you find any issues with passing an array?

**Comment by mjc** [comment]
Passing an array would work but it'll require updating all the plugins so I haven't looked into it very far.

**Comment by mjc** [comment]
In hindsight I guess I could check if it's an array or not. I'll get on this

**Comment by HaveAGitGat** [comment]
This should now be fixed on v2. Please re-open if needed. Thanks.
http://tdarr.io/docs/
