### ISSUE TITLE
[FEATURE REQUEST] Check output. 

### ISSUE THREAD

**Issue by rubenqs12** [HaveAGitGat/Tdarr#249]
First I want to thank you for this project, it makes it much easier to do things.
 I would like to know if you could add the following function. 
I have a library and I want everything transcoded to be put in another folder, but when the library is done it starts again with the same files. Would it be possible to add a validation so that does not happen? 

Example of what I say: 
1- Load original file 
2- Check that it has not been transcoded in the exit route (it could be checked in the database). 
3- If it exists, skip. 
4- If it does not exist, follow the normal process.

**Comment by HaveAGitGat** [comment]
My other app HBBatchBeast can do this although it has reduced functionality in other areas (no plugin stacks etc). I'll add this to the Tdarr July to-do found in the Discord.
