### ISSUE TITLE
Feature Request - Search Tab - Is result item in queue or not?

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#25]
Is it possible to indicate on the Search tab results if an item is currently in a queue or not in a queue? Currently I have no indication and I still have the ability to bump an item to the top of a potentially, non-existent queue.

If so, can we see the queue position number on that search result? If it's 3 out of 4,312 items I may not want to bump it, but if it's 4,041 then I may.

**Comment by HaveAGitGat** [comment]
Added in 1.005
