### ISSUE TITLE
The message argument must be specified

### ISSUE THREAD

**Issue by tzw9373** [HaveAGitGat/Tdarr#250]
Windows 10 native install, occurs while running health check on general worker. 

[2020-07-08T17:14:48.974] [INFO] tdarr - Worker 7wl2Wv23c:Worker online. Requesting item
Exception in callback of async function: TypeError [ERR_MISSING_ARGS]: The "message" argument must be specified
    at ChildProcess.target._send (internal/child_process.js:591:13)
    at ChildProcess.target.send (internal/child_process.js:576:19)
    at getNewTask (server/main.js:1467:41)
    at server/main.js:693:13
    at runWithEnvironment (packages\meteor.js:1286:24)
[2020-07-08T17:14:51.687] [INFO] tdarr - Plugin update finished

**Comment by HaveAGitGat** [comment]
Which health check have you selected in the library options?  Quick or Thorough?

**Comment by tzw9373** [comment]
Quick.

**Comment by HaveAGitGat** [comment]
Is it just with that one file? Have you tried running a thorough health check on it?

**Comment by tzw9373** [comment]
After changing the health check type, it still shows up on the same file and others.

**Comment by HaveAGitGat** [comment]
Seems you have an incorrect setting somewhere. Have you tried running a health check worker instead of a general worker?

What transcode settings are you using? Which version of Tdarr are you using?

**Comment by tzw9373** [comment]
I'm running Beta 1.1.092 with just Tdarr_Plugin_MC93_Migz3CleanAudio Migz-Clean audio streams. Using a health check worker appears to help so far.

**Comment by HaveAGitGat** [comment]
Perhaps this was an isolated error. Either way I've made some changes to the workers so this should be resolved in the next update.
