### ISSUE TITLE
Export list of health check files with errors

### ISSUE THREAD

**Issue by korzynski** [HaveAGitGat/Tdarr#252]
After running a health check and determining which files are not healthy, there is no practical way to do anything with the information.

In addition to #186 I would like to have the ability to export the list of files into a simple text format that could be used as input for a separate script.

Currently, it seems the only way to get a list of the failed files is to copy and paste the list from the web page. This is cumbersome for even a small group of files, as it includes lots of extraneous text that has to be filtered out. But when there are more than a few files, increasing the list size to show all of them is just impractical. In my case, there are thousands of files that would need to be displayed, and increasing the number of displayed items enough to show them all slows down the server considerably.

**Comment by HaveAGitGat** [comment]
Added to Discord July to-do
