### ISSUE TITLE
Use option lists (check box or radio box) for input options

### ISSUE THREAD

**Issue by jeff47** [HaveAGitGat/Tdarr#255]
It might streamline Plugin writing if we could use checkboxes or something similar in the configuration options, rather than relying on free form text boxes.  A fair amount of error checking could be bypassed if plugin writers could constrain user input to one of a few options.

**Comment by HaveAGitGat** [comment]
You can now use dropdown menus in plugin inputs in 2.00.12:

![image](https://user-images.githubusercontent.com/43864057/145770686-1ed54bcf-2583-4a56-b284-8e6ebcf724e7.png)

Take a look at this for an example:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js

```
  {
    name: 'enable_10bit',
    type: 'boolean',
    defaultValue: false,
    inputUI: {
      type: 'dropdown',
      options: [
        'false',
        'true',
      ],
    },
```

So to create a dropdown you need to set the inputUI type to 'dropdown' and then add whichever options you like. Hope that helps.
