### ISSUE TITLE
Error in plugin "input" section causes Tdarr unhandled error

### ISSUE THREAD

**Issue by jeff47** [HaveAGitGat/Tdarr#256]
In my plugin's "input" section, I accidentally had "tooltop" instead of "tooltip".  This resulted in an "oops, something went wrong" screen when I tried to load the Local plugin page.

**Comment by HaveAGitGat** [comment]
This was fixed in 2.00.05:
![image](https://user-images.githubusercontent.com/43864057/110433820-462f3e00-80b1-11eb-9c2e-40af8eca5b7a.png)
