### ISSUE TITLE
Unable to set Environment Variables to Change HW Encoding Driver

### ISSUE THREAD

**Issue by zachg99** [HaveAGitGat/Tdarr#258]
I'm running Tdarr in a Docker container on a Synology NAS.  I was using a DS918+ that didn't support 10bit HEVC encoding.  I upgraded to a DS920+ that does support 10bit HEVC encoding yet found out that the iHD driver has an issue where it doesn't currently allow for hardware video processing on newer intel processors.  [There are a few issues logged but here's one.](https://github.com/intel/media-driver/issues/930)

[This was also noted by Plex and they gave an option to specify the vaapi driver used (VaapiDriver) to allow users to select i965 or iHD. ](https://forums.plex.tv/t/problem-with-new-qnap-synology-nas/606878) This allows me to hw transcode on my synology in plex.

It seems that if i'm able to set these two environment variables it should cause FFMPEG to use the i965 driver:

LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri/ 
LIBVA_DRIVER_NAME=i965

I can set those env options in the docker container, but they only apply to the Tdarr user not the root user which is what Tdarr uses to perform the transcoding.  I think that's because I'm running the container with elevated privileges so I can access the HW transcoding and the env variables are only passed to the Tdarr user, not the root user. 

Can we have a way to specify this in Tdarr?  Either specify the root env variables or provide an option that adds those to the command line?

**EDIT: SOLVED** 
I was able to get this to work and am seeing good results now.  [I documented the solution here on reddit.](https://www.reddit.com/r/Tdarr/comments/hy7slr/use_i965_hw_encodingdecoding_driver_instead_of_ihd/)  It's a fairly simple thing to fix/get working in the Tdarr container.

**Comment by zachg99** [comment]
I found a change that can enable this.  If we can modify the sudoers file to preserve these environment variables it will allow people to set them in the container and they get passed to the root session that's performing the conversion.

Pre changes /etc/sudoers: 
Defaults      env_reset

Post changes /etc/sudoers:
# Defaults      env_reset                                                                                         
Defaults        env_keep += "LIBVA_DRIVER_NAME"                                                                   
Defaults        env_keep += "LIBVA_DRIVERS_PATH"

I did find another bug related to i965, it looks like the version of the file included in the container is from early 2018, this bug was identified and fixed in december 2018.  If you are using the i965 driver and reducing bitrate to be less than or equal to 50% of the original bit rate it kills the bit rate of the output file.  I was expecting a 5mbps video bitrate but i ended up with a 418kbps file that looked horrible.

**Comment by zachg99** [comment]
Just providing an update.  

I updated sources.list to include the focal repo.  Ran apt update and apt install i965-va-driver, that resolved the transcoding bug I was experiencing.

**Comment by HaveAGitGat** [comment]
Will close this as it's to do with v1 and you solved it.
