### ISSUE TITLE
Feature Request - Display full file path/name on worker

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#26]
Would it be possible to display the full path / filename on each individual worker?

Currently it's `<filename>`  and then % 

Then when you open the `i` you get the 
```
CLI:
Preset: 
Process reasons: 
Start time:
Duration: 
Original size (GB): 
```
Could we add in 
```
Path:
CLI:
Preset: 
Process reasons: 
Start time:
Duration: 
Original size (GB): 
```

**Comment by HaveAGitGat** [comment]
Added in 1.005
