### ISSUE TITLE
Transcode Error Due To Space In Folder Name

### ISSUE THREAD

**Issue by SpartanSpar** [HaveAGitGat/Tdarr#261]
When trying to Transcode my library I get this error <details>
  <summary>error</summary>
  
  "D:\Server Share\Tdarr-Windows\Tdarr-Windows\bundle\programs\server\npm\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe -i "D:/Plex/Movies/300 Rise of an Empire (2014)/300 Rise of an Empire 2014 Bluray-1080p.mkv" -map 0 -c:v libx265 -b:v 10021k -minrate 7014k -maxrate 13027k -bufsize 20042k -c:a copy -c:s copy -max_muxing_queue_size 4096 "A:\tdarr\300 Rise of an Empire 2014 Bluray-1080p-TdarrCacheFile-ekyxDbfGd.mkv"

Last 200 lines of CLI log:

shellThread

'D:\Server' is not recognized as an internal or external command,

operable program or batch file."
  
</details> 

I changed the folder name and it's all fine but it would be nice to see this get fixed.

**Comment by HaveAGitGat** [comment]
I've fixed this for the next release, thanks

**Comment by Sherby1988** [comment]
I also have this issue 
the command it executes: 
/opt/Tdarr_Node/assets/app/ffmpeg/ffmpeg42/ffmpeg -i /media/HDD/TVSeries/Westworld/Season 2/Westworld.S02E02.1080p.BluRay.x264-SHORTBREHD.mkv -c copy -map 0:v -map 0:1 -c:1 eac3 -b:a 640k -map 0:s? -map 0:d? -max_muxing_queue_size 9999 /media/HDD/Tdarr/Westworld.S02E02.1080p.BluRay.x264-SHORTBREHD-TdarrCacheFile-ZT7t9iIp1.mkv
As you can see the files don't have quotes and I receive an error 
/opt/Tdarr_Node/assets/app/ffmpeg/ffmpeg42/ffmpeg: 12: /opt/Tdarr_Node/assets/app/ffmpeg/ffmpeg42/ffmpeg: Syntax error: word unexpected
