### ISSUE TITLE
Workers run as the 'root' user and change the ownership of the media files to 'root'

### ISSUE THREAD

**Issue by Draxter** [HaveAGitGat/Tdarr#262]
**Describe the bug**
Worker processes run as the root user and change the ownership of transcoded video files to root which can cause access issues to other programs like Sonarr/Radarr/Emby/Plex etc.

**To Reproduce**
- I run Tdarr (using various MIGZ plugins) on a directory owned by user 1000
- Workers transcode the video files
- While transcoding is in progress, I exec into the container and run 'ps aux', which shows the worker processes running ffmpeg as root
- After transcoding the newly created video file replacements are owned by root

My docker-compose file:

>   tdarr:
>     image: haveagitgat/tdarr_aio:1.1092
>     container_name: tdarr
>     environment:
>       - TZ=Europe/London
>       - PUID=1000
>       - PGID=993
>       - GIDLIST=39
>       - NVIDIA_VISIBLE_DEVICES=all
>       - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
>     volumes:
>      - /storage/Private/test:/media
>      - /home/username/tdarr:/home/Tdarr/Documents/Tdarr
>      - /storage/transcode-temp:/transcode-cache
>     ports:
>      - 8265
>     devices:
>       - /dev/dri/renderD128:/dev/dri/renderD128
>       - /dev/dri/card0:/dev/dri/card0

**Expected behavior**
As a user, I expect the video files in my library to keep their original ownership and permissions after being transcoded. Especially considering the container allows users to pass in their PUID and PGID as environment variables, which could be used to chown the video files after transcoding by Tdarr.

**Desktop (please complete the following information):**
 - OS: Linux (Docker)
 - Version 1.1092

**Comment by Draxter** [comment]
#170 raises a similar issue, however I thought I would provide more information.

**Comment by Roxedus** [comment]
The workers runs as the user tdarr runs as, I am in the last stage of testing on my work before a PR, which solves this.

**Comment by Draxter** [comment]
> The workers runs as the user tdarr runs as, I am in the last stage of testing on my work before a PR, which solves this.

Are you sure? version 1.1092 (docker)?

I tested by running 'ps aux' inside the container and it produces output like:

> root       2928  0.6  0.3 569288 32404 ?        Sl   21:19   0:37 /usr/bin/node --max-old-space-size=16384 assets/app/worker1.js 8fGMN0S7o transcode
> root       2943  0.5  0.3 569376 32156 ?        Sl   21:19   0:30 /usr/bin/node --max-old-space-size=16384 assets/app/worker1.js 4TBArNgDF transcode
> root       7553  0.0  0.4 567284 33056 ?        Sl   22:49   0:00 /usr/bin/node --max-old-space-size=16384 assets/app/worker2.js
> root       7561  0.0  0.0   4624   868 ?        S    22:49   0:00 ffmpeg........
> root       7562 25.8  5.5 13963296 451500 ?     Sl   22:49   1:25 ffmpeg.....
> root       7600  0.2  0.4 567364 32732 ?        Sl   22:53   0:00 /usr/bin/node --max-old-space-size=16384 assets/app/worker2.js

Perhaps my test method is not right, but the transcoded files definitely end up being owned by root after transcoding

**Comment by Roxedus** [comment]
Yes, because tdarr runs as root

**Comment by HaveAGitGat** [comment]
The new container is currently being tested under `haveagitgat/tdarr:pro_nightly` and seems to be working well. 

I've updated http://tdarr.io/tools with new variables
Moving this under: https://github.com/HaveAGitGat/Tdarr/issues/170
