### ISSUE TITLE
Add UTF-8 support

### ISSUE THREAD

**Issue by jeff47** [HaveAGitGat/Tdarr#263]
Files fail due to UTF coding being used on the host system but not in the container.  Perhaps en_US.UTF-8 is a geocentric way to do it, and there is a more universal LANG setting that would avoid this problem.

My fix, via dockerfile:
```
RUN  apt-get update --allow-releaseinfo-change && \
  apt-get install -y locales mediainfo mkvtoolnix && \
  sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8 && \
  export LANG=en_US.UTF-8 && \ 
  export LC_ALL=en_US.UTF-8
```

**Comment by HaveAGitGat** [comment]
Added in `haveagitgat/tdarr:pro_nightly`
