### ISSUE TITLE
NVEnc Support

### ISSUE THREAD

**Issue by ghost** [HaveAGitGat/Tdarr#264]
**Is your feature request related to a problem? Please describe.**
Currently, none of the plugins allow transfer of HDR10 related metadata combined with GPU processing.

**Describe the solution you'd like**
Incorporate NVEnc support (https://github.com/rigaya/NVEnc) into Tdarr to allow for HDR proceeding outside of ffmpeg/handbrake.

**Describe alternatives you've considered**
Currently using nvenc manually for any HDR related processing

**Additional context**
Current CLI command I am using with NVEnc:

./nvencc -c hevc -i <filepath> --avhw  --output-depth 10 --multipass 2pass-full --max-bitrate 16000 --vbr 0 --strict-gop --nonrefp --aq --aq-strength 0 --level auto --tier main --colorrange auto --videoformat auto --colormatrix auto --colorprim auto --transfer auto --chromaloc auto --max-cll copy --master-display copy --audio-copy -b 3 -o <filepath>

**Comment by HaveAGitGat** [comment]
Tdarr only uses FFmpeg and HandBrake so this most likely won't be added in until those programs incorporate it.
