### ISSUE TITLE
Tdarr fails to Start on Docker

### ISSUE THREAD

**Issue by MartyMcKnife** [HaveAGitGat/Tdarr#265]
**Describe the bug**
Upon running the docker container through docker-compose, tdarr exits with code 1, and crashes at `standard_init_linux.go:211: exec user process caused "exec format error"
`

**To Reproduce**
1. Create a docker-compose.yml with the following text: 
`  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    ports:
      -  8265:8265
    environment:
      - TZ=Australia/Perth
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/docker/tdarr/:/home/Tdarr/Documents/Tdarr
      - ~/docker/tdarr/db/:/var/lib/mongodb
      - /mnt/storage/movies:/home/Tdarr/Media/Movies
`
2. Run the file with `docker-compose up -d`
3. Tdarr does not run

**Expected behavior**
Tdarr should launch correctly, and be accessible from the internet

**Desktop (please complete the following information):**
 - OS: DietPi
 - Browser: N/A
 - Version: v1.019 (latest)

**Additional context**
This is being run on an Odroid-N2+

**Comment by Roxedus** [comment]
The container is only built for x64.

**Comment by MartyMcKnife** [comment]
Huh. Dunno why I thought it would work x86. Thanks!
