### ISSUE TITLE
Videos with multiple audio streams tagged as default error out with default build-in-filter

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#268]
**Describe the bug**
There are video files in mkv format which have multiple audiotracks tagged as 'default:yes' This means that the player is forced to play the audio stream.
These files will always error out in the build in filer: ''[Contains built-in filter] This plugin will move the video stream to the front so Tdarr will recognize the codec correctly.''
In addition, for these files: Plex also doesn't play them Jellyfin plays all audio streams at the same time. so having a method by which these mkv files only have 1 audio-track as 'default:yes' or where all 'default:yes'are removed from all tracks would solve the problem

More information:
https://forums.plex.tv/t/video-files-containing-multiple-audio-tracks-all-played-at-once-on-apple-tv-app/127377/10

**To Reproduce**
File example: Mes.Premieres.Fois.S01E11.MULTI.1080p.WEB.x264-N3TFL1X; has 12 audio streams, with most 'default setting to yes'. Have more files if needed.

**Expected behavior**
2 fold:
1. That the standard build in filter:[This plugin will move the video stream to the front so Tdarr will recognize the codec correctly.]  doesn't error out.
2. Ideally incorporate in this standard plug-in that one audio channel '(the first encountered) is set to 'default-yes and no others to avoid problems with players as plex & jellyfin.

**Screenshots**

**Desktop (please complete the following information):**
OS: TDarr Synology docker, plex, jellyfin Synology docker. 

**Additional context**
[error_message.txt](https://github.com/HaveAGitGat/Tdarr/files/5057876/error_message.txt)
Added a dump from the error generated by the build-in plugin.

**Comment by HaveAGitGat** [comment]
`Subtitle codec 94213 is not supported.`

So you can't put these subtitles into mkv, would need to remove them or use mp4 container which supports them.

**Comment by HaveAGitGat** [comment]
The plugins have been updated a lot since this so please open an issue here if you still have problems, thanks:
https://github.com/HaveAGitGat/Tdarr_Plugins
