### ISSUE TITLE
Increase API Verbosity

### ISSUE THREAD

**Issue by ionred** [HaveAGitGat/Tdarr#269]
**Is your feature request related to a problem? Please describe.**
Various monitoring solutions would be able to make use of a more verbose API endpoint.

**Describe the solution you'd like**
Add additional data into the API response, or add additional endpoints to acquire additional information.
Example data points:
* Workers Active
  * Worker X status
  * Worker X current filename
  * Files processed in last Y hours
* Library Status
  * Total Items
  * Items Cancelled
  * Items Errored
  * Items queued
  * Items completed

* Perhaps an overall status as well, of all libraries combined?

**Comment by livearchivist** [comment]
Would love to have all of the items above! Also if we had the ability to call the API and tell it what to do, I could imagine building some sweet automations in Home Assistant like: `If Plex starts, pause all transcodes`. Or - `if all people have left the house, start transcoding`. I do what I can to not thrash the disks for transcoding when people are home and normally using the Plex server, but I feel like I could get more hours of transcoding in, if I could automate it. 

I could see myself building a Tdarr plugin for Home Assistant if some of these items came true :)

**Comment by HaveAGitGat** [comment]
Yes I plan on adding more endpoints. I've spent September on some significant performance updates (in 1.3001) and now need to fix/redo the workers due to issues with the output folder option but once I've done that I can work on things like this.

Will be added to https://tdarr.io/docs/apiv1

**Comment by HaveAGitGat** [comment]
Some more endpoints here for v2:

http://tdarr.io/docs/apiv2

Still need to add some more stats.

**Comment by HaveAGitGat** [comment]
Stats info can be found here:
https://github.com/HaveAGitGat/Tdarr/issues/166

Node + worker info can be gathered using:

```
const axios = require('axios');
(async () => {
    const result = await axios.get(`http://localhost:8266/api/v2/get-nodes`, {
        headers: {
            'content-Type': 'application/json',
        },
        data: {},
        timeout: 1000,
    });
    console.log(result.data);
})();
```
