### ISSUE TITLE
Different Databases

### ISSUE THREAD

**Issue by NotExpectYet** [HaveAGitGat/Tdarr#27]
Hi, very awesome project. Planning on spinning this up and testing it on my 28TB library. 

Would it be at all possible/easy to use another database than mongoDB. If it's too much work don't worry about it I'll just spin up a mongo container. 

MySQL or PostgreSQL would be awesome though.

**Comment by HaveAGitGat** [comment]
Hi, the whole framework is based on using MongoDB so it would be a lot of work.

For Docker, there is an Ubuntu Tdarr All-in-One container coming out soon which will have MongoDB inside of it so you don't have to spin up a separate container (I was using that previously but we changed to a minimal Alpine container 3 weeks ago with MongoDB running separately).  Would that be more suitable for you?

**Comment by HaveAGitGat** [comment]
Sorry for the late reply. I don't have a notification system so it's probably best to click 'watch' this repo so you get email notifications when a new update is available. 

The new container tdarr_aio (all in one) is now available. Please see the readme for instructions.

**Comment by NotExpectYet** [comment]
> Sorry for the late reply. I don't have a notification system so it's probably best to click 'watch' this repo so you get email notifications when a new update is available.
> 
> The new container tdarr_aio (all in one) is now available. Please see the readme for instructions.

No trouble, sorry for mine! I'll check it out thanks :)
