### ISSUE TITLE
Add additional search option - Size Ranges

### ISSUE THREAD

**Issue by ionred** [HaveAGitGat/Tdarr#270]
**Is your feature request related to a problem? Please describe.**
Size range option for search

**Describe the solution you'd like**
The ability through either drop down or part of the current text field to provide a size range to search for (or an open ended size)
Examples:
* 1.2GB-1.6GB
* <800MB
* \>5GB

**Comment by HaveAGitGat** [comment]
Added for 2.00.10
![image](https://user-images.githubusercontent.com/43864057/114663386-80b47800-9cfa-11eb-91fc-f8c2175d6123.png)
