### ISSUE TITLE
Volume normalization

### ISSUE THREAD

**Issue by Jacob-Lasky** [HaveAGitGat/Tdarr#272]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to turn up one episode /movie and then another way down because of the volumes are extremely different.

**Describe the solution you'd like**
I think it would be nice to have a way to normalize the loudness of my videos in a way that has the max volumes equal across all of my files.

**Describe alternatives you've considered**
Either having all video volumes go up, all go down, or all go somewhere in the middle.

**Comment by YouKnowBlom** [comment]
I believe this can be closed @HaveAGitGat
