### ISSUE TITLE
Hourly or daily or both transcode rate

### ISSUE THREAD

**Issue by mattwilbur** [HaveAGitGat/Tdarr#274]
TDARR Rocks. thank you for this. As I fired it up on a 1TB SSD full of files, it was really hard to figure out how many workers was the "sweet" spot. If the stats also displayed # of transcodes per day or hour it would really help me to tune my # of workers. I have a 48 core dual xeon monster to run it on but also had to figure out when i was saturating disk writes. Even though this wouldn't be a perfect measure because the files differ so much, it'd be a super tool to help us find the sweet spot.  Again thank you for this awesome tool!!

**Comment by HaveAGitGat** [comment]
Hi, this has been implemented for 2.00.09 which is in pre-release:
![image](https://user-images.githubusercontent.com/43864057/113980122-68e67b00-9846-11eb-804e-b6833a75dfa2.png)

Viewing 30 days+ will switch the bin size to daily from hourly.

https://tdarr.io/docs/pre-releases
