### ISSUE TITLE
Enconding starts looping when output folder in ON

### ISSUE THREAD

**Issue by crypto-vault** [HaveAGitGat/Tdarr#279]
I’m on v1.1093 and having a problem with Tdarr killing my SSDs because it’s creating partial file non stop when file is not video. I'm using different output folder setup btw.
Weird thing is file is already in output folder, it keeps on trying to process it, and creates a partial file in output folder, deletes it, processes again, over and over.
There are no files in source folder, no files in cache, looks like it loops processing file already in output folder.
When it gets a correct movie file it processes with no problems but once it reaches the problematic file it starts looping again.
This happens on all mkv/mp4 files that it detect as non video files.
If I disable output folder option and file is detected as non video and is added to DB in Error/Cancelled so no longer requeues it
but when I enable output folder again, instead of being added to DB as Error/Cancelled it starts looping

**To Reproduce**
Just put a bad movie mkv file in source folder

** Plugins **
Only using a custom plugin, no other processing
file.fileMedium !== "video" gets hit
Script exits with:
response.processFile = false
response.reQueueAfter = false

** Versions **
 - OS: UNRAID 6.8.3 (Nvidia)
 - Version 1.1093

> Source: Folder watch ON, Process Library ON, Scan on start ON, Closed caption scan (much slower -linux/tdarr_aio/win): OFF
> Folder watch: Use file system events (try if folder watch polling causes high CPU/disk IO): OFF
> Output Folder: ON, Copy to output if conditions already met:ON, Delete source file:ON
> Source is /home/Tdarr/Media/downloads/completed/Movies
> Transcode cache is /home/Tdarr/Media/downloads/cache
> Output folder is: /home/Tdarr/Media/downloads/post/movies
> Health check type: Quick - (Uses HandBrake to check file headers) ON

> [2020-09-06T11:51:17.764] [INFO] tdarr - Scanner IEh0ORtOb:Online
> [2020-09-06T11:51:17.772] [INFO] tdarr - Scanner IEh0ORtOb:vars received:/usr/bin/node,/home/Tdarr/Tdarr/bundle/programs/server/assets/app/fileScanner/fileScanner.js,IEh0ORtOb,jzt96Rn4tp3wXSKYq,,0,mkv,mp4,mov,m4v,mpg,mpeg,avi,>
> [2020-09-06T11:51:17.773] [WARN] tdarr - Scanner IEh0ORtOb:File  does not meet container or ignored folder requirements.
> [2020-09-06T11:51:17.773] [INFO] tdarr - Scanner IEh0ORtOb:Launching FFprobe on these files: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:17.773] [INFO] tdarr - Scanner IEh0ORtOb:ffprobeLaunch received these files:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:17.792] [INFO] tdarr - Scanner IEh0ORtOb:Launching FFprobe on this file: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:17.793] [INFO] tdarr - Scanner IEh0ORtOb:Running ffmpeg on file
> [2020-09-06T11:51:17.851] [ERROR] tdarr - Scanner IEh0ORtOb:FFprobe was unable to extract data from this file:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:17.851] [INFO] tdarr - Scanner IEh0ORtOb:Sending add file to DB:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:17.852] [INFO] tdarr - Add file to DB request received for: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv. Queueing
> [2020-09-06T11:51:17.854] [INFO] tdarr - File scanner exited
> [2020-09-06T11:51:20.719] [INFO] tdarr - This exact file does not exist in DB. Removing old, adding new
> [2020-09-06T11:51:20.722] [INFO] tdarr - Adding file to DB: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:21.118] [INFO] tdarr - Folder watcher jzt96Rn4tp3wXSKYq:file removed, removing:/home/Tdarr/Media/downloads/completed/Movies/movie/movie.mkv
> [2020-09-06T11:51:21.479] [INFO] tdarr - Worker kIyBfX7o- launched
> [2020-09-06T11:51:21.549] [INFO] tdarr - Worker kIyBfX7o-:Worker online. Requesting item
> [2020-09-06T11:51:21.578] [INFO] tdarr - Worker kIyBfX7o-:File received:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:21.578] [INFO] tdarr - Worker kIyBfX7o-:File includes F2F output folder
> [2020-09-06T11:51:21.578] [INFO] tdarr - Worker kIyBfX7o-:currentDestinationLine:/home/Tdarr/Media/downloads/cache/movie-TdarrCacheFile-e6yI7sPJR.mp4
> [2020-09-06T11:51:21.578] [INFO] tdarr - Worker kIyBfX7o-:finalFilePath:/home/Tdarr/Media/downloads/post/movies/movie/movie.mp4
> [2020-09-06T11:51:21.580] [INFO] tdarr - Worker kIyBfX7o-:Attempting to move new file to output folder/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:30.810] [INFO] tdarr - Worker kIyBfX7o-:Copying file successful:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv to /home/Tdarr/Media/downloads/post/movies/movie/movie-TdarrNew.mkv.partial
> [2020-09-06T11:51:30.810] [INFO] tdarr - Worker kIyBfX7o-:Renaming new file:/home/Tdarr/Media/downloads/post/movies/movie/movie-TdarrNew.mkv.partial to /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.033] [INFO] tdarr - Worker kIyBfX7o-:Renaming new file success:/home/Tdarr/Media/downloads/post/movies/movie/movie-TdarrNew.mkv.partial to /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.034] [INFO] tdarr - Worker kIyBfX7o-:Exiting
> [2020-09-06T11:51:31.053] [INFO] tdarr - Scanner FGaysB4Ys launched
> [2020-09-06T11:51:31.055] [INFO] tdarr - Worker exited
> [2020-09-06T11:51:31.055] [INFO] tdarr - Server:Worker completed:" /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.091] [INFO] tdarr - Scanner FGaysB4Ys:Online
> [2020-09-06T11:51:31.098] [INFO] tdarr - Scanner FGaysB4Ys:vars received:/usr/bin/node,/home/Tdarr/Tdarr/bundle/programs/server/assets/app/fileScanner/fileScanner.js,FGaysB4Ys,jzt96Rn4tp3wXSKYq,,0,mkv,mp4,mov,m4v,mpg,mpeg,avi,>
> [2020-09-06T11:51:31.098] [WARN] tdarr - Scanner FGaysB4Ys:File  does not meet container or ignored folder requirements.
> [2020-09-06T11:51:31.098] [INFO] tdarr - Scanner FGaysB4Ys:Launching FFprobe on these files: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.098] [INFO] tdarr - Scanner FGaysB4Ys:ffprobeLaunch received these files:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.117] [INFO] tdarr - Scanner FGaysB4Ys:Launching FFprobe on this file: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.118] [INFO] tdarr - Scanner FGaysB4Ys:Running ffmpeg on file
> [2020-09-06T11:51:31.180] [ERROR] tdarr - Scanner FGaysB4Ys:FFprobe was unable to extract data from this file:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.180] [INFO] tdarr - Scanner FGaysB4Ys:Sending add file to DB:/home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> [2020-09-06T11:51:31.181] [INFO] tdarr - Add file to DB request received for: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv. Queueing
> [2020-09-06T11:51:31.183] [INFO] tdarr - File scanner exited
> [2020-09-06T11:51:31.729] [INFO] tdarr - This exact file does not exist in DB. Adding
> [2020-09-06T11:51:31.732] [INFO] tdarr - Adding file to DB: /home/Tdarr/Media/downloads/post/movies/movie/movie.mkv
> 

> 

var response = {

    processFile: false,
    preset: '',
    container: '.mp4',
    handBrakeMode: false,
    FFmpegMode: false,
    reQueueAfter: false,
    infoLog: '',

  }

    // MAIN CODE

    if (file.fileMedium !== "video") {

        console.log("File is not video")

        response.infoLog += "☒File is not video \n"
        response.processFile = false
        response.reQueueAfter = false

        return response
    }

**Comment by zombiehoffa** [comment]
Same problem doing audio transcoding with an output folder on beta 1.207 (latest docker image) using my custom plugin patterned off of a recommended form for transcoding just audio from reddit (if I can find the post again I will share it)

**Comment by tenzone** [comment]
Im having the same issue, upgraded to the latest container (non pro). this is really killing my workflow, as it just churns and churns

**Comment by HaveAGitGat** [comment]
I’m currently doing a large re-write of Tdarr. It will still be a few weeks until a test version  but it will fix this issue.

**Comment by YouKnowBlom** [comment]
Is it possible to contribute to the re-write?

**Comment by HaveAGitGat** [comment]
@YouKnowBlom just doing it myself but I'll let you know if I need a hand, thanks :)

**Comment by YouKnowBlom** [comment]
> @YouKnowBlom just doing it myself but I'll let you know if I need a hand, thanks :)

That's fair. Will the rewritten project be closed source?

**Comment by HaveAGitGat** [comment]
This should be fixed in v2, instructions here:
http://tdarr.io/docs/

Please reopen if you still need help.

**Comment by HaveAGitGat** [comment]
@YouKnowBlom I've since spoken to you on Discord as to the reasons for closed source.
