### ISSUE TITLE
Issue with audio transcode plugin.

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#280]
**Describe the bug**
Getting an error message when attempting to transcode audio to MP3.

Command:

C:\tdarr\Tdarr-Windows-01-pre-alpha1\bundle\programs\server\assets\app\HandBrakeCLI.exe -i "D:/Music/10cc/Ten Out of 10 (1981)/10cc - Ten Out of 10 - 05 - Notell Hotel.flac" -o "10cc - Ten Out of 10 - 05 - Notell Hotel-TdarrCacheFile-Jsh_IjFhn.mp3" , -c:a copy -b:a 320k

Last 200 lines of CLI log:

shellThread

[14:28:02] Compile-time hardening features are enabled

Cannot load nvEn

codeAPI64.dll

[14:28:03] hb_init: starting libhb thread

[14:28:03] thread 1 started ("libhb")

chapters:

Invalid syntax (:a)

HandBrake has exited. 

**Expected behavior**
Should look for audio files in specified folder and transcode to MP3 320.

**Plugin Syntax**

    var fs = require('fs');
    var path = require('path');
    if (fs.existsSync(path.join(process.cwd() , '/npm'))) {
    var rootModules = path.join(process.cwd() , '/npm/node_modules/')
    } else{
    var rootModules = ''
    }
   
    const importFresh = require(rootModules+'import-fresh');
    const library = importFresh('../methods/library.js')
      
    module.exports.details = function details() {
          return {
            id: "S_yifXv5u",
            Name: "Martins Audio",
            Type: "Audio",
            Operation: "Transcode",
            Description: "",
            Version: "",
            Link: ""
          }
        }

    module.exports.plugin = function plugin(file) {

          //Must return this object at some point
          var response = {
             processFile : false,
             preset : '',
             container : '.mkv',
             handBrakeMode : false,
             FFmpegMode : true,
             reQueueAfter : true,
             infoLog : '',
        
          }

          response.infoLog += "" + library.filters.filterByMedium(file,"audio").note
        
          if((true &&library.filters.filterByMedium(file,"audio").outcome === true) || file.forceProcessing === true){
              response.preset = ', -c:a copy -b:a 320k'
              response.container = '.mp3'
              response.handBrakeMode = true
              response.FFmpegMode = false
              response.reQueueAfter = true;
              response.processFile = true
              response.infoLog +=  "File is being transcoded using custom arguments \n"
              return response
             }else{
              response.processFile = false;
              response.infoLog += "File is being transcoded using custom arguments \n"
              return response
             }
        }

      

**Desktop (please complete the following information):**
 Windows 10
Firefox Developer Edition

**Comment by martinkeat** [comment]
?

**Comment by HaveAGitGat** [comment]
`response.handBrakeMode = true
`
`, -c:a copy -b:a 320k`

Seems you have entered an ffmpeg command but have specified to use HandBrake so the command has failed.  Make sure to select FFmpeg when creating the plugin.

**Comment by martinkeat** [comment]
Nope. Still going straight to failed.

**Comment by HaveAGitGat** [comment]
Do you have the log?

**Comment by martinkeat** [comment]
Command:

C:\tdarr\Tdarr-Windows-01-pre-alpha1\bundle\programs\server\npm\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe -i "D:/Music/10cc/Ten Out of 10 (1981)/10cc - Ten Out of 10 - 06 - Les Nouveaux Riches.flac" -c:a copy -b:a 320k "F:\Transcode\10cc - Ten Out of 10 - 06 - Les Nouveaux Riches-TdarrCacheFile-pyHQCb2Np.mp3"

Last 200 lines of CLI log:

shellThread

ffmpeg version N-92722-gf22fcd4483 Copyright (c) 2000-2018 the FFmpeg developers

built with gcc 8.2.1 (GCC) 20181201

configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt

libavutil 56. 24.101 / 56. 24.101

libavcodec 58. 42.102 / 58. 42.102

libavformat 58. 24.101 / 58. 24.101

libavdevice 58. 6.101 / 58. 6.101

libavfilter 7. 46.101 / 7. 46.101

libswscale 5. 4.100 / 5. 4.100

libswresample 3. 4.100 / 3. 4.100

libpostproc 55. 4.100 / 55. 4.100

Input #0, flac, from 'D:/Music/10cc/Ten Out of 10 (1981)/10cc - Ten Out of 10 - 06 - Les Nouveaux Riches.flac':

Metadata:

ALBUM : Ten Out Of 10

ARTIST : 10cc

TITLE : Les Nouveaux Riches

TRACKTOTAL : 10

GENRE : Art-Rock

DATE : 1981

track : 06

Duration: 00:05:13.00, start: 0.000000, bitrate: 5125 kb/s

Stream #0:0: Audio: flac, 192000 Hz, stereo, s32 (24 bit)

[mp3 @ 0000016905c55f00] Invalid audio stream. Exactly one MP3 audio stream is required.

Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

Stream mapping:

Stream #0:0 -> #0:0 (copy)

Last message repe

ated 1 times

**Comment by HaveAGitGat** [comment]
The issue here is that you're trying to store **flac** audio in an **mp3** container which won't work. You need the container to be **.flac** or you need to transcode the **flac** into **mp3**.

Please reopen if you still need help.
