### ISSUE TITLE
TypeError: func.apply is not a function during statup

### ISSUE THREAD

**Issue by drikqlis** [HaveAGitGat/Tdarr#281]
**Describe the bug**
During statup i get following message: 
wrz 22 13:36:30: Exception in callback of async function: TypeError: func.apply is not a function
wrz 22 13:36:30:     at runWithEnvironment (packages/meteor.js:1286:24)
Tdarr starts and appears to be working but maybe it is worth checking out.

**To Reproduce**
Start up tdarr from command line.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Version: Beta v1.2068

**Comment by HaveAGitGat** [comment]
Seems to be a random framework error which doesn't affect anything. Removed it for the next update.
