### ISSUE TITLE
Plugins error

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr#282]
Hello, I try unsuccessfully to use the plugin "Nosirus h265, aac, no meta, subs kept" but it doesn't work, should we modify some things to make it work as before ?

Error 
"[matroska @ 0x5606f4bdfe80] Only audio, video, and subtitles are supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
encoded 0 frames
Conversion failed!"

**Comment by HaveAGitGat** [comment]
Do you have the full error log including the cli command?

**Comment by Nosirus** [comment]
Sorry, it was linking to the "m4v" video format that I have a problem with, so I don't link to the plugin.

I take advantage of it, is it possible to add a change of -crf in relation to the video resolution ? e.g. lower or higher than 1080p

**Comment by HaveAGitGat** [comment]
@Nosirus yes all plugins are customisable so copy the plugin to local and then edit it and add whatever crf you like. Have a look at this plugin for an example:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_d5d3_iiDrakeii_FFMPEG_NVENC_Tiered_MKV.js

`if (file.video_resolution === "480p" || file.video_resolution === "576p") {`

**Comment by Nosirus** [comment]
thank you very much, I've been to see one of them! :)

**Comment by HaveAGitGat** [comment]
Please reopen if you still need help.
