### ISSUE TITLE
Wiki "Installation" page url needs nodejs updated URL

### ISSUE THREAD

**Issue by jvaneck** [HaveAGitGat/Tdarr#283]
The page located here: https://github.com/HaveAGitGat/Tdarr/wiki/2---Installation

Under Windows, it states "Download and install NodeJS 12.18.2: https://nodejs.org/download/release/v8.16.1/"

It should instead state "Download and install NodeJS 12.18.2: https://nodejs.org/download/release/v12.18.2/"

(Unless there is a different version of nodeJS that should be getting used)

**Comment by HaveAGitGat** [comment]
Thanks, updated.
