### ISSUE TITLE
How to uninstall on Windows?

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#287]
**Describe the bug**
I'm having an issue where my plugins aren't loading, things are slow, lots of various issues. It was working last week when i initially set it up, so I don't know what happened. Regardless, I wnat to reinstall it from scratch. Clearing the database isn't enough. i want every setting, database, etc removed. Any way of achieving this? 

I saw the tdarr folder in documents, but don't know where else things are saved? When i reinstalled the settings were still there so there must've been somewhere else the info is being stored other than program files or appdata which didnt have tdarr

**Comment by DankMemeGuy** [comment]
I think an issue is that the folders can't have a space. This seems to be causing issues. Or allow folders to be in quotes if they have spaces

**Comment by HaveAGitGat** [comment]
You need to delete the folder where general settings/plugins/backups are stored:

C:\Users\User\Documents\Tdarr

And then you need to delete the MongoDB database folder which varies (can give it a Google). It's typically stored at:

C:\Program Files\MongoDB\Server\4.4\data

**Comment by HaveAGitGat** [comment]
Please try v2 and reopen if you still have issues. Thanks

http://tdarr.io/docs/
