### ISSUE TITLE
Stats and any following page causes error after update to 1.3004

### ISSUE THREAD

**Issue by Flapstaart** [HaveAGitGat/Tdarr#288]
I just updated to the latest version 1.3004 and found that all seems fine until I try to go to the "stats" page. This results in generic "Oops! Something went wrong." page, and remains so even when selecting any other top-bar item (Search / Logs / Dev / etc.) The only item that seems to work is the login-menu (I don't have an account). When clicking the logo in the top-left Tdarr's UI starts acting normally again, until Stats are selected.

**Comment by HaveAGitGat** [comment]
Hi are you able to press F12 in the browser and paste the error?

**Comment by HaveAGitGat** [comment]
This should now be fixed in v2.

Instructions here:
http://tdarr.io/docs/

Please reopen if you still need help.
