### ISSUE TITLE
Unable to get Nvidia GPU to work.

### ISSUE THREAD

**Issue by ghost** [HaveAGitGat/Tdarr#289]
**Describe the bug**
GPU Encoding does not function.

**To Reproduce**
Attempt to use any preset that requires NVENC

**Expected behavior**
Encodes to utilize the GPU and not crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mint
 - Version: 20

**Additional context**
Command:

ffmpeg -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid -i '/movies/The Dark Knight Rises (2012)/The Dark Knight Rises 2012 Remux-2160p.mkv' -map 0:v -map 0:a -map 0:s? -map -:d? -c copy -c✌️0 hevc_nvenc -rc:v vbr_hq -preset medium -profile:v main10 -rc-lookahead 32 -spatial_aq:v 1 -aq-strength:v 8 -max_muxing_queue_size 4096 -b:v 13920657 -maxrate 18096854 -minrate 9744460 -bufsize 23728435 -map_metadata:g -1 -metadata JSRVERSION=1 -metadata JSRPROCESSED=true -metadata JSRPROCESSEDTIME=1602376415085 '/home/Tdarr/cache/The Dark Knight Rises 2012 Remux-2160p-TdarrCacheFile-OUfFrwpTR.mkv'

Last 200 lines of CLI log:

shellThread

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3

libavutil 56. 31.100 / 56. 31.100

libavcodec 58. 54.100 / 58. 54.100

libavformat 58. 29.100 / 58. 29.100

libavdevice 58. 8.100 / 58. 8.100

libavfilter 7. 57.100 / 7. 57.100

libswscale 5. 5.100 / 5. 5.100

libswresample 3. 5.100 / 3. 5.100

libpostproc 55. 5.100 / 55. 5.100

Input #0, matroska,webm, from '/movies/The Dark Knight Rises (2012)/The Dark Knight Rises 2012 Remux-2160p.mkv':

Metadata:

title : The Dark Knight Rises 4K

ENCODER : Lavf58.29.100

Duration: 02:44:32.29, start: 0.000000, bitrate: 28329 kb/s

Stream #0:0: Video: hevc, yuv420p10le(tv, bt2020nc/bt2020/smpte2084, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)

Metadata:

DURATION : 02:44:32.279000000

Stream #0:1(eng): Audio: dts, 48000 Hz, 5.1(side), s32p (24 bit) (default)

Metadata:

title : DTS-HD MA 5.1

BPS : 4037310

BPS-eng : 4037310

DURATION-eng : 02:44:32.288000000

NUMBER_OF_FRAMES: 925527

NUMBER_OF_FRAMES-eng: 925527

NUMBER_OF_BYTES : 4982186640

NUMBER_OF_BYTES-eng: 4982186640

_STATISTICS_WRITING_APP: mkvmerge v19.0.0 ('Brave Captain') 64-bit

_STATISTICS_WRITING_APP-eng: mkvmerge v19.0.0 ('Brave Captain') 64-bit

_STATISTICS_WRITING_DATE_UTC: 2018-01-15 07:53:46

_STATISTICS_WRITING_DATE_UTC-eng: 2018-01-15 07:53:46

_STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

DURATION : 02:44:32.286000000

[AVHWDeviceContext @ 0x555740887600] Cannot load libcuda.so.1

[AVHWDeviceContext @ 0x555740887600] Could not dynamically load CUDA

Device creation failed: -1313558101.

[hevc_cuvid @ 0x55574086b6c0] No device available for decoder: device type cuda needed for codec hevc_cuvid.

Stream mapping:

Stream #0:0 -> #0:0 (hevc (hevc_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1 (copy)

Device setup failed for decoder on input stream #0:0 : Unknown error occurred

**Comment by HaveAGitGat** [comment]
To be clear, are you using Docker on Mint? Does GPU encoding work when using FFmpeg/HandBrake outside of Tdarr?

**Comment by RyanGoslingsBugle** [comment]
Are you running in a Docker container? I had the same problem, realised I hadn't added the following env vars to the container:

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all

**Comment by HaveAGitGat** [comment]
Please re-open if the above solution did not work for you. Thanks.
