### ISSUE TITLE
Update from 1.0.7 to Beta 1.2066 issue with fibers.node missing

### ISSUE THREAD

**Issue by MartyIU13** [HaveAGitGat/Tdarr#292]
**Describe the bug**
I have had Tdarr successfully running for a while. The most recent version was 1.0.7. I added the Tdarr Windows folder to my C drive and all works well. When unzipping the Tdarr-Windows-1.2066.zip folder and removing the one that was working, then use cmd to run it like I typically do I get error:

There is an issue with `node-fibers`
`c:\Tdarr-Windows\bundle\programs\server\node_modules\fibers\bin\win32-x64-57\fibers.node` is missing.

Try running this to fix the issue: C:\Program Files\nodejs\node.exe c:\Tdarr-Windows\bundle\programs\server\node_modules\fibers/build

There is no folder named win32-x64-57 in c:\Tdarr-Windows\bundle\programs\server\node_modules\fibers\bin. Only win32-x64-64 and win32-x64-72. I tried running the command it says to, but am unfamiliar with how to do so correctly.

**To Reproduce**
1. Download Tdarr-Windows-1.2066.zip
2. Unzip to C drive
3. Run cmd with:
cd c:\Tdarr-windows\bundle
set MONGO_URL=mongodb://localhost:27017/Tdarr
set PORT=8265
set ROOT_URL=http://localhost/
node main.js

**Expected behavior**
For Tdarr 1.2066 to start. How can I get the expected fiber node installed so it can work?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome, but issue is not in Chrome. I can't even get it to work in cmd
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Additional context**
Maybe I'm missing something obvious, but each time I've updated Tdarr in the past I just downloaded the new folder, put in C drive and ran the above command and everything worked. Can't get the new version 1.2066 to work as those did.

**Comment by reloxx13** [comment]
Update nodejs to latest v12

**Comment by MartyIU13** [comment]
> Update nodejs to latest v12

Thanks, that worked! Didn't realize it owuld be that simple and that node.js needed updating.

**Comment by wsegatto** [comment]
I'm getting this error and I'm already on NodeJS v12. :(
