### ISSUE TITLE
Files are requeued for health check

### ISSUE THREAD

**Issue by drikqlis** [HaveAGitGat/Tdarr#293]
**Describe the bug**
After some time files from libraries are moved from "Health check: Healthy" to "Health check queue"

**To Reproduce**
Can't reproduce on my own but i happens after few days.

**Expected behavior**
Is it expected behavior? What could be causing it?

**Desktop (please complete the following information):**
 - OS: Ubuntu LTS 18.0.4
 - Browser: Firefox
 - Version: v1.2068

**Additional context**
Libraries are on a nfs share mounted in /etc/fstab. Reboot does not cause this problem. Database is not wiped - I can see number of health checks in stats. Folder watch is turned on. Health check is set on: "Thorough - (Goes through each frame of the file with FFmpeg)".

**Comment by HaveAGitGat** [comment]
Are you transcoding the files? New files will be put in the health check queue after transcoding.

**Comment by drikqlis** [comment]
No, files are not changed in any way after they are added and transcoding is disabled. The same files that were checked and marked as healthy are moved to health check queue after few days. If i check them as healthy manually it happens again after few days.

**Comment by HaveAGitGat** [comment]
Hi, please try v2 and reopen if you still have this error. Thanks:

Instructions here:
http://tdarr.io/docs/
