### ISSUE TITLE
Unable to access libraries tab.

### ISSUE THREAD

**Issue by WhooooFloorpie** [HaveAGitGat/Tdarr#294]
Unable to access the libraries tab. Get a “oops, something went wrong message”. Refreshing page does not resolve issue. Have deleted container and started new container. Have restored backup. No fix.

**Comment by sienar1** [comment]
Dupe of https://github.com/HaveAGitGat/Tdarr/issues/291

**Comment by HaveAGitGat** [comment]
Fixed in v2. Instructions here:

http://tdarr.io/docs/
