### ISSUE TITLE
[FEATURE REQUEST] Display Original File data in i button when processing 

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#295]
**Is your feature request related to a problem? Please describe.**
Currently when you hit the i button on a processing file, it does not display the original file data settings from either handbrake or ffmpeg for why the file is being processed. It simply says "Processing Reasons: file is not X" such as "File is not h264 720p!" for example

**Describe the solution you'd like**
When pressing the i button, above or below the Processing Reasons, it should indicate what the original file is. For example

Processing Reasons: File is not h264 720p!
Original File: aac Other

**Comment by HaveAGitGat** [comment]
Seeing the full original file data is possible in 07 by clicking on the source file in the staging section.
