### ISSUE TITLE
[Feature Request] Add a frames per second stat to transcoder thread status

### ISSUE THREAD

**Issue by sienar1** [HaveAGitGat/Tdarr#296]
**Describe the solution you'd like**
Add a frames per second stat to transcoder thread status

**Additional context**
Not sure about Handbrake, but I know FFMpeg can provide a FPS counter as part of its status. I think if the transcoder thread status on the main Tdarr page could show this FPS counter, it would be a more intuitive way of judging an impact on transcode performance as you add and remove threads or other system processes run outside of Tdarr.

**Comment by HaveAGitGat** [comment]
Can't do this for HandBrake but I've added it for FFmpeg in v2.00.05 as well as a total FPS per Node:

![image](https://user-images.githubusercontent.com/43864057/107917925-08833d80-6f69-11eb-8647-6763c1de80f8.png)

**Comment by sienar1** [comment]
Awesome, thanks very much!
