### ISSUE TITLE
Add login/authentication

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [HaveAGitGat/Tdarr#297]
**Is your feature request related to a problem? Please describe.**
Anyone on local network can use Tdarr. Bad when using a seedbox/shared server

**Describe the solution you'd like**
Add authentication page.

**Describe alternatives you've considered**
Have it bind only to 127.0.0.1 when setting to "ROOT_URL=http://127.0.0.1/", right now it binds to all address even when 127.0.0.1 is specified.

**Comment by HaveAGitGat** [comment]
I've added user and api key auth for next version, you can try it if you like:

`docker.io/haveagitgat/tdarr_acc:dev_2.18.01_2023_12_21T15_42_37z`
`docker.io/haveagitgat/tdarr_node_acc:dev_2.18.01_2023_12_21T15_42_37z`

You'll need to set the following env/config vars on the server to activate it:

`auth=true`
`authSecretKey=somesecretkeythatyoukeepsafe`

On startup you should be prompted to create an account:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/f168ea21-2286-48c9-907e-0c5c5ee2befc)

Once you sign in you'll need to head to the `Tools->API Keys` page and create an API key for your Nodes to use.

You'll then need to set the `apiKey` env/config var for your Nodes so they can connect to your server.

**Comment by astronyu** [comment]
> I've added user and api key auth for next version, you can try it if you like:
> 
> `docker.io/haveagitgat/tdarr_acc:dev_2.18.01_2023_12_21T15_42_37z` `docker.io/haveagitgat/tdarr_node_acc:dev_2.18.01_2023_12_21T15_42_37z`
> 
> You'll need to set the following env/config vars on the server to activate it:
> 
> `auth=true` `authSecretKey=somesecretkeythatyoukeepsafe`
> 
> On startup you should be prompted to create an account:
> 
> ![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/f168ea21-2286-48c9-907e-0c5c5ee2befc)
> 
> Once you sign in you'll need to head to the `Tools->API Keys` page and create an API key for your Nodes to use.
> 
> You'll then need to set the `apiKey` env/config var for your Nodes so they can connect to your server.

This exact reply should be in the wiki/faq. Thanks, managed to have login with your help.

**Comment by HaveAGitGat** [comment]
It’s been in the docs for the last 10 months or so in case you missed it there 🙂
https://docs.tdarr.io/docs/other/authentication
