### ISSUE TITLE
encoding once

### ISSUE THREAD

**Issue by AwesomeGreat** [HaveAGitGat/Tdarr#299]
I want to encode my media, and output to a seperate folder, but i want to keep the originals aswell.
If i dont check "Delete source file", it encodes the already encoded file again and again and again.

How can i encode them, keep original, and not re encode them anymore?

Or what if i want to encode HEVC to HEVC. How to i stop infinite encoding?

**Comment by HaveAGitGat** [comment]
Hi, if you use v2 it won't loop (unless you are using plugins which are designed to loop). For example:

![image](https://user-images.githubusercontent.com/43864057/105856078-18060b00-5fe9-11eb-8a46-6f039e1ce194.png)

![image](https://user-images.githubusercontent.com/43864057/105856159-2d7b3500-5fe9-11eb-8174-0a7dead0332e.png)

Instructions here:
http://tdarr.io/docs/

Please reopen if you still need help.
