### ISSUE TITLE
Health Issue

### ISSUE THREAD

**Issue by AwesomeGreat** [HaveAGitGat/Tdarr#300]
I started an encode and interrupted it so it would be corrupt.

Mediainfo shows the file as Truncated. (which it is)

Tdarr health check (Thorough) shows the file as healthy (which its not)

Any way to solve this or does truncated not count as healthy lol

**Comment by kythorn** [comment]
Are you using the "output folder" option for your library, or letting it do it in place?

**Comment by HaveAGitGat** [comment]
If you know the exact error then it can be added here: https://github.com/HaveAGitGat/Tdarr/blob/master/private/ffmpegErrors.js
