### ISSUE TITLE
File scanner spawning multiple identical processes

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#301]
**Describe the bug**
While transcoding a single library, sometimes multiple instances of fileScanner.js get spawned with identical arguments.
/usr/bin/node assets/app/fileScanner/fileScanner.js "scannerID":"eKpQTPaKPge5TTSgh","DB_id":"eKpQTPaKPge5TTSgh","arrayOrPath":[],"arrayOrPathSwitch":0,"allowedContainers":["mkv","mp4","mov","m4v","mpg","mpeg","avi","flv","webm","wmv","vob","evo","iso","m2ts","ts"],"mode":3,"filePropertiesToAdd":{"HealthCheck":"Queued","TranscodeDecisionMaker":"Queued","cliLog":"","bumped":false,"history":""},"homePath":"/home/media/Documents","scanTypes":{"closedCaptionScan":false,"exifToolScan":false,"mediaInfoScan":false},"foldersToIgnore":[""],"resBoundaries":{"res480p":{"widthMin":100,"widthMax":792,"heightMin":100,"heightMax":528},"res576p":{"widthMin":"792","widthMax":"1100","heightMin":100,"heightMax":634},"res720p":{"widthMin":"1100","widthMax":1408,"heightMin":100,"heightMax":792},"res1080p":{"widthMin":100,"widthMax":2112,"heightMin":100,"heightMax:1188},"res4KUHD":{"widthMin":100,"widthMax":4224,"heightMin":100,"heightMax":2376},"resDCI4K":{"widthMin":100,"widthMax":4506,"heightMin":100,"heightMax":2376},"res8KUHD":{"widthMin":100,"widthMax":8448,"heightMin":100,"heightMax":5752}},"verboseLogs":false}

**To Reproduce**
Unsure, seems to happen at random.  One possible clue is that it tends to happen when there are multiple files queued that do not require transcoding.

**Expected behavior**
One instance of fileScanner.js per library.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Version: Tdarr Beta 1.207 (not dockerized)

**Comment by HaveAGitGat** [comment]
I believe this was fixed post 1.207 but I’ll double check it for v2

**Comment by HaveAGitGat** [comment]
Please try v2:

http://tdarr.io/docs/
