### ISSUE TITLE
Oops Something went wrong

### ISSUE THREAD

**Issue by spikemixture** [HaveAGitGat/Tdarr#302]
Refreshing and restarting sometimes gets past oops.

haveagitgat/tdarr:pro_1.3004-data-5

![image](https://user-images.githubusercontent.com/17228054/101277052-83530e00-37ec-11eb-89b4-d6a0e7bd6a99.png)

**Comment by HaveAGitGat** [comment]
Hi sorry about this, it will be fixed in v2, please see the notes here as it’s a duplicate: https://github.com/HaveAGitGat/Tdarr/issues/291#issuecomment-738905072
