### ISSUE TITLE
Tdarr not processing & "Value map does not contain the input value for this property" message in CMD

### ISSUE THREAD

**Issue by braedonsaunders** [HaveAGitGat/Tdarr#303]
I am running Tdarr 1.2070 on Windows without Docker. I have created a bat file to automatically start Tdarr. 
I setup my libraries, did an initial scan, and that went correctly. Next, I allowed it to start health checks on both libraries by creating several health check workers. This successfully performed health checks on 1500+ files, and then stopped working.

The web UI it still running, but no workers are processing anything. Restarting Tdarr does not help. The log does not mention anything unusual. The CMD console output is continuously displaying "Value map does not contain the input value for this property".

Any idea what is going on here? Thank you very much.

Edit: This seems to have to do with wmic.exe and a query parameter missing.

**Comment by HaveAGitGat** [comment]
Worth giving v2 a try if you're still having issues. 

http://tdarr.io/docs/

Feel free to re-open.
