### ISSUE TITLE
FFmpeg not detecting S_TEXT/WEBVTT subtitles

### ISSUE THREAD

**Issue by zmiguel** [HaveAGitGat/Tdarr#304]
**Describe the bug**
Transcode errors on all files with S_TEXT/WEBVTT subtitles

**To Reproduce**
Transcode any .mkv with webvtt subtitles with ffmpeg

**Expected behavior**
ffmpeg successfully identifies webvtt subtitles

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89

**Server**
- Docker
- tdarr_aio
- Beta 1.3003

**Additional context**
Using `Tdarr_Plugin_MC93_Migz1FFMPEG` plugin

```
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3
libavutil 56. 31.100 / 56. 31.100
libavcodec 58. 54.100 / 58. 54.100
libavformat 58. 29.100 / 58. 29.100
libavdevice 58. 8.100 / 58. 8.100
libavfilter 7. 57.100 / 7. 57.100
libswscale 5. 5.100 / 5. 5.100
libswresample 3. 5.100 / 3. 5.100
libpostproc 55. 5.100 / 55. 5.100
[matroska,webm @ 0x560556bfd780] Unknown/unsupported AVCodecID S_TEXT/WEBVTT.
[matroska,webm @ 0x560556bfd780] Could not find codec parameters for stream 2 (Subtitle: none): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

**Comment by HaveAGitGat** [comment]
Possible solution here:

https://stackoverflow.com/questions/61000319/ffmpeg-doesnt-detect-the-subtitle-format-webvtt-and-refuses-to-copy-it

**Comment by HaveAGitGat** [comment]
Solution above so closing this.

**Comment by codefaux** [comment]
The solution above causes damaged output files. An ffmpeg with proper webvtt support is required.

Some files may transcode properly, but I've run into an entire series of files which are problematic. They come packaged as mkv, and are proper according to mediainfo, vlc, mpv, etc etc. When attempting to transcode, I get error as above.

When writing a file with the above fix, the output file skips horribly, and is a much smaller filesize. Subtitles do not function, all video/audio tracks function.

Better results are achieved by forcing `-c:s:# srt` as decoder, even if `-c:s:# webvtt` is supplied as an output converstion; srt decoder seems capable of reading (most) webvtt subtitles but loses placement flags etc, however resulting file will play properly with either srt or webvtt encoding.

https://github.com/codefaux/tdarr_plugin_codefaux-mkvfixes
