### ISSUE TITLE
how to call ffprobe and ffmpeg?

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr#305]
Hello, I saw in the documentation that we could use ffprobe, but I don't understand how to use it and store the information in a variable afterwards?

I'm trying to get information for example birate and the "classic" method doesn't work all the time, can be used instead of ffmpeg to obtain this information.

```
const fs = require("fs");
const path = require("path");
let rootModules;
if (fs.existsSync(path.join(process.cwd(), "/npm"))) {
    rootModules = path.join(process.cwd(), "/npm/node_modules/");
} else {
    rootModules = "";
}

const ffprobePath = require(rootModules + 'ffprobe-static').path;
//do something with ffprobe
```

**Comment by HaveAGitGat** [comment]
In v2 you can set any external modules in the plugin and they will be auto installed. For example with the above:

```
module.exports.dependencies = [
  'ffprobe-static',
]

const fs = require("fs");
const path = require("path");
let rootModules;
if (fs.existsSync(path.join(process.cwd(), "/npm"))) {
    rootModules = path.join(process.cwd(), "/npm/node_modules/");
} else {
    rootModules = "";
}

const ffprobePath = require(rootModules + 'ffprobe-static').path;
//do something with ffprobe
```

V2 instructions here: 
http://tdarr.io/docs/

Please re-open if you still have an issue.
