### ISSUE TITLE
MongoDB fails to start

### ISSUE THREAD

**Issue by epiclulz666** [HaveAGitGat/Tdarr#306]
**Describe the bug**
MongoDB looks to be failing to start.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
unraid docker Version: 6.9.0-rc

**Additional context**

log

Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-setup-perms: executing...
usermod: no changes

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing...
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting MongoDB
[services.d] done.
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-setup-perms: executing...
usermod: no changes

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing...
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting MongoDB
[services.d] done.
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB
Starting MongoDB

**Comment by samcro1967** [comment]
Getting the same error.

**Comment by HaveAGitGat** [comment]
Please try v2 as MongoDB is no longer used:

http://tdarr.io/docs/
