### ISSUE TITLE
Hash functionality needed to identify updated files

### ISSUE THREAD

**Issue by mazzetta86** [HaveAGitGat/Tdarr#307]
**Is your feature request related to a problem? Please describe.**
If I update an already existing file (same name, different content), Tdarr won't recognise it as different (leaving it marked as healthy, even if the new file might be corrupted).

**Describe the solution you'd like**
Tdarr should implement a hash functionality. That could be implemented the same way as Snapraid. Snapraid firstly saves the timestamp and the hash of the file at the first iteration. During a scan, the timestamp is matched against the one in the database. If that is different, then the hash is recalculated and compared to the one in the database. If also the hash is different, the file should be re-queued for conversion and health check.

**Describe alternatives you've considered**
I could manually re-queue the files but that is not feasible for large arrays of files. 

**Additional context**
A very fast non-cryptographic hash should be used, to ensure unicity of the files, but at the same time not hampering the performance. Possibly the hash could be an optional setting.

**Comment by HaveAGitGat** [comment]
Hmm I'd need to see how much time it takes to get the timestamps when running a scan on 100,000+ files.

At the moment, if you have the folder watcher enabled, it should detect new files with the same file name.

**Comment by HaveAGitGat** [comment]
I tried a few hashing libraries but it would take potentially weeks/months to run a scan on large libraries as the whole file needs to be read to create a hash. 

Will leave this open for if anyone has a quick hash recommendation.

**Comment by tyhawk** [comment]
Wouldn't modification date and size (in bytes) differ if you place a new file with the same name but different content? These can be read directly from the host filesystem and shouldn't take up much processing power.

**Comment by mazzetta86** [comment]
As the author suggested if you use the Folder watch feature it works fine. If you want to run scans manually it won't. I have now enabled folder watch and I'm happy with it. I agree with you, it would be nice for Tdarr to check the creation/modification date at least.

**Comment by HaveAGitGat** [comment]
I've implemented an improvement for this in .08 so running `Scan (Find new)` will detect new files which have the same file name.

It's super quick too; takes about 2-3 seconds to find new files on an HDD with 5000 test files.

**Comment by DankMemeGuy** [comment]
I was going to start a new thread but I think it belongs here, but @HaveAGitGat when Tdarr compresses a h264 video into h265, are the hashes naturally different? For EXAMPLE, if I have a movie and it's been blacklisted by a cloud drive provider for pirated content, but then Tdarr runs the movie, compresses it down, and then I upload it back, would that file be cryptographically unique? Assuming the cloud provider has not also encoded a h265 version of that movie, correct?

Purely hypothetical.

**Comment by HaveAGitGat** [comment]
You might have to give that a google ;)
