### ISSUE TITLE
old/obsolete instructions / zip file issues

### ISSUE THREAD

**Issue by Commissar0617** [HaveAGitGat/Tdarr#308]
```

ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/sshpk-conv
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/sshpk-sign
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/sshpk-verify
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/uuid
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/which
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/rimraf
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/parser
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/node-gyp
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/.bin/node-pre-gyp
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/LICENSE
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/bin/babel-parser.js
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/lib/index.js
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/lib/index.js.map
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/CHANGELOG.md
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/README.md
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/package.json
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@babel/parser/typings/babel-parser.d.ts
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/underscore/LICENSE
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/underscore/README.md
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/underscore/index.d.ts
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/underscore/package.json
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/semver/LICENSE
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/semver/README.md
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/semver/index.d.ts
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/@types/semver/package.json
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/programs/server/npm-shrinkwrap.json
ERROR: Can not open output file : No such file or directory : /home/Tdarr-Linux-1.2070/bundle/star.json

Sub items Errors: 45183

Archives with Errors: 1
```

this is at the 7z step from https://github.com/HaveAGitGat/Tdarr/issues/95 

i did it slightly different to accomodate some differences in packager versions (i.e. nodejs is is debian apt repos already, you don't need a different repo), and using the newest version of Tdarr

sooo... the directions for deb buster are... well... broken, and the ubuntu directions are quite general, and the commands no compatible, so im muddling along as best i can...

**Comment by wsegatto** [comment]
Bump. I would gladly be a patron of this project like I am for Radarr but I mean, this is a ghost town. Who would want to be a patron if one doesn't even know how to install it?

**Comment by HaveAGitGat** [comment]
Hi, I’ve been working on v2 for the last couple of months or so. It’s a distributed transcoding system whereby you can put cross platform ‘Tdarr Nodes’ on different machines which all communicate with a  server to process your library.

I’m looking to have a decent version by the end of next week, the current preview version is working well for some: https://github.com/HaveAGitGat/Tdarr/tree/master/updater

All documentation will be updated next week.

**Comment by wsegatto** [comment]
Thanks for the info!
I have tried running the updater in my Raspberry PI OS ARMv8 64bits but it gives an error:
`./Tdarr_Updater: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`
Then I noticed that in the updater that you mention "linux_arm (Armv7 64)". It is supported for ARMv7 or ARMv8? AFAIK, ARMv7 is only 32 bits. 

PS: libatomic is installed in my system. Maybe I'm missing other packages? What does the updater require to be installed?

**Comment by Commissar0617** [comment]
> Hi, I’ve been working on v2 for the last couple of months or so. It’s a distributed transcoding system whereby you can put cross platform ‘Tdarr Nodes’ on different machines which all communicate with a server to process your library.
> 
> I’m looking to have a decent version by the end of next week, the current preview version is working well for some: https://github.com/HaveAGitGat/Tdarr/tree/master/updater
> 
> All documentation will be updated next week.

Sooo... ill have multiple terabytes of network traffic going to a remote server to reencode?

**Comment by wsegatto** [comment]
The "server" would be your own. You can have a local node in the same machine or you can distribute the workload. Seems nice to me.

But it seems this is not for ARMv8 (64bits). The description in README seems faulty. The updater works without any prerequisite (new system) in Raspberry PI OS (Debian) ARMv7 32 bits (armhf).

**Comment by wsegatto** [comment]
> Hi, I’ve been working on v2 for the last couple of months or so. It’s a distributed transcoding system whereby you can put cross platform ‘Tdarr Nodes’ on different machines which all communicate with a server to process your library.
> 
> I’m looking to have a decent version by the end of next week, the current preview version is working well for some: https://github.com/HaveAGitGat/Tdarr/tree/master/updater
> 
> All documentation will be updated next week.

I tried it in Windows and it "almost" worked. I say almost because there is an issue with the parameters order. It seems ffmpeg is picky regarding whether you put e.g. -vcoded copy _before_ or _after_ the -i <input file>. Tdarr puts the -i after, so it does not work. The solution would be to find (or create) your own plugin.

**Comment by Commissar0617** [comment]
> The "server" would be your own. You can have a local node in the same machine or you can distribute the workload. Seems nice to me.
> 
> But it seems this is not for ARMv8 (64bits). The description in README seems faulty. The updater works without any prerequisite (new system) in Raspberry PI OS (Debian) ARMv7 32 bits (armhf).

Oh ok. Males more sense

**Comment by HaveAGitGat** [comment]
@wsegatto thanks I removed the '64'.

Pleas try v2 and reopen if needed, thanks:
http://tdarr.io/docs/apiv2
