### ISSUE TITLE
Transcoding fails due to "Error: EPERM: operation not permitted,"

### ISSUE THREAD

**Issue by RobertKing42** [HaveAGitGat/Tdarr#309]
[This is on an up-to-date Linux Mint system.]

I've been pounding my head against this all day...

After transcoding a file, I get this:

> Attempting to move new file to original folder
> 
> Error: EPERM: operation not permitted, copyfile '/var/tmp/Tdarr/A Charlie Brown Christmas (1965)-TdarrCacheFile-mKtdLR1Oo.mkv' -> '/home/Tdarr/media/Christmas Movies/A Charlie Brown Christmas (1965)-TdarrNew.mkv.partial'
> 
> Deleting original file and moving new file unsuccessful

Both the source and destination folder's permissions are 0777.  I can create and delete files by hand in both those folders, but apparently Tdarr cannot.

**Comment by RobertKing42** [comment]
UPDATE:  This works then the destination is a local file but not when its a CIFS mount.

**Comment by k1lln1n3** [comment]
I have this issue too. Perfectly fine when its not a cifs mount. Doing the operation manually under the Tdarr user within the docker works perfectly fine.

**Comment by irakhlin** [comment]
Just wanted to note that this issue also happens with an NFSv3 mount as the media directory.

**Comment by lordairivis** [comment]
I also have this issue with beta 1.207 on Ubuntu Server 20.04.1. Manually ```mv```ing to the destination CIFS location successfully moves the file but still throws these errors.

[This post from StackExchange](https://unix.stackexchange.com/a/131181) suggests using ```cp``` then ```rm``` when preserving permissions is not important, or when moving across different filesystems. ```mv``` attempts to preserve permissions implicitly and will cause these issues. I suggest changing this ```mv``` operation to ```cp --no-preserve=mode``` followed by ```rm``` the local file once copying is completed, although I'm not sure how to make this change myself.

**Comment by wsegatto** [comment]
I'm having the same issue both with a cifs mount and local folder. Maybe this is an NPM/Node issue?

**Comment by irakhlin** [comment]
I ended up resolving this issue by switching the way my network share was being mounted in docker. I dropped in the docker-volume-netshare plugin on my docker host and used the following docker-compose to create the container:
`  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - tdarr-config:/home/Tdarr/Documents/Tdarr
      - tdarr-db:/var/lib/mongodb
      - "cifsMediaCC:/mnt/media"
    tmpfs:
      - /tmp
    networks:
      pub_net:
        ipv4_address: 10.255.255.52
    restart: unless-stopped
  volumes:
    cifsMediaCC:
        driver: cifs
        driver_opts:
            share: {my CIFS server}/{share path}
  networks:
    pub_net:
      external: true`

The relevant part being the drive mount for /mnt/media. There seemed to be other solutions but they involved heavily modifying the configuration of my NFS/CIFS server.

**Comment by wsegatto** [comment]
Maybe worth retrying with V2? I don't get issues for local folders, but for cifs and nfs mounts it fully copies the file but then deletes it and give out an error. Maybe something's happen after the "cp", something in regards to the rename functionality.

**Comment by RobertKing42** [comment]
Sorry.  I gave up on this a couple of weeks ago and just wrote my own
scripts to handle automated transcoding and validation.  Seems to work
fine, calling ffmpeg and/or handbrake directly.

**Comment by HaveAGitGat** [comment]
Worth trying with 2.00.03 as a different copy library is used.  Please reopen if needed. Thanks.
