### ISSUE TITLE
Container timezone set to GMT + 0

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#31]

**Comment by clifford64** [comment]
I have noticed this as well. I specify my timezone within my compose file, but it never changes the timezone in the container causing logs to show the incorrect time.

**Comment by HaveAGitGat** [comment]
Bump

**Comment by HaveAGitGat** [comment]
I've added server time to the dashboard to make this easier to resolve in the next version:
![image](https://user-images.githubusercontent.com/43864057/73603045-87cbec00-4575-11ea-9d3f-5cf1439218f5.png)

**Comment by HaveAGitGat** [comment]
For Docker add a TZ variable with a relevant timezone from this list:

https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones

For example: 

-e “TZ=Europe/London”

Working fine on tdarr_aio running Ubuntu. Need to add a package to tdarr running alpine in next update.

RUN apk add --no-cache tzdata

You can install that package immediately by using a terminal.

Use `container ls` to get the containerID

Run:

docker exec -it containerID /bin/ash

Run:

apk add --no-cache tzdata

**Comment by HaveAGitGat** [comment]
Added in for next release (1.105)
