### ISSUE TITLE
NodeJS version needs to be updated for Windows Installation Docs

### ISSUE THREAD

**Issue by burneystarke** [HaveAGitGat/Tdarr#310]
Not sure if I should leave this on git. 

I was getting the classic fiber.node missing issue after following the windows installation directions.
https://tdarr.io/docs/installation

I installed the latest version of 12.x instead of the version linked on the website and it worked. Here is a permalink to the 'latest 12.x'. Maybe if applicable this could be used in the docs?

https://nodejs.org/dist/latest-v12.x/

**Comment by HaveAGitGat** [comment]
Tdarr v2 doesn't require nodejs to be installed. Docs here:
http://tdarr.io/docs/
