### ISSUE TITLE
Transcode w/o filters loop

### ISSUE THREAD

**Issue by agpsn** [HaveAGitGat/Tdarr#311]
Any way to download h264/1080p and h265/2160p and not transcode same file repeatedly?

In the plugin, i can add filters, but if i add either, half wont be transcoded.

I transcode like this. (Yes i know i transcode 4k lol. I have transcoded versions because they look better than regular 1080p, and i have non transcoded 4k library)
1080p h264 >> 1080p h265
2160p h265 >> 1080p h265

**Comment by wsegatto** [comment]
Two libraries?

**Comment by HaveAGitGat** [comment]
Tdarr plugins are conditional, so you'd need to have a plugin which checks for a specific condition to determine if transcoding is needed or not.

To force transcoding, you can use the 'Video' switch with the filters left empty like this:
![image](https://user-images.githubusercontent.com/43864057/105607272-18f72c80-5d9e-11eb-9f00-d6caec2273f7.png)

**Comment by agpsn** [comment]
If i want the end results to be H265/1080p what filters would i use though?

source: h265/2160
source: h264/1080p
result: h265/1080p

i cant use the h265 filter or 1080p filter to prevent looping through the files repeatedly.

**Comment by HaveAGitGat** [comment]
You don't need to use any filter with the 'Video' setting. It will transcode all files regardless of their properties.

**Comment by HaveAGitGat** [comment]
The above method has been working well for me. Please re-open if needed. Thanks.

**Comment by agpsn** [comment]
Still doesn’t help :-(

In Sonarr/Radarr I allow it to download 2160p/H265 and if it’s not available in that, it downloads 1080p/H264.

If it downloads 2160p/H265 it gets encoded into 1080p/H265 so all files in library are 1080p/H265.

If it downloads 1080p/H264 it gets encoded into 1080p/H265 so all files in library are 1080p/H265.

In tdarr how do you encode BOTH 1080p/H264 and 2160p/H265 and NOT loop infinitely with 1080p/H265 not being touched?

**Comment by wsegatto** [comment]
Doesn't the Output folder history take care of that automatically?

**Comment by wsegatto** [comment]
And out of curiosity, why do you keep everything H265?

**Comment by agpsn** [comment]
[https://ibb.co/0Fthjbm](url)
I use those as the filters.

[https://ibb.co/rZk5ppZ](url)
that's the result of adding a 2160p/HEVC file to the library to process

If the source is 2160p AND HEVC, it is NOT encoded (which it should be). According to the filters, it should only skip files that are 1080p AND HEVC.

Its not processing the filters together but instead its processing any of the filters. (filters say "AND", but its doing "OR" lol)

As for why i keep everything in HEVC, is because its a smaller file size, all my devices support it, and its more convenient for my purposes.
