### ISSUE TITLE
V2 Preview tries to chown of entire library on start?

### ISSUE THREAD

**Issue by MRobi1** [HaveAGitGat/Tdarr#313]
Is this a bug or a feature?

Just tried to pull the v2preview tag on docker and on start it's running chown commands on every file in my library (and failing thank god).

No idea what it's trying to chown the files to, but this can cause some serious permission issues for basically every other app running that needs to access these same files.

Is this expected behavior with v2?

**Comment by HaveAGitGat** [comment]
The following folders are chowned on startup:

/home/Tdarr
/app
/temp
/logs

So make sure the stuff you don't want chowned is outside of those.

**Comment by MRobi1** [comment]
@HaveAGitGat thanks for clearing that up. I had mounted my media into /home/Tdarr/Media like the docker run example. I've since mounted it outside the /home directory and everything starts up just fine.

Now is there a secret to getting it to start processing? In 1.3xx it would automatically start and run until the database would crash a few hours later and give me the "Opps something is wrong" error. I've put in my tv series library in 2.0 before I go through the trouble of adding the rest, and it's sitting with 40,535 files in queue and has done nothing for hours.

**Comment by supersnellehenk** [comment]
> @HaveAGitGat thanks for clearing that up. I had mounted my media into /home/Tdarr/Media like the docker run example. I've since mounted it outside the /home directory and everything starts up just fine.
> 
> Now is there a secret to getting it to start processing? In 1.3xx it would automatically start and run until the database would crash a few hours later and give me the "Opps something is wrong" error. I've put in my tv series library in 2.0 before I go through the trouble of adding the rest, and it's sitting with 40,535 files in queue and has done nothing for hours.

You have to setup a second container, `tdarr_node`. That one does all the work. More info here: https://github.com/HaveAGitGat/Tdarr/tree/master/updater

**Comment by MRobi1** [comment]
> > @HaveAGitGat thanks for clearing that up. I had mounted my media into /home/Tdarr/Media like the docker run example. I've since mounted it outside the /home directory and everything starts up just fine.
> > Now is there a secret to getting it to start processing? In 1.3xx it would automatically start and run until the database would crash a few hours later and give me the "Opps something is wrong" error. I've put in my tv series library in 2.0 before I go through the trouble of adding the rest, and it's sitting with 40,535 files in queue and has done nothing for hours.
> 
> You have to setup a second container, `tdarr_node`. That one does all the work. More info here: https://github.com/HaveAGitGat/Tdarr/tree/master/updater

OK, I'm getting somewhere now. Sort of.
v2-dev would not start, but 1.99.11 starts up fine and with the second container for tdarr_node I'm able to control workers. But now both transcode and health check error out.

Transcode:
I've got it set for GPU transcoding. 
When I activate a GPU worker, the files show up under the worker, then go to the staging area with a status of "queued:requireCPU". I activated a CPU worker (even though I'm not using a CPU based plugin) and get a transcode error
`/Media/TV/(Un)Well/Season 01/(Un)Well - S01E04 - Fasting.mkv: No such file or directory Tdarr ALERT: NO OUTPUT FILE PRODUCED/temp/(Un)Well - S01E04 - Fasting-TdarrCacheFile-SNo6e9-Kq.mkv`

Health Check:
Regardless of CPU or GPU health check, I'm getting the same error
`Command:

HandBrakeCLI -i '/Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv' -o '/temp/2 Broke Girls - S01E16 - And the Broken Hearts-TdarrCacheFile-MavyE_zcq.mp4' --scan

Last 200 lines of CLI log:

Cannot load libnvidia-encode.so.1

[09:57:03] hb_init: starting libhb thread

[09:57:03] thread 7f0a9c111700 started ("libhb")

HandBrake 1.3.1 (2020080200) - Linux x86_64 - https://handbrake.fr

16 CPUs detected

Opening /Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv...

[09:57:03] CPU: Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz

[09:57:03] - Intel microarchitecture Sandy Bridge

[09:57:03] - logical processor count: 16

[09:57:03] Intel Quick Sync Video support: no

[09:57:03] hb_scan: path=/Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv, title_index=1

disc.c:323: failed opening UDF image /Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv

disc.c:424: error opening file BDMV/index.bdmv

disc.c:424: error opening file BDMV/BACKUP/index.bdmv

bluray.c:2585: nav_get_title_list(/Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv/) failed

[09:57:03] bd: not a bd - trying as a stream/file instead

libdvdnav: Using dvdnav version 6.0.1

libdvdread: Encrypted DVD support unavailable.

libdvdread: Can't stat /Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv

No such file or directory

libdvdread: Could not open /Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv

libdvdnav: vm: failed to open/read the DVD

[09:57:03] dvd: not a dvd - trying as a stream/file instead

[09:57:03] hb_stream_open: open /Media/TV/2 Broke Girls/Season 01/2 Broke Girls - S01E16 - And the Broken Hearts.mkv failed

[09:57:03] scan: unrecognized file type

[09:57:03] libhb: scan thread found 0 valid title(s)

No title found.

HandBrake has exited.

FFmpeg encountered the following errors with this file:`

**Comment by MRobi1** [comment]
OK, just experimenting and getting further.
I mounted all the same mount points to the node container as I did to the main container.

Health check is now processing fine with both GPU and CPU.
All files to be transcoded are still showing up in the staging area as "requireCPU".
The files first in queue are already all in hevc from already being processed in previous versions. 

So I guess the question is, do I need at least 1 cpu worker running in order to confirm already transcoded files?

**Comment by MRobi1** [comment]
Hit some h264 files and they're just getting moved to the "not required" section
15 | 10:34:53 | /Media/TV/24/Season 02/24.S02E24.Day 2- 7-00 A.M.-8-00 A.M..mkv | h264 | 480p | Not required | - | -
-- | -- | -- | -- | -- | -- | -- | --

Clicking on the Info button all it says is
`File has video in first stream
File meets conditions!
☒Plugin error! TypeError: plugin.details is not a function`
I'm using the same plugin stack I used in V1


I also have a lot sitting in staging with transcoding errors (instead of moving to the errors section.
`Command:

ffmpeg -c:v h264_cuvid -i '/Media/TV/24/Season 03/24.S03E23.Day 3- 11-00 A.M.-12-00 P.M..mkv' -map 0 -c:v hevc_nvenc -rc:v vbr_hq -cq:v 19 -b:v 200k -minrate 140k -maxrate 260k -bufsize 401k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 '/temp/24.S03E23.Day 3- 11-00 A.M.-12-00 P.M.-TdarrCacheFile-7KMyhVh_U.mkv'

Last 200 lines of CLI log:

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers built with gcc 9 (Ubuntu 9.3.0-10ubuntu2) configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3

libavutil 56. 31.100 / 56. 31.100 libavcodec 58. 54.100 / 58. 54.100 libavformat 58. 29.100 / 58. 29.100 libavdevice 58. 8.100 / 58. 8.100 libavfilter 7. 57.100 / 7. 57.100 libswscale 5. 5.100 / 5. 5.100 libswresample 3. 5.100 / 3. 5.100 libpostproc 55. 5.100 / 55. 5.100

Input #0, matroska,webm, from '/Media/TV/24/Season 03/24.S03E23.Day 3- 11-00 A.M.-12-00 P.M..mkv': Metadata: encoder : libebml v0.7.7 + libmatroska v0.8.1 creation_time : 2009-03-21T15:09:41.000000Z Duration: 00:39:46.48, start: 0.000000, bitrate: 421 kb/s

Stream #0:0: Video: h264, yuv420p(progressive), 640x368, SAR 1:1 DAR 40:23, 25 fps, 25 tbr, 1k tbn, 50 tbc (default) Stream #0:1(dut): Audio: aac, 48000 Hz, stereo, fltp (default)

[h264_cuvid @ 0x55d89de8f1c0] Cannot load libnvcuvid.so.1 [h264_cuvid @ 0x55d89de8f1c0] Failed loading nvcuvid.

Stream mapping: Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc)) Stream #0:1 -> #0:1 (copy) Error while opening decoder for input stream #0:0 : Operation not permitted`

**Comment by HaveAGitGat** [comment]
> OK, just experimenting and getting further.
> I mounted all the same mount points for my media files to the node container as I did to the main container.
> 
> Health check is now processing fine with both GPU and CPU.
> All files to be transcoded are still showing up in the staging area as "requireCPU".
> The files first in queue are already all in hevc from already being processed in previous versions.
> 
> So I guess the question is, do I need at least 1 cpu worker running in order to confirm already transcoded files?

Yes GPU workers are only for GPU tasks. A lot of plugins have  CPU related stuff in like remuxing and manipulating audio streams which are done using CPU.

`TypeError: plugin.details is not a function`

Sounds like there may be an invalid plugin in the stack. Someone else mentioned a similar issue, working on fixing that.

**Comment by MRobi1** [comment]
> > OK, just experimenting and getting further.
> > I mounted all the same mount points for my media files to the node container as I did to the main container.
> > Health check is now processing fine with both GPU and CPU.
> > All files to be transcoded are still showing up in the staging area as "requireCPU".
> > The files first in queue are already all in hevc from already being processed in previous versions.
> > So I guess the question is, do I need at least 1 cpu worker running in order to confirm already transcoded files?
> 
> Yes GPU workers are only for GPU tasks. A lot of plugins have CPU related stuff in like remuxing and manipulating audio streams which are done using CPU.
> 
> `TypeError: plugin.details is not a function`
> 
> Sounds like there may be an invalid plugin in the stack. Someone else mentioned a similar issue, working on fixing that.

Got what seems to be working. The node container was already set with the nvidia runtime.
However I had to add an environment variable of
NVIDIA_VISIBLE_DEVICES=all

and for good measure I changed
NVIDIA_DRIVER_CAPABILITIES=all

I do have audio tasks running which would require cpu which explains the requireCPU.

Is there a way to make tdarr process them at the same time. IE: Finish the video transcode with the GPU and imediately start the audio with the CPU?

I've setup an 8gb ramdisk to minimize wear on the SSD. The GPU is processing the video, then it's getting put back into to the staging area for the CPU to do it's thing on audio, leaving the temp files on the ramdisk while it waits for the cpu task. And since the CPU is much slower, I'm now just filling the staging area with
"Error writing trailer of /temp/24.S09E11.Day 9- 9-00 P.M. - 10-00 P.M.-TdarrCacheFile-eDkcbjq9q.mkv: No space left on device"

Also, after it's spitting out the error, it stays in the staging area. It doesn't move to the transcode error section. I can re-queue, but it's a big pain clicking the button on each individial file. A re-queue all button would be nice in the staging area OR have the error'd files move to the transcode error section so they can be requeued there.

**Comment by MRobi1** [comment]
@HaveAGitGat further to my example above, I emptied the temp drive. Started 1 GPU worker and 6 CPU workers thinking the CPU would be able to keep up. Came back a bit over an hour later to over 800 files sitting in the staging area with a transcode error for no space left on device. The ones with the temp files were buried in the staging area queue, I'd say with 3-400 files in front of them.

So I've spent the last hour clicking "requeue" on each of the individual 800 files since there's no requeue all button in the staging area and they're not going to the failed transcode area.

**Comment by wsegatto** [comment]
You could have requeued your entire library, maybe? Already transcoded files are skipped.

**Comment by MRobi1** [comment]
> You could have requeued your entire library, maybe? Already transcoded files are skipped.

There's a "Requeue All" button that's been implemented in the staging area for 1.99.13.
But I'm still having issues with my tmpfs drive filling up because the gpu and cpu process their parts of the file seperately instead of together.

I've got 6 plugins. Re-order, gpu transcode, then the rest are audio. After the gpu transcodes the video, the file gets put back into the staging area to wait for the cpu to do the audio. But in the meantime, the staging area keeps getting filled with more files to process and they end up in front of the ones the gpu just finished. I ran 1.99.13 for 20-30 mins, filled my 8gb tmpfs drive and had 520 files in the staging area waiting for workers to free up. 

Previously, when a worker grabbed a file, it would run plugins 1 through 6 on the file and when complete it would overwrite the original and move on to the next. I could run 12 gpu workers with no issues.

**Comment by HaveAGitGat** [comment]
As mentioned on Reddit, .14 now has an option to allow GPU workers to do CPU tasks which should fix your issue:
![image](https://user-images.githubusercontent.com/43864057/105607342-6378a900-5d9e-11eb-9687-fe7f506cdc44.png)

It does not apply to items already marked as 'Require CPU' as that would interfere with the 'Node hardware encoding type' option. For those items, launch a CPU worker.

**Comment by MRobi1** [comment]
> As mentioned on Reddit, .14 now has an option to allow GPU workers to do CPU tasks which should fix your issue:
> ![image](https://user-images.githubusercontent.com/43864057/105607444-0fba8f80-5d9f-11eb-933b-40757821b61f.png)
> 
> It does not apply to items already marked as 'Require CPU' as that would interfere with the 'Node hardware encoding type' option. For those items, launch a CPU worker.

Awesome!! I'll spin it up now and give it a shot and report back

**Comment by MRobi1** [comment]
@HaveAGitGat I've got 8 GPU workers running and been up for about 3hrs now. 
The only thing in my staging area now are the 8 files being processed. I've had no transcode errors and no files "waiting" for a cpu or gpu worker. I'll bump it up to 12 workers, but considering I've had 8 running for 3hrs where before I couldn't even run 1 worker for 1 hour I'm pretty confident that I can say this fixed the issue.

**Comment by MRobi1** [comment]
@HaveAGitGat I increased my tmpfs drive size to 16Gb from 8Gb and set my TV Series directory to transcode. I left it at 8 workers because it had been working for a few hours. I left this unsupervised for a bit more than 24hrs.

I just came back, there's 10 files in the staging area with drive is full errors. Looking at the tmpfs drive, there are 35 temp files in there. The 10 from the staging area plus 25 others. In the Transcode: Error/Cancelled section, there are 22,952 files.

I'd really like to be able to set this and forget it. Is it possible to have an option that if the transcode fails to remove the temp file? This way it wouldn't cause others to get backed up while it waits for user input on what to do with the failed file.

**Comment by HaveAGitGat** [comment]
Sure I'll add that option in.

**Comment by HaveAGitGat** [comment]
Added in for 2.00.02:
![image](https://user-images.githubusercontent.com/43864057/106099231-a0e08c00-613a-11eb-9353-7602feb21380.png)

**Comment by HaveAGitGat** [comment]
@MRobi1 can you try 2.00.02 pre-release? It's on Windows and Docker, just specify the 2.00.02 tag. Thanks.

**Comment by MRobi1** [comment]
> @MRobi1 can you try 2.00.02 pre-release? It's on Windows and Docker, just specify the 2.00.02 tag. Thanks.

Installing it now

**Comment by MRobi1** [comment]
@HaveAGitGat Looks like you've nailed it! Updated within minutes of my last post. It's been just a bit shy of 48hrs now. I've got 10 GPU workers going and it seems to be chugging away like V1 used to.

**Comment by HaveAGitGat** [comment]
Great, thanks for the feedback. Will close this once 2.00.02 is moved into latest.
