### ISSUE TITLE
V2 on macOS: Download of Tdarr_Node gets error unzipping

### ISSUE THREAD

**Issue by clunkclunk** [HaveAGitGat/Tdarr#320]
**Describe the bug**
V2 preview on macOS: Download of Tdarr_Node gets error unzipping.

**To Reproduce**
• Download Tdarr_Updater darwin_x64 to a directory on your Mac
• In Terminal, cd to said directory,
• `xattr -d com.apple.quarantine Tdarr_Updater` to remove macOS quarantine
• `./Tdarr_Updater`, note EOF error during unzipping of Tdarr_Node (other modules seem to download just fine, aside from Tdarr_Desktop, but that seems expected).

```
[2021-01-24T11:08:25.501] [INFO] Tdarr_Updater - Tdarr_Node | Current version:  | Required version: 2.00.00
Downloading:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%)
[2021-01-24T11:08:30.102] [INFO] Tdarr_Updater - Tdarr_Node | Downloaded!
[2021-01-24T11:08:30.107] [INFO] Tdarr_Updater - Tdarr_Node | Unzipping!
[2021-01-24T11:08:30.561] [ERROR] Tdarr_Updater - Tdarr_Node | Error: unexpected end of file
[2021-01-24T11:08:30.564] [ERROR] Tdarr_Updater - Tdarr_Node | Error unzipping!
[2021-01-24T11:08:30.564] [INFO] Tdarr_Updater - 
```

**Expected behavior**
Successful unzip of Tdarr_Node

**Desktop (please complete the following information):**
Issue reproduced on both Intel and Apple Silicon platforms and two different OS versions:
• macOS "Big Sur" 11.1 on Mac Mini (2020) on M1 Apple Silicon CPU
• macOS "Catalina" 10.15.7 on MacBook Pro (2015) on i7 Intel CPU

**Additional context**
I'm not all up to date on what's required to sign macOS apps so they aren't quarantined, but the download of Tdarr_Updater won't launch by default. `xattr -d com.apple.quarantine Tdarr_Updater` solves it.

**Comment by wsegatto** [comment]
Try executing the uploaded from another folder (forcing re-download). Maybe something went wrong when downloading?

Either that or the zip file had an issue during its upload by the owner.

**Comment by clunkclunk** [comment]
> Try executing the updater from another folder (forcing re-download). Maybe something went wrong when downloading?

Yeah, I considered that, so I tried it. As well as I replicated the entire problem on a completely separate machine, running a different OS and architecture.

> 
> Either that or the zip file had an issue during its upload by the owner.

That's my guess. Something is corrupt in the zip that's being downloaded and it gets an EOF.

**Comment by wsegatto** [comment]
@HaveAGitGat, could you please double check MacOS's zip file for V2?

**Comment by HaveAGitGat** [comment]
Please try 2.00.01 using this method:
https://github.com/HaveAGitGat/Tdarr/issues/327#issuecomment-767516511

**Comment by jasonsansone** [comment]
> Please try 2.00.01 using this method:
> [#327 (comment)](https://github.com/HaveAGitGat/Tdarr/issues/327#issuecomment-767516511)

This worked to install Tdarr_Node on macOS Big Sur (Intel based).

**Comment by HaveAGitGat** [comment]
@jasonsansone Great, thanks

**Comment by jasonsansone** [comment]
This should probably be closed.  Fixed in 2.00.01 release.

**Comment by HaveAGitGat** [comment]
Thanks

**Comment by clunkclunk** [comment]
I can confirm as well, resolved! Thanks.
