### ISSUE TITLE
V2 has excessive CPU usage while idle.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#321]
**Describe the bug**
When tdarr is idle, and has nothing to process the cpu usage is high. If no worker nodes are enabled then the server process runs the queue builder continuously, even if there are no changes to files or libraries. This causes spikes of cpu use every time it's run.

```
tdarr_new     | [2021-01-24T22:25:51.020] [INFO] Tdarr_Server - Queue builder launched
tdarr_new     | [2021-01-24T22:25:51.505] [INFO] Tdarr_Server - [0.003s] queue builder data received
tdarr_new     | [2021-01-24T22:25:51.509] [INFO] Tdarr_Server - verbose:[0.485s] Queue builder finished. 0 files processed
tdarr_new     | [2021-01-24T22:25:51.546] [INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end
tdarr_new     | [2021-01-24T22:25:52.548] [INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end
tdarr_new     | [2021-01-24T22:25:53.548] [INFO] Tdarr_Server - Queue builder launched
tdarr_new     | [2021-01-24T22:25:54.045] [INFO] Tdarr_Server - [0.003s] queue builder data received
tdarr_new     | [2021-01-24T22:25:54.055] [INFO] Tdarr_Server - verbose:[0.506s] Queue builder finished. 0 files processed
tdarr_new     | [2021-01-24T22:25:54.081] [INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end
tdarr_new     | [2021-01-24T22:25:55.082] [INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end
```

If workers are enabled on the node which is on the same machine, then each worker also polls the server once per second. With a transcode worker and several health check workers enabled I see spikes to over 50% cpu usage once per second as the workers continuously start, request work and exit:

```
tdarr_new_node | [2021-01-24T22:42:48.131] [INFO] Tdarr_Node - verbose:Worker ZrB-dDwkNN launched
tdarr_new     | [2021-01-24T22:42:48.619] [INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end
tdarr_new_node | [2021-01-24T22:42:48.827] [INFO] Tdarr_Node - verbose:Requesting item
tdarr_new_node | [2021-01-24T22:42:48.832] [INFO] Tdarr_Node - verbose:Item request received
tdarr_new_node | [2021-01-24T22:42:48.833] [INFO] Tdarr_Node - verbose:Getting new task
tdarr_new_node | [2021-01-24T22:42:48.832] [INFO] Tdarr_Node - verbose:Requesting item
tdarr_new     | [2021-01-24T22:42:48.836] [INFO] Tdarr_Server - verbose:Worker taa7VdfHtp requesting item. Nothing to process for this worker.
tdarr_new_node | [2021-01-24T22:42:48.838] [INFO] Tdarr_Node - verbose:Item request received
tdarr_new_node | [2021-01-24T22:42:48.839] [INFO] Tdarr_Node - verbose:Getting new task
tdarr_new     | [2021-01-24T22:42:48.841] [INFO] Tdarr_Server - verbose:Worker ev6h4Tl6V requesting item. Nothing to process for this worker.
tdarr_new_node | [2021-01-24T22:42:48.842] [INFO] Tdarr_Node - verbose:Exit request
tdarr_new_node | [2021-01-24T22:42:48.842] [INFO] Tdarr_Node - verbose:Worker exit request received
tdarr_new_node | [2021-01-24T22:42:48.843] [INFO] Tdarr_Node - verbose:Exiting
tdarr_new_node | [2021-01-24T22:42:48.845] [INFO] Tdarr_Node - verbose:Worker exit request received
tdarr_new_node | [2021-01-24T22:42:48.845] [INFO] Tdarr_Node - verbose:Exit request
tdarr_new_node | [2021-01-24T22:42:48.846] [INFO] Tdarr_Node - verbose:Exiting
tdarr_new_node | [2021-01-24T22:42:48.859] [INFO] Tdarr_Node - verbose:Worker exited
tdarr_new_node | [2021-01-24T22:42:48.860] [INFO] Tdarr_Node - verbose:Worker exited
tdarr_new_node | [2021-01-24T22:42:48.890] [INFO] Tdarr_Node - verbose:Requesting item
tdarr_new_node | [2021-01-24T22:42:48.894] [INFO] Tdarr_Node - verbose:Item request received
tdarr_new_node | [2021-01-24T22:42:48.895] [INFO] Tdarr_Node - verbose:Getting new task
tdarr_new     | [2021-01-24T22:42:48.896] [INFO] Tdarr_Server - verbose:Worker ZrB-dDwkNN requesting item. Nothing to process for this worker.
tdarr_new_node | [2021-01-24T22:42:48.899] [INFO] Tdarr_Node - verbose:Worker exit request received
tdarr_new_node | [2021-01-24T22:42:48.899] [INFO] Tdarr_Node - verbose:Exit request
tdarr_new_node | [2021-01-24T22:42:48.899] [INFO] Tdarr_Node - verbose:Exiting
tdarr_new_node | [2021-01-24T22:42:48.914] [INFO] Tdarr_Node - verbose:Worker exited
tdarr_new     | [2021-01-24T22:42:49.620] [INFO] Tdarr_Server - Queue builder launched
tdarr_new_node | [2021-01-24T22:42:50.088] [INFO] Tdarr_Node - verbose:Launching worker
tdarr_new_node | [2021-01-24T22:42:50.089] [INFO] Tdarr_Node - verbose:Launching worker
tdarr_new_node | [2021-01-24T22:42:50.089] [INFO] Tdarr_Node - verbose:Launching worker
tdarr_new     | [2021-01-24T22:42:50.092] [INFO] Tdarr_Server - [0.007s] queue builder data received
tdarr_new     | [2021-01-24T22:42:50.100] [INFO] Tdarr_Server - verbose:[0.48s] Queue builder finished. 0 files processed
```

**To Reproduce**
Start both server and node containers without any libraries configured.

**Expected behavior**
When no files require processing, the server and workers should consume minimal cpu, not continuously take up cpu cycles where there's no work to be done.

This may not be so noticeable on a powerful cpu, but on devices using lower spec hardware such as NAS boxes this can have an impact on other services running on the device.

**Screenshots**
tdarr server container cpu usage while idle:
![image](https://user-images.githubusercontent.com/7763268/105645977-1a575080-5e95-11eb-8dc7-5aa844f72b99.png)

tdarr node container cpu usage while idle, with 1 gpu worker and 4 health check workers enabled:
![image](https://user-images.githubusercontent.com/7763268/105646027-699d8100-5e95-11eb-90b8-5cc9f2ef5f54.png)

Difference of total cpu with tdarr running and stopped:
![image](https://user-images.githubusercontent.com/7763268/105646147-30b1dc00-5e96-11eb-8515-06933948c000.png)

**Desktop (please complete the following information):**
 - V2-preview docker containers running on ubuntu 20.04
 - System is a J4105 quad core celeron.
 

**Additional context**
v1 of tdarr did not exhibit this behaviour while idle - cpu usage was minimal unless actually transcoding.

**Comment by Little709** [comment]
After seeing this on the discord.

bump.

**Comment by HaveAGitGat** [comment]
Thanks will look at this tomorrow.

**Comment by HaveAGitGat** [comment]
Server 2.00.021 (in 2.00.02), should now use much less cpu when idle. Improving the nodes will take a bit more work.

**Comment by caiusseverus** [comment]
Just tried 2.00.02 and it's idling at 1% or less now, which is much better.

**Comment by HaveAGitGat** [comment]
Great, thanks for the feedback.

**Comment by idittansikte** [comment]
I've upgraded to 2.00.03 and server is at steady 5-7% CPU while idling and the node is at average 80% CPU while idling. RAM usage is at 430MB for server and node 90-230MB while idling. All this is a bit too much in my opinion. I would expect 0-5% CPU while idling (as my other 15 server processes) and maybe 100MB RAM for each process. I'm running this on an already busy server so this is unacceptable for me.

PS. Very nice peace of software which works as expected otherwise.

**Comment by reloxx13** [comment]
tdarr v2 in idle uses around 40-60wattage, which are over 1000-1400kwh per day which is crazy for an idling system.
no healthcheck and no transcodes r done.

**Comment by Little709** [comment]
Although I agree that this needs more attention, I think you are messing up some factors there. And it does not scale that way.

**Comment by reloxx13** [comment]
> 
> 
> Although I agree that this needs more attention, I think you are messing up some factors there. And it does not scale that way.

i have an energy meter and it how 1400kwh more when running tdarr.

**Comment by Little709** [comment]
1400kWh per day is impossible. It would mean that your pc has a power supply that can accept 58 kilowatts of power.

Idle usage of 50 watts will consume 1.2 kWh per day

**Comment by reloxx13** [comment]
1,4, sry

**Comment by Little709** [comment]
I've done some extra research on the issue. It seems that it only occurs when workers are active. 

It seems tasks are constantly being assigned to the workers but are instantly exited because no actual work has to be done

**Comment by HaveAGitGat** [comment]
![image](https://user-images.githubusercontent.com/43864057/107844732-5d427f00-6dd6-11eb-8a99-e1d0dc21efc6.png)
@caiusseverus every second or so the node launches a worker of each type if the running number of workers is less than the limit. This should be a super lightweight process - it does not even show up for me when looking at CPU utilisation on task manager. On your system I'm assuming something is either incorrectly logging the CPU utilisation or, for some reason, it's a much more expensive task to launch a worker.

I've just put 2.00.05 into pre-release which improves things so that the nodes will only launch workers when there are items related to that worker type in the queues (staging section or main queue).

Let me know if you still have the same issue, thanks.

**Comment by caiusseverus** [comment]
I don't think it's incorrectly logging - that graph is from Netdata, however I can see the same thing happening in other process monitors (htop, top, glances, portainer etc). The system it's running on is ubuntu 20.04, using the docker containers. Hardware is a quad core Celeron J4105, so not massively powerful in regards to CPU, but I don't know what would make it especially expensive to launch workers - there's nothing particularly unusual about the system.

Anyway, I have updated to 2.00.05 and it is much better - node container cpu is basically nothing while idle. The server container sits around 10% of one core while idle, which isn't really a problem . I'd say this issue is pretty much resolved with this change.

**Comment by idittansikte** [comment]
Running a J5005 CPU and can also confirm 2.00.05 is much better. Server at ~2.5% and node ~1% while idling. Docker stats however shows about 500MB memory usage on the server which is very high.
