### ISSUE TITLE
Remixing video not using CPU worker

### ISSUE THREAD

**Issue by soultaco83** [HaveAGitGat/Tdarr#322]
**Describe the bug**
The task to remix video on versions 1.99.14 and V2 are not allowed to use the cpu workers and showing requires GPU worker. I have gone back to version 1.99.13 for testing and remixing is properly using the cpu worker. 

**To Reproduce**
Steps to reproduce the behavior: Installed version 2 or 1.99.13 and attempt to remix video. Attached is the plugin I am using. A member of the community created it for me.
[remuxalways.zip](https://github.com/HaveAGitGat/Tdarr/files/5864688/remuxalways.zip)

**Expected behavior**
Remixing should be allowed to use cpu workers

**Comment by soultaco83** [comment]
![Capture](https://user-images.githubusercontent.com/76927195/105671336-898e6e00-5eb0-11eb-9562-5df10b10ff6c.PNG)
I found that if I uncheck the box: Allow GPU workers to do CPU tasks
then turning on CPU workers allows it to process just fine.

**Comment by HaveAGitGat** [comment]
Hi thanks, for me it was the other way around. If the switch is OFF then it gives a 'require GPU' error when trying to remux.  I've fixed this. Will put the release out later today.

**Comment by HaveAGitGat** [comment]
This should now be fixed in 2.00.01, you can try it using this method (or specify tag 2.00.01 if on Docker):
https://github.com/HaveAGitGat/Tdarr/issues/327#issuecomment-767516511

**Comment by soultaco83** [comment]
@HaveAGitGat After the new update I have a new error on my windows and docker node. 
![image](https://user-images.githubusercontent.com/76927195/105856067-c9d81400-5fb6-11eb-9bb9-eb3a40ce633b.png)
![image](https://user-images.githubusercontent.com/76927195/105856122-da888a00-5fb6-11eb-9289-e5093c882408.png)


I am unsure if this is of concern.

**Comment by soultaco83** [comment]
On the windows node at the very least it is keeping the files from being processed. They queue but then never update with percentages. 
I have tried with both gpu and cpu workers. Also with Allow GPU workers to do CPU tasks (This will not have any effect on items already marked as 'Require CPU'): toggled on and off

**Comment by HaveAGitGat** [comment]
That log is fine, plugin dependencies are auto installed if they're not in that node_modules folder. The package-lock is auto generated when dependencies are installed.

As discussed on Discord, the issue was due to trailing slashes on the pathTranslators paths. 2.00.02 will remove trailing slashes automatically.
