### ISSUE TITLE
Revise v2 Instructions to install linux prerequisite packages

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#324]
**Describe the bug**
Current instructions do not fully detail all required packages for Linux operating systems. For example: wget is required to pull Tdarr_Updater.zip, unzip is necessary to extract it, software-properties-common is needed to add repo’s, handbrake-cli ffmpeg and mkvtoolnix are needed for encoding.  At minimum, it might help the less line savvy to understand the list of prerequisites.

I suggest advising the following line of code prior to downloading Tdarr_Updater.zip:

(optional) add repositories for [Handbrake](https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases) and [mkvtoolnix](https://mkvtoolnix.download/downloads.html)
For Debian and Ubuntu: apt-get -q update && apt-get -y -q dist-upgrade && apt install -y wget unzip handbrake-cli ffmpeg mkvtoolnix software-properties-common && apt-get -q autoremove --purge && apt-get -q clean

**To Reproduce**
Download v2 on linux.  Without unzip package, the user can’t extract the archive.  Etc etc.

OS: Ubuntu 20.04.1 LTS as LXC container on Proxmox 5.4.78-2
Tdarr Version: 2.00.00

**Comment by HaveAGitGat** [comment]
Thanks, I'll add this to the instructions

**Comment by cbrherms** [comment]
@HaveAGitGat
These appear to still be missing? Or if they're in there it is not clear.

This, along with the systemd config mentioned in another issue, would be useful for those of us who do not wish to use the docker image.
