### ISSUE TITLE
Tdarr_Node archive doesn't extract for Darwin x64

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#328]
**Describe the bug**

The macOS node package is either corrupted or malformed somehow.

`[2021-01-25T15:18:38.615] [INFO] Tdarr_Updater - Tdarr_Node | Tdarr_Node_darwin_x64_2.00.00.zip already exists!
[2021-01-25T15:18:38.615] [INFO] Tdarr_Updater - Tdarr_Node | Unzipping!
[2021-01-25T15:18:39.520] [ERROR] Tdarr_Updater - Tdarr_Node | Error: unexpected end of file
[2021-01-25T15:18:39.520] [ERROR] Tdarr_Updater - Tdarr_Node | Error unzipping!`

`jasonsansone@home-desktop Tdarr_Node % ./Tdarr_Node
Pkg: Error reading from file.`

**To Reproduce**
Download and install Darwin x64 version of Tdarr v2.

**Screenshots**

![Screen Shot 2021-01-25 at 3 22 04 PM](https://user-images.githubusercontent.com/14913945/105767876-3accec80-5f21-11eb-8467-b98b5d24b76d.png)

**Desktop (please complete the following information):**
macOS Big Sur 11.1 (20C69)

**Comment by clunkclunk** [comment]
Looks like the issue I reported yesterday: https://github.com/HaveAGitGat/Tdarr/issues/320

**Comment by jasonsansone** [comment]
Yes, it appears to be a duplicate. I will close this issue. Thank you.
