### ISSUE TITLE
Loading some plugins results in a module read error... "import-fresh".

### ISSUE THREAD

**Issue by dhoffman98** [HaveAGitGat/Tdarr#329]
Attempting to load some plugins results in a read error indicating that a module could not be found.

Error: Cannot find module 'import-fresh' Require stack: - /app/Tdarr_Server/assets/app/plugins/Community/Tdarr_Plugin_NIfPZuCLU_2_Pass_Loudnorm_Audio_Normalisation.js - /snapshot/tdarr_express_be/src/pluginFuncs.js - /snapshot/tdarr_express_be/src/main.js

**To Reproduce**
Go to the Plugins tab.
Search for plugins.
Some results produce error that appears in the descriptions on the plugins screen and prevents the plugin from being loaded into a stack.

For example, two plugins that I have found so far:
-- Tdarr_Plugin_NIfPZuCLU_2_Pass_Loudnorm_Audio_Normalisation
-- Tdarr_Plugin_O8O0dCTlb_Set_File_Permissions_For_UnRaid

Both plugins call an include statement asking for a module called "import-fresh", however the module does not seem to be found, resulting in the error.

**Expected behavior**
Descriptions would be displayed properly, and when executing as part of a stack, should not result in errors.

**Environment:**
Version 2.0.0 installed via Docker on Unraid
Installed via haveagitgat/tdarr:v2-preview

**Comment by HaveAGitGat** [comment]
Please try the new Tdarr 2.00.01 image (it is not yet in v2-preview image).

**Comment by dhoffman98** [comment]
Started over with the 2.00.01 images for both server and node.
On the server side, still getting the error trying to load module "import-fresh".

![image](https://user-images.githubusercontent.com/41883171/105868016-55ec3a80-5fbb-11eb-82ca-6327a62404a4.png)

**Comment by HaveAGitGat** [comment]
Open the plugin and move the 'require' of 'import-fresh' inside the 'plugin function:

![image](https://user-images.githubusercontent.com/43864057/105871942-1d1f8600-5ffa-11eb-99c1-1afb9ffc7d5f.png)

I'll update the docs.

**Comment by dhoffman98** [comment]
Testing interrupted by a new issue. Filed new issue #332.
Will return to testing this one once the other is resolved.

**Comment by dhoffman98** [comment]
OK, Issue #332 made it difficult to test because I kept overwriting the community plugins.
However... I copied "Tdarr_Plugin_NIfPZuCLU_2_Pass_Loudnorm_Audio_Normalisation.js" into the LOCAL plugins directory, changed the ID, and then edited that plugin.

I moved the following two lines...
> const importFresh = require(rootModules + 'import-fresh');
> const library = importFresh('../methods/library.js')

... into the "module.exports.plugin" function.

**Results are good!** Worked as expected.

So, not really a code problem for the application... just for the two plugins that independently call import-fresh.

**Comment by dhoffman98** [comment]
Scratch that.... now the plugin can be loaded, but still getting read errors showing up in the GUI.

**Comment by dhoffman98** [comment]
OK, I've done more testing on 2.0.02 and I think the errors are still the result of a few plugins that might need to be modified with your instructions from above.

This one can probably be closed.

**Comment by HaveAGitGat** [comment]
Ok thanks. For anyone who has the issue saying import-fresh is missing (although this should be now fixed), you can download the import-fresh modules from Tdarr_Plugins:

https://github.com/HaveAGitGat/Tdarr_Plugins/tree/master/node_modules

Put the `node_modules` next to the 'Local' plugins folder inside Tdarr_Node. On Docker this would be in `app/Tdarr_Node/assets/app/plugins`

![image](https://user-images.githubusercontent.com/43864057/107148227-71a7f700-6952-11eb-9d1d-94b20bb0b033.png)
