### ISSUE TITLE
Prioritising of libraries

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#33]
> Say I have three different libraries configured, I would like to "rank" those libraries 1, 2 and 3 in order of prioritzation. Example - Library 1 has 200 files and is Prority 1, Library 2 is 500 files and is P2 and Library 3 is 3,000 files and is P3. Library 1 has completed processing everything but has Folder Watch enabled. Library 2 is currently in process as is Library 3. When a new item is detected in Library 1, since it has a higher priority than Library 2 or Library 3, that new item bumps up automatically to the top of the queue.

**Comment by marshalleq** [comment]
Great idea.  I've actually not even added a second library due to this - I want this library done first.  Also because I don't want the stats of the second library to interfere with the first - something on the roadmap I believe.

**Comment by HaveAGitGat** [comment]
Added in 1.005
