### ISSUE TITLE
Phantom Processes

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#331]
**Describe the bug**
Server is showing cpu checks or transcodes that aren't actually occurring.  Photo is when all nodes were idle.  The phantom processes count against the actual process limit, so for example if the node is allocated four CPU encodes, at times only three will occur as it believes four are happening.  I had to restart one node to clear the phantom transcode process.

![Screen Shot 2021-01-26 at 2 02 32 PM](https://user-images.githubusercontent.com/14913945/105898582-3b2bbd00-5fdf-11eb-8b84-464686e374cd.png)

![Screen Shot 2021-01-26 at 2 04 58 PM](https://user-images.githubusercontent.com/14913945/105898807-7fb75880-5fdf-11eb-8910-7e4a642d8c95.png)

**To Reproduce**
Unknown

**Expected behavior**
The count for transcodes and health checks should reflect actually running checks or transcodes.

**Screenshots**
Above

**Desktop (please complete the following information):**
Ubuntu 20.04 LTS

**Comment by jasonsansone** [comment]
Persist in 2.00.01 release

**Comment by HaveAGitGat** [comment]
This should be fixed when 2.00.02 is out (well, the discrepancy between the two sections will be fixed, which one was correct _may_ be another issue).

**Comment by jasonsansone** [comment]
Let me know when the preview release is out.  I will test and report back.  Thank for working to squash all these initial bugs!

**Comment by jasonsansone** [comment]
Appears to be resolved in 2.00.02.  Closing.  I will open a new ticket if there is a deeper issue going on.
