### ISSUE TITLE
V2.00.01 - Server fails to restart after first run

### ISSUE THREAD

**Issue by dhoffman98** [HaveAGitGat/Tdarr#332]
**Describe the bug**
I can install a fresh container using the 2.00.01 version, and it starts and runs with no problem.
But if I stop the container, and then start it again, it fails to run and appears to have an issue reading a database.

**To Reproduce**

1. Start with no saved configs or data... clean system.
2. Install the docker container using haveagitgat/tdarr:2.00.01.
3. Start the container.
4. Watch the logs. After it says it has downloaded and updated the plugins, the logs are quiet.
5. Check the GUI. Everything runs as expected.
6. Now stop and restart the container.
7. Watch the logs. Now you'll see a never ending cycle of the application starting, failing to connect to itself from port 8265 to 8266, and eventually throwing an error: 

> RangeError: Invalid string length
>     at log (/snapshot/tdarr_express_be/node_modules/single-line-log/index.js:28:34)
>     at createBar (/snapshot/tdarr_express_be/src/db/_jsonDB.js:25:3)
>     at Object.getAllSync (/snapshot/tdarr_express_be/src/db/_jsonDB.js:249:7)
>     at /snapshot/tdarr_express_be/src/db/crudDBBE.js:48:12
>     at Array.forEach (<anonymous>)
>     at Object.<anonymous> (/snapshot/tdarr_express_be/src/db/crudDBBE.js:44:9)
>     at Module._compile (pkg/prelude/bootstrap.js:1320:22)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
>     at Module.load (internal/modules/cjs/loader.js:1047:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:935:14)

-- Also notice that when connecting to the Web GUI, the tabs do not populate data correctly. For example, the Options tab only displays a spinning icon.

**Expected behavior**
Expected the application to start like the first time.

**Desktop (please complete the following information):**
Version 2.0.01 installed via Docker on Unraid

**Additional context**
Attaching a log file showing repeated errors, and restarts.
[tdarr_v2_logs.txt](https://github.com/HaveAGitGat/Tdarr/files/5875869/tdarr_v2_logs.txt)

**Workaround**
(Useless, but...)
After stopping the container, remove the contents of the DB2 directory. The container will then start correctly again... although it will look like a new install.

**Comment by dhoffman98** [comment]
This is unrelated to the other issue I created (329), so it should not be linked.

Note also that because the container was not available in the unraid community apps, I was controlling it through portainer after manually running the docker create. I don't know if portainer is the cause of the problems, but since it has been mentioned in other chat, I'm adding that note here as well.

**Comment by dhoffman98** [comment]
Adding comments. Seems unrelated to portainer.
Reproduced using the following steps starting from a clean server (having removed the previous container, image, and appdata).

1. Install using the docker create command line.
2. Start the container (from the Unraid GUI).
3. Connect to the UI... no problems.
4. Wait a few minutes to ensure processes are complete.
5. Stop the container (from the Unraid GUI).
6. Start the container again (from Unraid GUI).
6. Connect to the UI... now fails.
7. Stop the container (from the Unraid GUI).
8. Delete DB2.
9. Start the container (from the Unraid GUI).
10. All works as expected again.

Also tested using the following steps.... not using the GUI... all docker command line...
Again... from a clean server state.
1. Install using the docker create command line.
2. Start the container (CLI).
3. Connect to the UI... no problems.
4. Wait a few minutes to ensure processes are complete.
5. Stop the container (CLI).
6. Start the container again (CLI).
6. Connect to the UI... now fails.
7. Stop the container (CLI).
8. Delete DB2.
9. Start the container (CLI).
10. All works as expected again.


So, it doesn't seem to matter whether I use command line, Unraid GUI, or Portainer GUI.

**Comment by dhoffman98** [comment]
Workaround:
1. Use the backup tab to create a backup.
2. Stop the server.
3. Delete the DB2 folder.
4. Start the server
5. Use the backup tab and restore the previous backup.

All seems to work as if the server was never down.

**Comment by HaveAGitGat** [comment]
Thanks, haven't seen anyone else mention this error but this should be fixed in 2.00.02, will release a preview later today.

**Comment by ephekt** [comment]
Thought I would share that I had this issue, as well. On the latest docker/portainer as of writing this. I use the delete `DB*` folder method to get the server to work after restart. Ubuntu 20.xx

**Comment by dhoffman98** [comment]
I think there are too many places where people can bring up issues. Between github, discord, reddit... where else? I know on the Help channel on discord yesterday, it was mentioned by several people.

**Comment by ephekt** [comment]
> I think there are too many places where people can bring up issues. Between github, discord, reddit... where else? I know on the Help channel on discord yesterday, it was mentioned by several people.

I think we need to do a better job of guiding people to GitHub. It is a better system of record for these kinds of issues. Discord is a lovely group-texting tool but not so great for tracking the stuff like this!

**Comment by HaveAGitGat** [comment]
@dhoffman98 can you try 2.00.02 pre-release? It's on Windows and Docker, just specify the 2.00.02 tag.

**Comment by dhoffman98** [comment]
@HaveAGitGat I tried that earlier but possibly before 2.00.02 was published.
Just tried it again and was able to install.
Kind of successful... Not sure... Here are some logs.

This time I did a completely clean install using 2.00.02.
System started up just fine. I added a library, made a backup, and shut it down.
(odd... note in the logs while I was creating the library, it added another "Turning folder watch off" step for each keystroke as I was typing the path)
Here is the log after the install was completed and the library was added.
[_tdarr_v2_02_logs (7).txt](https://github.com/HaveAGitGat/Tdarr/files/5888992/_tdarr_v2_02_logs.7.txt)

Then I stopped the docker, waited a minute, and then started it again.
Lots of log errors, and in the GUI, I could not see anything on the Library or Options tabs... at first.
Then after a minute or so, it calmed down and then I could see everything.
Here is the log after the restart:
[_tdarr_v2_02_logs (8).txt](https://github.com/HaveAGitGat/Tdarr/files/5889008/_tdarr_v2_02_logs.8.txt)

**Comment by HaveAGitGat** [comment]
Those log errors are just about the WebUI not being able to contact the server. Unfortunately there's nothing saying what was holding everything up. 

Did it work fine after that?

**Comment by dhoffman98** [comment]
Yes. So far I haven't had any problems with 2.0.02 as far as the server and node ops go.
I'd say we can close this one.

**Comment by HaveAGitGat** [comment]
Ok thanks I'll close it when I move 2.00.02 into latest, just checking some other things.

**Comment by HaveAGitGat** [comment]
Moved it into 2.00.03 which is now available.
