### ISSUE TITLE
Missing directory blocking Node encoding

### ISSUE THREAD

**Issue by jasonsansone** [HaveAGitGat/Tdarr#334]
**Describe the bug**
I updated to 2.00.01.  All my nodes stopped working that worked under v2 initial release.  They were stuck at ETA Calculating.  The reason was a missing directory located at `/home/tdarr/`.  I created the directory and gave it the appropriate permissions.  That fixed the problem, and the directory remains empty with the exception of a hidden `.npm` folder.  Shouldn't this be created inside the Tdarr_Node directory?  2.00.00 did not require access to the `/home` directory.

The error is:
`Jan 27 13:24:08 tdarrv2-maverick Tdarr_Node[452]: Unhandled rejection Error: EACCES: permission denied, mkdir '/home/tdarr'`

**To Reproduce**
Upgrade from 2.00.00 to 2.00.01 and launch Tdarr_Node.  

**Expected behavior**
Expanded permissions to externally located directories shouldn't be required.

**Desktop (please complete the following information):**
Tdarr v 2.00.01 on Ubuntu 20.04.

**Comment by HaveAGitGat** [comment]
Is 'tdarr' the username on that machine?

I'm assuming it's the npm dependency as Nodes don't use 'home'.  2.00.00 didn't auto install import-fresh (used by lots of plugins), so I'm assuming that's why this error didn't appear.

**Comment by jasonsansone** [comment]
Yes, the user and group tdarr are used to launch the Tdarr systemd scripts and binary processes.

**Comment by HaveAGitGat** [comment]
Haven't had any more reports on versions since so will close.
