### ISSUE TITLE
Server Suddenly Crashes

### ISSUE THREAD

**Issue by aevans0001** [HaveAGitGat/Tdarr#337]
**Describe the bug**
Leave Tdarr running and going through my library.  After Last completed cache file has a couple of errors, server suddenly ends. Leaving everything else in limbo and waiting.  A file was actually stuck at 98%

**To Reproduce**
I have reproduced it by letting tdarr run for 8+ hours

**Expected behavior**
For it to work 72+ hours

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by HaveAGitGat** [comment]
Which OS are you using?

**Comment by HaveAGitGat** [comment]
2.00.03 just released should fix this issue. Please re-open if needed. Thanks
