### ISSUE TITLE
Failed Health Scan actions - Delete and Log, notify API to redownload

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#338]
**Describe the solution you'd like**
When errors are found during a health scan, limited actions are available as a result.  It would be great to have a delete option, to delete the unhealthy file, or a delete and log option so that you can see which files you need to recreate.  Requeue doesn't always work, or it may be an original file that can't be requeued.

Another option I can think of is to 're-download' as part of the API

Just having the delete option right now would be helpful to me, so that I don't have to log into the file system and do it manually one by one or feed a script from the log.  This would be a huge timesaver.  Thanks.

**Comment by HaveAGitGat** [comment]
2.00.14 has the option to delete unhealthy files:
![image](https://user-images.githubusercontent.com/43864057/153154586-974a9cf2-3fbf-440d-b6cd-1dcbead10223.png)

Re-downloading is a bit outside the scope of Tdarr.
