### ISSUE TITLE
V2 has excessive Disk usage while idle

### ISSUE THREAD

**Issue by mazzetta86** [HaveAGitGat/Tdarr#341]
**Describe the bug**
Tdarr V2 server writes constantly the files SettingsGlobalJSONDB and StatisticsJSONDB in DB2 and DB3 directories every second. It doesn't matter if you have any libraries configured. I have deleted my configuration and started fresh but behaves the same way.

It was also mentioned by another user:
https://github.com/HaveAGitGat/Tdarr/issues/321#issuecomment-769380973

**To Reproduce**
Start Tdarr V2 server and it will start immediately to write files every second

**Expected behaviour**
When idle I would expect minimal disk usage

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Manjaro Linux 20.2.1
 - Linux 5.10.7-3-MANJARO
 - Docker 20.10.2
 - Tdarr 2.00.03

**Additional context**
I checked the usage with fatrace: `sudo fatrace -tC Tdarr_Server`

`16:04:49.776222 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:49.776222 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2988360950
16:04:49.777643 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2988360950
16:04:49.794216 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2988360950
16:04:49.795568 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:49.799285 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:49.799285 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1020340556
16:04:49.799838 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1020340556
16:04:49.804028 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1020340556
16:04:49.805448 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:50.776186 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:50.776186 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.4292943766
16:04:50.776515 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.4292943766
16:04:50.792609 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.4292943766
16:04:50.794114 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:50.798186 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:50.798186 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.3595250936
16:04:50.798630 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.3595250936
16:04:50.805580 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.3595250936
16:04:50.807277 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:51.778356 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:51.778356 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2622055413
16:04:51.778962 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2622055413
16:04:51.795366 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2622055413
16:04:51.797082 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:51.800979 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:51.800979 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1914584685
16:04:51.801371 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1914584685
16:04:51.805898 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1914584685
16:04:51.808546 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:52.774992 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:52.774992 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1005769618
16:04:52.775379 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1005769618
16:04:52.790629 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.1005769618
16:04:52.790917 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB2/StatisticsJSONDB
16:04:52.791534 Tdarr_Server(3264370): + /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB
16:04:52.791534 Tdarr_Server(3264370): O /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2810882557
16:04:52.791595 Tdarr_Server(3264370): W /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2810882557
16:04:52.794890 Tdarr_Server(3264370): CW /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json.2810882557
16:04:52.795043 Tdarr_Server(3264370): <> /var/lib/docker/volumes/tdarr_data/_data/Tdarr/DB3/StatisticsJSONDB`

**Comment by HaveAGitGat** [comment]
Hi, thanks for opening an issue. What do you mean by excessive usage? The files being updated are 1KB in size or so:

![image](https://user-images.githubusercontent.com/43864057/106497295-24450900-64be-11eb-94a3-7b978cfd64fe.png)

This is normal behaviour for Tdarr. 10MB of writes or so per hour when idle is very low down the list on the applications I use: 
![image](https://user-images.githubusercontent.com/43864057/106497801-cc5ad200-64be-11eb-8dba-7aa1c737ce53.png)

**Comment by mazzetta86** [comment]
Good evening sir/madam,

I mean no disrespect, I really appreciate Tdarr. 10MB per hour is about 87GB per year. If the software is simply turned on, with nothing to do, nothing to scan, nothing to transcode or check, why is it constantly writing to the disk? As I mentioned before this is the behaviour you have after a clean install, with the software sitting there waiting to be used. Thank you for your support and please let me know if there is something else I can provide to facilitate this.

**Comment by bergi9** [comment]
That's the one reason why I never let tdarr run all the time. I only start the docker dontainer of tdarr when I need it. Then it will be shutdown after transcoding.

**Comment by HaveAGitGat** [comment]
I've fixed this in 2.00.14 so there's no idle disk writing.
