### ISSUE TITLE
V2 - Executables are missing the +x (executable) flags in Linux arm

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#344]
**Describe the bug**
Every time I run the updater and a new version is implemented, I have to `chmod u+x` all three executables (Server/Node/WebGUI) in order to run Tdarr:

`chmod u+x /opt/Tdarr/Tdarr_Server/Tdarr_Server /opt/Tdarr/Tdarr_Node/Tdarr_Node /opt/Tdarr/Tdarr_WebUI/Tdarr_WebUI `

**To Reproduce**
Re-download Tdarr via Updater and notice the main program files are not executable.

**Expected behavior**
Executables should have the +x flag. Not sure that's a possibility or if there are restrictions. Maybe it could even be a command at the end of the updater after the unzip?

**Desktop (please complete the following information):**
 - OS: Raspberry PI OS 32 bits Buster
 - Version: 2.00.031

**Comment by HaveAGitGat** [comment]
Thanks, added to the next release.

**Comment by HaveAGitGat** [comment]
Added to Tdarr_Updater 2.00.04 which is now up.

**Comment by wsegatto** [comment]
Thank you.
