### ISSUE TITLE
Feature request: avoid loop. place files in error/cancelled queue if they have been picked up for transcoding for too many times in a row 

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#345]
**Is your feature request related to a problem? Please describe.**
I am using scripts to add a new audio track (EAC3). However if that script failes (for some reason) to create a new audiotrack, the file will be picked up Endless; as Tdarr doesn't see a new track (EAC3) and thus starts to process the file again. Over and over.
This is causing a 24/7 stress on hardware on cpu, resources etc. As the system runs standalone and I'm not constantly supervising each transcoding.

**Describe the solution you'd like**
Would it be possible to 'count the number of times a specific file has been picked up for processing' lets lets say within 1 hour. If this is beyond x (10?) times, the file should be parkt in the 'transcode error/cancelled'' queue. This will stop the unnessesary resource utilization and allows me to periodicly check the error queu and see what is causing that issues with that specific file.
This solution would work all transcoding items that get in a 'loop'

**Describe alternatives you've considered**
Daily monitoring the log.

**Comment by HaveAGitGat** [comment]
I’ll try and add this today. I think the best method would be to check if the new command is the exact same as the last. If they are the same, and the file is the exact same, then it should throw an error.

**Comment by HaveAGitGat** [comment]
I've update the Node 2.00.04 pre-release so it will error and show something like the following if it detects a plugin loop:

```
The new transcode arguments were the exact same as the last ones meaning the file/worker would most likely be stuck in an infinite transcode loop if not stopped.

Last arguments: -Z "Very Fast 1080p30" -e nvenc_h265

New arguments: -Z "Very Fast 1080p30" -e nvenc_h265

Plugin Local 5wj2f_ZFe
```

**Comment by michpas** [comment]
I'm still a happy user of version 1.3, but with all major improvements I'll soon update to v2 and test this. 
Thanks again. Tdarr is such a helpful tool to manage large video libraries serving multiple output devices.
