### ISSUE TITLE
Enhancement - Plugin creator - add audiostream AC EAC ability to use higher bitrate

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#346]
The plugin creator allows to create a plugin with purpose to: Transcode - Add audio stream
This is very useful to create Eac3 or AC3 audiostreams for files that only have DTS as some televisions and soundbars do not process DTS.

It works great, but it encoding with 448 kb/s. AC3 can go up to 640 kb/s. Would it be possible to use the 640 kb/s or add a selection? Maybe add to drop down list:
AC 448
AC 640
EAC 448
EAC 640

I tried to modify the produced script, but don't see an option to change the plugin script as it doesnt use ffmpeg cli line

**Comment by HaveAGitGat** [comment]
Can add a bitrate input in the plugin here if still needed:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_00td_action_add_audio_stream_codec.js
