### ISSUE TITLE
Allow Server IP:Port to be specified

### ISSUE THREAD

**Issue by drowse7en** [HaveAGitGat/Tdarr#348]
**Is your feature request related to a problem? Please describe.**
The Split Tunnelling feature of NordVPN's Windows application adversely affects access to localhost.  This affects the ability of Tdarr nodes and WebUI from accessing the Tdarr server as you can only specify the listening port for Tdarr server and not the IP Address to listen on.

**Describe the solution you'd like**
Allow user to specify the IP Address for Tdarr server to listen on.

**Describe alternatives you've considered**
You can specify the IP:Port on Tdarr node and WebUI, but not Tdarr server.

**Comment by HaveAGitGat** [comment]
I've added this in for the next release:

Config:
`  "serverIP": "0.0.0.0",`

Log
` Tdarr_Server listening at http://0.0.0.0:8266`

**Comment by HaveAGitGat** [comment]
Hi sorry I've had to undo this change in 2.00.06 as it's been causing a few issues for some:

https://github.com/HaveAGitGat/Tdarr/issues/367
https://github.com/HaveAGitGat/Tdarr/issues/376

Will need to revisit the implementation. You can still use 2.00.05 if you really need this feature, thanks.
