### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by whatupcraig** [HaveAGitGat/Tdarr#349]
**Describe the bug**
None of the settings are being saved after docker restart.

**To Reproduce**
Setup a library and restart the docker. None of the settings save. 

**Expected behavior**
Is it possible to save the settings to the database?

**Screenshots**

**Desktop (please complete the following information):**
Unraid 6.9

**Comment by josh-gaby** [comment]
I was having this issue, adding an extra volume for "/app/server" to my docker startup command fixed it for me

`-v ~/.tdarr-v2/server:/app/server`

**Comment by HaveAGitGat** [comment]
@whatupcraig are you using the unraid template? It was updated a few days ago to fix this issue so the newest one should work fine. Please re-open if you still have problems, thanks.
