### ISSUE TITLE
Move / Copy files that error during transcode or healthcheck into another directory for later check / review

### ISSUE THREAD

**Issue by gjannece** [HaveAGitGat/Tdarr#350]
When transcoding a huge library of videos, it would be super helpful to make a copy of the files that fail healthchecks or transcoding to review later. Some of my videos were indeed damaged and I would like to manually check after. Maybe a button for deleting the file.

**Comment by HaveAGitGat** [comment]
There's an option to delete failed health check items in .14+:
![image](https://user-images.githubusercontent.com/43864057/156705338-7a41efaa-fdf2-405e-9d2a-b2fe1388e057.png)
