### ISSUE TITLE
Bug: Internal plugin creator to add-audiostream (EAC3 from DTS) errors out. error: invalid sample rate

### ISSUE THREAD

**Issue by michpas** [HaveAGitGat/Tdarr#352]
**Describe the bug**

I have created via the plugin creator a plugin that creates an eac3 5.1 file if missing from a dts stream and add it to the file.
This works for most files, but on this file the plug-in errors out with the following error:

File specs:
File: The.Banker.2020.1080p.BluRay.x264.DTS-HD.MA.7.1-MT.mkv
The audio stream is audio. DTS-HD Master Audio. A_DTS, 8 channels, sampling 96 kH, Bit:24, DTS-HD MA 7.1.
The file doesn't contain any other audio tracks.
The file also doesn't have any mpep/png pictures, 

Error:
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (dts (dca) -> eac3 (native))
Stream #0:1 -> #0:2 (copy)

Press [q] to stop, [?] for help
[eac3 @ 0x562c887681c0] invalid sample rate
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Expected behavior**
I would expect the internal plugin to create and add an eac3 track. It states: Invalid sample rate. Why is this? The file plays fine on a laptop with audio. But for some reason I can't use the internal plug-in to create an eac3 stream.
Thanks for your assessment.

**Comment by HaveAGitGat** [comment]
Are you able to post the full command being used (it's at the top of the error log/pop-up)?

**Comment by shir** [comment]
@michpas I had the same issue. For me, it happens on some files that have an image stream (poster or subtitle in image format). You may use plugin "Tdarr_Plugin_MC93_MigzImageRemoval" to remove images before convert audio. I usually keep this plugin disabled and if I have the error for a file, I enabled the plugin, reenqueue the file for processing and after success disable the plugin again.

**Comment by HaveAGitGat** [comment]
Thanks @shir . That plugin is now a default plugin when creating new libraries. Please reopen if needed.
