### ISSUE TITLE
Bug - Odd visual error within the node queue, stacked text at the bottom of the list

### ISSUE THREAD

**Issue by Jacob-Lasky** [HaveAGitGat/Tdarr#353]
**Describe the bug**
At the bottom of the node queue, it looks like a lot of directory-text is stacked on top of each other and two buttons are covered up.

**Screenshots**
![This is what it looks like](https://user-images.githubusercontent.com/6790237/106925495-609a8400-66cd-11eb-868c-d300ebf96678.png)

**To Reproduce**
Begin transcoding your queue and as GPU workers finish and we need CPU workers, this list begins to fill. When it is completely full I see this problem.

**Expected behavior**
I expect for the list to either continue going or for it to paginate and allow for clicking on the button. I also expect the text to not stack on itself.

**Desktop (please complete the following information):**
 - OS: UnRAID 6.8.3
 - Browser: Chrome Version 88.0.4324.104 (Official Build) (64-bit)
 - Tdarr: 2.00.03

**Comment by HaveAGitGat** [comment]
This seems to be a CSS bug when the grid reaches 1000 items or so. Not entirely sure why as the row HTML/CSS doesn't change for those items:

![image](https://user-images.githubusercontent.com/43864057/108588932-06035800-735c-11eb-8c4a-c33390890f5b.png)

**Comment by HaveAGitGat** [comment]
Added some changes which should fix this.
