### ISSUE TITLE
[Bug] When dealing with more than one subtitle stream, subs are extracted to the cache and not moved into place

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#356]
Whenever Tdarr has to extract more than one subtitle stream, it extracts these into the cache directory. When the plugin finishes extraction, the sub(s) aren't to the destination directory (i.e. where the source mkv is).
When there is only one subtitle stream, the subtitle gets extracted to the destination directory.

I've thoroughly tested this and both community plugins show this behavior:
- Tdarr_Plugin_078d_Output_embedded_subs_to_SRT_and_remove 
- Tdarr_Plugin_rr01_drpeppershaker_extract_subs_to_SRT 

I'm running the Tdarr_server and Tdarr_webui in a Docker container. I'm running nodes on docker and my laptop (amd64 Tdarr_node). All nodes run on Arch Linux and all volumes (cache and source directories) are NFS shares.

**Comment by HaveAGitGat** [comment]
This is due to the plugin being built for v1 where plugin cycles weren't all done in the cache like in v2. 

The `librarySettings` plugin argument could be used to fix this as it contains the path to the original library folder using `librarySettings.folder`. This could be used with  `librarySettings.cache` and `file.file` to determine the original file location which the subs would need to be output to.

`module.exports.plugin = function plugin(file, librarySettings, inputs) {`

Alternatively, I could pass down the original file properties to the plugin.

**Comment by tyhawk** [comment]
I'm not a developer (but a sysadmin) so I will see if I can figure this out with your pointers (if required with the help of the folks on the Discord channel).
If I can fix both plugins to make them compatible with V2, I will contribute my modifications via pull-request to the proper Github repositories.

**Comment by tyhawk** [comment]
I've tinkered with it a bit, but as stated, I'm not a JS developer and I don't know the language very well.
One of the things I tried is to copy the plugin to local and changing pre-processing to post-processing. I hoped it would extract the subs in the source directory. This makes the task fail with this error:
```
☑File doesn't contain audio tracks which are unwanted or that require tagging. Tdarr_Plugin_MC93_Migz2CleanTitle - Pre-processing ☒Plugin error! TypeError: Cannot read property 'toLowerCase' of undefined 
```
Tdarr_Plugin_MC93_Migz2CleanTitle is the next task in my library, so it is weird that the error seems to be caused by the next in line in stead of the one that actually failing.

Short story: I lack the JS knowledge to make the mentioned subtitle V2 compatible. I hope someone can resolve this issue one way or the other, because without proper subtitle extraction V2 is as good as useless to me as 99% of my media library requires subtitle handling.

**Comment by Scaredycrow** [comment]
suspect I'm seeing this bug also. Details from reddit thread here: https://www.reddit.com/r/Tdarr/comments/lk75qq/extracting_subtitles_to_srt_but_they_get_stuck_in/

What I'm working on currently is a TV stack that achieves the following (in order):

- Re-orders streams ( Migz6OrderStreams )

- Image Removal ( MigzImageRemoval )

- Clean Title Metadata ( Migz2CleanTitle )

- Clean Audio ( Migz3CleanAudio )

- Clean Subs ( Migz4CleanSubs )

- Convert 2ch Audio to AAC and Downmix from 7.1 ( Migz5ConvertAudio )

- Set Default Audio Stream ( SetDefaultAudioStream )

- Transcode non-AAC to AAC ( FFMPEG_Transcode_Specific_Audio_Stream_Codecs )

- Extract Subtitles to SRT and Remove ( drpeppershaker_extract_subs_to_SRT )

- Remux to MP4 ( Migz1Remux )

It works perfectly, however the extracted Subtitle files stay in the Transcode Cache folder and don't get put back into the Output Folder. File name like: 'TV Show - S02E03 - Chapter 11-TdarrCacheFile-dOHpIB76Q.eng.srt'

**Comment by HaveAGitGat** [comment]
I've updated both of those plugins so they should work fine when using v2.00.05. It won't work with an output folder though. Subs are output back to the library which is what the plugin was originally designed for.

A new plugin will be needed to support the output folder option.

**Comment by Scaredycrow** [comment]
Great news. I'll update and check it out.

**Comment by Scaredycrow** [comment]
Confirming this fix works for me. Updated to 2.00.05 and no other actions were necessary.

**Comment by tyhawk** [comment]
Cannot test at the moment due to issue #367, but glad to hear this is probably resolved.

Thanks for all the effort you're putting into bugswatting, @HaveAGitGat !

**Comment by tyhawk** [comment]
Now running 2.00.06 and subs seem to be handled correctly for files with 1 or more subtitles. Thanks!

**Comment by HaveAGitGat** [comment]
No further issues mentioned so will close this now. 👍

**Comment by jaycedk** [comment]
> 
> 
> I've updated both of those plugins so they should work fine when using v2.00.05. It won't work with an output folder though. Subs are output back to the library which is what the plugin was originally designed for.
> 
> A new plugin will be needed to support the output folder option.

Would love a plugin that supports output folder 😃

**Comment by datsoy** [comment]
Im having this problem for a while now, will this be updated/fix again?
