### ISSUE TITLE
Tdarr_Updater doens't exit to shell after running

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#357]
Not sure if it is a bug or intentional, but when I start Tdarr_Updater (amd64) the program runs and updates if there are any updates, but doesn't exit to shell. It keeps running. It would be nice if it would exit to shell or have a flag that would enable it to run and exit to shell.

**Comment by HaveAGitGat** [comment]
It was intentional so you could see the output when running the exe on Windows when double clicking (else it would close too quickly sometimes). I've changed this in version 2.00.04 of the updater so it will close automatically.
