### ISSUE TITLE
Tdarr_updater only updates to  2.0.0.3 in windows

### ISSUE THREAD

**Issue by ajw107** [HaveAGitGat/Tdarr#358]
**Describe the bug**
When updating  my  linux  server to the 2.0.0.4 docker I   noticed my windows node stopped working.  I  downloaded  the latest  Tdarr_updater and  ran it, but it was  convinced that 2.0.0.3 was  the latest version.  I changed  the  :latest tag to 2.0.0.4 and it then downloaded  the latest version of Tdarr_node.

**To Reproduce**
In windows download  the latest  Tdarr_updater and  run it,it is convinced 2.0.0.3 is the latest version

**Expected behavior**
Version 2.0.0.4 should be downloaded

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox and Chrome

**Comment by HaveAGitGat** [comment]
Hi please try the latest Tdarr_Updater (it doesn’t update itself as I don’t plan on changing it much more). 

http://tdarr.io/docs/

It was updated last week or so to allow downloading of packages which aren’t yet in the Tdarr package index which enables pre release packages to be used.

**Comment by ajw107** [comment]
Hi
Thanks for the quick response.  The updater I used was freshly downloaded a few  hours ago, so it was  the latest  version.

**Comment by HaveAGitGat** [comment]
Ah I think I see the misunderstanding.

2.00.04 is not in ‘latest’ yet as some things are still being checked. So using ‘latest’ will still only download 2.00.03.

**Comment by ajw107** [comment]
Ah, I didn't realise, thanks for letting me know.  I just assumed that because it had been pushed out  to  docker it was available everywhere.  Sorry about that.
