### ISSUE TITLE
[Bug] Resetting stats on a single library doesn't remove those stats from all libraries overview

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#360]
I love to keep track of my Tdarr stats, so I think the stats feature is great. I have a "test" library however, and I don't want those stats ending up in my final stats. So today, I reset the stats of that library to clean it up a bit. The stats of that library have been reset, however, I can see those stats in the "All" tab.
These are the stats of both libraries I currently have...

Test library:
```
Files | 10
Number of transcodes | 0
Space saved | 0 GB
Number of health checks | 2
```

Movies library:
```
Files | 512
Number of transcodes | 0
Space saved | 0 GB
Number of health checks | 8
```

All:
```
Files | 522
Number of transcodes | 129
Space saved | 8.848 GB
Number of health checks | 54
```

As you can see, they don't completely add up. Only the files total seems to be correct. The space saved value is from the test library prior to reset. Number of health checks also seems to be from the test library prior to the reset.

**Comment by HaveAGitGat** [comment]
I implemented this quite a while ago but I think it was done that way so the 'All' section shows all-time stats, rather than just those of the libraries.

Suppose will need to add in different sections for 'All' and 'All-time'.

**Comment by HaveAGitGat** [comment]
You can edit the stats in `server/Tdarr/DB2/StatisticsJSONDB` so probably easier to do that when you're wanting to manipulate the all-time stats.
