### ISSUE TITLE
Bug / Issue - Windows Server 2019 - Node

### ISSUE THREAD

**Issue by ironfox2151** [HaveAGitGat/Tdarr#361]
I have Tdarr installed on a Windows Server 2019 box.  I use the Node, Server and WebGUI.  Every so often ill need to restart the services, it appears the node is hanging.  Trying to cancel or make any changes in the webUI results in the node producing this error:

> Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
>     at ChildProcess.target.send (internal/child_process.js:708:16)
>     at cancelWorkerItem (D:\snapshot\tdarr_express_node\src\main.js:157:31)
>     at D:\snapshot\tdarr_express_node\src\main.js:174:3
>     at Layer.handle [as handle_request] (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\layer.js:95:5)
>     at next (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\route.js:137:13)
>     at Route.dispatch (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\route.js:112:3)
>     at Layer.handle [as handle_request] (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\layer.js:95:5)
>     at D:\snapshot\tdarr_express_node\node_modules\express\lib\router\index.js:281:22
>     at Function.process_params (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\index.js:335:12)
>     at next (D:\snapshot\tdarr_express_node\node_modules\express\lib\router\index.js:275:10)
>     at D:\snapshot\tdarr_express_node\node_modules\body-parser\lib\read.js:130:5
>     at invokeCallback (D:\snapshot\tdarr_express_node\node_modules\raw-body\index.js:224:16)
>     at done (D:\snapshot\tdarr_express_node\node_modules\raw-body\index.js:213:7)
>     at IncomingMessage.onEnd (D:\snapshot\tdarr_express_node\node_modules\raw-body\index.js:273:7)
>     at IncomingMessage.emit (events.js:315:20)
>     at endReadableNT (_stream_readable.js:1224:12) {
>   code: 'ERR_IPC_CHANNEL_CLOSED'

**Comment by HaveAGitGat** [comment]
I've removed this error in 2.00.04.

By hanging, what do you mean? The node workers are stuck on a certain percentage?

**Comment by ironfox2151** [comment]
I would appear that it would stop processing and the node would continue to request work, while not finishing its current task.  Next time it happens I can try to get a log output.

**Comment by HaveAGitGat** [comment]
Do you have other applications moving files around? Someone mentioned that if another application moves files while FFmpeg is transcoding them, FFmpeg sometimes exits without giving an error. I've only heard this from one person though. Haven't encountered it myself.

**Comment by HaveAGitGat** [comment]
This should be fixed in 07 but feel free to re-open.
