### ISSUE TITLE
V2 - Files backing up in staging section outside of library schedule

### ISSUE THREAD

**Issue by gdtms247** [HaveAGitGat/Tdarr#363]
**Describe the bug**
Appears that GPU/CPU transcode process is checking file, determining it requires CPU and placing it in staging section with status "Require CPU Worker"

**To Reproduce**
Multiple files added to library, node set with 1 CPU and 1 GPU worker. Library stack plugin is some CPU only process GPU can't handle

**Expected behavior**
Items should remain in the "transcode queue" until being processes so library schedule can have affect

**Screenshots**
![Screen Shot 2021-02-10 at 8 40 35 AM](https://user-images.githubusercontent.com/31072325/107525340-61736000-6b7c-11eb-9a65-d505e4f9c87f.png)

**Desktop (please complete the following information):**
Docker server and node running version 2.00.04

**Comment by HaveAGitGat** [comment]
As discussed, the node schedule should prevent this. Also 2.00.06 has option to limit the staged file section which prevents that section from becoming too long:

![image](https://user-images.githubusercontent.com/43864057/108630966-e0fc0b80-7467-11eb-828d-5be0f023c270.png)
