### ISSUE TITLE
Issue in tdarr_server docker container when using plugins with fs-extra

### ISSUE THREAD

**Issue by CplPwnies** [HaveAGitGat/Tdarr#365]
**Describe the bug**
When using plugins that require the **fs-extra** module, the plugin fails with an error because it cannot find the plugins: **universalify, graceful-fs, jsonfile**

**To Reproduce**
Use any community plugin (or local plugin in my case), that requires module **fs-extra**

**Expected behavior**
The plugin to not fail due to dependencies

**Screenshots**

**Desktop (please complete the following information):**
OS: Docker container / Debian

**Additional context**
I have a plugin that does some file renaming and requires the fs-extra module.
With Tdarr v2, I have added this to my plugin js file:
```
module.exports.dependencies = [
  'fs-extra',
];
```
But the plugin fails with the following error in the console:

>  Error: Cannot find module 'universalify'
> Require stack:
> - /app/Tdarr_Server/node_modules/fs-extra/lib/fs/index.js
> - /app/Tdarr_Server/node_modules/fs-extra/lib/index.js
> - /app/server/Tdarr/Plugins/Local/Tdarr_Local_Plugin_Rename.js
> - /snapshot/tdarr_express_be/src/api/nodeRelay/runPostProcPlugins.js
> - /snapshot/tdarr_express_be/src/api/nodeRelay/cacheCopyService.js
> - /snapshot/tdarr_express_be/src/api/nodeRelay/nodeRelay.js
> - /snapshot/tdarr_express_be/src/api/mainApi.js
> - /snapshot/tdarr_express_be/src/main.js
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

I have this code that looks for the root module path:
```
if(fs.existsSync(path.join(process.cwd(), '/node_modules'))) {
            var rootModules = path.join(process.cwd(), '/node_modules/');
        } else {
            var rootModules = '';
        }
var fsextra = require(rootModules + "fs-extra");
```

So I get into the docker container and copy the **universalify** module from `/app/server/Tdarr/Plugins/node_modules/` to 
`/app/Tdarr_Server/node_modules` and then `chown -R Tdarr:Tdarr` that directory.

After I do that, I get a similar error, but for **graceful-fs** this time, so I also copy and chown that folder as well. Then I stop and start the docker container.

After that is done, I get a similar error for **jsonfile**, so I copy and chown again

After all this, my plugin is working again. So there is definitely something up with the the plugin paths in the tdarr_server docker container.

I am using `tdarr_server:latest`

**Comment by HaveAGitGat** [comment]
I think the fs-extra install process might have been interrupted meaning the other modules weren't installed properly. I think the quick fix is to delete the `Tdarr_Server/assets/app/plugins/node_modules` folder and rerun. Tdarr just checks if 'fs-extra' exists so if the other modules haven't properly downloaded (there could be hundreds depending on the dependency) then errors will come up.

**Comment by CplPwnies** [comment]
I started an interactive terminal for the docker container to check for this directory and it does not exist.

**Comment by CplPwnies** [comment]
Closing this issue as it seems to be fixed in the latest container update.
