### ISSUE TITLE
GPU health check workers assume nvidia hardware on vaapi nodes.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#366]
**Describe the bug**
GPU accelerated health checking assumes Nvidia hardware is used. This causes thorough health checks to fail on vaapi nodes if GPU health check workers are enabled.

**To Reproduce**

Set health check type to 'thorough'
Enable GPU healthcheck worker on vaapi node.
Queue file for health checking.

**Expected behavior**
Node should do the check with appropriate hardware acceleration when using GPU health check worker.

**Screenshots**
Health check worker error output on vaapi node:
```
NodeID: odyssey
Command:
ffmpeg -stats -v error -hwaccel nvdec -i /mount/test/charlie.mkv -f null -max_muxing_queue_size 9999 /home/Tdarr/cache/charlie-TdarrCacheFile-PphxCeHeq.mp4
Last 200 lines of CLI log:
[AVHWDeviceContext @ 0x55ce74fd2f40] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x55ce74fd2f40] Could not dynamically load CUDA
Device creation failed: -1313558101.
[hevc @ 0x55ce74fd30c0] No device available for decoder: device type cuda needed for codec hevc.
Device setup failed for decoder on input stream #0:0 : Unknown error occurred
```

**Desktop (please complete the following information):**
v2.00.05 on docker.

**Additional context**
CPU thorough health checks work OK.
Changing the command line as below on vaapi workers functions correctly:

``ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -stats -v error -i /mnt/media/video/test/kilo.mkv -f null -max_muxing_queue_size 9999 /mnt/process/transcode/tdarr/kilo-TdarrCacheFile--sbuIPLVx.mp4``

Output:
``frame= 1602 fps=218 q=-0.0 Lsize=N/A time=00:01:07.76 bitrate=N/A speed=9.21x``

**Comment by HaveAGitGat** [comment]
Not too familiar with VAAPI, are these always the same across systems?

`-hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128`

**Comment by caiusseverus** [comment]
Yes, except the last one can change depending on how many gpus are in the system. With a single gpu ``/dev/dri/renderD128`` is normal, but if there is a second gpu there might be more than one render device eg ``/dev/dri/renderD129`` as well if there’s an igpu and a discrete card. 

In docker these have to be passed to the container, so what appears at that location depends on what mapping you use. Most vaapi plugins assume D128 which will work in most cases.

**Comment by caiusseverus** [comment]
Just tested this on 2.00.06 and it's working great.
