### ISSUE TITLE
Enhancement - Hardlinks / Atomic moves option for final copy from transcode cache to library

### ISSUE THREAD

**Issue by Scaredycrow** [HaveAGitGat/Tdarr#368]
**Is your feature request related to a problem? Please describe.**
Final copying from cache to library takes time and is taxing on the network 

**Describe the solution you'd like**
The option to enable hardlinks rather than a full copy process (similar perhaps to sonarr / radarr) that would enable low effort relocation of files when the transcode cache and library are on the same filesystem. In my case the transcode cache and library are indeed on the same filesystem. 

**Describe alternatives you've considered**
None. 

**Additional context**
![image](https://user-images.githubusercontent.com/26639308/108176562-4beecf00-7156-11eb-9ba1-327bcc4728c2.png)

**Comment by HaveAGitGat** [comment]
I've added this to 07 in the dev container. It will try to move/rename and fall back to copy/delete if there's an error.

https://hub.docker.com/layers/haveagitgat/tdarr/dev/images/sha256-7880fc10984059193b26d6e81fe759100da6ec0d7ebfc4810ca25b2ea31c4bf1?context=explore

**Comment by HaveAGitGat** [comment]
This is in 2.00.07/latest as of yesterday. Added a note on it in the info box:
![image](https://user-images.githubusercontent.com/43864057/110433685-13854580-80b1-11eb-96aa-d290f1783e0c.png)
