### ISSUE TITLE
Tdarr_Node displays "Node registered" every 4 seconds and never stabalizes

### ISSUE THREAD

**Issue by berserktron3k** [HaveAGitGat/Tdarr#369]
**Describe the bug**
Tdarr_Node displays "Node registered" every 4 seconds and never stabalizes

**To Reproduce**
Built a separate Ubuntu 20.04 server instance to run health checks via CPU, however the node keeps registering over and over so I can never configure it from the WebUI.

**Expected behavior**
Node registers successfully and is configurable.

**Screenshots**
![image](https://user-images.githubusercontent.com/20486420/108408772-121bd800-71eb-11eb-9616-6e730f119a6a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Browser: NA
 - Version: V2

**Additional context**

**Comment by DJBenson** [comment]
I'm getting the same, server hosted in Docker on a Synology NAS, node on my MacBook Pro (also tried other machines with the same outcome).

![image](https://user-images.githubusercontent.com/1013909/108415099-f9301880-7224-11eb-9b0f-3fe1444e68c0.png)

**Comment by St0rm3rt** [comment]
Same issue here.
When I install 2nd node with full machine IPs no 2nd node shows up in WebUI:
{
"nodeID": "Tdarr_imac",
"nodeIP": "192.168.178.34",
"nodePort": "8267",
"serverIP": "192.168.178.29",
"serverPort": "8266",
"handbrakePath": "",
"ffmpegPath": "",
"mkvpropeditPath": "",
"pathTranslators": [
{
"server": "",
"node": ""
}
]
}
However when I install 2nd node with 0.0.0.0 for nodeIP I get the 4sec registration of the 2nd node in the WebUI:
{
"nodeID": "Tdarr_imac",
"nodeIP": "0.0.0.0",
"nodePort": "8267",
"serverIP": "192.168.178.29",
"serverPort": "8266",
"handbrakePath": "",
"ffmpegPath": "",
"mkvpropeditPath": "",
"pathTranslators": [
{
"server": "",
"node": ""
}
]
}

**Comment by HaveAGitGat** [comment]
`Please make sure the IP and Port are correct else it may be a firewall issue.`

When a Node repeatedly registers it normally means it's a firewall issue. The Node can contact the server but the server can't contact the Node so you need to check the outbound firewall rules on the server or the inbound rules on the Node.

**Comment by HaveAGitGat** [comment]
Using a phone to ping the server and node IP/Ports can help narrow down the issue to see which is blocked.

iNetTools on iOS is useful for this:
![CE0B679A-9875-44C4-B940-789C40B4C7A7](https://user-images.githubusercontent.com/43864057/108539561-72d90c80-72e0-11eb-8b3c-24b6df114b36.jpeg)

**Comment by DJBenson** [comment]
I’m fairly confident it’s not a firewall issue. The host is a Synology NAS, the firewall is disabled. The node is a MacBook Pro, again firewall disabled. Other nodes behaved the same.

Port scan shows the server port is open;
![B9363475-4FD4-4B80-8AC3-62FE78A3E197](https://user-images.githubusercontent.com/1013909/108541136-03f8b500-72da-11eb-9e8d-b70aec3bc366.jpeg)

**Comment by HaveAGitGat** [comment]
@DJBenson  @St0rm3rt is having the same issue with a Mac node so I can only assume there’s something else aside from the firewall which is stopping traffic going through the ports on the node.

**Comment by DJBenson** [comment]
@HaveAGitGat same issue experienced on Debian Buster on a Raspberry Pi 4.

**Comment by DJBenson** [comment]
In my case, it was because the Node IP hadn't been updated from 0.0.0.0 - my bad.

**Comment by St0rm3rt** [comment]
I got my issue solved thanks to reddit post in Docker. See my Docker run command below that I initially used based on instructions on https://tdarr.io/docs/installation under Docker paragraph for ‘tdarr_node’ container. After removing the “—network host” line and adding “-p 8267:8267 \” in the Docker run command used on my iMac, the 2nd node got registered properly and now shows up in the Tdarr WebUI.

Not sure, but maybe the Docker run command for the ‘tdarr_node’ container on tdarr.io instructions only applies for the node when installed on the same machine as ‘tdarr’ container?

docker run -ti
-v "/Volumes/Multimedia/TV Shows:/Media/TVShows"
-v /Volumes/Multimedia/transcode_cache:/temp
-e "nodeID=TdarrNode_imac"
-e "nodeIP=192.168.178.34"
-e "nodePort=8267"
-e "serverIP=192.168.178.29"
-e "serverPort=8266"
**--network host**
-e "TZ=Europe/Amsterdam"
-e PUID=1000
-e PGID=1000
--log-opt max-size=10m
--log-opt max-file=5
haveagitgat/tdarr_node

**Comment by HaveAGitGat** [comment]
@St0rm3rt thanks. A single slash is an escape character. You need to use double backslashes

I've updated the commands to use the following instead of `--network host`:

```
                --network bridge \
                -p 8265:8265 \
                -p 8266:8266 \
```


@DJBenson glad you found the issue.

Re-open if needed.
