### ISSUE TITLE
Per-library stat breakdown

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#37]

**Comment by Torqu3Wr3nch** [comment]
Let me know if you would like this as a separate enhancement request, but it would also be nice to have the "space saved" stat included in this and have it reset when the library is cleared. Right now the "space saved" stat is cumulative and never resets even though the files that it "saved space in" are long-gone.

**Comment by marshalleq** [comment]
I'm liking the fact it doesn't reset right now.  It's the only thing that isn't resetting - so to that end I like that I can see what I've achieved.  I would not like it to reset as well.

**Comment by HaveAGitGat** [comment]
@Torqu3Wr3nch the main stat table is meant to be historical/cumulative/all-time and is not meant to reduce/reset when libraries are cleared or files are removed.

I've added per-library stat breakdown. All time-time stats won't be affected but per library stats will start from scratch in 1.006 as it's a new data point. On each library there is an option to reset that libraries stats or reset all stats.
