### ISSUE TITLE
"Exec format error" on Mac Mini M1

### ISSUE THREAD

**Issue by CarlosHartmann** [HaveAGitGat/Tdarr#370]
**Describe the bug**
I downloaded the Unix Arm Tdarr_Updater and cannot execute it. I receive the error message `zsh: exec format error: ./Tdarr_Updater`

**To Reproduce**

- cd into the directory of Tdarr_Updater file
- chmod +x Tdarr_Updater
- enter `./Tdarr_Updater` or simply `Tdarr_Updater`

**Expected behavior**
According to the tutorial, it should have downloaded 4 modules.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.1
 - Hardware: Mac Mini 2020 with M1 chip
 - Version: Tdarr V2

**Additional context**
HaveAGitGat did promise it would work on M1 Macs. If it doesn't I still have another Arm machine but would prefer my Mac to be the main server for Tdarr.

I have also tried the other updater for Unix and had the exact same error message.

**Comment by EpicKris** [comment]
Which `Tdarr_Updater` did you download?

**Comment by clunkclunk** [comment]
You should use Tdarr_Updater darwin_x64 rather than Tdarr_Updater linux_arm.

Darwin is the macOS kernel - hence the name, and while it's x64, the ffmpeg it includes is compiled for Apple Silicon / M1.

**Comment by CarlosHartmann** [comment]
> Darwin is the macOS kernel - hence the name, and while it's x64, the ffmpeg it includes is compiled for Apple Silicon / M1.

I didn't know about Darwin yet, lots to learn. That of course solved it.
