### ISSUE TITLE
Using a second GPU for Tdarr

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#371]
I have Patreon but I figured this was was easier since I don't check that website.

I have an AMD GPU which obviously doesn't have NVENC, and thus all the Tdarr stuff happens to my CPU. I am wondering if I get a Geforce 2060, would I be able to use my AMD card as my daily driver for my monitor etc, but then the GeForce card gets exclusively used by Tdarr?

I'm on Windows 10 pro

**Comment by HaveAGitGat** [comment]
Yes you can do that. You can set the hardware encoder for each Node in the Node Options. You'd just need to set it as nvenc:

![image](https://user-images.githubusercontent.com/43864057/108588724-f3d4ea00-735a-11eb-996e-ba52d8b9ac4a.png)


Bear in mind you can use your AMD card to do hardware transcoding as FFmpeg includes encoders for that:

![image](https://user-images.githubusercontent.com/43864057/108588786-4d3d1900-735b-11eb-8cd1-c505b24e3229.png)

**Comment by HaveAGitGat** [comment]
Re-open if needed, thanks.
