### ISSUE TITLE
Tdarr ALERT: NO OUTPUT FILE PRODUCED/tmp/Hacker's Game - Redux (2018)-TdarrCacheFile-YuX8k7x8o.mp4

### ISSUE THREAD

**Issue by spikemixture** [HaveAGitGat/Tdarr#372]
2 things I am assuming are connected

[WARN] Tdarr_Node - Binary test 3: mkvpropeditPath not working:

And the Title above.

Running V2.00.03 in Docker on a Qnap NAS

**Comment by HaveAGitGat** [comment]
`[WARN] Tdarr_Node - Binary test 3: mkvpropeditPath not working`

You can ignore this. It's just a warning.

Best to post the full logs and your configs for the `NO OUTPUT FILE PRODUCED` issue. It's very generic.

**Comment by spikemixture** [comment]
Ok . Where exactly are the logs kept in docker. 
I am searching for /app/server/Tdarr/Logs

**Comment by HaveAGitGat** [comment]
Should be in `/app/logs`

![image](https://user-images.githubusercontent.com/43864057/108630338-81e8c780-7464-11eb-8085-27056290e834.png)

http://tdarr.io/docs/

**Comment by HaveAGitGat** [comment]
I'm assuming this is because the server and node don't have access to the same library and cache folders.

`Make sure the Node and Server machines have the same media library and transcode cache locations. In other words, the cache and library must be shared between the Node and Server.`

**Comment by spikemixture** [comment]
Thanks HGG But where is "Should be in /app/logs"
I am using docker on a Qnap NAS. 

Appears to be working now as removed and remade the 2 plugins I use for remux and recoding movies.

**Comment by HaveAGitGat** [comment]
` /app/logs` is the absolute path inside the container.

Glad it's working now :).

**Comment by ovizii** [comment]
> `[WARN] Tdarr_Node - Binary test 3: mkvpropeditPath not working`
> 
> You can ignore this. It's just a warning.
> 
> Best to post the full logs and your configs for the `NO OUTPUT FILE PRODUCED` issue. It's very generic.

that is weird, your comment shows it as WARN while in a current tdarr version its actually ERROR

```
cat logs/Tdarr_Node_Log.txt |grep -i error |more
[2022-01-29T14:10:52.335] [ERROR] Tdarr_Node - Binary test 3: mkvpropeditPath not working

```
server and node do share the exact same volume mappings. Can we still ignore this ERROR?

**Comment by typicalGtaTG** [comment]
I'm facing the same issue, I'm not sure what's wrong either. I already checked the paths.

**Comment by ellismichaelc** [comment]
For those on OSX who are looking to resolve the "mkvpropeditPath" warning. Follow these steps.

1. Download and install MKVToolNix: https://mkvtoolnix.download/macos/
2. Edit your config file like so: 

> "mkvpropeditPath": "/Applications/MKVToolNix-75.0.0.app/Contents/MacOS/mkvpropedit",

**Comment by sfatula** [comment]
For installing mkvpropedit on MacOS, if you are using brew:

brew install mkvtoolnix

and then set the path to /opt/homebrew/bin/mkvpropedit. This avoids needing to download the Intel version of mkvtoolnix from their site, and, avoids having version issues if you actually use it and update it now and then since the path would change based on the version number.
