### ISSUE TITLE
Error code 'EACCES' on M1 Mac

### ISSUE THREAD

**Issue by CarlosHartmann** [HaveAGitGat/Tdarr#373]
**Describe the bug**
Tdarr finds a new file when it's added but does not initiate transcoding. In the Terminal, it throws this error:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/Carlitos/tdarr/Tdarr_Server/node_modules/ffprobe-static/bin/darwin/x64/ffprobe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Carlitos/tdarr/Tdarr_Server/node_modules/ffprobe-static/bin/darwin/x64/ffprobe',
  path: '/Users/Carlitos/tdarr/Tdarr_Server/node_modules/ffprobe-static/bin/darwin/x64/ffprobe',
  spawnargs: [
    '-show_streams',
    '-print_format',
    'json',
    '/Users/Carlitos/Movies/transcoding/in/Lola (1981).mkv'
  ]
}
```

**To Reproduce**
I have caused this by activating folder watch and inserting the file into my source dir and manual scan commands do the same.

**Desktop (please complete the following information):**
- Machine: M1 Mac
 - OS: Big Sur 11.1

**Additional context**
The used plugin is supposed to use HandBrake. The plugin is correctly modified and marked enabled.

**Comment by HaveAGitGat** [comment]
In a terminal run:

`chmod +x /Users/Carlitos/tdarr/Tdarr_Server/node_modules/ffprobe-static/bin/darwin/x64/ffprobe`

Should fix the issue. The binary needs execution permissions.

**Comment by HaveAGitGat** [comment]
Made some changes for 2.00.06 so this should be done automatically in future.

**Comment by HaveAGitGat** [comment]
Re-open if needed. Thanks.
