### ISSUE TITLE
intel 10th gen iHD intel driver

### ISSUE THREAD

**Issue by marine1988** [HaveAGitGat/Tdarr#375]
**Describe the bug**
I have the new i7 10500u and tried to use hw transcoding with no luck becaus de image doesnt have intel iHD drivers

**To Reproduce**
Use hw deconding

**Expected behavior**
Is suppose to use new iHD intel drivers

**Screenshots**
![image](https://user-images.githubusercontent.com/6524068/108649920-39f29080-74b6-11eb-8a99-42386171fdfd.png)
![image](https://user-images.githubusercontent.com/6524068/108649978-58f12280-74b6-11eb-862e-5614aa04ef71.png)

**Desktop (please complete the following information):**
 - OS: debian
 - Version docker image haveagitgat/tdarr:2.00.05

**Comment by HaveAGitGat** [comment]
Should be fixed for 07, currently in dev containers:
https://github.com/HaveAGitGat/Tdarr/issues/397

**Comment by stokkes** [comment]
Hey @HaveAGitGat this won't always work, I think different versions of the 10th Gen Intel use different drivers.

Even on the :dev branch, I had to install `va-driver-all` or `vainfo` would throw an error.
