### ISSUE TITLE
Copying files before processing

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#377]
**Describe the bug**
When files are being moved into staging, they get added to cache. However, I end up with a lot queued requiring CPU etc, and this fills my disk.

**Expected behavior**
Cache file should only be created once it's started processing.

**Please provide the following information:**
OS: Linux
Browser: Chrome
Version: 2.00.03

**Comment by HaveAGitGat** [comment]
Tdarr doesn't copy files from the library to the cache, it transcodes/remuxes directly from library to cache for the first plugin pass. So any files in the cache are files which have already been processed and are awaiting further processing.

2.00.06 has several changes which will help limit the staging section, more info here:
https://www.reddit.com/r/Tdarr/comments/lp0n40/transcode_cache_over_600gb/go8qp06?utm_source=share&utm_medium=web2x&context=3

2.00.06 is now available if you set it manually, will be moved into 'latest' once this fix is confirmed:
https://github.com/HaveAGitGat/Tdarr/issues/367
