### ISSUE TITLE
[Enhancement] improved error reports

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#378]
Here is an example of a failed job:
```
☑File doesn't contain subtitle tracks which are unwanted or that require tagging. ☒Plugin error! TypeError: Cannot read property 'details' of undefined 
```
The first part (prefixed with ☑) is a report of a previous step. The actual plugin error "TypeError: Cannot read property 'details' of undefined" comes for a different plugin than the first message. Although the first message is a clue to what plugin is the step before the one throwing the error, it would be very helpful to have the name of the plugin that failed in the error message somewhere.

**Comment by ConfusedTA** [comment]
I'm having the exact same error, and having more details on the errors would certainly help! Following this one as I'm directly affected.

**Comment by HaveAGitGat** [comment]
This was added in 07 so the plugin ID will be shown if there's an error:

![image](https://user-images.githubusercontent.com/43864057/111022743-ff08bc00-83d4-11eb-8710-9aa2d6913752.png)

**Comment by tyhawk** [comment]
Awesome! Thanks!
