### ISSUE TITLE
[Enhancement] Improve Nvidia GPU health check speed considerably.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#379]
After the implementation of vaapi gpu health checks, I was curious why the nvidia node with a GTX 1060 was slower running the health checks than the node with a celeron iGPU.

The current command line used for nvidia GPU nodes doing thorough health checks is:
``-stats -v error -hwaccel nvdec , -f null -max_muxing_queue_size 9999``

This does not make optimal use of the decoder, because I think it copies the decoded frames back to system memory, which bottlenecks it. System monitor showed the Video Decoder using only ~35% of capacity with high CPU usage. Since there is no further processing being done to the frames, there is no need to do this. Instead the frames should be kept in GPU memory using the hwaccel_output_format switch.

A comparison of speed on a 4k hevc test file:

Software only (4th gen i5):
frame= 1602 fps= 54 q=-0.0 Lsize=N/A time=00:01:07.76 bitrate=N/A speed= 2.3x

nvdec as currently implemented:
frame= 1602 fps= 81 q=-0.0 Lsize=N/A time=00:01:07.76 bitrate=N/A speed=3.45x [1.5x faster than software]

nvdec with -hwaccel_output_format switch set:
frame= 1602 fps=221 q=-0.0 Lsize=N/A time=00:01:07.76 bitrate=N/A speed=9.37x [4.1x faster than software]

The last example uses 100% of decoder capacity and is 2.7x faster than the current version with much lower cpu overhead.

The amended command line should be:
``-stats -v error -hwaccel nvdec -hwaccel_output_format cuda , -f null -max_muxing_queue_size 9999``

**Comment by HaveAGitGat** [comment]
Thanks, I added this to 2.00.06 which moved to ‘latest’ earlier today. You should be able to see it in the change log.
