### ISSUE TITLE
GUI not present on Safari 2.00.06

### ISSUE THREAD

**Issue by rasorjb** [HaveAGitGat/Tdarr#380]
**Describe the bug**
GUI is not present on Safari browser (iOS or MacOS)

**To Reproduce**
Attempt to bring up TDARR on Safari Browser

**Expected behavior**
TDARR GUI would be present

**Screenshots**
Safari
<img width="1315" alt="Screen Shot 2021-02-23 at 11 38 51 AM" src="https://user-images.githubusercontent.com/35665609/108876095-d9ee0e00-75cb-11eb-8cf5-c834816bb6b6.png">

Chrome on Same System
<img width="1188" alt="Screen Shot 2021-02-23 at 11 38 59 AM" src="https://user-images.githubusercontent.com/35665609/108876125-e3777600-75cb-11eb-926d-fdf4ecea3e45.png">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Can't find this file in my Docker Setup (using DockStarter)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[log.txt](https://github.com/HaveAGitGat/Tdarr/files/6030446/log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: MacOS 11.2.1 / iOS 14.4
 - Browser: Safari 14.03 / Safari iOS

**Additional context**
Works without issue on any other browser.

**Comment by jasonsansone** [comment]
I replicated and can confirm the bug.  

![Screen Shot 2021-02-23 at 11 13 43 AM](https://user-images.githubusercontent.com/14913945/108880755-35b69800-75c8-11eb-88b2-081a4d163105.png)

**Comment by HaveAGitGat** [comment]
Tried Chrome, Firefox, Opera and Edge and all is working well so not sure why Safari is doing this. I don’t have a Mac either which makes investigating it difficult. Was it the same for 2.00.05?

**Comment by jasonsansone** [comment]
I went from 2.00.04 to 2.00.06, so I can't say.  FYI - it is relatively easy to run macOS in a VM on Proxmox, ESXi, virtualbox, or vmWare Workstation.

**Comment by caiusseverus** [comment]
> Was it the same for 2.00.05?

I have this issue on ipad on Safari (and Chrome, but that's basically just a skin of safari anyway).  The UI worked OK on 2.00.05 and earlier versions.

**Comment by rasorjb** [comment]
> > Was it the same for 2.00.05?
> 
> I have this issue on ipad with Safari (and Chrome, but that's basically just a skin of safari anyway). The UI worked OK on 2.00.05 and earlier versions.

Nope worked perfect in the last version.

**Comment by rasorjb** [comment]
> Tried Chrome, Firefox, Opera and Edge and all is working well so not sure why Safari is doing this. I don’t have a Mac either which makes investigating it difficult. Was it the same for 2.00.05?

Worked perfect in 2.00.05 for both iOS and MacOS.

**Comment by marshalleq** [comment]
Adding a me to on this.

**Comment by HaveAGitGat** [comment]
Thanks, I've found the issue (upath dependency). Fix will be in 2.00.07 and is in the dev container now:
https://hub.docker.com/layers/haveagitgat/tdarr/dev/images/sha256-f8b0c96aae0d96639799168d705d45d8aa05756f8280aa6eaf900238f7eefcdb?context=explore

**Comment by HaveAGitGat** [comment]
This fix was released yesterday (2.00.07) so should be working fine now.

**Comment by shir** [comment]
@HaveAGitGat It works. Thank you!
