### ISSUE TITLE
Info [i] and History [H] buttons on the Transcode Success/Not Required list do not show information

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#381]
This is on the "Transcode Success/Not Required" list.  When clicking the [i] button, only the output from the last plugin is shown.  All plugins output should be shown.  When clicking the [H] button, no information is shown at all.

 - OS: Debian Buster (non-Docker)
 - Browser Firefox
 - Version 2.00.06

**Comment by gavzey** [comment]
I can confirm this behaviour exists using Version 2.00.06 in Docker (on Centos 8) using the 1st party image.

**Comment by HaveAGitGat** [comment]
This has been added in for 08. A side by side comparison of original and new file will be shown when clicking the History button.

![image](https://user-images.githubusercontent.com/43864057/111022817-881ff300-83d5-11eb-8fdf-efa9aa02e6a7.png)
