### ISSUE TITLE
Info [i] button on Node Transcoding item only shows current plugin output

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#382]
The [i] button next to a transcoding item in the Node list only shows the current plugin output.  It should show all previous plugin output up to that point as well.

 - OS: Debian Buster (non-Docker)
 - Browser Firefox
 - Version 2.00.06

**Comment by HaveAGitGat** [comment]
I've fixed this for 09 and made it a bit easier to read:

![image](https://user-images.githubusercontent.com/43864057/114294131-9af11a80-9a9c-11eb-921a-481d6042d371.png)

**Comment by HaveAGitGat** [comment]
09 released
