### ISSUE TITLE
[Enhancement] Add the ability to collapse sections

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#383]
I would like the ability to collapse/hide each section of the main transcoding UI: Server Overview, Nodes, Staging, Status, Status Filters/Config.  Mainly, I want to be able to see the transcoding progress of a node at the same time as the Transcode Queue.  Right now there is too much vertical space for those to both be visible at once.

**Comment by HaveAGitGat** [comment]
This has been added for 07:

![image](https://user-images.githubusercontent.com/43864057/110232499-4c40e580-7f1e-11eb-843d-297788791594.png)

**Comment by slim186** [comment]
Looks great! Any way you could collapse from "Ignore schedules" to "Items" as well?  So that the Status section would have the queued/completed lists directly under the section title.

**Comment by HaveAGitGat** [comment]
Added that in, it's in 2.00.07/latest.

![image](https://user-images.githubusercontent.com/43864057/110433423-b5586280-80b0-11eb-8e33-ed968d8309d8.png)

**Comment by slim186** [comment]
Not working for me.  I have Server on Debian and a Windows 10 node.  Setting Low Priority on the Windows node does nothing, it still runs as "Normal" priority.
