### ISSUE TITLE
[Enhancement] Add a combined transcode progress list

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#384]
I would like to have one list that shows all transcoding progress across all nodes, instead of having to click back and forth between nodes.  Similar to the stats section that has an All view as well as each library.

**Comment by HaveAGitGat** [comment]
I've added this for 09 with a combined FPS for all nodes too:

![image](https://user-images.githubusercontent.com/43864057/114140710-f098bc00-9910-11eb-8f15-ac6435db575c.png)
