### ISSUE TITLE
Low CPU Priority is missing

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#385]
There is no way to set CPU priority in V2.  Ideally there would be a setting in UI or config that would specify the CPU priority level for each module, particularly for Windows.

 - OS: Debian Buster (non-Docker), Windows 10
 - Browser Firefox
 - Version 2.00.06

**Comment by slim186** [comment]
I have worked around this on my Debian system by setting Nice values in the systemd scripts, but there isn't a good way of doing the same in Windows.  I need to manually go into the Task Manager every time I start Tdarr and set the priority.  This becomes cumbersome after a node has started processing as there are multiple processes running.

**Comment by HaveAGitGat** [comment]
I've add this in for 2.00.07 although it doesn't have any effect if running a node in a Docker container:
![image](https://user-images.githubusercontent.com/43864057/109924496-a7759c80-7cc0-11eb-9bd0-6b87ffe8b2a2.png)

**Comment by HaveAGitGat** [comment]
This is in 2.00.07/latest (as of yesterday).

**Comment by slim186** [comment]
Not working for me. I have Server on Debian and a Windows 10 node. Setting Low Priority on the Windows node does nothing, it still runs as "Normal" priority.

**Comment by slim186** [comment]
@HaveAGitGat still an issue on Windows, not using docker, 2.00.09
