### ISSUE TITLE
Transcodes stuck in staging

### ISSUE THREAD

**Issue by shanehughes1990** [HaveAGitGat/Tdarr#388]
**Describe the bug**
I have no idea if its actually a bug or not, but I am using tdarr v2 everything works great, but I do have a very large list of files stuck in processing in the staging section, when you click the info button a blank windows pops up, If I requeue them they go through the process and end up stuck at the staging section again, now out of a 10k video library I have about 100ish that are stuck, but would like to know why/how to fix it.

**To Reproduce**
For me it was just let it run its course and by the end of it transcoding my library I have those stuck in staging queue

**Expected behavior**
I assume the expected behavior would be for them to finish processing and complete

**Screenshots**
![image](https://user-images.githubusercontent.com/31993465/109391764-c225cb00-78e6-11eb-9f48-05be57274a0c.png)
![image](https://user-images.githubusercontent.com/31993465/109391767-c520bb80-78e6-11eb-9e19-4df3effb52a6.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
```
root@76ea39d56603:/# cat /app/configs/Tdarr_Server_Config.json 
{
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```

```
root@76ea39d56603:/# cat /app/configs/Tdarr_WebUI_Config.json 
{
  "webUIPort": "8265",
  "serverIP": "10.5.0.253",
  "serverPort": "8266"
}
```
- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

The only log file I have is the Tdarr_Server_log.txt https://gist.github.com/shanehughes1990/5d57b223d3863fd563e1de822b26ed4b

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

The staging items when you press the 'i' it brings up a blank grey screen

 - OS: [e.g. Linux] Docker Host

 ubuntu 20

 Chrome
 - Version [e.g. 2.00.00]

2.00.03

**Additional context**
FWI I am using your "official" tdar v2 docker container

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue. Are you able to enable verbose logs on the `Logs` tab, run one of those files through Tdarr and then post the `Tdarr_Node_Log.txt`, it should be in /app/logs in the tdarr_node container.

Thanks

**Comment by shanehughes1990** [comment]
Yup I can likely do that tonight. I will post the results

**Comment by shanehughes1990** [comment]
I've got a new library with one of the shows that was stuck, I only have the transcode to h264 plugin enabled on that, verbose logging is not enabled, fresh log file for this test only. once it's done its business I will give you the entire log and we can go from there. I really have high hopes for this app, you have done an awesome job so far. I REALLY want this to work as I would like to standardize my library autonomously.

**Comment by shanehughes1990** [comment]
Of course I let it run its course on a smaller library less plugins and it works just fine. I will try and replicate the issue and post the results.

**Comment by shanehughes1990** [comment]
Okay new test, same EXACT library plugins just on a single tv show that was failing, I am wondering if its a bug with one of the plugins now that it worked flawlessly without my plugin stack. I will get back to you

**Comment by HaveAGitGat** [comment]
Thanks for the feedback, and yeah let me know how it goes!

**Comment by mdoom23** [comment]
@shanehughes1990 I'm curious what the plug-in stack was that you encountered this.  I'm currently running into this on 2..00.07.

I'm currently getting some stuck in "Processing" After running Tdarr_Plugin_MC93_Migz1FFMPEG and when I have a few more plugins left.

I may go back to using my own plug-in, although I'm not sure if this is even a plug in issue or not.  I can try some of the same checks if needed (verbose logging etc.) but if you already had done this testing, I anxiously await your findings so @HaveAGitGat  can investigate!

**Comment by shanehughes1990** [comment]
Not going to lie I got busy and forgot about this, I will get the results tonight as I let the stack run its course I will post back the results, I can tell you off top my head I have all official community pkugins except one that adds aac audio was a custom plugin, just from the plugin Crestor I will link the plugin stack aswell

**Comment by HaveAGitGat** [comment]
Please reopen if needed, thanks. Also double check the error occurs on 2.00.09.
