### ISSUE TITLE
Codec exclusion options universal based on video or audio

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr#39]
Have the "Don't transcode videos already in these codecs:" be universal for the video and audio sections. If i add a codec to the video section allow the box to now appear on all video libraries, similar for audio. Not for the options to be selected the same across all libraries but so we do not have to manually enter them for every single library.

**Comment by luigi311** [comment]
Perhaps store this in mongodb, one for video and one for audio then just pull that data to populate the box entries.

**Comment by HaveAGitGat** [comment]
I’ll add this in 👍

**Comment by luigi311** [comment]
Perhaps also add a whitelist flag so we can make it so it will only transcode files with that specific codec.

**Comment by HaveAGitGat** [comment]
@luigi311 Hi again, not sure about your second point. I don't think there's a situation where this is needed where the current way couldn't handle it? 

For example if you're only wanting to convert h264 files then you can just add all other codecs to the filter so they won't be converted?

**Comment by luigi311** [comment]
While it is true that you can set it up to only transcode h264 by blacklisting every single other codec it is a lot more error prone to do it that way instead of only allowing it to transcode h264 with a whitelist. It's also hard to make sure you black list everything because codecs appear when you don't expect them too. Before I created the rearrange streams plug-in I was getting videos with a codec of ASS/SRT/AAC for my videos even though I knew they were vc-1/h264/h265. So if I had only blacklisted both vc-1 and h265 it would of transcoded everything else that was misreported with the incorrect codec.

**Comment by HaveAGitGat** [comment]
Yeah I get your point. I’ll create a new issue for that.

And your second point about incorrect codecs showing if video is not in stream 0 will be fixed👍

**Comment by HaveAGitGat** [comment]
Added in 1.006
