### ISSUE TITLE
Small rare file locking issue

### ISSUE THREAD

**Issue by realtyem** [HaveAGitGat/Tdarr#393]
**Describe the bug**
Version 2.00.06
Started receiving this error output on the Windows Tdarr_Node once an hour. Would not let me delete temp.zip(which reported a file size of 0) while node application was running, even as an administrator. Closing the application removed the file automatically, and restarts normally with no errors after that.

> [2021-03-02T10:09:07.792] [INFO] Tdarr_Node - Cloning plugins
>Error: EPERM: operation not permitted, open 'C:\Services\Tdarr\Tdarr_Node\assets\app\plugins\temp.zip'
>[2021-03-02T10:09:17.170] [FATAL] Tdarr_Node - Error in main thread:Error: EPERM: operation not permitted, open >'C:\Services\Tdarr\Tdarr_Node\assets\app\plugins\temp.zip'
>[2021-03-02T10:09:17.724] [INFO] Tdarr_Node - Finished downloading plugins!
>[2021-03-02T10:09:17.724] [ERROR] Tdarr_Node - Zip path does not exist!
>[2021-03-02T10:09:19.737] [ERROR] Tdarr_Node - Plugin unzip failed!
>[2021-03-02T11:09:07.798] [INFO] Tdarr_Node - Updating plugins
>[2021-03-02T11:09:07.799] [ERROR] Tdarr_Node - Error: EPERM: operation not permitted, lstat >'C:/Services/Tdarr/Tdarr_Node/assets/app/plugins/temp.zip'
>    at Object.lstatSync (fs.js:1026:3)
>    at Object.fs.lstatSync (pkg/prelude/bootstrap.js:1010:33)
>    at Object.lstatSync (D:\snapshot\tdarr_express_node\node_modules\graceful-fs\polyfills.js:308:16)
>    at Object.rimrafSync [as removeSync] (D:\snapshot\tdarr_express_node\node_modules\fs-extra\lib\remove\rimraf.js:228:18)
>    at updatePlugins (D:\snapshot\tdarr_express_node\srcjs\pluginFuncs.js:140:17)
>    at Timeout.scheduledPluginUpdate [as _onTimeout] (D:\snapshot\tdarr_express_node\srcjs\main.js:173:9)
>    at listOnTimeout (internal/timers.js:549:17)
>    at processTimers (internal/timers.js:492:7)

![Tdarr_node_windows_plugin_and_zip_error](https://user-images.githubusercontent.com/1582365/109694225-32835500-7b50-11eb-8017-995b1a32aeb9.jpg)
![Tdarr_node_windows_plugin_and_zip_error_security_props_dialog](https://user-images.githubusercontent.com/1582365/109694857-dff66880-7b50-11eb-97dd-ee72f007e876.jpg)

**Please provide the following information:**
 - OS: Windows

**Additional context**
A vanilla Windows 10 installation, nothing else installed

**Comment by HaveAGitGat** [comment]
Thanks, haven't had any other reports of this. Seems like some process locked the file preventing it from being deleted. Will re-open if it's a more widespread issue.
