### ISSUE TITLE
[Enhancement] Move instead of copying file from cache.

### ISSUE THREAD

**Issue by dabonetn** [HaveAGitGat/Tdarr#394]
**Is your feature request related to a problem? Please describe.**

I have my source and cache on the same drive.  When the cached job is done, tdarr creates another copy in the destination, before deleting the original out of the cache.

Moving the cache file instead of copying it again reduces writes, and makes it basically instant.

**Describe the solution you'd like**

Instead of a copy command use a move command. There's no need to create another copy of the final job on the same drive.
Or give the option to enable move instead of copy for cache handling.

**Comment by HaveAGitGat** [comment]
Hi thanks, I'll tag this onto this issue:
https://github.com/HaveAGitGat/Tdarr/issues/394

**Comment by supersnellehenk** [comment]
> Sorry, but has this issue been addressed ?

It has been, I suggest joining the discord and asking your question there.

Could also do it in a new GitHub issue if you prefer.
