### ISSUE TITLE
question: can tdarr and related plugins work memory space

### ISSUE THREAD

**Issue by repomanz** [HaveAGitGat/Tdarr#396]
Hello - I'm new to tdarr but am curious if a lot of the plugin work can be done in memory space.  I have 3 plugins that i use migz video, migz audio and migz subs.  I noticed as tdarr and the plugins are working there is a lot of writing to my SSD (for each plugin).  Is it possible to configure tdarr in a way where the writing is done in memory until the final operation. At this point it writes to disk.

**Comment by jaycedk** [comment]
I could see a problem with 60-80 Gb Bluerays.

**Comment by jasonsansone** [comment]
You can easily set your cache directly to use memory on any linux OS (/var/run) but I would be impressed if you have sufficiently available memory to keep the entire cache directory for multiple simultaneous transcodes in RAM.

**Comment by repomanz** [comment]
agree, 4k raw files would be a beast of a memory foot print; for me I have enough to support a single worker with 1080p content.  Totally forgot about linux memory space; I may try that out.

**Comment by HaveAGitGat** [comment]
Hi you can use RAM disks for this as suggested.

Some guides here:
https://www.linuxbabe.com/command-line/create-ramdisk-linux

https://www.maketecheasier.com/setup-ram-disk-windows/
