### ISSUE TITLE
Reanalyze transcoded file in Plex

### ISSUE THREAD

**Issue by ConfusedTA** [HaveAGitGat/Tdarr#398]
**Is your feature request related to a problem? Please describe.**

Once a file has been transcoded, Plex is unaware of the change, for example h264 to h265. This causes Plex to try to treat the file as h264, and playback fails. By manually Analyzing the file, Plex picks up the changes, and the file plays successfully.

**Describe the solution you'd like**

Add a connection to Plex, and upon successful transcode and file copy/move is complete, this file is set to be Analyzed.

**Describe alternatives you've considered**

**Additional context**

Thanks for your brilliant work on this - it's been running a few days now and had started to make a small dent on my library, still a few months more time to finish optimising everything!

**Comment by jaycedk** [comment]
You can try this "Tdarr_Plugin_MC93_MigzPlex_Autoscan" its in the plugin list under 3rd party

**Comment by HaveAGitGat** [comment]
Thank @jaycedk. As mentioned the plex Plugin should do this.
