### ISSUE TITLE
Bug:  Bitrate returns "null" response and marks as 'success/not required'

### ISSUE THREAD

**Issue by dsrtusr88** [HaveAGitGat/Tdarr#399]
**Describe the bug**
Some .mp4 files are returning "bit_rate": null however plex is able to get the bitrate.  Additionally it will mark the file as success/not required and not transcode.  Using Migz NVENC transcode plugin.

**To Reproduce**
Steps to reproduce the behavior: Seems like it happens predominantly on high bitrate files

**Expected behavior**
It produces the same result as plex where it can identify the bitrate.

**Screenshots**
https://pastebin.com/TuiFTafq.  Plex pulls a bit rate as:  Bitrate 40034 kbps 

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Docker
 - Version [e.g. 2.00.07]

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks, this seems to be due to an exiftool inconsistency with how it tags the Duration. In most of my files, it's this way:

`"Duration": 5207.359,`

But in your sample, it's this:
```

    "Duration": {
      "Scale": 0.0000111111111111111,
      "Value": 112281600
    },

```

I've added some extra checks for .08

**Comment by dsrtusr88** [comment]
@HaveAGitGat was this addressed in .08?  Seeing the same result.
