### ISSUE TITLE
Status on health check

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr#40]
Health checks seem to just go from 0% to complete instead of actually showing the progress or an ETA.  Is this possible to fix or not due to outputting to null?

**Comment by HaveAGitGat** [comment]
I’ll see if I can improve this 👍

**Comment by HaveAGitGat** [comment]
Hi again, sorry for the delay. Unfortunately there is no output from ffmpeg at all when carrying out the following command:

`-v error, -f null`

So I don't think it's possible to show the percentage status of thorough health checks.

**Comment by luigi311** [comment]
Yeah I think you are correct. Thanks for looking into it
