### ISSUE TITLE
ffmpeg: error while loading shared libraries: libass.so.5

### ISSUE THREAD

**Issue by wizzardking** [HaveAGitGat/Tdarr#400]
Hi

First, thank you for this great software.

Probably it's just a misconfiguration on my end, but I don't find what I did wrong and hope someone can help me here.

When I try to convert some files with any of the prebuilt plugins, I will get the following error message in the logs and the transcoding will fail directly:

```
ffmpeg -i /share/Serien/something/Season 01/Something - S01E01 - WEBRip-1080p - X264.mkv -map 0:v? -map 0:a? -map 0:s? -map 0:d? -map 0:t? -c copy /home/Something - S01E01 - WEBRip-1080p - X264-TdarrCacheFile-OgeYzdCem.mkv
Last 200 lines of CLI log:
ffmpeg: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory
Tdarr ALERT: NO OUTPUT FILE PRODUCED:
```

I'm running Tdarr in a Container on a QNAP Nas.
To bring the graphics card to work in the container, I had to put some additional informations to the docker-compose file and probably somewhere there will be my mistake.

Yaml File:
version: "3.4"
services:
  Tdarr:
    container_name: Tdarr
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # node port. It should be mapped on this container because
                  # the node container use the network from the main container
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - CUDA_VERSION=10.0.130
      - CUDA_PKG_VERSION=10-0=10.0.130-1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
      - LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
      - PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - /share/Dockerconfig/Tdarr/server:/app/server
      - /share/Dockerconfig/Tdarr/configs:/app/configs
      - /share/Dockerconfig/Tdarr/logs:/app/logs
      - /share/Serien:/share/Serien
      - /share/Filme:/share/Filme
      - /share/CACHEDEV1_DATA/.qpkg/NVIDIA_GPU_DRV/usr:/usr/local/nvidia

  tdarr-node:
    container_name: tdarr-node
    image: haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:Tdarr
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=100
      - UMASK_SET=002
      - nodeID=MainNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - serverIP=0.0.0.0
      - serverPort=8266
      - CUDA_VERSION=10.0.130
      - CUDA_PKG_VERSION=10-0=10.0.130-1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411
      - LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
      - PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - /share/Dockerconfig/Tdarr/configs:/app/configs
      - /share/Dockerconfig/Tdarr/logs:/app/logs
      - /share/Serien:/share/Serien
      - /share/Filme:/share/Filme
      - /share/CACHEDEV1_DATA/.qpkg/NVIDIA_GPU_DRV/usr:/usr/local/nvidia
     
The Config files are untouched.

**Comment by HaveAGitGat** [comment]
Please try 2.00.12 as there has been an update to ffmpeg and dependencies. Re-open if needed, thanks.
