### ISSUE TITLE
[Enhancement] Local plugins: filter by bitrate

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#401]
Although when creating a local plugin, there is already a nice selection of filters available, I would love to see one that would enable me to create a filter based on bitrate. It would help me recode files that have a higher bitrate than I transcode to with my plugins.
This information is stored in the database about all media files as far as I can tell, so I hope that adding this won't actually be much of a hassle.

**Comment by HaveAGitGat** [comment]
Added for 2.00.13
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/methods/library/filters/filterByBitrate.js
