### ISSUE TITLE
[Enhancement] Add optional delay before processing file after scan.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#402]
**Is your feature request related to a problem? Please describe.**
This situation arises when using automated downloading such as sonarr. It is often the case that an episode becomes available in one quality eg 720p, and then becomes available in a higher quality shortly after, eg 1080p. Normally, sonarr will download the best quality available initially, but then download and replace it with a better quality version afterwards.

If tdarr notices the first download and starts processing it, and sonarr downloads the replacement before it is finished, then sonarr will import the new version but not delete the existing file as it is in use. Tdarr then finishes processing the first file and the result is two versions of the same episode in different qualities instead of just one in the best quality. This is annoying and requires manual intervention to get rid of the surplus files.

**Describe the solution you'd like**
I would like there to be a configurable delay in the library settings which prevents tdarr beginning processing until the delay duration has passed. eg a new file is added to the queue by the scanner, a delay of 30 minutes is set, so tdarr does not begin processing until 30 minutes after the file is added to the queue.

This allows time for sonarr to find an upgraded quality, download it and replace the original before any processing has taken place.

**Describe alternatives you've considered**
I have tried switching off file system events and using the periodic folder scan with a longer interval set, and turning folder watch off and using the hourly scan instead however these are not entirely satisfactory, since they rely on the scan not coinciding with a new file arriving. Duplicates can still occur if the download does coincide with the scan.

**Comment by HaveAGitGat** [comment]
Hi, this has been implemented here: https://github.com/HaveAGitGat/Tdarr/issues/424
Currently in the 2.00.09 pre-release

**Comment by caiusseverus** [comment]
Thanks - seems to be working well.
