### ISSUE TITLE
Docker Images only support AMD64

### ISSUE THREAD

**Issue by rbiddulph** [HaveAGitGat/Tdarr#403]
When downloading a docker image of Tdarr 2.x, only AMD64 is available. It would be helpful if ARM versions were also available. My use case is that I want to run a server on my raspberry pi 4, the local machine to the media, and then nodes on other devices. Currently setting up on a pi 4 downloads the AMD64 image and does not launch.

**Comment by HaveAGitGat** [comment]
It works on my Pi 4 running native. The updater will only download the new packages. If you double click on Tdarr_Server then Raspberry Pi OS gives you an option to launch or run in a terminal which should work.

Would like to have ARM docker containers. Only issue is building them takes an hour+ on my Pi which is far from ideal.

**Comment by HaveAGitGat** [comment]
Will put this under this issue:
https://github.com/HaveAGitGat/Tdarr/issues/110

**Comment by HaveAGitGat** [comment]
FYI you can now use arm containers:
https://github.com/HaveAGitGat/Tdarr/issues/110#issuecomment-821780888
