### ISSUE TITLE
Question: does Tdarr work with network drives?

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#404]
Not a feature request or bug, but I am building a new PC for my rendering/plex, etc but I have my dense storage on my other computer so I am wondering if there will be any issues with Tdarr connecting via SMB (windows network drives) to the other computer to do the actual processing?

any suggestions on things I should check/do? I noticed the FAQ and past issues didn't address network drives, or at least I could'nt see from searching

Thank you!

**Comment by buddhastevend** [comment]
UNC is not currently supported, it is documented somewhere, but I don't remember where I read it. I have my drives mapped from a separate Windows 10 PC to another Windows 10 PC and in Tdarr use the "D:\Movies", etc. paths and that works.

Also, to point out, depending on your Windows security set up, make sure you don't run the server, node, and webui as admin unless you need to.

**Comment by jaycedk** [comment]
If you are on 2.00.07 UNC path are working.
//path/to/share

**Comment by HaveAGitGat** [comment]
UNC is supported. It was added in 2.00.01:
![image](https://user-images.githubusercontent.com/43864057/112747031-1938c180-8fb3-11eb-9313-1f66bbff7ace.png)

Has been working well from what I've heard since.

**Comment by DankMemeGuy** [comment]
Can confirm, works flawlessly. 2.x has been quite amazing compared to the 1.x. Great work!

**Comment by HaveAGitGat** [comment]
Glad to hear it, thanks :)
