### ISSUE TITLE
OSX Updater should chmod +x the executables.

### ISSUE THREAD

**Issue by Webreaper** [HaveAGitGat/Tdarr#405]
Installed v2.00.07 per the instructions, but when I went to run the ./Tdarr_Node/Tdarr_Node, I had to chmod +x it first. Would be nice if the updater did that automatically for me. :)

**Comment by HaveAGitGat** [comment]
This should be working already (at least it is on Linux).

Does `chmod a+rwx -R path` work on your Mac on the Tdarr folders?

**Comment by Webreaper** [comment]
I just did chmod +x Tdarr_Node and it fixed it.

**Comment by HaveAGitGat** [comment]
I was more asking if that specific command works for you as that is the command which Tdarr Updater runs once it has finished extracting new packages 👍 .

**Comment by HaveAGitGat** [comment]
I have not heard any other reports of this and Tdarr_Updater already runs `chmod a+rwx -R` on the unzipped files. Reopen if needed.
