### ISSUE TITLE
Trouble with getting second node set up.

### ISSUE THREAD

**Issue by Rsslone** [HaveAGitGat/Tdarr#406]
**Describe the bug**
I have been attempting to get a second node set up but there is an issue with the pathing, I have verbose on and its not giving me much help. Its currently registering the node fine, but once I enable a worker, the output is spammed with blank paths.

**Expected behavior**
For the second node to move files to stage and scan them.

**Please provide the following information:**
```
{
  "nodeID": "slone-pc",
  "nodeIP": "192.168.11.105",
  "nodePort": "8267",
  "serverIP": "192.168.11.110",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "A:/Plex - Anime/",
      "node": "A:/Plex - Anime/"
    },
    {
      "server": "A:/TranscodeCache/",
      "node": "A:/TranscodeCache/"
    }
  ]
}
```

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
https://gist.github.com/Rsslone/b07a23e348a5489f81c97054797696d9
https://gist.github.com/Rsslone/95c16715717062e38723228ac7672175

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
```
The following source file cannot be accessed on Tdarr_Node slone-pc:

A:/Plex - Anime/Fate+Stay Night - Unlimited Blade Works/Season 1/Fate+Stay Night - Unlimited Blade Works - S01E10 - The Fifth Contractor.mkv

To resolve this, make sure the Server and Node can access the same library and transcode cache paths.

For example, /mnt/library on the Server should point to the same location as /mnt/library on the Node.

You can set the path translators in Tdarr_Node_Config.json for when it's not possible to have the exact same paths

(e.g. if you have the Server on Linux but the Node on Windows). For instance, you could set a translator

to translate /mnt/library to C:/Library or vice versa.
```

 - OS: Win10
 - Version 2.00.07

**Comment by mdoom23** [comment]
Is the server setup with A:/TranscodeCache/ as the transcode path as well?   The cache needs to be common across node and server.

For example, I have a linux (unraid) server, and a windows node as well.  On windows I have it mapped to a network drive, but the server has a local file.  So I have something like this in my windows node config:
`  "pathTranslators": [
    {
      **"server": "/mnt/media/"**,
      "node": "M:/"
    },
    {
      **"server": "/temp/",**
      "node": "T:/"
    }
  ]`

**Comment by Rsslone** [comment]
Yes my server and node on machine 1 have a local drive A:/TranscodeCache/ and my machine 2 has a node that should see the same thing since I have the drive mapped.

**Comment by jaycedk** [comment]
On your Node can you try with UNC path, instead of drive mapping.

**Comment by Rsslone** [comment]
That seems to be connecting, but there is another problem...

```
[2021-03-24T17:16:56.645] [WARN] Tdarr_Node - Tdarr ALERT: NO OUTPUT FILE PRODUCED:
//Plex-server/a/TranscodeCache/Fire Force - S01E01 - Shinra Kusakabe Enlists-TdarrCacheFile-vd9V5w5z0.mkv
```
```
//Plex-server/a/TranscodeCache/Fire Force - S01E01 - Shinra Kusakabe Enlists-TdarrCacheFile-vd9V5w5z0.mkv: Permission denied
```

**Comment by jaycedk** [comment]
Check if your files only have read permissions.
Since tdarr can see files, but not replace.

**Comment by Rsslone** [comment]
I can't believe it was just that. I swear I set full permission. Thank you for your wisdom. For people reading in the future, make sure to use the network location by default its something like \\a\TranscodeCache\ but change it to forward slashes //a/TranscodeCache/ if network mapped drives don't work.

**Comment by Rsslone** [comment]
Huh, another interesting issue, I am running it as a service with NSSM, but it does not recognize the paths there, if I launch it directly or through cmd, it works fine.

**Comment by Rsslone** [comment]
Alright, I figured that issue out myself. For my case I had to set the service logon to my specific account with the login details. For some reason using the local system account failed to connect to the drive.
