### ISSUE TITLE
Not checking video length after transcoding to length before transcoding

### ISSUE THREAD

**Issue by Starker3** [HaveAGitGat/Tdarr#408]
**Describe the bug**
Tdarr sometimes incorrectly marks a transcode as successful and copies incomplete files to source folder

**To Reproduce**
Use network share as source folder, running 3 GPU workers - not 100% sure how to reproduce.
Using local drive as cache

This has happened too many times to be coincidence or random, not sure if the source folder becomes temporarily inaccessible or not, but Tdarr is sometimes copying files that are obviously incomplete (i.e. 3 minutes length vs original 43 minutes) thereby completely removing the source file.

**Expected behavior**
It is expected that in order to mark a transcode as successful we would be comparing the video file length (Minutes/seconds/frames) to the original information

**Screenshots**
I didn't take scrrenshots yet, I'll take some when it happens again as well as the worker output for the file that it shows as successful transcode.

**Please provide the following information:**

Desktop config:
{
  "Tdarr_Node": true,
  "Tdarr_Server": true,
  "Tdarr_WebUI": true,
  "serverIP": "127.0.0.1",
  "serverPort": 8266
}

Server config:
{
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": ""
}

 - OS: Windows
 - Browser: Desktop version
 - Version 2.00.07

**Comment by Starker3** [comment]
This happened again today, this time when manually cancelling an item that was being transcoded Tdarr marked the transcodes as successful. When I looked at the transcode information for the 'successful' transcode it shows that the video file length is short (pasted below)
![image](https://user-images.githubusercontent.com/20905821/112057890-ba440880-8bbe-11eb-850b-88b821ae0d97.png)
![image](https://user-images.githubusercontent.com/20905821/112058026-eb243d80-8bbe-11eb-834f-984f4b63cf9e.png)


{
  "_id": "D:/tdarr-cache/The Vampire Diaries - S03E18 - The Murder of One Bluray-1080p-TdarrCacheFile-TfIbkY5jM.mkv",
  "file": "D:/tdarr-cache/The Vampire Diaries - S03E18 - The Murder of One Bluray-1080p-TdarrCacheFile-TfIbkY5jM.mkv",
  "DB": "008dAUSH4",
  "container": "mkv",
  "ffProbeRead": "success",
  "createdAt": 1616446629795,
  "lastPluginDetails": "none",
  "bit_rate": 6895593.215559178,
  "statSync": {
    "dev": 1154211766,
    "mode": 33206,
    "nlink": 1,
    "uid": 0,
    "gid": 0,
    "rdev": 0,
    "blksize": 4096,
    "ino": 2251799813685765,
    "size": 806906803,
    "blocks": 1575992,
    "atimeMs": 1616442103249.4417,
    "mtimeMs": 1616442103249.4417,
    "ctimeMs": 1616442103249.4417,
    "birthtimeMs": 1616440738804.7485,
    "atime": "2021-03-22T19:41:43.249Z",
    "mtime": "2021-03-22T19:41:43.249Z",
    "ctime": "2021-03-22T19:41:43.249Z",
    "birthtime": "2021-03-22T19:18:58.805Z"
  },
  "file_size": 769.5262937545776,
  "ffProbeData": {
    "streams": [
      {
        "index": 0,
        "codec_name": "hevc",
        "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
        "profile": "Main",
        "codec_type": "video",
        "codec_time_base": "1001/24000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "width": 1920,
        "height": 1080,
        "coded_width": 1920,
        "coded_height": 1088,
        "has_b_frames": 0,
        "sample_aspect_ratio": "1:1",
        "display_aspect_ratio": "16:9",
        "pix_fmt": "yuv420p",
        "level": 120,
        "color_range": "tv",
        "chroma_location": "left",
        "refs": 1,
        "r_frame_rate": "24000/1001",
        "avg_frame_rate": "24000/1001",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "ENCODER": "Lavc58.42.102 hevc_nvenc",
          "DURATION": "00:15:33.766000000"
        }
      },
      {
        "index": 1,
        "codec_name": "dts",
        "codec_long_name": "DCA (DTS Coherent Acoustics)",
        "profile": "DTS",
        "codec_type": "audio",
        "codec_time_base": "1/48000",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "sample_fmt": "fltp",
        "sample_rate": "48000",
        "channels": 6,
        "channel_layout": "5.1(side)",
        "bits_per_sample": 0,
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "bit_rate": "1536000",
        "disposition": {
          "default": 1,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "00:15:33.630000000"
        }
      },
      {
        "index": 2,
        "codec_name": "subrip",
        "codec_long_name": "SubRip subtitle",
        "codec_type": "subtitle",
        "codec_time_base": "0/1",
        "codec_tag_string": "[0][0][0][0]",
        "codec_tag": "0x0000",
        "r_frame_rate": "0/0",
        "avg_frame_rate": "0/0",
        "time_base": "1/1000",
        "start_pts": 0,
        "start_time": "0.000000",
        "duration_ts": 936142,
        "duration": "936.142000",
        "disposition": {
          "default": 0,
          "dub": 0,
          "original": 0,
          "comment": 0,
          "lyrics": 0,
          "karaoke": 0,
          "forced": 0,
          "hearing_impaired": 0,
          "visual_impaired": 0,
          "clean_effects": 0,
          "attached_pic": 0,
          "timed_thumbnails": 0
        },
        "tags": {
          "language": "eng",
          "DURATION": "00:15:36.142000000"
        }
      }
    ]
  },
  "meta": {
    "SourceFile": "D:/tdarr-cache/The Vampire Diaries - S03E18 - The Murder of One Bluray-1080p-TdarrCacheFile-TfIbkY5jM.mkv",
    "errors": [],
    "Duration": 936.142,
    "ExifToolVersion": 12.1,
    "FileName": "The Vampire Diaries - S03E18 - The Murder of One Bluray-1080p-TdarrCacheFile-TfIbkY5jM.mkv",
    "Directory": "D:/tdarr-cache",
    "FileSize": "770 MB",
    "FileModifyDate": {
      "year": 2021,
      "month": 3,
      "day": 23,
      "hour": 8,
      "minute": 41,
      "second": 43,
      "millisecond": 0,
      "tzoffsetMinutes": 780,
      "rawValue": "2021:03:23 08:41:43+13:00"
    },
    "FileAccessDate": {
      "year": 2021,
      "month": 3,
      "day": 23,
      "hour": 8,
      "minute": 41,
      "second": 43,
      "millisecond": 0,
      "tzoffsetMinutes": 780,
      "rawValue": "2021:03:23 08:41:43+13:00"
    },
    "FileCreateDate": {
      "year": 2021,
      "month": 3,
      "day": 23,
      "hour": 8,
      "minute": 18,
      "second": 58,
      "millisecond": 0,
      "tzoffsetMinutes": 780,
      "rawValue": "2021:03:23 08:18:58+13:00"
    },
    "FilePermissions": "rw-rw-rw-",
    "FileType": "MKV",
    "FileTypeExtension": "mkv",
    "MIMEType": "video/x-matroska",
    "EBMLVersion": 1,
    "EBMLReadVersion": 1,
    "DocType": "matroska",
    "DocTypeVersion": 4,
    "DocTypeReadVersion": 2,
    "TimecodeScale": "1 ms",
    "MuxingApp": "Lavf58.24.101",
    "WritingApp": "Lavf58.24.101",
    "VideoFrameRate": 23.976,
    "ImageWidth": 1920,
    "ImageHeight": 1080,
    "AudioChannels": 6,
    "AudioSampleRate": 48000,
    "AudioBitsPerSample": 32,
    "TrackNumber": 3,
    "TrackLanguage": "eng",
    "TrackDefault": "No",
    "CodecID": "S_TEXT/UTF8",
    "TrackType": "Subtitle",
    "ChapterTimeStart": "0:40:46",
    "ChapterTimeEnd": "0:41:14",
    "ChapterString": "00:40:45.818",
    "ChapterLanguage": "und",
    "TagName": "DURATION",
    "TagString": "00:15:36.142000000",
    "ImageSize": "1920x1080",
    "Megapixels": 2.1
  },
  "mediaInfo": {
    "@ref": "",
    "track": [
      {
        "@type": "General",
        "UniqueID": "291029448881995772134657021086529720880",
        "VideoCount": "1",
        "AudioCount": "1",
        "TextCount": "1",
        "MenuCount": "1",
        "Format": "Matroska",
        "Format_Version": "4",
        "FileSize": "806906803",
        "Duration": "936.142",
        "OverallBitRate": "6895593",
        "FrameRate": "23.976",
        "FrameCount": "22388",
        "StreamSize": "18089638",
        "IsStreamable": "Yes",
        "Encoded_Application": "Lavf58.24.101",
        "Encoded_Library": "Lavf58.24.101",
        "extra": {
          "ErrorDetectionType": "Per level 1"
        }
      },
      {
        "@type": "Video",
        "StreamOrder": "0",
        "ID": "1",
        "UniqueID": "1",
        "Format": "HEVC",
        "Format_Profile": "Main",
        "Format_Level": "4",
        "Format_Tier": "Main",
        "CodecID": "V_MPEGH/ISO/HEVC",
        "Duration": "933.766000000",
        "BitRate": "5249371",
        "Width": "1920",
        "Height": "1080",
        "Stored_Height": "1088",
        "Sampled_Width": "1920",
        "Sampled_Height": "1080",
        "PixelAspectRatio": "1.000",
        "DisplayAspectRatio": "1.778",
        "FrameRate_Mode": "CFR",
        "FrameRate": "23.976",
        "FrameCount": "22388",
        "ColorSpace": "YUV",
        "ChromaSubsampling": "4:2:0",
        "BitDepth": "8",
        "Delay": "0.000",
        "StreamSize": "612711207",
        "Encoded_Library": "Lavc58.42.102 hevc_nvenc",
        "Language": "en",
        "Default": "Yes",
        "Forced": "No"
      },
      {
        "@type": "Audio",
        "StreamOrder": "1",
        "ID": "2",
        "UniqueID": "2",
        "Format": "DTS",
        "Format_Settings_Mode": "16",
        "Format_Settings_Endianness": "Big",
        "CodecID": "A_DTS",
        "Duration": "933.630000000",
        "BitRate_Mode": "CBR",
        "BitRate": "1509000",
        "Channels": "6",
        "ChannelPositions": "Front: L C R, Side: L R, LFE",
        "ChannelLayout": "C L R Ls Rs LFE",
        "SamplesPerFrame": "512",
        "SamplingRate": "48000",
        "SamplingCount": "44814240",
        "FrameRate": "93.750",
        "BitDepth": "24",
        "Compression_Mode": "Lossy",
        "Delay": "0.000",
        "Delay_Source": "Container",
        "StreamSize": "176105958",
        "StreamSize_Proportion": "0.21825",
        "Language": "en",
        "Default": "Yes",
        "Forced": "No"
      },
      {
        "@type": "Text",
        "ID": "3",
        "UniqueID": "3",
        "Format": "UTF-8",
        "CodecID": "S_TEXT/UTF8",
        "Duration": "936.142000000",
        "Language": "en",
        "Default": "No",
        "Forced": "No"
      },
      {
        "@type": "Menu",
        "extra": {
          "_00_00_00_000": ":00:00:00.000",
          "_00_00_40_374": ":00:00:40.374",
          "_00_01_59_745": ":00:01:59.745",
          "_00_09_33_031": ":00:09:33.031",
          "_00_17_23_584": ":00:17:23.584",
          "_00_25_02_376": ":00:25:02.376",
          "_00_29_36_608": ":00:29:36.608",
          "_00_35_22_912": ":00:35:22.912",
          "_00_40_45_818": ":00:40:45.818"
        }
      }
    ]
  },
  "hasClosedCaptions": false,
  "bumped": false,
  "HealthCheck": "",
  "TranscodeDecisionMaker": "",
  "processingStatus": false,
  "fileMedium": "video",
  "infoLog": "",
  "video_codec_name": "hevc",
  "audio_codec_name": "",
  "video_resolution": "1080p",
  "lastHealthCheckDate": 0,
  "lastTranscodeDate": 0,
  "history": "",
  "oldSize": 0,
  "newSize": 0,
  "tPosition": 0,
  "hPosition": 0
}

**Comment by HaveAGitGat** [comment]
I have not seen or heard of this error happening so like you say it might be something to do with your setup. Tdarr relies on FFmpeg/HandBrake to give an error if a problem is encountered (Tdarr also does an extra check to see if an output file exists). Are you using HandBrake or FFmpeg? 

The issue with your suggestion is that the duration isn't always available on input files and file processing may drastically change the number of frames (e.g when going from 60fps to 30fps).

**Comment by Starker3** [comment]
I changed the setup to have the server running on the UnRAID host and haven't really had this issue come up again.

It's possible that this issue is only related to running server & node on the windows machine with the files located on a network share.

Current setup is Server - unRAID 
File location: local to server, mapped drive on node
Cache location: local to server, mapped drive on node

As for the suggestion, would it be possible to check the output file size is at least close the estimated output size? (Within a few % points maybe)
I would imagine that in most cases the estimated size would be at least close to the actual output size and that would have picked up the ones that actually failed because they were like 50% of the expected size.

**Comment by HaveAGitGat** [comment]
Yeah sounds like FFmpeg isn't throwing an error if the network connection drops or something like that. 

I'll try and add a check in which compares the times/durations of the new and old file (if that info is available for each file).

**Comment by stuart475898** [comment]
Just to add I've noticed myself experiencing the same issue today - some files are far to small in the transcode area waiting to be accepted. I have source/destination + server on one machine, and the single worker running on another. I have also been having some problems with my worker PC dropping its connection occasionally (looks to be a possible driver issue with the NIC + high load). Sounds very similar to OPs issue - would second a frame/time check on file post transcode, as well as any other health check that could be done (I don't know enough about the technicalities of encoding to know whether the last one is even possible?). For reference, using the `Tdarr_Plugin_drdd_standardise_all_in_one` plugin

**Comment by HaveAGitGat** [comment]
There are now file size and duration check plugins where you can add the upper and lower bounds (%).

Tdarr_Plugin_a9he_New_file_size_check
Tdarr_Plugin_a9hf_New_file_duration_check

Add them anywhere in your plugin stack.

**Comment by ChristianStrawn** [comment]
> Tdarr_Plugin_a9hf_New_file_duration_check

I wish I had known about this plugin much earlier, lol.
