### ISSUE TITLE
Unknown Handbrake option  

### ISSUE THREAD

**Issue by russdog75** [HaveAGitGat/Tdarr#409]
My transcodes are failing.  After completing the process, they all get moved to the error log.  

It appears to be passing an option to handbrake that handbrake does not recognize.  Anyone know how to fix this?

The error information is pasted below:

NodeID: thick-teal

Command:

/usr/bin/handbrake -i /media/raid/tvshows/America's Test Kitchen/Season 17/America's Test Kitchen - S17E03 - Back to Basics HDTV-720p.mp4 -o /media/raid2/cache/America's Test Kitchen - S17E03 - Back to Basics HDTV-720p-TdarrCacheFile-luACc2Liz.mp4 --scan

Last 200 lines of CLI log:

Unknown option -i

(handbrake:46811): GLib-GObject-CRITICAL **: 08:28:44.761: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(handbrake:46811): GLib-GObject-CRITICAL **: 08:28:44.762: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(handbrake:46811): GLib-GObject-CRITICAL **: 08:28:44.767: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by jaycedk** [comment]
The Handbreak option -i is input.
That error indicates that handbreak can not find your file. or path is incorrect.
[https://handbrake.fr/docs/en/latest/cli/command-line-reference.html](https://handbrake.fr/docs/en/latest/cli/command-line-reference.html
)

**Comment by cfishwick** [comment]
@jaycedk Actually, not true.  The version of handbrake in the default Ubuntu install doesn't have a -i command line option.  It needs to be removed and the version from the PPA installed instead.  (At least on Ubuntu 18.04 this was the case for me)

@russdog75 Follow the directions here: https://handbrake.fr/docs/en/1.3.0/get-handbrake/download-and-install.html to install the PPA version which should then work.

**Comment by HaveAGitGat** [comment]
@cfishwick thanks. Closing this as there's a solution.
