### ISSUE TITLE
Apply button for changes

### ISSUE THREAD

**Issue by luigi311** [HaveAGitGat/Tdarr#41]
Some people might feel uneasy with changes being applied automatically to something that could potentially ruin their entire media library without an undo process. Can you add a apply button to changes that we can make so it doesn't go and start making changes to our files until we are completely done setting everything up.

**Comment by HaveAGitGat** [comment]
Hi there is the 'Process library' switch already for this reason:

![image](https://user-images.githubusercontent.com/43864057/67254962-aea75c00-f477-11e9-899e-5a5f4fbd481b.png)

Perhaps it will do what you need?

**Comment by luigi311** [comment]
You know what your right. I didn't even consider that. That works.
