### ISSUE TITLE
Issue with transcode loop errors

### ISSUE THREAD

**Issue by russdog75** [HaveAGitGat/Tdarr#410]
I'm unable to get the Tdarr_Plugin_MC93_Migz1FFMPEG plugin working. It's giving me the following error on every file. Anyone run into this before?

The new transcode arguments were the exact same as the last ones meaning

the file/worker would most likely be stuck in an infinite transcode loop if not stopped.

Last arguments: , -map 0 -c copy

New arguments: , -map 0 -c copy

Plugin Community Tdarr_Plugin_MC93_Migz1FFMPEG

**Comment by HaveAGitGat** [comment]
Have you configured the inputs for that plugin in the library settings?

Are the files being scanned correctly? If you search for one of the files on the Search tab and click the 'i' button, does it show data has been extracted?

**Comment by HaveAGitGat** [comment]
Reopen if needed, thanks.

**Comment by yevon** [comment]
I'm getting this error with the Tdarr_Plugin_MC93_Migz1FFMPEG plugin also when setting the container to mp4, using any file.
