### ISSUE TITLE
Tdarr deletes source file without replacing it.

### ISSUE THREAD

**Issue by MariusSp** [HaveAGitGat/Tdarr#411]
**Describe the bug**
Tdarr detects a new file, scans it, sends it to a node for transcoding (which also gets processed, reading of the progress bar and system processes). Then it tries to replace the source file with the transcode from the temp folder, which fails. Error message says  `The following source file cannot be accessed on Tdarr_Node Node1`, but the /series dir + all containing files have sufficient permissions (775). This started a few days ago. I might have updated the container, don't quite remember. v2.00.07

docker server log:
```[2021-03-27T19:55:43.517] [INFO] Tdarr_Server - v5grUEX7a: File detected, adding to queue:/media/series/DIR/FILENAME.mkv,
[2021-03-27T19:56:02.036] [INFO] Tdarr_Server - v5grUEX7a: Sending files for scanning, library :v5grUEX7a,
[2021-03-27T19:56:02.042] [INFO] Tdarr_Server - tossT0Dlar Prep started,
[2021-03-27T19:56:02.102] [INFO] Tdarr_Server - [0.061s] tossT0Dlar Prep finished,
[2021-03-27T19:56:02.102] [INFO] Tdarr_Server - Scanner tossT0Dlar launched,
[2021-03-27T19:56:02.723] [INFO] Tdarr_Server - Online,
[2021-03-27T19:56:02.727] [INFO] Tdarr_Server - 1 files sending,
[2021-03-27T19:56:02.728] [INFO] Tdarr_Server - [0.001s] 1 files sent,
[2021-03-27T19:56:14.858] [INFO] Tdarr_Server - Finished in 12.136s,
[2021-03-27T19:56:14.859] [INFO] Tdarr_Server - Scanner tossT0Dlar:Finished,
[2021-03-27T19:56:14.859] [WARN] Tdarr_Server - Exit approved. Closing process.,
[2021-03-27T19:56:15.873] [INFO] Tdarr_Server - tossT0Dlar File scanner exited,
Error: ENOENT: no such file or directory, open '/temp/FILENAME-TdarrCacheFile-47QxaSCny.mkv',
    at Object.openSync (fs.js:461:3),
    at Object.fs.openSync (pkg/prelude/bootstrap.js:487:32),
    at /snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:85:51,
    at step (/snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:33:23),
    at Object.next (/snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:14:53),
    at /snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:8:71,
    at new Promise (<anonymous>),
    at __awaiter (/snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:4:12),
    at run (/snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:79:32),
    at /snapshot/tdarr_express_be/srcjs/fileScanner/mediaInfo.js:114:22,
No such file or directory: /temp/FILENAME-TdarrCacheFile-47QxaSCny.mkv,
[2021-03-27T19:59:42.505] [INFO] Tdarr_Server - v5grUEX7a: file removed, removing:/media/series/DIR/FILENAME.mkv,
```

docker node log only says `File is not video`, I'm not sure tho if this is related or just an artifact of something else.

**Expected behavior**
Replacing the source file with the transcode result. If it fails during the process, at least don't remove the source file.

**Please provide the following information:**
node config:
```{
  "nodeID": "Node1",
  "nodeIP": "0.0.0.0",
  "nodePort": "8267",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ]
```
server config:
```
{
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```

docker config:
```
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - TZ=Europe/Berlin
      - PUID=1001
      - PGID=1001
      - serverPort=8266
      - webUIPort=8265
      - serverIP=0.0.0.0
    volumes:
      - /media:/media
      - ./tdarr:/app/server
      - ./tdarr/configs:/app/configs
    ports:
      - 127.0.0.1:8265:8265
      - 8266:8266
      - 8267:8267
    network_mode: bridge
    restart: unless-stopped

  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    environment:
      - TZ=Europe/Berlin
      - PUID=1001
      - PGID=1001
      - serverIP=0.0.0.0
      - serverPort=8266
      - nodeIP=0.0.0.0
      - nodePort=8267
      - nodeID=Node1
    volumes:
      - /media:/media
      - ./tdarr/configs:/app/configs
      - ./tdarr:/app/server
    network_mode: service:tdarr
    restart: unless-stopped
```

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
Interestingly, I can't find any logfiles on my disk.

**Comment by HaveAGitGat** [comment]
Hi, the log files are within the container at `/app/logs/` which you have not mapped in your compose file. You'd need to add something such as ` - ./tdarr/logs:/app/logs` in the `volumes` to be able to see the logs.

**Comment by MariusSp** [comment]
Well that's kinda obvious, thanks...

Anyway, logs created match those excerpts above. Or is there any extra debug mode?

**Comment by HaveAGitGat** [comment]
Folders looks fine so it seems to a be permissions issue with your host OS. Perhaps try using some test files on a different drive/share so you can narrow down the issue.

**Comment by HaveAGitGat** [comment]
Reopen if needed, thanks.

**Comment by MariusSp** [comment]
Yea, I'm not sure what else I could do here. All permissions are set + owner etc. is the same. Unfortunately the server only has the one disk installed.

I probably will install tdarr again. Thanks.

**Comment by danielx** [comment]
Just had the same issue, forgot to map the volume for `/temp` on my `tdarr_node` container.

Was really surprised when i noticed that all successful transcodes using tdarr had actually saved me more disk space than i could ever imagine :)

+1 on not deleting source files if the replacement fails.
