### ISSUE TITLE
CPU Usage limiter

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#413]
**Is your feature request related to a problem? Please describe.**
When Tdarr runs it will max the CPU usage.

**Describe the solution you'd like**
Set a rate limit for how much CPU usage should occur.

**Describe alternatives you've considered**

**Additional context**

**Comment by HaveAGitGat** [comment]
There's an option in the Node Options to set a lower process priority for HandBrake/FFmpeg processes (doesn't work for Docker). If using Docker you can pin cores which is the best method.

![image](https://user-images.githubusercontent.com/43864057/113396788-62ff1e80-939c-11eb-9e24-fb26860fccd2.png)

**Comment by milindpatel63** [comment]
But the node cpu usage is fine..
In my case, the tdarr_server process uses around 20% of my cpu even when idle...even when it's not updating any db, or transcoding anything...
