### ISSUE TITLE
Question about Filepath translation

### ISSUE THREAD

**Issue by Marly212** [HaveAGitGat/Tdarr#415]
Hey,

I am currently trying to Transcode all new Files from the /media Folder with my own HandBrake Preset, I am using the Plugin "Video Transcode Customisable" to specify my JSON Preset and other Parameters. The Preset is doing exactly what it should and is executing the command:

HandBrakeCLI -i /media/SW/test movie.mkv -o /temp/test movie-TdarrCacheFile-ImXrelDV0.mkv --preset-import-file /app/server/Tdarr/Plugins/Local/MyPreset.json -Z MyPreset

The Command is fine BUT HandBrake cant find the file cause it's searching for /media/SW/test and not the whole Path. When I tried the exact same Command but with " " for the Paths it's working and the Transcoding is working.

HandBrakeCLI -i "/media/SW/test movie.mkv" -o "/temp/test movie-TdarrCacheFile-ImXrelDV0.mkv --preset-import-file /app/server/Tdarr/Plugins/Local/MyPreset.json" -Z MyPreset

I just wanna know if I forgot a setting or somethin else to give the path with "" so HandBrake can find the File.

**Comment by HaveAGitGat** [comment]
Hi, thanks for opening an issue.

Please can you provide more info on your Tdarr setup. The bug report option asks this but seems you may have missed it:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 2.00.00]


**Additional context**
Add any other context about the problem here.
```

I have not heard any issues with spaces in file paths in a fair while. You need to use quotes around file paths when running the commands manually as that is different to how Tdarr executes the command.

The Tdarr release tests use file paths with spaces in and all those tests passed.

```
────────────────────────────────────────────┐
cypress_1     |   │ Tests:        30
                                            │
cypress_1     |   │ Passing:      30
                                            │
cypress_1     |   │ Failing:      0
                                            │
cypress_1     |   │ Pending:      0
                                            │
cypress_1     |   │ Skipped:      0
                                            │
cypress_1     |   │ Screenshots:  0
                                            │
cypress_1     |   │ Video:        true
                                            │
cypress_1     |   │ Duration:     1 minute, 5 seconds
                                            │
cypress_1     |   │ Spec Ran:     nav/nav.js
                                            │
cypress_1     |   └───────────────────────────

```

**Comment by Marly212** [comment]
Hey, sorry for responding so late.

I noticed the Bug Report option, but I thought that it was simply a button or setting I need to change so I didn't choose that Options.

**Describe the bug**
As I mentioned in the Issue, Tdarr is executing the Command to Transcode the File like this:

HandBrakeCLI -i /media/SW/test movie.mkv -o /temp/test movie-TdarrCacheFile-ImXrelDV0.mkv --preset-import-file /app/server/Tdarr/Plugins/Local/MyPreset.json -Z MyPreset

This is fine BUT Handbreak can't find the File to Transcode cause it's not parsing the Path as a whole, so for example I took the exact same Code and executed it in the Container but with " " at the beginning and the end like this:

HandBrakeCLI -i "/media/SW/test movie.mkv" -o "/temp/test movie-TdarrCacheFile-ImXrelDV0.mkv --preset-import-file /app/server/Tdarr/Plugins/Local/MyPreset.json" -Z MyPreset

After I execute this Command Tdarr begins to Transcode the File.

**To Reproduce**
The Description above should be enough, pls ask if you don't understand something

**Expected behavior**
Tdarr to parse the Path with "" that Handbrake can find the File

**Screenshots**
Tdarr WebUI 

![grafik](https://user-images.githubusercontent.com/42452096/113848914-3fbbe100-9799-11eb-9db7-8f99c6bac616.png)

Tdarr Server

![grafik](https://user-images.githubusercontent.com/42452096/113848971-4ea29380-9799-11eb-96fb-283ade89c532.png)

Pls think of localip as my local Ip address

**Please provide the following information:**
Config files: See Screenshots, cause I can't upload JSON Files

Log files: 
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/6274046/Tdarr_Server_Log.txt)

-Worker error 
![grafik](https://user-images.githubusercontent.com/42452096/113924129-bbde1500-97e9-11eb-8c03-db47ed1074ba.png)

- OS: Docker Container on a Synology NAS 
 - Browser Firefox
 - Version 2.00.08

**Comment by HaveAGitGat** [comment]
The issue is not to do with quotes around file paths, it's to do with your HandBrake preset. That's the error which HandBrake gives when there's an issue with the preset settings.

Use a community plugin on the same file and you'll see it's not to do with the input/output filepaths (or something else is wrong).

**Comment by Marly212** [comment]
Ok thanks for the info, I will test it later the Day or tomorrow.

Another Question:

How can I tell Tdarr to Transcode every Video File in the Folder with a specific HandBreak Preset that I exported from my Windows GUI HandBrake?

**Comment by HaveAGitGat** [comment]
Tdarr is a conditional based transcoding application so you need to set some conditions for transcoding. You can set some basic filters in the video library settings, or you can add some more filters in the plugin creator on the Plugins tab. Else you can write your own plugin if you know some Javascript
![image](https://user-images.githubusercontent.com/43864057/114261739-8b120180-99dc-11eb-8f45-52a26ac9ee32.png)

Community plugins are hosted here: 
https://github.com/HaveAGitGat/Tdarr_Plugins/tree/master/Community

That error might be to do with copyright protection which HandBrake does not support.

**Comment by HaveAGitGat** [comment]
Reopen if needed. Thanks.
