### ISSUE TITLE
Library option "Scan (Find new)" requeues all files in library

### ISSUE THREAD

**Issue by CplPwnies** [HaveAGitGat/Tdarr#416]
**Describe the bug**
When looking at the library options, the "Scan (Find New)" option exhibits the same behavior as the "Scan (Fresh)" option. It requeues ALL files in the library regardless of whether it's already been processed.

**To Reproduce**
Go to any library -> Options dropdown -> Scan (Find New)

**Expected behavior**
Only queue up new files instead of ALL files

**Screenshots**
N/A

**Please provide the following information:**
 - OS: Debian / docker
 - Browser Chrome
 - Version 2.00.08

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
Hi, I've tried to replicate this on Window, Docker for Windows, Ubuntu 18.04 and Docker for Linux but could not, everything was working fine. 

Is it just the first time you scan or every time?

**Comment by CplPwnies** [comment]
Hi,

So far I've done it twice and it has had the same outcome every time.

**Comment by HaveAGitGat** [comment]
I suspect it’s due to the file system being used rather than than the OS. Which file system are your drives using?

**Comment by CplPwnies** [comment]
I am using ZFS on my media drives setup in a raid ZFS1

**Comment by HaveAGitGat** [comment]
Probably something to do with mtime/ctime of files. I've made some changes in the 2.00.09 packages/container which _should_ fix this. Are you able to verify? Create a backup on the backups tab before hitting the Scan (Find new) button if needed. Working fine on NTFS and EXT4 drives for me.

**Comment by CplPwnies** [comment]
I just pulled down the 2.00.09 container and did a Scan (Find new) on both my libraries and it did not requeue all the files, so it looks like that fixed it.

Thanks so much!

**Comment by HaveAGitGat** [comment]
Pleased to hear it, thanks for checking!

**Comment by HaveAGitGat** [comment]
09 released
