### ISSUE TITLE
[Feature Request] Add ability to show what Library each item originated from in the Status / Queue areas

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#417]
**Is your feature request related to a problem? Please describe.**
Right now, it's not possibly to see an item in the queue/status and to easily tell what library that item originated from.

**Describe the solution you'd like**
On the status/queue screens, add an additional column (perhaps even with a configuration switch to turn it off/on) that displays the name of the Library that the item originated from.

**Describe alternatives you've considered**
Not knowing what library the item is from

![Selection_095](https://user-images.githubusercontent.com/39832147/113449576-21866780-93cc-11eb-9506-1999f6a3f2c8.png)

**Comment by HaveAGitGat** [comment]
Added to 2.00.15:
![image](https://user-images.githubusercontent.com/43864057/155923429-5f440063-a8b9-4cd6-99b7-b122f597207f.png)
