### ISSUE TITLE
Stalled workers not detected reliably

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#418]
**Describe the bug**
I occasionally get gpu hangs which result in ffmpeg sitting there doing nothing until it is manually killed. Restarting a job usually works ok. I have the "auto-cancel stalled workers" option ticked, however it doesn't seem to work.

**To Reproduce**
Run transcodes until a gpu hang occurs.

**Expected behavior**
Tdarr should notice that the transcode is not progressing and kill/restart the worker.

**Screenshots**
Files usually sit there like this:
![image](https://user-images.githubusercontent.com/7763268/113465480-25e26d00-942c-11eb-917d-5bdab9a7e54a.png)

There is no output file generated since ffmpeg hangs before anything is produced.

**Comment by HaveAGitGat** [comment]
Hi, I've fixed this for 09. Also added an option so you can set the stall check interval (default 5 mins):
![image](https://user-images.githubusercontent.com/43864057/113500280-f7908a80-951c-11eb-88de-ce42cec78f64.png)

Will be out today.

**Comment by HaveAGitGat** [comment]
2.00.09 is now in pre-release:
https://tdarr.io/docs/pre-releases

**Comment by caiusseverus** [comment]
This appears to be working correctly now. Thanks.
