### ISSUE TITLE
Stats page timesout on load, in Chrome and Edge, Firefox works.

### ISSUE THREAD

**Issue by jaycedk** [HaveAGitGat/Tdarr#419]
**Describe the bug**
Updatet to 2.00.09.
I can't load the stats page if im using chrome or edge.
Chrome and edge times out and asks if I want to wait.
Firefox its loading after 30 sec.

**To Reproduce**
Open Tdarr webui in chrome or edge -> stats -> wait -> timeout.

**Expected behavior**
Open Tdarr webui in chrome or edge -> stats -> load stats page.

**Screenshots**
![billede](https://user-images.githubusercontent.com/17232146/113505771-3fc1a400-9541-11eb-8a07-7fa91140ecc9.png)

**Please provide the following information:**
Running Native on Windows 10

- Log files  
There is nothing in the Server logs about it.

 - OS: Windows 10
 - Browser Chrome and Edge
 - Version [2.00.09]

**Additional context**
There is also nothing in the browser console about it, because the page is not loading.

If you need me to test something else, just tell me, and I will try and get you what you need :)

**Comment by HaveAGitGat** [comment]
Are you logged in or out when that happens?

**Comment by jaycedk** [comment]
Oh yeah, forgot about that.
I have tried logging in before and after loading the page.
I have also cleared browser cache.
And tried in incognito mode. 
All of this with both Chrome and Edge.

**Comment by HaveAGitGat** [comment]
Thanks. Are you able to check /server/Tdarr/DB2/WorkerHistoryJSONDB and WorkerVerdictHistoryJSONDB? How many items are in those folders?

**Comment by jaycedk** [comment]
/server/Tdarr/DB2/WorkerHistoryJSONDB = 718 files
/server/Tdarr/DB2/WorkerVerdictHistoryJSONDB = 522112 files
Thats alot of files.

**Comment by HaveAGitGat** [comment]
Yeah that might be *slightly* more than I was expecting the average user to have. Will need to do some optimizing. 

How much RAM does Tdarr Server use for you?

**Comment by jaycedk** [comment]
Right now its using 
![billede](https://user-images.githubusercontent.com/17232146/113506556-d7c18c80-9545-11eb-8833-bbd783d6da6c.png)
Not sure why its has 3 Tdarr_server.exe running, is that normal ?

**Comment by jaycedk** [comment]
Overall system RAM 16GB Used 40%

**Comment by HaveAGitGat** [comment]
400MB for the main server process is better than I was expecting for that amount of data. Those DB files are tiny (under 50bytes) so don’t add up to much.

Yeah the other processes are just sub-processes which show separately. One of them is for the web UI.

**Comment by jaycedk** [comment]
ok, guess i'm an edge case 😃 with all those files.

**Comment by HaveAGitGat** [comment]
It came down to one line holding up the rendering. I've made some changes so now it's 200-300 times faster (~5 secs vs ~0.02 secs).

I used 300,000 or so data points but it should be useable for you. Else it might be something else.

![image](https://user-images.githubusercontent.com/43864057/113510025-d9e11680-9558-11eb-8626-26dd082a9c50.png)

New packages will be ready in 10 mins or so.

**Comment by HaveAGitGat** [comment]
Updated the packages and containers 👍

**Comment by jaycedk** [comment]
Cool will try and report back.

**Comment by jaycedk** [comment]
👍  Its alive 😃 and working in both Chrome, Edge.
And firefox loads alot faster now.
Thank you 😄

**Comment by HaveAGitGat** [comment]
Great! Thanks for the help 👍.
