### ISSUE TITLE
Feature Request - URL Base

### ISSUE THREAD

**Issue by nyid** [HaveAGitGat/Tdarr#42]
Hello! I'd like to set up Tdarr behind a nginx reverse proxy with a subdirectory. Would it be possible to add a configuration for url base?

**Comment by HaveAGitGat** [comment]
I’ll see if I can add this in 👍

**Comment by HaveAGitGat** [comment]
Hi just to double check, by 'base' do you mean for example:

base:8265/configurable_base/tdarr

**Comment by nyid** [comment]
Yes I _think_ we're talking about the same thing. Base URL in this context refers to the URL portion after "IP:PORT".

The base URL for tdarr is currently "/". All resources are located at "localhost:8265/". 

A common practice is to put web applications behind a reverse proxy. My use case is to separate by sub-directories, I.e. "www.mywebsite.com/tdarr". When those requests are proxied to the internal IP:PORT it looks like "localhost:8265/tdarr". 

I would expect a configuration in Tdarr to change the base URL from "/" to "/tdarr" (or whatever the user wants). 

So the current URL of "localhost:8265/logs/" would be changed to "localhost:8265/tdarr/logs/", where the base URL is "/tdarr".

I hope that explained it better.

**Comment by HaveAGitGat** [comment]
Ok yeah that's fine. 

I've added this into 1.005. Will be released tomorrow.

You need to set a new environment variable 'BASE' to change the base path e.g.:

 -e "BASE=/test" 

Home URL will then be:

localhost:8265/test

**Comment by theg00s3** [comment]
Hey @nyid I was wondering if I could see the tdarr section of your nginx config. I can't get mine to work

**Comment by nyid** [comment]
Sure, I'm using the standard letsencrypt proxy config and organizr auth. Make sure you have ROOT_URL set if you're using docker and don't forget to set the base url under tdarr options.

docker env
```
ROOT_URL=http://localhost/tdarr
```

tdarr options
```
Base URL=/tdarr
```

tdarr.conf
```
# tdarr redirect
    location /tdarr {
    return 301 /tdarr/;
    }
# tdarr CONTAINER	
    location /tdarr/ {
    auth_request /auth-0;
    proxy_pass http://10.0.20.50:8265/tdarr/;
    include /config/nginx/proxy.conf;
    }
```

proxy.conf
```
## Version 2019/10/23 - Changelog: https://github.com/linuxserver/docker-letsencrypt/commits/master/root/defaults/proxy.conf

client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

# TLS 1.3 early data
proxy_set_header Early-Data $ssl_early_data;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
#proxy_cookie_path / "/; HTTPOnly; Secure"; # enable at your own risk, may break certain apps
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
```
