### ISSUE TITLE
PathTranslators is missing for HandBrake Presets

### ISSUE THREAD

**Issue by david-steg** [HaveAGitGat/Tdarr#420]
**Describe the bug**
I'm using Handbrake preset for all my encoding. By using a second Node, the Pathtranslators doesn't work for preset.
Message:
HandBrake has exited.
Tdarr ALERT: NO OUTPUT FILE PRODUCED: ...

**To Reproduce**
- Server and webUI running on a Linus Server (Regardless)
- A Seconde Node running on Windows
- by using for Exepmle: "--preset-import-file /mnt/mercury/transcode/preset/serie.json -Z "serie"" in the "Transcode options".

**Expected behavior**
An Access to the Pathtranslators mount points for the presets.

**Screenshots**
![image](https://user-images.githubusercontent.com/71213394/113511433-00ef1680-9560-11eb-88a4-82c39bc9906b.png)
![image](https://user-images.githubusercontent.com/71213394/113511441-0ea49c00-9560-11eb-9acf-4a79cef84849.png)
![image](https://user-images.githubusercontent.com/71213394/113511453-20863f00-9560-11eb-8e92-75cf71d0707e.png)

**Please provide the following information:**

 - OS: [Linux]
 - Browser [Chrome]
 - Version [2.00.07]

**Comment by HaveAGitGat** [comment]
Added in for 2.00.09, you can use it in  the pre-release in 30 mins or so.

https://tdarr.io/docs/pre-releases

**Comment by david-steg** [comment]
Wow thank you! but i'm not using Docker, I allocated a full VM for Tdarr in Proxmox. I will have to wait the normale release :)

**Comment by jaycedk** [comment]
Hmm you should be able to edit the Tdarr_Updater_Config.json in the config dir.
And then run the Tdarr_updater
See and read this [https://tdarr.io/docs/pre-releases](https://tdarr.io/docs/pre-releases)

**Comment by HaveAGitGat** [comment]
09 released
