### ISSUE TITLE
[Feature Request] Sort Queue by Alpha & by Folder

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#421]
**Describe the solution you'd like**
The ability to be able to sort the queue by Alphabetical order and by sub-folder/Alphabetical order.

Alphabetical by filename only
Folder A\File A
Folder B\File B
Folder A\File C

Alphabetical by filename only & sub-directory
Folder A\File A
Folder A\File C
Folder B\File B

**Describe alternatives you've considered**
N/A

**Comment by HaveAGitGat** [comment]
FYI I added this a couple of weeks ago. Will be in .10
