### ISSUE TITLE
Feature Request - Display a Node's Path (either media or transcode) from the server

### ISSUE THREAD

**Issue by Tharic99** [HaveAGitGat/Tdarr#422]
We talked on Discord a month ago and I wanted to make sure this one was captured.

Feature request - Is there a way to see a node's paths (either media or transcode) from the server? Just to make troubleshooting easier?

**Comment by HaveAGitGat** [comment]
`media or transcode`

What do you mean by this? The path translators?

**Comment by Tharic99** [comment]
Yes. When a node is connected to the server, but is unable to process files, it would be extremely helpful in troubleshooting the problem by being able to look on the server GUI to see what the path translators are or if any other "helpful" information could be displayed there.

**Comment by HaveAGitGat** [comment]
I've added the node config to the top of the node options for 09:

![image](https://user-images.githubusercontent.com/43864057/114140524-a7e10300-9910-11eb-82fa-f4002f6dcff5.png)

Would like to make it configurable in for .10.

**Comment by HaveAGitGat** [comment]
09 released
