### ISSUE TITLE
Tdarr_Server is not closing exiftool.exe after use.

### ISSUE THREAD

**Issue by jaycedk** [HaveAGitGat/Tdarr#423]
**Describe the bug**
Tdarr_Server is not closing exiftool.exe after use.
Resulting in xx exiftool.exe running 
Restarting Tdarr_Server clears them.

**To Reproduce**
Let Tdarr_Server run ;)

**Expected behavior**
For Tdarr_Server to close exiftool.exe after ended use.

**Screenshots**
Screenshots from before restart Tdarr_Server
![billede](https://user-images.githubusercontent.com/17232146/113710307-d332da80-96e3-11eb-9e66-fb5fbf5b879d.png)
![billede](https://user-images.githubusercontent.com/17232146/113710374-e34aba00-96e3-11eb-8b10-def8b3d1db5d.png)
![billede](https://user-images.githubusercontent.com/17232146/113710418-f493c680-96e3-11eb-8fa0-e7ed73364dbb.png)

Screenshots from after restart Tdarr_Server
![billede](https://user-images.githubusercontent.com/17232146/113710555-273dbf00-96e4-11eb-8f3c-72ec678cd267.png)

 - OS: Windows 10
 - Browser Firefox, Chrome and Edge
 - Version [2.00.09]

**Comment by HaveAGitGat** [comment]
Already fixed 👍. Re-download 09

**Comment by jaycedk** [comment]
Fantastic 👍 Will do 😄

**Comment by jaycedk** [comment]
@HaveAGitGat If you need a beta tester that runs on windows, just tell me.
I make my living i IT-Support, qurrent working from Home, do to Covid-19.
And have the time to test 😃

**Comment by HaveAGitGat** [comment]
Sorry had work but thanks. I noticed the RAM spiking up on my Pi so quickly fixed it. Been holding steady since but the Heap memory has been climbing up at 0.5MB per hour or so. Nothing urgent but will look into it when I have time

![image](https://user-images.githubusercontent.com/43864057/113823147-97008800-977e-11eb-8c76-45803c7d7ab0.png)

Thanks, will let you know. I've added a new holding section FYI:
https://github.com/HaveAGitGat/Tdarr/issues/424

**Comment by jaycedk** [comment]
Ok will redownload 2.00.09
And test it 😄 and have a look at the New Hold options.
Will post about Hold function in #424

**Comment by DankMemeGuy** [comment]
I think this issue is still happening. It works perfectly when health checkers are off, but after turning on the health checker to 1, server crashed within an hour

**Comment by jaycedk** [comment]
@DankMemeGuy If you delete Tdarr_Server, Tdarr_Node and 
Tdarr_Node_win32_x64_2.00.09, Tdarr_Server_win32_x64_2.00.9 in .staging dir
Then run Tdarr_updater.exe again.
That way you don't have left over files, that could mess up your install.

Do NOT delete the following directories 
config , logs and server.

**Comment by DankMemeGuy** [comment]
> @DankMemeGuy If you delete Tdarr_Server, Tdarr_Node and
> Tdarr_Node_win32_x64_2.00.09, Tdarr_Server_win32_x64_2.00.9 in .staging dir
> Then run Tdarr_updater.exe again.
> That way you don't have left over files, that could mess up your install.
> 
> Do NOT delete the following directories
> config , logs and server.

That's what I had done, but tdarr_server.exe still crashes after running for less than a day, but only while on health check enabled. 

Do you have health check enabled?

**Comment by jaycedk** [comment]
Yes but only quick health check.
Are you running Thorough health check ?

**Comment by DankMemeGuy** [comment]
I have just quick enabled, too.

Maybe my issue isn't related to this issue then, perhaps there's another bug. I'll enabled verbose logging and see what's happening

**Comment by HaveAGitGat** [comment]
@DankMemeGuy you can try running Tdarr_Server from a terminal instead of double clicking the exe. That way when it crashes you can see the error in the terminal. Btw what do you mean by crashes? The UI freezes or the application closes? You can check the memory graph on the stats tab to see if it's a RAM issue.

**Comment by DankMemeGuy** [comment]
I'll try that out. I have it running on my secondary PC so I don't check it often, but whenever I check it every 12 hours or so the Server.exe is closed while the Node remains running. It doesn't seem to be a RAM issue from the graph. I'll try the terminal window though.

**Comment by DankMemeGuy** [comment]
@HaveAGitGat this is the fatal error that crashes the server everytime:

[2021-04-16T01:36:27.774] [ERROR] Tdarr_Server - Error: Cannot find module 'C:/Users/Name/Desktop/Tdarr/Tdarr_Server/node_modules/exiftool-vendored'
Require stack:
- D:\snapshot\be\srcug\fileScanner\runExifToolSub.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\snapshot\be\srcug\fileScanner\runExifToolSub.js:1:5545)
    at Module._compile (internal/modules/cjs/loader.js:1198:30)
    at Module._compile (pkg/prelude/bootstrap.js:1327:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
internal/fs/utils.js:259
    throw err;
    ^

Error: EMFILE: too many open files, open 'C:\Users\Name\Desktop\Tdarr\Tdarr_Server\Tdarr_Server.exe'
    at Object.openSync (fs.js:461:3)
    at internal/bootstrap/pkg.js:35:17
    at internal/bootstrap/pkg.js:43:4
    at internal/bootstrap/pkg.js:44:2 {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: 'C:\\Users\\Name\\Desktop\\Tdarr\\Tdarr_Server\\Tdarr_Server.exe'
}

C:\Users\Name>

**Comment by DankMemeGuy** [comment]
This is the server memory: https://i.imgur.com/ZVU437F.png

there was plenty of overhead so it doesn't seem to be memory related

**Comment by HaveAGitGat** [comment]
@DankMemeGuy Seems to be a **Windows** bug with a dependency which causes it to crash when exiftool is run more than 8000 times or so during thorough health checks or transcodes (quick health checks don't use it, tested it and it's working fine). I've removed the dependency and implemented things myself and now it's working fine. Left it running overnight and it reached 100,000+ thorough health checks.

You can use it now by downloading the 2.00.10 pre-release:
https://tdarr.io/docs/pre-releases
Or:
https://tdarrs.s3.us-west-000.backblazeb2.com/versions/2.00.10/win32_x64/Tdarr_Node.zip
https://tdarrs.s3.us-west-000.backblazeb2.com/versions/2.00.10/win32_x64/Tdarr_Server.zip

**Comment by DankMemeGuy** [comment]
ahh will try that - thank you! I really appreciate the time you spent helping me out!

**Comment by DankMemeGuy** [comment]
Just wanted to say this solved the issue. Running this for 24 hours now without any issue

**Comment by HaveAGitGat** [comment]
@DankMemeGuy great, thanks for the update :).
