### ISSUE TITLE
Minimal File-Age Filter

### ISSUE THREAD

**Issue by wizzardking** [HaveAGitGat/Tdarr#424]
Hi

Is there any way to set a minimal age of a file to start the transcode?
It happens really often, that a file will be replaced several times in the first days of a release.

Example: I get a new 720p file, because this one was released first. 3 hours later, a 1080p file will be released and the file in my library will be replaced. One day later, there is a 1080p File with 5.1 Audio and the file in the library will be replaced again.
In this scenario, Tdarr would have transcoded the same episode 3 times in 1 day.

Is there any way to set a minimal file age of 7 days, which should be reached, before it starts to transcode?

**Comment by HaveAGitGat** [comment]
Hi, this has been a much requested but it's not possible to do with plugins so I've added a new feature for 2.00.09, the 'Hold' tab:
![image](https://user-images.githubusercontent.com/43864057/113822348-9e736180-977d-11eb-8fa4-0a89f3856ee3.png)

You can set the hold length in the library settings:
![image](https://user-images.githubusercontent.com/43864057/113822577-e3979380-977d-11eb-999d-88986178875e.png)

Still testing it.

**Comment by jaycedk** [comment]
I have testet this on windows.
And I can only say good job 👍 
I have testet on a test dir, where I introduced a new video.
Hold 5 min (300s) It set the video to hold 5 min :)
Deletet the video, video removed from que :)
Introduced the same video, New hold time :)
Waited 2 min, introduced same video with new name, Added to que now 2 videos in que, with diffrent hold time :)
Delete 1 Video from dir, removed from que. 2 Video still in que. ( As expected ) 
Re-added 1 Video, now in que after with new que time :)

Good work 👍

**Comment by HaveAGitGat** [comment]
Great, thanks for the update :)

**Comment by wizzardking** [comment]
Thank you very much for your fast support.
Better as on any paid service!

I'm running Tdarr as a Docker Container on a QNAP NAS and it seems also to work perfect there. Newly added Files will be shown in the Hold tab.

**Comment by HaveAGitGat** [comment]
Awesome, thanks for the update 👍

**Comment by HaveAGitGat** [comment]
09 released yesterday.
