### ISSUE TITLE
Allowing "Size" to be in different metrics

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#425]
**Is your feature request related to a problem? Please describe.**
I archive millions of TikTok videos that are often very small to begin with; 0.5-5 MB each. Right now files on the Transcode Queue show the Size column as GB only. So videos will have many 0.00s before the number, and then I have to do mental math to figure out how large it is in MB.

**Describe the solution you'd like**
Ability to have different sizing options, like MB and perhaps KB. I would rather see "11,000 MB and 2 MB" then seeing "11GB and 0.002 GB"

**Describe alternatives you've considered**
Automatically list the metric beside what is most relevant so it would show 11GB and the next video could show 5MB and the user doesn't need to select a metric to be tied to. 

**Additional context**

**Comment by HaveAGitGat** [comment]
I've added this is for .10 so it auto changes:
![image](https://user-images.githubusercontent.com/43864057/114349782-a14cc880-9b68-11eb-9f40-bd8b8440459b.png)
