### ISSUE TITLE
Bitrate Cutoff [Issue #244]

### ISSUE THREAD

**Issue by tommyjohn81** [HaveAGitGat/Tdarr#426]
https://github.com/HaveAGitGat/Tdarr/issues/244

Was this ever implemented? I see from the last discussion it was added to the to do but no information if it was completed or not. 
Thanks!

**Comment by HaveAGitGat** [comment]
A filter by bitrate plugin was added a while back:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_00td_filter_by_bitrate.js

![image](https://user-images.githubusercontent.com/43864057/152918486-7953b67c-f22a-4538-bdfa-805427bf2277.png)
