### ISSUE TITLE
Always stuck on the same spot when "extracting info"

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#430]
**Describe the bug**
No matter how many times I scan the library, it will always get stuck at:

`Extracting info:471407/471486 Scanner mem: 95.3MB/99.1MB
`

The terminal windows don't reveal anything pertaining to this. These are the logs from the Server that might be pertaining to this:

[2021-04-15T06:12:40.346] [ERROR] Tdarr_Server - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (D:\snapshot\be\node_modules\threads\dist\master\spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by HaveAGitGat** [comment]
>2.00.00

Please make sure you are using the latest version (2.00.09 [11th April 2021])

>10000ms

The timeout was increased to 60000ms for 2.00.09 so try that first. Thanks. Given your other posts I think you are still using quite an old version of the .09 pre-release.

https://tdarr.io/docs/installation

Reopen if needed.

**Comment by HaveAGitGat** [comment]
Use these direct links:
https://tdarrs.s3.us-west-000.backblazeb2.com/versions/2.00.09/win32_x64/Tdarr_Node.zip
https://tdarrs.s3.us-west-000.backblazeb2.com/versions/2.00.09/win32_x64/Tdarr_Server.zip

**Comment by DankMemeGuy** [comment]
I was using 2.00.09 but I'll try with those links, thanks!
