### ISSUE TITLE
[Feature Request] Copying queue

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#431]
**Is your feature request related to a problem? Please describe.**
Right now the staging works like a 1 person lineup. The files get queued and 1 file gets copied while the rest "await copy." this is causing problems when the queue just builds up, so instead of having 3+ workers, I have to have 2 or less since that's roughly the speed that the copying process works. Anymore than 2 and the staging block gets full.

**Describe the solution you'd like**
If possible, close this if not, but it would be nice to have the ability to copy multiple videos at once. Essentially going from a 1 lineup queue into a multiple lineup. This would allow the staging queue to speed up, while also allowing multiple workers. I'd understand that a limit exists with the mechanical drives, but I think letting the HDD do the multiple copying at once would be faster than Tdarr making it a 1-person lineup

**Describe alternatives you've considered**
I think having too many lineups would make a bottleneck, but not all HDDs are the same, so it could be nice to let the user decide how many files Tdarr lets copy at once before sending it to a "copy await" status.

**Comment by HaveAGitGat** [comment]
Doing multiple copies on an HDD is slower than doing one at a time as the HDD read/write head has to move around more often. To solve your problem you could put the transcode cache on the same drive as your library files. That way an instant move will be done instead of a copy.

**Comment by HaveAGitGat** [comment]
There is an argument for this if your library is split over several drives. I'll add it on the backlog as it's not super urgent.

**Comment by ajax-lives** [comment]
> There is an argument for this if your library is split over several drives. I'll add it on the backlog as it's not super urgent.

I run a Mergerfs pool, so this would be huge for me - as the file I'm transcoding is likely to not be on the drive that it'll use as temp.
