### ISSUE TITLE
Error: "UnhandledPromiseRejectionWarning"

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#432]
**Describe the bug**
The error (below) keeps happening. It doesn't seem to crash Tdarr, but it's happening very often. I'm not sure if it's causing issues somewhere else in Tdarr that I haven't realized yet.

**To Reproduce**
Just run the program, i guess?

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 2.00.00] 2.0.10

**Additional context**

```
Tdarr_WebUI running at http://localhost:8265
(node:16880) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, stat 'C:\Users\Username\Desktop\Tdarr\logs\Tdarr_Server_Log.txt.3'
(Use `Tdarr_Server --trace-warnings ...` to show where the warning was created)
(node:16880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by HaveAGitGat** [comment]
I've done a fair few updates since this issue was posted so please reopen if you still encounter the error on 2.00.12 (just released). Thanks.
