### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#433]
**Describe the bug**
When you have "library alternation" enabled, and you sort by largest (or whatever else), the entire queue will still show just the biggest, and not alternating for other libraries. Thus, the processing occurs just for the largest to smallest, but not respecting the library alternating. 

I would imagine that having the "library alternating" enabled would force the biggest (or whatever option is selected) to alternative the processing from each of the libraries that are enabled.

For example, if Lib A has 10 files, each file is 100-200GB, and Lib 2 has 10 files, each file is 10-100MB; the processing queue should be:

Lib A: 200GB
Lib B: 100MB
Lib A: 199GB
Lib B: 99MB
etc...

instead right now it is:
Lib A: 200GB
Lib A: 199GB
Lib B: 100MB
Lib B: 99MB

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by HaveAGitGat** [comment]
I have not been able to recreate this issue recently. Please reopen if needed, thanks.
