### ISSUE TITLE
Trascode location depending on file size

### ISSUE THREAD

**Issue by yekul** [HaveAGitGat/Tdarr#435]
Note: Primary use is to encode files downloaded BEFORE they hit my library. Tdarr basically sits in the middle catching new downloads and converting everything to HEVC. 

**Is your feature request related to a problem? Please describe.**
I typically transcode to the RAM to save some disk wear and tear (and just generally for performance), however larger movies (20+GB) will run out of RAM to transcode to and fail. This only happens over a certain size, which of course will change depending on what else i'm running on the server (but is usually about 16GB and above). It is no problem for TV episodes as I never grab files that big, however it happens a lot for movies which tend to be much larger even in HEVC. 

**Describe the solution you'd like**
An option to specify the transcoding directory based on file size. Perhaps have something like /ram and /temp. User specifiable file size which lets you opt for one or the other once files reach a certain size. 

**Describe alternatives you've considered**
Current alternative is manually passing these files through by temporarily disabling the transcoding plugins (usually just audio as video is HEVC for most movie downloads). Alternative could be if a file fails because it runs out of space, there is a fall back location it will also try.

**Comment by HaveAGitGat** [comment]
The size of the new file depends on the transcode settings, not on the size of the input file, so doing this wouldn't help in a lot of cases where the user has input the wrong settings.

It's best just to use a cheap ssd, can get a few hundred GB for $20 these days.
