### ISSUE TITLE
Add option to "Accept All" in staging section

### ISSUE THREAD

**Issue by Starker3** [HaveAGitGat/Tdarr#438]
**Is your feature request related to a problem? Please describe.**
At the moment I don't have Tdarr automatically accept trasncoded items in the Cache folder because I've had some random issues where the transcoded item wasn't completed (Could be network disconnect or other random issues)
Most of the time though all of the files are fine and I then just click the accept button on all the files in the staging section.

**Describe the solution you'd like**
It would be great to have a button for the staging section to click "Accept All" for the cache files in the staging section.

**Describe alternatives you've considered**
I've considered enabling automatically accept transcodes but it forced me to have to re-rip some files that were only partially transcoded and subsequently caused some of the files in the final library to effectively be incomplete or corrupted.

**Additional context**
Refs #408

**Comment by HaveAGitGat** [comment]
Thanks, added all buttons for 2.00.12 

![image](https://user-images.githubusercontent.com/43864057/144013137-8e95db0d-d2cc-419f-9532-5b70204a4150.png)
