### ISSUE TITLE
How to use ffmpeg?

### ISSUE THREAD

**Issue by Nosirus** [HaveAGitGat/Tdarr#44]
I'm new to ffmpeg and can't use the basic commands in Tdarr.

I would like to encode in x265 with crf and fdk_aaa all audio + subtile

which syntax is used?

**Comment by HaveAGitGat** [comment]
Hi I'd recommend looking at some ffmpeg guides like these:

https://www.ostechnix.com/20-ffmpeg-commands-beginners/
https://opensource.com/article/17/6/ffmpeg-convert-media-file-formats

In Tdarr, for ffmpeg the input and output arguments are separated by a comma. For example

> -sn,  -s 50x50

**Comment by HaveAGitGat** [comment]
Please feel free to re-open if you have any more questions
