### ISSUE TITLE
Limit Node to specific libraries

### ISSUE THREAD

**Issue by jacobdhendrix** [HaveAGitGat/Tdarr#440]
**Is your feature request related to a problem? Please describe.**
Some of my nodes are slower than others. Rather than a slower node spending 95 hours on a large movie, I'd like to limit it to working some older TV series that only take around 1 hour per episode and let the faster nodes handle the large movies.

**Describe the solution you'd like**
I would like a toggle on the Node options screen to select either All Libraries or a specific library.

**Describe alternatives you've considered**
I am currently doing this manually by sorting the transcode queue right before the slower nodes start another file.

**Additional context**
I love this software. It has saved a lot of space for me and this feature would mean I need to spend less time sorting and just let it do its thing.

**Comment by simbasamba** [comment]
+1 Same here. That would be great because I have a server without a GPU that runs 24/7 but a desktop with GPU that's turned on only during the day.

**Comment by villieb** [comment]
I'd like to also see this feature...

**Comment by HaveAGitGat** [comment]
This will be available in next version (2.00.20)

![image](https://user-images.githubusercontent.com/43864057/220566051-50431ee7-bd6f-4c84-be6b-4ba3292c7dab.png)

Available to try now on docker x64

```
docker pull haveagitgat/tdarr_acc:dev_2.00.20_2023_02_22T09_18_17z
docker pull haveagitgat/tdarr_node_acc:dev_2.00.20_2023_02_22T09_18_17z
```

**Comment by liam8888999** [comment]
is there any indication to when the next version may be released

**Comment by HaveAGitGat** [comment]
Trying to fix this issue so probably after that: https://discord.com/channels/623392507828371476/1074635670192148510

**Comment by HaveAGitGat** [comment]
2.00.20 released
