### ISSUE TITLE
Tdarr_Server leaves zombie ps processes on Linux

### ISSUE THREAD

**Issue by slim186** [HaveAGitGat/Tdarr#441]
**Describe the bug**
After running for a while, Tdarr_Server will leave multiple unkillable zombie "ps -p ####,1" processes in the process list.  Only way to get rid of them is to restart Tdarr_Server.

**To Reproduce**
Leave Tdarr_Server running for a while.  I've noticed it happen within 5 minutes or sometimes it takes days.

**Expected behavior**
ps processes end on their own and get cleaned up.

**Please provide the following information:**
 - OS: Debian Buster (no Docker)
 - Browser: Firefox
 - Version: 2.00.09

**Additional context**
Seems to have shown up in a recent release, don't remember it happening with 06 or 07.

**Comment by ajw107** [comment]
Yeah, I noticed this for the Tdarr_Node too, after closing the process I also have to run a `sudo killall -I -r tdarr` (this is on a machine that is just running as a node).

**Comment by jpartain89** [comment]
Same here, its not fun ssh into my ubuntu machine and seeing "3,235 zombie processes" on the MOTD... (left the encoding running over this past vacation weekend)

Is there a plan to fix this?

**Comment by tyhawk** [comment]
Same here, 2.00.09, lots of defunct `ps` processes. I'm running openSUSE Leap 15.3, but had the same issue on 15.2.

Restarting the Tdarr server service gets rid of the processes as a workaround, but it is an annoying bug. I run my nodes within a podman container and haven't seen the same behaviour in there so far.

**Comment by Fish2** [comment]
im also getting a lot ubuntu 20.04 docker

**Comment by HaveAGitGat** [comment]
I haven't had any reports of this since 2.00.10 (August) but please reopen if needed.
