### ISSUE TITLE
The new transcode arguments were the exact same as the last ones

### ISSUE THREAD

**Issue by wizzardking** [HaveAGitGat/Tdarr#442]
Hi

I just created my first custom plugin with the plugin creator.

This Plugin should downscale all Videos in 1080p or higher resolution to 720p with libx265 codec in ffmpeg. Audio and subtitles should be kept original.

The transcode works as is should, but at the end I got the error, that the transcode would stuck in a loop.
Because I choose as a filter by resolution "1080p,4KUHD,DCI4K,8KUHD,Other", this doesn't make much sense to me. After the transcode, the file is 720P, so it shouldn't be fetched again and can't go in to a loop.

Error:
The new transcode arguments were the exact same as the last ones meaning

the file/worker would most likely be stuck in an infinite transcode loop if not stopped.

Last arguments: <io>-c:v libx265 -crf 23 -vf scale=-1:720 -c:a copy -c:s copy
New arguments: <io>-c:v libx265 -crf 23 -vf scale=-1:720 -c:a copy -c:s copy

**Comment by ajw107** [comment]
I'm not an expert, but it sounds like you've got reQueueAfter set to true in the response struct.  Try setting it to false.

**Comment by wizzardking** [comment]
Thank you. That was the solution.
