### ISSUE TITLE
Max Width failing check

### ISSUE THREAD

**Issue by dsrtusr88** [HaveAGitGat/Tdarr#444]
**Describe the bug**
Video above 4k failing to transcode.

**To Reproduce**
Steps to reproduce the behavior:  Happens on all files that are 5120Wx2880p

**Expected behavior**
Normal transcode.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

NodeID: zany-zebu

Command:

ffmpeg -c:v h264_cuvid -i /path/movie.2880p.mp4 -map 0 -c:v hevc_nvenc -rc:v vbr_hq -cq:v 19 -b:v 21407k -minrate 14984k -maxrate 27829k -bufsize 42814k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le -bf 5 /path/movie.2880p-TdarrCacheFile-Xvjd0e_rB.mkv

Last 200 lines of CLI log:

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers

built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

configuration: --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --nvccflags='-gencode arch=compute_52,code=sm_52 -O2' --disable-debug --disable-doc --disable-ffplay --disable-static --enable-cuda-nvcc --enable-cuda-sdk --enable-cuvid --enable-ffprobe --enable-gpl --enable-libaom --enable-libass --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-nonfree --enable-nvdec --enable-nvenc --enable-openssl --enable-shared --enable-small --enable-stripping --enable-vaapi --enable-vdpau --enable-version3

libavutil 56. 31.100 / 56. 31.100

libavcodec 58. 54.100 / 58. 54.100

libavformat 58. 29.100 / 58. 29.100

libavdevice 58. 8.100 / 58. 8.100

libavfilter 7. 57.100 / 7. 57.100

libswscale 5. 5.100 / 5. 5.100

libswresample 3. 5.100 / 3. 5.100

libpostproc 55. 5.100 / 55. 5.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/path/movie.2880p.mp4':

Metadata:

major_brand : mp42

minor_version :

0

compatible_brands:

mp42mp41

creation_time : 2020-09-10T14:30:22.000000Z

Duration: 00:41:50.63, start: 0.000000, bitrate: 44894 kb/s

Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 5120x2700, 44569 kb/s, 60 fps, 60 tbr, 60k tbn, 120 tbc (default)

Metadata:

creation_time : 2020-09-10T14:30:22.000000Z

handler_name : ?Mainconcept Video Media Handler

encoder : AVC Coding

Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)

Metadata:

creation_time : 2020-09-10T14:30:22.000000Z

handler_name : #Mainconcept MP4 Sound Media Handler

[h264_cuvid @ 0x557c9e68f0c0] Video width 5120 not within range from 48 to 4096

Stream mapping:

Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1 (copy)

Error while opening decoder for input stream #0:0 : Invalid argument

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by supersnellehenk** [comment]
This isn't a bug with Tdarr, nor ffmpeg. The Nvdec part of your nvidia card doesn't do higher than 4K decoding. You'd have to resort to CPU decoding and GPU encoding, which should work.
