### ISSUE TITLE
Locks up scanning DB

### ISSUE THREAD

**Issue by russdog75** [HaveAGitGat/Tdarr#445]
Server hangs on startup.  

Running tdarr on Ubuntu 20.04.  Everything was working fine until I had to reboot the server and now every time I start up the server it hangs while scanning the DB.  The number it hangs at is different every time.  Is there a way to force a rebuild of the database?

![image](https://user-images.githubusercontent.com/52375836/119684566-9bf2c700-be12-11eb-8a32-c5787c6af3cf.png)

**Comment by russdog75** [comment]
Log file is just repeated entries like this:

[2021-05-26T11:09:21.088] [WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI.

**Comment by HaveAGitGat** [comment]
There's no way to rebuild but I'd recommend trying 2.00.12. Deleting these folders in 'server\Tdarr\DB2' might help:
![image](https://user-images.githubusercontent.com/43864057/145769843-fddf4554-84ab-4386-85d7-070de581a2a0.png)
