### ISSUE TITLE
Pagination on Queues & History

### ISSUE THREAD

**Issue by ConfusedTA** [HaveAGitGat/Tdarr#447]
**Is your feature request related to a problem? Please describe.**
I would like to see what is going on with my Hold, Queue, Completed etc files, but it is difficult to do so when there are large numbers.

**Describe the solution you'd like**
The current "Items" text box allows limiting of number of currently visible items, and I like being able to easily adjust this (without it being hidden away in a Settings page), but the ability to scroll through the Queue etc in pages of X would be very beneficial.

**Describe alternatives you've considered**
 The only option at the moment appears to be to increase the number of items, refresh the page, and wait whilst it loads, and hope that you don't run out of memory/processor whilst it fetches potentially thousands of items.

**Additional context**
None that I can think of!

BTW, thanks very much for writing this!

**Comment by HaveAGitGat** [comment]
Thanks for the info :)

Moving under this:
https://github.com/HaveAGitGat/Tdarr/issues/115
