### ISSUE TITLE
Windows update

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#45]
You mentioned in a thread to me a number of weeks ago that you were planning to release a substancial update for the windows version. Any idea when that will be?

**Comment by HaveAGitGat** [comment]
Hi martin sorry got side tracked because the majority of people use Tdarr in Docker which I've been upating. I'll update the Windows, Linux and macOS packages later today.

**Comment by HaveAGitGat** [comment]
The updated Windows package is now available
