### ISSUE TITLE
Multiple PathTranslators Fails (Node)

### ISSUE THREAD

**Issue by CyberBlaed** [HaveAGitGat/Tdarr#450]
**Describe the bug**
When using a single "Server and node" translation, its fine, and works a treat, adding a second one, causes the application to bug out and wipe the config file.
I have seen other posts here that others manage to use multiple paths, so it may be a mac specific issue to how it handles it?

**To Reproduce**
```
 "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
```
Will work fine, but the following will not.
```
  "pathTranslators": [
    {
      "server": "/mnt/server/folder",
      "node": "/Volumes/Drive/Folder"
    }
    {
      "server": "/mnt/server/folder/folder",
      "node": "/Volumes/Disk/Folder"
    }
```

**Expected behavior**
More than one folder being able to be mapped/translated.

**Screenshots**
[Terminal one](https://i.imgur.com/oIESf6r.jpg)

**Please provide the following information:**
- Config files  
```
{
  "nodeID": "VENUS",
  "nodeIP": "10.0.0.199",
  "nodePort": "8267",
  "serverIP": "10.0.0.110",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/mnt/shares/MERCURY_SvrSpace/",
      "node": "/Volumes/MERCURY_SvrSpace/"
    }
    {
      "server": "/mnt/RAMDISK/",
      "node": "/Volumes/RAMDISK/"
    },
    {
      "server": "/mnt/input/",
      "node": "/Volumes/Multimedia/Video/Input"
    },
    {
      "server": "/mnt/output/",
      "node": "/Volumes/Multimedia/Video/Output"
    },
  ]
}
```

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error 
fails due to bad mapping of my 'ramdisk' page translation

 - OS: [Server: Unraid - Docker / Node: Mac Big Sur 11.04] (error is on/from my node)
 - Browser [Firefox, though not a browser issue at all.]
 - Version [e.g. 2.00.09]

**Additional context**
its odd, if one translation is set, it boots and is fine, but errors on transcode due to not all the mapping of folders.
so by adding the 2nd or 3rd folders, the app just bugs out, wipes the config file and then bugs out claiming 0.0.0.0 is not reachable.

Sadly, symlinks on mac cannot be done to emulate folder structure as the '/' root cannot be written to without serious consequences, and I don't wish to do that.

**Comment by jakejones48** [comment]
Looks like you have misplaced a comma. Need commas between the two brackets"} { "and not one at the ending"} "

Hope that made sense, something like below:

  "pathTranslators": [
    {
      "server": "/mnt/shares/MERCURY_SvrSpace/",
      "node": "/Volumes/MERCURY_SvrSpace/"
    }, 
    {
      "server": "/mnt/RAMDISK/",
      "node": "/Volumes/RAMDISK/"
    },
    {
      "server": "/mnt/input/",
      "node": "/Volumes/Multimedia/Video/Input"
    },
    {
      "server": "/mnt/output/",
      "node": "/Volumes/Multimedia/Video/Output"
    }
  ]

**Comment by HaveAGitGat** [comment]
Yes you are missing a comma:

![image](https://user-images.githubusercontent.com/43864057/128462135-78887096-bf8c-41ee-9335-8d44e686d501.png)
