### ISSUE TITLE
Plugin error! TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by tyhawk** [HaveAGitGat/Tdarr#451]
I'm seeing the same error show up with multiple (community) plugins and I don't know what is causing it.
```
Plugin error! TypeError: Cannot read property 'substring' of undefined
```
 - OS: Linux / openSUSE
 - Browser: Firefox
 - Version: 2.00.09

Examples:
```
Keep Preffered Audio - Pre-processing☒Plugin error! TypeError: Cannot read property 'substring' of undefined 
```
The plugin that seems to cause this error the most is Keep Preffered Audio.

**Comment by supersnellehenk** [comment]
This issue should be over on https://github.com/HaveAGitGat/Tdarr_Plugins/issues, but regardless, the issue comes from that plugin being written for V1 and it hasn't been rewritten for V2 (as far as I can tell).

**Comment by tyhawk** [comment]
Clear. I'll close this issue and hope these plugins get rewritten to v2 soon.
