### ISSUE TITLE
Add custom parameters or add -extra_hw_frames 3 to health check

### ISSUE THREAD

**Issue by Fribb** [HaveAGitGat/Tdarr#454]
**Is your feature request related to a problem? Please describe.**
Trying to run a GPU health check errors out with the message `No decoder surfaces left`. This seems to be a known issue according to [this](https://trac.ffmpeg.org/ticket/7562) ticket on ffmpeg. health check on the CPU works without getting that error but will require the CPU to run those health checks.

OS: Unraid
Tdarr Version: 2.00.09
Nvidia Drivers: 465.31

**Describe the solution you'd like**
It would be great to have something like "additional" parameters for the pre-defined commands like a Health check. This would enable the user to quickly add certain "fixes" like the `-extra_hw_frames 3` workaround (as you can see in the ticket above) or even the Max Muxing size if a plugin should not have it directly.

**Describe alternatives you've considered**
as an alternative, this could be integrated as one of the default parameters in the health check itself.

**Additional context**

**Comment by Fish2** [comment]
@HaveAGitGat any news on getting "-extra_hw_frames 3" added are a option nomads to the health check selections ?

**Comment by HaveAGitGat** [comment]
Added an option for this in the next version .13 so you can add extra args:

![image](https://user-images.githubusercontent.com/43864057/147418455-0061a214-64fc-4554-b7ab-3c26a6e543e8.png)

**Comment by Fish2** [comment]
@HaveAGitGat just tested getting a few error it ideally needs to before the input file on the gpu one or you can get this 

`Codec AVOption extra_hw_frames (Number of extra hardware frames to allocate for the user) specified for output file`

**Comment by Fribb** [comment]
> @HaveAGitGat just tested getting a few error it ideally needs to before the input file on the gpu one or you can get this
> 
> `Codec AVOption extra_hw_frames (Number of extra hardware frames to allocate for the user) specified for output file`

After getting the new Update today I can confirm that this is running into the described error.

**Comment by Fish2** [comment]
any news for a fix on this ?

**Comment by HaveAGitGat** [comment]
Sorry missed this. Will add it to the next version.

**Comment by HaveAGitGat** [comment]
Added to .15 so you can set extra input/output args:
![image](https://user-images.githubusercontent.com/43864057/154901084-03fc0b26-bc32-4b46-9cc9-13511930674a.png)

You can use it in the linux/amd64 dev container in 15 mins or so:
`docker pull haveagitgat/tdarr_acc:dev`
