### ISSUE TITLE
libx265 HDR encoding command truncated

### ISSUE THREAD

**Issue by qiqian** [HaveAGitGat/Tdarr#456]
The following is the response.preset generated by my plugin, I know this is correct as it is displayed in the tdarr panel

, -movflags use_metadata_tags -map 0:0 -c:0 libx265 -crf 20 -preset slow -x265-params hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display="G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,20)":max-cll=0,0:vbv-maxrate=53962:vbv-bufsize=71950 -pix_fmt yuv420p10le -map 0:15 -c:1 copy -metadata:s:1 language=eng -map 0:16 -c:2 copy -metadata:s:2 language=eng -map 0:17 -c:3 copy -metadata:s:3 language=chi -map 0:2 -c:4 copy -metadata:s:4 title="英语 Dolby Atmos" -metadata:s:4 language=eng -map 0:4 -c:5 copy -disposition:5 0 -metadata:s:5 title="英语 Dolby Digital" -metadata:s:5 language=eng -map 0:3 -c:6 copy -disposition:6 0 -metadata:s:6 title="DTS-HD Master Audio" -disposition:1 0 -disposition:3 default -max_muxing_queue_size 9999

But the task fails with only video channel extracted, audio & subtitles are missing, I looked into the tdarr node's command log, and find 

NodeID: Nuc
Command:
ffmpeg -i /media/TV/Game.Of.Thrones/Game.of.Thrones.S05E01.The.Wars.to.Come.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv -movflags use_metadata_tags -map 0:0 -c:0 libx265 -crf 20 -preset slow -x265-params hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display= G(8500 /temp/Game.of.Thrones.S05E01.The.Wars.to.Come.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT-TdarrCacheFile-vr-wqLjMs.mkv

the hdr parameter is truncated to G(8500, and all the following channel mapping are lost, I thinks this causes the final video file lost audio channel and subtitle channel

**Comment by qiqian** [comment]
my plugin is at 
https://github.com/qiqian/tdarr_plex_optimizer

**Comment by jortan** [comment]
Seems like commas inside the ffmpeg preset returned by the plugin are being interpreted as a delimiter.  Everything after a comma is discarded.

This is also blocks plugin being able to crop and resize in the same operation (needs something like crop=3840:1600:0:280,scale=-1:1920) and plugins using multiple filters, described here:
 
https://www.reddit.com/r/Tdarr/comments/hlzolk/plugin_with_multiple_filters_comma_gets_parsed_by

**Comment by HaveAGitGat** [comment]
```
When using FFmpeg, you need to separate the input and output parameters with <io>. FFmpeg Examples:

-r 1<io>-r 24
<io>-sn -c:v copy -c:a copy
<io>-c:v lib265 -crf 23 -ac 6 -c:a aac -preset veryfast
<io>-map 0 -c copy -c:v libx265 -c:a aac
-c:v h264_cuvid<io>-c:v hevc_nvenc -preset slow -c:a copy
```
