### ISSUE TITLE
[Bug+Workaround - 2.00.10 (Docker) and 2.00.09 ARM] Files only partially copied to Output Folder

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#457]
**EDIT: This is a bug of 2.00.09 and 2.00.10 (docker) in ARM.**

**Describe the bug**
I have noticed an odd behavior in my instance. For ~~_some_ videos, usually HEVC DTS-HD 4K ones,~~ the remux/transcode process flows correctly, but the output file has only a few MBs of size instead of the GBs it was supposed to have.

**To Reproduce**
~~Transcode a HEVC DTS-HD 4K file using any plugin, e.g. Tdarr_Plugin_a9hd_FFMPEG_Transcode_Specific_Audio_Stream_Codecs, but the~~ issue is not related to the plugin activity, we just want it to go to the Output Folder, which should be a CIFS or NFS remote mount.
**EDIT: This is a bug for ARM distributions in Tdarr 2.00.09 and also 2.00.10 (Docker).** This behavior does not happen in 2.00.08.

**Expected behavior**
The entire content of the tmp file should be copied to the Output Folder after "accepting" the successful transcode.
**Note: this issue only happens for these files when the output folder is in a CIFS or NFS mount.** My entire library, with all sorts of codecs and resolutions, have been working perfectly for many months, copying to a remote share.
I feel I cannot "trust" Tdarr anymore, since I may end up importing a partial file.

**Screenshots**
Temp file:
![image](https://user-images.githubusercontent.com/35738729/123329488-3e39c380-d513-11eb-8195-1ca10b8274f7.png)

Output file:
![image](https://user-images.githubusercontent.com/35738729/123329552-51e52a00-d513-11eb-8e42-f75f4da8acc3.png)

**Please provide the following information:**
- Config:
[Tdarr_Config.zip](https://github.com/HaveAGitGat/Tdarr/files/6712041/Tdarr_Config.zip)

- Log files:
[Tdarr_logs.zip](https://github.com/HaveAGitGat/Tdarr/files/6712051/Tdarr_logs.zip)

-Worker error: No errors found.

 - OS: Raspberry PI OS arm32 and arm64
 - Browser: Chrome
 - Version: 2.00.09 or 2.00.10

Note 1: I'm able to manually copy the "failed" item via the File Explorer with no issues.
Note 2: Tdarr has been working for other media/codecs for resolutions including 4K and with MUCH larger files (e.g. 50GB+) with no problems. 

EDIT 1: Note 3: Issue does not happen in 2.00.08.

EDIT 2: Issue also appears in 2.00.10. @HaveAGitGat, I believe you should add a file size check to make sure the cache file has the same size of the output file and only then do the final renaming and deleting the cache file. What I'm seeing in 2.00.10 (docker) is that the files are only partially copied (a few hundred MBs), renamed to the final name (without "TdarrCachexxxxx") ~~and the cache file staying in the transcode folder~~ . Tdarr shows "Transcode successful" incorrectly. If one is replacing the original file, this leads to tremendous loss of data. If the file size check is not successful, you should assume the copy has failed and it should remain in the staging area to retry the copy.

EDIT 3: The files get deleted from the cache and I have a reproducible example. A movie is consistently getting 5GB of output in the cache and the copy "succeeds" after copying 1GB of data, every time. Cache file is deleted and movie goes to Transcode Successful.

----------------------
ISSUE UPDATE:
I noticed that the move/copy method to the output folder is different depending on the folder/drive you copy to.
e.g. transcode folder is at ~/tmp/Transcode:

a. Output is a network drive in /mnt --> FAIL
b. Output is a local folder in ~/tmp/Output --> FAIL
**c. Output is a subfolder of the transcode folder e.g. ~/tmp/Transcode/Tdarr_out --> SUCCESS! (only a MV operation seems to take place)**
d. Output is a network drive mounted in a subfolder of the transcode folder e.g. ~/tmp/Transcode/Tdarr (pointing to /mnt/.../Tdarr) --> FAIL

-----------------------
WORKAROUND UPDATE
Since the only place I can safely store the output files is a local subfolder inside the transcode folder, I have done so, and the copy/remove operation to the network drive (to e.g. /mnt/.../Tdarr) is done via a shell script. Here's the code:
https://pastebin.com/mcEMD4Lb

**Comment by wsegatto** [comment]
I have faced the same issue for 1080p files in x264 as well, so it's definitely not related to any codec. Notice in the following example the strange output sizes for a season of 1080p videos that had more or less the same size:

![image](https://user-images.githubusercontent.com/35738729/123491684-b07ed680-d5ed-11eb-98b5-e72d4a83b532.png)

I have downgraded Tdarr to 2.00.08 and the issue no longer happens.
Therefore, maybe something you changed in 2.00.09 (copy method?) broke the copy to CIFS and NFS mounts.
_2.00.09 Changelog:
- Tdarr Server on linux_arm will attempt to move files before falling back to copying (same as other platforms)._

**Comment by cooper7692** [comment]
what rpi are you using? my rpi4 does not work at all

**Comment by wsegatto** [comment]
> what rpi are you using? my rpi4 does not work at all

RPI4. I am managing to get it working somehow, however the issue persists some times. If you have a specific issue not related to the actual copy to output folder, maybe you should open another issue or reach out in Discord.

**Comment by HaveAGitGat** [comment]
I've updated the .10 container so it now does a byte size comparison to make sure the full file is moved/copied. Seems there is a bug with a dependency in some situations so it doesn't throw an error when it fails. So Tdarr should now catch that.

**Comment by HaveAGitGat** [comment]
@wsegatto please reopen if needed but I believe this was fixed in the official release version of .10, (I think you were using the pre-release at the time).
