### ISSUE TITLE
Accept delimited text file of files to transcode

### ISSUE THREAD

**Issue by douginoz** [HaveAGitGat/Tdarr#458]
**Is your feature request related to a problem? Please describe.**
I've got a library of >4000 movies, of which many, but not most, need transcoding.  There are a lot (1000 or so) that I don't want to transcode.  I can't practically move out a subset of my /Movies folder as that would disrupt Plex etc.  I can't practically select each movie folder individually or as a group either

**Describe the solution you'd like**
Accept a text file containing a list of fully qualified (drive, path, and filename) video files to be added to the queue.  Perhaps this could be an option/alternative when creating a new library; instead of selecting the source via navigation, have a field that allows you to select a text file for processing.  It could be as simple a file as:

c:\movies\123 (1955)\movieblah.mkv
c:\movies\star wars 93 (2025)\movieblech.mkv
etc.

**Describe alternatives you've considered**
manually navigating to each movie folder that I want transcoded; also creating hard links, but with >1000 links to create, it's awesomely painful.

**Additional context**
I'm able to generate this text file fairly simply via ncdu and sorting subfolders by size, saving the list as a text file, and editing it to remove those movies I definitely don't want transcoded.  The result is a list of folders/movies that remain and can be transcoded.

**Comment by jortan** [comment]
> via ncdu and sorting subfolders by size,

Given file size is your criteria for transcoding, there are a number of Tdarr plugins that will only process files over a given bitrate.  Might that be a better approach?

**Comment by HaveAGitGat** [comment]
Yeah the whole point of plugins is so you can do stuff like this. You could create a simple plugin which only allows processing of files in your list. For example, here is a plugin which does this based on this plugin: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Tdarr_Plugin_bbbb_Filter_Example.js:

```
module.exports.details = function details() {
    return {
        id: 'Tdarr_Plugin_bbbb_Filter_Example',
        Stage: 'Pre-processing',
        Name: 'Filter files',
        Type: 'Video',
        Operation: 'Filter',
        Description: 'This plugin only processed certain files \n\n',
        Version: '1.00',
        Link: '',
        Tags: '',
    };
};

module.exports.plugin = function plugin(file) {
    // Must return this object at some point in the function else plugin will fail.

    const response = {
        processFile: true,
        infoLog: '',
    };

    const allowedFiles = [
        'c:/movies/123 (1955)/movieblah.mkv',
        'c:/movies/star wars 93 (2025)/movieblech.mkv',
    ]

    if (allowedFiles.includes(file.file)) {
        response.processFile = true;
        response.infoLog += `File is allowed.`;
    } else {
        response.processFile = false;
        response.infoLog += `Filter preventing processing.`;
    }

    return response;
};
```

Just added the rest of your files to the `allowedFiles` array. Hope that helps.
