### ISSUE TITLE
"Settings" page is blank (just a white screen) when clicking on "libraries" button. after update to Windows Alpha

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#46]
When you goto the "libraries" tab the screen just comes up blank.

I thought it might just be some aberrant cache files left over from the previous version but have tried this in chrome, firefox and edge to no avail. Tried clearing cache etc. Just a blank screen on page
http://localhost:8265/settings/

**Comment by HaveAGitGat** [comment]
Sorry a huge amount has changed since your last version so I’d recommend going on the ‘Dev’ tab and then click ‘Clear database’ and restart Tdarr.  Your files won’t be deleted but you’ll need to re-add your libraries again.

**Comment by martinkeat** [comment]
OK. I have access. Thanks for that. However, I cant seem to see the options for setting the transcoding type? Can you point me to the right place....or the instruction manual. LOL

**Comment by HaveAGitGat** [comment]
Hi @martinkeat, are you able to see the 'i' information button at the top tof the libraries page?:

![image](https://user-images.githubusercontent.com/43864057/67433533-35774880-f5e0-11e9-8030-ae9f819b3f6b.png)

It contains help on how to set up Tdarr depending on what you're wanting to do. For example:

![image](https://user-images.githubusercontent.com/43864057/67433626-5b9ce880-f5e0-11e9-88b0-f51eb0c3c3d8.png)

This will convert files which aren't in h264 into h264 using HandBrake's  Very Fast 1080p30 preset with mkv as the output container.

Hope this helps.

**Comment by martinkeat** [comment]
Yeah except it is h265 I want to convert into, Remember you assisted me with changing this in the pre-alpha version a few weeks ago.

**Comment by HaveAGitGat** [comment]
Here's the closed issue which willl help:

https://github.com/HaveAGitGat/Tdarr/issues/5

So put the following in the preset box:

-Z "H.265 MKV 1080p30"

And then select the 'hevc' checkbox. Your settings should look like this:

![image](https://user-images.githubusercontent.com/43864057/67436970-a4a46b00-f5e7-11e9-9d5d-4f06a97e6799.png)

**Comment by martinkeat** [comment]
Cheers. Thanks

**Comment by HaveAGitGat** [comment]
No problem.
