### ISSUE TITLE
Stream Title not gathered for MP4 

### ISSUE THREAD

**Issue by gauth-fr** [HaveAGitGat/Tdarr#460]
**Describe the bug**
Audio stream title in MP4 not "ingested" by tdarr

**To Reproduce**
Have a MP4 with an audio stream with a title and check the metadata in tdarr

**Expected behavior**
The audio stream title should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/39403109/123646852-e27b7d00-d827-11eb-9ff5-164b8512d2d2.png)

**Please provide the following information:**
- Config files
**Server**:
{
  "nodeID": "MainNode",
  "nodeIP": "0.0.0.0",
  "nodePort": "8267",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ]
}

**Node**:
{
  "nodeID": "t490-node",
  "nodeIP": "192.168.0.21",
  "nodePort": "8267",
  "serverIP": "192.168.0.250",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/home/Tdarr/Media/test",
      "node": "Z:\\test"
    },
    {
      "server": "/home/Tdarr/Media/films",
      "node": "Z:\\Films"
    },
    {
      "server": "/temp",
      "node": "Z:\\tdarr_cache"
    }
  ]
}

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
Nothin relevant

-Worker error 
The Tdarr_Plugin_MC93_Migz3CleanAudio is trying to set the title on a MP4 and end in the loop due this issue.

The new transcode arguments were the exact same as the last ones meaning
the file/worker would most likely be stuck in an infinite transcode loop if not stopped.
Last arguments: , -map 0 -metadata:s:a:0 title="5.1" -c copy -max_muxing_queue_size 9999
New arguments: , -map 0 -metadata:s:a:0 title="5.1" -c copy -max_muxing_queue_size 9999
Plugin Community Tdarr_Plugin_MC93_Migz3CleanAudio

 - OS: Docker
 - Browser Chrome/FF
 - Version 2.00.09

**Additional context**
The title can be seen with media info or VLC but not with ffmpeg/ffprobe.

**Comment by HaveAGitGat** [comment]
Tdarr also uses Exiftool and MediaInfo so it's worth checking that data inside the 'meta' and 'mediaInfo' objects:

` "Title": "Big Buck Bunny, Sunflower version",`

**Comment by HaveAGitGat** [comment]
I updated FFrobe in 2.00.11 so hopefully it has the data needed else check the 'meta' and 'mediaInfo' objects. Reopen if required.
