### ISSUE TITLE
Extra quotes when editing metadata

### ISSUE THREAD

**Issue by gauth-fr** [HaveAGitGat/Tdarr#465]
**Describe the bug**
In a plugin im making, im' trying to add some title to audio like "fre AAC 5.1".

Im doing something like that:
```
title="5.1 "+inputs.tag_language
ffmpegCommandInsert += `-metadata:s:a:${audioIdx} title='${title}' `;
```
It's working, but in the end, when I check the metadata I have:
```
"tags": {
"language": "fre",
"title": "'fre AAC 5.1'", <---- note that the single quotes are in the metadata
```

I tried ``ffmpegCommandInsert += `-metadata:s:a:${audioIdx} title="${title}" `;`` (with double quotes)
I end up with "title": "\"fre AAC 5.1"\" in the metadata
(see the screenshot)

I tried without double/quotes : it won't works because AAC and 5.1 and not valid input parameter
But it works if the title is a single word.

Note that i tried through the CLI and and it works fine (no double/quotes added to the metadata).

So i guess there are some double/quotes escaping done some where when executing the ffmpeg command?

It also does the same when using for example the plugin Tdarr_Plugin_MC93_Migz2CleanTitle to remove the title from a video 
(see the screenshot):
```
        "tags": {
          "title": "\"\"",
          "DURATION": "00:40:37.723000000"
        },

```
**To Reproduce**
Create a stack with the plugin Tdarr_Plugin_MC93_Migz2CleanTitle.
Process a file with title to remove it and check the metadata.

You could also use the plugin Tdarr_Plugin_MC93_Migz3CleanAudio which may add a title to audio streams without titles.

**Expected behavior**
Those extra quotes should not appears

**Screenshots**
![image](https://user-images.githubusercontent.com/39403109/125815432-0edf5e87-8faf-4d4a-a052-a32e675cc265.png)
A screenshot where the title is removed by the plugin Tdarr_Plugin_MC93_Migz2CleanTitle 

![image](https://user-images.githubusercontent.com/39403109/125819561-ab1411f5-afee-4c55-92b7-eda66d12c6de.png)
A screenshot from VLC. Note the empty title which is "", and the extra quotes on the audio tracks.

**Please provide the following information:**

- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Server:
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```

Node:
```
{
  "nodeID": "t490-node",
  "nodeIP": "192.168.0.22",
  "nodePort": "8267",
  "serverIP": "192.168.0.250",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/home/Tdarr/Media/test",
      "node": "Z:\\test"
    },
    {
      "server": "/home/Tdarr/Media/films",
      "node": "Z:\\Films"
    },
    {
      "server": "/temp",
      "node": "Z:\\tdarr_cache"
    }
  ]
}
```
- Log files  
There is actually nothing in the log files, as the plugins (and everything) execute correctly.
Just those extra quotes in the output files

-Worker error 
The transcode works fine. It's really those extra quotes which are the problems

Server
 - OS: Docker on Linux (Synology) 
 - Browser: chrome, ff, brave
 - Version: 2.00.09

Node
 - OS: Windows 10 (native app) 
 - Browser: chrome, ff, brave
 - Version: 2.00.09

**Comment by HaveAGitGat** [comment]
Hi, place double quotes around the whole argument:

`"title=hello there"`

Comes out as:

` "Title": "hello there",`

Modified plugin here:
https://pastebin.com/1cwXqM5k

**Comment by dbondarchuk** [comment]
Sorry for bringing up this issue, but @HaveAGitGat what if I need to have a quote in the title?
For example:

```typescript
const title = 'AAC / Ukrainian - Studio "Postmodern"';
ffmpegCommandInsert += `-map 0:${i} -c:a:${currentAudioIdx} aac -ac:a:${currentAudioIdx} 2 -metadata:s:a:${currentAudioIdx} "title=${escapeTitle(title)}" `;
```

How to write function `escapeTitle`?
I have tried the following:

```typescript
const escapeTitle = (title) => title.replaceAll('"', '\\"');
const escapeTitle = (title) => title.replaceAll('"', '\\\\"');
const escapeTitle = (title) => title.replaceAll('"', '""');
```

Thanks!
