### ISSUE TITLE
Removing audio language from file without copying the whole file

### ISSUE THREAD

**Issue by ajhorvath20** [HaveAGitGat/Tdarr#466]
Hi, I have number of files with 2 or 3 languages and I want to remove any non-english language but without copying the whole again. 

Basically my media is on the cloud and when I remove the subs or remove the audi language it copies the whole file. Is it possible to avoid it?

Thank you

**Comment by supersnellehenk** [comment]
The way FFMPEG works, it'll always have to rewrite the entire file. Perhaps there's some other piece of software that's able to do it, but FFMPEG can't afaik.

**Comment by HaveAGitGat** [comment]
Not possible with ffmpeg sorry. Not sure if this is possible in general as a new file has to be created where all the container/stream/meta data is encoded correctly.
