### ISSUE TITLE
node announcing what it is working on at node console.

### ISSUE THREAD

**Issue by andbir** [HaveAGitGat/Tdarr#468]
It would be nice if the nodes could display on the node console output which files it is currently working on. 
For example it could display "GPU3: /movies/The little mermaid (1986)/The little mermaid BDRIP-2160.mkv" or whatever
I suppose this could be done in each pluginscript, but it would be nicer if it did it automatically from Tdarr instead of having to modify every script to make sure the output looks the same.

**Comment by HaveAGitGat** [comment]
Added
