### ISSUE TITLE
Feature Request: Estimated size after transcode.

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#47]
I note that under "i" under the video being transcoded you have "Original Size (GB)" listed in the extra information. Could you add "Estimated size" as well to show the estimated size of the new file being created?

**Comment by marshalleq** [comment]
Yes I agree.  I believe this is available as part of the handbrake output, so should be possible.   I have seen a working implementation with ffmpeg too if I recall correctly.

**Comment by HaveAGitGat** [comment]
Ok will do.

**Comment by HaveAGitGat** [comment]
HandBrake doesn't support estimated file size:
https://github.com/HandBrake/HandBrake/issues/385

I have added estimation of file size based on the size of the output file relative to how much is left to process.

It's not very accurate with HandBrake as it does its processing in RAM before bulk outputting the result as it nears the end of transcoding.

With FFmpeg it is quite accurate though. For example here, at 10% conversion, it estimates a 13MB output size. The final size is 15MB.

![image](https://user-images.githubusercontent.com/43864057/72925952-77cd3480-3d4b-11ea-80d6-89fb11d6ee54.png)

So the accuracy will depend on transcode settings/CLI but I suppose it's better than nothing.

Will be in 1.103 later this week.

**Comment by marshalleq** [comment]
Handbrake CLI has this functionality built in. I thought you could just pass that forward to tdarr?

Sent from my mobile device

On 23/01/2020, at 08:26, HaveAGitGat <notifications@github.com> wrote:

﻿

HandBrake doesn't support estimated file size:
HandBrake/HandBrake#385<https://github.com/HandBrake/HandBrake/issues/385>

I have added estimation of file size based on the size of the output file relative to how much is left to process.

It's not very accurate with HandBrake as it does its processing in RAM before bulk outputting the result as it nears the end of transcoding.

With FFmpeg it is quite accurate though. For example here, at 10% conversion, it estimates a 13MB output size. The final size is 15MB.

[image]<https://user-images.githubusercontent.com/43864057/72925952-77cd3480-3d4b-11ea-80d6-89fb11d6ee54.png>

So the accuracy will depend on transcode settings/CLI but I suppose it's better than nothing.

Will be in 1.103 later this week.

**Comment by HaveAGitGat** [comment]
No, I don't think so:

![image](https://user-images.githubusercontent.com/43864057/72929235-62f39f80-3d51-11ea-9097-e9a0f570d398.png)
