### ISSUE TITLE
ffProbeRead returns nothing

### ISSUE THREAD

**Issue by cheers12** [HaveAGitGat/Tdarr#471]
For some reason ffProbeRead is not returning anything on two mp4 files that I have but on other mp4 files it seems to work fine

Tdarr version 2.00.09

not working
```
{
  "_id": "/media/Movies/Nightcrawler.2014.1080p.BluRay.x265-RARBG/Nightcrawler.2014.1080p.BluRay.x265-RARBG.mp4",
  "file": "/media/Movies/Nightcrawler.2014.1080p.BluRay.x265-RARBG/Nightcrawler.2014.1080p.BluRay.x265-RARBG.mp4",
  "DB": "_mifebCLB",
  "hasClosedCaptions": false,
  "container": "mp4",
  "ffProbeRead": "",
  "ffProbeData": {
    "streams": []
  },
  "file_size": 1884.70064163208,
  "video_resolution": "",
  "fileMedium": "other",
  "video_codec_name": "",
  "audio_codec_name": "",
  "lastPluginDetails": "none",
  "processingStatus": false,
  "createdAt": 1628106719613,
  "bit_rate": 0,
  "statSync": {
    "mtimeMs": 1628060405404.0715,
    "ctimeMs": 1628060405404.0715,
    "atime": "2021-08-04T07:00:05.462Z",
    "mtime": "2021-08-04T07:00:05.404Z",
    "ctime": "2021-08-04T07:00:05.404Z"
  },
  "HealthCheck": "Success",
  "TranscodeDecisionMaker": "Not required",
  "lastHealthCheckDate": 1628106691487,
  "holdUntil": 0,
  "lastTranscodeDate": 1628106751021,
  "infoLog": "\nMigz-Order Streams - Pre-processing\n☑ Streams are in expected order. \n \nMigz-Remove image formats from file - Pre-processing\n☑File doesn't contain any unwanted image format streams.\n\nTranscode Specific Audio Stream Codecs - Pre-processing\n☑ File does not have any streams that need to be transcoded! \n\nMichPass-Remove subtitle and audio streams with certain codecs - Pre-processing\n☑File doesn't contain subtitle or audio codecs which were unwanted or that require tagging.\n",
  "bumped": false,
  "history": "",
  "oldSize": 0,
  "newSize": 0,
  "lastUpdate": 1628106719888
}
```

working
```
{
  "_id": "/media/Movies/A.Star.Is.Born.2018.Encore.Edition.1080p.BluRay.x265-RARBG/A.Star.Is.Born.2018.Encore.Edition.1080p.BluRay.x265-RARBG.mp4",
  "file": "/media/Movies/A.Star.Is.Born.2018.Encore.Edition.1080p.BluRay.x265-RARBG/A.Star.Is.Born.2018.Encore.Edition.1080p.BluRay.x265-RARBG.mp4",
  "DB": "_mifebCLB",
  "hasClosedCaptions": false,
  "container": "mp4",
  "ffProbeRead": "success",
  "ffProbeData": {
    "streams": [
      {
        "codec_name": "hevc",
        "codec_type": "video",
        "bit_rate": "2000171",
        "tags": {
          "creation_time": "2020-03-28T13:59:25.000000Z",
          "language": "und",
          "handler_name": "VideoHandler"
        },
        "avg_frame_rate": "1616564424/67423669",
        "duration": "8853.024000",
        "width": 1920,
        "height": 800,
        "nb_frames": "212259"
      },
      {
        "codec_name": "aac",
        "codec_type": "audio",
        "bit_rate": "224000",
        "channels": 6,
        "tags": {
          "creation_time": "2020-03-28T13:59:25.000000Z",
          "language": "eng",
          "handler_name": "SoundHandler"
        },
        "avg_frame_rate": "0/0",
        "duration": "8852.981000",
        "nb_frames": "414986"
      }
    ]
  },
  "file_size": 2354.3033838272095,
  "video_resolution": "1080p",
  "fileMedium": "video",
  "video_codec_name": "hevc",
  "audio_codec_name": "",
  "lastPluginDetails": "none",
  "processingStatus": false,
  "createdAt": 1625115290679,
  "bit_rate": 2230800.2553703687,
  "statSync": {
    "mtimeMs": 1617517986241.2622,
    "ctimeMs": 1617523416807.8098,
    "atime": "2021-07-01T04:54:41.023Z",
    "mtime": "2021-04-04T06:33:06.241Z",
    "ctime": "2021-04-04T08:03:36.808Z"
  },
  "HealthCheck": "Success",
  "TranscodeDecisionMaker": "Not required",
  "lastHealthCheckDate": 1625130903380,
  "holdUntil": 0,
  "lastTranscodeDate": 1625551506243,
  "infoLog": "\nMigz-Remove image formats from file - Pre-processing\n☑File doesn't contain any unwanted image format streams.\n\nTranscode Specific Audio Stream Codecs - Pre-processing\n☑ File does not have any streams that need to be transcoded! \n\nMichPass-Remove subtitle and audio streams with certain codecs - Pre-processing\n☑File doesn't contain subtitle or audio codecs which were unwanted or that require tagging.\n",
  "bumped": false,
  "history": "",
  "oldSize": 0,
  "newSize": 0,
  "tPosition": 1937,
  "hPosition": 1938
}

```

**Comment by HaveAGitGat** [comment]
Are you able to run ffprobe on it manually?

**Comment by cheers12** [comment]
Do you have instructions on how? I'm not a dev so I'm not sure how I would start with these instructions.

https://github.com/HaveAGitGat/Tdarr/issues/305
https://github.com/HaveAGitGat/Tdarr/issues/209

**Comment by HaveAGitGat** [comment]
You don't need to be a dev to use ffprobe, it's just a CLI tool. You can download it here:
https://ffbinaries.com/downloads

Then just run it on one of your files.

`ffprobe /media/Movies/Nightcrawler.2014.1080p.BluRay.x265-RARBG/Nightcrawler.2014.1080p.BluRay.x265-RARBG.mp4`

Should give some output such as: 

```
Input #0, matroska,webm, from 'sample__1080__libx264__aac__30s__video.mkv':
  Metadata:
    title           : Big Buck Bunny, Sunflower version
    GENRE           : Animation
    MAJOR_BRAND     : isom
    MINOR_VERSION   : 1
    COMPATIBLE_BRANDS: isomavc1
    COMPOSER        : Sacha Goedegebure
    ARTIST          : Blender Foundation 2008, Janus Bager Kristensen 2013
    COMMENT         : Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
    ENCODER         : Lavf57.83.100
  Duration: 00:00:30.02, start: 0.000000, bitrate: 4357 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn, 120 tbc (default)
    Metadata:
      HANDLER_NAME    : GPAC ISO Video Handler
      ENCODER         : Lavc57.107.100 libx264
      DURATION        : 00:00:30.021000000
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : GPAC ISO Audio Handler
      ENCODER         : Lavc57.107.100 aac
      DURATION        : 00:00:30.021000000
  Stream #0:2: Audio: aac (LC), 48000 Hz, 5.1, fltp (default)
    Metadata:
      HANDLER_NAME    : GPAC ISO Audio Handler
      ENCODER         : Lavc57.107.100 aac
      DURATION        : 00:00:30.021000000

```

**Comment by cheers12** [comment]
Thanks

`ffprobe version 4.2.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/volume1/video/Movies/Nightcrawler.2014.1080p.BluRay.x265-RARBG/Nightcrawler.2014.1080p.BluRay.x265-RARBG.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2020-04-09T13:32:26.000000Z
    title           : Nightcrawler.2014.1080p.BluRay.x265-RARBG
    encoder         : Lavf58.20.100
    comment         : Nightcrawler.2014.1080p.BluRay.x265-RARBG
  Duration: 01:58:05.33, start: 0.000000, bitrate: 2231 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1920x800 [SAR 1:1 DAR 12:5], 2000 kb/s, 23.98 fps, 23.98 tbr, 1200k tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2020-04-09T13:32:26.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 223 kb/s (default)
    Metadata:
      creation_time   : 2020-04-09T13:32:26.000000Z
      handler_name    : SoundHandler
`

**Comment by HaveAGitGat** [comment]
I've updated ffprobe in the latest release (2.00.11), reopen if you still have the same issue.
