### ISSUE TITLE
Oops! Something went wrong.  Please try refresh the page or create an issue here.

### ISSUE THREAD

**Issue by DevXen** [HaveAGitGat/Tdarr#472]
this started happening today when i click on libraries or stats. it'll start to load the page then goes to this.
i tried reinstalling the docker container. that didnt help. workers are still going.

**Comment by HaveAGitGat** [comment]
Which version and OS are you using?

**Comment by DevXen** [comment]
sorry. i didn't see i could clear the db and restore from backup before posting here. but that fixed it

**Comment by HaveAGitGat** [comment]
Ok great :)

**Comment by DevXen** [comment]
ok so that didn't fix it, its happening again, i've tried to restore previous databases. i've restarted the docker container. i've refreshed the page. it'll work for awhile. then it pops up with that error if i click on the libraries tab. i think i'm just going to start over with a fresh DB to see if that helps. - also i have like 30,000 files loaded so i'm not sure if that is an issue or not. 18 workers going with a Quadro p2000 card. 5 health checks going. 

i am running the docker container for unraid. on the latest stable. 6.9.2

**Comment by DevXen** [comment]
nope even clearing the DB. restarting the docker container, and refreshing the page. is pulling that error. the library page tries to load for a few seconds then goes to that error.

**Comment by HaveAGitGat** [comment]
> Which version and OS are you using?

Which Tdarr version are you using?

**Comment by DevXen** [comment]
Sorry. Got busy at work. 

I'm using the latest tdarr_aio container. I even force updated it before I reset the db.

This is something i noticed Before then and now as well. The gap between all and the library name keeps getting farther apart on the stats page.
![Screenshot_20210808-095815_Remote Desktop](https://user-images.githubusercontent.com/2284801/128638177-3185cea4-7039-40eb-aac6-bf2cca9bd6fc.jpg)
![Screenshot_20210808-095832_Remote Desktop](https://user-images.githubusercontent.com/2284801/128638182-cf851ca0-4fd3-4ef7-a440-a7821928f999.jpg)

**Comment by HaveAGitGat** [comment]
tdarr_aio is from V1 and is no longer supported (stopped being supported about 7 months ago).

V2 instructions are here:
https://tdarr.io/docs/installation/docker
