### ISSUE TITLE
Unable to start container when GPU passed through Unraid

### ISSUE THREAD

**Issue by fiservedpi** [HaveAGitGat/Tdarr#473]
**Describe the bug**

when adding the extra parameters and visible devices variables as described in the documentations the container will not start if you remove the added variables container will start on Unraid TdarrV2 PRO
**To Reproduce**
Add:
—runtime=nvidia 
Add variable:
NVIDIA _VISIBLE_DEVICES 
GPUID
NVIDIA_DRIVER_CAPABILITIES
ALL

**Expected behavior**

The container to start and be able to use the GPU as a device
These exact same added peramiters worked before the update
**Screenshots**
Unraid pop up
“Server execution error”

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux] Unraid
 - Browser [e.g. chrome, safari] Edge 
 - Version [e.g. 2.00.00]TDARR V2 PRO

**Additional context**
Logs if needed but they do not show anything since the container won’t start with the added parameters

**Comment by HaveAGitGat** [comment]
Hmm I didn't change anything regarding GPU so not sure what this could be. Someone else double checked and GPU is working fine for them on 2.00.10 on unraid so thinking it might be something locally for you.

The GPU variables aren't really needed for the server, only the nodes. As a quick solution, does it work fine if you only use the variables with Tdarr Nodes?

**Comment by fiservedpi** [comment]
I’ve tried each way both, just node only I’ll reproduce and grab all the files/info I can

**Comment by fiservedpi** [comment]
![tdarr1](https://user-images.githubusercontent.com/42981853/128641596-09ce4e3a-5f02-4baa-8ccb-9c12ab618c87.PNG)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/6951261/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/6951263/Tdarr_Server_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/6951268/Tdarr_Server_Log.txt)

**Comment by HaveAGitGat** [comment]
Please try 2.00.12 as there's been an update to the containers. Reopen if needed, thanks.
