### ISSUE TITLE
Tdarr Node running into Fatal - Undefined

### ISSUE THREAD

**Issue by HStep20** [HaveAGitGat/Tdarr#475]
Any time media is queued in the server web ui, it begins to process, then just disappears from the queue. Nothing replaces it, and it doesn't show up in the error tab. Its just gone. Once the transcoding worker limit is hit, nothing continues to queue, and nothing is actually transcoded. This behavior seemed to begin with the latest update to the Node.

To Reproduce it, all I need to do is try and requeue media.

Stacks for the Library:
Community,Tdarr_Plugin_lmg1_Reorder_Streams
Community,Tdarr_Plugin_MC93_MigzImageRemoval
Community,Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only

Logs:
- Configs: https://pastebin.com/N3eZsYut
- Windows Node: https://pastebin.com/q05xEvNi
- Server Node: https://pastebin.com/wWAb0bji

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Unraid (Server), Win 10 (Node)
 - Browser: Firefox
 - Version 2.00.10

**Comment by HaveAGitGat** [comment]
This error should show in 2.00.11. Please reopen if needed.
