### ISSUE TITLE
High CPU use when GPU transcoding

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#476]
**Describe the bug**
CPU use seems high for GPU transcoding

**To Reproduce**
Start GPU transcoding, observe top on node.

**Expected behavior**
I would not expect CPU usage to be this high per transcode, PLEX seems to be able to hardware transcode on this machine with about 5% CPU per transcode.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/11021632/129787714-f59f77f0-88a9-402f-85a0-a1ebe1034d0b.png)

**Please provide the following information:**
[Config and Logs.zip](https://github.com/HaveAGitGat/Tdarr/files/7002786/Config.and.Logs.zip)

 - OS: Docker
 - Browser Edge
 - Version 2.00.10

**Comment by tehniemer** [comment]
This is a fairly typical ffmpeg command

`-hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi <io> -max_muxing_queue_size 8000 -map 0:0 -c:v:0 hevc_vaapi -vf "scale_vaapi=format=p010" -b:v 7654080 -map 0:1 -c:a:0 copy -map 0:s -scodec copy -map_metadata:g -1 -metadata JBDONEVERSION=1 -metadata JBDONEDATE=2021-08-18T21:12:48.442Z -map_chapters 0`

**Comment by HaveAGitGat** [comment]
Please try 2.00.12 as FFmpeg has been updated including VAAPI support so that hopefully fixes your issue.

**Comment by tehniemer** [comment]
I'm still seeing high CPU use on 2.00.12, anything else I can provide to help you look into it?

![image](https://user-images.githubusercontent.com/11021632/145823024-e044039d-1bfa-4c34-998c-c25042652019.png)

**Comment by supersnellehenk** [comment]
To be fair, 25% (which is 25% of a single core) isn't that high for a single ffmpeg process. Tdarr is way more resource intensive compared to plex which only intermittently transcodes at full speed.

**Comment by tehniemer** [comment]
OK, I don't have any other transcoding experience aside from PLEX to compare against. If this seems normal I have no issue with it.

**Comment by HaveAGitGat** [comment]
Yeah that looks fairly normal to me. There are lots of FFmpeg processes that don't use the GPU/iGPU so CPU% can be around that.

You can submit a bug report to FFmpeg if you think it's of concern: https://trac.ffmpeg.org/
