### ISSUE TITLE
[Feature Request] Spread GPU transcodes over multiple GPUs (if equipped)

### ISSUE THREAD

**Issue by sbrown7792** [HaveAGitGat/Tdarr#477]
**Is your feature request related to a problem? Please describe.**
My Tdarr_node PC (Windows 10 native client, not docker) has two identical GPUs. From my testing, FFmpeg by default only uses the first GPU unless the '-gpu \<N\>' argument is added. In order to utilize both GPUs on my transcoding node, I duplicated the GPU transcoding plugin I was using, and edited it to include '-gpu 1' in the FFmpeg command, but now have to split my media across multiple libraries, so I can specify half of the libraries use the default plugin, and the other half use the modified '-gpu 1' plugin. Then, I have to check "Library alternation" in order to **mostly** alternate encodes across GPUs (if one library finishes encoding all files first, one GPU will end up with all the transcodes while the second sits idle).

**Describe the solution you'd like**
An advanced "Transcode: GPU:" option, where the user could specify "Total GPU transcodes", and "Per GPU transcodes", and then the Tdarr node could control the '-gpu \<N\>' flag in a plugin, tracking which GPUs are currently transcoding. 

**Describe alternatives you've considered**
I thought about running two separate node software instances on the same system, and somehow forcing the second copy to add the "-gpu 1" additional argument to the FFmpeg call. I'm not sure how I'd intercept or wrap the second FFmpeg call to ensure the second GPU was used.

**Additional context**
Even though each of my GPUs (980ti) could comfortably encode 2 files individually, I ran into the problem [here](https://forums.developer.nvidia.com/t/creating-nvenc-encoders-on-multi-gpu-cards-fails-with-out-of-memory/39194), where the fourth overall transcode would fail with nvenc error "out of memory". So I had to keep the total GPU transcodes to 3. It seems like I can do 2 encodes on one GPU (regardless of which one) and only one on the second GPU. If the feature were to be implemented, I'd need the ability to limit overall transcodes to "3", while the "Per GPU transcode" setting would be "2". Users running Quadro's or more enterprise GPUs may not run into the same "out of memory" limitation I have, and could increase transcodes to however many their system can support.

**Comment by HaveAGitGat** [comment]
I think it could technically be done from within a plugin. So detect how many encodes are already running on each GPU, then assign the new encode to the one with the least running encodes.

Would need a cross platform solution for it though.  Else could be done internally, depends which is easier.

**Comment by simeononsecurity** [comment]
I can see how it might be done in a plug-in but I can't see how it could be done in a plug-in without breaking other transcode plugins. Unfortunately for cross-platform support and the ability to use it with any plugin or any transcode settings it would be nice to have native support in tdarr

**Comment by UmamaheshwarN** [comment]
If anyone is still looking to use multiple NVIDIA GPUs on a single node, I have modified "Tdarr_Plugin_MC93_Migz1FFMPEG" Plugin to make use of multiple GPUs. Thanks for the suggestion by @sbrown7792. Here's the [plugin](https://github.com/UmamaheshwarN/Tdarr_Plugins/blob/0b528d2a970f353c30f94e30e0d8e3fbc20ed16a/Community/Tdarr_Plugin_FFMPEG_All_NVIDIA_GPUs.js) if anyone is interested. 

Download the file and add to your Server's Local Plugins folder and you can use the Plugin.

Note: Plugin uses nvidia-smi command to find the GPU with the lowest memory consumption and assigns new transcode to that GPU.

**Comment by simeononsecurity** [comment]
> 

I'm still testing it out, but it seems like it's working. 
You should submit a merge request so that others may know about this. Very much appreciated!

I don't have enough understanding of the code. But should this plugin work in configurations where the system has more than 2 gpus? Is there any known limit?

**Comment by UmamaheshwarN** [comment]
I already submitted a merge request to [update](https://github.com/HaveAGitGat/Tdarr_Plugins/pull/341) the original plugin (Tdarr_Plugin_MC93_Migz1FFMPEG).

> I don't have enough understanding of the code. But should this plugin work in configurations where the system has more than 2 gpus? 

Yes, it will make use of the additional NVIDIA GPUs in the system (node). 
> Is there any known limit?

No. Plugin will not add any GPU arguments to the FFMPEG args if there is only 1 GPU and/or node cannot access more than 1 GPU or they are not available for the node.

**Comment by simeononsecurity** [comment]
> I already submitted a merge request to [update](https://github.com/HaveAGitGat/Tdarr_Plugins/pull/341) the original plugin (Tdarr_Plugin_MC93_Migz1FFMPEG).
> 
> > I don't have enough understanding of the code. But should this plugin work in configurations where the system has more than 2 gpus?
> 
> Yes, it will make use of the additional NVIDIA GPUs in the system (node).
> 
> > Is there any known limit?
> 
> No. Plugin will not add any GPU arguments to the FFMPEG args if there is only 1 GPU and/or node cannot access more than 1 GPU or they are not available for the node.

One last question. Have you tested it on windows and linux?

**Comment by UmamaheshwarN** [comment]
I have tested it in both Windows (with 2 GPUs) and Linux (with 6 GPUs), so yes.

I also checked the documentation for the command used and it is the same for both Windows and Linux so there should be no problems.

**Comment by simeononsecurity** [comment]
Shoot, I've waited so long for this. Thanks @UmamaheshwarN !
Now.. if only we could get the same for health checks and it would be perfect!

**Comment by sbrown7792** [comment]
Hi @UmamaheshwarN, great work getting it into a plugin! I just got the chance to test it and ran into an issue on my Windows 10 machine where it doesn't recognize the "wc" command: "'wc' is not recognized as an internal or external command, operable program or batch file."

How did you get wc on your Windows machine? cygwin or similar?

**Comment by UmamaheshwarN** [comment]
Shoot... I have added that after the initial testing, and I forgot to test it on Windows.

`wc -l` is a linux shell command to count lines. Let me see how to fix it

**Comment by sbrown7792** [comment]
Hi @UmamaheshwarN , progress at least!

I get "Error in reading nvidia-smi output!" now in the log, and work is mapped to the first GPU exclusively. I'm able to run the "nvidia-smi" command in a cmd and get the expected output, so I poked around the code to see if I could determine where exactly it's failing. I noticed a typo on line 355: "gpu_res.**lenght**;", fixed that, but still an issue. 

I did the classic debug print statements:
```
try {
    response.infoLog += `debug1`;
    var gpu_res = execSync('nvidia-smi --query-gpu=name --format=csv,noheader');
    response.infoLog += `debug2`;
    gpu_res = gpu_res.trim();
    response.infoLog += `debug3`;
    gpu_res = gpu_res.split(/\r?\n/);
    response.infoLog += `debug4`;
```

and the output in the log is now:
`debug1debug2Error in reading nvidia-smi output!`

So it looks like the file is crashing on the .trim() function call.

Thanks!!

**Comment by UmamaheshwarN** [comment]
Can you add `response.infoLog += gpu_res` right after execSync line and post the ouput?

**Comment by sbrown7792** [comment]
I tried .toString just based off of a precursory google, so bit of a mess but the code is now:
```
try {
    response.infoLog += `debug1`;
    var gpu_res = execSync('nvidia-smi --query-gpu=name --format=csv,noheader');
    response.infoLog += gpu_res;
    response.infoLog += `debug2`;
    gpu_res = gpu_res.toString.trim();
    response.infoLog += `debug3`;
    gpu_res = gpu_res.split(/\r?\n/);
    response.infoLog += `debug4`;
    
    /* When nvidia-smi returns an error it contains 'nvidia-smi' in the error
      Example: Linux: nvidia-smi: command not found
               Windows: 'nvidia-smi' is not recognized as an internal or external command, operable program or batch file.*/
    if (!gpu_res[0].includes('nvidia-smi')) {
      gpu_count = gpu_res.length;
    } else {
      gpu_count = -1;
    }
  } catch (error) {
    response.infoLog += `Error in reading nvidia-smi output!\n`;
    response.infoLog += error.message;
    gpu_count = -1;
  }
```

And the result is:
```
2022-10-17T21:37:18.903Z "infoLog": "Container for output selected as mkv. \nCurrent bitrate = 3078 \nBitrate settings: \nTarget = 1539 \nMinimum = 1077 \nMaximum = 2000 \nRunning nvidia-smi to see if a GPU is available and selecting the GPU with less memory usage\ndebug1NVIDIA GeForce GTX 980 Ti\r\nNVIDIA GeForce GTX 980 Ti\r\ndebug2Error in reading nvidia-smi output!\ngpu_res.toString.trim is not a functionFile is not hevc or vp9. Transcoding. \n",
```

**Comment by sbrown7792** [comment]
@UmamaheshwarN Looks like I was on the right track with the toString, but forgot the ()

Once I added those in, the results looks good!

**Comment by simeononsecurity** [comment]
Is the code updated? Where should I look?

**Comment by sbrown7792** [comment]
The changes I've made to get it working in my machine (as well as updating it

**Comment by simeononsecurity** [comment]
> The updated code looks good to me. I have tested it on my Ubuntu machine with 6 GPUs and it is working fine.
> 
> @sbrown7792 I have merged your update.
> 
> @simeononsecurity Can you take a look and see if we can merge this plugin update to original plugin?

I'm not a maintainer on the repo. But it looks good to me.

**Comment by UmamaheshwarN** [comment]
@sbrown7792 I have been reading the [NVIDIA](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/) and [FFMPEG](https://trac.ffmpeg.org/wiki/HWAccelIntro) hardware acceleraion docs and doing some testing and found that making the below updates will speed up the transcoding.
Replacing the preset as follows
Input:
    from `-c:v h264_cuvid` 
    to     `-hwaccel cuvid -hwaccel_device ${gpu_num} -hwaccel_output_format cuda`
Output:
    from `-map 0 -c:v hevc_nvenc -gpu ${gpu_num}`
    to     `-map 0 -vf 'scale_cuda=w=${video_width}:h=${video_height}' -c:v hevc_nvenc -gpu ${gpu_num}`

Don't forget to replace `${gpu_num}` with the actual gpu number like 0,1,2 etc., and the `${video_height}` and `${video_width}` with values you read from video stream.

Here's a link to the updated full [plugin](https://github.com/UmamaheshwarN/Tdarr_Plugins/blob/f0705bf4decfda47e6f4e3501cf20c358834542e/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js). Please test and let me know the results.

**Comment by simeononsecurity** [comment]
Some nvidia gpus don't have h.265 encode/decode support. We should add a check to discover which of the gpus have h.265 encoders. Otherwise the transcode will fail every time a gpu without that encoder is selected.

**Comment by UmamaheshwarN** [comment]
> Some nvidia gpus don't have h.265 encode/decode support. We should add a check to discover which of the gpus have h.265 encoders. Otherwise the transcode will fail every time a gpu without that encoder is selected.

Good point, But can we even use those GPUs for transcoding using this plugin since the original preset uses `-c:v hevc_nvenc` which means we need an HEVC encoder?
And for the decoder, we don't need HEVC decoder (NVDEC/ hevc_cuvid) as the plugin will not be transcoding if the file is already in HEVC. It only copies if the file is in HEVC but not in the selected container, which will anyways be done by CPU.

**Comment by simeononsecurity** [comment]
> > Some nvidia gpus don't have h.265 encode/decode support. We should add a check to discover which of the gpus have h.265 encoders. Otherwise the transcode will fail every time a gpu without that encoder is selected.
> 
> Good point, But can we even use those GPUs for transcoding using this plugin since the original preset uses `-c:v hevc_nvenc` which means we need an HEVC encoder? And for the decoder, we don't need HEVC decoder (NVDEC/ hevc_cuvid) as the plugin will not be transcoding if the file is already in HEVC. It only copies if the file is in HEVC but not in the selected container, which will anyways be done by CPU.

Yeah, tdarr isn't that smart. You have to build the logic into the plugin. One of my transcode rigs has both an a2000 and gtx 1030 in it. The a2000 runs my plex docker container as well. Since it has utilization and the 1030 doesn't, the transcode keeps trying to work on the 1030 and it keeps failing.  I could be wrong here, but after updating the plugin in this use case, I'm seeing it fail every time it gets to the transcode step.

**Comment by UmamaheshwarN** [comment]
I tried looking at both FFMPEG and NVIDIA docs to see if there is a command to find the available decoders/encoders for a specific GPU. Either I am not able to find it or there is no such option.

Are you using docker or regular installation for Tdarr?

**Comment by simeononsecurity** [comment]
I'm using the docker version and I have the gpus passed through correctly. 
After looking into it myself, I've run into the same issue of being unable to determine what gpus have what encoders from the command line. 
It would probably be a PIA, but hardcoding it is always an option.... https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
Require GTX 9xx series or newer and disable setting the gpu if it starts with an K, if it starts with an M and the numbers that follow are less than 2000, etc.

**Comment by UmamaheshwarN** [comment]
If you are using docker, then I would suggest you to only pass the HEVC-supported GPUs to Tdarr node. I was initially doing something similar where I created 5 nodes passing a single GPU to each node, then I found out @sbrown7792 's script and started looking on how to assign to a specific GPU.

I mean we could add some hard coding to the plugin to filter out the unsupported GPUs but that will complicate the script even more. Let me know what you think.

**Comment by simeononsecurity** [comment]
> If you are using docker, then I would suggest you to only pass the HEVC-supported GPUs to Tdarr node. I was initially doing something similar where I created 5 nodes passing a single GPU to each node, then I found out @sbrown7792 's script and started looking on how to assign to a specific GPU.
> 
> I mean we could add some hard coding to the plugin to filter out the unsupported GPUs but that will complicate the script even more. Let me know what you think.

Yeah, I've done that now. It's kind of unfortunate I was using that car specifically for media library that I had set up that I wanted in 264 rather then 265
But I do get you. It's more than reasonable because I have a doctor container to just disable it or set up multiple nodes. Like if you still say no, I'm not going to fight you on it. However, I do think that idiot proofing is smart to add to pretty much any project. For instance, if I wasn't running in a doctor container I would have no option but to remove that GPU entirely from the system wish I don't think is an acceptable compromise for lesser technical users than myself. Though it is niche. I'm in no position of power to tell you to do it so I won't. However, I do think it's still a good idea, assuming that it's not a great deal of work to implement.

**Comment by UmamaheshwarN** [comment]
How about we add an input option for a list of GPUs to exclude?

**Comment by simeononsecurity** [comment]
> How about we add an input option for a list of GPUs to exclude?

Even easier. I'm for it

**Comment by UmamaheshwarN** [comment]
Updated the input option to exclude GPUs based on their numbers instead of names. Try and test the updated [plugin](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/3225fcead0e93372d895c655c2c3ef35732f723c/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js) and le me know if it works!

If you want to exclude GPU 0 from transcoding tasks, just put 0 in exclude_gpus. If you want to exclude 1 & 2 use 1,2

**Comment by simeononsecurity** [comment]
> 

Just tested both options. Seems to work.

**Comment by kesp91** [comment]
Is there a way to see which GPUs are detected by Tdarr/Plugin? I am running Tdarr container on Unraid and can't seem to get multiple GPUs added to the container. Any other attempts I make, I can't verify if Tdarr can "see" the other cards.

**Comment by simeononsecurity** [comment]
> Is there a way to see which GPUs are detected by Tdarr/Plugin? I am running Tdarr container on Unraid and can't seem to get multiple GPUs added to the container. Any other attempts I make, I can't verify if Tdarr can "see" the other cards.

Connect to the console of the docker container and run "nvidia-smi" if they are nvidia cards. Should pop up there. 
Don't forget to add the gpu id's or just add "all" under the nvidia_visible_devices var

**Comment by magickarle** [comment]
I'm a bit confused.
I was using H265-Transcode Using Nvidia GPU & FFMPEG with load balancing but when i've added a windows node, i got error on the wc.
Then i see the Migz-Transcode Using Nvidia GPU & FFMPEG got updated so i've removed the "load balancing" plugin and replaced it with the Migz-Transcode BUT:
I can't get the 3rd GPU kick in. as per nvidia-smi, 70% of ffmeg gets on GPU 0 and the reste on GPU 1. Nothing on GPU 3.
Eve if i set 25 GPU transcode in Tadrr, still nothin on the GPU 3.

The " load balancing" was working flawless for me (except the windows wc bug).
Is there a patched version for the load balancing one?

**Comment by hvanmegen** [comment]
This would be great as I have a bit of compute power at my disposal to convert my collection...
```
GPU 0: NVIDIA A100-SXM4-40GB (UUID: GPU-1c732fab-9182-7a9b-619b-2f9471a67b1e)
GPU 1: NVIDIA A100-SXM4-40GB (UUID: GPU-2fa2bc54-8cdf-5b5a-8d98-4d2fbc3a8cb1)
GPU 2: NVIDIA A100-SXM4-40GB (UUID: GPU-3ab4fdce-4c52-9d9a-6cd8-3f2bca7e9e52)
GPU 3: NVIDIA A100-SXM4-40GB (UUID: GPU-4cb3e2fd-b52a-8d9a-5e98-2fabcd4e3a1f)
GPU 4: NVIDIA A100-SXM4-40GB (UUID: GPU-5db2fa3c-e2cd-4b9a-8e9d-3fabce2d4a1e)
GPU 5: NVIDIA A100-SXM4-40GB (UUID: GPU-6eb1fd3a-cd2e-4b8a-9e8d-1f2abcde3a2f)
```

**Comment by simeononsecurity** [comment]
> This would be great as I have a bit of compute power at my disposal to convert my collection...
> 
> ```
> $> nvidia-smi -L | cut -d " " -f 1-4
> GPU 0: NVIDIA RTX A6000
> GPU 1: NVIDIA RTX A6000
> GPU 2: NVIDIA RTX A6000
> GPU 3: NVIDIA RTX A6000
> GPU 4: NVIDIA RTX A6000
> GPU 5: NVIDIA RTX A6000
> ```
> 
> I'm guessing it's not working as intended just yet?
> 
> edit: the A100's doesn't support NVENC apparently.. lol..

Geese man, how much transcoding do you need to do?
