### ISSUE TITLE
Export all status columns in CSV

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#478]
**Is your feature request related to a problem? Please describe.**
When using the CSV export only the `file` column is exported. This makes looking for `success/not required` or `error/cancelled` impossible. 

**Describe the solution you'd like**
Export all of the columns
![image](https://user-images.githubusercontent.com/11021632/130067844-41ee6f7f-b8f7-405b-8638-495ae0e1c78b.png)

**Comment by HaveAGitGat** [comment]
I've changed it so that in the next version it contains all file info:
![image](https://user-images.githubusercontent.com/43864057/143830283-e03e5b80-c1a0-4c21-9687-9427f7e3f32a.png)
