### ISSUE TITLE
Add a graph for Space Saved

### ISSUE THREAD

**Issue by julianrinaldi** [HaveAGitGat/Tdarr#480]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a graph showing the history of how much space you've saved with Tdarr.

**Describe the solution you'd like**
Graphs for "All" and each library showing space saved over time.

**Comment by risb0r** [comment]
Even making the data accessible via the API would be good too!

**Comment by HaveAGitGat** [comment]
Added for all and each library in next version:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/cac09318-4f6a-4266-9484-ad3f457dfa01)

**Comment by HaveAGitGat** [comment]
2.21.01 released
