### ISSUE TITLE
WorkerVerdictHistory taking up a lot of space

### ISSUE THREAD

**Issue by modem7** [HaveAGitGat/Tdarr#481]
**Describe the bug**
WorkerVerdictHistory taking up a lot of space. 

Is this required or can it be deleted via some form of rotation etc?

Seems like a lot of small files that are taking up a ludicrous amount of space and it only seems to be for pro features?
![image](https://user-images.githubusercontent.com/4349962/131049072-b4d8e6db-9e51-4eb8-9752-8df9da59ca8b.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/4349962/131048963-0576a01b-7f26-44f2-9d12-961f0e9a4188.png)

**Expected behavior**
Compress or delete unneeded files. 

 - OS: Ubuntu/Docker
 - Version [e.g. 2.00.00]

**Comment by HaveAGitGat** [comment]
Hmm that is a lot of space. You must have processed a lot of files to reach that size, have not seen it that large before. Yes you can delete it (can also delete DB3 folder entirely). I'll try and improve this or give an option for how much historical data the user would like to save.

**Comment by HaveAGitGat** [comment]
Just an update on this. DB3 was removed a few updates ago and the history is now limited to the last 100,000 items (4-5MB) in the next version 2.00.14 so the overall DB size is much smaller.
