### ISSUE TITLE
"Delete source file:" doesnt delete source file...

### ISSUE THREAD

**Issue by tordenflesk** [HaveAGitGat/Tdarr#483]
**Describe the bug**
"Delete source file:" doesnt delete source file...

**To Reproduce**
Enable "Delete source file:"

**Expected behavior**
"Delete source file:" should delete source file...

 - OS: Debian 10 / OMV5
 - Version [e.g. 2.00.10]

**Comment by supersnellehenk** [comment]
Are you getting any errors anywhere? Have you enabled output folder?

**Comment by HaveAGitGat** [comment]
Please reopen if you have some specific steps to recreate the bug as it has been working fine for me.
