### ISSUE TITLE
No Video on Completion

### ISSUE THREAD

**Issue by Sylvaeseel** [HaveAGitGat/Tdarr#487]
**Describe the bug**
For a few videos, when transcoding from h264 to h265, upon completion of transcoding of the video, the plugin stack finishes and doesn't copy the video to the final file, just the audio, this is using the default FFMPEG CPU plugin, it's the only plugin that affects video that I use, if you guys needs my entire plugin stack and settings I can get it. It doesn't affect all videos, infact I've only seen it happen with about 20 videos out of about 3700

**To Reproduce**
Steps to reproduce the behavior: Unsure, seems to be at random, maybe an issue with how the original file was transcoded?

**Expected behavior**
Expected to transcode and have video

**Screenshots**
![Capture6](https://user-images.githubusercontent.com/3047592/133414525-5089ce40-6839-4775-9456-f17d389bbc5f.PNG)

**Please provide the following information:**
- Config files  
Server https://pastebin.com/xu8srVQp
Node https://pastebin.com/ysT7e1hN

- Log files  https://pastebin.com/W3vynBc8

Here is the full difference between one of the files from the screenshot https://pastebin.com/1tGNFWtx

-Worker error N/A

 - OS: Unraid; Dockeer
 - Browser Edge
 - Version [e.g. 2.00.00]

**Comment by HaveAGitGat** [comment]
FFmpeg was updated in December so hopefully that fixes the issue. Reopen if needed.
