### ISSUE TITLE
Extraction of Subtitles and convert if needed.

### ISSUE THREAD

**Issue by minermartijn** [HaveAGitGat/Tdarr#488]
**Is your feature request related to a problem? Please describe.**
I do not now how to create a plugin, and hopefully you are oke with me requesting a feature for this plugin.
Tried multiple plugins for extracting subtitles that dont work.

**Describe the solution you'd like**
Can anyone create for me a plugin that extracts any type of subtitles in the filtered languages. eg eng,dut,fre
And than when extracted convert it to srt if its in a different format.

**Describe alternatives you've considered**

**Additional context**
Appologies incase this is not the correct way to ask for this, I just need help with a plugin that will do this for me.
Most of the times, subtitles that are already inside mkv files are synced very well. So i want to keep these.

**Comment by HaveAGitGat** [comment]
Add here if you still need this: https://github.com/HaveAGitGat/Tdarr_Plugins

It depends what codec your subs are in. It's not always possible to convert everything to SRT
