### ISSUE TITLE
Animate tdarr to use GPU for transcoding in unraid

### ISSUE THREAD

**Issue by cm86** [HaveAGitGat/Tdarr#49]
Hello,
It's Not an issue.
But what can i so to use my Nvidia GPU in the tdarr Container!?
I have already installed the Nvidia Plugin and it's working with the Plex Container.

Thanks for comments...
Chris

**Comment by HaveAGitGat** [comment]
Hi Chris,

Which Tdarr container are you using? There are 2:

tdarr - Alpine image with MongoDB separate (same as before)
tdarr_aio - all-in-one Ubuntu image with MongoDB inside + hardware transcoding


Make sure to use tdarr_aio. There isn’t yet an UnRaid template for it so just enable DockerHub results in UnRaid Community Applications.

**Comment by cm86** [comment]
Hello Thanks for the reply.
Yes i have yet installed tdarr_aio.
But what extra Options i have to Set in the tdarr webgui to use the GPU!?

**Comment by HaveAGitGat** [comment]
Are you using handbrake or ffmpeg?

You need to specify the nvenc encoding flag in the arguments box. Some handbrake examples:

`-Z “Very Fast 1080p30” -e nvenc_h265`

Or 

`-Z “Very Fast 1080p30” -e nvenc_h264`

**Comment by cm86** [comment]
Hello i have used Handbrake at least...
Thanks i will try this in the evening

**Comment by cm86** [comment]
Hello again.
It's working.
Thanks for the hint...

**Comment by HaveAGitGat** [comment]
Good to hear!
