### ISSUE TITLE
Question / Feature - Central distributen for Handbrake Presets

### ISSUE THREAD

**Issue by maximilianvonamerongen** [HaveAGitGat/Tdarr#490]
**Is your feature request related to a problem? Please describe.**
Currently I try two run two nodes on Windows and Linux. 
I exported the preset from Handbrake and saved this to the Tdarr server temp folder (central place).
In the transcode options I am using the Tdarr_Plugin_075a_Transcode_Customisable profile and provide the path to the preset. 
My idea was to use the /temp/****.json as a total path but this is not working because the path translation is not working for this kind of arguments. 

**Describe the solution you'd like**
Is it possible to extend the pathTranslators for such argument like in running profiles?

**Comment by HaveAGitGat** [comment]
The path translation should be working for presets. For example, here is the path to my json file:

`--preset-import-file "C:/Users/HaveAGitGat/Desktop/testpreset.json" -Z "My Preset"`

 I then set this pathTranslator:

```
    {
      "server": "C:/Users/HaveAGitGat/Desktop/",
      "node": "Y:/Users/HaveAGitGat/Desktop/"
    }
```

I then turned on verbose logging on the 'Logs' tab. When the Node processes the item, I can see in the logs the translation has worked:

`preset: '--preset-import-file "Y:/Users/HaveAGitGat/Desktop/testpreset.json" -Z "My Preset"',`

Re-open if needed.
