### ISSUE TITLE
Use Tdarr search filter to select specific files to process

### ISSUE THREAD

**Issue by casperse** [HaveAGitGat/Tdarr#491]
**Is your feature request related to a problem? Please describe.**
Sofar I have not found a easy way to select only MPEG2 in MKV to trancode to my stack.....

**Describe the solution you'd like**
When doing a search - export them to transcoding que 

**Describe alternatives you've considered**
You could get custom plugins, but the search would work on all scanned files

**Additional context**

Adding a button send selected files to transcoding...
![image](https://user-images.githubusercontent.com/2026859/134897887-b0c01769-5e0f-4c25-90c8-d80a8a892afe.png)

**Comment by HaveAGitGat** [comment]
Will move this under here as they're quite similar:
https://github.com/HaveAGitGat/Tdarr/issues/464
