### ISSUE TITLE
how can add extra audio streams codecs to my files before they get uploaded to gdrive ?

### ISSUE THREAD

**Issue by aniel300** [HaveAGitGat/Tdarr#492]
I am trying to add extra audio streams to my files with both 7.1, 5.1 and 2.0 respectively (aac, ac3, eac3, truehd, dts to aac, ac3, eac3, truehd, dts). How do I go about doing this? I have tried using both tdarr and unmanic, but I don't know what I'm doing. I want take whatever audio the files come with and duplicate it/add extra audio streams with different audio codecs such as aac, ac3, eac3, truehd, dts as well different audio channels such as 7.1, 5.1 and 2.0 respectively, although I am not sure if 5.1 to 7.1 is possible or even necessary.

**Comment by HaveAGitGat** [comment]
On the plugins tab:

![image](https://user-images.githubusercontent.com/43864057/143831775-4bf8f3b0-8a42-49a7-8385-1adc25a1e2bb.png)

Then you'd use this action to specify which stream to try and add.

![image](https://user-images.githubusercontent.com/43864057/143831948-2e7a8bc5-07c1-411c-a909-bdfb0e9cefb4.png)

Please reopen if needed.
