### ISSUE TITLE
Encoder error - "Specified rc mode is deprecated."

### ISSUE THREAD

**Issue by KptnKMan** [HaveAGitGat/Tdarr#493]
**Describe the bug**
All encodes that run through Tdarr end in error and fail.
In the log for each attempted encode, end with this (fulll log lower down):

> [hevc_nvenc @ 000001c0c38b6b40] Specified rc mode is deprecated.
> [hevc_nvenc @ 000001c0c38b6b40] Use -rc constqp/cbr/vbr, -tune and -multipass instead.
> [hevc_nvenc @ 000001c0c38b6b40] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!

There seems to be an issue with the depreciated use of the "rc mode", and seems like it should be updated?
When trying to research the issue, [this reddit post](https://www.reddit.com/r/shutterencoder/comments/kfgcff/hardware_encoding_failed_with_nvenc_when_cq/) seems relevant.
[This comment](https://www.reddit.com/r/shutterencoder/comments/kfgcff/comment/gg8i09g/?utm_source=reddit&utm_medium=web2x&context=3) in particular highlights:

> Command from console which don't work:
> `-hwaccel dxva2 -i "INPUT.mp4" -map v -c:a aac -ar 48k -b:a 128k -map a:0 -c:v h264_nvenc -profile:v high -level 5.1 -crf 25 -rc vbr_hq -cq 25 -pix_fmt yuv420p -sws_flags bicubic -movflags faststart -threads 0 -y "OUTPUT.mp4"`
> 
> Fixed command that works:
> `-hwaccel dxva2 -i "INPUT.mp4" -map v -c:a aac -ar 48k -b:a 128k -map a:0 -c:v h264_nvenc -profile:v high -level 5.1 -crf 25 -cq 25 -pix_fmt yuv420p -sws_flags bicubic -movflags faststart -threads 0 -y "OUTPUT.mp4"`

It seems that they are highlighting that `-rc vbr_hq -cq 25` in their example should be `-cq 25`.
How this relates to this issue, and Tdarr, seems to be that `-rc:v vbr_hq -cq:v 19` might be replaced with `-cq:v 19`?

Is there a way that this can be modified or updated?
I can't seem to find where to do this?

**To Reproduce**
- Server is setup on Unraid 6.9.2, using Docker.
- 2x nodes setup on separate Windows systems with Nvidia Graphics cards (3090 & 1080Ti).
- Latest updated Tdarr v2.00.10
- ffmpeg (Windows) ffmpeg-2021-09-22-git-447cf53774-full_build.7z from [gyan.dev Codex FFMPEG builds](https://www.gyan.dev/ffmpeg/builds/)
- HandBrakeCLI-1.4.1-win-x86_64.zip from [HandBrake downloads](https://handbrake.fr/downloads2.php)
- Media/Source and Transcode Cache folders are mapped, and verified in node logs.
- All health checks pass without error.

I'm using the plugin "Migz-Transcode Using Nvidia GPU & FFMPEG" with the settings:
- container: mkv
- bitrate_cutoff: [blank]
- enable_10bit: false
- enable_bframes: false
- force_conform: false

**Expected behavior**
Expected behaviour is that encoding would begin and complete using NVENC, from "Migz-Transcode Using Nvidia GPU & FFMPEG" plugin.

**Screenshots**
Screenshot of NVENC plugin:
![image](https://user-images.githubusercontent.com/12234043/134935797-c9c98f8b-f19e-44c2-9e88-f17fdb73b26d.png)
Screenshot of failed encode (Identical to other encodes using same plugin):
![image](https://user-images.githubusercontent.com/12234043/134936074-e088afce-92c3-4fff-8559-fd086447c0ba.png)

**Please provide the following information:**
Config files:
- Server (Unraid Docker) config file:
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.178.11",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```
- Node (Windows 10 & RTX3090) config:
```
{
  "nodeID": "EJECT1",
  "nodeIP": "192.168.178.101",
  "nodePort": "8267",
  "serverIP": "192.168.178.11",
  "serverPort": "8266",
  "handbrakePath": "C:\\Programs\\HandBrakeCLI\\HandBrakeCLI.exe",
  "ffmpegPath": "C:\\Programs\\ffmpeg\\bin\\ffmpeg.exe",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/mnt/media",
      "node": "Y:/"
    },
    {
      "server": "/temp",
      "node": "P:/TdarrTranscode"
    }
  ]
}
```

Log files:
-Worker error:
```
NodeID: EJECT1
Command:
C:\Programs\ffmpeg\bin\ffmpeg.exe -c:v h264_cuvid -i Y:/Videos/SERIES_DOCUMENTARIES/Louis Theroux's Weird Weekends/Season 1/Louis Theroux's Weird Weekends - S01E01 - Christianity WEBDL-480p.mkv -map 0 -c:v hevc_nvenc -rc:v vbr_hq -cq:v 19 -b:v 706k -minrate 494k -maxrate 917k -bufsize 1412k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 P:/TdarrTranscode/Louis Theroux's Weird Weekends - S01E01 - Christianity WEBDL-480p-TdarrCacheFile-VsTW7q5IG.mkv
Last 200 lines of CLI log:
ffmpeg version 2021-09-22-git-447cf53774-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil 57. 6.100 / 57. 6.100
libavcodec 59. 9.100 / 59. 9.100
libavformat 59. 5.100 / 59. 5.100
libavdevice 59. 0.101 / 59. 0.101
libavfilter 8. 9.100 / 8. 9.100
libswscale 6. 1.100 / 6. 1.100
libswresample 4. 0.100 / 4. 0.100
libpostproc 56. 0.100 / 56. 0.100
Input #0, matroska,webm, from 'Y:/Videos/SERIES_DOCUMENTARIES/Louis Theroux's Weird Weekends/Season 1/Louis Theroux's Weird Weekends - S01E01 - Christianity WEBDL-480p.mkv':
Metadata:
ENCODER : Lavf57.82.100
Duration: 00:49:32.16, start: 0.000000, bitrate: 1480 kb/s
Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 640x480 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 1k tbn (default)
Metadata:
DURATION : 00:49:32.160000000
Stream #0:1: Audio: eac3, 48000 Hz, stereo, fltp, 128 kb/s (default)
Metadata:
DURATION : 00:49:32.096000000
Stream #0:2: Subtitle: ass
Metadata:
ENCODER : Lavc57.106.101 ssa
DURATION : 00:49:18.920000000
Stream mapping:
Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[hevc_nvenc @ 000001c0c38b6b40] Specified rc mode is deprecated.
[hevc_nvenc @ 000001c0c38b6b40] Use -rc constqp/cbr/vbr, -tune and -multipass instead.
[hevc_nvenc @ 000001c0c38b6b40] InitializeEncoder failed: invalid param (8): Preset P1 to P7 not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelayEnable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding and set
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Additional context**
When trying to research the issue, [this reddit post](https://www.reddit.com/r/shutterencoder/comments/kfgcff/hardware_encoding_failed_with_nvenc_when_cq/) seems relevant.

**Comment by 7hr08ik** [comment]
Hi,

I've been having the same issue as OP. Im running tdarr on Unraid, with my GPU node on  another rig.
I copied the Tdarr_Plugin_MC93_Migz1FFMPEG plugin, changed the line 286 to alter `-rc:v vbr_hq` to just `-rc:v vbr` and its working again.

Unfortunately i do not know if this will be making my videos better/worse/the same. So i am not running the node until i figure it out

**Comment by HaveAGitGat** [comment]
For the last 2 months Tdarr Docker has been using Jellyfin ffmpeg so this issue should be resolved. If using Linux native then you need to install ffmpeg and use that rather than using the static binary that Tdarr comes with.

**Comment by wormvortex** [comment]
Got the issue today since the latest docker pull. Wasn't getting it before. 7hr08ik's comment worked but I'm not sure if it effects the quality?

**Comment by tyriekfv** [comment]
I have this same issue.  Rolling back to 2.00.14 fixed the error.

**Comment by HaveAGitGat** [comment]
@wormvortex @tyriekfv the only change between .14 and .15 with FFmpeg was this upgrade in the Linux x64 image: https://github.com/HaveAGitGat/Tdarr/issues/555

I downgraded FFmpeg in .15.1 so if you pull that image it should work as before. Let me know if you have any issues.

**Comment by HaveAGitGat** [comment]
For compatibility reasons, I recently merged a plugins PR which removes the use of vbr_q (affects 6 plugins).

I compared the difference and could not see any. Not using vbr_hq results in a very slight increase in file size. Example:

Input:
H264 (36 MB)

Output:
H265 - with vbr_hq (17.2 MB)
H265  - without vbr_hq (17.9 MB)

You can compare the input and output samples here (some might not play/show video in the browser but will when downloaded):

https://gofile.io/d/rZUGab
