### ISSUE TITLE
Node ID can't be numbers only

### ISSUE THREAD

**Issue by mearl72** [HaveAGitGat/Tdarr#494]
**Describe the bug**
I was trying to add a node with the name "3070" but when the node started up it kept showing "Node registered" every 4 seconds. In the web GUI the node would appear and then immediately disappear every 4 seconds. Once I changed the name to anything that contained letters (dashes seemed to work also) alongside numbers, the application would stay registered.

No errors showed up in the logs. I turned on verbose but nothing showed except `[INFO] Tdarr_Server - verbose:[0s] Pushing files to DB end`

I'm not sure if this is expected behavior but it threw me off for a couple of hours haha.

**To Reproduce**
Change `nodeID` option to only numbers in `Tdarr_Node_Config.json`

**Expected behavior**
I would expect the node to start up, register with the server, and stay registered.

 - Server's OS: Docker
 - Node's OS: Windows 10
 - Browser: Chrome
 - Version: 2.00.10

**Comment by HaveAGitGat** [comment]
fixed in 2.00.11
