### ISSUE TITLE
Handbrake update

### ISSUE THREAD

**Issue by rafisher79** [HaveAGitGat/Tdarr#495]
Is it possible to update handbrake?  The newest version gives a colorspace option which would allow transcoding from HDR to SDR, which would be super helpful. Thanks!

**Comment by HaveAGitGat** [comment]
HandBrake has been updated on all platforms except linux_x64 as I came across a bug (reported) in it which has been fixed for the next HandBrake release so will wait until then.

**Comment by HaveAGitGat** [comment]
Bumped handbrake to 1.5.1 for 2.00.14

https://github.com/HaveAGitGat/Tdarr/blob/4792c6bb5d9d23219676c0ca5eb763a9a42a4b7c/Dockerfile#L13
