### ISSUE TITLE
Audio files being recognized as video

### ISSUE THREAD

**Issue by pinpspinps** [HaveAGitGat/Tdarr#496]
Hello,
I added my audio files in Tdarr but the flac and mp3 files are recognized as video files.
It's the same problem as here https://github.com/HaveAGitGat/Tdarr/issues/88

![image](https://user-images.githubusercontent.com/88548939/135147328-c05a35f1-86db-4cda-aef6-54237b78f719.png)

I think it's because of this that I see in the file information.

![image](https://user-images.githubusercontent.com/88548939/135147578-d3a7bad6-0c29-4c4e-9726-140826a1dbcd.png)

Do you have any idea what I can do to correct the problem?

**Comment by HaveAGitGat** [comment]
Yeah it’s because of that stream. I’ll work on a fix for .12.

**Comment by HaveAGitGat** [comment]
This has been fixed, the changes are now in the 2.00.12 acceptance containers/packages: https://tdarr.io/docs/pre-releases

**Comment by pinpspinps** [comment]
Will you be able to update the docker container for ARM architecture on dockerhub when the version is ready please?

**Comment by HaveAGitGat** [comment]
Yes will do. The linux_arm and linux_arm64 packages are available if you need them. Will updates the containers this week:

https://f000.backblazeb2.com/file/tdarrs/versions/2.00.12/linux_arm/Tdarr_Server.zip

https://f000.backblazeb2.com/file/tdarrs/versions/2.00.12/linux_arm/Tdarr_Node.zip

https://f000.backblazeb2.com/file/tdarrs/versions/2.00.12/linux_arm64/Tdarr_Server.zip

https://f000.backblazeb2.com/file/tdarrs/versions/2.00.12/linux_arm64/Tdarr_Node.zip

**Comment by HaveAGitGat** [comment]
2.00.12 is now out. Let me know if you have any issues.

**Comment by pinpspinps** [comment]
Hello, 
I updated to 2.00.12 but my audio files are still recognized as video files.
Is there anything I can do to make them appear as audio files?

**Comment by HaveAGitGat** [comment]
> Hello,
> I updated to 2.00.12 but my audio files are still recognized as video files.
> Is there anything I can do to make them appear as audio files?

Have you rescanned your files? The updates only apply to newly scanned files.

**Comment by pinpspinps** [comment]
yes, it's ok with a fresh scan.
thank you
