### ISSUE TITLE
Pipe files to nodes

### ISSUE THREAD

**Issue by stefanh12** [HaveAGitGat/Tdarr#499]
**Is your feature request related to a problem? Please describe.**
Today, the nodes needs to be configured to have read access to the libraries and read/write to the tmp folder. This means that the mapping needs to be correct and clients with nodes needs access to library and tmp folder
**Describe the solution you'd like**
Security and easy of use would greatly increase if the server would pipe the library files to the nodes for processing and back for storage. That way, the nodes needs no file mapping at all.
**Describe alternatives you've considered**
Easy of use would greatly increase if the files where piped to and from the client instead of the client having network SAMBA access.
**Additional context**

**Comment by HaveAGitGat** [comment]
2.27.01 just released adds a new node type 'unmapped' nodes, more info here: https://docs.tdarr.io/docs/nodes/nodes#unmapped
