### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#5]
Have installed node js on windows and also MongoDB
Downloaded Windows .7z file and unzipped.

The next instruction says to run command prompt in the root folder.

First Question: Which folder?

Second Question: I am getting the following error when I run the commands stated:

PS C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle> set MONGO_URL=mongodb://localhost:27017/Tdarr
PS C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle> set PORT=8265
PS C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle> set ROOT_URL=http://localhost/
PS C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle> node main.js
C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\node_modules\fibers\fibers.js:90
                                        return fn.apply(this, arguments);
                                                  ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages\meteor.js:1378:11)
    at runWebAppServer (packages/webapp/webapp_server.js:771:18)
    at webapp_server.js (packages/webapp/webapp_server.js:1175:1)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\packages\webapp.js:1588:15
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\packages\webapp.js:1597:3
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\boot.js:419:36
    at Array.forEach (<anonymous>)
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\boot.js:228:19
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\boot.js:479:5
    at Function.run (C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\profile.js:510:12)
    at C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle\programs\server\boot.js:478:11
PS C:\Tdarr\Tdarr-Windows-01-pre-alpha\bundle>

**Comment by HaveAGitGat** [comment]
Hi @martinkeat . The root folder is the folder with main.js in. It seems you are in the correct folder (inside bundle).

Which version of Windows are you on?

**Comment by HaveAGitGat** [comment]
@martinkeat you need to run the command from Command Promt (CMD), not Powershell. That should solve your issue.

**Comment by martinkeat** [comment]
Got it! Brilliant! 

Two questions: 1. Will this transcode the new file into the same folders?
                       2. Can I get it to delete the original after transcoding?

**Comment by HaveAGitGat** [comment]
It transcodes new files into the transcode cache folder and then replaces the original files afterwards. So it automatically deletes the original file. 

FYI the version you have now is massively behind the current build but I’ll be updating the Windows, Linux and macOS versions in the next couple of days.

**Comment by martinkeat** [comment]
OK. What CLI arguments do I need to make here. I want the transcode to be HD but as small a file size as possible.

**Comment by martinkeat** [comment]
Or will default suffice?

**Comment by HaveAGitGat** [comment]
It’s easiest to go with a HandBrake H265 preset for small files sizes but know that the transcoding will take much longer for H265.

Have a look at the presets here:

https://handbrake.fr/docs/en/latest/technical/official-presets.html

So you could for example put the following in the CLI argument box:

-Z “ H.265 MKV 1080p30”

Then make sure to tick the ‘hevc’ box in the ‘don’t transcode files already in these codecs’ section so that Tdarr won’t transcode files already in h265.

**Comment by martinkeat** [comment]
Cool. One last stupid question. Will Tdarr launch automatically on startup, if not, how do I launch it now that it is all setup.

**Comment by HaveAGitGat** [comment]
No problem.

The easiest way is using a .bat file. So open up notepad and add the following:

set MONGO_URL=mongodb://localhost:27017/Tdarr
set PORT=8265
set ROOT_URL=http://localhost/
node main.js

Save that as say Tdarr.bat next to main.js

Then create a shortcut of Tdarr.bat and add the shortcut to your Windows Startup programs folder.

**Comment by martinkeat** [comment]
Getting a lot of failed transcodes. Error says invalid preset h.265

**Comment by HaveAGitGat** [comment]
What did you put inside the CLI argument/preset box?

**Comment by martinkeat** [comment]
![image](https://user-images.githubusercontent.com/8785775/65824201-d6324c80-e25c-11e9-8fa2-7459c2f4b289.png)

**Comment by martinkeat** [comment]
![image](https://user-images.githubusercontent.com/8785775/65824214-11348000-e25d-11e9-83e5-b6ef32f6cc97.png)

**Comment by HaveAGitGat** [comment]
@martinkeat  sorry was just investigating that as I was truly baffled. It seems that when I copied the command on my phone it copied some hidden line breaks which prevented it from working. Copy the following:

-Z "H.265 MKV 1080p30"

It looks the same but there are no line breaks hidden inside.

**Comment by martinkeat** [comment]
Just an update. All seems to be working fine. Await the update version with baited breath.
