### ISSUE TITLE
[Feature Request] Ability to Reorder Nodes in GUI

### ISSUE THREAD

**Issue by julianrinaldi** [HaveAGitGat/Tdarr#505]
**Is your feature request related to a problem? Please describe.**
Currently the only way to change the order of how nodes are listed in the GUI is to stop and restart nodes in the correct order.

**Describe the solution you'd like**
The ability to change the order of nodes similar to how reordering libraries works

**Describe alternatives you've considered**
The ability to drag and drop nodes (and libraries) to change their order would be great.

**Comment by HaveAGitGat** [comment]
I’ll add this in .12 in the hope that Windows will one day allow me re-order task bar thumbnails without needing to use 7+ Taskbar Tweaker 🙂.

**Comment by HaveAGitGat** [comment]
Added some arrows similar to the library system for 2.00.12
![image](https://user-images.githubusercontent.com/43864057/144698947-ae292d66-cbea-42a2-b2eb-e5728d9e4174.png)

**Comment by julianrinaldi** [comment]
Thanks!

**Comment by julianrinaldi** [comment]
Just installed the new version. Thanks. My only other request would be to be able to lock them in a certain order, so that if a node restarts, the node goes back to its previous place in the list. I have a few nodes that randomly restart and I haven't been able to figure out why. They come right back up though, but then they're out of place. I assume this is probably a more complicated feature to implement though.
