### ISSUE TITLE
Docker Container (Server/Node w/GPU) + Win10 Node (Multiple GPUs)

### ISSUE THREAD

**Issue by TechD87** [HaveAGitGat/Tdarr#507]
Not exactly a "Problem", but a brick wall that I keep running into.
I currently have Tdarr setup in Unraid using both a server & node (w/GPU, specifically a P2000.
I've been running it using the SI1 videos for over a month, no issues.

After the same channel came out with a Windows Node video, I followed the same steps. I got the server to recognize and register the node, but it is not recognizing either of my GPUs (K4000) installed. 

When I attempt to turn on a GPU transcode in the Node section, it auto-fails. Looking at the error I'm getting:

**Stream mapping:

Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1 (copy)

Stream #0:2 -> #0:2 (copy)

Press [q] to stop, [?] for help

[hevc_nvenc @ 00000237f36afac0] No NVENC capable devices found

Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

Conversion failed!** 

I would assume the solution is to edit the FFMPEG in some fashion, but nothing is exactly precise with all of the scouring I've done on FB, Reddit, YT, and here.

In the future, I think it would be beneficial for there to be a clear documentation on how users with multiple GPUs in a single NODE or multiple NODES can get up and running fast without digging too deep in the code.

This is an amazing program that I took a long to hop on the bandwagon for. I've already saved over 5TB of space!

**Comment by HaveAGitGat** [comment]
Sorry for the late reply. Hmm strange, which Windows OS are you using? There aren’t any docs on that as FFmpeg/Handbrake normally work straight out of the box with nvenc on Windows.

And I’m redoing the documentation atm so will add that in. Thanks for the feedback 🙂.

**Comment by HaveAGitGat** [comment]
Just to confirm, NVENC is working fine with the packaged FFmpeg version that Tdarr comes with. Task manager shows the video encoder is being used:
![image](https://user-images.githubusercontent.com/43864057/152726451-55da2a5d-8198-498e-871d-e41f65e7c8b0.png)

Seems the K4000 isn't supported for h265 NVENC so that's most likely the issue:
https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding
