### ISSUE TITLE
Add option to show old and new file sizes in Staging section

### ISSUE THREAD

**Issue by KuroSetsuna29** [HaveAGitGat/Tdarr#508]
**Is your feature request related to a problem? Please describe.**
Sometimes the new re-encoded version results in a file size larger than the original, I have to manually check which is very tedious. Having the files size available quickly will help speed that up. 

**Describe the solution you'd like**
Option in settings, to enable if user wanted, to show old and new file sizes in Staging section similar to the Status section.

**Describe alternatives you've considered**
Another option is there a way to automatically mark the transcode failed if size is larger than original?

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
I've added the sizes in:
![image](https://user-images.githubusercontent.com/43864057/144184301-41134082-99cb-4f60-83da-97d7b6608b5d.png)

Would you mind trying this size check plugin? It will automatically mark items as failed if the new size is larger than the old size.
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/examples/Tdarr_Plugin_a9he_New_file_size_check.js
