### ISSUE TITLE
ERROR: "/dev/dri": no such file or directory.

### ISSUE THREAD

**Issue by ikrowni** [HaveAGitGat/Tdarr#509]
Trying to install the node in docker on windows but im getting this error.

docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

windows 11
RTX 2080
Ryzen 7 2700x
Docker Desktop

**Comment by supersnellehenk** [comment]
That's because `/dev/dri` is a Linux specific way of mounting a GPU. If you want to use your GPU I recommend installing the node on Windows itself and not through Docker.

**Comment by ikrowni** [comment]
Thank you for the help. That explains it. Do you happen to know how to run the tdarr node as a service without the terminal appearing?

**Comment by supersnellehenk** [comment]
People have used NSSM, but it's kinda hit or miss regarding permissions. I've got no clue how to set it up as a service beyond that.

**Comment by ikrowni** [comment]
thanks again.
