### ISSUE TITLE
Base URL doesn't appear to work

### ISSUE THREAD

**Issue by nyid** [HaveAGitGat/Tdarr#51]
Hello! I've upgraded the tdarr_aoi docker on unraid to 1.005 and the base url env variable doesn't appear to work based on the instructions provided in the feature request. This is the docker variable I'm passing in as a test:

 -e 'BASE'='/base'

![image](https://user-images.githubusercontent.com/5327772/68005295-6ab41400-fc3a-11e9-851b-49e96acfcdba.png)

When navigating to "http://localhost:8265/base/stats", a blank page comes up with the menu on top. The menu still points back to the root "/", for example if I select Stats on the menu, the url is "http://localhost:8265/stats".

**Comment by HaveAGitGat** [comment]
Hi sorry about this, it's working fine on the tdarr (Alpine) container and on Windows, just trying to work out why it's not working on tdarr_aio

**Comment by nyid** [comment]
No worries, I appreciate you listening to feedback! Funny I was on Alpine and switched to aio before upgrading. 😛

**Comment by HaveAGitGat** [comment]
Haha just your luck. Yeah it seems the environment variables aren’t working on the Ubuntu container as the ‘DATA’ variable doesn’t work either. Will have a look later today to see what’s causing this.

**Comment by HaveAGitGat** [comment]
Still no luck with this, I’ll need to ask on the Docker forum.

**Comment by HaveAGitGat** [comment]
Waiting to see if anyone replies here else I’ll come up with a different method to set base path:

https://forums.docker.com/t/passing-env-variables-to-ubuntu-container/83741

**Comment by HaveAGitGat** [comment]
No update on that request so I've created a secondary method for setting base URL.

Save this as 'env.json' in your Tdarr/Data folder (change baseTest to your preferred URL):

```
{
    "BASE":"/baseTest"
}
```

When 1.006 is released later this week (Friday) it will load the file.

**Comment by HaveAGitGat** [comment]
Also in 1.006 you scan specify the base URL on the new 'Options' tab:

![image](https://user-images.githubusercontent.com/43864057/68349807-4c488f80-00f6-11ea-90b5-c27b10cf8643.png)

**Comment by Flippage** [comment]
Can't set the Base URL through the options tab. No matter what I put in, it doesn't stick after I restart Tdarr.

Also, tried the env.json file as suggested above, but still doesn't work.

Every time I launch Tdarr it has default settings with no URL Base.

Any ideas?
