### ISSUE TITLE
Cannot install docker image on raspberry pi 4 (armv8)

### ISSUE THREAD

**Issue by Footsiefat** [HaveAGitGat/Tdarr#510]
```
[217]: ../src/util.cc:185:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Starting Tdarr_Server
[232]: ../src/util.cc:185:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
Starting Tdarr_Server
```

**Comment by supersnellehenk** [comment]
Could you use the issue template? This says nothing at all.

**Comment by Footsiefat** [comment]
Extra context:
When installing Tdarr_server on a raspberry pi 4 (armv8) using the docker image which supports armv7, it shows the following errors above when trying to run tdarr. What is the correct way of running tdarr on a raspberry pi 4?

**Comment by Footsiefat** [comment]
Okay guys I figured out how to get it running on a armv8 raspberry pi. First download the armv7/armhf updater binary, enable armhf librarys on the pi through dpkg, install armhf version of libc (DONT OVERRIDE) then execute the binary and it all works well.
