### ISSUE TITLE
Tdarr Install Node Not Registering

### ISSUE THREAD

**Issue by Fahmula** [HaveAGitGat/Tdarr#512]
I have Tdarr working perfectly fine in docker but I'm trying to install it to an Debian VM and I can't get pass this issue.

(node:1677) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:8266
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(Use `Tdarr_Node --trace-warnings ...` to show where the warning was created)
(node:1677) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1677) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-12-06T03:06:14.620] [ERROR] Tdarr_Node - Server not alive IP:0.0.0.0 PORT:8266

What's worst if that I watched the installation video and tried a pop os VM and it works no problem. Is there anything I'm missing?

**Comment by HaveAGitGat** [comment]
Hi pretty sure you can ignore that error, happens to me too on a Windows node when the Server is not running/contactable by the Node.

So double-check the Node machine can access the IP/PORT of the server.

**Comment by Fahmula** [comment]
The node and the server is on the same machine. I followed the guide and make sure the server is running. I can access the website but the node just won't connect to the server.

**Comment by supersnellehenk** [comment]
> The node and the server is on the same machine. I followed the guide and make sure the server is running.
> 
> I can access the server gui but the node just won't connect to the server.

So is this about a Debian node not being able to connect to a Docker server or what's the system configuration here?

**Comment by Fahmula** [comment]
> > The node and the server is on the same machine. I followed the guide and make sure the server is running.
> > I can access the server gui but the node just won't connect to the server.
> 
> So is this about a Debian node not being able to connect to a Docker server or what's the system configuration here?

Sorry I wasn't clear enough in the OP. The server and the node is running on the same system. I just mention docker because I have tdarr working there.

**Comment by supersnellehenk** [comment]
> [https://imgur.com/IWAYLwm](url)
> 
> here's a picture showing the server running and the node not connecting.

The server isn't running, because you CTRL+C'd out of it, terminating it. You need to open a second terminal and run the node in there.

**Comment by Fahmula** [comment]
> > [https://imgur.com/IWAYLwm](url)
> > here's a picture showing the server running and the node not connecting.
> 
> The server isn't running, because you CTRL+C'd out of it, terminating it. I advise you use screen, as explained here: https://linuxize.com/post/how-to-use-linux-screen/. So basically you type `screen -S tdarr_server ./Tdarr_Server`, then you press `ctrl+a`, then `d` to detach from that screen, allowing it to run in the background. Then you can start the node in the same terminal.

Silly me! that was the issue. Thank you!!

**Comment by HaveAGitGat** [comment]
Please it’s sorted 🙂.
