### ISSUE TITLE
Transcoding error

### ISSUE THREAD

**Issue by Fahmula** [HaveAGitGat/Tdarr#513]
I can't figure out why I'm getting this error;

[hevc_vaapi @ 0x55829f27f700] No usable encoding entrypoint found for profile VAProfileHEVCMain (17).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

The output of vainfo shows the it supports the profile.

root@TdarrDocker:~# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

What's even weirder is it I install docker on the same system tdarr works fine. 

I want to get tdarr working without using docker.

**Comment by Fahmula** [comment]
Any help?

**Comment by HaveAGitGat** [comment]
It's helpful if you fill out the bug report with all the details as we can't even see what ffmpeg command you're using or what linux distro you're on :).

Probably to do with the ffmpeg binary.

Install ffmpeg manually  `apt-get install -y ffmpeg`

And then in the `Tdarr_Node_Config.json` file set ffmpegPath to `ffmpeg`.

Hopefully that should work.

**Comment by Fahmula** [comment]
Sorry for the lack of information. I'm testing tdarr on a promox container using debian 11.

**Comment by HaveAGitGat** [comment]
Ok thanks, reopen if needed.
