### ISSUE TITLE
mp4 generate files can't preview on Macos

### ISSUE THREAD

**Issue by dagar21** [HaveAGitGat/Tdarr#514]
Hello i have a problem with mp4 and Apple. If i convert the files to mp4 with h265 the mp4 file can't preview and don't work with Quicktime. From what I understand transcode-video marks the video stream has hev1, but it actually needs to be marked as hvc1 in order to be recognized by Quick Time and preview function.

**Comment by HaveAGitGat** [comment]
Check this out: https://stackoverflow.com/questions/32152090/encode-h265-to-hvc1-codec

So you need to add the tag `-tag:v hvc1` to the ffmpeg command you're using. 

Hope that helps.
