### ISSUE TITLE
Streams Array  / Codec identification issue

### ISSUE THREAD

**Issue by danwestness** [HaveAGitGat/Tdarr#516]
**Describe the bug**
Tdarr indicating video codec based on array position [0].
This causes plugins to match these media files as <> codec

**To Reproduce**
Observable in search output

**Expected behavior**
Video codec is evaluated properly.
You can see in the attached screenshot that this video file is in fact in h264 codec as are the others, but for some reason it's listed in the 3rd position in the Streams array so Streams[0] = ac3 and therefore my pluging matches that this is NOT h264 and begins transcoding it

**Screenshots**
![image](https://user-images.githubusercontent.com/32807749/145272900-108a924a-0a4d-495d-8d88-b6820e0889df.png)

**Comment by HaveAGitGat** [comment]
Which plug-in are you using? 

The next version 2.00.12 fixes the main codec identification but most plugins still expect the video stream to be in stream 0 hence the reorder streams plugin is a default plugin at the top of the plug-in stack when you create a new library. 

Re-add the reorder streams plugin and it should fix the issue.

**Comment by HaveAGitGat** [comment]
2.00.12 is now out so let me know if you have any issues :)
