### ISSUE TITLE
Tdarr_Server.exe entry procedure point GetHostNameW could not be located in W32_32.dll

### ISSUE THREAD

**Issue by doczong** [HaveAGitGat/Tdarr#520]
**Describe the bug**
On startup of server version .12 (was working in .11)

**To Reproduce**
Start service, windows 7, does not start.

Pro user, upgraded to get the MP3 issue fixed with embedded videos in the MP3s, encountered this issue.  Server will not start.

Same with Node.  Issue also appear launching tdarr_node.exe

**Comment by doczong** [comment]
So, that's it then?  

Great project, it got me through what I needed to do and saved a few TB, but I guess I will have to cancel and exit stage left.

**Comment by doczong** [comment]
> Hi,
> 
> [nodejs/node#40353](https://github.com/nodejs/node/issues/40353)
> 
> Windows 7 reached end of life almost 2 years ago so it’s not being supported by a lot of projects/dependencies anymore unfortunately.

I have a docker installation, I assume then without getting too far offtopic, I can just copy the "server" dir and db subdirs to the linux box and it should make it so I dont have to rescan my whole 60000 item libraries?

**Comment by supersnellehenk** [comment]
> > Hi,
> > [nodejs/node#40353](https://github.com/nodejs/node/issues/40353)
> > Windows 7 reached end of life almost 2 years ago so it’s not being supported by a lot of projects/dependencies anymore unfortunately.
> 
> I have a docker installation, I assume then without getting too far offtopic, I can just copy the "server" dir and db subdirs to the linux box and it should make it so I dont have to rescan my whole 60000 item libraries?

You'll have to rescan anyways, because the paths don't match anymore between a native Windows installation and docker.

**Comment by doczong** [comment]
> 

Merci... that... is a pain in the rear lol.

**Comment by supersnellehenk** [comment]
> Edit: THe files are on a NAS all pointing to the \ip.address.of.nas\ - rescan still required?

In that case, it *should* work I believe. Only one way to find out. If it doesn't, rescanning doesn't take too long if you have mediaInfo and closed captions disabled.

**Comment by doczong** [comment]
> > Edit: THe files are on a NAS all pointing to the \ip.address.of.nas\ - rescan still required?
> 
> In that case, it _should_ work I believe. Only one way to find out. If it doesn't, rescanning doesn't take too long if you have mediaInfo and closed captions disabled.

Spot on.  I'll give it a shot when I am in front of the installation tonight or tomorrow and will update for posterity's sake.

**Comment by HaveAGitGat** [comment]
Believe me, if I could still use Windows 7 I would as I'm not a fan of Windows 11 at all.

Yeah I was going to suggest using Docker if that's still supported on Windows 11.

Obviously I could undo the NodeJS update but I'm not sure it's the best move to ignore the security and stability updates of the newer versions.

Hope it goes well on Docker 👍 .

**Comment by doczong** [comment]
Alright, dumb question, or not.  Tdarr installed into docker.  Restored from last nights backup. But I forgot... docker can't see out past the container.  So it can't see my NAS which is on another hardware device on the lan.  So... works... but doesn't.  Any ideas?

**Comment by tordenflesk** [comment]
> Believe me, if I could still use Windows 7 I would as I'm not a fan of Windows 11 at all.

Enablin ESU updates on W7 is a trivial task.

**Comment by tordenflesk** [comment]
> Any way I could downgrade my windows install to .11 for the time being?
I happened to have a copy of .10
https://www.transfernow.net/dl/20211213LYJSDkG5

**Comment by HaveAGitGat** [comment]
To use .11 just set the required version to 2.00.11 in the 'requiredVersion' of the Tdarr Updater config. Or you can get the direct download links to the modules here: https://tdarr.io/docs/installation/windows-linux-x64-arm-and-macos

Re-open if needed.

**Comment by CollinChaffin** [comment]
Do you have a working link to 2.00.11 for windows? It's not in the json on the download site the oldest is only 2.00.13 for windows.

**Comment by tordenflesk** [comment]
https://we.tl/t-aj9f8zCop0

**Comment by madxcream** [comment]
I'm also looking for the link to 2.00.11 for windows. The above shared link is no longer working. Thanks.

**Comment by tordenflesk** [comment]
https://gofile.io/d/PfW9Lh
