### ISSUE TITLE
Tdarr_Node 2.00.12: ffmpeg is missing or no longer includes libfdk_aac audio encoder

### ISSUE THREAD

**Issue by daverichards78** [HaveAGitGat/Tdarr#521]
It seems the libfdk_aac encoder is missing or no longer included in ffmpeg in the latest release of Tdarr_Node.

I've reverted my Docker containers back to the previous images and all is well on my system for now. But I thought this was worth bringing to someone's attention.

I noticed when I updated my containers and I had a lot of encode errors -- the info "i" on the failed encodes said something to the effect of, "plugin did not produce the expected output file" and also included a ffmpeg error output something like, "ffmpeg: libfdk_aac is not a valid encoder." Sure enough, I opened a Bash shell inside the container and ran "ffmpeg -encoders | grep libfdk" and the codec is not listed.

Was this done in error with this release or was it intentional? I saw the release notes mentioned a new ffmpeg build in 2.00.12. I'm hoping this was just an oversight in the new ffmpeg build used in the container image.

**Comment by HaveAGitGat** [comment]
I updated FFmpeg to the latest version as seen here:
https://github.com/HaveAGitGat/Tdarr/blob/master/Dockerfile

But yeah seems it's missing a few codecs so will probably go with Jellyfin as that has been recommended.

**Comment by HaveAGitGat** [comment]
The container has been using Jellyfin ffmpeg for a couple of weeks now but it doesn't have libfdk_aac so this might be something that people need to add manually or we have 2 different ffmpeg versions in the container.

**Comment by HaveAGitGat** [comment]
Will need to open a request here to have it added in:
https://github.com/jellyfin/jellyfin-ffmpeg
