### ISSUE TITLE
Subtitle encoding currently only possible from text to text or bitmap to bitmap

### ISSUE THREAD

**Issue by CappiSteijns** [HaveAGitGat/Tdarr#523]
**Describe the bug**
I am using Tdarr on my Unraid server to transcode my tv shows and movies to get more direct plays trough Plex.

When using the community plugin "Tdarr_Plugin_z1ab_TheRealShadoh_FFmpeg_Subs_H264_Fast" I encounter the following error which results in a lot of cancelled transcodes. (not all of them)

<details>
  <summary>click to open the ERROR LOG</summary>
  NodeID: CappiNode

Command:

ffmpeg -i /mnt/movies/hd/Fury (2014)/Fury (2014) Remux-1080p.mkv -map_metadata -1 -map 0:v -map 0:s? -map 0:a -c:v copy -c:a aac -c:s mov_text /temp/Fury (2014) Remux-1080p-TdarrCacheFile-VX8iBxCWG.mp4

Last 200 lines of CLI log:

CS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:9(fin): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Finnish

BPS-eng : 21028

DURATION-eng : 02:08:13.269000000

NUMBER_OF_FRAMES-eng: 2612

NUMBER_OF_BYTES-eng: 20221893

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:10(fre): Subtitle: hdmv_pgs_subtitle

Metadata:

title : French

BPS-eng : 19335

DURATION-eng : 02:13:41.847000000

NUMBER_OF_FRAMES-eng: 2540

NUMBER_OF_BYTES-eng: 19388263

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:11(ger): Subtitle: hdmv_pgs_subtitle

Metadata:

title : German

BPS-eng : 26337

DURATION-eng : 02:08:12.851000000

NUMBER_OF_FRAMES-eng: 3018

NUMBER_OF_BYTES-eng: 25326442

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:12(gre): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Greek

BPS-eng : 26463

DURATION-eng : 02:14:18.801000000

NUMBER_OF_FRAMES-eng: 2930

NUMBER_OF_BYTES-eng: 26657868

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:13(hin): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Hindi

BPS-eng : 22252

DURATION-eng : 02:03:52.050000000

NUMBER_OF_FRAMES-eng: 2956

NUMBER_OF_BYTES-eng: 20673164

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:14(ice): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Icelandic

BPS-eng : 26419

DURATION-eng : 02:08:13.269000000

NUMBER_OF_FRAMES-eng: 2820

NUMBER_OF_BYTES-eng: 25406325

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:15(ita): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Italian

BPS-eng : 25838

DURATION-eng : 02:03:52.050000000

NUMBER_OF_FRAMES-eng: 2954

NUMBER_OF_BYTES-eng: 24004426

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:16(jpn): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Japanese

BPS-eng : 17690

DURATION-eng : 02:03:15.262000000

NUMBER_OF_FRAMES-eng: 2710

NUMBER_OF_BYTES-eng: 16353518

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:17

(kor): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Korean

BPS-eng : 14664

DURATION-eng : 02:07:01.197000000

NUMBER_OF_FRAMES-eng: 2960

NUMBER_OF_BYTES-eng: 13970462

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:18(nor): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Norwegian

BPS-eng : 20099

DURATION-eng : 02:08:13.185000000

NUMBER_OF_FRAMES-eng: 2540

NUMBER_OF_BYTES-eng: 19328509

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:19(por): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Brazilian

BPS-eng : 24558

DURATION-eng : 02:07:00.905000000

NUMBER_OF_FRAMES-eng: 2916

NUMBER_OF_BYTES-eng: 23394618

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:20(por): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Iberian

BPS-eng : 25851

DURATION-eng : 02:08:13.227000000

NUMBER_OF_FRAMES-eng: 2734

NUMBER_OF_BYTES-eng: 24860514

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:21(rus): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Russian

BPS-eng : 26924

DURATION-eng : 02:06:59.696000000

NUMBER_OF_FRAMES-eng: 2960

NUMBER_OF_BYTES-eng: 25644186

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:22(spa): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Castilian

BPS-eng : 21043

DURATION-eng : 02:14:20.511000000

NUMBER_OF_FRAMES-eng: 2880

NUMBER_OF_BYTES-eng: 21202361

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:23(spa): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Latin American

BPS-eng : 25319

DURATION-eng : 02:08:13.227000000

NUMBER_OF_FRAMES-eng: 2926

NUMBER_OF_BYTES-eng: 24348511

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng:

2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:24(swe): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Swedish

BPS-eng : 18191

DURATION-eng : 02:14:18.425000000

NUMBER_OF_FRAMES-eng: 1827

NUMBER_OF_BYTES-eng: 18324586

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:25(tur): Subtitle: hdmv_pgs_subtitle

Metadata:

title : Turkish

BPS-eng : 27473

DURATION-eng : 02:03:52.050000000

NUMBER_OF_FRAMES-eng: 2954

NUMBER_OF_BYTES-eng: 25522688

_STATISTICS_WRITING_APP-eng: mkvmerge v55.0.0 ('Waiting For Space') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2021-04-03 14:40:01

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:26: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x360 [SAR 96:96 DAR 16:9], 90k tbr, 90k tbn, 90k tbc (attached pic)

Metadata:

filename : cover.jpg

mimetype : image/jpeg

Stream mapping:

Stream #0:0 -> #0:0 (copy)

Stream #0:26 -> #0:1 (copy)

Stream #0:3 -> #0:2 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:4 -> #0:3 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:5 -> #0:4 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:6 -> #0:5 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:7 -> #0:6 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:8 -> #0:7 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:9 -> #0:8 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:10 -> #0:9 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:11 -> #0:10 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:12 -> #0:11 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:13 -> #0:12 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:14 -> #0:13 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:15 -> #0:14 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:16 -> #0:15 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:17 -> #0:16

(hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:18 -> #0:17 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:19 -> #0:18 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:20 -> #0:19 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:21 -> #0:20 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:22 -> #0:21 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:23 -> #0:22 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:24 -> #0:23 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:25 -> #0:24 (hdmv_pgs_subtitle (pgssub) -> mov_text (native))

Stream #0:1 -> #0:25 (dts (dca) -> aac (native))

Stream #0:2 -> #0:26 (ac3 (native) -> aac (native))

Subtitle encoding currently only possible from text to text or bitmap to bitmap

</details>

**To Reproduce**
- Make a library and at the tab transcode options use the following community plugin: "Tdarr_Plugin_z1ab_TheRealShadoh_FFmpeg_Subs_H264_Fast"
- Let Tdarr transcode some files and wait for the error described as above.

**Expected behavior**
The plugin should make the video file mp4, aac and should keep the subs.

**Screenshots**
My transcode options:
![afbeelding](https://user-images.githubusercontent.com/84481241/146532252-05d79f35-e061-468a-ba1f-d1df4d594b77.png)

Status of the files (removed the tv episodes from ''transcode: Error/Cancelled") So 53 movies already got cancelled.
![afbeelding](https://user-images.githubusercontent.com/84481241/146532615-1e0eb76b-410d-4365-8535-7b32a9df43aa.png)

**Please provide the following information:**
- Config files
[configs.zip](https://github.com/HaveAGitGat/Tdarr/files/7734480/configs.zip)

- Log files 
[logs.zip](https://github.com/HaveAGitGat/Tdarr/files/7734485/logs.zip)

**Additional context**
I really like this plugin because it makes the file mp4, change the audio to AAC and keeps the subs.
What could I do to make sure this plugin gets more succes transcodes?
Or is there another plugin that does the same but gets me more succes?

Thanks for any help!

**Comment by HaveAGitGat** [comment]
Please keep plugin issues in the plugin repo :) https://github.com/HaveAGitGat/Tdarr_Plugins

You can't convert image subtitles to text subtitles with FFmpeg so you'd need to keep in mkv or remove them.
