### ISSUE TITLE
[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

### ISSUE THREAD

**Issue by wgstarks** [HaveAGitGat/Tdarr#524]
**Describe the bug**
I can't connect to the webui on version 2.00.12. The page opens but just get a spinner with a timer and the text "Is TDARR running?". I can see from the cpu activity that TDARR is running. Reverted to version 2.00.11 and that seems to have corrected the error.

**To Reproduce**
Open TDARR in browser.

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
- [32m[2021-12-19T07:55:42.960] [INFO] Tdarr_Server - [39mrAZ1LEx0H: Sending files for scanning, library :rAZ1LEx0H
[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /socket.io/?EIO=4&transport=polling&t=NtIojl2 from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v2/cruddb from 10.0.1.20:8265 to http://10.0.1.20:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
 [32m[2021-12-19T08:18:54.500] [INFO] Tdarr_Server - [39mrAZ1LEx0H: File detected, adding to queue:/mnt/media/XBMC/Torrents/The Expendables 3 (2014)/The Expendables 3 (2014).mkv [32m[2021-12-19T08:19:13.172] [INFO] Tdarr_Server - [39mrAZ1LEx0H: Sending files for scanning, library :rAZ1LEx0H
[91m[2021-12-19T08:20:15.792] [ERROR] Tdarr_Server - [39mNode is not alive ID:node_1 IP:10.0.1.20 PORT:8267. Removing.
 [cont-finish.d] executing container finish scripts... [cont-finish.d] done. [s6-finish] waiting for services. [s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

 - OS: unRAID 6.9.2
 - Browser Safari
 - Version 2.00.12

**Comment by HaveAGitGat** [comment]
Please post your Tdarr server config.

**Comment by wgstarks** [comment]
`{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "10.0.1.20",
  "handbrakePath": "",
  "ffmpegPath": ""
}`

**Comment by HaveAGitGat** [comment]
Thanks.

It might be that it's held up while deleting a folder called `DB3` which was large but not used anymore. You can delete it manually at this path (where the server app data is):
![image](https://user-images.githubusercontent.com/43864057/147417043-34440c8a-ce39-44c7-a296-80f098be761b.png)

Haven't had other reports of this issue so hopefully it's that.

**Comment by HaveAGitGat** [comment]
Feel free to reopen if the above solution does not work for you.

**Comment by HaveAGitGat** [comment]
Will move this under here:
https://github.com/HaveAGitGat/Tdarr/issues/532
