### ISSUE TITLE
Tdarr_node (windows) re-creates original config, doesn't connect to server

### ISSUE THREAD

**Issue by Shadzae** [HaveAGitGat/Tdarr#525]
**Describe the bug**
Tdarr_note, when it turns on, redownloads plugins and along the way, re-downloads the original tdarr_node_configuration.json. It will backup the current one to "config_backup.json". However, because the original is set to 0.0.0.0, it will then look for a server there and error continuously.

**To Reproduce**
Install Tdarr win, update, edit tdarr_node_config.json with custom values, run tdarr_node

**Expected behavior**
I would expect it to connect to the server specified in _config.json

**Screenshots**
![tdarr error](https://user-images.githubusercontent.com/76454219/146713592-cff66372-0cbf-471d-bc74-47ccfc235f1a.png)

**Please provide the following information:**
- Config files
![tdarr config](https://user-images.githubusercontent.com/76454219/146713685-a6acc00c-84bf-4300-927a-59165299124e.png)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows 10 x64
 - Browser Chrome
 - Version 2.00.12

**Additional context**
I followed SpaceInvaderOne's videos on how to set this up on an Unraid server, and then on Windows as a node for an Unraid server.

**Comment by HaveAGitGat** [comment]
Hi as mentioned on Discord this is due to you entering invalid JSON. A single backslash acts as an escape character so `"U:\"` is escaping the double quotes (this is why Notepad++ has greyed it out for you). Use double backslash: `"U:\\"`
