### ISSUE TITLE
http callback status not added to infoLog

### ISSUE THREAD

**Issue by goofballtech** [HaveAGitGat/Tdarr#526]
**Is your feature request related to a problem? Please describe.**
I am writing a plugin that uses Plex's API to force a folder fresh after transcode rather than the other ones that need additional programs or dockers. In this plugin i hit the API of the plex server to refresh a given folder. The response then give a hint as to if the refresh was successful or not based on the response status codes. 200,, 401, 404, etc. 

if i do the below, the responses in the check reply function are never added because TDarr has moved on before the request resolves (i'm assuming this piece since it works fine in node directly)

```javascript
    http.get(fullUrl, (res) => {
      checkReply(res.statusCode, redactedUrl)
      return response
    }).on('error', (e) => {
      response.infoLog += `We have encountered an error: ${e}`
      return response
    });
```

**Describe the solution you'd like**
i would like for the program to receive these response codes properly so i may added a success/error message to the user facing display. 

**Describe alternatives you've considered**
i have tried a few different way to do it. Async/await, callbacks, or making my own new Promise. 

**Additional context**
added a PR to plugins so the code can be viewed properly. https://github.com/HaveAGitGat/Tdarr_Plugins/pull/217

**Comment by supersnellehenk** [comment]
Issues like these should be done on https://github.com/HaveAGitGat/Tdarr_Plugins/issues/ instead of here.

**Comment by goofballtech** [comment]
ok. moved over there.
