### ISSUE TITLE
cron scheduling

### ISSUE THREAD

**Issue by wgstarks** [HaveAGitGat/Tdarr#529]
**Is your feature request related to a problem? Please describe.**
Not really a problem. More of an enhancement.

**Describe the solution you'd like**
I would like to be able to have TDARR run a "new scan" on a cron schedule from command line. Maybe this is already possible but I couldn't find any details.

**Comment by HaveAGitGat** [comment]
What would be the need for this? There’s already the hourly scan option in the library settings as well as the folder watch option.

**Comment by wgstarks** [comment]
You're absolutely right.😁 Completely forgot about folder watch even though I had it turned on. Was looking at the schedule tab. Am closing this.

**Comment by wgstarks** [comment]
Scheduling is already implemented.

![IMG_2687](https://github.com/HaveAGitGat/Tdarr/assets/5657833/e0c81697-6eea-4d2d-a640-5a6bf1d852b7)

**Comment by vakarian92** [comment]
How can I apply the scan to find new files to that? How can I have a daily scan and keep the scheduler on for other tasks?

It would be amazing to have a cron option here rather than on/off

![image](https://github.com/HaveAGitGat/Tdarr/assets/45591560/2dd9a6dc-7a6f-4505-b395-d5d46a450e9d)
