### ISSUE TITLE
Plugins read error

### ISSUE THREAD

**Issue by CandiMiiS** [HaveAGitGat/Tdarr#530]
**Describe the bug**
All plugins shows read error

**Screenshots**
![image](https://user-images.githubusercontent.com/20426969/147612857-030dcb0c-cff6-45fe-95b3-ef704c07af2e.png)

 - OS: linux
 - Browser chrome
 - Version 2.00.12

**Comment by HaveAGitGat** [comment]
Click update community plugins on that page or restart the container. Should be working, will look into what caused the issue.

**Comment by PhuriousGeorge** [comment]
I noticed the same before I restarted my rig 30 not minutes ago while trying to switch back to a Community plugin to troubleshoot that issue.
