### ISSUE TITLE
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed

### ISSUE THREAD

**Issue by Niemand112233** [HaveAGitGat/Tdarr#532]
After a week of stable uptime of v2.00.12 I face the exact same problem directly after upgrading to v2.00.13

I'm running the non-docker version.

`Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed`
`[ERROR] Tdarr_Server - Tdarr_Server is not alive at 192.168.10.240:8266 retrying
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed`
` [ERROR] Tdarr_Server - Tdarr_Server is not alive at 192.168.10.240:8266 retrying`

edit: going back to v2.00.12 on the server and all nodes seems to resolve the problem.

_Originally posted by @Niemand112233 in https://github.com/HaveAGitGat/Tdarr/issues/367#issuecomment-1004063799_

**Comment by HaveAGitGat** [comment]
What does the rest of the log say? That error on its own is often not an issue. It's just waiting for the server to start.

**Comment by TimothyRatliff** [comment]
I seem to be getting a similar error. The server hangs and I get these 2 errors on repeat in the logs. I'm running in docker. Let me know what else I can provide to help. 
```
http://{{SERVER_IP}}:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/v2/cruddb from {{SERVER_IP}}:8265 to http://{{SERVER_IP}}:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket.io/?EIO=4&transport=polling&t=NwCryXK from {{SERVER_IP}}:8265 to http://{{SERVER_IP}}:8266 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by HaveAGitGat** [comment]
Sorry had covid so had this on the backburner for the last few weeks. 

I updated the dependency in the dev amd64 image earlier, hoping that will fix the issue.

https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev/images/sha256-5d21ceb4c0acd44e281bda4cf091ba68386616a3d6540d2a4497f07ae8c0f4cc?context=explore

Will do a release this week. If you can try that it would be helpful 👍.

**Comment by TimothyRatliff** [comment]
Sorry to hear that, hope you're feeling better! No worries, I'll give this a try this week.

**Comment by HaveAGitGat** [comment]
Yeah all good, thanks 👍

**Comment by schadis** [comment]
I am on the lastest docker release from 19.02.2022 and i get this error in my log:
`[HPM] Error occurred while proxying request 192.168.1.200:8265/socket.io/?EIO=4&transport=polling&t=NyR51Np&sid=tf9_506zEtaiO-FyAAAS to http://192.168.1.200:8266/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I dont know if it was there before the latest update...
the error apairs in the log everytime i open the webui in chrome or refresh the webui or close it.
hope this helps

**Comment by HaveAGitGat** [comment]
That error is just the proxy being interrupted.  Completely fine if it shows when refreshing /closed the browser.

**Comment by HaveAGitGat** [comment]
I think the issue might be fixed in the dev container as I removed the proxy, worth a try:

`docker.io/haveagitgat/tdarr_acc:dev`

**Comment by danieltmc** [comment]
Is there an easy way to test the dev changes without Docker? I'm facing the same issue on Debian with version 2.00.14 via the Tdarr_Updater

**Comment by HaveAGitGat** [comment]
@danieltmc .15 pre-release/dev packages for linux_x64 are here:
```
      "Tdarr_Node": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.15/linux_x64/Tdarr_Node.zip",
      "Tdarr_Server": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.15/linux_x64/Tdarr_Server.zip"
```

The dev packages aren't built for other platforms unless there's a specific need to test something.

**Comment by danieltmc** [comment]
Thanks! I started running this yesterday and 2.00.15 is definitely an improvement.

Version 2.00.14 was going unresponsive and required me to restart the UI every time a file finished transcoding. The pre-release of .15 goes unresponsive for 5-10 seconds when a file finishes transcoding, but recovers before closing the channel and doesn't require the UI to be restarted.

**Comment by HaveAGitGat** [comment]
Ok reopen if you still have the same issue in 2.00.16, thanks.
