### ISSUE TITLE
Add multiple paths to library source field

### ISSUE THREAD

**Issue by jeff47** [HaveAGitGat/Tdarr#533]
**Is your feature request related to a problem? Please describe.**
Can the ability to add multiple paths to the library source be added?  Ie, "/movies/library1/, /movies/library2/".  Similar to how a list of paths can be added to the ignore field.

**Describe the solution you'd like**
Support a comma-delimited list of paths in the library source field

**Describe alternatives you've considered**
Create multiple libraries, but this is annoying to have to duplicate and keep the transcode stack up to date.

**Comment by HaveAGitGat** [comment]
Duplicate issue here: https://github.com/HaveAGitGat/Tdarr/issues/533
