### ISSUE TITLE
FFPROBE can't read subs stream

### ISSUE THREAD

**Issue by jasimancas** [HaveAGitGat/Tdarr#535]
Until 2 days ago everything has worked fine, but suddenly, I have plugins that clean the titles of the subtitle tracks and remove subtitles of other languages and do not work, in audio and video tracks without problem, but the subtitle tracks do not get to read them, when in some plugin I do fProbeData.streams.length I only get the sum of video and audio tracks, but nothing of subtitles.

**Comment by supersnellehenk** [comment]
Can you pastebin your file json? You can find that if you search for the filename in the search tab and clicking the info button. Should be a bunch of json.

**Comment by jasimancas** [comment]
`{
  "_id": "/media/series12tb1/Series/Ojo de Halcón (2021)/Season 1/Ojo de Halcón - S01E02 - El escondite - [WEBDL-1080p h264].mkv",
  "file": "/media/series12tb1/Series/Ojo de Halcón (2021)/Season 1/Ojo de Halcón - S01E02 - El escondite - [WEBDL-1080p h264].mkv",
  "DB": "q_zQOZD-F",
  "hasClosedCaptions": false,
  "container": "mkv",
  "scannerReads": {
    "ffProbeRead": "success"
  },
  "ffProbeData": {
    "streams": [
      {
        "codec_name": "h264",
        "codec_type": "video",
        "tags": {
          "BPS": "5563851",
          "NUMBER_OF_FRAMES": "70899",
          "NUMBER_OF_BYTES": "2054542467",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:49:14.129000000"
        },
        "avg_frame_rate": "24/1",
        "width": 1920,
        "height": 1080
      },
      {
        "codec_name": "ac3",
        "codec_type": "audio",
        "bit_rate": "384000",
        "channels": 6,
        "tags": {
          "language": "spa",
          "BPS": "384000",
          "NUMBER_OF_FRAMES": "92317",
          "NUMBER_OF_BYTES": "141798912",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:49:14.144000000"
        },
        "avg_frame_rate": "0/0"
      },
      {
        "codec_name": "ac3",
        "codec_type": "audio",
        "bit_rate": "640000",
        "channels": 6,
        "tags": {
          "language": "eng",
          "ENCODER": "Lavc58.54.100 ac3",
          "BPS": "640000",
          "NUMBER_OF_FRAMES": "92315",
          "NUMBER_OF_BYTES": "236326400",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:49:14.080000000"
        },
        "avg_frame_rate": "0/0"
      },
      {
        "codec_name": "subrip",
        "codec_type": "subtitle",
        "tags": {
          "language": "spa",
          "title": "Castellano [Completos]",
          "BPS": "63",
          "NUMBER_OF_FRAMES": "750",
          "NUMBER_OF_BYTES": "23374",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:49:13.046000000"
        },
        "avg_frame_rate": "0/0",
        "duration": "2954.144000"
      },
      {
        "codec_name": "subrip",
        "codec_type": "subtitle",
        "tags": {
          "language": "eng",
          "title": "Inglés [Completos]",
          "BPS": "74",
          "NUMBER_OF_FRAMES": "754",
          "NUMBER_OF_BYTES": "25004",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:44:56.130000000"
        },
        "avg_frame_rate": "0/0",
        "duration": "2954.144000"
      },
      {
        "codec_name": "subrip",
        "codec_type": "subtitle",
        "tags": {
          "language": "eng",
          "title": "Inglés [Para Sordos]",
          "BPS": "81",
          "NUMBER_OF_FRAMES": "838",
          "NUMBER_OF_BYTES": "27665",
          "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
          "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
          "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES",
          "DURATION": "00:45:10.130000000"
        },
        "avg_frame_rate": "0/0",
        "duration": "2954.144000"
      }
    ]
  },
  "file_size": 2321.92937374115,
  "video_resolution": "1080p",
  "fileMedium": "video",
  "video_codec_name": "h264",
  "audio_codec_name": "",
  "lastPluginDetails": "none",
  "processingStatus": false,
  "createdAt": 1641840440897,
  "bit_rate": 0,
  "statSync": {
    "mtimeMs": 1641840425547.9353,
    "ctimeMs": 1641840438347.9363,
    "atime": "2022-01-10T18:47:18.504Z",
    "mtime": "2022-01-10T18:47:05.548Z",
    "ctime": "2022-01-10T18:47:18.348Z"
  },
  "HealthCheck": "Success",
  "TranscodeDecisionMaker": "Transcode success",
  "lastHealthCheckDate": 1641840467525,
  "holdUntil": 0,
  "lastTranscodeDate": 1641840440899,
  "infoLog": "\nPre-processing - Re-order all streams V2\nStreams are in the correct order!\nPre-processing - Tdarr_Plugin_lmg1_Reorder_Streams \nFile has video in first stream\n File meets conditions!\n\nPre-processing - JASimancas-Remove all langs except native and Spanish\nCouldn't grab ID from Radarr/Sonarr, grabbing it from file name \n☒Couldn't find the IMDB id of this file. Skipping. \n\nPre-processing - JASimancas-AC3\nTrack: 1 - Index: 1 - Codec: ac3 (Channels: 6) - Language = spa \nTrack: 2 - Index: 2 - Codec: ac3 (Channels: 6) - Language = eng \nAudio Tracks: 2 \n-------------------------- \nFile doesn't contain track to delete.\n\nPre-processing - JASimancas-Set Spanish audio Default & Forced\nFile doesn't contain tracks to set disposition.\n\nPre-processing - Re-order audio streams\n☑ Preferred language is already first audio track! \n\nPre-processing - JASimancas-Clean MKV file\n☑File doesn't contain subtitle tracks which are unwanted or that require tagging.\n\nPre-processing - Convert ASS subs to SRT (text)\nNo subs in file to extract!\nPre-processing - Migz-Remux container\n☑File is already in mkv container. \n\nPost-processing - JASimancas-NodeRed",
  "bumped": false,
  "history": "",
  "oldSize": 2.6188797038048506,
  "newSize": 2.2675091540440917,
  "videoStreamIndex": 0,
  "originalFile": {
    "_id": "/media/series12tb1/Series/Ojo de Halcón (2021)/Season 1/Ojo de Halcón - S01E02 - El escondite - [WEBDL-1080p h264].mkv",
    "file": "/media/series12tb1/Series/Ojo de Halcón (2021)/Season 1/Ojo de Halcón - S01E02 - El escondite - [WEBDL-1080p h264].mkv",
    "DB": "q_zQOZD-F",
    "hasClosedCaptions": false,
    "container": "mkv",
    "scannerReads": {
      "ffProbeRead": "success"
    },
    "ffProbeData": {
      "streams": [
        {
          "codec_name": "h264",
          "codec_type": "video",
          "tags": {
            "BPS": "5563851",
            "DURATION": "00:49:14.130000000",
            "NUMBER_OF_FRAMES": "70899",
            "NUMBER_OF_BYTES": "2054542467",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "24/1",
          "width": 1920,
          "height": 1080
        },
        {
          "codec_name": "eac3",
          "codec_type": "audio",
          "bit_rate": "256000",
          "channels": 6,
          "tags": {
            "language": "spa",
            "title": "Castellano DD+ 5.1 @ 256 kbps",
            "BPS": "256000",
            "DURATION": "00:49:14.144000000",
            "NUMBER_OF_FRAMES": "92317",
            "NUMBER_OF_BYTES": "94532608",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0"
        },
        {
          "codec_name": "ac3",
          "codec_type": "audio",
          "bit_rate": "384000",
          "channels": 6,
          "tags": {
            "language": "spa",
            "title": "Castellano DD 5.1 @ 384 kbps",
            "BPS": "384000",
            "DURATION": "00:49:14.144000000",
            "NUMBER_OF_FRAMES": "92317",
            "NUMBER_OF_BYTES": "141798912",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0"
        },
        {
          "codec_name": "eac3",
          "codec_type": "audio",
          "bit_rate": "768000",
          "channels": 6,
          "tags": {
            "language": "eng",
            "title": "Inglés DD+ Atmos 5.1 @ 768 kbps",
            "BPS": "768000",
            "DURATION": "00:49:14.080000000",
            "NUMBER_OF_FRAMES": "92315",
            "NUMBER_OF_BYTES": "283591680",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0"
        },
        {
          "codec_name": "ac3",
          "codec_type": "audio",
          "bit_rate": "640000",
          "channels": 6,
          "tags": {
            "language": "eng",
            "title": "Inglés DD 5.1 @ 640 kbps",
            "ENCODER": "Lavc58.54.100 ac3",
            "BPS": "640000",
            "DURATION": "00:49:14.080000000",
            "NUMBER_OF_FRAMES": "92315",
            "NUMBER_OF_BYTES": "236326400",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0"
        },
        {
          "codec_name": "subrip",
          "codec_type": "subtitle",
          "tags": {
            "language": "spa",
            "title": "Castellano [Completos]",
            "BPS": "63",
            "DURATION": "00:49:10.958000000",
            "NUMBER_OF_FRAMES": "750",
            "NUMBER_OF_BYTES": "23374",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0",
          "duration": "2954.144000"
        },
        {
          "codec_name": "subrip",
          "codec_type": "subtitle",
          "tags": {
            "language": "eng",
            "title": "Inglés [Completos]",
            "BPS": "74",
            "DURATION": "00:44:54.042000000",
            "NUMBER_OF_FRAMES": "754",
            "NUMBER_OF_BYTES": "25004",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0",
          "duration": "2954.144000"
        },
        {
          "codec_name": "subrip",
          "codec_type": "subtitle",
          "tags": {
            "language": "eng",
            "title": "Inglés [Para Sordos]",
            "BPS": "81",
            "DURATION": "00:45:08.042000000",
            "NUMBER_OF_FRAMES": "838",
            "NUMBER_OF_BYTES": "27665",
            "_STATISTICS_WRITING_APP": "mkvmerge v59.0.0 ('Shining Star') 64-bit",
            "_STATISTICS_WRITING_DATE_UTC": "2021-11-24 14:17:21",
            "_STATISTICS_TAGS": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
          },
          "avg_frame_rate": "0/0",
          "duration": "2954.144000"
        }
      ]
    },
    "file_size": 2681.732816696167,
    "video_resolution": "1080p",
    "fileMedium": "video",
    "video_codec_name": "h264",
    "audio_codec_name": "",
    "lastPluginDetails": "none",
    "processingStatus": true,
    "createdAt": 1641839983410,
    "bit_rate": 0,
    "statSync": {
      "mtimeMs": 1641814919193.871,
      "ctimeMs": 1641839386576.117,
      "atime": "2022-01-10T18:29:50.996Z",
      "mtime": "2022-01-10T11:41:59.194Z",
      "ctime": "2022-01-10T18:29:46.576Z"
    },
    "HealthCheck": "Success",
    "TranscodeDecisionMaker": "Queued",
    "lastHealthCheckDate": 1641840198265,
    "holdUntil": 0,
    "lastTranscodeDate": 0,
    "infoLog": "",
    "bumped": false,
    "history": "",
    "oldSize": 0,
    "newSize": 0,
    "videoStreamIndex": 0
  }
}`

**Comment by supersnellehenk** [comment]
I can see three subrip streams in there? So there are subtitles?

**Comment by jasimancas** [comment]
Yes, but as you can see, "title" appears only in subtitles, in audio and video it has been removed correctly.

**Comment by supersnellehenk** [comment]
Well that entirely depends on your plugin, if you hop into the Tdarr discord I could try to help. So it's not an issue with Tdarr itself.

**Comment by jasimancas** [comment]
Is this normal?
It is the log of the node container every time I perform a transcode.
![image](https://user-images.githubusercontent.com/15717847/148849433-32f4ce95-3ec2-4185-a4e2-8f74b6101275.png)

**Comment by HaveAGitGat** [comment]
> Is this normal? It is the log of the node container every time I perform a transcode. ![image](https://user-images.githubusercontent.com/15717847/148849433-32f4ce95-3ec2-4185-a4e2-8f74b6101275.png)

No that's not normal, which plugin are you using?

**Comment by HaveAGitGat** [comment]
Re-open if needed, thanks.
