### ISSUE TITLE
Add support for mkvcleaver/mkvtool 

### ISSUE THREAD

**Issue by justindgreen** [HaveAGitGat/Tdarr#537]
After much time, effort, and pain, it has become clear that Tdarr does not have a good solution for handling PGS and other image-based subs beyond "remove them and find new ones". This solution is far from ideal since many files are ripped from blu-rays and only have access to those subs.

I propose that mkvcleaver/mkvtool be added into the modules alongside ffmpeg and handbrake to allow the development of plugins that would be able to better deal with those types of files.

**Comment by supersnellehenk** [comment]
So, your suggestions are basically MkvToolNix. What would this bring regarding features that plugins would benefit from?

**Comment by HaveAGitGat** [comment]
mkvtoolnix is installed in the 2.00.14 Docker image if you need it
