### ISSUE TITLE
[Feature Request] Assign Library to Specific Nodes

### ISSUE THREAD

**Issue by joelang1699** [HaveAGitGat/Tdarr#539]
Would is be possible to assign specific nodes to specific library tasks.

For example. I'd like to be able to assign x265 encodes to suitably powerful nodes and SD/Audio tracks to lower powered nodes.

Presently I'm running two servers to divide up the tasks.

**Comment by brayrobert201** [comment]
Or separate staging queues to separate libraries.

My scenario is kinda similar. I've got two libraries. One that's intended for GPU conversions to x265. Another that's for fixing up audio.

I've got two GPU workers and 6 CPU workers. However as soon as the staging queue is full of stuff that's waiting for something in the GPU focused queue, the CPUs sit idle.

If each library could have its own staging queue, the audio library would be able to keep going whenever there was an available CPU worker while the video queue could just do its current thing of waiting for a GPU worker without blocking anything else.

**Comment by Enigma0** [comment]
This would be a nice addition, or the inverse, assign nodes to specific libraries.

**Comment by HaveAGitGat** [comment]
I'll put this under here as it's pretty much the same thing: 
https://github.com/HaveAGitGat/Tdarr/issues/440

**Comment by hardwareadictos** [comment]
Nice one, pretty interested on this also :)

**Comment by villieb** [comment]
I'd like to see this too...

**Comment by HaveAGitGat** [comment]
Assigning libraries to nodes is added for next version, can try here: https://github.com/HaveAGitGat/Tdarr/issues/440#issuecomment-1439629990
