### ISSUE TITLE
[Feature Request] Pause/resume library via API

### ISSUE THREAD

**Issue by brayrobert201** [HaveAGitGat/Tdarr#540]
**Is your feature request related to a problem? Please describe.**
I'm currently syncing a media store with a friend via Syncthing.

My upload is 40mbit.

I'd like to be able to keep the upload backlog within a manageable size. So I can process at full speed until my upload backlog is at X size, then pause it until the upload queue clears.

**Describe the solution you'd like**
I'd like to be able to get an API call to pause/resume a library.

If I can do this, then I can write a script that monitors my syncthing backlog and calls the pause/resume endpoint whenever the upload queue is too big/too small, then execute this via cron.

**Describe alternatives you've considered**
I could shutdown the entire node(s), but that means that libraries that process slowly enough that my upload speed isn't the bottleneck also stop.

I've also tried fiddling with the scheduling, but that doesn't really deal with a large amount of files that don't need to be updated coming in at once.

**Additional context**

**Comment by HaveAGitGat** [comment]
You can do this using 2 steps:

Get the library _ids:

```
const result = await axios.post(`http://localhost:8265/api/v2/cruddb`, {
    headers: {
      'content-Type': 'application/json',
    },
    "data":{
        "collection":"LibrarySettingsJSONDB",
        "mode":"getAll"
    }
});
console.log(result);
```

Update the library `processLibrary` value to true/false.
```
const result = await axios.post(`http://localhost:8265/api/v2/cruddb`, {
    headers: {
      'content-Type': 'application/json',
    },
    data: {
        "collection": "LibrarySettingsJSONDB",
        "mode": "update",
        "docID": "axtVFYQlA",
        "obj": {
            "processLibrary": true
        }
    },
  });
```

**Comment by brayrobert201** [comment]
Ok cool, thanks.

**Comment by brayrobert201** [comment]
So I'm attempting to do this via curl. Just submitting the above json payloads.

```curl -v --url http://10.85.15.243:8265/api/v2/cruddb --header 'Content-Type: application/json' -d '{"collection":"LibrarySettingsJSONDB","mode":"getAll"}'```

That returns this error
```2022-01-28 05:08:10.746049+00:00(node:327) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'collection' of undefined
2022-01-28 05:08:10.746078+00:00at /snapshot/be/srcug/api/mainApi.js:1:15490
2022-01-28 05:08:10.746086+00:00at _0x5dd987 (/snapshot/be/srcug/api/mainApi.js:1:10189)
2022-01-28 05:08:10.746091+00:00at Object.next (/snapshot/be/srcug/api/mainApi.js:1:8494)
2022-01-28 05:08:10.746096+00:00at /snapshot/be/srcug/api/mainApi.js:1:7970
2022-01-28 05:08:10.746100+00:00at new Promise (<anonymous>)
2022-01-28 05:08:10.746105+00:00at __awaiter (/snapshot/be/srcug/api/mainApi.js:1:7335)
2022-01-28 05:08:10.746109+00:00at /snapshot/be/srcug/api/mainApi.js:1:15192
2022-01-28 05:08:10.746113+00:00at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5)
2022-01-28 05:08:10.746118+00:00at next (/snapshot/be/node_modules/express/lib/router/route.js:137:13)
2022-01-28 05:08:10.746122+00:00at Route.dispatch (/snapshot/be/node_modules/express/lib/router/route.js:112:3)
2022-01-28 05:08:10.746158+00:00at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5)
2022-01-28 05:08:10.746164+00:00at /snapshot/be/node_modules/express/lib/router/index.js:281:22
2022-01-28 05:08:10.746168+00:00at Function.process_params (/snapshot/be/node_modules/express/lib/router/index.js:335:12)
2022-01-28 05:08:10.746172+00:00at next (/snapshot/be/node_modules/express/lib/router/index.js:275:10)
2022-01-28 05:08:10.746177+00:00at /snapshot/be/node_modules/body-parser/lib/read.js:130:5
2022-01-28 05:08:10.746181+00:00at invokeCallback (/snapshot/be/node_modules/raw-body/index.js:224:16)
2022-01-28 05:08:10.746186+00:00(node:327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 54)
```

Can you see what I've done wrong?

**Comment by brayrobert201** [comment]
Meh, all good. Looks like it'll simply be easier to learn a little JS.

**Comment by HaveAGitGat** [comment]
> So I'm attempting to do this via curl. Just submitting the above json payloads.
> 
> `curl -v --url http://10.85.15.243:8265/api/v2/cruddb --header 'Content-Type: application/json' -d '{"collection":"LibrarySettingsJSONDB","mode":"getAll"}'`
> 
> That returns this error
> 
> ```
> 2022-01-28 05:08:10.746078+00:00at /snapshot/be/srcug/api/mainApi.js:1:15490
> 2022-01-28 05:08:10.746086+00:00at _0x5dd987 (/snapshot/be/srcug/api/mainApi.js:1:10189)
> 2022-01-28 05:08:10.746091+00:00at Object.next (/snapshot/be/srcug/api/mainApi.js:1:8494)
> 2022-01-28 05:08:10.746096+00:00at /snapshot/be/srcug/api/mainApi.js:1:7970
> 2022-01-28 05:08:10.746100+00:00at new Promise (<anonymous>)
> 2022-01-28 05:08:10.746105+00:00at __awaiter (/snapshot/be/srcug/api/mainApi.js:1:7335)
> 2022-01-28 05:08:10.746109+00:00at /snapshot/be/srcug/api/mainApi.js:1:15192
> 2022-01-28 05:08:10.746113+00:00at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5)
> 2022-01-28 05:08:10.746118+00:00at next (/snapshot/be/node_modules/express/lib/router/route.js:137:13)
> 2022-01-28 05:08:10.746122+00:00at Route.dispatch (/snapshot/be/node_modules/express/lib/router/route.js:112:3)
> 2022-01-28 05:08:10.746158+00:00at Layer.handle [as handle_request] (/snapshot/be/node_modules/express/lib/router/layer.js:95:5)
> 2022-01-28 05:08:10.746164+00:00at /snapshot/be/node_modules/express/lib/router/index.js:281:22
> 2022-01-28 05:08:10.746168+00:00at Function.process_params (/snapshot/be/node_modules/express/lib/router/index.js:335:12)
> 2022-01-28 05:08:10.746172+00:00at next (/snapshot/be/node_modules/express/lib/router/index.js:275:10)
> 2022-01-28 05:08:10.746177+00:00at /snapshot/be/node_modules/body-parser/lib/read.js:130:5
> 2022-01-28 05:08:10.746181+00:00at invokeCallback (/snapshot/be/node_modules/raw-body/index.js:224:16)
> 2022-01-28 05:08:10.746186+00:00(node:327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 54)
> ```
> 
> Can you see what I've done wrong?

Close, this should do the trick with curl:

```
curl --request POST \
     --url http://10.85.15.243:8265/api/v2/cruddb \
     --header 'Content-Type: application/json' \
     -d '{"data": {"collection":"LibrarySettingsJSONDB","mode":"getAll"}}'
```

**Comment by HaveAGitGat** [comment]
@brayrobert201 you can now also use https://tdarr.readme.io/reference/post_cruddb to auto-generate the curl command.

**Comment by brayrobert201** [comment]
That's just awesome.

Having a fiddle with getting a document - The following is returned from get all:
```
        "_id": "/media/TV/Future Man/Season 3/Future Man - S03E03 - (HDTV-1080p x265).mkv",
	"file": "/media/TV/Future Man/Season 3/Future Man - S03E03 - (HDTV-1080p x265).mkv",
	"DB": "YQPQMZYfA",
	"hasClosedCaptions": false,
        ***snip***```

Getting a null this:
```
curl --request POST      --url http://10.85.24.182:8265/api/v2/cruddb      --header 'Content-Type: application/json'      --data '
{     
     "data": {
          "docID": "/media/TV/Future Man/Season 3/Future Man - S03E03 - (HDTV-1080p x265).mkv",
          "collection": "FileJSONDB",                                                                            
          "mode": "getByID"              
     }                                                                                                           
}                                         
'
null
```

Have I misunderstood it?

HEre's a verbose response from curl
```Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.85.24.182:8265...
* Connected to 10.85.24.182 (10.85.24.182) port 8265 (#0)
> POST /api/v2/cruddb HTTP/1.1
> Host: 10.85.24.182:8265
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 189
> 
* upload completely sent off: 189 out of 189 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< access-control-allow-origin: *
< access-control-allow-methods: GET,HEAD,OPTIONS,POST,PUT
< access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< content-type: application/json; charset=utf-8
< content-length: 4
< etag: W/"4-K+iMpCQsduglOsYkdIUQZQMtaDM"
< date: Wed, 09 Feb 2022 06:46:36 GMT
< connection: close
< 
* Closing connection 0
```

Unfortunately verbose logging doesn't return anything.
