### ISSUE TITLE
[Feature Request] Separate stage queues per library

### ISSUE THREAD

**Issue by brayrobert201** [HaveAGitGat/Tdarr#541]
**Is your feature request related to a problem? Please describe.**
I have two libraries. One library is GPU dependent. Another is purely CPU dependent.

I have two GPU workers and six CPU workers.

When my staging queue is full of files procided by the GPU depdendent library, the CPU dependent library needs to wait for a free spot.

**Describe the solution you'd like**
Allow a library to have a separate stage. So a stage that's full of GPU dependent transcodes doesn't stop CPU dependent transcodes from being processes.

**Describe alternatives you've considered**
I've increased the size of the queue. That only delays the problem.

Alternating helps a bit, but it still stops the CPU dependent queue as soon as the stage is full.

**Additional context**
One library focuses on transcoding to X265. Another focuses on dealing with annoying audio setups (EAC3, which isn't handled by Plex in Android. Six channel audio when two is preferred)

This gives an example of what happens. My CPU-dependent audio stage queue is about 60k items long. The only thing that's active is two GPU workers.
![example](https://user-images.githubusercontent.com/6738853/149864211-cbb11df8-0d43-4010-b148-150bfd2788de.jpg)

**Comment by HaveAGitGat** [comment]
Enable this option on the node settings and only use GPU workers:
![image](https://user-images.githubusercontent.com/43864057/168517808-bb25f013-9dd7-40d2-905c-868ab1b37948.png)

This will prevent the staging section becoming too large.

Having separate staging sections would get confusing I think.
