### ISSUE TITLE
[Feature Request] Shared progress databases

### ISSUE THREAD

**Issue by brayrobert201** [HaveAGitGat/Tdarr#543]
**Is your feature request related to a problem? Please describe.**
I've got this running over a cluster of devices that use folders synchronised via Syncthing (An application that basically takes the torrent approach to folder syncronisation. Similar to Resilio Sync). Because it requires a temp folder that's accessible by the server, processing needs to be performed in one location and then pushed out to the rest of the cluster. The connection this is being done on has 40mbit outbound, which is the limiting factor.

**Describe the solution you'd like**
I used to use my own set of scripts to manage file processing and synchronisation with a shared postgres database in between.

When a file was being processed, it would be set to inprogress in this database, and when the file was successfully completed, it would be removed (or marked as failed)

It would be good if multiple servers could keep a status database between them and only pick up tasks that haven't been picked up by another cluster.

**Describe alternatives you've considered**
I've considered a shared temp filesystem between them, but the acceptance and copying is still being done by a single server and being re-uploaded, so it seems like this would only make the problem far more confusing.

**Additional context**

**Comment by HaveAGitGat** [comment]
Hi, the whole point of the Tdarr node system is that all the nodes connect with a central server and the queues/processing is managed at a central location. It seems you're wanting to add another layer above this to the servers which defeats the point of  the nodes and server. Your devices should all be connecting to the server directly, not through Syncthing.
