### ISSUE TITLE
Trying to limit tdarr and tdarr-node via docker limits

### ISSUE THREAD

**Issue by ovizii** [HaveAGitGat/Tdarr#547]
**Is your feature request related to a problem? Please describe.**
I just started using tdarr and woke up to countless out of memory and CPU wait warnings. I ran your sample docker-compose and before going to sleep I had like 60GB of RAM available and nothing except tdarr and 1 tdarr-node running and the CPU still had plenty of warnings as well as the tdarr-node running out of memory

**Describe the solution you'd like**
I would like to be able to limit the resources via available docker methods

**Additional context**
I tried what I usually do with greedy containers: 

edit docker-compose.yml and change the version to
`version: '2.4'`

then I added these limits to tdarr:
```
    cpu_count: 2                                                                                                                                                
    mem_limit: 4G
```
and these limits to tdarr-node:
```
    cpu_count: 4                                                                                                                                                
    mem_limit: 8G
```
within seconds of starting the tdarr-node ran out of memory and crashed and tdarr was saying no nodes found. I upped the memory limit to 16GB and it took like 10 seconds longer before crashing. Currently it is at 32GB and this is its usage:
```
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT   MEM %     NET I/O           BLOCK I/O   PIDS                                                          
0095010e0a66   tdarr-node   38.15%    31.99GiB / 32GiB    99.96%    5.47MB / 24.9MB   0B / 0B     3                                                             
```
and it has crashed again :-( 

**I can't just let tdarr-node run wild without limits. It needs to behave and stay within the limits I define without crashing. Please help.**

these are my worker settings:
![image](https://user-images.githubusercontent.com/837902/151662861-19cca9ae-e299-46a8-811a-c96fa551610e.png)

**Comment by ovizii** [comment]
btw. I had one transcode fail:

`Error writing trailer of /temp/Movie Name (2008) Bluray-1080p-TdarrCacheFile-JuuM_9INx.mkv: No space left on device`

/temp is mounted as instructed to /dev/shm
`- /dev/shm:/temp`

is is big enough but we can see it is indeed full:
```
df -h |grep shm                                                                                                                   
tmpfs                                                                           63G   63G  400M 100% /dev/shm
```

of course this happens if tdarr-node easily eats 32GB of RAM so nothign is left for /dev/shm

**Comment by ovizii** [comment]
please keep in mind, I am not actually doing any movie transcoding, I am simply removing subtitles and audio streams in undesired languages followed by converting dts streams to ac3 streams.

**Comment by supersnellehenk** [comment]
Well, you're telling it to transcode to RAM, which depending on your source file will eat that amount of RAM. If you've got 4x8 GB source files transcoded into RAM, that's 32 GB in your cache. So trying to limit the RAM usage is basically impossible that way, unless you set a staging limit.

**Comment by ovizii** [comment]
btw. I have reduced my workers to 1 each:
![image](https://user-images.githubusercontent.com/837902/151663642-c5c1989f-ded7-42ad-93ff-46df46435dd3.png)

but if I do a ls -al /dev/shm on the host I see 10 movie folders and /dev/shm is basically permanently full - really not sure what tdarr is doing here, why does it keep so many movies inside /temp (aka the transcode cache) when it only has 1 running worker?

**Comment by supersnellehenk** [comment]
@ovizii  Workers will just transcode away until it hits the staging limit. If you look at the staging section of the UI you'll probably see one is copying back and the others are awaiting copy.

**Comment by ovizii** [comment]
thanks for the feedback, trying to figure things out. If I understand you correctly this should work: 

Limit tdarr to 1 worker for health and transcode. 
Set docker limits to 32GB.
No single file is more than 20GB in size.

So this should work for me and keep /dev/shm as transcoding cache?

Coul you please explain what "the staging limit" is? I see the staging section but what is its limit?

**Comment by supersnellehenk** [comment]
It limits the amount of files Tdarr can have processing at a time, from being actively worked on by a worker to just waiting to copy. If it's at 10, then you'd need 10 x 20 GB = 200 GB of cache at a maximum. Since your transcode requirements are relatively low, it'll do the files pretty much at the speed your disks will transfer, thus filling your cache rather quick.

I'd set your staging limit to 1, thus requiring your cache to be entirely empty before the next file can be processed. That way you won't run into your RAM issues.

**Comment by ovizii** [comment]
cool, thanks for confirming and helping put things together. I am currently working with the following settings and it seems to work fine: I'll keep an eye on it though ;-)

- tdarr-node limited to 32GB RAM
- tdarr staging limit set to 1
- 1 worker for health checks (not sure if health checks also copy the file - if not I could up this)
- 1 worker for transcoding
