### ISSUE TITLE
Sort queue by Codec does not differenciate between H264 and HEVC

### ISSUE THREAD

**Issue by Carl-Wilhelm** [HaveAGitGat/Tdarr#549]
My media library only has H264 and HVEC codecs, and i am not able to get HEVC at top of the "Transcode queue".
When i select "sort by Codec A-Z", all the clips with H264 comes at top.
Then i change it to soft by "Codec Z-A" and all my H264 clips are still at top. 

OS: Windows Server 2016
Browser Chrome
Version 2.0.0.13

**Comment by HaveAGitGat** [comment]
Working fine from what I can see:
![image](https://user-images.githubusercontent.com/43864057/152724398-d1d1735c-a60f-4071-b42a-ff4868ca0ef0.png)

![image](https://user-images.githubusercontent.com/43864057/152724437-92b66b4a-4b1c-4455-9aeb-960381f2926c.png)

Depending on your system it can take a while to sort the queue so you might have to wait while it processes.

**Comment by Carl-Wilhelm** [comment]
Hi again.
It does absolutely NOT work here.
I waited about 1 hour after changing sorting mode before i took screenshot.
I see the list is updating after a few seconds, but h264 is always on top. (I only have H264 and HEVC in my library)

Codec A-Z
![image](https://user-images.githubusercontent.com/75078972/152857094-79662ffc-dec7-4d50-8e5a-c5d24bd4826b.png)

Codec Z-A
![image](https://user-images.githubusercontent.com/75078972/152856968-b6140b5f-5cb3-4f66-823f-5f9ceaff70a0.png)

**Comment by HaveAGitGat** [comment]
I think this is due to your streams not being in the correct order (video stream is not first) as the sorting is done on the first stream codec. I've made some changes so this should be fixed in 2.00.14.
