### ISSUE TITLE
[2.00.13] Closed Captions (EIA_608) are not detected

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#550]
**Describe the bug**
EIA_608 Closed Captions embedded in the video stream are not detected by Tdarr 2.00.13. This works properly in 2.00.10.

**To Reproduce**
Check the JSON Media Info for a file with embedded CCs in the video stream. 2.00.10 shows the CCs, 2.00.13 does not.

**Expected behavior**
2.00.13 should show CCs present as well.

**Screenshots**
File information in 2.00.10 (note the "closed_captions" parameter in stream 0):

![image](https://user-images.githubusercontent.com/35738729/152220086-b7c120d5-51e2-40cb-ad60-a4252b327c75.png)

Same file information in 2.00.13:
![image](https://user-images.githubusercontent.com/35738729/152220128-f322fd12-e533-4ba8-8176-c458966facd8.png)

**Please provide the following information:**
- Config files: not relevant
- Log files: not relevant
- Worker error: no errors

 - OS: Raspberry Pi OS ARMv7 32 bits
 - Browser: not relevant
 - Version: 2.00.13

**Comment by HaveAGitGat** [comment]
Should be fixed in 2.00.14

![image](https://user-images.githubusercontent.com/43864057/153138743-2eaf6214-81bc-4536-8f70-43ee01e50684.png)

**Comment by wsegatto** [comment]
Thank you, HGG!
