### ISSUE TITLE
WebUI Unavailable after restarting Docker container

### ISSUE THREAD

**Issue by RyanMakesMovies** [HaveAGitGat/Tdarr#551]
**Describe the bug**
On restarting tdarr's docker container, a "Connection was reset" error is received when trying to load the WebUI. The only fix has been to delete and reinstall the container, but obviously that's not sustainable for long-term use.

**To Reproduce**
Restart docker container and try to access WebUI

 - OS: Linux/Synology DSM
 - Browser: Firefox, Chrome
 - Version 2.00.13

**Additional context**
As referenced [here](https://old.reddit.com/r/Tdarr/comments/sia882/webui_unavailable_after_restarting_docker/), problem can be worked around by deleting everything except Backups folder, restarting container, and then restoring from backup

**Comment by HaveAGitGat** [comment]
If you can post the startup log when the error happens then I can take a look at which part it's getting stuck on. Sounds like maybe a permissions issue when reading the database files.

**Comment by RyanMakesMovies** [comment]
```
Starting Tdarr_Server
version: 2.00.13
linux_x64
Preparing environment
/app/configs/Tdarr_Server_Config.json
{
  serverPort: '8266',
  webUIPort: '8265',
  serverIP: '192.168.1.69',
  handbrakePath: '',
  ffmpegPath: ''
}

Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:SettingsGlobalJSONDB
```

It hangs up at the Reading DB: SettingsGlobalJSONDB line

**Comment by HaveAGitGat** [comment]
Thanks, I've added more info to the logs so it shows which file is being read in the .14 pre-release.

![image](https://user-images.githubusercontent.com/43864057/152912889-9db01fe3-4d91-4111-b522-8511f0b45201.png)

Would you mind giving it a go?

 https://f000.backblazeb2.com/file/tdarrs/versions/2.00.14/linux_x64/Tdarr_Server.zip
 https://f000.backblazeb2.com/file/tdarrs/versions/2.00.14/linux_x64/Tdarr_Node.zip

Build should be done in 30 mins or so.

**Comment by eltiel** [comment]
I believe this issue is somewhat related to https://github.com/HaveAGitGat/Tdarr/issues/485, which was never really fixed for me even until today.

**Comment by HaveAGitGat** [comment]
@eltiel that issue was to do with this error ` Error: Timeout: Did not receive an init message from worker after 10000ms` relating to slow drives.

So the timeout was increased to 200 seconds to give HDDs enough time to read the files.

This issue is to do with something else as the timeout error does not appear.

So hopefully @RyanMakesMovies can try the above packages or the dev image to see if it fixes the issue:

haveagitgat/tdarr_acc:dev
https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev/images/sha256-b22ee03fb35fdcf7a45d9eace95853ba8d9ffd2dbb29cd851b573a4a3b351bb4?context=explore

@eltiel if you are still receiving the timeout error then please reopen the other issue.

**Comment by eltiel** [comment]
> @eltiel that issue was to do with this error ` Error: Timeout: Did not receive an init message from worker after 10000ms` relating to slow drives.
> 
> So the timeout was increased to 200 seconds to give HDDs enough time to read the files.
> 
> This issue is to do with something else as the timeout error does not appear.
> 
> So hopefully @RyanMakesMovies can try the above packages or the dev image to see if it fixes the issue:
> 
> haveagitgat/tdarr_acc:dev https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev/images/sha256-b22ee03fb35fdcf7a45d9eace95853ba8d9ffd2dbb29cd851b573a4a3b351bb4?context=explore
> 
> @eltiel if you are still receiving the timeout error then please reopen the other issue.

I can reproduce this issue that @RyanMakesMovies raised.

My server also hangs upon container restart, hanging at this point:

`Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:SettingsGlobalJSONDB`

I tried the Tdarr_acc:dev build, and this is what I see now:

`Reading DB:>>>>>>>>>>(100%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading`

I checked my app folder and the .json file is present and appears to be correctly named.

**Comment by eltiel** [comment]
I was able to reproduce the issue @RyanMakesMovies raised.

I tried your dev image and it managed to load past "Reading DB" but threw out additional errors:

```
[2022-02-09T14:50:40.358] [INFO] Tdarr_Server - exiftoolPath:/app/Tdarr_Server/node_modules/exiftool-vendored.pl/bin/exiftool

Error: Cannot find module './swaggerJson.json'

Require stack:

- /snapshot/be/srcug/api/mainApi.js

- /snapshot/be/srcug/main.js

[2022-02-09T14:50:40.651] [FATAL] Tdarr_Server - Error in main thread:Error: Cannot find module './swaggerJson.json'
Require stack:

- /snapshot/be/srcug/api/mainApi.js

- /snapshot/be/srcug/main.js
```

**Comment by HaveAGitGat** [comment]
Thanks @eltiel. Spotted that issue, should be working soon, just waiting for the raspberry pi build to finish. Can take up to an hour as the processor isn't very good.

**Comment by HaveAGitGat** [comment]
It's good that it got past the db read steps though, looks promising.

**Comment by eltiel** [comment]
> It's good that it got past the db read steps though, looks promising.

Apparently it only worked the very first time when I switched to the dev build. After a restart, I'm stuck at the same spot:

`Reading DB:>>>>>>>>>>(100%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading`

**Comment by HaveAGitGat** [comment]
Ok at least it shows the exact file it's stuck on.

Tdarr is just doing a simple read on the file:

```
 data = fs.readFileSync(filePath);
 data = JSON.parse(dataOut);
```

So not sure what would prevent reading and cause it to hang.

**Comment by eltiel** [comment]
Not sure if this info will be useful, but I noticed that in my case it's not a hard hang.

Whenever it is stuck in the `Reading DB` step, it seems to trigger a restart 30 seconds later. The logs look like this:
<img width="670" alt="1" src="https://user-images.githubusercontent.com/11868456/153157815-7b472400-3cfa-43fc-8251-0ac2cc48a8d6.png">
<img width="661" alt="2" src="https://user-images.githubusercontent.com/11868456/153157849-bb6bbf03-f606-456c-b00c-e30bbe9499eb.png">

And it repeats endlessly.

**Comment by HaveAGitGat** [comment]
Ok seems something is causing it to crash for some reason.

I've switched to using [fs-extra](https://www.npmjs.com/package/fs-extra) for the reading of the files. Hopefully that will solve the issue. New build will be done in an hour.

**Comment by eltiel** [comment]
Same issue, except now `Reading DB` shows 0%

<img width="730" alt="Screenshot 2022-02-10 180259" src="https://user-images.githubusercontent.com/11868456/153384130-faf97dd1-5dc3-4b76-8b4f-3f64a719aa13.png">

**Comment by RyanMakesMovies** [comment]
Can confirm, I also get hung up at 0% now with the 2.00.14 build. 

`Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f1                                      73693057d0c2f3c07b0d3a3c.json:Reading`

Interestingly, in the past I was also getting the restarts that @eltiel was mentioning, but those no longer seem to be happening. Now it's just sitting on the Reading DB bit.

**Comment by HaveAGitGat** [comment]
Thanks for trying. The code after that is just 

` dataOut = fsextra.readJsonSync(filePath);`

[fs-extra](https://www.npmjs.com/package/fs-extra) gets 66 million downloads a week so a bit stumped why it's not working for you. Nothing seems to come up when searching for hang/freezing issues.

Are you both using Synology? Perhaps something to do with that.

**Comment by eltiel** [comment]
> Are you both using Synology? Perhaps something to do with that.

Yes I am

**Comment by RyanMakesMovies** [comment]
> > Are you both using Synology? Perhaps something to do with that.
> 
> Yes I am

Me too

**Comment by HaveAGitGat** [comment]
Must be some low level file system bug/issue to do with NodeJS/Docker/Synology then. Does Synology have a permissions UI or something like that? Confirmed the container permissions are ok with the Synology os permissions?

If you open up this file what's in it?

`/SettingsGlobalJSONDB/afdf79ef24e7f6f1 73693057d0c2f3c07b0d3a3c.json:Reading`

If you format it using the following then it should be a file roughly 98 lines long:

**Comment by eltiel** [comment]
Synology's Docker allows for some configuration, although I'm not clear what else is needed considering I've configured the container exactly as per Tdarr's docs. What other permissions are required?

A point to note is that if the container starts with a clean slate (by wiping the `server` and `configs` folders), it will work just fine. 

If I open up the `SettingsGlobalJSONDB` file, I do see the following 98 lines:

> {
>    "_id":"globalsettings",
>    "theme":"medium2",
>    "autoAcceptTranscodes":true,
>    "lowCPUPriority":false,
>    "ignoreSchedules":false,
>    "homePath":"/app/server",
>    "pluginSearchLoading":false,
>    "prioritiseHealthChecks":true,
>    "prioritiseTranscodes":false,
>    "lastQueueUpdateTime":0,
>    "workerStallDetector":false,
>    "workerStallDetectorInterval":300,
>    "backupLimit":30,
>    "dropdownShow":{
>       "serverOverview":true,
>       "nodesOverview":true,
>       "stagingSection":true,
>       "statusTables":true,
>       "statusTablesOptions":true
>    },
>    "transcodeWorkerLimit":0,
>    "healthcheckWorkerLimit":0,
>    "queueSortType":"sortDateNewest",
>    "prioritiseLibraries":false,
>    "alternateLibraries":true,
>    "verboseLogs":false,
>    "basePath":"",
>    "stagedFileLimit":100,
>    "communityPluginRepo":"https://github.com/HaveAGitGat/Tdarr_Plugins/archive/master.zip",
>    "searchResultColumns":{
>       "index":true,
>       "fileName":true,
>       "streams":true,
>       "closedCaptions":true,
>       "codec":true,
>       "resolution":true,
>       "size":true,
>       "bitrate":true,
>       "duration":true,
>       "bump":true,
>       "createSample":true,
>       "transcode":true,
>       "healthCheck":true,
>       "info":true,
>       "history":true,
>       "remove":true
>    },
>    "tableSize":"200",
>    "resBoundaries":{
>       "res480p":{
>          "widthMin":100,
>          "widthMax":792,
>          "heightMin":100,
>          "heightMax":528
>       },
>       "res576p":{
>          "widthMin":100,
>          "widthMax":792,
>          "heightMin":100,
>          "heightMax":634
>       },
>       "res720p":{
>          "widthMin":100,
>          "widthMax":1408,
>          "heightMin":100,
>          "heightMax":792
>       },
>       "res1080p":{
>          "widthMin":100,
>          "widthMax":2112,
>          "heightMin":100,
>          "heightMax":1188
>       },
>       "res4KUHD":{
>          "widthMin":100,
>          "widthMax":4224,
>          "heightMin":100,
>          "heightMax":2376
>       },
>       "resDCI4K":{
>          "widthMin":100,
>          "widthMax":4506,
>          "heightMin":100,
>          "heightMax":2376
>       },
>       "res8KUHD":{
>          "widthMin":100,
>          "widthMax":8448,
>          "heightMin":100,
>          "heightMax":5752
>       }
>    },
>    "runningDocker":true,
>    "logsLoading":false,
>    "selectedLibrary":0,
>    "version":"2.00.10"
> }

**Comment by HaveAGitGat** [comment]
Thanks, that looks fine. Will need to potentially wait for someone experienced with Docker/Synology to post a solution.

You could perhaps try running the container using `--privileged`. I need to sometimes use that when running on Raspberry Pi.

`When the operator executes docker run --privileged, Docker will enable access to all devices on the host as well as set some configuration in AppArmor or SELinux to allow the container nearly all the same access to the host as processes running outside containers on the host. Additional information about running with --privileged is available on the [Docker Blog](https://blog.docker.com/2013/09/docker-can-now-run-within-docker/).`

https://docs.docker.com/engine/reference/run/

**Comment by eltiel** [comment]
> You could perhaps try running the container using --privileged. I need to sometimes use that when running on Raspberry Pi.

I already did but to no avail:

<img width="490" alt="root" src="https://user-images.githubusercontent.com/11868456/154634929-d9e71bd5-5e13-4010-b199-f26a66bc8d3f.png">

**Comment by HaveAGitGat** [comment]
Perhaps try putting the server data on a different disk/share/USB.

**Comment by thtwice** [comment]
Hi,
Got sent here from [this](https://github.com/HaveAGitGat/Tdarr/issues/575) 

Just to add a bit of new information .
In versions .13 and before tdarr simply failed to load as shown by the others. 
In .14 it also fills all the RAM of the system trying to start.

Maybe it can help narrow down the cause.

Regards.

**Comment by HaveAGitGat** [comment]
@thtwice just to confirm you're not using Synology right?

**Comment by thtwice** [comment]
> @thtwice just to confirm you're not using Synology right?

No. Ubuntu host on Intel system. Tdarr running in docker.

**Comment by HaveAGitGat** [comment]
Ok thanks, would you mind checking the size of this file? 
`/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json`

It should be a few KB or so but for some reason for you it seems to fill up RAM when being read.

**Comment by thtwice** [comment]
> Ok thanks, would you mind checking the size of this file? `/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json`
> 
> It should be a few KB or so but for some reason for you it seems to fill up RAM when being read.

I spun up a fresh container, stopped it and then restarted it.
The file stayed the same size at 1.7K all the time

**Comment by thtwice** [comment]
> Ok thanks, would you mind checking the size of this file? `/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json`
> 
> It should be a few KB or so but for some reason for you it seems to fill up RAM when being read.

I want to repeat that until .13 it failed to start but the memory leak wasn't there.
It started filling the ram with version .14

**Comment by HaveAGitGat** [comment]
@thtwice frustrating as nothing changed in that area except some stuff being added to the Docker image. 

It’s a fs.readFileSync() bug where it seems to read an infinite amount of data into ram and then crashes.

**Comment by HaveAGitGat** [comment]
@thtwice I'll try some things tomorrow to hopefully fix this.

**Comment by timberjoegithub** [comment]
Any update on this?  I have a similar setup to @thtwice (ubuntu 20.4 & latest docker) and it starts loading the SettingsGlobal file (~2k) and just spins out of control until it crashes, repeat process

**Comment by HaveAGitGat** [comment]
Sorry, had a crazy busy weekend. Please try the updated dev image:
`docker pull haveagitgat/tdarr_acc:dev`

**Comment by timberjoegithub** [comment]
No worries, hopefully it was a busy FUN weekend!  I tried the tdarr_acc:dev build and still having the same problem:

Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading

Starting Tdarr_Server

version: 2.00.16

linux_x64_docker_true

Preparing environment

/app/configs/Tdarr_Server_Config.json

{

  serverPort: '8266',

  webUIPort: '8265',

  serverIP: '192.168.10.9',

  handbrakePath: '',

  ffmpegPath: ''

}

Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading


Starting Tdarr_Server

version: 2.00.16

linux_x64_docker_true

Preparing environment

/app/configs/Tdarr_Server_Config.json

{

  serverPort: '8266',

  webUIPort: '8265',

  serverIP: '192.168.10.9',

  handbrakePath: '',

  ffmpegPath: ''

}

Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading

**Comment by HaveAGitGat** [comment]
No it was spent debugging some Tdarr issues lol.

Okay thanks. Might need one of you to send me your machines 😅.

Could this be a filesytem issue? What file system are you using? Has anyone tried running on different one?

**Comment by thtwice** [comment]
Yep, same behavior here too..
This one fails the first start also

```
`[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 01-migrations: executing... 

[migrations] started

[migrations] no migrations found

[cont-init.d] 01-migrations: exited 0.

[cont-init.d] 01-setup-perms: executing... 

usermod: no changes



User uid:    1000

User gid:    1000

-------------------------------------



Chowning the appassets, this make take some time

chmod: cannot access '/app/Tdarr_Node/assets/app/fileScanner/': No such file or directory

chmod: cannot access '/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe': No such file or directory

[cont-init.d] 01-setup-perms: exited 0.

[cont-init.d] 02-hw-transcoding: executing... 

[cont-init.d] 02-hw-transcoding: exited 0.

[cont-init.d] 02-tamper-check: executing... 

[cont-init.d] 02-tamper-check: exited 0.

[cont-init.d] 10-adduser: executing... 



-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/





Brought to you by linuxserver.io

-------------------------------------



To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------



User uid:    1000

User gid:    1000

-------------------------------------



[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Starting Tdarr_Server

Starting Tdarr_Node

version: 2.00.16

linux_x64_docker_true

/app/configs/Tdarr_Node_Config.json

{

  nodeID: 'MyInternalNode',

  nodeIP: '0.0.0.0',

  nodePort: '8367',

  serverIP: '0.0.0.0',

  serverPort: '8366',

  handbrakePath: '',

  ffmpegPath: '',

  mkvpropeditPath: '',

  pathTranslators: [ { server: '', node: '' } ],

  platform_arch: 'linux_x64_docker_true'

}

[2022-03-09T21:14:13.318] [INFO] Tdarr_Node - Starting Tdarr_Node

Preparing environment

version: 2.00.16

linux_x64_docker_true

Preparing environment

[2022-03-09T21:14:13.435] [INFO] Tdarr_Node - Updating plugins

[2022-03-09T21:14:13.440] [INFO] Tdarr_Node - Tdarr_Node listening at http://0.0.0.0:8367

[2022-03-09T21:14:13.734] [INFO] Tdarr_Node - ---------------Binary tests start----------------

[2022-03-09T21:14:13.746] [INFO] Tdarr_Node - handbrakePath:HandBrakeCLI

[2022-03-09T21:14:13.756] [INFO] Tdarr_Node - ffmpegPath:ffmpeg

[2022-03-09T21:14:13.769] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit

[2022-03-09T21:14:13.770] [INFO] Tdarr_Node - Binary test 1: handbrakePath working

[2022-03-09T21:14:13.770] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working

[2022-03-09T21:14:13.770] [INFO] Tdarr_Node - ---------------Binary tests end-------------------

/app/configs/Tdarr_Server_Config.json

{

  serverPort: '8366',

  webUIPort: '8365',

  serverIP: '0.0.0.0',

  handbrakePath: '',

  ffmpegPath: ''

}

[2022-03-09T21:14:13.969] [ERROR] Tdarr_Node - Failed to contact server, retrying...

Reading DB:>>>>>>>>>>(100%):0:SettingsGlobalJSONDB::Reading done



[2022-03-09T21:14:15.443] [ERROR] Tdarr_Node - Server not alive IP:0.0.0.0 PORT:8366

[2022-03-09T21:14:15.972] [ERROR] Tdarr_Node - Failed to contact server, retrying...

[2022-03-09T21:14:17.445] [ERROR] Tdarr_Node - Server not alive IP:0.0.0.0 PORT:8366

[2022-03-09T21:14:17.974] [ERROR] Tdarr_Node - Failed to contact server, retrying...

[2022-03-09T21:14:19.446] [ERROR] Tdarr_Node - Server not alive IP:0.0.0.0 PORT:8366

[2022-03-09T21:14:19.975] [ERROR] Tdarr_Node - Failed to contact server, retrying...
```
`


It's just an ext4 fs on a SATA SSD. Do you have any suggestion on what I shoult try that could help you debugging?

I'm pasting my fstab relative to that partition but it's really a bog standard setup fs-wise:

`UUID=03bdfa6a-dc18-43e8-b0b8-e3e503c84f7z       /                       ext4    errors=remount-ro,discard,noatime       0       1
`

**Comment by thtwice** [comment]
So, I think I've got something new.
I can start a container using:
`docker run -ti    -v /home/twice/tdarrnew/server:/app/server     -v /home/twice/tdarrnew/configs:/app/configs       -v /home/twice/tdarrnew/logs:/app/logs       -v /media:/media       -v /home/twice/Backup/Scaricati/convertions:/temp       -e "serverIP=0.0.0.0"       -e "serverPort=8366"       -e "webUIPort=8365"   -e "internalNode=true"     -e "nodeID=MyInternalNode"       -e "nodeIP=0.0.0.0"    -e "nodePort=8367"     --network bridge       -p 8365:8365       -p 8366:8366       -e "TZ=Europe/Rome"    -e PUID=1000       -e PGID=1000   --memory=4096m    --log-opt max-size=10m    --log-opt max-file=5       haveagitgat/tdarr_acc:dev`

at this point I can exit the container but if I then start it again using:
`docker start tdarrnew`
it fails.

But if I (without touching the config files) then run `docker run -ti    -v /home/twice/tdarrnew/server:/app/server     -v /home/twice/tdarrnew/configs:/app/configs       -v /home/twice/tdarrnew/logs:/app/logs       -v /media:/media       -v /home/twice/Backup/Scaricati/convertions:/temp       -e "serverIP=0.0.0.0"       -e "serverPort=8366"       -e "webUIPort=8365"   -e "internalNode=true"     -e "nodeID=MyInternalNode"       -e "nodeIP=0.0.0.0"    -e "nodePort=8367"     --network bridge       -p 8365:8365       -p 8366:8366       -e "TZ=Europe/Rome"    -e PUID=1000       -e PGID=1000   --memory=4096m    --log-opt max-size=10m    --log-opt max-file=5       haveagitgat/tdarr_acc:dev` again it creates a new container that reads the config files without problem and runs fine.

Could it be that tdarr is messing up the container during the shutdown procedures?
If the new  container manages to read the settings file without problem maybe the issue is not in that file.

Can @[timberjoegithub](https://github.com/timberjoegithub) confirm this behavior?


The last few lines of the container shutting down don't give any clues sadly:
`[2022-03-09T22:10:23.888] [INFO] Tdarr_Server - Finished downloading plugins!
[2022-03-09T22:10:27.099] [INFO] Tdarr_Server - [3.607s]Plugin update finished
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by HaveAGitGat** [comment]
The base image is a standard linux server io one, you can see the Docker file here:
https://github.com/HaveAGitGat/Tdarr/blob/master/docker/Dockerfile

I've updated the dev container so it runs a R/W accessibility check before reading the file. Should give an error if there are any problems: 

`Tdarr/DB2/StagedJSONDB/17e214ac4fd5bbc165fef6b7600fc2c1683687fd.json:R/W Accessible`

**Comment by timberjoegithub** [comment]
My UI is now coming up!!!!! of course my nodes are mismatched so nothing is processing, but it appears to be working.  Would you recommend I upgrade the nodes as well or wait for the dev channel to move to latest to get it all working again?

**Comment by timberjoegithub** [comment]
I changed the source from dockerhub HaveAGitGat/tdarr:latest to HaveAGitGat/tdar_acc:dev in Portainer and redeployed with pulling new image checked. 

Reboot still brings up UI and looks like it loads all the DB entries.  I did move one of my nodes from dockerhub HaveAGitGat/tdarr_node:latest to HaveAGitGat/tdarr_node:dev but that appears to have backrev'd that node to 2.00.12 while tdarr_node:latest is at 2.00.15 and tdarr_acc:dev is at 2.00.16.  I assume once I get a node at 2.00.16 everything should work.

I do have watchtower running so I get any new dockerhub deployments of a branch I am using every 24 hours.

**Comment by thtwice** [comment]
Yep. alright. I can now confirm that whatever changes @HaveAGitGat did to the acc:dev everything seems to be working.

Great job!

Now to just wait for these changes to get published on the stable image :-)

Btw, @HaveAGitGat , what ended up being the source of the problems?

**Comment by RyanMakesMovies** [comment]
Checking in - acc:dev seems to be working fine! 

Related question - my node is on a Windows machine - is there a way for us to access the Win build of 2.00.16 Node?

**Comment by HaveAGitGat** [comment]
Awesome, thanks for trying 😀.

Well I’m not sure what fixed it as I changed 2 things at once. The first was adding the file access check and the second was removing a 3rd party console log dependency. I think it might have been the latter. 

Glad it’s working though. Which packages do you need? I can build the .16 pre release ones.

**Comment by timberjoegithub** [comment]
If you build the .16 ones I did get one node upgraded (had to snoop around to find the repository) and proved that it is actually appears to be processing.  I think all we need is them built and us pointed to them.

Thank you so much for being responsive and solving the problem.

**Comment by HaveAGitGat** [comment]
No problemo. I've built the updated pre-release containers/packages for .16 on a few more architectures. Please could you check it's working for you and also try out the cool new job report system :). Thanks.

![jobReportViewer](https://user-images.githubusercontent.com/43864057/158064246-238225f7-10f8-4d58-9c2a-bde380c81b58.png)



Docker (x64):
```
ghcr.io/haveagitgat:tdarr_acc:dev
ghcr.io/haveagitgat:tdarr_node_acc:dev
```

Native:
```
  "2.00.16": {
    "darwin_x64": {
      "Tdarr_Node": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/darwin_x64/Tdarr_Node.zip",
      "Tdarr_Server": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/darwin_x64/Tdarr_Server.zip"
    },
    "linux_x64": {
      "Tdarr_Node": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/linux_x64/Tdarr_Node.zip",
      "Tdarr_Server": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/linux_x64/Tdarr_Server.zip",
      "Tdarr_WebUI": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/linux_x64/Tdarr_WebUI.zip"
    },
    "win32_x64": {
      "Tdarr_Node": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/win32_x64/Tdarr_Node.zip",
      "Tdarr_Server": "https://f000.backblazeb2.com/file/tdarrs/versions/2.00.16/win32_x64/Tdarr_Server.zip"
    }
  }
```

**Comment by thtwice** [comment]
Can confirm it works on docker on an x86 machine.

Just created the container and restarted it a few times and it seems to be fixed.

Thanks again to @HaveAGitGat for the quick work!

**Comment by HaveAGitGat** [comment]
:). 2.00.16 released.
