### ISSUE TITLE
Tdarr doesn't always remove the Cache suffix after processing a file

### ISSUE THREAD

**Issue by dstufft** [HaveAGitGat/Tdarr#553]
**Describe the bug**
A problem I've noticed that *sometimes* happens, but not always, is that after Tdarr has processed a file and moved it back into it's final location, it will still have the Tdarr cache suffix.

So in other words, I will add a new file like:

```
/mnt/data/media/Movies/Some Movie (YYYY)/Some Movie Remux-2160p.mkv
```

Tdarr will see the new file, wait the 1 hour hold I have set, then run my plugins, then once it's finished it will copy the modified file back to the original directory and delete the old file, however it will end up with a filename like:

```
/mnt/data/media/Movies/Some Movie (YYYY)/Some Movie Remux-2160p-TdarrCacheFile-dIzKvSgkr.mkv
```

with the original file gone.

As far as I can tell, the file appears to be correctly processed, and when I manually rename it and Tdarr picks it back up again it runs it through the plugin stack, with no changes needing to be made. 

**To Reproduce**

I'm unsure what is causing it or how to reproduce it. It just occasionally happens. 

**Expected behavior**

The filename should match what it was originally, without the TdarrCacheFile suffix.

[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/8007294/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/8007297/Tdarr_Node_Log.txt)

 - OS: Linux
 - Browser Edge
 - Version 2.00.13
-  Running in Docker

**Comment by HaveAGitGat** [comment]
Sounds like something else might be preventing the file rename. Do you have any other applications monitoring the same folders?

**Comment by dstufft** [comment]
Just a pretty basic *arr, Plex, Tdarr stack.

**Comment by HaveAGitGat** [comment]
Thanks, I've added some extra error logging during the rename so the errors should show up in .14 logs with the reason.

**Comment by HaveAGitGat** [comment]
Reopen if you still have this issue on .14 (released).
