### ISSUE TITLE
11th gen intel / Tiger Lake hevc VAAPI encoding broken with QSV

### ISSUE THREAD

**Issue by rnsc** [HaveAGitGat/Tdarr#555]
**Describe the bug**
When trying to encode hevc files on a 11th gen Intel/Tiger Lake, you end up with a garbage encoding.
This has been flagged here on the Intel repos: https://github.com/intel/media-driver/issues/1190

**To Reproduce**
I have a Tdarr Dockerfile in which I install the lastest Intel non free drivers, like the linuxserver.io team does for Plex: https://github.com/linuxserver/docker-plex/blob/db1e255267abeed25f2ac4ffba33724c1c07d91a/Dockerfile#L25-L35
```
 echo "**** add Intel repo ****" && \
 curl -sL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add - && \
 echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' > /etc/apt/sources.list.d/intel.list && \
 echo "**** install runtime packages ****" && \
 apt-get update && \
 apt-get install -y \
	jq \
	intel-opencl-icd \
	udev \
	unrar \
	wget && \
```

Someone already did a patch for ffmpeg to fix this issue, following this comment:
https://github.com/intel/media-driver/issues/1190#issuecomment-963747307

The patch itself:
https://github.com/intel-media-ci/cartwheel-ffmpeg/blob/master/patches/0025-lavc-vaapi_encode_h265-fix-max_transform_hierarchy_d.patch

Given that, could we fork the jellyfin-ffmpeg repository and include this patch and install the updated Debian package in the Tdarr image?

I can also open a Github issue for the jellyfin team.

**Expected behavior**
I'd expect encodings to work without issues.

**Screenshots**
![Example from the Intel repo](https://user-images.githubusercontent.com/882016/116470023-8d4cda80-a87b-11eb-99ac-367c041acf3d.png)

**Please provide the following information:**

 - OS: Ubuntu Focal
 - Browser: NA
 - Version: NA

**Comment by rnsc** [comment]
JellyFin team has a potential fix coming in https://github.com/jellyfin/jellyfin-ffmpeg/issues/90

**Comment by HaveAGitGat** [comment]
Thanks, will wait for that.

**Comment by rnsc** [comment]
Hey @HaveAGitGat , the new version of jellyfin-ffmpeg has been released:
https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v4.4.1-2

**Comment by rnsc** [comment]
Just tested the new built package and I have artefacts, so it's not fixed

**Comment by HaveAGitGat** [comment]
Hmm that's not ideal. Nonetheless I've updated the dev image with it:
`docker.io/haveagitgat/tdarr_acc:dev`

**Comment by HaveAGitGat** [comment]
Have been using ffmpeg 5 for the last few months and haven't had any reports of this so will close, reopen if needed ty.
