### ISSUE TITLE
common numbers/phrases highlighted in bad context

### ISSUE THREAD

**Issue by Gumbyohson** [HaveAGitGat/Tdarr#557]
**Describe the bug**
The information view on plugin processing appears to highlight any instance of certain numbers despite the context. 

**To Reproduce**
Steps to reproduce the behavior: Have the number 720, 265, etc, appear at any point in the transcoding information context menu even if it is part of another number (eg "target = 2720", the 720 in 2720 is highlighted as if this denotes 720P).

**Expected behavior**
The numbers and codex names should only highlight in the appropriate context.

**Screenshots**
Attached

**Please provide the following information:**
- Config files: na

- Log files: na

-Worker error: na

 - OS: Windows server 2016 Standard
 - Browser: Chrome
 - Version 97.0.4692.99

Example attached
![2022-02-07 17_59_00-Window](https://user-images.githubusercontent.com/1866263/152740080-2e895614-a6a9-4386-a746-8b19ac4a2889.png)

**Comment by Gumbyohson** [comment]
Very low priority issue but thought I would bring it up. I couldn't see another issue similar during a brief scan.

**Comment by HaveAGitGat** [comment]
There are thousands of potential scenarios (probably millions when including all the random filenames people might have) so most likely won't work on this as it would be a project in and of itself. It's just meant to do some basic highlighting, can add an option to turn it off if needed.
