### ISSUE TITLE
MKV-Chapter-Maker

### ISSUE THREAD

**Issue by binarygeek119** [HaveAGitGat/Tdarr#559]
i would love to be able to run this program on all my media. 
[MKV-Chapter-Maker](https://github.com/optio50/MKV-Chapter-Maker)
what it does is looks for black frames and adds them as chapter points.
a lot of my media is missing chapters. and i want to use this with 
[ErsatzTV](https://github.com/jasongdove/ErsatzTV)
so i can have Commercial breaks in my fake tv channels. at this point i works by using chapter data to find when to go to Commercial.

**Comment by HaveAGitGat** [comment]
There is the `Run CLI` flow plugin so you can specify the custom mkv command for generating chapters or whatever else you're after:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/16284c94-0517-43b8-a5f6-66601432fce0)

Hope that helps.
