### ISSUE TITLE
/api/v2/cruddb api documentation

### ISSUE THREAD

**Issue by systemmonkey42** [HaveAGitGat/Tdarr#560]
Is there documentation for the 'cruddb' API?

The basic documented API is very limited, and I've often seen issues where the answer is to perform some undocumented request
via the cruddb API

eg https://github.com/HaveAGitGat/Tdarr/issues/540#issuecomment-1019399128

Is the cruddb api documented?  Where can I get information on how to use it?

This problem I am trying to solve is simple - query the running Tdarr_Server for the status of the "Transcode Queue".  If there are items waiting, use Wake-on-Lan to bring a remote worker node online to process the queue.

Thanks

**Comment by HaveAGitGat** [comment]
I've added that endpoint to the api docs:

https://tdarr.readme.io/reference/post_cruddb

![image](https://user-images.githubusercontent.com/43864057/153130449-ee75185a-ff94-4fa3-923c-ac35948c4216.png)

For your use case, you'd need to do something similar to this:

https://github.com/linuxserver/Heimdall-Apps/pull/419/files

So you'd need to query `StatisticsJSONDB` and then get `table1Count` for the transcode queue. Hope that helps.
