### ISSUE TITLE
GPU transcoding very strange behaviour

### ISSUE THREAD

**Issue by janipewter** [HaveAGitGat/Tdarr#562]
Issue: when transcoding, the worker under the Node window is disappearing and reappearing approximately every half a second.

![off](https://user-images.githubusercontent.com/18750515/154854604-568ccb5b-055e-474c-b704-149f83924910.png)
![on](https://user-images.githubusercontent.com/18750515/154854605-4785573f-7cab-4eaf-8c69-7e5b68b3a83b.png)

If I manage to hit the info button on the worker, the popup window disappears as soon as the worker disappears. It does appear to be transcoding though - the file is being written in the cache and eventually the transcode does complete. Some transcodes complete successfully, others fail. Example of a failed one:

`
NodeID: Heineken (Quadro P1000)

Command:

ffmpeg -c:v h264_cuvid -i /mnt/media/TV Shows/Band of Brothers (2001) [imdb-tt0185906]/Season 01/Band of Brothers (2001) - S01E06 - Bastogne [Bluray-1080p][AC3 5.1][x264]-CtrlHD.mkv -map 0 -c:v hevc_nvenc -rc:v vbr_hq -cq:v 19 -b:v 9231k -minrate 6461k -maxrate 12000k -bufsize 18462k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le /temp/Band of Brothers (2001) - S01E06 - Bastogne [Bluray-1080p][AC3 5.1][x264]-CtrlHD-TdarrCacheFile-i-z3NNue8.mkv

Last 200 lines of CLI log:

ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers

built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)

configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec

libavutil 56. 51.100 / 56. 51.100

libavcodec 58. 91.100 / 58. 91.100

libavformat 58. 45.100 / 58. 45.100

libavdevice 58. 10.100 / 58. 10.100

libavfilter 7. 85.100 / 7. 85.100

libswscale 5. 7.100 / 5. 7.100

libswresample 3. 7.100 / 3. 7.100

libpostproc 55. 7.100 / 55. 7.100

Input #0, matroska,webm, from '/mnt/media/TV Shows/Band of Brothers (2001) [imdb-tt0185906]/Season 01/Band of Brothers (2001) - S01E06 - Bastogne [Bluray-1080p][AC3 5.1][x264]-CtrlHD.mkv':

Metadata:

title : Band.Of.Brothers.E06.2001.1080p.BluRay.DD5.1.x264-CtrlHD

encoder : libebml v1.3.10 + libmatroska v1.5.2

creation_time : 2020-03-16T08:37:26.000000Z

Duration: 01:07:19.52, start: 0.000000, bitrate: 19359 kb/s

Chapter #0:0: start 0.000000, end 149.149000

Metadata:

title : 00:00:00.000

Chapter #0:1: start 149.149000, end 224.349000

Metadata:

title : 00:02:29.149

Chapter #0:2: start 224.349000, end 513.513000

Metadata:

title : 00:03:44.349

Chapter #0:3: start 513.513000, end 836.669000

Metadata:

title : 00:08:33.513

Chapter #0:4: start 836.669000, end 1238.070000

Metadata:

title : 00:13:56.669

Chapter #0:5: start 1238.070000, end 1548.839000

Metadata:

title : 00:20:38.070

Chapter #0:6: start 1548.839000, end 1923.922000

Metadata:

title : 00:25:48.839

Chapter #0:7: start 1923.922000, end 2318.858000

Metadata:

title : 00:32:03.922

Chapter #0:8: start 2318.858000, end 2643.641000

Metadata:

title : 00:38:38.858

Chapter #0:9: start 2643.641000, end 3031.237000

Metadata:

title : 00:44:03.641

Chapter #0:10: start 3031.237000, end 3494.366000

Metadata:

title : 00:50:31.237

Chapter #0:11: start 3494.366000, end 3845.091000

Metadata:

title : 00:58:14.366

Chapter #0:12: start 3845.091000, end 4039.520000

Metadata:

title : 01:04:05.091

Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)

Metadata:

title : Band.Of.Brothers.E06.2001.1080p.BluRay.DD5.1.x264-CtrlHD

BPS-eng : 18752007

DURATION-eng : 01:07:12.028000000

NUMBER_OF_FRAMES-eng: 96672

NUMBER_OF_BYTES-eng: 9451077653

_STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2020-03-16 08:37:26

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s

(default)

Metadata:

BPS-eng : 640000

DURATION-eng : 01:07:19.520000000

NUMBER_OF_FRAMES-eng: 126235

NUMBER_OF_BYTES-eng: 323161600

_STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2020-03-16 08:37:26

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream #0:2(eng): Subtitle: subrip

Metadata:

BPS-eng : 40

DURATION-eng : 01:00:31.590000000

NUMBER_OF_FRAMES-eng: 502

NUMBER_OF_BYTES-eng: 18405

_STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit

_STATISTICS_WRITING_DATE_UTC-eng: 2020-03-16 08:37:26

_STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

[h264_cuvid @ 0x55b9455a6380] Cannot load libnvcuvid.so.1

[h264_cuvid @ 0x55b9455a6380] Failed loading nvcuvid.

Stream mapping:

Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1

(copy)

Stream #0:2 -> #0:2 (copy)

Error while opening decoder for input stream #0:0 : Operation not permitted
`

My setup:
Unraid (latest version)
Tdarr and Tdarr node dockers on Unraid
Nvidia P1000, driver v510.54
Everything in Unraid/Tdarr is set up correctly as I've previously transcoded 700+ items with no issue. This strange behaviour only started yesterday. I noticed there was an update to the Tdarr docker yesterday; I don't know if this is coincidence. GPU HW transcoding in Plex works flawlessly.

Other infos:

`
root@heineken:~# ldconfig -p | grep libnv
        libnvoptix.so.1 (libc6,x86-64) => /usr/lib64/libnvoptix.so.1
        libnvidia-vulkan-producer.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-vulkan-producer.so.510.54
        libnvidia-vulkan-producer.so (libc6,x86-64) => /usr/lib64/libnvidia-vulkan-producer.so
        libnvidia-tls.so.510.54 (libc6,x86-64, OS ABI: Linux 2.3.99) => /usr/lib64/libnvidia-tls.so.510.54
        libnvidia-rtcore.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-rtcore.so.510.54
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-ptxjitcompiler.so.1
        libnvidia-ptxjitcompiler.so (libc6,x86-64) => /usr/lib64/libnvidia-ptxjitcompiler.so
        libnvidia-opticalflow.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-opticalflow.so.1
        libnvidia-opticalflow.so (libc6,x86-64) => /usr/lib64/libnvidia-opticalflow.so
        libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-opencl.so.1
        libnvidia-nvvm.so.4 (libc6,x86-64) => /usr/lib64/libnvidia-nvvm.so.4
        libnvidia-nvvm.so (libc6,x86-64) => /usr/lib64/libnvidia-nvvm.so
        libnvidia-ngx.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-ngx.so.1
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-ml.so.1
        libnvidia-ml.so (libc6,x86-64) => /usr/lib64/libnvidia-ml.so
        libnvidia-gtk3.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-gtk3.so.510.54
        libnvidia-gtk2.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-gtk2.so.510.54
        libnvidia-glvkspirv.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-glvkspirv.so.510.54
        libnvidia-glsi.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-glsi.so.510.54
        libnvidia-glcore.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-glcore.so.510.54
        libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-fbc.so.1
        libnvidia-fbc.so (libc6,x86-64) => /usr/lib64/libnvidia-fbc.so
        libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-encode.so.1
        libnvidia-encode.so (libc6,x86-64) => /usr/lib64/libnvidia-encode.so
        libnvidia-eglcore.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-eglcore.so.510.54
        libnvidia-egl-wayland.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-egl-wayland.so.1
        libnvidia-egl-gbm.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-egl-gbm.so.1
        libnvidia-container.so.1 (libc6,x86-64) => /usr/lib/libnvidia-container.so.1
        libnvidia-container.so (libc6,x86-64) => /usr/lib/libnvidia-container.so
        libnvidia-container-go.so.1 (libc6,x86-64) => /usr/lib/libnvidia-container-go.so.1
        libnvidia-container-go.so (libc6,x86-64) => /usr/lib/libnvidia-container-go.so
        libnvidia-compiler.so.510.54 (libc6,x86-64) => /usr/lib64/libnvidia-compiler.so.510.54
        libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-cfg.so.1
        libnvidia-cfg.so (libc6,x86-64) => /usr/lib64/libnvidia-cfg.so
        libnvidia-allocator.so.1 (libc6,x86-64) => /usr/lib64/libnvidia-allocator.so.1
        libnvidia-allocator.so (libc6,x86-64) => /usr/lib64/libnvidia-allocator.so
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib64/libnvcuvid.so.1
        libnvcuvid.so (libc6,x86-64) => /usr/lib64/libnvcuvid.so
`

`
root@heineken:~# nvidia-smi
Sun Feb 20 17:05:58 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P1000        Off  | 00000000:07:00.0 Off |                  N/A |
| 43%   55C    P0    N/A /  N/A |    463MiB /  4096MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     26429      C   ffmpeg                            461MiB |
+-----------------------------------------------------------------------------+
`

`
# ldconfig -p | grep libnv
        libnvoptix.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvoptix.so.1
        libnvidia-tls.so.510.54 (libc6,x86-64, OS ABI: Linux 2.3.99) => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.510.54
        libnvidia-rtcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.510.54
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
        libnvidia-opticalflow.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1
        libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
        libnvidia-ngx.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.1
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
        libnvidia-glvkspirv.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.510.54
        libnvidia-glsi.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.510.54
        libnvidia-glcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.54
        libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1
        libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
        libnvidia-eglcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.510.54
        libnvidia-compiler.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.510.54
        libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1
        libnvidia-allocator.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.1
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
`

`
# nvidia-smi
Sun Feb 20 17:06:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P1000        Off  | 00000000:07:00.0 Off |                  N/A |
| 43%   55C    P0    N/A /  N/A |    463MiB /  4096MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     26429      C                                     461MiB |
+-----------------------------------------------------------------------------+
`

**Comment by janipewter** [comment]
Queued up a season folder for transcode, it failed on all but one episode which was successful, but if I kept on re-queuing the failed ones, eventually it works lol

**Comment by jackfalveyiv** [comment]
Seeing the same problem, looks like you are having more success than I am.  Previously over 12000 successful transcodes, once my server updated this morning.  Pastebin of my error:

https://pastebin.com/EKqnG7NR

# nvidia-smi
Sun Feb 20 14:33:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 40%   50C    P2    73W / 270W |   3337MiB /  8192MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1475      C                                     231MiB |
|    0   N/A  N/A     20123      C                                     341MiB |
|    0   N/A  N/A     20127      C                                     616MiB |
|    0   N/A  N/A     20559      C                                     616MiB |
|    0   N/A  N/A     20816      C                                     614MiB |
|    0   N/A  N/A     20911      C                                     616MiB |
|    0   N/A  N/A     22612      C                                     292MiB |
+-----------------------------------------------------------------------------+
# 

---------------------------------------------------------------------------------------------------------------------

# ldconfig -p | grep libnv
        libnvoptix.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvoptix.so.1
        libnvidia-tls.so.510.54 (libc6,x86-64, OS ABI: Linux 2.3.99) => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.510.54
        libnvidia-rtcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.510.54
        libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
        libnvidia-opticalflow.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1
        libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
        libnvidia-ngx.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.1
        libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
        libnvidia-glvkspirv.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.510.54
        libnvidia-glsi.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.510.54
        libnvidia-glcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.510.54
        libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1
        libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
        libnvidia-eglcore.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.510.54
        libnvidia-compiler.so.510.54 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.510.54
        libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1
        libnvidia-allocator.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.1
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
#

**Comment by jackfalveyiv** [comment]
Also adding that while I'm currently on v510.47.03 nvidia driver, I started troubleshooting this morning on v470.74 and got the same errors.

**Comment by Tharkn** [comment]
I'm facing the same issues with the docker containers on version 2.00.14.

I've been able to fix that behavior by downgrading to version 2.00.13 on both server and nodes :)

**Comment by HaveAGitGat** [comment]
This is most likely due to the update including a Node in the Server image which is causing interference for some.

I've just released a small Server image update so you now have to set `internalNode=true` to enable the Node in the Server container. So pull the latest container and enable the internal Node as you see fit.

https://docs.tdarr.io/docs/installation/docker/run-compose/

**Comment by HaveAGitGat** [comment]
Reopen if you still have issues.

**Comment by janipewter** [comment]
How can I do this in unraid?

**Comment by supersnellehenk** [comment]
> How can I do this in unraid?

Edit the container, scroll down, click 'Add port, variable bla bla bla', change it to variable, key is `internalNode` and value is `true`.

**Comment by janipewter** [comment]
> 

Thanks, I realise what the above meant now. I have updated my server image and it appears to have fixed the issue. I am not running the internal node in the server, I am running the separate tdarr_node image on the same machine. Will report back after some tests to confirm the fix is good.

**Comment by HaveAGitGat** [comment]
Great, thanks 👍

**Comment by SmilinJoe** [comment]
I am still seeing this even after going to a node and server container. I just deployed this today, and don't have a working config to fall back on. Pretty sure my nvidia drivers are correct as Plex works and nvidia-smi reports back correctly. This is my docker-compose: 
```
  # Tdarr Server
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    networks:
      - traefik2_proxy
    ports:
      - 8266:8266 # server port
    volumes:
      - ${DOCKERDIR}/tdarr/server:/app/server
      - ${DOCKERDIR}/tdarr/configs:/app/configs
      - ${DOCKERDIR}/tdarr/logs:/app/logs
      - ${DOCKERDIR}/tdarr/transcode_cache:/temp
      - ${MEDIADIR}/movies:/media/movies
      - ${MEDIADIR}/tvshows:/media/tvshows
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKERDIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.tdarr-rtr.entrypoints=https" 
      - "traefik.http.routers.tdarr-rtr.rule=HostHeader(`tdarr.$DOMAINNAME`)"  
      - "traefik.http.routers.tdarr-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.tdarr-rtr.middlewares=chain-authelia@file"       
      ## HTTP Services
      - "traefik.http.routers.tdarr-rtr.service=tdarr-svc"
      - "traefik.http.routers.tdarr-rtr-bypass.service=tdarr-svc"
      - "traefik.http.services.tdarr-svc.loadbalancer.server.port=8265"

  # Tdarr Node
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    networks:
      - traefik2_proxy  
    ports:
      - 8268:8268
    volumes:
      - ${DOCKERDIR}/tdarr/server:/app/server
      - ${DOCKERDIR}/tdarr/configs:/app/configs
      - ${DOCKERDIR}/tdarr/logs:/app/logs
      - ${DOCKERDIR}/tdarr/transcode_cache:/temp
      - ${MEDIADIR}/movies:/media/movies
      - ${MEDIADIR}/tvshows:/media/tvshows
      - "/etc/localtime:/etc/localtime:ro"
      - ${DOCKERDIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - nodeID=NapsterNode
      - nodeIP=x.x.y.y
      - nodePort=8268
      - serverIP=x.x.y.y
      - serverPort=8266
    devices:
      - /dev/dri:/dev/dri
```

**Comment by NeoDuder** [comment]
Can the Internal Node still support Nvidia cards? I assume we just need add the NV environment variables to the main server container now instead of the node?

**Comment by HaveAGitGat** [comment]
Yes the Server and Node use the same Docker file so you just need to add the relevant env variables.
