### ISSUE TITLE
[2.00.13] Health Check error: "New transcode arguments were the exact same as the last ones"

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#564]
**Describe the bug**

I had some issues with my downloaders I and triggered a fresh scan of all of my movies.
I have cleared the Output files and triggered a new search.
Many movies went straight to the Transcode: Error/Cancelled category saying the following:

```
The new transcode arguments were the exact same as the last ones meaning
the file/worker would most likely be stuck in an infinite transcode loop if not stopped.
Last arguments:
New arguments:

```

However, this is not true, this is a fresh scan.

**To Reproduce**
1- Clear the Output files
2- Trigger a fresh scan on movies that have been already checked/transcoded before.

**Expected behavior**
System should process the files correctly, there are no stuck processes.

**Screenshots**
![image](https://user-images.githubusercontent.com/35738729/154963475-db65d25a-c39e-40a0-82f0-9bd184e1953c.png)

 - OS: Raspberry Pi OS 32bits (armv7)
 - Version: 2.00.13

**Comment by HaveAGitGat** [comment]
Are you doing health checks or transcodes? What are your settings for each? If transcoding, seems the plugin you're using isn't giving any transcode arguments.

**Comment by HaveAGitGat** [comment]
Re-open if needed, thanks.
