### ISSUE TITLE
.14 web UI going unresponsive constantly

### ISSUE THREAD

**Issue by Enigma0** [HaveAGitGat/Tdarr#566]
It was a problem in .13 but is much worse in .14

Most interactions with queue items, whether accepting staged items or really clicking any button on the main page often causes the whole UI to become unresponsive requiring `http://[IP]:8265/api/v2/restart-ui` to be issued to regain access.

**Comment by HaveAGitGat** [comment]
Do you get the same issue when running incognito?

**Comment by Enigma0** [comment]
> Do you get the same issue when running incognito?

I'll try that an report back.

**Comment by HaveAGitGat** [comment]
Are you able to provide details about which platform/architecture you're using? Are there any errors in the logs?

By unresponsive what do you mean? Are you able to refresh the page and it loads?

Ideally the bug report template should be filled out when creating a bug report, thanks:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 2.00.00]


**Additional context**
Add any other context about the problem here.
```

![image](https://user-images.githubusercontent.com/43864057/155460554-6bad2d07-8f71-43d1-8295-501fe25aa122.png)

**Comment by HaveAGitGat** [comment]
Will put this under this issue as I think it's the same:
https://github.com/HaveAGitGat/Tdarr/issues/532
