### ISSUE TITLE
Req: Use a more unique command to launch the ffmpeg process.

### ISSUE THREAD

**Issue by NeoDuder** [HaveAGitGat/Tdarr#567]
The GPU Info Dash plugin in UnRaid will usually show a small logo to show what programs are utilising the GPU. It is unable to do this with TDARR as the process just shows as "ffmpeg". Is there any way to have this process changed to a TDARR-Specific process in order that the GPU Dash Plugin can recognise TDARR specifically? See following forum discussion for more info...

https://forums.unraid.net/topic/89453-plugin-gpu-statistics/page/23/?tab=comments#comment-1099885

Thanks in advance :)

**Comment by NeoDuder** [comment]
> The Docker file is here so if you have some suggested changes then can open a PR if you like:
> 
> https://github.com/HaveAGitGat/Tdarr/blob/9387eb4eba1a138a3478ecb568205cbdd9e37132/docker/Dockerfile#L38

I'm no coder, lol. I just wanted a nice little logo in my GPU dashboard. I think the developer of the GPU dash on that forum post mentioned that all he'd need is for the symbolic link to be named differently. So I guess something like...

ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/tdarr-ffmpeg && \

But like I said, I'm no coder. I guess this would then cause issues for the Tdarr process that calls ffmpeg?

**Comment by fkmuck1** [comment]
NeoDuder, I think you are talking about your request you made here?:
`https://forums.unraid.net/topic/89453-plugin-gpu-statistics/page/23/#comment-1100166`

HaveAGitGat, maybe you can easily understand and implement the programmer's answer in the post above? I would support the request because I would also like it if the process were clearly identifiable and a logo could be displayed in the unraid dashboard.

**Comment by HaveAGitGat** [comment]
This should now be working in the dev image, would you mind checking it works for you? Images are:
`haveagitgat/tdarr_acc:dev`
`haveagitgat/tdarr_node_acc:dev`

**Comment by NeoDuder** [comment]
Yes. Working Perfectly, thank you!

**Comment by HaveAGitGat** [comment]
Great, thanks for the info. Will be in .17.
