### ISSUE TITLE
unable to start tdarr_node docker on unraid

### ISSUE THREAD

**Issue by wgstarks** [HaveAGitGat/Tdarr#569]
**Describe the bug**
I believe this is due to the node port entry on the new unraid template.

docker run command-
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='tdarr_node' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'serverIP'='10.0.1.20' -e 'serverPort'='8266' -e 'nodeIP'='10.0.1.20' -e 'nodeID'='node_1' -e 'PUID'='99' -e 'PGID'='100' -e 'NVIDIA_VISIBLE_DEVICES'='GPU-b4602330-5b21-6f5e-bbc1-1107747562ec' -e 'NVIDIA_DRIVER_CAPABILITIES'='all' -p '8267:8267/tcp' -p '8267:nodePort/tcp' -v '/mnt/user/appdata/tdarr/configs':'/app/configs':'rw' -v '/mnt/user/appdata/tdarr/logs':'/app/logs':'rw' -v '/mnt/user/Media/':'/mnt/media':'rw' -v '/mnt/user/Media/tdarr_transcode/':'/temp':'rw' --runtime=nvidia 'haveagitgat/tdarr_node' 
docker: Invalid containerPort: nodePort.
See 'docker run --help'.

The command failed.`

This is the same error that was occurring with the TDARR docker before the template was reverted. Deleting the invalid port entry and replacing it with 8267:8267 TCP has corrected the problem.

**To Reproduce**
Restart tdarr_node docker on unraid.

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux] unraid 6.9.2
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by HaveAGitGat** [comment]
Both templates were reverted by Jordan 2 days ago so this would be an issue with your local unraid template which you need to update:
https://github.com/selfhosters/unRAID-CA-templates/pull/320/files
