### ISSUE TITLE
Not all files are added to the DB successfully

### ISSUE THREAD

**Issue by jackald** [HaveAGitGat/Tdarr#570]
**Describe the bug**
Not all files are being added to the database. My Films library is pointing to the folder /media/Films which has 28 films in it. When I clear the library then do a fresh scan only 20 films are added to the transcode queue (I set both CPU and GPU transcode workers to 0). I have set the log to be Verbose and I can see that the scan finds all 28 films and sends them for extraction. I can then do a Find new scan and the 8 missing films will be found. The logs say added to the DB for all 8. However I can then search for one of the 8 files in Tddar, and nothing is found. I can keep scanning for new and the 8 films will be noted as being added to the DB.

**To Reproduce**
I am running this on Docker with the Host OS being linux x86_64 Debian GNU/Linux 10 (buster). I am using the docker image haveagitgat/tdarr:latest which has a build date of 2022-02-20 22:49:42. To reproduce I just clear the library then do a fresh scan. I am using mergerfs to pool my media drives but do not see how that could cause only some of the files not to be added. The other docker bind mounts are on an ext4 SSD.
The mergerfs options are ``defaults,allow_other,cache.files=full,dropcacheonclose=true,use_ino``

**Expected behavior**
I expect all 28 films to be added to the transcode queue and be in the DB.

**Screenshots**
Screenshot of the transcode queue
![image](https://user-images.githubusercontent.com/77757817/155841615-7759413e-32f2-4e28-9152-d6d7e777d7f0.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config - Copy.json.txt](https://github.com/HaveAGitGat/Tdarr/files/8146473/Tdarr_Node_Config.-.Copy.json.txt)
[Tdarr_Server_Config - Copy.json.txt](https://github.com/HaveAGitGat/Tdarr/files/8146474/Tdarr_Server_Config.-.Copy.json.txt)
Had to change the extension to txt to upload.

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[2022.02.26.Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/8146476/2022.02.26.Tdarr_Server_Log.txt)

- Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom] 
 No worker error as no transcode or health check is done.

 - OS: Linux x86_64 Debian GNU/Linux 10 (buster)
 - Browser Firefox
 - Version 2.00.14

**Additional context**

**Comment by HaveAGitGat** [comment]
Do you still get the error if you stop Tdarr, delete `server\Tdarr\DB2\FileJSONDB` , start Tdarr and run a fresh scan?
