### ISSUE TITLE
Reduce Docker image size

### ISSUE THREAD

**Issue by rnsc** [HaveAGitGat/Tdarr#572]
Hello,

I'd like to reduce the Docker image size of Tdarr.
Currently it's around 1.7GB, which seems a bit high.
Now I've noticed that in the Dockerfile, a lot of "dev" libraries and build binaries are added to compile some stuff.
Maybe we could optimise this by avoiding compiling things?
Or remove all the dev libraries + adding an `apt-get auto remove -y` afterwards?

What do you think?

Kind regards,

**Comment by HaveAGitGat** [comment]
Using `apt-get autoremove -y` didn't make much difference (few MB or so). So yeah it would be a case of removing deps but not sure which ones will break anything. Will be a trial and error process.

**Comment by rnsc** [comment]
@HaveAGitGat AFAIK, all *-dev packages are only useful at compilation time, they are unused once the binary is built.
So then maybe just removing all the *-dev packages and obvious build packages like gcc, etc, without doing an auto-remove?
Btw, aren't the flags used to build HandBrake in the Dockerfile already enabled by default in the distributed package?

**Comment by HaveAGitGat** [comment]
The distributed package was missing a bunch of stuff such as qsv last time I checked.

**Comment by HaveAGitGat** [comment]
FYI I tried removing all the dev packages a couple of weeks ago but only seemed to save 50-100MB or so.

**Comment by hollanbm** [comment]
@HaveAGitGat The best solution would be use of dependency layers. Make another image that contains all of the dependencies that shouldn't change much. Then use that as the base for the final tdarr image

The final image size wouldn't change, but subsequent updates (and image builds) would speed up significantly.

**Comment by iafydsttta** [comment]
[docker slim](https://github.com/docker-slim/docker-slim) might be of help to reduce image size in the future.

**Comment by HaveAGitGat** [comment]
> @HaveAGitGat The best solution would be use of dependency layers. Make another image that contains all of the dependencies that shouldn't change much. Then use that as the base for the final tdarr image
> 
> The final image size wouldn't change, but subsequent updates (and image builds) would speed up significantly.

Docker does that already I believe. If you pull a Tdarr update then it skips down a few layers to the layer where the Tdarr binary is added to image and downloads from there without having to redownload the dependency layers.

So it skips to this layer:
https://github.com/HaveAGitGat/Tdarr/blob/fb02b5ca874aa720f6dcb6cae519a3c78bd6dd47/docker/Dockerfile#L124


@iafydsttta interesting I'll take a look at that, thanks.

**Comment by HaveAGitGat** [comment]
Docker image physical size is 87% smaller in 2.00.22 just released,  (now 204MB)

**Comment by rnsc** [comment]
> Docker image physical size is 87% smaller in 2.00.22 just released,  (now 226MB)

Thank you @HaveAGitGat that's awesome !
