### ISSUE TITLE
Hi, please see this issue which is a more efficient solution:

### ISSUE THREAD

**Issue by xFaultx** [HaveAGitGat/Tdarr#573]
Hi, please see this issue which is a more efficient solution: 
https://github.com/HaveAGitGat/Tdarr/issues/568

_Originally posted by @HaveAGitGat in https://github.com/HaveAGitGat/Tdarr/issues/571#issuecomment-1056186244_

This isn't really a fix for the issue however. What you're describing would only really work when writing with media that has either the same/similar source quality, and/or similar end file size. I have some things that the source bitrate is lower because I don't need it to be higher quality. An example would be maybe some holiday movie that is something we throw on in the background once a year. But in the same library I have movies that I want to have very little quality loss, and sold naintIn that very high bitrate. The goal is to have lower quality movies stay low quality, and higher quality stay high.

**Comment by HaveAGitGat** [comment]
Hi, you don't need to open a new issue. You can just reply to old one.

**Comment by xFaultx** [comment]
> Hi, you don't need to open a new issue. You can just reply to old one.

Sorry on mobile I must have hit the new issue button instead of comment

**Comment by HaveAGitGat** [comment]
> > Hi, you don't need to open a new issue. You can just reply to old one.
> 
> Sorry on mobile I must have hit the new issue button instead of comment

No worries 👍
