### ISSUE TITLE
Keep getting some files in Error/Cancelled and not sure why

### ISSUE THREAD

**Issue by NotExpectedYet** [HaveAGitGat/Tdarr#574]
**Describe the bug**
Some of my files seem to be dropping into the "Error/Cancelled" section and I am not sure why. I've just picked up using Tdarr again after a few years so it's probably me not understanding the settings somewhere. Do love where you've taken this though! Think I last used it in 2019. 

**To Reproduce**
Not really sure. 

**Expected behavior**
To transcode the files  

**Please provide the following information:**
Have attached my config and logs for you. Let me know if anything else will help!

-Worker error:
[configs and logs.zip](https://github.com/HaveAGitGat/Tdarr/files/8175502/configs.and.logs.zip)

```
The new transcode arguments were the exact same as the last ones meaning

the file/worker would most likely be stuck in an infinite transcode loop if not stopped.

Last arguments: <io> -c copy -map 0:0 -map 0:2 -map 0:1 in .mp4

New arguments: <io> -c copy -map 0:0 -map 0:2 -map 0:1 in .mp4

Plugin Community Tdarr_Plugin_00td_action_re_order_all_streams_v2 

```

I also just noticed one in embed subs to SRT too, gather it's related as there's no settings on that one. 

```
The new transcode arguments were the exact same as the last ones meaning

the file/worker would most likely be stuck in an infinite transcode loop if not stopped.

Last arguments: , -map 0 -map -0:2 -c copy in .mkv

New arguments: , -map 0 -map -0:2 -c copy in .mkv

Plugin Community Tdarr_Plugin_078d_Output_embedded_subs_to_SRT_and_remove 

```

 - OS: UnRaid/Linux/Docker
 - Browser: Firefox
 - Version: 2.00.14

**Comment by HaveAGitGat** [comment]
Hi, pleased you like it.  You'd need to check the last completed cache file to see if FFmpeg has done what was requested of it (sometimes it has bugs with certain files/properties).

For example, in this command ` -map 0 -map -0:2 -c copy` FFmpeg is trying to remove the 3rd stream (index 2) as it seems to be a sub stream. So you'd need to check the last completed file to see if that stream has been removed or not, as FFmpeg is trying to remove it again.

**Comment by NotExpectedYet** [comment]
> Hi, pleased you like it. You'd need to check the last completed cache file to see if FFmpeg has done what was requested of it (sometimes it has bugs with certain files/properties).
> 
> For example, in this command ` -map 0 -map -0:2 -c copy` FFmpeg is trying to remove the 3rd stream (index 2) as it seems to be a sub stream. So you'd need to check the last completed file to see if that stream has been removed or not, as FFmpeg is trying to remove it again.

Oh, so just to make sure I'm understanding you correctly. ffmpeg is kind of holding on to the last file properties, and attempting to remove those on the file after it. 

How would I find the last cached file? I'm not sure what your relating to there, like the queue has progressed quite a bit. Do you mean awaiting for the next error and seeing the file in the queue before it? 

I checked some recent completed files and there doesn't seem to be a problem with it. Or am I looking in the wrong place? 

```
Pre-processing - Re-order all streams V2

Streams are in the correct order!

Pre-processing - Tdarr_Plugin_lmg1_Reorder_Streams

File has video in first stream

File meets conditions!

Pre-processing - Migz-Remove image formats from file

☑File doesn't contain any unwanted image format streams.

Pre-processing - Migz-Clean title metadata

☑File has no title metadata

Pre-processing - Output embedded subs to SRT and remove

No subs in file to extract!

Pre-processing - Migz-Clean subtitle streams

☑File doesn't contain subtitle tracks which are unwanted or that require tagging.

Pre-processing - Migz-Clean audio streams

☒Cancelling plugin otherwise all audio tracks would be removed.

Pre-processing - Migz-Convert audio streams

☑File contains all required audio formats.

Pre-processing - Migz-Transcode Using Nvidia GPU & FFMPEG

File is already hevc or vp9 & in mkv.

undefined
```

![image](https://user-images.githubusercontent.com/61137988/156690495-4b6cfa91-32d7-413f-a944-086ee1f4d8e8.png)

**Comment by NotExpectedYet** [comment]
I think it's something specific to those files maybe. Looking at the health checks for the music videos that passed there's the same error but they should be failing the health check. As they have the same error. Wonder if it's something with youtube-dl... and amvd's formatting, because some show's I'd ripped myself haven't failed.

**Comment by HaveAGitGat** [comment]
Please try 2.00.16 and check the new job report system. Reason will most likely be in there. Reopen if needed, thanks.

**Comment by NotExpectedYet** [comment]
> Please try 2.00.16 and check the new job report system. Reason will most likely be in there. Reopen if needed, thanks.

Brilliant thanks! Just waiting on some RAM to setup a remote transcode box and will take a look :)
