### ISSUE TITLE
Feature Request: Scan Files API - Sub Directory Path versus the Library's Entire Path

### ISSUE THREAD

**Issue by buroa** [HaveAGitGat/Tdarr#577]
**Is your feature request related to a problem? Please describe.**
You can send API calls to /api/v2/scan-files, but you have to specify the entire library otherwise Tdarr looses history and thinks that is the new library path.

**Describe the solution you'd like**
I want Tdarr to only scan a specified folder within a library. My architecture is all API based and I know what changed. Let me tell Tdarr that.

**Describe alternatives you've considered**
None. This is a feature Tdarr would have to implement.

**Additional context**
Please and thank you :)

**Comment by HaveAGitGat** [comment]
That endpoint is primarily for scanning library folders, not for scanning specific library subfolders like you're trying to do.

You'd need to use the array functionality and specify which files you'd like to scan with the `scanFolderWatcher` mode.

```
  {
  "data": {
    "scanConfig": {
      "dbID": "KX7zfikAc",
        "arrayOrPath": [
          "/data/shows/file1.mp4",
          "/data/shows/file2.mp4",
          "/data/shows/file3.mp4",
        ],
          "mode": "scanFolderWatcher"
    }
  }
}
```
