### ISSUE TITLE
Feature Request: Sort queue by bitrate

### ISSUE THREAD

**Issue by vongrippen** [HaveAGitGat/Tdarr#578]
**Is your feature request related to a problem? Please describe.**
Not a problem with the software.

**Describe the solution you'd like**
I have a large amount of media in my libraries, some of which is incredibly high bitrate due to poor initial encoding. I'd like to sort my queue by the bitrate to be able to process these files first and be able to get the bitrate down to something more reasonable based on my transcode settings.

**Describe alternatives you've considered**
I've been manually bumping the files using the search in Tdarr, but with nearly 50,000 files (and growing) in my libraries this is just not a very scalable solution for me.

**Additional context**
No additional context.

**Comment by supersnellehenk** [comment]
High bitrate files are usually quite large, couldn't you just sort the queue based on the file size?

**Comment by vongrippen** [comment]
A lot of them are significantly shorter videos in lower resolution (like
30min 480p video, but stupidly 15-25Mbps bitrate), while being high
bitrate, so they end up being a lot smaller files than say 4K 2+ hour
videos. I already sort my queue by Largest as it is, but I still have to go
review the search regularly and bump the high bitrate videos.
------------------------------------------------------
Mike Cochran
***@***.***

**Comment by HaveAGitGat** [comment]
Added for .16, will only apply to newly scanned files

**Comment by HaveAGitGat** [comment]
.16 released.
