### ISSUE TITLE
New items in staging are added to the top of the staging queue

### ISSUE THREAD

**Issue by DavidReinberger** [HaveAGitGat/Tdarr#579]
**Describe the bug**
Whenever file is processed it is added to the top of staging queue instead of the bottom. Which causes incorrect order of transcodes.

**To Reproduce**

1. Run a Tdarr instance
2. Sort a library queue by `Oldest (Created)`
3. Files are added to staging
4. Files are always pushed to the top below the first `processing` file

**Expected behavior**
The staging queue is a FIFO queue and files are processed in order in which they've been added.

**Screenshots**

<img width="530" alt="Snímek obrazovky 2022-03-11 v 16 55 48" src="https://user-images.githubusercontent.com/3901054/157902894-c10ad038-1fee-48a1-86c9-87a7a1f0aa3b.png">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by supersnellehenk** [comment]
The staging queue just shows files that are currently being worked on. Does the way that's sorted really matter?

**Comment by DavidReinberger** [comment]
It does, files at the top are being processed.

**Comment by HaveAGitGat** [comment]
Fixed for .16
