### ISSUE TITLE
Update documentation for Linux shell command

### ISSUE THREAD

**Issue by briankelley** [HaveAGitGat/Tdarr#580]
The documentation here:
https://docs.tdarr.io/docs/installation/windows-linux-macos

states simply: "Run /Tdarr_Updater (if on Linux/macOS you may need to give the file execution permissions by running chmod +x Tdarr_Updater)"

Even if the file is executable, and while logged in as root in Ubuntu Server 20.04, the following would not permit the Tdarr_Updater binary to run.
`. Tdarr_Updater`

Returns:
`bash: .: Tdarr_Updater: cannot execute binary file`

The updater still needs to be run with sudo even though you're running it as root. This won't be obvious to those who follow the instructions closely (because they need to). The following command launches the updater without issue.

`sudo Tdarr_Updater`

**Comment by HaveAGitGat** [comment]
Hi, 

To execute a binary on Linux you use `./path`.

So executing `./Tdarr_Updater` works fine, no sudo required.
