### ISSUE TITLE
libtesseract still missing from Linux x64 build

### ISSUE THREAD

**Issue by briankelley** [HaveAGitGat/Tdarr#581]
**Describe the bug**
Following the instruction provided here:
https://docs.tdarr.io/docs/installation/windows-linux-macos

The instruction directs you to run both the Tdarr_Server and Tdarr_Node

When running the Tdarr_Server, it still returns:
`[ERROR] Tdarr_Server - Scanner test 4: CCExtractor not working:"/opt/Tdarr/Tdarr_Server/assets/app/ccextractor/ccextractor: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory\n"`

(My installation is being run from /opt/Tdarr)

This issue appears to have been [fixed and merged here](#545), but it still exists in the x64 Linux build.

By manually running the apt-get command on line 30 from that commit, I was able to correct the error and launch the Tdarr_Server without issue.
`apt-get update && apt-get install -y curl unzip mkvtoolnix libtesseract-dev`

 - OS: 
```
/opt/Tdarr #> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by HaveAGitGat** [comment]
`libtesseract-dev` was added to the docker container and is working fine on X64.

If you're using the native Tdarr package then you'd need to install those dependencies separately as CCExtractor is not a static binary.

**Comment by briankelley** [comment]
Fair enough. Wasn't sure if this was helpful or not, but didn't want to assume anything. Is there official documentation for the prerequisites?

**Comment by HaveAGitGat** [comment]
I've added a line to the documentation to specify that libtesseract-dev needs to be installed on linux x64 if wanting to use CCExtractor 👍, thanks.
