### ISSUE TITLE
2.0.15 linux docker server-windows node wont connect

### ISSUE THREAD

**Issue by bsaurusrex** [HaveAGitGat/Tdarr#584]
**Describe the bug**
After upgrading to 2.0.15 docker linux container, my windows 2.0.15 node cant connect.

**To Reproduce**
Upgrade to 2.0.15 on linux server and windows node.
-server
[2022-03-19T12:52:08.453] [ERROR] Tdarr_Server - Node: 192.168.1.194:8267 - nodeID 'Desktop' could not be contacted by the server.
       Please make sure the IP and Port are correct else it may be a firewall issue.

**NODE Version:**
version: 2.00.15
win32_x64_docker_false

rollback to 2.0.14 connects perfectly.

**Comment by HaveAGitGat** [comment]
Hi, firstly, try 2.00.16 (latest version). Secondly, please post your configs.

**Comment by bsaurusrex** [comment]
Seems to be an issue with truecharts port exposure.  Migrated to docker directly and its working now.

Nice quality of life improvements on 1.0.16.  Thanks!

**Comment by HaveAGitGat** [comment]
Great, thanks for the update 🙂.
