### ISSUE TITLE
Better handling of rename failures

### ISSUE THREAD

**Issue by exodus454** [HaveAGitGat/Tdarr#585]
**Is your feature request related to a problem? 

Yes, when permissions are not perfect on all the folders, Tdarr continues to process without saying anything anywhere. I haven't seen anything in the server or node logs even with debugging/verbose logging enabled. This results in the jobs succeeding, the library being filled with TdarrrCacheFIle, and the library seems to continue processing the unmodified files. 

Currently I'm just removing all the cache files manually and it ends up losing a LOT of cpu time and power reproceesing everything. Just today I ended up freeing 3TB of tdarrcachefiles from the library.

**Describe the solution you'd like**
Better notifications of rename failed at the very least. 

**Describe alternatives you've considered**
If possible it'd be great to have Tdarr keep track of the errored jobs and have it fix everything once the permissions have been corrected. 

**Additional context**
I'm running Tdarr dev (2.0.15) on docker/k3s, library (40TB) is on NFS storage

**Comment by HaveAGitGat** [comment]
With Tdarr Flows it will throw an error during the rename so this should be handled correctly in that. Worst case you need to restart the flow:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/33026ac1-4ae7-4910-962d-68703b35e96a)

**Comment by HaveAGitGat** [comment]
Beta released the other day, feel free to reopen if you have any issues.
