### ISSUE TITLE
Feature Request: Sort Queue by resolution

### ISSUE THREAD

**Issue by hollanbm** [HaveAGitGat/Tdarr#586]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the option to sort the queue by resolution. Sorting by file size, sort of works. But it isn't guaranteed, I do have some small files, which are high resolution. For example, 1080p Anime specials, that are ~2-3mins long.

**Describe the solution you'd like**
Ability to sort queue by resolution

**Describe alternatives you've considered**
Sorting by file size is an okay workaround, but not guaranteed.

**Comment by HaveAGitGat** [comment]
Sure will add this for .17.

**Comment by HaveAGitGat** [comment]
Added: 
![image](https://user-images.githubusercontent.com/43864057/162134093-64f2022e-cc57-49a1-bbf8-7ab744ed55d2.png)
