### ISSUE TITLE
Tdarr making video file largers H265

### ISSUE THREAD

**Issue by uefcommand** [HaveAGitGat/Tdarr#587]
**Describe the bug**
Greetings I have H265 via an Nvidia P2200 Episodes of Dr Who seem to be outputting larger. No other files are doing it. I have validated settings via FFMPEG and as well as these transcodes do not run on my P2200 no processes are running on the NVIDIA SMI when others will. The log has a file size that starts at 2.135 GB and finishes at 2.147 GB. No worker error it says success. 

**Additional context**
[6dWFyc0JM-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8385265/6dWFyc0JM-log.txt)

**Comment by HaveAGitGat** [comment]
Hi, the job report you posted is from a health check on the file:

`2022-03-30T19:40:13.430Z 6dWFyc0JM:Node[Node 1]:Worker[sPcgNUfXQ]:Handbrake healthcheck task, no need to scan for extra file details`

Do you still have the transcode job report? You can search for the file on the search tab, hit the job report button and then select the transcode job report on the left if it's still available.

**Comment by uefcommand** [comment]
Here is the transcode log. Thank you. Sorry I have been out of town. 
[115mlZ9js27-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8468068/115mlZ9js27-log.txt)

**Comment by HaveAGitGat** [comment]
Hi, thanks for this. There's nothing unusual going on here. You've run the following plugins on the file:

Tdarr_Plugin_00td_action_re_order_all_streams_v2
Tdarr_Plugin_MC93_MigzImageRemoval

`File size  2186MB -> 2198MB (12MB increase).`

It's completely normal for the file size to fluctuate a bit when remuxing files as how the data is arranged in the file is changed so the sizes won't be exactly the same.
