### ISSUE TITLE
AMD GPU Thorough Health Check Support

### ISSUE THREAD

**Issue by Enigma0** [HaveAGitGat/Tdarr#589]
It would be great if Tdarr supported AMD GPU thorough health checks.

**Comment by HaveAGitGat** [comment]
This should work if you set the node as a `vaapi` node on the node options panel. Updated for 2.00.21 so it also works if selecting `amf`. The command would be the same:

`-stats -v error -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128`
