### ISSUE TITLE
FFProbe not show AAC Bit_Rate

### ISSUE THREAD

**Issue by jasimancas** [HaveAGitGat/Tdarr#592]
**Describe the bug**
FFPROBE does not show AAC audio bit_rate

**Expected behavior**
It should display the bit_rate tag like AC3 audio for example.

**Screenshots**
![image](https://user-images.githubusercontent.com/15717847/163174497-c9dceafb-b644-4235-8696-7ab2c80bfd9e.png)

 - OS: Docker
 - Browser: EDGE
 - Version 2.00.16

**Comment by supersnellehenk** [comment]
This has nothing to do with Tdarr itself, but with ffprobe. Tdarr simply runs `ffprobe -print_format json -show_format -show_streams` on the file, which you see there. I tried it on a file with DTS, but the `bit_rate` field isn't there either.

**Comment by HaveAGitGat** [comment]
Yeah stream bitrate is a bit of a pain as it's not consistently collected by FFprobe. It's not to do with the codec but more so with how the stream was encoded. Does mediainfo show it? 

![image](https://user-images.githubusercontent.com/43864057/163555233-ea8752cf-ca1c-4f0f-8431-a41a09fab63e.png)

**Comment by HaveAGitGat** [comment]
Closing as to do with FFprobe but feel free to discuss any findings.
