### ISSUE TITLE
Excessively Long Titles Cause Health Check to Fail

### ISSUE THREAD

**Issue by rcm024** [HaveAGitGat/Tdarr#593]
**Describe the bug**
Too long of a file name leads to a health check failure. Log reports "No Title Found. HandBrake has exited."

**To Reproduce**
Try to heath check a file with a really long name and/or lots of spaces in the name.

**Expected behavior**
Normal health check

**Screenshots**
See attached logs

**Please provide the following information:**
- Config files  -will provide if deemed necessary

- Log files  -Attached

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Tdarr on Linux (Unraid Docker); Tdarr Node on Windows 10

**Additional context**
Not sure if the issue is the actual character count or the number of spaces (spaces may be causing inflated character counts?) but either way, if you have a file with too long of a name, the heath check will fail. 2 example logs attached. I have manually shortened the file names of the 20 or so files that had this issue and they all pass health check now that the file name has been shortened

[Vjrk32Cnlfw-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8490484/Vjrk32Cnlfw-log.txt)
[OzeQaZlnYTM-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8490488/OzeQaZlnYTM-log.txt)

**Comment by supersnellehenk** [comment]
This is due to windows having a 256 character limit, your filenames are over that. Generally for anime you'd rather not have the real title, since some animes have entire descriptions as their title.
