### ISSUE TITLE
Improvement - Do not show empty rows when there are less items than the current "rows" setting

### ISSUE THREAD

**Issue by crafty35a** [HaveAGitGat/Tdarr#595]
**Is your feature request related to a problem? Please describe.**
Currently if I set the Status or Staging Section to a large number of rows (e.g. 100 rows) the UI will always show the full number of rows selected, even if there are only a few items in the list. This makes for tons of wasted space in the UI, especially since you need to scroll past the staging section to see the Status section.

**Describe the solution you'd like**
Only show as many rows as are required to display the number of items in the list, regardless of the rows setting.

**Current UI:**
![image](https://user-images.githubusercontent.com/1082003/163828812-f4ef6787-c5a0-4f3a-8e2a-9d6e4e008225.png)

**Proposed change:**
![image](https://user-images.githubusercontent.com/1082003/163829455-6c6b4566-e148-4532-987a-8fd0f5bd63bb.png)

**Comment by HaveAGitGat** [comment]
I tried that but found it inconvenient as it makes the page jump around a lot as the number of items in those sections frequently change. Better to have a fixed size I think.

If you don’t want wasted space then you can reduce the number of items per page with the setting at the bottom of each table.

**Comment by HaveAGitGat** [comment]
Update to .17 and there are ‘20’ and ‘50’ page size options which you maybe find more useful.

**Comment by crafty35a** [comment]
Maybe as a compromise there could be an "All" option that shows all items, with only as many rows as needed? And the existing options can continue to function as-is. Just a thought - thanks!

**Comment by HaveAGitGat** [comment]
I've added this for the next version. So if you select a page size of 1, it will give this notification: 
![image](https://user-images.githubusercontent.com/43864057/168971348-75cfb328-b429-4fdb-aca0-3595dd50c297.png)

**Comment by HaveAGitGat** [comment]
FYI I've removed this due to this issue:
https://github.com/HaveAGitGat/Tdarr/issues/633

Don't want people with thousands of items to freeze their browser.
