### ISSUE TITLE
Stats page are not calculating

### ISSUE THREAD

**Issue by jaycedk** [HaveAGitGat/Tdarr#596]
**Describe the bug**
Stats page are not calculating.
Number of transcodes is always 1
Space saved is some odd low number.
Number of health checks is always 1

All stats
![billede](https://user-images.githubusercontent.com/17232146/163922381-f1794956-cb82-427c-a2f1-bd2269e0a88f.png)

1 of my libraries, where Space saved looks ok. It is that same for all libraries.
![billede](https://user-images.githubusercontent.com/17232146/163922438-fc2efdce-106b-40b5-bdb3-c4576b07ed73.png)

**To Reproduce**
Not sure, its was calculating with v. 2.00.16
But something changed with v. 2.00.17

**Expected behavior**
Stats being calculated

 - OS: Windows 10
 - Browser Firefox, Chrome and Edge.
 - Version 2.00.17

**Comment by MichalRybecky** [comment]
Exactly the same issue here, v.2.00.17 on Debian server and node running GPU transcoding only, no experience with previous versions. Everything else works as expected, except the stats in the stats page are incorrect.

**Comment by HaveAGitGat** [comment]
Hi sorry about this, there's a small bug in 2.00.17 affecting the following 3 stats:

```
- Number of transcodes
- Space saved
- Number of health checks
```

About 10-20 people used the dev container/packages over the last few weeks and unfortunately was not spotted by myself.

I've released 2.00.18 which fixes the bug, you'll see this notice on startup:

![image](https://user-images.githubusercontent.com/43864057/163951267-ac4ca1aa-f909-48e5-b17c-8736da7a0d98.png)

It contains this link to restore the stats: http://localhost:3000/docs/restoring-statistics

The backup features has finally come in handy 👍 .

Apologies for the inconvenience.

**Comment by HaveAGitGat** [comment]
Woops wrong link, should be this: https://docs.tdarr.io/docs/restoring-statistics

**Comment by jaycedk** [comment]
Will try it and report back :)

**Comment by HaveAGitGat** [comment]
Thanks 💯

**Comment by MichalRybecky** [comment]
Just updated to v.2.00.18, stats are updating perfectly! Thank you

**Comment by HaveAGitGat** [comment]
Awesome, thanks for the update. Was all (my 2) hands on deck this morning when I saw that issue. Stressful start to the day 🙂.

**Comment by MichalRybecky** [comment]
Haha no worries mate, pretty amazed on how fast you were able to solve this and even write docs for it!

**Comment by jaycedk** [comment]
Can confirm its fixed :)
And now updating.

**Comment by jaycedk** [comment]
Thank you for the fast fix :)
Closing this again.

**Comment by HaveAGitGat** [comment]
Sorry had to go to work but glad it's fine now, ty for the help.

**Comment by Gumbyohson** [comment]
I'm actually having an issue with the stats page where the pie charts don't appear at all and all I get in that section is "Click on pie segments to load respective files". The rest of stats appears okay like "Worker Verdict History" etc. Is this a related issue or a new one?
![2022-04-20 09_33_11-Window](https://user-images.githubusercontent.com/1866263/164117907-9daec82c-ee4b-4e58-9502-19ce7e33acb7.png)

**Comment by HaveAGitGat** [comment]
@Gumbyohson different thing. If you have a large number of files then the stats are generated less regularly, should after a few minutes if workers are active.

**Comment by HaveAGitGat** [comment]
@Gumbyohson I've made a very tiny change to 2.00.18 so that the stats generate at the same frequency as before when having  over 10000 files, so re-pull .18/latest if you don't want to wait around for the stats to show up.

**Comment by HaveAGitGat** [comment]
@Gumbyohson some people on discord had the same issue as you. Verified a fix with them which has been patched onto 2.00.18. So redownload/pull 2.00.18 and the pie charts should show up again. Let me know if you have any issues, thanks.

**Comment by Gumbyohson** [comment]
@HaveAGitGat, thanks so much. I've waited a while but the pie chart isn't appearing still which is weird. I also have now rerun the server updater (closed almost immediately so not sure if I'm doing it right or if it's finding the changes you uploaded) and also waited a while but the pie chart isn't appearing still which is weird... I'm at 21888 items in the DB. I'll let you know how this goes after some time.

**Comment by HaveAGitGat** [comment]
@Gumbyohson yeah you need to delete the Tdarrr_Server folder and rerun the updater else it won't download the patched .18 package.

**Comment by jaycedk** [comment]
Or you can just edit Tdarr_Updater_Config.json
{
  "platform_arch": "default",
  "modules": {
    "Tdarr_Node": {
      "enabled": true,
      "requiredVersion": "2.00.18",
      "currentVersion": "2.00.17"
    },
    "Tdarr_Server": {
      "enabled": true,
      "requiredVersion": "2.00.18",
      "currentVersion": "2.00.17"
    }
  }
}

And then run the update tool.
That should pull the latest 2.00.18
After the server and node update.
Make sure to Force Refresh the WebUI in your browser.

**Comment by Gumbyohson** [comment]
I deleted the server folder and it's all appeared again. Thanks so much guys
