### ISSUE TITLE
Mixed use of user abc and Tdarr breaking Docker HW transcoding

### ISSUE THREAD

**Issue by cristian-rivera** [HaveAGitGat/Tdarr#598]
I've been trying to get this image working with GPU passthrough and I haven't had much luck. I think I've narrowed it down though, here are my findings.

Firstly, I think that the command [here](https://docs.tdarr.io/docs/installation/docker/hardware-transcoding#ffmpeg-vaapi) is a bit misleading. The command should succeed almost always (ignoring the setting of `privileged: true`), but only because it will be executed as **root** in that context, not **abc** which is what s6 and **Tdarr_Node/Tdarr_Serve** run as.

When opening a shell into the unmodified image, `ps aux` returns the following:
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0    204     4 ?        Ss   17:43   0:00 s6-svscan -t0
root          35  0.0  0.0    204     4 ?        S    17:43   0:00 s6-supervise
root         391  0.0  0.0    204     4 ?        S    17:43   0:00 s6-supervise
root         392  0.0  0.0    204     4 ?        S    17:43   0:00 s6-supervise
abc          395  0.4  0.3 997728 126508 ?       Ssl  17:43   0:04 ./Tdarr_Node
abc          396  2.1  1.6 1734892 533504 ?      Ssl  17:43   0:19 ./Tdarr_Serve
```
Note `./Tdarr_Node` and `./Tdarr_Serve` running as **abc**.

I dug around and noticed that a new **Tdarr** user is created in the [Dockerfile](https://github.com/HaveAGitGat/Tdarr/blob/master/docker/Dockerfile#L28) and that same user is also configured to access the related `/dev/dri` groups by this [file](https://github.com/HaveAGitGat/Tdarr/blob/master/docker/root/etc/cont-init.d/02-hw-transcoding).

I think the issue here is that **Tdarr_Node/Tdarr_Serve** are running as user **abc**, but [02-hw-transcoding](https://github.com/HaveAGitGat/Tdarr/blob/master/docker/root/etc/cont-init.d/02-hw-transcoding) is configuring the `/dev/dri` groups for the **Tdarr** user. I've confirmed that running the [command](https://docs.tdarr.io/docs/installation/docker/hardware-transcoding#ffmpeg-vaapi) as user **Tdarr** works, but as user **abc** it doesn't.

Is there a specific reason as to why the user **Tdarr** is created as opposed to using the s6 provided **abc** user everywhere? I took a look at the way [linuxserver/plex](https://github.com/linuxserver/docker-plex) handles this and they indeed only use **abc** in their [equivalent file](https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/50-gid-video) that configures the `/dev/dri` group ids.

**Comment by HaveAGitGat** [comment]
Hi,

` The command should succeed almost always`

Not if the device/driver settings are incorrect which I think is the purpose the command.

I think using the Tdarr user is just a carry-over from before starting to use `lsiobase`. Changing over to the abc user would have caused permissions issues for some people (always happens when changing permissions/users), so was just an easy way to keep things running smoothly. Can perhaps be changed in future though.

**Comment by huuub** [comment]
Well I think this is still an issue. How do we fix this?

**Comment by HaveAGitGat** [comment]
There must be a bit more to this as plenty of people are using GPU passthrough without any issues so not exactly sure why it's a problem here.

Either way used ChatGPT to add some somments to those scripts:

01-setup-perms
```
#!/usr/bin/with-contenv bash

# Set the group ID and user ID for the user "Tdarr"
groupmod -o -g "${PGID}" Tdarr
usermod -o -u "${PUID}" Tdarr

# Display the user ID and group ID for the user "Tdarr"
echo "
User uid:    $(id -u Tdarr)
User gid:    $(id -g Tdarr)
-------------------------------------
"

# Change the ownership of the specified directories to the user "Tdarr"
chown -R ${PUID}:${PGID} \
    "${HOME}" \
    /temp \
    /logs

# Check if the "CHOWN_ON_STARTUP" variable is set to false. If so, skip chown.
# If not, check if it's the first run. If yes, chown /app, ffmpeg, and ffprobe.
# If not the first run, there's no need to chown.
if [ "$CHOWN_ON_STARTUP" = false ] ; then
    echo "chown: CHOWN_ON_STARTUP = false, skipping startup chown"
elif [ -f /firstRun ] ; then
    echo "chown: Not first run, no need to chown"
elif [ ! -f /firstRun ] ; then
    echo "chown: First run and CHOWN_ON_START != false, chowning /app, ffmpeg and ffprobe, this may take some time"
    chown -R ${PUID}:${PGID} /app
    chmod a+rwx -R /app/Tdarr_Node/assets/{app/fileScanner/,app/ffmpeg/}
    chmod a+rwx -R /app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
    touch /firstRun
fi
```

02-hw-transcoding
```
#!/usr/bin/with-contenv bash

# Find all relevant devices
DEVICES=$(find /dev/dri /dev/dvb /dev/vchiq /dev/vcsm /dev/vc-mem /dev/video1? -type c -print 2>/dev/null)

# If Nvidia GPU is present, print runtime info
if hash nvidia-smi 2>/dev/null; then
    echo "Runtime detected"
    echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader)"
    echo "Capabilities: ${NVIDIA_DRIVER_CAPABILITIES} Devices: ${NVIDIA_VISIBLE_DEVICES}"
fi

# Loop through devices and assign Tdarr user to relevant groups
for i in ${DEVICES}; do
    # Get the group ID and NAME (if exists) for the current device in the list
    DEVICE_GROUP_ID=$(stat -c '%g' "$i")
    DEVICE_GROUP_NAME=$(getent group "${DEVICE_GROUP_ID}" | awk -F: '{print $1}')

    # If group NAME doesn't exist, create it and assign it the group ID
    if [[ -z "${DEVICE_GROUP_NAME}" ]]; then
        DEVICE_GROUP_NAME="video${RANDOM}"
        groupadd -g "${DEVICE_GROUP_ID}" "${DEVICE_GROUP_NAME}"
    fi

    # Add Tdarr user to group if not already present
    getent group "${DEVICE_GROUP_NAME}" | grep -q Tdarr || usermod -a -G "${DEVICE_GROUP_NAME}" Tdarr
done
```


So should just be able to replace user `Tdarr` with `abc`.


`What is the default user for s6  overlay container?`

ChatGPT: `The default user for s6 overlay container is abc. This is a non-root user account created by the s6-overlay image to run the services inside the container with reduced privileges. It has a user ID of 911 and a group ID of 911. This user is commonly used in images based on the alpine Linux distribution, which is known for its small image size and focus on security.`

`How do you set and use the user abc uid and gid in overlay container?`

ChatGPT:
```
To set and use the abc user's UID and GID in an overlay container managed by s6-overlay, you can pass environment variables to the container using the -e flag when running the docker run command.

For example:
docker run -d \
  -e PUID=1001 \
  -e PGID=1001 \
  my-overlay-container
```

Asking it to use user abc for both scripts:

```
#!/usr/bin/with-contenv bash

# Set the group ID and user ID for the user "abc"
groupmod -o -g "${PGID}" abc
usermod -o -u "${PUID}" abc

# Display the user ID and group ID for the user "abc"
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

# Change the ownership of the specified directories to the user "abc"
chown -R ${PUID}:${PGID} \
    "${HOME}" \
    /temp \
    /logs

# Check if the "CHOWN_ON_STARTUP" variable is set to false. If so, skip chown.
# If not, check if it's the first run. If yes, chown /app, ffmpeg, and ffprobe.
# If not the first run, there's no need to chown.
if [ "$CHOWN_ON_STARTUP" = false ] ; then
    echo "chown: CHOWN_ON_STARTUP = false, skipping startup chown"
elif [ -f /firstRun ] ; then
    echo "chown: Not first run, no need to chown"
elif [ ! -f /firstRun ] ; then
    echo "chown: First run and CHOWN_ON_START != false, chowning /app, ffmpeg and ffprobe, this may take some time"
    chown -R ${PUID}:${PGID} /app
    chmod a+rwx -R /app/Tdarr_Node/assets/{app/fileScanner/,app/ffmpeg/}
    chmod a+rwx -R /app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
    touch /firstRun
fi
```

```
#!/usr/bin/with-contenv bash

DEVICES=$(find /dev/dri /dev/dvb /dev/vchiq /dev/vcsm /dev/vc-mem /dev/video1? -type c -print 2>/dev/null)

if hash nvidia-smi 2>/dev/null; then
    echo "Runtime detected"
    echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader)"
    echo "Capabilities: ${NVIDIA_DRIVER_CAPABILITIES} Devices: ${NVIDIA_VISIBLE_DEVICES}"
fi

for i in ${DEVICES}; do
    # Get the group ID and NAME (if exists) for the current device in the list
    DEVICE_GROUP_ID=$(stat -c '%g' "$i")
    DEVICE_GROUP_NAME=$(getent group "${DEVICE_GROUP_ID}" | awk -F: '{print $1}')

    # If group NAME doesn't exist, create it and assign it the group ID
    if [[ -z "${DEVICE_GROUP_NAME}" ]]; then
        DEVICE_GROUP_NAME="video${RANDOM}"
        groupadd -g "${DEVICE_GROUP_ID}" "${DEVICE_GROUP_NAME}"
    fi

    getent group "${DEVICE_GROUP_NAME}" | grep -q abc || usermod -a -G "${DEVICE_GROUP_NAME}" abc
done

```

So by running the second script in your container it should start working. Running the first script won't really make a difference as the user `Tdarr` is not really relevant as chown is done using `${PUID}:${PGID}`.

Will give this a go next week.

**Comment by HaveAGitGat** [comment]
Added a gist so you can easily run it in the container:https://gist.github.com/HaveAGitGat/657338756e219cbc318acfee692d83a5

So would run `docker ps` to get the container id.

Then `docker exec -it <id> bash`.

Then this to run the script:
`wget -qO- https://gist.github.com/HaveAGitGat/657338756e219cbc318acfee692d83a5/raw/script.sh | bash`

**Comment by HaveAGitGat** [comment]
I've updated the dev container so it only uses user abc, can try here:

`docker pull haveagitgat/tdarr_acc:dev_2.00.21_2023_04_08T17_31_10z`

**Comment by HaveAGitGat** [comment]
Closing as change was added in 2.00.21
