### ISSUE TITLE
Since updating to 2.00.18, error "Value map does not contain the input value for this property." - Config worked fine before and cannot see what the problem is in logs or otherwise testing.

### ISSUE THREAD

**Issue by KptnKMan** [HaveAGitGat/Tdarr#601]
**Describe the bug**
Since updating to 2.00.18, error "Value map does not contain the input value for this property." - Config worked fine before and cannot see what the problem is in logs or otherwise testing.

I'm running tdarr on linux and windows.

- server is linux in docker on unraid
- node 1 is windows
- node 2 is windows

Ever since updating to 2.00.18 I've been repeatedly getting the error "Value map does not contain the input value for this property." and I cannot figure out why this is happening.
The error is listed repeatedly in the worker window, to infinity.
This also makes it impossible or extremely difficult to determine any other information in the window, as the repeating error overwhelms all others.

I know it is with the upgrade because node2 (with identical config) that wasn't updated from 2.00.16 and didn't display the error, then did when updated to 2.00.18.

I'm not sure if I should find out how to downgrade everything or keep trying to figure this out.

So far I've been removing the various "pathTranslators" to see which is causing an issue, but none seem to be. All the shares are mapped directly to the docker server as docker directory paths. Like I said, this config worked 100% before the update.

I also removed the "NodeIP" and "NodePort" to see if that was the problem, same issue.

Anyone else seen this or experiencing this?

**To Reproduce**
Upgraded docker linux server to latest 2.00.18
Upgraded windows nodes to latest 2.00.18

**Expected behavior**
I expected everything to continue as normal with current config.

**Screenshots**
N/A

**Please provide the following information:**
- Config files:
Server config:
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.178.111",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO"
}
```

My Node config (Both Identical):
```
{
  "nodeID": "NODE1",
  "serverIP": "192.168.178.111",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/mnt/media",
      "node": "\\\\SERVER\\media"
    },
    {
      "server": "/mnt/media2_ftp",
      "node": "\\\\SERVER\\ftp"
    },
    {
      "server": "/temp",
      "node": "\\\\SERVER\\ssd2\\TdarrTranscode"
    },
    {
      "server": "/mnt/media3_others",
      "node": "\\\\SERVER\\hdd1\\TdarrTranscodeOthers"
    }
  ],
  "platform_arch": "win32_x64_docker_false",
  "logLevel": "DEBUG"
}
```

- Log files:
N/A, nothing remotely different listed in logs even with DEBUG enabled.

-Worker error:
The error is "Value map does not contain the input value for this property.".
The error is listed repeatedly in the worker window, to infinity.
This also makes it impossible or extremely difficult to determine any other information in the window, as the repeating error overwhelms all others.

 - OS: Linux & Windows
 - Browser Chrome
 - Version N/A

**Additional context**
N/A

**Comment by KptnKMan** [comment]
For anyone else who might encounter this issue/error, I posted this bug initially on Reddit and got a workaround from @HaveAGitGat (I'm very grateful for the response):

"It’s harmless error that Windows gives when trying to set the process cpu priority to low.

wmic has been removed by Microsoft in Windows 11 so that’s why. Should be working fine in Windows 10 or if you have wmic installed.

Else disable low cpu priority in the node options and the error should go away."

Although it's harmless, unfortunately I can't do this on one of my boxes as it would adversely affect performance without the low priority for other processes, as transcoding is not a priority on these boxes.

As it is, I'm going to keep looking and testing.
I'll leave this here in the hope that it gets fixed eventually, and hopefully it might help someone else.

**Comment by HaveAGitGat** [comment]
Thanks for the info, FYI made a small update to 2.00.18 which suppresses this error for the time being so it doesn't clog up the console. Will fix it this weekend.

**Comment by KptnKMan** [comment]
Much appreciated!
I'll definitely keep an eye out for any updates.

**Comment by HaveAGitGat** [comment]
Hi, patch has been applied to .18 so this should now be working fine. Delete the Tdarr_Node folder and redownload. Let me know how it goes.

**Comment by KptnKMan** [comment]
Thanks, I deleted the Tdarr_Node folder as advised.
I can confirm that the message has been suppressed.

I couldn't ask for more or better, thanks very much. 👍
