### ISSUE TITLE
Reducing worker count not considered for new work

### ISSUE THREAD

**Issue by skandragon** [HaveAGitGat/Tdarr#603]
**Describe the bug**

When a node is configured to run some number of jobs, say 5, and then later reduced to 3, new work will be added until the two "extra jobs" complete.

It should look at the number of running jobs, and only start new work if the current running count is < configured limit.

**To Reproduce**

1.  Set a node to run 5 jobs, and wait for it to start them.
2. Reduce the number of jobs allowed to 3.
3. If one of the first three jobs finishes first, a new job will be added to that slot, keeping the count at 5.
4. Once the slots 4 and 5 complete, the running job count does adjust.

**Expected behavior**

See above.

**Additional context**

Not OS dependent I'm sure.

Running v2.00.18

**Comment by HaveAGitGat** [comment]
This has been this way for the last 2.5 years or so, suppose it hasn't been much of an issue as people don't really startup more workers than they need.

Nonetheless I've fixed it for 2.00.19 so it will act as you expect, thanks.
