### ISSUE TITLE
Nodes Section Displays 'Health Check CPU' when using GPU for Health Check 

### ISSUE THREAD

**Issue by sxb1n9** [HaveAGitGat/Tdarr#604]
**Describe the bug**
Nodes Section Displays 'Health Check CPU' when using GPU for Health Check 

**To Reproduce**

UNRAID V6.10.x 
Nvidia P2000 on server which runs both TDAR Server and Node
Verify transcode works under P2000 so we know all of unraid and drivers and docker passthrough is working
TDAR PRO with working key 

Set Library to use GPU P2000 in my case for health check and run health check.  Observer it is called Health Check CPU 

**Expected behavior**

Should say GPU? 

**OTHER** 

If you can't reproduce I will provide logs and screenshots or if you are confused by my explanations but I doubt that.    

Thanks <fist bump>

**Comment by supersnellehenk** [comment]
Is this with quick checks or thorough checks? Quick checks can only be done by the CPU. Also, Tdarr won't magically launch a CPU health check if it doesn't have any CPU health check workers. Have you checked you only have GPU health check workers?

**Comment by sxb1n9** [comment]
thoroogh

**Comment by sxb1n9** [comment]
and turn only the GPU HC ON = 2 and CPU HC is = 0

**Comment by sxb1n9** [comment]
runs and succeds and is clearly using GPU based on speed of 800 frames a sec

**Comment by sxb1n9** [comment]
Anyway even with only GPU HC works = 2 and CPU HC workers = 0 and clearly using the GPU it says in the (blue / green) text Health Check CPU silly bug not important but wanted you to know

**Comment by HaveAGitGat** [comment]
Thanks, patch has been applied to .18
