### ISSUE TITLE
Library names are garbled

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#606]
**Describe the bug**
Library names are garbled sometimes.

**To Reproduce**
Open Tdarr web UI, not sure what other triggers cause this to happen.

**Expected behavior**
Library names are displayed properly

**Screenshots**

![image](https://user-images.githubusercontent.com/11021632/165119950-bc648614-e163-404b-bda0-d7b8998d078e.png)

![image](https://user-images.githubusercontent.com/11021632/165120901-a8116f2c-702c-40c1-b1e5-e5faa46d5882.png)

**Please provide the following information:**
- Log files  [Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8555890/Server-log.txt)

 - OS: Docker
 - Browser: Edge
 - Version: 2.00.18

**Comment by HaveAGitGat** [comment]
Those are just the library IDs which you can see in the URL when browsing your libraries. Have not seen this on my side but I'm assuming your system just takes a bit more time to load the data in. Does clicking the refresh button on the table fix the issue when it happens?

**Comment by tehniemer** [comment]
Switching tabs seems to correct the issue, I assume the refresh button would do the same. It doesn't happen all the time either.

**Comment by HaveAGitGat** [comment]
Haven't had any reports of this in recent versions so will close.
