### ISSUE TITLE
API: scan-individual-file

### ISSUE THREAD

**Issue by jasimancas** [HaveAGitGat/Tdarr#607]
**Describe the bug**
Requests the file object if it is already specified

**To Reproduce**
Attempt to scan an individual file

**Expected behavior**
Start scanning

**Screenshots**
![image](https://user-images.githubusercontent.com/15717847/165122988-e1b4698a-f265-48a4-8082-7a81a7800ae4.png)

OS: Docker
Browser: EDGE
Version 2.00.18

**Comment by supersnellehenk** [comment]
Might I suggest you update to 2.00.18? That's the latest version.

**Comment by jasimancas** [comment]
Sorry, i'm in 2.00.18, (wrong paste, edited)

**Comment by HaveAGitGat** [comment]
Based on the validation error you need to put the file object within 'data' but not within 'scanTypes'.

```
     "data": {
          "file": {
                    "file": "C:/Sample.mkv"
               },
          "scanTypes": {
               "exifToolScan": true,
               "mediaInfoScan": true,
               "closedCaptionScan": true
          }
     }
```

Updated the docs.
