### ISSUE TITLE
When filtering hold transcode queue by title, page number does not reset to 1

### ISSUE THREAD

**Issue by hollanbm** [HaveAGitGat/Tdarr#608]
**Describe the bug**
Change the current page to an arbitrary number. For example, page 50.

Type in the filename filter box, the name of a file. The total pages will shrink to the resultant search size. But the current page will not reset to 1. Making it appear like no results were found.

![image](https://user-images.githubusercontent.com/7390038/165196501-f965f123-da1e-47c9-abf0-86961d69546a.png)
![image](https://user-images.githubusercontent.com/7390038/165196543-0dee340d-fb99-48b6-b5e0-1909c67fdc82.png)
![image](https://user-images.githubusercontent.com/7390038/165196666-5410fecd-4b22-41eb-8146-9a8b8376d316.png)

**Comment by HaveAGitGat** [comment]
Thanks, fixed for .19
