### ISSUE TITLE
Tdarr in a Docker container wastes CPU with chown

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#609]
**Describe the bug**

I run tdarr client in a docker container. When I do so the container client fails to start servicing requests and instead is doing a chown -R 1000:1000 /app. Contained therein (under /app/configs/Tdarr) is apparently tdarr's database. It's huge with lots of .json files. The thing is this chown takes about 1 hour to finish, largely trying to chown .json files to have the same owner and group they already have. After this process is done a touch file of /firstRun is created. But if the user ever re-downloads a Tdarr docker image the /firstRun is triggered and the long, and mostly needless, chown process has to run.

**To Reproduce**

* Setup Tdarr node
* Run for a while building up a database
* Stop and delete docker container and image
* Download a newer image (or re-run a docker run command)
* Start docker container with old settings.

**Expected behavior**

The docker container would immediately come up

```
# cat /app/configs/Tdarr_Node_Config.json 
{
  "nodeID": "Mars",
  "nodeIP": "192.168.0.100",
  "nodePort": "8268",
  "serverIP": "192.168.0.251",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true"
}
```
```
# cat /app/configs/Tdarr_Server_Config.json 
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```
 - OS: Ubuntu 21.10
 - Browser N/A
 - Version [e.g. 2.00.00]

**Additional context**

I think this is an oversight caused by a Docker image starting fresh (e.g. no /firstRun touch file) and having a huge database of work already performed, the vast majority of which don't need chmod'ing.

**Comment by HaveAGitGat** [comment]
Sorry yeah should have posted here. And yeah you must have pulled it just before it was finished updating so `CHOWN_ON_STARTUP` should be working now e.g. with `docker pull haveagitgat/tdarr_acc:dev_2.00.19_2023_02_03T20_28_35z` and `docker pull haveagitgat/tdarr_node_acc:dev_2.00.19_2023_02_03T20_05_57z` from Friday

**Comment by adefaria** [comment]
I'm a little confused. I've been using `haveagitgat/tdarr` not `haveagitgat/tdarr_acc`. Looking over at hub.docker.com I see both of them. Which should I use? Additionally, I generally pull `haveagitgat/tdarr:latest` not a specific version. 

So I changed around my scripts to use the `tdarr_acc` and `tdarr_node_acc` names and these specific versions, made sure I removed the containers and images on both the client and the server and ran my scripts to get them up and running. The server never got the web interface going. Nothing was written into the server log. I let it run for 11 minutes and never got the web interface to come up.

I've reverted my scripts.

**Comment by HaveAGitGat** [comment]
The tdarr `_acc` repos contain the dev and acceptance (pre-release) images. Did anything unusual show in the logs when that happened? It's probably some permission issue causing a crash because the `chown` has been disabled so I guess we're back to square one there.

**Comment by adefaria** [comment]
That's the thing, nothing was written to the log file. And yet the container remained busy working on something.

**Comment by HaveAGitGat** [comment]
Can this be closed based on this: https://github.com/HaveAGitGat/Tdarr/issues/817

**Comment by adefaria** [comment]
Yes

**Comment by HaveAGitGat** [comment]
Thanks
