### ISSUE TITLE
Change Windows Tdarr_node.exe description to Tdarr_node

### ISSUE THREAD

**Issue by Sn00zEZA** [HaveAGitGat/Tdarr#611]
**Is your feature request related to a problem? Please describe.**
Currently the Windows Tdarr_Node.exe description displays "Node.js JavaScript Runtime"

**Describe the solution you'd like**
Please change the Tdarr_Node.exe description to "Tdarr_Node" or something similar.

**Comment by HaveAGitGat** [comment]
Hi, I looked into this but unfortunately there is no way to change the description at the moment without using something like resource hacker. Will change it in future if it becomes possible.
