### ISSUE TITLE
Why is TDARR detecting files begining with "._" 

### ISSUE THREAD

**Issue by MikulaMali90** [HaveAGitGat/Tdarr#612]
So TDARR detects all of the right files, but with the right ones also it detects a file starting with "._" for every movie or tv show video file. 

Here is a photo example :
![TDARR](https://user-images.githubusercontent.com/99772579/165592312-857ab293-0308-4c0c-b64e-39a00c27dd28.PNG)

**Comment by supersnellehenk** [comment]
They're hidden files created by something, but they end in `.mkv`, which is why they were picked up. Tdarr doesn't ignore hidden files, which could be a feature request.

**Comment by MikulaMali90** [comment]
> They're hidden files created by something, but they end in `.mkv`, which is why they were picked up. Tdarr doesn't ignore hidden files, which could be a feature request.

Thank you for the quick reply. Is there a way to maybe ignore files that are under 10MB?

**Comment by HaveAGitGat** [comment]
Maybe just add this to the source ignore setting:
![image](https://user-images.githubusercontent.com/43864057/165695558-0d3e6b70-cf02-486d-bd8d-43ccc2c2c0d7.png)
