### ISSUE TITLE
Errors when hardware transcoding some files

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#613]
After getting hardware transcoding working on my docker container using Nvidia it blazed past most of my movies/TV shows.

Note: In the issue [Unable to utilize NVidia GPUs in Docker container](https://github.com/HaveAGitGat/Tdarr/issues/610) I was told I didn't need `--device=/dev/dri:/dev/dri` but lacking that in my docker run command I would get "no CUDA-capable device is detected"

Then I noticed most of them were errors so I started looking into them. One reports:

```
[matroska @ 0x55b92fad1640] Only audio, video, and subtitles are supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
```

**To Reproduce**
Now I know that hardware transcoding works in the container. I can fire off the ffmeg with the right options and I see it in nvtop (a top that shows GPUs). So I `docker exec -it -u 1000 tdarr_node bash` and execute the following:

```
ffmpeg -c:v h264_cuvid -i "/input/TV/The Office (US)/The Office (US) S08E09 - Mrs. California.mp4" -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 195k -minrate 136k -maxrate 253k -bufsize 390k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 "/temp/The Office (US) S08E09 - Mrs. California-TdarrCacheFile-yGMPC5bw3.mkv"
```
And I get the error shown above.

**Expected behavior**
I expected this to transcode normally

According to https://www.reddit.com/r/ffmpeg/comments/qx062i/help_with_error_only_audio_video_and_subtitles/ if I merely add -dn to the ffmpeg command it works. And I verified it did indeed work for me when I added -dn running from within the Docker container.

- Config files
```
{
  "nodeID": "Earth",
  "nodeIP": "192.168.0.102",
  "nodePort": "8268",
  "serverIP": "192.168.0.251",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true"
}
```
-Log files
All I find in the log files is stuff like 

```
[2022-04-28T09:35:33.140] [INFO] Tdarr_Node - Processing file: /temp/The Office (US) S06E13 - Secret Santa-TdarrCacheFile-S9R9TlOrr.mkv
```
No mention of any errors.

-Worker error 

```
  "TranscodeDecisionMaker": "Transcode error",
  "lastHealthCheckDate": 1650380314565,
  "holdUntil": 0,
  "lastTranscodeDate": 1651163014734,
  "infoLog": "NodeID: Earth \r\n \r\n Command: \r\nffmpeg -c:v h264_cuvid -i /input/TV/The Office (US)/The Office (US) S08E09 - Mrs. California.mp4 -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 195k -minrate 136k -maxrate 253k -bufsize 390k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /temp/The Office (US) S08E09 - Mrs. California-TdarrCacheFile-yGMPC5bw3.mkv\r\nLast 200 lines of CLI log:\r\n ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)\n  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec\n\r\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/input/TV/The Office (US)/The Office (US) S08E09 - Mrs. California.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    creation_time   : 2017-07-03T00:19:06.000000Z\n    title           : The Office S08E09 Mrs California\n    encoder         : HandBrake 0.10.5 2016021100\n  Duration: 00:22:08.38, start: 0.000000, bitrate: 409 kb/s\n    Chapter #0:0: start 0.000000, end 139.890000\n    Metadata:\n      title           : 00:00:00.000\n    Chapter #0:1: start 139.890000, end 567.150000\n    Metadata:\n      title           : 00:02:19.806\n    Chapter #0:2: start 567.150000, end 995.578000\n    Metadata:\n      title           : 00:09:27.066\n    Chapter #0:3: start 995.578000, end 1328.244000\n    Metadata:\n      title           : 00:16:35.494\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360, 337 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)\n    Metadata:\n      creation_time   : 2017-07-03T00:19:06.000000Z\n      handler_name    : VideoHandler\n    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 64 kb/s (default)\n    Metadata:\n      creation_time   : 2017-07-03T00:19:06.000000Z\n      handler_name    : Stereo\n    Stream #0:2(eng): Data: bin_data (text / 0x74786574)\n    Metadata:\n      creation_time   : 2017-07-03T00:19:06.000000Z\n      handler_name    : SubtitleHandler\n\r\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))\n  Stream #0:1 -> #0:1 (copy)\n  Stream #0:2 -> #0:2 (copy)\nPress [q] to stop, [?] for help\n\r\n[hevc_nvenc @ 0x55bb4f615040] OpenEncodeSessionEx failed: out of memory (10): (no details)\n\r\n[hevc_nvenc @ 0x55bb4f615040] No capable devices found\n\r\nError initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height\n\r\nConversion failed!\n",
```

BTW: Can't infoLog be wrapped for easier reading?

 - OS: Ubuntu 21.10 (though I'm running it in a docker container)
 - Browser N/A
 - Version 2.00.15

**Additional context**

I believe I have other transcoding errors that I have not investigated yet.

Note I was not able to get hardware transcoding to even attempt to work until I modified the plugins for the library in question. Specifically, I enabled `Tdarr_Plugin_MC93_Migz1FFMPEG
Migz-Transcode Using Nvidia GPU & FFMPEG` and moved it before `Tdarr_Plugin_MC93_Migz1FFMPEG_CPU
Migz-Transcode Using CPU & FFMPEG`. It seems odd to have to do this as I would think the default setting would be to use HW if available otherwise use CPU. I have another Tdarr node who I can't seem to get HW transcoding to work. If I have those two plugins enabled and in that order what happens when my Tdarr node that can't do HW transcoding starts processing a file?

Also, I am using the Tdarr provided plugin and haven't mucked with it but I'd like to add the -dn option if that fixes this problem. How would I go about doing that?

How do I easily kick all of these transcode errors back into the queue to be processed correctly?

**Comment by HaveAGitGat** [comment]
Data streams aren't supported in mkv.  `-dn` removes data streams which is why it works.

Add `Tdarr_Plugin_vdka_Remove_DataStreams` before your transcoding plugin to automate the process.

Plugins are generally run sequentially so you have to put the plugins you'd like to run first higher in the plugin stack.

The exception to this is when using GPU workers as they'll try and run the GPU plugins else requeue the files with `requireCPU`, then CPU workers will pick them up. Or vice versa.
