### ISSUE TITLE
Need some help diagnosing transcode errors: 

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#615]
I have about 100 files out of ~14000 that have transcode errors and I'm unsure of how to correct them. Any help would be appreciated. Example logs attached. 

[vxPwanNUX0-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8595470/vxPwanNUX0-log.txt)
[HJuB3TJR7g-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8595471/HJuB3TJR7g-log.txt)
[BqeI-vIg6f-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8595472/BqeI-vIg6f-log.txt)

 - OS: Docker
 - Version 2.00.18

**Comment by HaveAGitGat** [comment]
The second one is this error:

`Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'`

https://superuser.com/questions/1633883/ffmpeg-hevc-vaapi-impossible-to-convert-between-the-formats-supported-by-the-fi

For first and second, where did you get that plugin?

Seems it's not formatting the filepaths correctly so ones with spaces are having the filename cut off.

Reopen if needed, thanks.

**Comment by tehniemer** [comment]
The plugin is a modification of [this ](https://github.com/tehniemer/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_JB69_JBHEVCQSV_MinimalFile.js)one. I just haven't submitted it to the community database yet as I wanted to make sure it was working correctly. It has successfully processed 14361 files and errored on 124.

**Comment by tehniemer** [comment]
I just submitted a pull request to have my plugins added to the community.

**Comment by tehniemer** [comment]
> The second one is this error:
> 
> `Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'`
> 
> https://superuser.com/questions/1633883/ffmpeg-hevc-vaapi-impossible-to-convert-between-the-formats-supported-by-the-fi
> 
> Reopen if needed, thanks.

The suggestion in this link didn't fix my issue, I've tried quite a few different variations on it.

[Sf372A1Df-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786530/Sf372A1Df-log.txt)
[nVgLNwMxj-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786531/nVgLNwMxj-log.txt)
[kkJaky1_--log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786532/kkJaky1_--log.txt)
[IXE1Fgfcg-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786533/IXE1Fgfcg-log.txt)
[bcwckK-03-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786534/bcwckK-03-log.txt)
[5v7rI3zvP-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8786535/5v7rI3zvP-log.txt)
