### ISSUE TITLE
Scheduler works with UTC but UI acts like server/localtime

### ISSUE THREAD

**Issue by Snuffsis** [HaveAGitGat/Tdarr#616]
**Describe the bug**
The Schedule feature of a library, and schedule under options for a node, does not follow the local or server time, it follows UTC. Which can be confusing.

**To Reproduce**
Be in timezone not the same as utc (for example sweden, which is +2 now, like me)

**Expected behavior**
It should follow server clock, or it should show that it is following utc.

**Screenshots**
![image](https://user-images.githubusercontent.com/8822958/166124394-757245f8-d8ec-47e0-8a02-447867aff16f.png)

Here you can see it is flashing 00 for sunday, which is correct, it is as of time of posting, 00:15.
However, I have to enable the hour 22 of the day before in this case for it to start, as it goes by UTC.

**Please provide the following information:**
The two config files in question:
![image](https://user-images.githubusercontent.com/8822958/166124420-ccf07d5e-559f-47c9-a240-982e64f8a5b6.png)

- There is no error, as either it shows as library or node paused and thus not running, or its running fine, which it is now that i have enabled hours 2 hours back

 - OS: Docker on Zorin OS
 - Browser: Edge
 - Version: 2.00.18

**Comment by HaveAGitGat** [comment]
This should be fixed for .19.

The browser should be following the server clock, not UTC, so in future it should flash on 22 instead of 00 in your example. Thanks.

**Comment by CameronSima** [comment]
Has the fix been released?
