### ISSUE TITLE
WQHD ('1440p') downscale resolution support

### ISSUE THREAD

**Issue by XenHat** [HaveAGitGat/Tdarr#618]
**Is your feature request related to a problem? Please describe.**
I would like to scale video down to 2560x1440. The resolution does not exist in the options panel's resolution list.

**Describe the solution you'd like**
I would like to be able to select 2560x1440 as a resolution preset in plugins and such.

**Describe alternatives you've considered**
I have not considered any alternatives

**Additional context**
Most of my displays' native resolution is 2560x1440, where 4K has significant overhead, and 1080p looks bad.
2560x1440p is also known as **WQHD**.

**Comment by HaveAGitGat** [comment]
The options tab just shows some common resolutions which Tdarr uses for some simple categorization.

You can still access the width and height in plugins using:

`file.meta.ImageWidth`
`file.meta.ImageHeight`

You can also get it from the FFprobe data:

`file.ffProbeData.streams[0].width`
`file.ffProbeData.streams[0].height`

Example use in plugin: 

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/d245122b31d61dbd6778b20c7bfdaa7543b5b6de/Community/Tdarr_Plugin_e3jc_Tharic_H.264_MKV_480p30_No_Subs_No_Title_Meta.js#L62

Note that downscaling will still require the file to be transcoded so there might be some quality loss.

I'll add 1440p category option for the next version.
