### ISSUE TITLE
Transcode cache not always cleaned up

### ISSUE THREAD

**Issue by Glynax** [HaveAGitGat/Tdarr#619]
**Describe the bug**
I have ~20 nodes all using a ZFS mirrored 1TB SSDs NFS share for a temp transcode cache, I notice every few weeks or months it inevitably fills up (till I catch it at 80%) with files that have not been touched in weeks. Picture attached shows a handful of those small null files but the bulk of the space is taken by videos at various levels of processing.

**To Reproduce**
I'm just running tdarr and nodes in a docker compose (except my windows node)

**Expected behavior**
I'd expect the temp files to be purged after the entire plugin stack is finished for said file

**Screenshots**
https://cdn.discordapp.com/attachments/623799920574595092/972665664529645578/unknown.png

[Tdarr_Server_Log1.txt](https://github.com/HaveAGitGat/Tdarr/files/8646396/Tdarr_Server_Log1.txt)
[Tdarr_Server_Log2.txt](https://github.com/HaveAGitGat/Tdarr/files/8646397/Tdarr_Server_Log2.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/8646398/Tdarr_Server_Log.txt)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
![image](https://user-images.githubusercontent.com/7043861/167283432-7a756ec8-9a89-4967-9066-03253dd534f3.png)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom] 
I had just cleared out the staging queue.. Is there anywhere else I could find this info?

 - OS: [e.g. Linux] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 2.00.00] 2.00.18

**Additional context**

**Comment by HaveAGitGat** [comment]
Those files all have `null` as the container so are they from when you didn't have the plugin configs quite right? If you clear those out manually do you still encounter the issue on new files?

**Comment by Glynax** [comment]
> Those files all have `null` as the container so are they from when you didn't have the plugin configs quite right? If you clear those out manually do you still encounter the issue on new files?

I still have it to this day, haven't changed anything in awhile I was letting it settle to see if it would go away.
![image](https://user-images.githubusercontent.com/7043861/171784197-62579c80-7dc5-432e-8556-38742deb32f2.png)

**Comment by ArmonicPvP** [comment]
I have this exact same issue. This is over three days:

![image](https://user-images.githubusercontent.com/24983808/178084764-c8a607d8-3ed2-40c0-a4ec-20c8e9fd34b1.png)

**Comment by cjmanca** [comment]
Can confirm that I also see extra files left behind occasionally. It usually cleans up, but sometimes will leave a file behind. I haven't found a specific cause yet though.

**Comment by HaveAGitGat** [comment]
2.00.20 has several new things to address this:

```
- Added improved cache cleaner service
- Added cache file browser to Staging section for manually deleting cache files if needed
```

Cache cleaner service will run hourly and clean up any dangling cache files not in use. Then there's a UI in the staging section to force delete cache files if needed.
