### ISSUE TITLE
Multiple GPUs in one system. Allow selection of work for specific GPUs.

### ISSUE THREAD

**Issue by simeononsecurity** [HaveAGitGat/Tdarr#622]
Say for instance I have two a2000's in a system running tdarr. There is no way of utilizing more than one gpu per system in tdarr currently. Even if I use the tdarr docker container and use the docker commands to specify each gpu it still doesn't work. This is unfortunate and seemingly a huge lack of support. For those of us with larger libraries of files, transcoding across multiple gpus without having to build multiple tdarr nodes would be great.

**Comment by adefaria** [comment]
Hmmm.... my Tdarr setup seems to be using 3 GPUs on my Nvidia card:

![Screenshot at 2022-05-12 07-14-00](https://user-images.githubusercontent.com/2692127/168095713-00871c81-9ade-4491-839f-d8c965cb0dfa.png)

Or perhaps I don't understand. Are you saying you can only use one of your a2000's at a time? I have only 1 Nvidia card but I think it has multiple GPUs - https://gpuspecs.com/card/nvidia-geforce-rtx-2060-super-8gb

**Comment by simeononsecurity** [comment]
> :

Yeah unfortunately it just doesn't work that way. If your gpu has multiple encoders ffmpeg and handbreak only utilize one. If you have multiple gpus, ffmpeg and handbreak have options to select which gpu to use. However, tdarr will only use one gpu. I'm not looking to use multiple gpus for a single task. However when I've got multiple workers running, I want the ability to distribute the work across the gpus. Which, tdarr doesn't have any options for currently.

**Comment by HaveAGitGat** [comment]
Will move this under here:
https://github.com/HaveAGitGat/Tdarr/issues/477

**Comment by eliliam** [comment]
> Or perhaps I don't understand.

It's the later, if you look at the `DEV` column all the `tdarr-ffmpeg` processes are running on device 0, so it's only using a single one of your GPUs. I think you were thinking he meant multiple GPU cores(CUDA), but he's referring to multiple physical GPU devices.

**Comment by dennix85** [comment]
since using docker, can't just pop each gpu in its own container and handle it in the webui as a separated node ?
At least that's how i used to deal with multi gpu in linux before the switch to windows for multi gpu environment.
