### ISSUE TITLE
Filter by Tag to prevent re-encodes

### ISSUE THREAD

**Issue by jfishie** [HaveAGitGat/Tdarr#623]
Is it possible to filter against a specific tag to prevent re-encoding files?

I would like to convert my library to H265 with the tag -tag:v hvc1 so that my files will preview and play natively on macOS. 

My understanding was that HVC1 was a codec (distinguishable from HEVC) and setting the filter to HVC1 would exclude HVC1 files from being encoded. However, any file that is already in HEVC is ignored since tdarr sees HVC1 and HEVC as being the same thing. Therefore, files that I **would** like to encode and tag are skipped. 

I would like to see a way to filter against FFmpeg tags or have support for different variations of the H265 codecs to better handle re-encoding. 

I am still struggling to find a solution that may allow filtering based on the FFmpeg arguments.

**Comment by HaveAGitGat** [comment]
Are you able to post the Tdarr file info for one of your hvc1 and hevc files (click on the file on Tdarr tab and a popup will show)? FFprobe sees those codecs the same as you say.

**Comment by HaveAGitGat** [comment]
I've added a new plugin called `Tdarr_Plugin_00td_filter_by_codec_tag_string`

So in the `codecTagStringsToNotProcess` input, put hvc1 and that should do what you're after :).

Let me know if it works as you intend.

**Comment by jfishie** [comment]
The new plug in appears to be working. Thank you.  HVC1 files are shown as successful/not required and current HEVC files are being processed if they do not contain the HCV1 tag.

**Comment by HaveAGitGat** [comment]
Great, thanks for the update
