### ISSUE TITLE
[Bug] Sort By Smallest First

### ISSUE THREAD

**Issue by zero77** [HaveAGitGat/Tdarr#624]
**Describe the bug**
I have selected sort by smallest first and for the first few entries its working. But, once you start to scroll down there is a mixture of different sizes across GB, MB and KB in no particular order.

Also, once you move to a different tab or page it resorts the order and not even the top entries are ordered correctly.

**To Reproduce**
sort by smallest first

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux] Debian
 - Browser [e.g. chrome, safari] Firefox and Chrome
 - Version [e.g. 2.00.00]  200.18

**Additional context**

**Comment by HaveAGitGat** [comment]
How are you sorting the queue? Make sure to use this setting:

![image](https://user-images.githubusercontent.com/43864057/168513218-34a58034-ee53-4e85-88a0-8c750ad378f7.png)

**Comment by zero77** [comment]
@HaveAGitGat 
> How are you sorting the queue? Make sure to use this setting:
> 
> ![image](https://user-images.githubusercontent.com/43864057/168513218-34a58034-ee53-4e85-88a0-8c750ad378f7.png)
> 

Yes, i have tried sorting with the dropdown under options and at the top of the column, neither seem to work correctly.

**Comment by HaveAGitGat** [comment]
Thanks, does it resolve itself after a restart? I use this setting on my library and has been working fine, haven't heard of any other reports of it so far.

Will keep this open for more reports. Showing like this for me atm:

![image](https://user-images.githubusercontent.com/43864057/169105765-8dd05394-fc29-4292-8f25-06334ad3af18.png)

**Comment by zero77** [comment]
@HaveAGitGat 
I have left Tdarr running for several days and it has cleared the smaller files. Now there are only files that range from several GB to several hundred MB.

This seems to have fixed the issue. So it looks like it's not sorting between KB, MB, GB mixed numbers that range from one to three digits.

**Comment by HaveAGitGat** [comment]
Haven't heard any more reports of this from anyone so will close, reopen if needed ty
