### ISSUE TITLE
Unable to transcode some .mp4 files to .mkv

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#625]
I have many videos failing to transcode. Here's a typical error:

```
"NodeID: Earth \r\n \r\n Command: \r\nffmpeg -c:v h264_cuvid -i /input/TV/Quantum Leap/Quantum Leap S01E04 - The Right Hand of God.mp4 -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 185k -minrate 129k -maxrate 240k -bufsize 370k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /temp/Quantum Leap S01E04 - The Right Hand of God-TdarrCacheFile-Uw0-yF1AT.mkv\r\nLast 200 lines of CLI log:\r\n ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)\n  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec\n\r\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n\r\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/input/TV/Quantum Leap/Quantum Leap S01E04 - The Right Hand of God.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    creation_time   : 2017-09-11T23:07:11.000000Z\n    title           : Quantum Leap S01E04 The Right Hand of God\n    encoder         : HandBrake 0.10.5 2016021100\n  Duration: 00:47:39.65, start: 0.000000, bitrate: 388 kb/s\n    Chapter #0:0: start 0.000000, end 116.158000\n\r\n    Metadata:\n      title           : Chapter 1\n    Chapter #0:1: start 116.158000, end 339.422000\n    Metadata:\n      title           : Chapter 2\n    Chapter #0:2: start 339.422000, end 745.995000\n    Metadata:\n      title           : Chapter 3\n    Chapter #0:3: start 745.995000, end 1246.537000\n    Metadata:\n      title           : Chapter 4\n    Chapter #0:4: start 1246.537000, end 1462.836000\n    Metadata:\n      title           : Chapter 5\n    Chapter #0:5: start 1462.836000, end 1765.013000\n    Metadata:\n      title           : Chapter 6\n    Chapter #0:6: start 1765.013000, end 2043.166000\n    Metadata:\n      title           : Chapter 7\n    Chapter #0:7: start 2043.166000, end 2311.100000\n    Metadata:\n      title           : Chapter 8\n    Chapter #0:8: start 2311.100000, end 2802.550000\n    Metadata:\n      title           : Chapter 9\n    Chapter #0:9: start 2802.550000, end 2859.607000\n    Metadata:\n      title           : Chapter 10\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 480x360, 316 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)\n    Metadata:\n      creation_time   : 2017-09-11T23:07:11.000000Z\n      handler_name    : VideoHandler\n    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 65 kb/s (default)\n    Metadata:\n      creation_time   : 2017-09-11T23:07:11.000000Z\n      handler_name    : \r\nStereo\n    Stream #0:2(eng): Data: bin_data (text / 0x74786574)\n    Metadata:\n      creation_time   : 2017-09-11T23:07:11.000000Z\n      handler_name    : SubtitleHandler\n\r\n[AVHWDeviceContext @ 0x561e912c6e40] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n\r\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))\n  Stream #0:1 -> #0:1 (copy)\n  Stream #0:2 -> #0:2 (copy)\nError while opening decoder for input stream #0:0 : Unknown error occurred\n"
```

If I extract the ffmpeg command and convert the paths appropriately (the above is from Tdarr running in a Docker container whereas my reproduction of the ffmpeg command is running on my desktop, outside of Docker). Somewhere I found that this problem can be solved merely by changing the .mkv -> .mp4 on the output file. This works! So the question is why doesn't it work under Tdarr and how can I fix that?

I also see this error:
```
[matroska @ 0x564439a1ed40] Subtitle codec 94213 is not supported.
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Error initializing output stream 0:0 -- 
Conversion failed!
```

**Comment by HaveAGitGat** [comment]
Depends which plugin you're using. Some plugins have the option to set the container:

![image](https://user-images.githubusercontent.com/43864057/168512873-856c6129-8eb7-40e3-8994-5363aa707fa9.png)

**Comment by adefaria** [comment]
But don't I want to have things converted to mkv? I have not really gotten into plugins. The only change I made was to configure Tdarr_Plugin_MC93_Migz1FFMPEG Migz-Transcode Using Nvidia GPU & FFMPEG in order to get HW transcoding and to disable Tdarr_Plugin_MC93_Migz1FFMPEG_CPU Migz-Transcode Using CPU & FFMPEG. Interestingly I cannot copy and paste the names. Weird - anyway, forgive any typos I made.

Or are you saying that I should re-activate the later plugin and processing will first try HW transcoding with Nvidia (cause it's listed first) but if that fails then it will continue with the next plugin that uses the CPU (and to say change the container to mp4)?

**Comment by HaveAGitGat** [comment]
That plug-in outputs to mkv by default so click on it in the plug-in stack and in the popup replace mkv with mp4.

**Comment by adefaria** [comment]
Again, but isn't mkv better?

**Comment by jimbodoken-byte** [comment]
Dev - Would it would be better to add an option to add the ffmpeg flag -c:s srt when mov_text (Subtitle codec 94213) is encountered?

**Comment by countbuggula** [comment]
> Dev - Would it would be better to add an option to add the ffmpeg flag -c:s srt when mov_text (Subtitle codec 94213) is encountered?

I'll second this.  I prefer to use mkv containers but have a bunch of media that fails transcoding/remuxing due to subtitle codec 94213.

**Comment by pmmikes** [comment]
Could this be accomplished through a plugin?

**Comment by HaveAGitGat** [comment]
Can use `Tdarr_Plugin_00td_action_remove_stream_by_specified_property`

So set `propertyToCheck` as the stream property to check, I think in this case it's `codec_name`, `codec_tag` or `codec_tag_string` - can check by clicking on the filename on the Tdarr tab and checking what `94213` comes under (I don't have any of these files so can't check sorry)

Then in `valuesToRemove` enter `94213`

**Comment by HaveAGitGat** [comment]
@jimbodoken-byte use above plugin for more general solution^

**Comment by mpolom** [comment]
I also found that using the _Migz-Transcode Using CPU & FFMPEG_ plugin I was able to get around the error by selecting `false` in the `force_conform` variable

**Comment by jbridgma** [comment]
I've had this same problem (and the `force_confirm` option described above didn't work for me) so I tried `Tdarr_Plugin_00td_action_remove_stream_by_specified_property `.

Curiously, I don't see `94213` listed in any of the problematic streams when I examine then, but I did find some other common identifiers I have tried. Currently, I'm using `codec_name` as the stream property to check with a `value_to_remove` of `bin_data`, as that was true of every subtitle stream I looked at that threw the `94213` error, and none of the working subtitles used that codec name.

This _almost_ seems to be working. I have it at the top of my plugin stack, so here's a few select lines from the log for the first task, C1:

```
Pre-processing - Tdarr_Plugin_00td_action_remove_stream_by_specified_property
Removing stream 4 which is has codec_name of bin_data
Files has streams which need to be removed, processing
...
[Step W06] [C1] Worker [-success-]
Updating transcode stats
Deleting non-latest cache file /mnt/media/Tdarr/{redacted}
Scanning new file: /temp/Yesterday (2019) {imdb-tt8079248}-TdarrCacheFile-u5YInZGDG.mp4
Updating file properties using mkvpropedit
Updated file properties using mkvpropedit
Requesting Tdarr Server to scan file
Subworker exited null
Scan complete
Transcodes during this job so far: 1
```
In spite of the `Subworker exited null` line, the transcode task shows as successful in Tdarr log. BUT, when Tdarr moves onto the next job, it runs this same plugin all over again. Here's select log notes from what should be the next task, C2:

```
Pre-processing - Tdarr_Plugin_00td_action_remove_stream_by_specified_property
Removing stream 4 which is has codec_name of bin_data 
Files has streams which need to be removed, processing 
```

Which leads to this (understandably):

```
Performing safety check on worker config to see if old transcode args/container match new ones
Safety check [-error-]:The new transcode arguments were the exact same as the last ones meaning
the file/worker would most likely be stuck in an infinite transcode loop if not stopped. 
Last arguments: , -map 0 -c copy -max_muxing_queue_size 9999 -map -0:4 in .mp4 
New arguments: , -map 0 -c copy -max_muxing_queue_size 9999 -map -0:4 in .mp4 
Plugin Community Tdarr_Plugin_00td_action_remove_stream_by_specified_property 
Check your plugin stack or transcode settings to make sure that you have conditions to prevent an infinite transcode loop 
```

The `Tdarr_Plugin_00td_action_remove_stream_by_specified_property` seems like it's _so close_ to being the thing I need here. But I _think_ it's not successfully removing the bad subtitle stream when it transcodes, which leads to it looping (and thankfully detecting the loop and exiting - nice safety check, I appreciate that lol).

There's not a lot of settings to tweak with this plugin though, so I'm at a bit of a loss as to how to fix the issue. I've tried a couple different `valuesToRemove` for the bad subtitle streams and none have worked. Any ideas?

**Comment by mpolom** [comment]
> I've had this same problem (and the `force_confirm` option described above didn't work for me) so I tried `Tdarr_Plugin_00td_action_remove_stream_by_specified_property `.
> 
> Curiously, I don't see `94213` listed in any of the problematic streams when I examine then, but I did find some other common identifiers I have tried. Currently, I'm using `codec_name` as the stream property to check with a `value_to_remove` of `bin_data`, as that was true of every subtitle stream I looked at that threw the `94213` error, and none of the working subtitles used that codec name.
> 
> This _almost_ seems to be working. I have it at the top of my plugin stack, so here's a few select lines from the log for the first task, C1:
> 
> ```
> Pre-processing - Tdarr_Plugin_00td_action_remove_stream_by_specified_property
> Removing stream 4 which is has codec_name of bin_data
> Files has streams which need to be removed, processing
> ...
> [Step W06] [C1] Worker [-success-]
> Updating transcode stats
> Deleting non-latest cache file /mnt/media/Tdarr/{redacted}
> Scanning new file: /temp/Video {imdb-##}-TdarrCacheFile-u5YInZGDG.mp4
> Updating file properties using mkvpropedit
> Updated file properties using mkvpropedit
> Requesting Tdarr Server to scan file
> Subworker exited null
> Scan complete
> Transcodes during this job so far: 1
> ```
> 
> In spite of the `Subworker exited null` line, the transcode task shows as successful in Tdarr log. BUT, when Tdarr moves onto the next job, it runs this same plugin all over again. Here's select log notes from what should be the next task, C2:
> 
> ```
> Pre-processing - Tdarr_Plugin_00td_action_remove_stream_by_specified_property
> Removing stream 4 which is has codec_name of bin_data 
> Files has streams which need to be removed, processing 
> ```
> 
> Which leads to this (understandably):
> 
> ```
> Performing safety check on worker config to see if old transcode args/container match new ones
> Safety check [-error-]:The new transcode arguments were the exact same as the last ones meaning
> the file/worker would most likely be stuck in an infinite transcode loop if not stopped. 
> Last arguments: , -map 0 -c copy -max_muxing_queue_size 9999 -map -0:4 in .mp4 
> New arguments: , -map 0 -c copy -max_muxing_queue_size 9999 -map -0:4 in .mp4 
> Plugin Community Tdarr_Plugin_00td_action_remove_stream_by_specified_property 
> Check your plugin stack or transcode settings to make sure that you have conditions to prevent an infinite transcode loop 
> ```
> 
> The `Tdarr_Plugin_00td_action_remove_stream_by_specified_property` seems like it's _so close_ to being the thing I need here. But I _think_ it's not successfully removing the bad subtitle stream when it transcodes, which leads to it looping (and thankfully detecting the loop and exiting - nice safety check, I appreciate that lol).
> 
> There's not a lot of settings to tweak with this plugin though, so I'm at a bit of a loss as to how to fix the issue. I've tried a couple different `valuesToRemove` for the bad subtitle streams and none have worked. Any ideas?

I am using the plugin `Tdarr_Plugin_vdka_Remove_DataStreams` to do exactly this 
The description is
`[Contains built-in filter] This plugin removes data streams if detected. The output container is mkv. Helps with issues like bin_data making files impossible to process.`
But also no joy!

**Comment by jbridgma** [comment]
I have still been unable to find any plugin that's capable of removing the subtitle streams that throw the `Subtitle codec 94213 is not supported` error.

As a fallback, I tried to see if I could get a filter such as `Tdarr_Plugin_00td_filter_by_file_property` or `Tdarr_Plugin_00td_filter_by_codec_tag_string` to identify files that contained the mkv-breaking subtitle streams. My intent was to have two libraries with the same source folder - both of which started with that filter.

One library would be configured to transcode to h265 with mp4 if the unsupported subtitle stream was present - since mkv wouldn't work on those files. The other library would transcode to h265 with mkv if the unsupported subtitle stream was NOT present.

I'm pretty sure this _would_ work, and it would get as many of my files as possible into mkv, except for some reason I cannot figure out how to get any of the available filters to work. If I tell them to look for things like `code_name` of `bin_data`, they can't find it.

If anybody can find an applicable filter, let me know. I'd settle for that solution as opposed to simply leaving the unsupported subtitle files as failed transcodes, and as opposed to choosing mp4 as the default for everything.

For lack of a more graceful alternative, I might still try a two-library-same-source setup that filters for codec instead of specifically the unsupported subtitle stream. One transcodes mp4->mp4 only, and the other transcodes all other files. I'll get as much mkv as I can, and I won't have to re-transcode files already processed to mp4.

If I have to use this solution, I may leave the mp4-only library set to _not_ process most of the time, and only turn it on after the main library outputting mkv has finished processing every file it can (and probably only after I also disable processing for the main library while the mp4 one is working).

None of my fallback ideas are ideal solutions, but maybe putting them out here will trigger a better idea in somebody else's brain! Hah.

**Comment by supersnellehenk** [comment]
An FYI, codec `94213` is actually `mov_text`. It's the MP4 equivalent of SRT subtitles, which can only be in an MP4 container. Easiest would be to run the Migz remux plugin that removes them using `force_conform=true`.

**Comment by jbridgma** [comment]
My plugin stack is already using `Migz-Transcode Using Nvidia GPU && FFMPEG` with `force_conform=true` and I'm still getting the `94213` errors.

I've tried a bunch of other plugins with different methods of trying to remove the `mov_text` subtitle stream, or trying to convert it to SRT, but none have worked. I've tried basically every community plugin that claims to be able to remove subtitles or able to remove streams by tag etc... no dice so far.

**Comment by rgreen83** [comment]
> Can use `Tdarr_Plugin_00td_action_remove_stream_by_specified_property`
> 
> So set `propertyToCheck` as the stream property to check, I think in this case it's `codec_name`, `codec_tag` or `codec_tag_string` - can check by clicking on the filename on the Tdarr tab and checking what `94213` comes under (I don't have any of these files so can't check sorry)
> 
> Then in `valuesToRemove` enter `94213`

For others finding this in the future I just wanted to drop a correction here because using the error value won't work. 

You want Property to Check = codec_name and Values to Remove = mov_text
Alternatively Property to Check = codec_tag_string and Values to Remove = tx3g
This works with classic plugin "Tdarr_Plugin_00td_action_remove_stream_by_specified_property" and with the ffmpeg flow plugin "Remove Stream By Property"

**Comment by joonboi** [comment]
sorry to revive something so old, but is there no way to filter and CONVERT the mov_text to SRT instead of removing it?

**Comment by MeroWW** [comment]
> sorry to revive something so old, but is there no way to filter and CONVERT the mov_text to SRT instead of removing it?

just add -c:s srt after the -c:s copy to convert to srt
