### ISSUE TITLE
[Bug] Can't Close Any Report

### ISSUE THREAD

**Issue by zero77** [HaveAGitGat/Tdarr#628]
**Describe the bug**
The exit button in the top corner seams to be missing for all of the reports. The only way to close the report you want to view is by going back or clicking an a link at the top.

**To Reproduce**
Open any report

**Expected behavior**
There should be an exit button in the top corner allowing you to close the report you are viewing. Like there is when you click on the exclamation mark next to report under Nodes.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux] Debian
 - Browser [e.g. chrome, safari] Firefox and Chrome
 - Version [e.g. 2.00.00]  2.0.18

**Additional context**

**Comment by HaveAGitGat** [comment]
Hi, this isn't a bug. When you open a report it opens the job report viewer page (useful for sharing report links around teams). 

So there's no close button as it's a completely new page with a separate link. You can right click on the report button to open in a new tab. Hope that makes sense :).
