### ISSUE TITLE
Transcoding Failing, Latest Build

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#63]
Hi,

I’ve just updated my docker container, and I’m unable to transcode using handbrake. I get the following error on every file:

```
sync: got 0 frames, 60518 expected
```

The command it’s running is:

```
HandBrakeCLI -i '/mnt/user/tvshows/iZombie/Season 2/iZombie - S02E12 - Physician, Heal Thy Selfie.mkv' -o '/home/Tdarr/cache/iZombie/Season 2/iZombie - S02E12 - Physician, Heal Thy Selfie.mkv' -Z "Very Fast 1080p30"
```

Has anything changed that might be somewhere to start with this issue? I blew away database and all app data too, just in case, but no luck.

**Comment by HaveAGitGat** [comment]
@jleck just to double check, are you on v1.0055 (it specifies at the top left of the page). And are you using tdarr or tdarr_aio container?

Also are you able to paste the full error message here?

Haven’t had any other reports of this, but `sync: got 0 frames, ` seems to be a permission issue when creating the output file in your cache.

**Comment by jleck** [comment]
D’oh, it was permissions on cache folder.

Thanks for quick response!

**Comment by HaveAGitGat** [comment]
No problem, pleased it’s resolved 👍
