### ISSUE TITLE
GPU Transcode fails in Docker container but works outside of Docker

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#630]
I have a lot of transcoding failures. I've also had a lot of transcoding successes. I have a desktop with an Nvidia card that I am running Tdarr in a Docker container. As I said many of the transcodes work just fine. I'm able to monitor the GPUs by using a version of nvtop that I built from the source. In analyzing the transcode failures I see things like:

```
"NodeID: Mars \r\n \r\n Command: \r\nffmpeg -c:v h264_cuvid -i /input/Movies/House of Gucci (2021)/House of Gucci (2021).mkv -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 4276k -minrate 2993k -maxrate 5558k -bufsize 8553k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /temp/House of Gucci (2021)-TdarrCacheFile-FAKXZA8pb.mkv\r\nLast 200 lines of CLI log:\r\n ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)\n  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n\r\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n\r\nGuessed Channel Layout for Input Stream #0.1 : 5.1\n\r\nInput #0, matroska,webm, from '/input/Movies/House of Gucci (2021)/House of Gucci (2021).mkv':\n  Metadata:\n    title           : House.of.Gucci.2021.CMRG\n    encoder         : libebml v1.3.4 + libmatroska v1.4.5\n    creation_time   : 2022-01-31T23:47:40.000000Z\n  Duration: 02:37:46.88, start: 0.000000, bitrate: 8968 kb/s\n    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x800 [SAR 1:1 DAR 12:5], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)\n    Metadata:\n      BPS             : 8326352\n      BPS-eng         : 8326352\n      DURATION        : 02:37:46.833000000\n      DURATION-eng    : 02:37:46.833000000\n      NUMBER_OF_FRAMES: 226977\n      NUMBER_OF_FRAMES-eng: 226977\n      NUMBER_OF_BYTES : 9853023992\n      NUMBER_OF_BYTES-eng: 9853023992\n      _STATISTICS_WRITING_APP: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_APP-eng: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_DATE_UTC: 2022-01-31 23:47:40\n      _STATISTICS_WRITING_DATE_UTC-eng: 2022-01-31 23:47:40\n      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n    Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1, fltp\n    Metadata:\n      title           : English\n      BPS             : 640000\n      BPS-eng         : 640000\n      DURATION        : 02:37:46.880000000\n      DURATION-eng    : 02:37:46.880000000\n      NUMBER_OF_FRAMES: 295840\n      NUMBER_OF_FRAMES-eng: 295840\n      NUMBER_OF_BYTES : 757350400\r\n\n      NUMBER_OF_BYTES-eng: 757350400\n      _STATISTICS_WRITING_APP: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_APP-eng: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_DATE_UTC: 2022-01-31 23:47:40\n      _STATISTICS_WRITING_DATE_UTC-eng: 2022-01-31 23:47:40\n      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n    Stream #0:2(eng): Subtitle: subrip\n    Metadata:\n      title           : English [SDH]\n      BPS             : 53\n      BPS-eng         : 53\n      DURATION        : 02:32:00.807000000\n      DURATION-eng    : 02:32:00.807000000\n      NUMBER_OF_FRAMES: 2245\n      NUMBER_OF_FRAMES-eng: \r\n2245\n      NUMBER_OF_BYTES : 60670\n      NUMBER_OF_BYTES-eng: 60670\n      _STATISTICS_WRITING_APP: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_APP-eng: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_DATE_UTC: 2022-01-31 23:47:40\n      _STATISTICS_WRITING_DATE_UTC-eng: 2022-01-31 23:47:40\n      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n    Stream #0:3(eng): Subtitle: subrip\n    Metadata:\n      title           : English\n      BPS             : 51\n      BPS-eng         : \r\n51\n      DURATION        : 02:31:55.846000000\n      DURATION-eng    : 02:31:55.846000000\n      NUMBER_OF_FRAMES: 2188\n      NUMBER_OF_FRAMES-eng: 2188\n      NUMBER_OF_BYTES : 58267\n      NUMBER_OF_BYTES-eng: 58267\n      _STATISTICS_WRITING_APP: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_APP-eng: mkvmerge v11.0.0 ('Alive') 64bit\n      _STATISTICS_WRITING_DATE_UTC: 2022-01-31 23:47:40\n      _STATISTICS_WRITING_DATE_UTC-eng: 2022-01-31 23:47:40\n      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\n\r\n[h264_cuvid @ 0x55b2fe35f9c0] Cannot load libnvcuvid.so.1\n[h264_cuvid @ 0x55b2fe35f9c0] Failed loading nvcuvid.\n\r\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))\n  Stream #0:1 -> #0:1 (copy)\n  Stream #0:2 -> #0:2 (copy)\n  Stream #0:3 -> #0:3 (copy)\nError while opening decoder for input stream #0:0 : Operation not permitted\n"
```
If, however, I take that ffmpeg command and run it on my desktop itself, IOW, not in the Docker container, it transcodes without issue. Why does it work on the desktop and not in the Docker container?

Note there are some 3000 or so transcode failures. While not all of them fail with Operation not permitted, some fail with other error messages, often just running it outside of the Docker container works. This is tedious at best. Is there something I can change or re-configure in the Docker container so that Tdarr transcodes it using the Docker container without error?

**To Reproduce**
Examine transcode errors in the Tdarr WebUI. Copy and paste the ffmpeg command (adjusting paths if required). See that the transcode is successful outside of the Docker container.

**Expected behavior**
I expected that Tdarr would be able to successfully transcode such files using the Docker container.

-Worker error 
[XgiZ9-oqPz-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8717667/XgiZ9-oqPz-log.txt)

 - OS: Ubuntu 21.10

**Comment by HaveAGitGat** [comment]
What is your Docker config?

Play around with this command until it's working fine on your system, then use the same settings for your Tdarr container:

https://docs.tdarr.io/docs/installation/docker/hardware-transcoding#ffmpeg-nvenc

If using NVENC on an Ubuntu or Debian host, make sure to install the [NVIDIA container toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) on the host.

**Comment by adefaria** [comment]
For tdarr_node I have:
```
#!/bin/bash

serverIP=192.168.0.251
nodeIP=$(ip address | grep 192.168 | cut -c10-22)
host=$(hostname)
mediaFolder=/Videos

# This just creates a pretty name for host with the first letter capitalized
Host=$(echo ${host:0:1} | tr [:lower:] [:upper:])$(echo ${host:1}   | tr [:upper:] [:lower:])

# Stop any running container
docker stop tdarr_node > /dev/null 2>&1

# Remove any old tdarr_node container
docker container rm -f tdarr_node > /dev/null 2>&1

# Create a docker container
# This version does not add the NVIDIA stuff. I had a problem trying to
# create a docker container with Nvidia support for Mars but not for Earth.
# Seems the MacBook is not "CUDA cabable" but rather simulates CUDA using
# the CPU. This makes it very slow. It also makes it so we cannot specify
# Nvidia stuff here.
if [ "$host" = "mars" ]; then
  echo "Running docker container for Mars with no Nvidia support"
  docker run -d \
    -v $mediaFolder:/input\
    -v /System/tmp/tdarr_cache/:/temp \
    -v /System/Config/tdarr:/app/server \
    -v /System/Config/tdarr/$host:/app/configs \
    -v /System/Config/tdarr/$host:/app/logs \
    -e "nodeID=$Host" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -p 8268:8268 \
    -e "TZ=America/Los_Angeles" \
    -e PUID=1000 \
    -e PGID=1000 \
    --network bridge \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name tdarr_node \
    ghcr.io/haveagitgat/tdarr_node
else
  echo "Running docker container for Earth with Nvidia support"
  docker run -d \
    -v $mediaFolder:/input\
    -v /System/tmp/tdarr_cache/:/temp \
    -v /System/Config/tdarr:/app/server \
    -v /System/Config/tdarr/$host:/app/configs \
    -v /System/Config/tdarr/$host:/app/logs \
    -e "nodeID=$Host" \
    -e "nodeIP=$nodeIP" \
    -e "nodePort=8268" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -e "TZ=America/Los_Angeles" \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "NVIDIA_DRIVER_CAPABILITIES=all" \
    -e "NVIDIA_VISIBLE_DEVICES=all" \
    -p 8268:8268 \
    --device=/dev/dri:/dev/dri \
    --network bridge \
    --gpus=all \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name tdarr_node \
    --runtime=nvidia \
    ghcr.io/haveagitgat/tdarr_node
  fi

# With the container created start tdarr_node
echo "Starting tdarr_node"
docker start tdarr_node

# This is needed to set the restart option
echo "Updating restart"
docker update --restart=unless-stopped tdarr_node
```
Note that Earth is my Ubuntu desktop with Nvidia and Mars is my MacBook also running Ubuntu but it's the one I had posted the issue about how to GPU transcode with AMD as that MacBook doesn't have Nvidia.

The FFmpeg NVENC results in  [ffmpeg_nvenc.txt](https://github.com/HaveAGitGat/Tdarr/files/8718844/ffmpeg_nvenc.txt) 

I have installed the NVIDIA container toolkit already on Earth. Prior to doing that no transcodes would work with the Docker container. I have done thousands of GPU transcodes of videos before. These are just the transcode errors I'm trying to work through. As I said, they are not working under Docker for these videos but have worked for many of the other videos.

**Comment by HaveAGitGat** [comment]
That logs seems fine, things running as they should be. 

How many GPU workers are you using? Running too many can cause errors as each card has an encode limit.

Does it work when you requeue the files that have failed? If not then it could be a permissions issue. That would make sense if it works fine when you run from outside of a Docker container.

**Comment by adefaria** [comment]
I keep the Transcode GPU processes to 3 or less. I've seen if I start the 4th one then it errors out. I think my limit is 3.

I've tried queuing the failed files again but they seem to just fail again.

I did the following:

1. Found a recent failed to transcode video (Metallica and San Francisco Symphony Sandm2 2019 1080P (2019).mvk).
2. All transcodes have ceased since all that could be processed were processed and I have only transcode errors to fix.
3. I requeued that video file by going to `Search` and searching for it by name and clicking on `Requeue Transcode`.
4. Watched it come into the `Nodes` queue briefly. It said Calc and the %'s were zero. It only stayed there for a second or two then disappeared. 
5. Went back to the `Search` section and clicked on `Refresh`
6. Clicked on the title then downloaded that as [Metallica and San Francisco Symphony Sandm2 2019 1080P (2019).txt](https://github.com/HaveAGitGat/Tdarr/files/8721136/Metallica.and.San.Francisco.Symphony.Sandm2.2019.1080P.2019.txt).
7. Back on the `Search` page I clicked on the `Report` button and got [9IAyDgAh7-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8721145/9IAyDgAh7-log.txt)

**Comment by HaveAGitGat** [comment]
If you check the CLI output in the job report you can see the FFmpeg output:

```
2022-05-18T14:55:42.821Z       _STATISTICS_WRITING_DATE_UTC-eng: 2020-09-07 22:28:56
2022-05-18T14:55:42.821Z       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
2022-05-18T14:55:42.821Z 
2022-05-18T14:55:42.821Z [AVHWDeviceContext @ 0x5602766c0000] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-18T14:55:42.821Z 
2022-05-18T14:55:42.821Z Stream mapping:
2022-05-18T14:55:42.821Z   Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))
2022-05-18T14:55:42.821Z   Stream #0:1 -> #0:1 (copy)
2022-05-18T14:55:42.821Z Error while opening decoder for input stream #0:0 : Unknown error occurred
2022-05-18T14:55:42.821Z 
```

So this isn't a Tdarr error per-se, just to do with FFmpeg,the file or the GPU (not a config issue as you mentioned it works on other files).

Btw you don't need to go to the search tab to requeue files. You can just hit the requeue button on the errored files at the bottom of the Tdarr tab:

![image](https://user-images.githubusercontent.com/43864057/169242120-20822717-82bd-4382-b408-8bfab9dd2f7c.png)

Unfortunately the error is very vague, perhaps try the solution here?

https://github.com/leggedrobotics/darknet_ros/issues/288

**Comment by adefaria** [comment]
I still don't understand why it works outside of Docker but not inside Docker. Apparently, the ffmpeg is different! On my desktop ffmpeg resides in /bin and is version 4.4-6ubuntu5, but inside the Docker container, it's in /usr/local/bin which symlinks to /usr/lib/jellyfin-ffmpeg and is version 4.3.2-Jellyfin. If this is the case then couldn't it be said that the Docker container is not configured correctly? Over at https://github.com/jellyfin/jellyfin-ffmpeg/releases, the latest ffmpeg is 5.0.1-5. There is a focal there but my desktop is Ubuntu 21.10 (impish).

That link talks about darknet_ros. I don't think I'm using that.  I get output from nvidia-smi. It also says that if I don't want to use Cuda then set CUDA_VISIBLE_DEVICES to 0. Well I do want to use Cuda right? Still I tried setting that but I still have the same problem.

Would it be worth it to try to install a later version of jellyfin-ffmpeg into the container? Tried but got:
```
root@3951c1d2cf13:/# dpkg -i /app/configs/jellyfin-ffmpeg5_5.0.1-4-focal_amd64.deb 
Selecting previously unselected package jellyfin-ffmpeg5.
dpkg: considering removing jellyfin-ffmpeg in favour of jellyfin-ffmpeg5 ...
dpkg: yes, will remove jellyfin-ffmpeg in favour of jellyfin-ffmpeg5
(Reading database ... 29041 files and directories currently installed.)
Preparing to unpack .../jellyfin-ffmpeg5_5.0.1-4-focal_amd64.deb ...
Unpacking jellyfin-ffmpeg5 (5.0.1-4-focal) ...
dpkg: dependency problems prevent configuration of jellyfin-ffmpeg5:
 jellyfin-ffmpeg5 depends on libllvm11 (>= 1:9~svn298832-1~); however:
  Package libllvm11 is not installed.

dpkg: error processing package jellyfin-ffmpeg5 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
Errors were encountered while processing:
 jellyfin-ffmpeg5
```

**Comment by HaveAGitGat** [comment]
Great, glad it's working for you :).
