### ISSUE TITLE
Razer game manager service opens tens of thousands of CPU handles in response to TDARR node over time

### ISSUE THREAD

**Issue by Gumbyohson** [HaveAGitGat/Tdarr#632]
**Describe the bug**
Razer game manager service opens tens of thousands of CPU handles in response to TDARR node over time resulting in very poor performance (CPU handles saturation and RAM use/leak)

**To Reproduce**
Have razer synapse
Windows 10 64
Tdarr node running GPU and CPU tasks
Leave to run for a while and watch the game manager service open more and more handles

**Expected behavior**
The Razer service shouldn't be looking at TDARR node at all

**Screenshots**
I'll add these next time it happens

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.zip](https://github.com/HaveAGitGat/Tdarr/files/8735069/Tdarr_Node_Config.zip)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.zip](https://github.com/HaveAGitGat/Tdarr/files/8735072/Tdarr_Node_Log.zip)

 - OS: Windows 10 Pro 64 21H2 

**Additional context**
I fully understand this is likely an issue on the Razer side. Was just hoping there could be a way to flag the processes as not a game despite the GPU usage.

**Comment by Gumbyohson** [comment]
![image](https://user-images.githubusercontent.com/1866263/169436644-234f43ff-3c69-4941-be93-5035c5996c59.png)
This number just keeps going up.

**Comment by Gumbyohson** [comment]
2 hours later
![image](https://user-images.githubusercontent.com/1866263/169450757-f2646c25-e6c4-49d8-a125-57b40be12d13.png)

**Comment by HaveAGitGat** [comment]
That's a very random bug but yeah not sure there's much I can do from my side. Does it go up with every item that Tdarr processes or does it just go up when Tdarr is idle?

Perhaps these might help:

https://www.reddit.com/r/razer/comments/bsfot4/razer_gamemanagerservice_using_high_cpu_usage/
https://www.reddit.com/r/razer/comments/kpp3hu/ysk_how_to_disable_razer_game_manager_service_as/
https://www.reddit.com/r/razer/comments/bpc1se/synapse_may_be_worse_than_you_think_high_cpu_usage/
https://www.reddit.com/r/razer/comments/bw1yjf/razer_gamemanagerservice_using_upto_49_cpu_and/

**Comment by Gumbyohson** [comment]
> That's a very random bug but yeah not sure there's much I can do from my side. Does it go up with every item that Tdarr processes or does it just go up when Tdarr is idle?
> 
> Perhaps these might help:
> 
> https://www.reddit.com/r/razer/comments/bsfot4/razer_gamemanagerservice_using_high_cpu_usage/ https://www.reddit.com/r/razer/comments/kpp3hu/ysk_how_to_disable_razer_game_manager_service_as/ https://www.reddit.com/r/razer/comments/bpc1se/synapse_may_be_worse_than_you_think_high_cpu_usage/ https://www.reddit.com/r/razer/comments/bw1yjf/razer_gamemanagerservice_using_upto_49_cpu_and/

Yeah ive been trying to get in the habit of killing it before i leave it running overnight.
