### ISSUE TITLE
Changing the row count for Transcode Successes to 10,000 causes UI crashes

### ISSUE THREAD

**Issue by ajax-lives** [HaveAGitGat/Tdarr#633]
**Describe the bug**
Changing the row count for Transcode Successes to 10,000 causes UI crashes

**To Reproduce**
Change row count to 10,000
UI slows to crawl
If you have less than 10,000, it fills it with empty rows.
Makes it nigh on impossible/extremely difficult to change row count back. since button hardly responds, and continues crashing.
Mine is currently stuck.

**Expected behavior**
UI/tab doesn't crash.
Doesn't fill with empty rows - just shows the maximum that you have.
Doesn't slow to a crawl.

 - OS=Linux
 - Browser=Chrome
 - Version=2.00.18

**Comment by HaveAGitGat** [comment]
I suppose it depends on your browser + CPU but yeah that's not ideal. I've removed the 10000 option for the next version.

The page size is fixed as it's not good to have the page jumping around when flicking through pages.

That setting is stored in the browser so you can fix it by clearing the site cache and it will reset to 10.

**Comment by ajax-lives** [comment]
Hey!  Thanks for the well thoughout response and decisiveness!

Also the tip on browser cache - its not stored in the config files so that makes sense.

Tdarr has been a dream for me.  Picked up a new GPU and its been tearing through, and I love that it lets GPU do CPU type tasks.  Been refactoring my audio tracks w/ AAC and converting to MP4.

Have a good one 😃

**Comment by HaveAGitGat** [comment]
You're probably not the first one to do that haha so yeah best to change it

Great glad you're finding it useful :), hope the transcoding goes well.

**Comment by ajax-lives** [comment]
For sure!
It has been awesome, keep up the fantastic work.  You're a hero!
