### ISSUE TITLE
Re-order streams is stuck in an infinite loop

### ISSUE THREAD

**Issue by pabloromeo** [HaveAGitGat/Tdarr#635]
**Describe the bug**
It appears that certain files get stuck in infinite loops attempting to re-order the streams, continuously re-ordering them in different ways for hours and hours creating dozens of different file versions that never end. I'm attaching an example after a few versions, however other files have run for hours and generated so many versions that the Output screen can't even load.

**To Reproduce**
Attempt to process certain files. It's also not a single one either, it's occurred to about 10 of them, which i had to manually cancel.

**Expected behavior**
Processing should re-order streams and continue with the process flow.

**Screenshots**
The re-order streams plugin is just the default one: "Tdarr_Plugin_00td_action_re_order_all_streams_v2"
![image](https://user-images.githubusercontent.com/41338020/169845025-0139ced7-6077-47ef-ab43-592468a62d60.png)

**Please provide the following information:**
Log file: [KjrSaRc8H-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8755464/KjrSaRc8H-log.txt)

The same happens both on a CPU Worker running on Windows (manually installed Node), as well as on a docker-based GPU Worker running on a Linux-based QNAP NAS.
Also, this same configuration and Workers has processed hundreds of other files previously without problems. 

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks I might modify that plugin to skip mp4 files as it seems ffmpeg struggles to re-order them sometimes, seems to be an ffmpeg bug as the Tdarr logic is fine.

**Comment by HaveAGitGat** [comment]
I updated the plugin yesterday so now with mp4 files it only puts the video stream first and doesn't try to do more advanced stream ordering. So should be working fine now, re-open if needed.

**Comment by pabloromeo** [comment]
I'll give it a try, thanks!!
