### ISSUE TITLE
Docker HandBrakeCLI does not support qsv hardware encoding

### ISSUE THREAD

**Issue by makzdot** [HaveAGitGat/Tdarr#638]
**Describe the bug**
QSV does not work for HandBrakeCLI inside the Docker install. Due to missing Debian packages related to: https://github.com/HandBrake/HandBrake-docs/issues/164

The Dockerfile is missing the following apt packages:
- libmfx-dev
- libmfx1

**To Reproduce**
1. Get a Docker container up and running with hardware encoding support:
tdarr:
    hostname: tdarr
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Amsterdam
      - serverPort=8266
      - internalNode=false
      - webUIPort=8265
      - nodePort=8267
    volumes:
      - /data/tdarr/config:/app/server
      - /data/tdarr/cache/:/temp
      - /media:/media
      - /data/handbrake/config:/config:ro
      - /mnt/tdarr:/cache
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8265:8265
      - 8266:8266
      - 8267:8267

2. go into the docker container with "docker exec -it tdarr /bin/bash"3. 
3. Do HandBrakeCLI --help. 4. 
4. Under "Video Options" at the -e part the output should also list: 
                               qsv_h264
                               qsv_h265
                               qsv_h265_10bit
But it does not.

**Expected behavior**
It should also list the above encoders

**Screenshots**

**Please provide the following information:**
Adding the packages to the Dockerfile should fix the problem (Tested locally)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
Not needed

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
Not needed

 - OS: [e.g. Linux] Ubuntu 20.04.4 LTS
 - Version [e.g. 2.00.00] 2.00.18

**Additional context**
Adding these packages after line 93 in the Dockerfile should fix the problem. I could not test if this breaks builds on other architectures though.
- libmfx-dev
- libmfx1

**Comment by p2bauer** [comment]
I'm seeing this issue as well on the `latest` node image, and I'm curious - does this mean if you want to use Intel/QSV on docker, you can't use handbrake-based plugins? 

...and if it's a matter of installing 2 additional packages in the dockerfile, is that something that @HaveAGitGat you're open to?

**Comment by HaveAGitGat** [comment]
I've added those deps, new dev image will be available in 30 mins or so: https://hub.docker.com/r/haveagitgat/tdarr_acc/tags

**Comment by p2bauer** [comment]
@HaveAGitGat just pulled the new dev image down and tried it out.  After many struggles, this time right away for the first time handbrake reported:

> Intel Quick Sync Video support: yes

Will start trying both h264 and 265 encodes now that handbrake is finally reporting that they're supported via qsv :-). Thank you both @HaveAGitGat and @makzdot for your help!

**Comment by HaveAGitGat** [comment]
Great thanks for the update 🙂 ty to @makzdot

**Comment by giop98** [comment]
@p2bauer Did you manage to transcode something using quick sync? I tried many plugins but none of the works. I'm running an intel i7 7700t

**Comment by p2bauer** [comment]
@giop98 sorry, I got busy and I should've posted a follow up - it worked for me as well after I switched to the tdarr_acc `dev` image, using the `handbrake basic options` plugin for h265 w/ qsv.  (and I'm able to use qsv with plex via docker as well, using `/dev/dri` just like tdarr)

But I wasn't able to get the same plugin working with h264.  Which codec(s) were you able to successfully use?

**Comment by HaveAGitGat** [comment]
Reopen after trying 2.00.19 if needed and post job report ty https://docs.tdarr.io/docs/other/job-reports/
