### ISSUE TITLE
libnvrm.so: cannot open shared object file error on Jetson Nano in Docker

### ISSUE THREAD

**Issue by gregology** [HaveAGitGat/Tdarr#646]
**Describe the bug**

I'm running Tdarr on a Jetson Nano with Docker. I am using the default GPU transcode options. Any file I try and transcode returns this error

`tdarr-ffmpeg: error while loading shared libraries: libnvrm.so: cannot open shared object file: No such file or directory`

I also have the same error when I try to CPU transcode. The media is stored on an NFS share but I have confirmed that the container has the appropriate permissions.

I have also attempted to transcode many different formats and file types but all return the same error. I have updated the packages on the docker container but that didn't help either. I haven't been able to find this particular error anywhere else.

**To Reproduce**

Install the latest version of Jetpack for Jetson Nano, create docker container with config below, try and transcode any file.

**Expected behavior**

I would assume it would work out of the box with default settings.

**Screenshots**

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/1595448/172517070-293d638c-f18a-4756-bd97-fbd7dff479a4.png">

**Please provide the following information:**

Config files
  
```
docker run -td \
    --name tdarr \
    -v $HOME/tdarr/server:/app/server \
    -v $HOME/tdarr/configs:/app/configs \
    -v $HOME/tdarr/logs:/app/logs \
    -v $HOME/nfs/Media:/media \
    -e "serverIP=10.0.0.135" \
    -e "serverPort=8266" \
    -e "webUIPort=8265" \
    -e "internalNode=true" \
    -e "nodeID=MyInternalNode" \
    --network bridge \
    -p 8265:8265 \
    -p 8266:8266 \
    -e "TZ=America/Toronto" \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "NVIDIA_DRIVER_CAPABILITIES=all" \
    -e "NVIDIA_VISIBLE_DEVICES=all" \
    --gpus=all \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    ghcr.io/haveagitgat/tdarr
```

Worker error

`Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W05] [C1] Launching subworker`
```
1 2022-06-07T21:50:18.385Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W05] [C1] Launching subworker
2 2022-06-07T21:50:18.388Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Preparing to launch subworker
3 2022-06-07T21:50:18.389Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker launched
4 2022-06-07T21:50:18.390Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[1/3] Sending command to subworker
5 2022-06-07T21:50:18.391Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[2/3] tdarr-ffmpeg -c:v mpeg4_cuvid -i /media/tmp/x265/Ewoks - Caravan of Courage (1984) [thePiratePimp].avi -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 481k -minrate 336k -maxrate 625k -bufsize 963k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 Ewoks - Caravan of Courage (1984) [thePiratePimp]-TdarrCacheFile-ON1dXFR2Tm.mkv
6 2022-06-07T21:50:18.392Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[3/3] Command sent
7 2022-06-07T21:50:18.392Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:To see live CLI output, enable 'Log full FFmpeg/HandBrake output' in the staging section on the Tdarr tab before the job starts.
8 2022-06-07T21:50:19.398Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker:Online
9 2022-06-07T21:50:19.400Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker:Receiving transcode settings
10 2022-06-07T21:50:19.401Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker:Running CLI
11 2022-06-07T21:50:19.402Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker exit approved, killing subworker
12 2022-06-07T21:50:19.402Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Subworker killed
13 2022-06-07T21:50:19.403Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:CLI code: 127
14 2022-06-07T21:50:19.404Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Last 200 lines of CLI log:
15 2022-06-07T21:50:19.405Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:tdarr-ffmpeg: error while loading shared libraries: libnvrm.so: cannot open shared object file: No such file or directory
16 2022-06-07T21:50:19.405Z
17 2022-06-07T21:50:19.405Z
18 2022-06-07T21:50:19.405Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[-error-]
```

`Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W07] [C1] Worker [-error-]`

```
1 2022-06-07T21:50:19.406Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W07] [C1] Worker [-error-]
2 2022-06-07T21:50:19.406Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Error encountered when processing /media/tmp/x265/Ewoks - Caravan of Courage (1984) [thePiratePimp].avi
3 2022-06-07T21:50:19.407Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Checking new cache file
4 2022-06-07T21:50:19.407Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Tdarr ALERT: NO OUTPUT FILE PRODUCED:
5 2022-06-07T21:50:19.407Z Ewoks - Caravan of Courage (1984) [thePiratePimp]-TdarrCacheFile-ON1dXFR2Tm.mkv
6 2022-06-07T21:50:19.408Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Updating transcode stats
```

`Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W09] [-error-] Job end`

```
1 2022-06-07T21:50:19.408Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:[Step W09] [-error-] Job end
2 2022-06-07T21:50:19.409Z t2_9I7-mqNo:Node[MyInternalNode]:Worker[yGG4GIGUN]:Transcoding error encountered. Check sections above.
```

 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 102.0.5005.61

**Additional context**

**Comment by supersnellehenk** [comment]
So, according to https://reddit.com/r/JetsonNano/comments/j57xsz/nvenc_hw_encode_error_ffmpeg_on_jetson_nano/ the nano doesn't officially support ffmpeg at all. It uses Gstreamer, which someone built an ffmpeg wrapper thing for. https://github.com/jocover/jetson-ffmpeg if you could get that working on your bare Ubuntu install you could map it into the docker container, though you'd need to create your own plugin to use the jetson encoder.

**Comment by gregology** [comment]
Thanks for the direction. I'll close this issue because it's out of scope but I'll post an update here once I get it working for future googlers. Cheers @supersnellehenk!

**Comment by isaacolsen94** [comment]
> Thanks for the direction. I'll close this issue because it's out of scope but I'll post an update here once I get it working for future googlers. Cheers @supersnellehenk!

Did you ever get this figured out? One of those googlers looking for solution lol
