### ISSUE TITLE
Tdarr keeps transcoding the same files - "File is hevc or vp9 but is not in mp4 container. Remuxing.

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#647]
Tdarr seems to get stuck in a loop processing the same files over and over again resulting in a video that is larger than the original, then tries again, over and over again getting nowhere.

**To Reproduce**
I just notice that Tdarr appears to be stuck. Seems the transcodes do a simple -map 0 -c copy

```
tdarr-ffmpeg -i /input/Movies/The Idle Class (1921).mkv -map 0 -c copy /temp/The Idle Class (1921)-TdarrCacheFile-Mc4ltZJf4p.mp4
```

**Expected behavior**
I expected either the transcode to produce a smaller file or if it can't, skip doing the file marking it as already optimized.

This is a real pain as all future transcodes get backed up over these stuck transcodes.

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

[ONhiuX-66-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8886030/ONhiuX-66-log.txt)

**Comment by supersnellehenk** [comment]
You've got the GPU plugin set to mp4, but the CPU plugin is set to MKV. That's your issue.

**Comment by adefaria** [comment]
Really? How do I correct?

**Comment by supersnellehenk** [comment]
> Really? How do I correct this? What are the exact steps to take?

Just set the container the same for both plugins.

**Comment by adefaria** [comment]
AFAICT they are the same.
![2022-06-12@07:59:42](https://user-images.githubusercontent.com/2692127/173239282-ea8f2332-b70c-4199-9d23-838d79c7897f.png)

![2022-06-12@08:00:23](https://user-images.githubusercontent.com/2692127/173239321-608fb2f1-dd51-40c7-b686-93be6dac7c22.png)

I had at one time changed the container for the GPU plugin to mp4 because I was getting errors when it was set to mkv. I've since changed it back as you can see. Either way these suck transcodes seem to happen.

**Comment by supersnellehenk** [comment]
```2022-06-12T07:25:20.509Z Pre-processing - Migz-Transcode Using Nvidia GPU & FFMPEG
2022-06-12T07:25:20.509Z File is already hevc or vp9 & in mp4. 
2022-06-12T07:25:20.509Z 
2022-06-12T07:25:20.509Z Pre-processing - Migz-Transcode Using CPU & FFMPEG
2022-06-12T07:25:20.509Z File is hevc or vp9 but is not in mkv container. Remuxing. ```

That's what's juggling constantly according to the log you've sent. Make sure you requeue a file that's currently being worked on to reflect the changes.

**Comment by adefaria** [comment]
OK, it may have been that this report was when it was set to mp4. I used Search to requeue this. How do I flush it up to the top so as to see if it works now?

**Comment by HaveAGitGat** [comment]
You can search for the file and then use the bump button to put it to the top

**Comment by HaveAGitGat** [comment]
Think this can now be closed but reopen if needed.
