### ISSUE TITLE
size queue filter should be intelligent

### ISSUE THREAD

**Issue by robvanhooren** [HaveAGitGat/Tdarr#648]
_**Please describe.**_

the 'size' queue filter is not useful, since filter value(s) often range wildly.

whereas queue filters such as 'codec', 'resolution', etc are useful, because the choices are explicit items.

_**Describe the solution you'd like**_

the 'size' filter field should be able to recognize partial matches, gt and lt operands, and wildcards.  

e.g. < 1GB, > 10GB, *MB

_**Describe alternatives**_

partial matches might be enough 
(like the 'File(CSV)' filter does)

_**Additional context**_

![tdarr_sizeFilter](https://user-images.githubusercontent.com/30581164/173839206-582603db-8910-4354-a122-1fa2a23acf3e.jpg)

**Comment by HaveAGitGat** [comment]
Sure that's a good suggestion thanks.

**Comment by HaveAGitGat** [comment]
Added for next version:
![image](https://user-images.githubusercontent.com/43864057/226820464-a5bc267f-e6df-4c77-99be-94d58a75ae11.png)

**Comment by HaveAGitGat** [comment]
2.00.20 released

**Comment by wnypoker** [comment]
Less than appears to work.

Greater than does not work.

Please see images:

<img width="460" alt="greater than does not work" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/c166344c-7f85-4395-8a72-cf02b7a4b43b">
<img width="508" alt="less than works" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/2d2ea4a7-590a-4589-b76d-e1421e032113">

**Comment by HaveAGitGat** [comment]
@wnypoker are you typing GB?

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/fe02fdca-7219-47fc-9d1f-4d14ee716d4e)

**Comment by wnypoker** [comment]
Yes, I am typing the full string.  Also, I am in the Transcode: Success/Not required not the Queue, please see image.

Thank you.


<img width="494" alt="Screenshot 2023-08-07 at 1 05 57 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/3f29e80d-3176-4965-b125-bc4f5c3fb9ae">
<img width="523" alt="Screenshot 2023-08-07 at 1 05 48 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/07a941dd-936c-449d-88da-d81fb51d1740">
<img width="210" alt="Screenshot 2023-08-07 at 1 07 30 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/1559b555-ad32-44c3-b75b-742eb415de05">

**Comment by robvanhooren** [comment]
@wnypoker,is there a space between the number and the GB?Typogaphical errors courtesy of iPhone. On Aug 7, 2023, at 1:09 PM, wnypoker ***@***.***> wrote:﻿
Yes, I am typing the full string.  Also, I am in the Transcode: Success/Not required not the Queue, please see image.
Thank you.

**Comment by wnypoker** [comment]
Tried with space and without.

It works with space or no space for less than but neither works for greater than.

<img width="400" alt="Screenshot 2023-08-07 at 1 59 59 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/b598fa3f-c67c-41ad-9491-0ad0727a70a5">
<img width="415" alt="Screenshot 2023-08-07 at 1 59 42 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/614a151f-4fbf-4490-bcc5-0643f67b739a">

**Comment by HaveAGitGat** [comment]
Thanks, I've fixed this for next version. Issue not to do with spaces but with unit types of oldSize and newSize

**Comment by wnypoker** [comment]
Hi.  I updated but your fix appears to have broken search in Transcode: Success/Not in any field.
<img width="318" alt="Screenshot 2023-08-11 at 4 36 54 AM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/f87c70ad-400e-422e-858e-4570879777cd">
<img width="366" alt="Screenshot 2023-08-11 at 4 42 45 AM" src="https://github.com/HaveAGitGat/Tdarr/assets/17883450/98d9d9e8-de8b-4387-ae27-5b6464f7de3b">

**Comment by HaveAGitGat** [comment]
![89A78BC1-C7BD-47D4-A002-D1FA664E0828](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5b2ddff7-e1b7-4124-b73e-bdd8c5c66da8)
![A992DC2A-EB10-41EA-ACC8-1DBCD7025F24](https://github.com/HaveAGitGat/Tdarr/assets/43864057/1bc29eeb-3138-4fbb-a40f-6b29682591e6)
![B7030540-4B21-4778-81E4-4EB57162BE74](https://github.com/HaveAGitGat/Tdarr/assets/43864057/e153fb28-9a06-4f17-8cd6-2d8bdec658b2)
![C377F1E8-E64C-45BC-8E06-30E63B752E50](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9f6e6be3-e4da-4539-b8da-a449b742618d)
![9319E86C-E72C-4678-AD4A-394BCDCB0825](https://github.com/HaveAGitGat/Tdarr/assets/43864057/db2d1864-15b3-48b0-afda-8460ebcf6954)


Working fine from what I can see. Make sure you’re on latest version, also seems in your pic the results are still loading so you maybe have to wait a few seconds for the files to appear.

**Comment by HaveAGitGat** [comment]
If you still have an issue after that then let me know and I’ll have another look because from what can see it seems to be working fine
