### ISSUE TITLE
Remux container for specific file

### ISSUE THREAD

**Issue by Kazz3r24** [HaveAGitGat/Tdarr#649]
I'm loving what I'm seeing so far, but I don't really intend on using this as a "fire and forget" tool and instead going to be far more strict and specific with which files are getting touched.

I have a Dolby Vision/HDR10 file that has all of the specifics I am looking for, except it's in an m2ts container so the DV isn't being seen in Plex. All I want to do is remux the container to mkv so it's seen properly in Plex. So far, I've scanned in my 4K movies which went fine and I've been tinkering with plugins etc - got one that specifically remuxes the container and got the autoscan plugin for good measure (I use autoscan too). 

Now if I only want to remux the container for this file to mkv; should I set my transcode options for my 4K library to just use the remux container plugin, then queue that file for transcoding? Or am I going about this completely wrong?

All of the documentation I've seen is for configuring Tdarr essentially as fire and forget, which I don't want.

Thank you in advance!

**Comment by supersnellehenk** [comment]
For a single file it would be easier to just grab ffmpeg and run it from the CLI. Tdarr isn't designed to run on a single file.

If you want to use Tdarr, you'd have to create a directory with just that file in it.

Also, ffmpeg 4 which Tdarr still uses unless you're using the development containers will destroy the dolby vision metadata.

**Comment by supersnellehenk** [comment]
You don't need anything specific as far as I know. Just ffmpeg5. All you need to do is `ffmpeg -i "inputfile.m2ts" -map 0 -c copy "outputfile.mkv"` unless there's something weird with the file.
