### ISSUE TITLE
[i] report style on completed files.

### ISSUE THREAD

**Issue by Gumbyohson** [HaveAGitGat/Tdarr#650]
**Is your feature request related to a problem? Please describe.**
When a transcode finishes I feel like it's difficult to understand what generally happened to a file.

**Describe the solution you'd like**
The [i] information on currently running transcodes with a quick graphical rundown of the different plugins is very easy to understand and I feel that using this or offering this next to the report button on a completed file would be helpful. 
This view is really good and easy to understand
![image](https://user-images.githubusercontent.com/1866263/173968314-3131dcf7-e96e-482d-be07-8afdea3d265d.png)
vs this report which is very helpful on a technical specifics level for diagnostics but doesn't give a very clear immediate overview of what was done
![image](https://user-images.githubusercontent.com/1866263/173968796-72293c48-bf68-4470-a7d2-c607b946f978.png)

**Comment by HaveAGitGat** [comment]
Hi, yeah had this mentioned on Discord so there's a request for a clearer summary of the errors instead of having to look through each one. The job reports have an abundance of info so it's possible to track down errors but yeah not ideal/easy.

**Comment by harveybolton** [comment]
Been searching for this hoping it was an option already and came across this request, +1. Having the report is great and all as it has really technical verbose logging for when things go wrong but most of the time I just want to see at a glance what plugins were ran on a particular file and why. Having an info button next to each completed transcode (or tab in the report) would be awesome.

**Comment by HaveAGitGat** [comment]
Added as per here:
https://www.reddit.com/r/Tdarr/comments/11l70xq/comment/jbiq8cz/?context=3
https://imgur.com/a/mT3EUG2

**Comment by HaveAGitGat** [comment]
2.00.20 released
