### ISSUE TITLE
"Not required" isn't represented in the worker bar graph

### ISSUE THREAD

**Issue by Gumbyohson** [HaveAGitGat/Tdarr#651]
**Is your feature request related to a problem? Please describe.**
Worker history does not include "not required" in the bar graph

**Describe the solution you'd like**
If possible can we have an option to enable that for tracking here?
![image](https://user-images.githubusercontent.com/1866263/173969399-58b9553a-079a-4f1b-a3ae-983569c302f2.png)

**Comment by HaveAGitGat** [comment]
Hi, this is done on purpose else it would cause a few problems:

-  A lot of the time, when re-running Tdarr on your library, most items would be `notRequired`, so the other sections would be barely visible
- If you have 100,000 items and they're all notRequired, this will very quickly cause a large amount of data to be written to the statistics database to track this info.

It's possible but yeah could cause some issues.

**Comment by HaveAGitGat** [comment]
Added option for this for 2.00.20
![image](https://user-images.githubusercontent.com/43864057/223044278-95ef1d04-a716-43c6-871f-e066f1439d6a.png)
