### ISSUE TITLE
File size check incorrectly reporting 0 byte size

### ISSUE THREAD

**Issue by thespad** [HaveAGitGat/Tdarr#652]
**Describe the bug**
Post-transcode file check reporting 0 byte size (and thus failing the run), but cached file is correct size
```text
2022-06-17T14:29:57.795Z nga5gsJQt:Node[zima]:Worker[oka4-3hlR]:Error Error: New file size not within limits. New file has size 0.000 MB which is 0% of original file size: 243.636 MB. lowerBound is 40%
```

**To Reproduce**
Two-node setup, both x86_64 hosts running Docker. Remote GPU node is handling the transcode job using Intel Quicksync. Have tried with multiple Intel QSV/VAAPI plugins with the same result.

Transcode options:
![image](https://user-images.githubusercontent.com/8425502/174309706-b7cb4079-46ec-4fec-8cf5-6d466a0d0355.png)

**Expected behavior**
Size check should report correct values

**Screenshots**
![image](https://user-images.githubusercontent.com/8425502/174308482-5e772cba-f4be-4d1c-b746-28e6ffca3032.png)

(Yes, that is the correct UID/GID)

**Please provide the following information:**
```json
{
  "nodeID": "zima",
  "serverIP": "tdarr.local",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true",
  "logLevel": "INFO"
}
```
Worker job log:
[nga5gsJQt-log.txt](https://github.com/HaveAGitGat/Tdarr/files/8927953/nga5gsJQt-log.txt)

 - OS: Docker
 - Version  2.00.18

**Comment by supersnellehenk** [comment]
Have you shared the cache location between the server and node? The node can't have a local cache. The check works fine, it's usually a wrong cache setup or a permission issue.

**Comment by thespad** [comment]
I was not. I'll adjust that and retry, thanks.

**Comment by thespad** [comment]
Yup, that's sorted it, appreciate the help.
