### ISSUE TITLE
High CPU on computer hosting files when Tdarr Server is open on different PC with mapped drives

### ISSUE THREAD

**Issue by bigsteve76** [HaveAGitGat/Tdarr#654]
**Describe the bug**
I've been chasing this for months and can't figure what is happening. Tdarr is installed on my Windows 10 gaming PC (Node and Server). I've tried both mapped drives and network address folders to my file host PC (Windows 10 with Plex Server) for my directories in Tdarr. If I turn on Tdarr's server the CPU on my other PC runs up to 80-100%. I installed UnManic and it will operate with the exact same setup without any issues. CPU is 20-30% on my plex server while running Unmanic. I prefer Tdarr over Unmanic, but I can't for the life of me figure out why this is happening only with the Tdarr Server. I don't run into this with any other programs that regularly accesses the network folders. 

***update*** This is caused when 'Folder watch' is toggled "on" for the remote folder library. Toggling off the remote watch corrects this problem.

**To Reproduce**
Steps to reproduce the behavior: Start the Tdarr Server (with worker node still off)

**Expected behavior**
Processor on remote computer hosting directory folders increases to 80-100%.  High cpu usage under "System" process on remote PC.

**Screenshots**

**Server Log Files**

[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/8951175/Tdarr_Server_Log.txt)

 - OS: Windows 10 Pro (Both Machines)
 - Browser Chrome
 - Version 102.0.5005.115 (Official Build) (64-bit)

**Additional context**

**Comment by adefaria** [comment]
I'm not surprised that `Folder Watch` is wanky on Windows. I believe Tdarr uses inotify to do `Folder Watch` and https://stackoverflow.com/questions/3517460/is-there-anything-like-inotify-on-windows. You might try `Folder Watch` on and `Folder watch: Use file system events` off. That said, Tdarr should support `Folder Watch` properly when running on Windows.

**Comment by HaveAGitGat** [comment]
Tdarr uses [chokidar](https://www.npmjs.com/package/chokidar?activeTab=readme) for this which seems pretty well established.
 
Uses this config so I'm not sure there any extra options for the issue you're facing:

```
  persistent: true,
  ignoreInitial: true,
  followSymlinks: true,
  usePolling: !useFsEvents,
  interval: folderWatchScanInterval,
  binaryInterval: folderWatchScanInterval,
  awaitWriteFinish: {
    stabilityThreshold: 10000,
    pollInterval: 1000,
  },
  useFsEvents,
```

Could try lowering the poll period or disabling folder swatch and just use the hourly scan option which is less intensive: 
![image](https://user-images.githubusercontent.com/43864057/228764598-a566e27c-f209-4eed-817e-df8c5129ade3.png)
