### ISSUE TITLE
Does Tdarr copy to cache location for checking?

### ISSUE THREAD

**Issue by cat007mine** [HaveAGitGat/Tdarr#655]
Hi all.

I had issues with storage midway through my library conversion and I'd like to do a full rescan of the library so it picks up any files it has missed.

My question is, if I do a "Scan - Fresh", does this copy each file from the library to the cache folder to scan/check if it needs transcoding or can it do the scan without the need for the copy?
I don't really want to have to copy each file just to do the check - perhaps this is not the way anyway?

Cheers!

**Comment by supersnellehenk** [comment]
It does not copy them to the cache unless a plugin decided a file needed work.

For health checks it doesn't copy them at all, just checks them in place.

**Comment by cat007mine** [comment]
Thanks!
