### ISSUE TITLE
Cannot find setting

### ISSUE THREAD

**Issue by pzabel** [HaveAGitGat/Tdarr#656]
So I accidentally check the box to not remove plugins thinking that it would stop prompting me with a warning that I was removing a plugin.  Now, I cannot remove any plugins.  For the life of me, I cannot find the setting that is preventing me from removing plugins.  Where is this setting and how can I re-enable removing plugins that I will never use?

**Comment by HaveAGitGat** [comment]
> check the box to not remove plugins

Which box do you mean by this?  Do you have a screenshot? To remove plugins you use these buttons:

![image](https://user-images.githubusercontent.com/43864057/183531430-12627ed7-de59-4c64-a1b3-e0be558ec482.png)

**Comment by HaveAGitGat** [comment]
Re-open if needed thanks
