### ISSUE TITLE
Space in source name giving invalid folder error

### ISSUE THREAD

**Issue by cat007mine** [HaveAGitGat/Tdarr#657]
Hi all.

I have a few libraries I want to scan but I'm getting "Invalid Folder" errors when I try and add them.

First is:

\\192.168.1.20\New Folder

I try putting that in and I get "Invalid Folder"

I have even tried mapping the location to a local windows drive letter, T in this case.

Tried:
 T:
T:\
T
T:/

All the same.

Any ideas?

Thanks :)

**Comment by adefaria** [comment]
Maybe you could give us a clue as to exactly where you are "putting that in"?

**Comment by supersnellehenk** [comment]
Could you explain your setup a bit? Like operating system, docker/non docker, etc.

It might be related to running as admin, you should not run Tdarr as admin.

**Comment by cat007mine** [comment]
Ok so both node and server are running on a single Windows 10 machine.
The media is located on a raspberry pi shared via SMB.
The shares are mapped to drive letters on the Windows machine.
Cache folder is a local drive on the Windows machine and Tdarr doesn't have any issues with this. 

Weirdly enough I have another library set up in Tdar to: 

//192.168.20.46/raid5tv/TV Shows

It doesn't have any issues with this. 
Even if I duplicate this library and edit the path to:

//192.168.20.46/TV Shows

Tdarr complains that it is an Invalid Folder.

Ok forget all that - the permissions on the smb.conf for that share were not set correctly.

It now works.

Oops.

Closing issue.

**Comment by adefaria** [comment]
Just goes to show you - it's always something.

But it would be very helpful for you to make a post detailing what you configured wrong and how you corrected it and then marking that as the solution so that others may find the answer.

**Comment by cat007mine** [comment]
Resolution was permissions on the //192.168.20.46/TV Shows   smb share

They were: 

[TV Shows]
 comment=Raspberry Pi TV Share
 path=/mnt/usb4tb/TV Shows/
 browseable=Yes
 writeable=Yes

They are now, which is a mirror of the "Movies" share:

[TV Shows]
 comment=Raspberry Pi TV Share
 path=/mnt/usb4tb/TV Shows/
 browseable=Yes
 writeable=Yes
 only guest=no
 create mask=0777
 directory mask=0777
 public=yes
