### ISSUE TITLE
Max number of workers that limit transcodes and health checks overall for each node.

### ISSUE THREAD

**Issue by Fribb** [HaveAGitGat/Tdarr#658]
**Is your feature request related to a problem? Please describe.**
I have set my Prioritization to "Transcodes", my GPU transcodes are set to 3 and my GPU Health checks are also set to 3, I do thorough health checks. Stage Limit is 3.

Whenever the last Item in the Transcode Queue is removed and put into the staging section and transcoded the transcode queue is empty. it seems that because of this, the health checks are able to start.

This means that now I have X remaining transcode jobs that need to finish and a full stack of health checks running.
This might not be a problem when you have unlocked your GPU for unlimited streams but if your GPU doesn't support that or there are too many streams you could end up with transcoding errors.

**Describe the solution you'd like**
Adding a "max number of jobs" to each node would allow us to limit the overall number of jobs that run simultaneously. This would prevent the situation that we potentially have 6 active jobs running at the same time when your transcodes and health checks are set to 3 each.

This could be even expanded from each node to "all" as well.

**Describe alternatives you've considered**
An alternative would be to let the prioritization of transcodes and health checks include the currently running jobs.

**Comment by HaveAGitGat** [comment]
Added max GPU worker limit for 2.00.21
![image](https://user-images.githubusercontent.com/43864057/236675993-35054caa-bf32-4b86-bb76-cd7307ca2d3f.png)

![image](https://user-images.githubusercontent.com/43864057/236675933-bd97f902-ec95-4ba4-949d-8d1c15ee8d1c.png)
