### ISSUE TITLE
720p files misidentified as 1080p

### ISSUE THREAD

**Issue by thespad** [HaveAGitGat/Tdarr#659]
**Describe the bug**
Files which are 720p are misidentified as 1080p in situations where the width is greater that 1280 but less than 1920, causing issues with filters, exclusions, etc.

**To Reproduce**
Scan a file with a width greater than 1280 but less than 1920, e.g.
```
"width":1478
"height":620
```
And observe the results in the webui

**Expected behavior**
I would expect files to be identified based on at least their nearest resolution marker, although personally I would consider anything *less* than a given resolution to be classified as the step below but YMMV on that. In any case 1478*620 is much closer to being 720p than 1080p and should really be classified as such.

**Please provide the following information:**
[configs.zip](https://github.com/HaveAGitGat/Tdarr/files/9035236/configs.zip)
```
"ffProbeData":{
	  "streams":[
		    0:{
			      "index":0
			      "codec_name":"h264"
			      "codec_long_name":"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"
			      "profile":"High"
			      "codec_type":"video"
			      "codec_tag_string":"[0][0][0][0]"
			      "codec_tag":"0x0000"
			      "width":1478
			      "height":620
			      "coded_width":1478
			      "coded_height":620
			      "closed_captions":0
			      "has_b_frames":1
			      "sample_aspect_ratio":"1:1"
```
```
"file_size":3625.7779397964478
"video_resolution":"1080p"
"fileMedium":"video"
"video_codec_name":"h264"
"audio_codec_name":""
"lastPluginDetails":"none"
"processingStatus":false
```
Full scan report: [data.txt](https://github.com/HaveAGitGat/Tdarr/files/9035234/data.txt)

 - OS: Windows 10 x64
 - Version  2.00.18

**Comment by Bakeneko** [comment]
Check options => Resolution boundaries. 720p max width is set to 1408 by default, your file is therefore identified as 1080p.
