### ISSUE TITLE
Feature Request: Duplicate Library Settings

### ISSUE THREAD

**Issue by Migz93** [HaveAGitGat/Tdarr#66]
It'd be nice if we could go to an existing library and duplicate/clone it to a new library. The majority of my settings stay the same between libraries, only really the source path changes, so it'd be nice if i could configure one library, hit a clone button which creates a second library with identical settings, i can then go in and change the source folder to a new location.

Thank you

**Comment by HaveAGitGat** [comment]
Good idea 👍

**Comment by HaveAGitGat** [comment]
Added in 1.007 out later this week
