### ISSUE TITLE
FEATURE REQUEST : Delete Button on Transcode Error Table

### ISSUE THREAD

**Issue by sxb1n9** [HaveAGitGat/Tdarr#660]
Delete button on transcode error/canceled table with confirmation to delete files that are bad directly easily.   

Thanks, sxb1n9

**Comment by adefaria** [comment]
I think you need to be careful here and have two options - one that says, stop trying to transcode this file and another to say just delete the file entirely (with appropriate warnings/colors/are you really, really sure.

**Comment by HaveAGitGat** [comment]
Added for 2.00.20
