### ISSUE TITLE
Feature Request: Option to NOT record an output folder history

### ISSUE THREAD

**Issue by advorsky73** [HaveAGitGat/Tdarr#661]
**Is your feature request related to a problem? Please describe.**
I do have an automatic folder set up to be converted everything i throw into it and then the result to be moved to a specific output folder. In my case other automation systems pick up from there and the output folder gets cleaned out.
My issue is that I do have the case very often that files with the same name already been converted are again added to the pickup folder. Those are then not being converted as they are already in the output folder history.
They are the same name, though not the same content and the previous file with the same name is long gone from the output folder.
So to make this work, i have to clean out the output folder history manually all the time and restart the schedule for the files hanging in the pickup folder.

**Describe the solution you'd like**
I would like to see an option in the output folder configuration page of a library to explicitly NOT recording a file history, so converting a file with the same name multiple times is possible.

**Describe alternatives you've considered**
A plugin maybe? I have no clue if a plugin could do that...

**Additional context**

**Comment by HaveAGitGat** [comment]
Quick method could be to just run this command in a terminal every few seconds which will clear the output history.


```
curl --request POST \
     --url http://localhost:8266/api/v2/cruddb \
     --header 'Content-Type: application/json' \
     --data '
{
     "data": {
          "collection": "F2FOutputJSONDB",
          "mode": "removeAll"
     }
}
'
```

So something like this:

`while true; do date && curl --request POST --url http://localhost:8266/api/v2/cruddb --header 'Content-Type: application/json' --data '{ "data": { "collection": "F2FOutputJSONDB", "mode": "removeAll"}}' && echo; sleep 1; done`


https://tdarr.readme.io/reference/post_cruddb

**Comment by HaveAGitGat** [comment]
Added for 2.00.20
![image](https://user-images.githubusercontent.com/43864057/229032964-ca466d6d-19ed-44da-bd89-a56cf3a60eb4.png)

**Comment by HaveAGitGat** [comment]
2.00.20 released

**Comment by ChristianMalazarte** [comment]
Maybe this could be clearer. I thought it was output LOG history. Good thing I looked up what it does. No wonder my encodes were looping... FFS haha...

Maybe a clearer name like "Allow re-processing same filename."
