### ISSUE TITLE
Success/Not required not updating & Library no longer scanning for new.

### ISSUE THREAD

**Issue by TheCanadian529** [HaveAGitGat/Tdarr#665]
Version - 2.00.18
OS - Windows 11 Pro - Latest update

**Success/Not required not updating**

I've noted that it is no longer adding items that have been transcoded under Success/Not required. I've watched it transcode with no issues but it seems to not show up at all. This has happened twice. The first time I reinstall Tdarr as a fresh version and didn't have any issues till recently. 

I'm also getting "Warning: Info on queue counts" I believe this is due to a file getting stuck in the staging section but I am unsure. 

**Library no longer scanning for new**

The library is set up correctly that I know as sometimes it will transcode from this folder. I'm not sure if it's not required and that's why it's not doing it, but I'm unable to tell as the Success/Not required isn't updating. This folder is also on folder watch as well. 

Any help would be appreciated

**Comment by TheCanadian529** [comment]
I also just noticed that in my libraries setup under transcode options it's showing read error for all plugins under all of my libraries. 
![image_2022-07-16_074154534](https://user-images.githubusercontent.com/33788502/179351640-0d9b4315-036c-4967-8592-ebaa77ebfa13.png)

**Comment by TheCanadian529** [comment]
I've reinstalled and it seems to be transcoding again. The only issue is that it stopped showing things under Success/Not required not updating again. Things will transcode with no issues but won't show under Success/Not required not updating anymore.

**Comment by TheCanadian529** [comment]
So it seems to only be showing one library under Success/Not required.... Before the update it was showing them all.

**Comment by TheCanadian529** [comment]
Not it seems like Tdarr has stopped detecting new things in all other libraries besides one.

**Comment by HaveAGitGat** [comment]
> "Warning: Info on queue counts"

If you click on the yellow button it will tell you more about why this shows.

Do you have `Run an hourly Scan (Find new)`. The folder watcher sometimes doesn't work in certain situations (such as if using network drives and having file system events enabled in the scanner settings.)

**Comment by TheCanadian529** [comment]
> > "Warning: Info on queue counts"
> 
> If you click on the yellow button it will tell you more about why this shows.
> 
> Do you have `Run an hourly Scan (Find new)`. The folder watcher sometimes doesn't work in certain situations (such as if using network drives and having file system events enabled in the scanner settings.)

I don't have it to scan hourly. It is network drives. Should I host the Tdarr server on my server with the files and the Node on the computer I'm transcoding on?

**Comment by HaveAGitGat** [comment]
You can do either, but to use file system events for the folder watcher you have to have Tdarr server on the same machine as the files. Else it will use more intensive polling (i.e. scanning all files periodically to see what has changed instead of being notified by the file system of exactly what has changed). Use latest version and reopen if need thanks.
