### ISSUE TITLE
Current Version Beign Displayed

### ISSUE THREAD

**Issue by samcro1967** [HaveAGitGat/Tdarr#671]
I am currently running the `latest` image form Docker Hub which is tagged `2.00.18.2`.  The GUI ad API both show the running version as `2.00.18`.  I think maybe the GUI and API are just not currently showing the full version?  If this is the case, can the full version be added to the display in both?

**Comment by HaveAGitGat** [comment]
Latest package version is 2.00.18. 

2.00.18.2 was some minor changes to the docker image so had to bump the image tag.

**Comment by samcro1967** [comment]
Does that mean you only bumped the tag and not the version displayed in the app?

**Comment by HaveAGitGat** [comment]
Yeah you can see the app package versions here:
https://f000.backblazeb2.com/file/tdarrs/versions.json

So made a small change to the docker image and then bumped the tag else some container managers don't recognize the change if you keep the tag the same.
