### ISSUE TITLE
Check if "new transcode arguments were the exact same as the last ones", BEFORE transcoding the file

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr#674]
**Describe the bug**
Transcoded file ends up with a error "The new transcode arguments were the exact same as the last ones" after it's been fully transcoded, 

**To Reproduce**
Transcode a h265 to reduce it's size (my self made plugin calculates the new bitrate from resolution, framerate and duration, so always the same transcode arguments)
File gets pushed again to transcoding queue
File gets transcoded again with the exact same arguments as before
Once the file is fully transcoded, and CPU/GPU time wasted, it ends up with an error "The new transcode arguments were the exact same as the last ones"

**Expected behavior**
Check if transcode arguments were used in previous transcode BEFORE actually fully transcoding the file.

**Screenshots**

**Please provide the following information:**

**Additional context**

**Comment by supersnellehenk** [comment]
Could you provide a job report with this behaviour? It'll always have to transcode the file, but if the second run of the plugin generates the same arguments it stops and does not create a cache file. Or at least it should.

**Comment by ejalal** [comment]
[wZLQvvNOpj-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9403929/wZLQvvNOpj-log.txt)

**Comment by ejalal** [comment]
It transcodes everything except mjpeg, but you are right I should add a custom meta tag to mark the file as already encoded.

**Comment by HaveAGitGat** [comment]
FYI this new break plugin stack plugin is being added:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/328/files#diff-8b7534f6a2b6faaa3ca37300835c76ad5888794095b681442c4436ee15241ad3

So you can put this before your transcode plugin when trying to do h265 to h265.

I think using metadata is a better way because then you can safely requeue your files in future and not have to worry about them being transcoded again.

**Comment by ejalal** [comment]
Thank you for this, I found a workaround by adding a new tag in metadata, but it's a better idea to do this check as you did with a filter

**Comment by HaveAGitGat** [comment]
I've added a filter so that you can check tags: `Tdarr_Plugin_00td_filter_by_stream_tag`

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/388

So can use with https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/examples/force_transcode_filter_notes to force reencode of hvec (or any codec)
