### ISSUE TITLE
Set priority to Nodes

### ISSUE THREAD

**Issue by aiorus** [HaveAGitGat/Tdarr#675]
**Is your feature request related to a problem? Please describe.**
It would be great if you could prioritize the nodes to use, so you can decide to use your most powerful one most, or your most energy efficient, etc
**Describe the solution you'd like**
In the UI, each node would have a priority number. This priority number will be used when a new job comes in or from the queue. This way it can be controlled which node will be used the most, for example, use your most powerful node most to complete the jobs faster.

**Describe alternatives you've considered**
Right you you have to be constantly monitoring to turn nodes on and off to resemble this.

**Comment by HaveAGitGat** [comment]
Added for 2.00.20

**Comment by HaveAGitGat** [comment]
2.00.20 released
