### ISSUE TITLE
Docker GPU Memory Max

### ISSUE THREAD

**Issue by jpulley101** [HaveAGitGat/Tdarr#676]
**Describe the bug**
Not sure why but during encoding using my nvidia P40 its capping the ram usage on the GPU to 576MIB this GPU has 24gb

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |              
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                    0 |
| N/A   42C    P0    65W / 250W |  16936MiB / 23040MiB |     46%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7981      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      7982      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      8128      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      8141      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      8494      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      8598      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      8941      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9022      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9035      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9179      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9282      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9381      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9490      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9655      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9715      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A      9918      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A     10021      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A     10124      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A     10219      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A     10312      C   tdarr-ffmpeg                      576MiB |
|    0   N/A  N/A     10942      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11105      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11279      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11437      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11604      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11764      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     11927      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     12103      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     12264      C   tdarr-ffmpeg                      539MiB |
|    0   N/A  N/A     12413      C   tdarr-ffmpeg                      539MiB |
+-----------------------------------------------------------------------------+

I should be able to run a process without a cap 

 - OS: Ubuntu 22.04.1
 - TDARR: latest from docker

**Comment by supersnellehenk** [comment]
This is just how ffmpeg works. It won't load the entire file into RAM, just the portion it's working on. The amount used also varies between resolutions being processed, 4K can take like 1 GiB or even more.

**Comment by jpulley101** [comment]
@supersnellehenk Is there anyway to bump it up so its faster? also thanks for the fast reply!

**Comment by supersnellehenk** [comment]
There is not, since it's the NVENC chip maxing out. Assigning more RAM won't do anything, since it can't process any faster.
