### ISSUE TITLE
Tdarr to continue transcoding with file following reboot

### ISSUE THREAD

**Issue by villieb** [HaveAGitGat/Tdarr#677]
**Is your feature request related to a problem? Please describe.**
I turn off my server overnight. Files that are being transcoded are in my transcode cache. When I power on my server, 'new' files begin to transcode, leaving the partially transcoded files in the transcode cache

**Describe the solution you'd like**
Tdarr to continue transcoding files (or prioritising files in the transcode cache) so that users like me, who turn their servers off, do not see disk space being filled up by partially transcoded files

**Describe alternatives you've considered**
I could delete old files in this directory however, I am transcoding using the CPU and it takes a bit of time to transcode each file. I would rather leave these files so that when Tdarr reaches these files, transcoding continues

**Additional context**

**Comment by supersnellehenk** [comment]
FFmpeg as far as I know can't continue a transcode, so your cache file would be corrupt in that sense. Tdarr should be deleting old cache files on boot, or that has been disabled.

This *could* be possible if Tdarr would split the original file into parts and join them at the end. This is pretty complicated to get right though.

Best case scenario for you would be to use the schedule to make sure an item does not get queued within X hours of you shutting the machine down.

**Comment by villieb** [comment]
Thanks supersnellehenk - the option to delete old files cache files on boot - is this a pro feature?

**Comment by HaveAGitGat** [comment]
Not possible to continue transcoding a file like that. 2.00.20 (next version) has a better cache cleaner system which runs hourly so will clean up files not in staging section. Also has a UI for manually deleting cache files.
