### ISSUE TITLE
Add ability to run Action Plugin after accepting a transcode

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr#678]
**Is your feature request related to a problem? Please describe.**
I would like be able to add some actions to run after transcoded file being accepted (either manually or automatically), could be anything via an Action Plugin (like updating Radarr/Sonarr for example)

**Describe the solution you'd like**
Currently, when I accept a transcode, I go to every single accepted file and refresh info in Radarr, this will update the file size, and som other stuff.

**Describe alternatives you've considered**

**Additional context**

**Comment by wsegatto** [comment]
Interesting idea. 
What you could do today is to output the changed files to a different folder, then write a script that moves and overwrites the original files, then trigger the Sonarr/Radarr APIs. You'd need a "buffer folder", but if they are in the same drive, the disk activity is practically the same. Aaand avoids your Plex (or another Media Server) from indexing temp files while Tdarr is doing its magic.

**Comment by supersnellehenk** [comment]
Post-processing plugins are run after you accept a file, so you could use that for this use-case.

**Comment by ejalal** [comment]
> Post-processing plugins are run after you accept a file, so you could use that for this use-case.

Oh, didn't realize the post processing plugins run after accepting the file!
Thanks
