### ISSUE TITLE
Post-transcode healthcheck rechecks original file instead of new file if library set to use Output Folder

### ISSUE THREAD

**Issue by FreelancerJay** [HaveAGitGat/Tdarr#683]
**Describe the bug**
I currently have all my libraries set to put the completed encodes to various output folders, so that none of my originals get deleted until after I check the results, for at least while I'm learning the ins and outs of Tdarr, as well as for testing new settings and plugins.
In this setup, I noticed that after each encode, a healthcheck is triggered (which I have set to thorough), however it runs on the original file.
At first I thought maybe it was causing a filesystem change at the end or during the encode that caused Tdarr to requeue it for a healthcheck, but since it doesn't then re-add it to the Transcode queue or the "Not Needed" lists, I've come to realise that it is trying to check the completed file after the encode, since the default behaviour is to copy back replacing the original.

**To Reproduce**
Set library to copy to an output folder, keeping the original
Set library to do thorough healthchecks
Complete transcode, with at least one healthcheck worker available to do the healthcheck afterwards.

The log file for healthchecks both before and after will both reference the original file.

**Expected behavior**
Either:
- Complete the Healthcheck while the completed file is still in the TCache before copying it.
- Copy the file to either the output folder or the original library location with a different name, then perform the healthcheck (with success) on that copied file before renaming it (and removing the original if needed)

Second option probably makes more sense to me since then it will also detect damage that occurred during the copy that didn't trigger a failure at that stage. It will also help performance a little if the TCache is on a seperate storage to the source of the file being checked

**Screenshots**
Showing the "Before" and "After" filesizes of the successful transcode, as well as original file path
![Transcode before and after sizes](https://user-images.githubusercontent.com/67540736/189600565-b97c83a5-d37a-4ee9-9c30-92a5ba9ceb24.png)
The new file's filename after being copied into place
![New Filename](https://user-images.githubusercontent.com/67540736/189600556-21aa3b12-f1bc-4391-b5c9-4e5e254ee7d3.png)
The second healthcheck, running on the original file instead
![Healthcheck rechecking original file](https://user-images.githubusercontent.com/67540736/189600584-4c5f8dfd-4d2d-461d-a10e-3a62a900383f.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Debian 11.1
 - Browser Safari 14.1.2 (yes, I'm old)
 - Version 2.00.18

**Additional context**
Would also resolve #355

**Comment by ccfman2004** [comment]
I have the same issue using the Unraid Docker version.

**Comment by HaveAGitGat** [comment]
Fixed with Tdarr Flows so you can choose which file is added to db after. With this example the new file will be added and health checked:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/2bf65fc1-280f-4204-9292-bfd0482a666a)

Or you can set the original file at the end which means the original file will be kept in db and health checked:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9207ddbd-b579-49be-8295-29685cb8b037)
