### ISSUE TITLE
Add Ability to allow or disallow CPU and/or GPU worker from pulling from queue

### ISSUE THREAD

**Issue by tws101** [HaveAGitGat/Tdarr#684]
The issue occurs when we are using long plugin lists and want one specific worker CPU or GPU to be the one getting started.  (Meaning pulling the item from the queue and beginning the work)   

Example
We want to at plugin 11 look at audio bit rate and down-convert if over a certain amount, AND plugin 13 evaluates entire bit rate to determine if GPU worker will be transcoding....  If a GPU worker pulled this from QUEUE (not staging area) it will try and transcode first then hand off later to do the CPU work....  These options would avoid this problem and allow the user to determine what worker starts the process.

**Is your feature request related to a problem? Please describe.**
A    I am frustrated when  a plugin stack is setup to have CPU workers do work first and a GPU worker pulls the item from queue and tries to do all its work first.....  

**Describe the solution you'd like**
A     I want to be able to tell the queue with a on/off slider which workers may pull item from queue    Example    Under main page queue     Option (defaulted to ON) reads CPU worker may process this queue     second option (defaulted to ON) read GPU worker may process this queue            ******This does NOT affect the staging area AT ALL (and we dont want it too)  regardless of these proposed setting the stage area is NOT affected

**Describe alternatives you've considered**
A    I have considered building filters to look at stream bit rates  (stream NOT TOTAL) BUT this is not possible for MKV only for MP4 as MKV stream bit rates are not readable... and adding a remux to the stack wont help in this circumstance because if the GPU worker goes first the remux will be ignored.

So the end result would be      (if CPU can pull from queue ON    and   GPU can pull from queue OFF)
If the queue has things to pull and GPU worker was set to NO do not pull from the queue...... The available GPU worker will sit fallow until the staging area has a file that says needs GPU worker.... Then the GPU worker would get to work.

***Or the opposite of this assuming the user set it that way

**Comment by HaveAGitGat** [comment]
Added for 2.00.20

![image](https://user-images.githubusercontent.com/43864057/224813030-d6f8b2b2-6f26-4fc2-94a9-6e44970e77ec.png)

```
Process Plugins Sequentially


Disable this to allow plugins to be processed non-sequentially.

For example, if you have a CPU plugin first, then a GPU plugin, disabling this will allow a GPU worker to jump to the GPU plugin, and vice versa.
```
