### ISSUE TITLE
Tdarr node process doesn't stop when closing terminal on Windows

### ISSUE THREAD

**Issue by savvasdalkitsis** [HaveAGitGat/Tdarr#692]
**Describe the bug**
When starting the node on a windows machine using the executable, a terminal is started. Closing the terminal doesn't kill the node process, meaning that the server keeps a node registered with the node id meaning that if the user tries to start the node again using the executable, a new terminal with a new process will start that attempts to register with the same ID causing a problem.

**To Reproduce**
Start the node on windows, close the terminal, and start it again.

**Expected behavior**
The node is started up and connected to the server. What happens instead is that server rejects the node cause a node with the same ID is already registered (the first node process which is still alive).

 - OS: Server: docker on ubuntu machine. Node on windows 11
 - Version: 2.00.18

**Additional context**
I created a reddit post about this problem [here](https://www.reddit.com/r/Tdarr/comments/xswliw/tdarr_node_db_files_get_recreated_automatically/) before figuring out the issue

**Comment by savvasdalkitsis** [comment]
Note that I am using One Commander as my explorer replacement. It is possible that it could be related as I can see that the dangling tdarr node process is a child of my One Commander process. It might behave differently under explorer

**Comment by supersnellehenk** [comment]
I'm suspecting it's an issue of One Commander, could you try bare bones explorer? Haven't seen anyone else with an issue like this either.

**Comment by Rycochet** [comment]
The root issue is Tdarr I believe - I run via docker (linux for server, both linux and windows for nodes, and they have both done this) - it seems that there is no way for the server to timeout an unresponsive node to free it up again - if a node loses connection it will never get it back again, same thing if you restart the node and it doesn't send the de-register packet - when you go to the node Options panel and hit Restart it (obviously?) fails, but gives no override option to kick it the same way you can for a stream etc :-/
