### ISSUE TITLE
Transcoding with custom hevc_amf Codec isn't recognized as GPU specific Plugin (CPU Worker Required)

### ISSUE THREAD

**Issue by Seriox** [HaveAGitGat/Tdarr#693]
**Describe the bug**
My setup looks like this:
Server (Docker on Linux)

Node-1 (Windows)
- AMD GPU
- AMD CPU

Node-2 (Windows)
- Nvidia GPU
- Intel CPU

For Node-1 I've copy/pasted [this plugin](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js#L338) and modified it to use the hvec_amf Codec. When testing the Plugin with a GPU worker only on Node-1 it says "require CPU Worker". Even tough this is not wanted, as I want to use my AMD GPU for transcoding. Setting "Allow GPU workers to do CPU tasks" to "On" helps for the moment. 

If I add [Tdarr_Plugin_MC93_Migz1FFMPEG_CPU](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_Migz1FFMPEG_CPU.js) to my Plugin Stack after my custom Plugin the CPU Utilization doesn't increase. If I add it in front of my custom Plugin the GPU Utilization doens't increase. It appears that I can only use either my CPU or GPU even though I want to be able to use both.

With a second node, things get even messier. :D Node-2 tries to use my custom Plugin and just stops with "DLL amfrt64.dll failed to open" (obviously as it has no AMD CPU/GPU)

**To Reproduce**
Take [this plugin](https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js#L338), modify Line 338 "-c:v hevc_nvenc" to "-c:v hevc_amf" and try transcoding with CPU and GPU workers. (CPU Plugin mentioned above)

**Expected behavior**
I expected Tdarr to recognize my custom Plugin as a GPU specific one. So that adding GPU workers doesn't bring up "CPU worker required"

**Screenshots**
![image](https://user-images.githubusercontent.com/6906690/193479316-d6b46ed9-7cc1-42c5-a4fa-83a34f954314.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
(Worker Log) [F8Mdr9AT0-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9693737/F8Mdr9AT0-log.txt)
(Worker Log) [DzKIFysmf6-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9693739/DzKIFysmf6-log.txt)

-Worker error
Error/Warning on Node-1 when only adding GPU Workers
2022-10-02T23:46:39.999Z F8Mdr9AT0:Node[Home_PC]:Worker[IK7Z8kwXm]:[Step W03.1] [C1] Won't process: requireCPU

Error on Node-2
2022-10-02T23:43:31.691Z [hevc_amf @ 000001753a073040] DLL amfrt64.dll failed to open
2022-10-02T23:43:31.691Z Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2022-10-02T23:43:31.691Z
2022-10-02T23:43:31.691Z Conversion failed!
2022-10-02T23:43:31.691Z
2022-10-02T23:43:31.691Z
2022-10-02T23:43:31.692Z YS6rzw0JWP:Node[Developer_NB]:Worker[h5SjvnHLe]:[-error-]

 - Browser Chrome
 - Version 2.00.18

**Comment by TChilderhose** [comment]
I am running into the same issue. My `hevc_amf` plugins are seen as CPU tasks instead of GPU tasks and are erroring on my non-amd nodes.

**Comment by TChilderhose** [comment]
@Seriox I was able to find a sort of hacky work around. If you add `-metadata:s:v:0 dummy="hevc_vaapi` to the ffmpeg command, tdarr parses it as it needing a GPU. It just basically adds a dummy metadata field on the first video stream. Not great but it works for now.

**Comment by wranglatang** [comment]
@Seriox - How did you get the AMD Plugin? Im trying to use an AMD GPU on a windows machine running tdarr node and i can find that plugin on my list!?
![image](https://user-images.githubusercontent.com/30660751/206525902-b83ab845-2c12-49a1-a666-48829c76bf3b.png)

**Comment by HaveAGitGat** [comment]
Fixed the amf gpu worker in the 2.00.20 packages:

Can use these docker images:
docker pull haveagitgat/tdarr_acc:dev_2.00.20_2023_02_16T20_12_48z
docker pull haveagitgat/tdarr_node_acc:dev_2.00.20_2023_02_16T19_55_34z


Or this guide for 2.00.20 pre-release native packages:
https://docs.tdarr.io/docs/releases/changing-version/#using-a-native-package-pre-release

**Comment by HaveAGitGat** [comment]
2.00.20 released
