### ISSUE TITLE
Add ability to cancel/ignore current "Plugin" if estimated target size is bigger than expected

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr#694]
**Is your feature request related to a problem? Please describe.**
I would like to be able to cancel/ignore and move to next plugin if estimated target size produced by current plugin is bigger than expected. I know this can be managed with the "New file size check" plugin, but this is done once current plugin is 100% completed (or at the end of all plugins).

This will help save some time and processing power by interrupting the job earlier if target size will more likely to be rejected.

**Describe the solution you'd like**
- Add a target size threshold in pecentage to not exceed for the target size produced from current plugin
- Add a progress percentage to run the check: As the target file size is sometimes exagerated at the beginning of the processing, it becomes more stable over time so this second parameter will be used as trigger for check

Example
If at 25% progress of movie transcode (always current plugin), the estimated target size is bigger than 110%, cancel current plugin and move to next plugin in the transcoding queue.

**Describe alternatives you've considered**

**Additional context**

**Comment by HaveAGitGat** [comment]
Better way to approach this is to use specific bitrates when encoding so that the new file size is guaranteed to smaller than original file size. But yeah this would be a more general solution for all the different plugins.

**Comment by HaveAGitGat** [comment]
Moving this under this issue https://github.com/HaveAGitGat/Tdarr/issues/571 ty.

**Comment by HaveAGitGat** [comment]
Added with flow plugin `Compare File Size Ratio Live`. Click `Update community plugins` on the classic plugins tab or will auto update within an hour or so.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6a9d81e6-5160-462f-bccc-edb6bd737fb8)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0cffff4d-dac7-47d1-a6de-bda993f12739)

Can compare between either the estimated file size or the current file size of the output file.

```
  Compare either the estimated final size or current output size to the input size and 
  give an error if estimated final size or current size surpasses the threshold %.

  Works with 'FfmpegCommand', 'HandBrake Custom Arguments', 'Run Classic Transcode' and other flow plugins 
  that output a file.

  Can be placed anywhere before a plugin which outputs a new file.
```
