### ISSUE TITLE
Creeping ram usage on unraid

### ISSUE THREAD

**Issue by SluggishWorm** [HaveAGitGat/Tdarr#696]
**Describe the bug**
ram usage slowly creeps up, appears to creep faster when health checks are being performed. This has actually filled ram on a couple of occasions, causing server to lock up. I have processed a rather sizeable library, around 200k items. 32gb ram, usually sits at 57-60 percent upon boot. Will creep up to 100 if i let it over a period of 2-3 days. The command docker restart tdarr brings ram back down to the 60 percent range. 3 gpu workers, 3 cpu workers. I did have cpu workers up at 20 for health checks, but reducing these values doesn't appear to have made a difference

**To Reproduce**
given size of library, not really sure if reproduction if feasible

**Expected behavior**
i have  /temp mapped to the share /mnt/user/Transcode/, which is a share residing on an nvme drive so i wouldnt expect tdarr to be running too much in ram but im not a dev so maybe im completely wrong

**Please provide the following information:**
- Server config {
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.1.139",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO"
}
Node config
{
  "nodeID": "1050ti",
  "serverIP": "192.168.1.139",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true",
  "logLevel": "INFO",
  "nodeIP": "192.168.1.139",
  "nodePort": "8267"
}

 - OS: unraid 6.9.2
 - Browser chrome
 - Version 2.00.18

**Additional context**
I have used tdarr with no issues really for approx 18 months, this behaviour has only really started after my media collection "finished" transcoding, and tdarr began transcoding new files as they were acquired.
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/9737879/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/9737880/Tdarr_Node_Log.txt)
[Tdarr_Node_Log.txt.1.txt](https://github.com/HaveAGitGat/Tdarr/files/9737881/Tdarr_Node_Log.txt.1.txt)
[Tdarr_Server_Log.txt.1.txt](https://github.com/HaveAGitGat/Tdarr/files/9737882/Tdarr_Server_Log.txt.1.txt)

**Comment by MichalRybecky** [comment]
Noticed the same issue today. My Tdarr VM was unresponsive, found out that Tdarr Node slowly ramps up RAM usage, to the point where the VM basically locks up. Everything was working fine till yesterday/today for me.

**Comment by nayab9** [comment]
Seeing the same thing here, and it has only become a problem recently - it was working without any issues for months prior.

No clue what could have changed, been on the same unraid version for a long time Unraid (6.9.2) and our tdarr version has not been updated either (2.00.18)?

The community plugins in my transcode pipelines have not been updated in 10+ months - I'm at a loss as to why this could suddenly start happening...

**Comment by HaveAGitGat** [comment]
Thanks for the report. Like you say there weren’t any new Tdarr updates at that time so not sure what could have made that start happening.

Released 2.00.19 today so reopen if you still have this issue, thanks.  (Perhaps whatever changed before has now resolved itself and 2.00.18 has been working fine for you).

**Comment by Healzangels** [comment]
Hey apologies for commenting on a closed issue but sounds very similar to what I'm seeing on my unraid system. Do you happen to recall if you ran an htop what the usage/what it was showing was using the ram when tdarr was the culprit. Thanks!
