### ISSUE TITLE
Distributed encode of one file

### ISSUE THREAD

**Issue by 46620** [HaveAGitGat/Tdarr#700]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have ffmpeg split a file into multiple chunks to then be sent to different nodes to all work on one file at once. This could help with in a setup with multiple nodes spread across different networks using something like rclone to connect to the main server with limited internet and still help out.

**Describe the solution you'd like**
 - When a file is sent for transcoding, ffmpeg splits it into smaller chunks (10-15 seconds or user decided) and sent to multiple nodes.
 - After the encode job is finished, the files get merged back together into one episode.

**Describe alternatives you've considered**

**Additional context**
I saw a [comment on Reddit](https://www.reddit.com/r/ffmpeg/comments/9yoxei/comment/ea3btyl/?utm_source=share&utm_medium=web2x&context=3) about how audio can possibly by choppy if done in chunks if it's not quiet. Encoding the audio as one stream and then adding it back in when stitching the chunks together could be a solution.

**Comment by HaveAGitGat** [comment]
Will revisit in future if there are more reliable solutions
