### ISSUE TITLE
Docker Image is over 17 Gigs?

### ISSUE THREAD

**Issue by ZerkerEOD** [HaveAGitGat/Tdarr#701]
**Describe the bug**
Tdarr Node Docker image is taking 17+ gigs of space.

**To Reproduce**
Steps to reproduce the behavior: Look at docker sizes

**Expected behavior**
Not take 17gigs

**Screenshots**
![image](https://user-images.githubusercontent.com/26573385/200923176-7e419734-afcd-4663-873b-c07dd279d7cc.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.txt](https://github.com/HaveAGitGat/Tdarr/files/9974505/Tdarr_Node_Config.txt)
[Tdarr_Server_Config.txt](https://github.com/HaveAGitGat/Tdarr/files/9974507/Tdarr_Server_Config.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/9974530/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/9974533/Tdarr_Server_Log.txt)
[Tdarr_Server_Log1.txt](https://github.com/HaveAGitGat/Tdarr/files/9974537/Tdarr_Server_Log1.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
Not seeing the i on an item just at the top that details the information.

 - OS: Linux (Docker)
 - Browser Chrome
 - Version 2.00.18

**Additional context**
I do not know why my node is taking 17 gigs of space. It doesn't seem to be doing anything also.

**Comment by supersnellehenk** [comment]
The container itself is 2,5 GB, it sounds like you haven't set a transcode cache. There might be cache files in the image, I'm guessing they are under `/app/server`. 

Easiest would be to force repull the image.

**Comment by ZerkerEOD** [comment]
That would make sense. I had an issue with mounting cache directory in the beginning and I was thinking it would have fixed it self. But adding --pull --no-cache to the extra parameters in Unraid dashboard send to fix it. I'll keep an eye on it to make sure I still don't have the issue. Thanks for the help and I wanted to add the details just in case others struggle with a forced pull on Unraid as they don't make it straight forward.

Thanks @supersnellehenk for the help!
