### ISSUE TITLE
Linux: Intel Arc A380 (DG2) QSV works with FFmpeg on host but leads to transcode error with Tdarr

### ISSUE THREAD

**Issue by Deathproof76** [HaveAGitGat/Tdarr#702]
**Hello and thanks for Tdarr!**
I finally got my Arc A380 (DG2) to work with a compiled FFmpeg on Ubuntu 22.04 and wanted to try it out with Tdarr, for which I basically bought it. But when I add it as a node the transcodes error out.
I also use a 11th gen UHD730 which is working with the same settings. I tried Tdarr on host, also with the path of FFmpeg on my system and also in docker.  I also deactivated the UHD730/didn't expose it to the container.

Passed the device through to the container like this:
```
    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD129:/dev/dri/renderD128

```

I'm using the plugin `"Boosh-Transcode using QSV GPU & FFMPEG"`.
FFmpeg pipeline: `-fflags +genpts -hwaccel qsv<io> -map 0 -c:v hevc_qsv -b:v 4000k -minrate 3000k -maxrate 5000k -bufsize 10262k -preset medium  \n     -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -profile:v main10 -pix_fmt p010le` 

FFmpeg Error message: 

```
[AVHWDeviceContext @ 0x5642d6467600] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x5642d6467600] Failed to initialise VAAPI connection: 1 (operation failed).
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_qsv @ 0x5642d5637180] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument
```

Add an Arc node

**Expected behavior**
I expected it to transcode the file without error.

**Please provide the following information:**

 - OS: Ubuntu 22.04

**Additional context**
Would be super great if this could be sorted out, as the Arc is pulling 640fps trancoding 10gb 1080p h264_qsv to 1080p hevc_qsv, which makes it twice as fast as my rtx 3080.
btw: little bit of detail on how I got it to work with ffmpeg if someone may be interested https://www.reddit.com/r/Tdarr/comments/yogs95/ive_tried_the_intel_arc_a380_on_ubuntu_with_tdarr/

edit:
I got it to work with bare metal Ubuntu: https://www.reddit.com/r/Tdarr/comments/yvsq3n/got_my_intel_arc_a380_dg2_to_work_with_booshs_qsv/
I suspect that an update of the base of the docker image to jammy, also newer drivers and FFmpeg compiled to use oneVPL instead of Intel Media SDK should make it work with the docker version. Details for bare metal tutorial here: https://www.reddit.com/r/Tdarr/comments/yvsq3n/comment/iwhsezk/?utm_source=share&utm_medium=web2x&context=3

**Comment by Deathproof76** [comment]
I got my arc to work with Tdarr with Booshs Plugin! Still in the testing phase but so far it works perfect. Built the oneVPL from source and defined a compiled from source version of ffmpeg in the node and server config of baremetal. In the compiled ffmpeg i specifically used ---enable-libvpl instead of libmfx. Had to turn "enable 10bit" off in the plugin (which adds -profile:v main10 -pix_fmt p010le in the ffmpeg pipe). Else it errors out with

```
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
```

My configure for FFmpeg:

`./configure --prefix=/home/username/.local/ffmpeg --extra-cflags="-I/opt/intel/mediasdk/include" --extra-ldflags="-L/opt/intel/mediasdk/lib" --extra-ldflags="-L/opt/intel/mediasdk/plugins" --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-libvpl --enable-vdpau`

Other specifics of my setup: Disabled my IGPU to weed out confounding factors. Ubuntu 22.04 with with the newest [drm-tip Kernel](https://kernel.ubuntu.com/~kernel-ppa/mainline/drm-tip/2022-11-12/), Intel Media Driver built from source with [cmake ../media-driver -DENABLE_PRODUCTION_KMD=ON](https://github.com/intel/media-driver/wiki/Alchemist%28DG2%29-and-ATSM-Setup), [OneVPL](https://github.com/oneapi-src/oneVPL), [OneVPL-GPU](https://github.com/oneapi-src/oneVPL-intel-gpu)

It's fricking glorious 630 fps on a 1080p 10gb file h264_qsv to hevc_qsv. At least 40% faster than my 3080 with better quality!

**Comment by Deathproof76** [comment]
I'm still leaving open because I would like the docker container to work becaus of my UHD 730 IGPU. I had to disable it for the current setup to work. But the arc doesn't seem to work with my Plex container (no hw-transcode). I'll have to think on that, but it seems likely that I'll need to take that one bare metal too, or rewrite booshs plugin on the bare metal tdarr to use `ffmpeg -hwaccel qsv -hwaccel_device 1` so it'll choose the arc.

**Comment by HaveAGitGat** [comment]
Hi, thanks for the feedback. Give 2.00.19 a try (released today).

**Comment by HaveAGitGat** [comment]
Reopen if needed thanks.
