### ISSUE TITLE
Pause when Temp Folder is (X) size

### ISSUE THREAD

**Issue by Kooramah** [HaveAGitGat/Tdarr#703]
Not really a bug per se. I was just thinking about this since I have Tdarr running on Unraid. 

I have Temp folders set on Tdarr to process in the cache drive. 

It would be nice to have Tdarr pause if temp folder / cache drive hits 100G left of space.

Just a thought

**Comment by HaveAGitGat** [comment]
Sure could add notification too.

**Comment by ionred** [comment]
+1 on this. Alternatively to a minimum amount of space left, a feature to just restrict the staging/cache to a maximum size. I also am unraid but use the /dev/shm/ folder which is a RAM only folder that utilizes half of the system RAM. So being able to set a max staging size of 32gb when I have 64gb of ram would be very helpful

**Comment by HaveAGitGat** [comment]
Sorry not yet, started a flow plugin for this sitting in my drafts but haven’t completed it yet

**Comment by HaveAGitGat** [comment]
@CurlyFlow sure could be done that way. Was just doing it in a plugin so that it's easily customizable but can do either.

**Comment by HaveAGitGat** [comment]
Added for next version:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/b5141e35-5ce3-4466-b645-b3005b19a464)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6e841a70-1f4b-4126-990c-feb22d030bae)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/2ea40d98-0609-4b71-ade6-d88cf9b04c60)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0dfef53d-519c-484b-a389-96cc9d26fb58)

**Comment by HaveAGitGat** [comment]
2.21.01 released

**Comment by Kooramah** [comment]
This setting makes me happy :)
