### ISSUE TITLE
Optionally cache source file (have Nodes work on files locally)

### ISSUE THREAD

**Issue by damonbreeden** [HaveAGitGat/Tdarr#705]
The option to cache the source file locally before starting transcodes would be great, I am accessing files over a network share and unfortunately the network is the slowest part of my setup

Caching them locally before starting and working on the local file would increase my speed 10x and allow multiple passes on the same file before the final version gets returned to the server

**Comment by HaveAGitGat** [comment]
I don't think this will result in any speed increase but you can do it with Tdarr Flows, would just need to do this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/c5156507-9691-48ac-9ee8-027b4512dc30)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6fb95a93-1e72-4d3c-828a-d749b36828eb)

**Comment by HaveAGitGat** [comment]
Beta released the other day, feel free to reopen if you have any issues.

**Comment by HaveAGitGat** [comment]
2.27.01 just released adds a new node type 'unmapped' nodes, more info here: https://docs.tdarr.io/docs/nodes/nodes#unmapped
