### ISSUE TITLE
support ssh/sshfs/rsync

### ISSUE THREAD

**Issue by damonbreeden** [HaveAGitGat/Tdarr#707]
**Is your feature request related to a problem? Please describe.**
I have servers that have access to my media server only via ssh

**Describe the solution you'd like**
Support for remotely accessing the media via ssh/sshfs
This could include not only mounting the media via ssh, but also using ssh port forwarding to access the server without any other mechanism to access port 8265, and use rsync by default to transfer files to the remote node (to improve reliability & speed, especially with very large files)

**Describe alternatives you've considered**
I currently mount the remote dir using sshfs on my laptop & run both the server & node on my laptop but there's a lot of gains to be made by integrating ssh/sshfs/rsync directly into the code

**Additional context**

**Comment by agilob** [comment]
Why cant you use nfs? With nfs and permission mapping you would have less problems than on ssh when uuids between systems don't match.

**Comment by damonbreeden** [comment]
I abandoned this idea but I don’t think nfs would work bc the two servers are at different sites

Could do a vpn I guess.

**Comment by HaveAGitGat** [comment]
Any remote mounting should be done outside of Tdarr, seems very niche use case to have this done in the application itself.

**Comment by HaveAGitGat** [comment]
Could be interesting but the application would probably need to be designed from the ground up with this in mind. Not sure the dependencies would support it either.
