### ISSUE TITLE
FFMPEG Video bitrate lost in result file when transcoding Audio only

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr#710]
**Describe the bug**
I first started reencoding audio only of all my movies from anything to aac (64k per channel)... well the problem with this is that I lost Video bitrate info (using "-c copy  -map 0:v"). Also ordered streams to have video first, then audio, then subs.

Now I'm trying to reencode video to H265, but can't determine video birate from file.ffProbeData.streams[0].bit_rate (index 0 being video stream)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Docker
- v 2.00.18

**Additional context**

**Comment by HaveAGitGat** [comment]
Due to FFmpeg not tagging the metadata when it creates the new file. I assume this is fixed by running mkvpropedit on the new file, planning on having that in next version.

**Comment by jerrodlv** [comment]
> Due to FFmpeg not tagging the metadata when it creates the new file. I assume this is fixed by running mkvpropedit on the new file, planning on having that in next version.

Is this a known issue, ffmpeg not tagging metadata? I am having an issue where the final plugin step of my transcode steps (a file check step) fails seemingly due to the file not having metadata.

Windows node, ffmpeg nvenc transcode from a communty plugin. I don't see any plugins to run mkvpropedit, do i need to make my own?

**Comment by Sigri44** [comment]
Same here.

**Comment by HaveAGitGat** [comment]
@jerrodlv yes it's a known issue, working on a solution

**Comment by HaveAGitGat** [comment]
2.00.19 runs mkvpropedit between plugin cycles so should be resolved. Make sure to set `mkvpropeditPath` in Tdarr_Node_Config.json if not using Docker image
