### ISSUE TITLE
Spelling of a word - /#/stats - Stream Stats

### ISSUE THREAD

**Issue by tomaspland** [HaveAGitGat/Tdarr#711]
**Describe the bug**
Minor spelling mistake on /#/stats under Stream Stats, word shown as "Higest", think you mean "Highest"

**To Reproduce**
version 2.00.18 Pro
Goto http://host:port/#/stats
Under Stream Stats block, column title reads Higest

**Expected behavior**
Correct spelling should be Highest

**Screenshots**
![image](https://user-images.githubusercontent.com/44840487/208553513-5f22007e-0ee7-4df4-bfa1-89f1a23b9944.png)

**Please provide the following information:**
- Config files 
Tdarr_Server_Config.json:-
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO"
}

Tdarr_Node_Config.json:-
{
  "nodeID": "MyInternalNode",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "platform_arch": "linux_x64_docker_true",
  "logLevel": "INFO"
}

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/10263716/Tdarr_Server_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom] - N/A

 - OS: [e.g. Linux] Ubuntu 22.04.1LTS running Docker 20.10.21 (API: 1.41)
 - Browser [e.g. chrome, safari] Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
 - Version [e.g. 2.00.00] 2.00.18 Pro

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks, is fixed for .19
