### ISSUE TITLE
Latest dev build of the Tdarr docker image in Unraid is not working

### ISSUE THREAD

**Issue by thespinmaster** [HaveAGitGat/Tdarr#712]
**Describe the bug**
Version:          2.00.19 
Repository:    haveagitgat/tdarr_acc:dev

Updated my Tdarr docker image on Unraid.
Went to the Help tab in Tdar to run ffmpeg to check the version. (To make sure Tdarr still has the newer version of ffmpeg that does not trash Dolby Vision data)

**To Reproduce**
In Tdarr, Click on the the Tools tab and then click the Run button for FFmpeg

**Result**
tdarr-ffmpeg: symbol lookup error: tdarr-ffmpeg: undefined symbol: vaSyncBuffer

**Expected behavior**
FFmpeg runs without errors

**Comment by HaveAGitGat** [comment]
Was doing some updates last night but seems some things have changed around with ffmpeg/intel setup so the old stuff isn't working. Will look into it.

**Comment by HaveAGitGat** [comment]
This should now be working, I've added it to `haveagitgat/tdarr_acc:2.00.19` and  `haveagitgat/tdarr_acc:latest` so you don't have to use the dev container. Same for nodes.

**Comment by thespinmaster** [comment]
Great, thank you very much. Can confirm all is working. Closed
