### ISSUE TITLE
MediaInfo failing

### ISSUE THREAD

**Issue by cjmanca** [HaveAGitGat/Tdarr#713]
**Describe the bug**
MediaInfo is failing for every file with the latest dev version:
```
"scannerReads":{
"ffProbeRead":"success"
"exiftoolRead":"success"
"mediaInfoRead":"{}"
"closedCaptionRead":"success"
}
```

**To Reproduce**
Put checkmark in "MediaInfo" in library settings and click any filename.

**Expected behavior**
MediaInfo output.

 - OS: Unraid
 - Browser chrome
 - Version 2.00.19 (docker dev channel)

**Comment by HaveAGitGat** [comment]
Sorry this was due to a mediaInfo bug, `dev` should now be working. Will add the timestamp to the dev tag in future so it's easier to jump between dev versions.

**Comment by HaveAGitGat** [comment]
2.00.19 released
