### ISSUE TITLE
TdarrCacheFile isn't being found

### ISSUE THREAD

**Issue by JoshLoecker** [HaveAGitGat/Tdarr#715]
**Describe the bug**
When running any transcoding, an error occurs with the message
```
[2022-12-23T15:58:10.568] [WARN] Tdarr_Node - Tdarr ALERT: NO OUTPUT FILE PRODUCED:
/media/.tdarr_transcode/New Girl (2011) - S03E01 - All In [WEBRip-1080p][AAC 5.1][x265]-RARBG-TdarrCacheFile-Y_aaj8FnZ0.mkv
```

The file that does exist in this location is named: `'New Girl (2011) - S03E01 - All In [WEBRip-1080p][AAC 5.1][x265]-RARBG-TdarrCacheFile-B1aDs2MVfV.mp4'`. The section after the `TdarrCacheFile` is what is different

I don't have any additional nodes configured, I'm using the one that is "preinstalled" with the server docker setup

**To Reproduce**
1. Create a library with the following plugins (in this order) using their default settings:
- Migz-Remove image formats from file
- Tdarr_Plugin_Img1_Reorder Streams
- Add audio stream codec
- Standardise audio stream codecs
- Set Default Audio Stream (Based On Channel Count)
- 2 Pass Loudnorm Volume Normalisation
- Migz-Clean title metadata

2. Start processing
3. View the error

**Expected behavior**
The transcode should finish successfully

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.json](https://pastebin.com/Yubet7zT)
[Tdarr_Server_Config.json](https://pastebin.com/Uy32sVza)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://pastebin.com/yb6pz081)
[Tdarr_Server_Log.txt](https://pastebin.com/WcZmqZZy)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
I get a blank screen when I click the "i" button. I've tried firefox and chrome, and both show a blank screen
Here is a screenshot:
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/47901540/209409382-62a492cb-2e6f-4fa4-b21f-9b9ce624d1c2.png">

 - OS: Linux (docker install)
 - Browser: Chrome
 - Version: 2.00.19

Thanks for any help!

**Comment by HaveAGitGat** [comment]
Please post the full job report if you can. Can access it using the little file icon
![image](https://user-images.githubusercontent.com/43864057/215959502-c1f1162d-979d-4781-9583-91a6a604eaa6.png)

**Comment by Nova849** [comment]
![Tdarr issue](https://user-images.githubusercontent.com/123332898/218371331-229b6806-f6ae-4733-8223-4d923b05fa46.JPG)

I am having the same issue. I am using a custom plugin to do Av1 CPU transcoding. It works great on my Unraid server with the Tdarr server and Tdarr node dockers running 2.00.19 (thank you for updating Handbrake to 1.6 btw). I know I've had this working in the past on this machine to do 264->265 and just to make sure I went back and followed spaceinvaderone's video again which got me up and running sometime last year. No dice this time. I've tried two options in the pathtranslators for the transcode folder. "X:/" (mapped to "\\UNRAID\transcode") and  "//UNRAID/transcode". The process hits step three which is my Av1 plugin, gives me this error, and then tries the next file and the process repeats.

**Comment by HaveAGitGat** [comment]
@Nova849 please post full job report if possible thanks
https://docs.tdarr.io/docs/other/job-reports/

**Comment by HaveAGitGat** [comment]
Reopen if needed ty

**Comment by JoshLoecker** [comment]
Reopening, as I've forgotten about this, here is a job report! It seems to be repeatedly processing the same file. I've let it run twice, and then downloaded the report

[Gh5vlzspc-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11014156/Gh5vlzspc-log.txt)

**Comment by HaveAGitGat** [comment]
@JoshLoecker please post full job report, yours is only up to 

```
2023-03-19T21:23:27.265Z Gh5vlzspc:Node[internalNode]:Worker[RLb2zvqSd]:Subworker:Receiving transcode settings
2023-03-19T21:23:27.265Z Gh5vlzspc:Node[internalNode]:Worker[RLb2zvqSd]:Subworker:Running CLI
```

**Comment by JoshLoecker** [comment]
Ok, I've let the job run for a while and steps are repeated during processing. This is the name of each job:

```
[Step S01] [2.00.19] Server relay initialising job
Node[internalNode]: [Step N01] Node relay received job
Node[internalNode]:Worker[DZXTpRNbB]: [Step W01] Received file, original: /mnt/media/conversion/working/testing/Lost Treasures of Egypt (2019) - S01E02 -
Hunt for the Pyramid Tomb [WEBDL-1080p] [EAC3 5.1] [×264]-TrollHD.mkv
Node[internalNode]:Worker [DZXTpRNbB]:[Step W02] [C1] Running pre-process file
Node [internalNode]: Worker[DZXTpRNbB]: [Step W03] [C1] Analysing file running plugins
Node[internalNode]:Worker [DZXTpRNbB]:[Step W04] [C1] Preparing command
Node [internalNode]:Worker[DZXTpRNbB]: [Step W05] [C1] Launching subworker
Node[internalNode]:Worker [DZXTpRNbB]: [Step W06] [C1] Worker [-success-]
Node [internalNode]:Worker[DZXTpRNbB]: [Step W02] [C2] Running pre-process file
Node[internalNode] :Worker [DZXTpRNbB]: [Step W03] [C2] Analysing file - running plugins
Node[internalNode] :Worker [DZXTpRNbB]:[Step W04] [C2] Preparing command
Node[internalNode]:Worker[DZXTpRNbB]: [Step W05] [C2] Launching subworker
Node [internalNode]:Worker [DZXTpRNbB]: [Step W06] [C2] Worker [-success-]
Node[internalNode]:Worker[DZXTpRNbB]:[Step W02] [C3] Running pre-process file
Node[internalNode]:Worker[DZXTpRNbB]: [Step W03] [C3] Analysing file - running plugins
Node[internalNode]:Worker [DZXTpRNbB]:[Step W04] [C3] Preparing command
Node[internalNode] :Worker[DZXTpRNbB]: [Step W05] [C3] Launching subworker
Node[internalNode]:Worker[DZXTpRNbB]: [Step W06] [C3] Worker [-success-]
Node[internalNode]:Worker[DZXTpRNbB]: [Step W02] [C4] Running pre-process file
Node [internalNode]:Worker [DZXTpRNbB]: [Step W03] [C4] Analysing file - running plugins
Node [internalNode]: Worker[DZXTpRNbB]: [Step W04] [C4] Preparing command
Node [internalNode] :Worker [DZXTpRNbB]: [Step W05] [C4] Launching subworker
Node[internalNode]:Worker[DZXTpRNbB]: [Step W06] [C4] Worker [-success-]
```

And then the process repeats from "`Running pre-process file`"

Here's the jog report!

[RzLnbngOhm-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11046044/RzLnbngOhm-log.txt)

**Comment by Nova849** [comment]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11073254/Tdarr_Node_Log.txt)

Here is what I believe you are asking for? These are the logs from the PC I am trying to get it working on. Works great on the unraid machine.

**Comment by PatientXero** [comment]
This shouldn't be closed. It's happening to me as well on a fresh install of Ubuntu Server 22.04. All the permissions are set correctly. There is nothing to block Tdarr from accessing my cache path. Same problem that is happening to others on bare Ubuntu installs.

**Comment by HaveAGitGat** [comment]
@JoshLoecker seems a plug-in conflict. You have a plugin which is adding streams and then a plugin which is removing streams so it’s just looping. So would need to reconfigure. Tdarr plugins are cyclic: https://docs.tdarr.io/docs/plugins/basics

@PatientXero this above issue isn’t a cachefile error so post your job report if you’re having a problem.

**Comment by HaveAGitGat** [comment]
@Nova849 enable full CLI output on the Tdarr tab but from the end of the log it seems handbrake does not support the handbrake preset you’re trying to use.

**Comment by PatientXero** [comment]
I'll stick to manually encoding with Handbrake until this issue has been resolved. It is the exact same issue that @JoshLoecker is having.

**Comment by HaveAGitGat** [comment]
@PatientXero I've had a look through the log here again.

The issue is because of these 2 plugins:

`Tdarr_Plugin_00td_action_add_audio_stream_codec`
`Tdarr_Plugin_00td_action_keep_one_audio_stream`

So one is adding an audio stream, and then the other is removing it and only keeping one, so it's just looping.

Which plugins are you using?

**Comment by Nova849** [comment]
@HaveAGitGat My issue was resolved in another ticket. I thought this one died. Handbrake on the Node wasn't updated to match that of the server yet. The latest update resolved all my issues. Thank you.

**Comment by PatientXero** [comment]
> @HaveAGitGat My issue was resolved in another ticket. I thought this one died. Handbrake on the Node wasn't updated to match that of the server yet. The latest update resolved all my issues. Thank you.

Same. Had to run sudo apt install handbrake-cli to correct the Handbrake detection issue.
As for ffmpeg, I edited the Tdarr Node json config file to point ffmpeg to /usr/lib/ffmpeg
Also note that libnvidia-encode-525 (Ubuntu 22.04 repo version) has to be installed to resolve the libnvidia-encode.so.1 errors coming from ffmpeg.
