### ISSUE TITLE
Any? Guide on How To Update FFMPEG(preferably from source) on Tdarr-Unraid

### ISSUE THREAD

**Issue by adamgwaps** [HaveAGitGat/Tdarr#716]
I managed to passtrough Intel Arc to unraid-tdarr-docker however the built in ffmpeg seems to be outdated and need the latest build for it to work, which what i did on Windows-Tdarr and upon updating FFMPEG on Windows it worked flawlessly and gloriously 600fps average. So i am excited to make it work on unraid and if i do i might buy two more intel arc cards.

**Comment by HaveAGitGat** [comment]
2.00.19 uses updated FFmpeg, just doing some testing on it. Can use it atm with `docker pull haveagitgat/tdarr_acc:dev`

**Comment by HaveAGitGat** [comment]
2.00.19 released on Sunday so should now be working. Post here https://github.com/HaveAGitGat/Tdarr/issues/702 if any issues. Thanks.
