### ISSUE TITLE
video from 5d mark iv 4k MJPEG only output audio file. any suggestion?

### ISSUE THREAD

**Issue by idnawsi** [HaveAGitGat/Tdarr#717]
when i tried transcode the 4k MJPEG file from Canon 5D Mark IV, the output file is only audio, i am using Migz ffmpeg GPU

**Comment by HaveAGitGat** [comment]
Please post the job report on the item using the file icon: 
![image](https://user-images.githubusercontent.com/43864057/215959903-758fbdf3-d306-4eec-a5f5-4d21e70df8a8.png)
