### ISSUE TITLE
Support for "Deep Link Hyper Encode" for multi-Intel-CPU/GPU systems

### ISSUE THREAD

**Issue by millercentral** [HaveAGitGat/Tdarr#718]
**Is your feature request related to a problem? Please describe.**
For Intel-CPU systems that also have an Intel Arc GPU, this would be an opportunity to team the integrated GPU with the discrete GPU for faster encoding.

**Describe the solution you'd like**
Intel recently introduced a concept they call "Deep Link Hyper Encode" that increases encoding performance by combining multiple hardware resources on a system. It uses the OneVPL media SDK. It would be cool if this is something Tdarr could support on systems that meet the hardware requirements. Developer implementation information linked below.

**Describe alternatives you've considered**

**Additional context**
Here is the developer guide for the feature:
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/doc/HyperEncode_FeatureDeveloperGuide.md

...and here is some more general information about the technology:
https://www.intel.com/content/www/us/en/architecture-and-technology/adaptix/deep-link.html

**Comment by HaveAGitGat** [comment]
Seems Intel has added the option of this being used directly in FFmpeg https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html 

But is still quite new so will wait for Jellyfin ffmpeg to incorporate it. Seems you can try it now if you build from FFmpeg master:
https://github.com/FFmpeg/FFmpeg

Would then just need to set the `ffmpegPath` option in `Tdarr_Node_Config.json`
