### ISSUE TITLE
Topaz Video AI integration

### ISSUE THREAD

**Issue by BobOkisama** [HaveAGitGat/Tdarr#720]
The latest Topaz Video AI 3.x version now have an API you can use to do ffmpeg transcodes with AI from cli. Would love to see that integrated into tdarr.

**Comment by HaveAGitGat** [comment]
Looks interesting thanks

**Comment by HaveAGitGat** [comment]
Other issue is Topaz doesn't seem to support Linux which is what most people run Tdarr on.

You can create a custom flow plugin to run this if you like, copy this folder into the local flow plugins folder and then rename it and change the cli path from mkvpropedit to the topaz one and add the transcode arguments you need:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/tools/runMkvPropEdit/1.0.0/index.ts

**Comment by HaveAGitGat** [comment]
Added update here (https://github.com/HaveAGitGat/Tdarr/issues/498) on running custom commands.
