### ISSUE TITLE
Tdarr server and node on windows 11, "location is not avaiable" after a few transcodes

### ISSUE THREAD

**Issue by webeliphant** [HaveAGitGat/Tdarr#721]
**Describe the bug**
I run Tdarr server and node on the same W11 machine. Transcoding goes fine. But after a while I get alot of failed transcodes. When I check my file explorer. I see that my network shares are not accessible anymore. When I close tdarr, I can acces them again. 
When they are not accessible on my machine. I can still acces them on a different pc in the same network:
![image](https://user-images.githubusercontent.com/121857397/210326228-ad8f6d7d-243f-4b0d-8af4-8405b08540b8.png)

**To Reproduce**
Run tdarr on W11 and server and node on same machine.
Let them run for a while. 
Network shares become not accesssible anymore.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/121857397/210326418-b24a3ef4-098c-4790-81f8-82e065c62090.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
node: https://pastebin.com/daDsVznB
server: https://pastebin.com/iLSagBKe
- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
- https://pastebin.com/ukVP8JYS

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows 11
 - Browser Firefox
 - Version 2.00.18

**Additional context**

**Comment by webeliphant** [comment]
![image](https://user-images.githubusercontent.com/121857397/210428538-6ad605bf-baaf-4dcc-badd-4aadd8989fd3.png)

**Comment by HaveAGitGat** [comment]
When this happened do you remember if lots of Tdarr processes were running (e.g. in task manager)?

**Comment by HaveAGitGat** [comment]
Reopen if need thanks

**Comment by Library7875** [comment]
I am having this exact error, though I'm not running a node on this machine, only a server.

I noticed 6 tdarr services in task manager.

**Comment by fefsf** [comment]
I just started to have this same error for no reason that i can think of. yes, i have a lof (5 right now) of Tdarr server run time processes and a lot more when it is scanning for new files. 

![Image](https://github.com/user-attachments/assets/3ce50ab0-f758-4613-a1e3-39513affce51)
