### ISSUE TITLE
Unable to start Tdarr Docker container on Synology

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#722]
**Describe the bug**

I run my Tdarr server on Synology in a Docker container. Sometimes the Synology needs to be restarted or, like recently, a power outage caused the Synology to be rebooted. When it comes back up all of my Docker containers get restarted and work (meaning their web interfaces work) except Tdarr. Bopping into the Docker container and running `top` I see:

```
top - 20:49:03 up 25 days,  9:56,  0 users,  load average: 0.73, 1.02, 2.65
Tasks:   8 total,   1 running,   7 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.7 us,  2.7 sy,  0.0 ni, 88.0 id,  4.3 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :   7802.1 total,    308.5 free,   3803.6 used,   3690.1 buff/cache
MiB Swap:   6731.9 total,   4618.2 free,   2113.7 used.   3666.1 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                   
  357 abc       20   0 2007884 844156  22084 S   0.3  10.6   9:39.50 Tdarr_Server                              
    1 root      20   0     200      0      0 S   0.0   0.0   0:00.02 s6-svscan                                 
   39 root      20   0     200      0      0 S   0.0   0.0   0:00.00 s6-supervise                              
  351 root      20   0     200     64     44 S   0.0   0.0   0:02.78 s6-supervise                              
  352 root      20   0     200      0      0 S   0.0   0.0   0:00.00 s6-supervise                              
  416 root      20   0    7108   3524   3308 S   0.0   0.0   0:00.01 bash                                      
  442 root      20   0    9116   3072   2564 R   0.0   0.0   0:00.62 top                                       
 3538 abc       20   0 1048744 225044  22560 S   0.0   2.8   0:24.03 Tdarr_Server
```

For a while, the Tdarr_Server process is hogging the CPU but it eventually settles down. However, the web interface does not work. 

I have instead, a bash script that restarts the Tdarr server for me. It starts by stopping the old container if running, removing it and then doing a `docker run`

```
Jupiter:more /System/bin/tdarr_server 
#!/bin/bash
mediaFolder=/Videos
host=$(hostname)

# Stop any running containers
docker stop tdarr_server > /dev/null 2>&1

# Remove any old docker container
docker container rm -f tdarr_server > /dev/null 2>&1

# Recreate new docker container
docker run -d \
  -v $mediaFolder:$mediaFolder \
  -v /System/Cache/:/tmp \
  -v /System/Config/tdarr/:/app/server \
  -v /System/Config/tdarr/:/app/configs \
  -v /System/Config/tdarr/:/app/logs \
  -e "serverIP=0.0.0.0" \
  -e "webUIPort=8265" \
  -e "serverPort=8266" \
  -e "TZ=America/Los_Angeles" \
  --network="bridge" \
  -p 8265:8265 \
  -p 8266:8266 \
  -e PUID=1000 \
  -e PGID=1000 \
  --log-opt max-size=10m \
  --log-opt max-file=5 \
  --name tdarr_server \
  haveagitgat/tdarr

# With the container created start tdarr_server
echo "Starting tdarr_server on $host"
docker start tdarr_server

# This is needed to set the restart option
docker update --restart=unless-stopped tdarr_server
Jupiter:
```

I also reported a problem about Tdarr taking a long time to start up because it's doing a huge `chown` in https://github.com/HaveAGitGat/Tdarr/issues/609. That has not been fixed. I think I know why this is happening. Because I remove the old container and do a `docker run` the Docker container is new. Tdarr wants to make sure the database that it keeps as to which videos have been processed and which haven't is owned by the proper user so it does a `chown` on the whole tree, which takes a long time since I have so many videos processed and thus a big database. I see this as useless as the files already have the correct ownership. Perhaps an envvar can be used to tell Tdarr "Don't worry about the ownership stuff - that's already done".

Anyway, it seems like if I do not remove the Docker container and do `docker start` then Tdarr will start, busy the Tdarr_Server process (doing what I don't know), and then never get around to establishing the web interface. And if I do remove the Docker container and do a `docker run` then I'll need to wait, sometimes upwards of 20 minutes, for the `chown` to finish and for the web interface to come up.

**To Reproduce**

1. Set up the Tdarr server to run on Synology
2. Restart Synology

**Expected behavior**

I expect the Tdarr server container to fire up and present the web interface quickly and not need to be recreated (with the long `chown` problem).

**Please provide the following information:**

[tdarr_logs_and_config.zip](https://github.com/HaveAGitGat/Tdarr/files/10353951/tdarr_logs_and_config.zip)

 - OS:  Synology DSM 7.1

**Comment by HaveAGitGat** [comment]
Yeah the chown is not an ideal solution, was added as more of a brute force fix for people having permissions issues etc. Will look into a better solution.

**Comment by adefaria** [comment]
How about implementing an envvar, say "PERFORM_CHOWN" that the user can set to say skip it (default do it)?

**Comment by HaveAGitGat** [comment]
How about `CHOWN_ON_STARTUP`

So updated code would be

```sh
if [ "$CHOWN_ON_STARTUP" = false ] ; then
    echo "chown: CHOWN_ON_STARTUP = false, skipping startup chown"
elif [ -f /firstRun ] ; then
    echo "chown: Not first run, no need to chown"
elif [ ! -f /firstRun ] ; then
    echo "chown: First run and CHOWN_ON_START != false, chowning /app, ffmpeg and ffprobe, this may take some time"
    chown -R ${PUID}:${PGID} /app
    chmod a+rwx -R /app/Tdarr_Node/assets/{app/fileScanner/,app/ffmpeg/}
    chmod a+rwx -R /app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
    touch /firstRun
fi
```

Added to the dev container, will be available in 30 mins so I can check it

**Comment by HaveAGitGat** [comment]
Seems to be working fine 
![image](https://user-images.githubusercontent.com/43864057/216689248-396b9d87-9efc-44e3-a8e6-762d3b912aff.png)

**Comment by adefaria** [comment]
Thanks for working on this. I'm still verifying it. Hmm... Didn't seem to work. I removed the container and image and pulled again. When I ran it however the chown was running even thought I added a `-e CHOWN_ON_STARTUP=false` to my docker run command:

```
Jupiter:docker exec -it tdarr_server bash
root@23ced12ca8cd:/# echo $CHOWN_ON_STARTUP
false
root@23ced12ca8cd:/# ps -ef | grep chown
root       260   247  3 11:31 ?        00:00:08 chown -R 1000:1000 /app
root       281   273  0 11:35 pts/0    00:00:00 grep chown
root@23ced12ca8cd:/# 
```
Looking at the logs I see:

```
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 01-setup-perms: executing... 
usermod: no changes

User uid:    1000
User gid:    1000
-------------------------------------

Chowning the appassets, this may take some time
```
That last line doesn't match the `echo` you have above so perhaps I grabbed it too soon? You said 30 minutes and your post was more than 30 minutes ago so I thought it was safe to proceed. Tdarr server reports version 2.00.18. 

In the meantime, I think you posted this fix to the wrong issue. I think it should be on https://github.com/HaveAGitGat/Tdarr/issues/609. 

This issue is regarding the Tdarr server not starting when my Synology reboots. This script above will restart it, but in Synology, there is a Docker GUI app

![2023-02-03@11:34:10](https://user-images.githubusercontent.com/2692127/216694437-4acb0bce-c4e7-4c95-9c75-ace564c252ec.jpg)

And Synology correctly handles the restarting of all my docker containers, 'cept Tdarr_server. The container starts, and there is no `chown` but the web interface never comes up. This may be because of my script that uses docker run instead of configuring the docker container thru the Synology Docker GUI app. Why is this?

Another way this problem can be demonstrated is to start tdarr_server with my script using docker run then go to the Synology Docker GUI app and stop the container. If you then restart it starts but again you never get to the web interface. This time the `/firstRun` file was present from the previous run and the `chown` was skipped now but again, the web interface does not come up. I've attached the log.

[tdarr_server_docker.log](https://github.com/HaveAGitGat/Tdarr/files/10582406/tdarr_server_docker.log)

**Comment by adefaria** [comment]
I updated Tdarr Server today and it complained that my Tdarr Node was not the same version. So I updated that. Now the Tdarr Node is `chown`'ing for like 50 minutes. The Tdarr Node never used to do this `chown`'ing thing or at least it didn't take an hour to get it done.

Seems to me that the `chown`'ing is `chown`'ing way too many files and perhaps I could trim this a bit. For example, there are like 120605 directories under Tdarr/DB2/JobReports. I'm sure many of them are old and not needed. Can I just remove them? What else under Tdarr can I remove? I'd like to keep what's necessary to have meaningful stats and whatever other history is required but perhaps remove the junk to speed things up.

Also, can the start-up sequence not block on the chown but rather have it `chown`'ing in the background? I assume the chown is to avoid things like permission problems but the chances are high that the chown will not be changing any ownership of any file it hasn't chown'ed last time.

**Comment by HaveAGitGat** [comment]
Yeah you can just delete them. There's an option to set the max size on the 'Options' tab.

The chown was changed from 

```
if [ ! -f /firstRun ]; then
    echo "Chowning the appassets, this may take some time"
    chown -R ${PUID}:${PGID} /app
    chmod a+rwx -R /app/Tdarr_Node/assets/{app/fileScanner/,app/ffmpeg/}
    chmod a+rwx -R /app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
    touch /firstRun
fi
```

to

```
if [ "$CHOWN_ON_STARTUP" = false ] ; then
    echo "chown: CHOWN_ON_STARTUP = false, skipping startup chown"
elif [ -f /firstRun ] ; then
    echo "chown: Not first run, no need to chown"
elif [ ! -f /firstRun ] ; then
    echo "chown: First run and CHOWN_ON_START != false, chowning /app, ffmpeg and ffprobe, this may take some time"
    chown -R ${PUID}:${PGID} /app
    chmod a+rwx -R /app/Tdarr_Node/assets/{app/fileScanner/,app/ffmpeg/}
    chmod a+rwx -R /app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
    touch /firstRun
fi
```

So not sure about the Node. Would depend how you've set up the Node as if it's mapped to the server data then yes it will chown the server data on startup.

**Comment by adefaria** [comment]
Is the new chown thing in the latest now?

I see `Total job history size limit (GB)` is set to 10 yet:

```
Jupiter:du -sh JobReports
11G	JobReports
Jupiter:
```
Perhaps just a rounding error?

Regarding node - I changed nothing in this, save getting the newer version. Maybe the newer version removed `/firstRun`? My node runs on my Ubuntu Desktop because it has better GPUs. Access to the files on the Synology NAS (Jupiter) is accomplished via NFS. Essentially `/volume1/Media/Videos` on the NAS is NFS mounted onto `/Videos` on my desktop and the Docker container maps (`-v /Videos:/Videos). I then configure Tdarr Node to watch /Videos.

**Comment by HaveAGitGat** [comment]
Reopen if you still have original issue on 2.00.22 thanks
