### ISSUE TITLE
[Documentation] tdarr_inform

### ISSUE THREAD

**Issue by deathbybandaid** [HaveAGitGat/Tdarr#723]
I wrote a utility for Sonarr and Radarr to inform Tdarr of new/changed/deleted files without relying on filesystem events or frequent disk scanning.

It would be nice for this tool to appear somewhere on the tdarr documentation, so others can find and make use of it more easily

https://github.com/deathbybandaid/tdarr_inform

**Comment by HaveAGitGat** [comment]
Thanks I'll create a 3rd party utils part in the docs for things like this :)

**Comment by HaveAGitGat** [comment]
Thanks, added here:

https://docs.tdarr.io/docs/tools-and-integrations
