### ISSUE TITLE
Timed out nodes often cannot re-register

### ISSUE THREAD

**Issue by UndercoverPervert** [HaveAGitGat/Tdarr#726]
**Describe the bug**
When a node times out, it sometimes remains listed, and when the node attempts to re-register itself, it fails, stating that the name is already taken,

**To Reproduce**
In my case it happens when I overwhelm the server's gigabit connection or when my dram-less ssds fill system memory.

**Expected behavior**
The "already registered" node should be pinged to verify that it's responsive before declining a node registering with the same name, if the one that already exists is not responsive, the registration request should go through. It should also be aware that a node is unresponsive when the system stats can no longer be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/32446791/211995742-7f98e65a-1266-4c83-889a-b996f98b81e7.png)
![image](https://user-images.githubusercontent.com/32446791/211995841-ca676b0d-1b09-4dd9-bcff-b8ba44ad403b.png)

I'll provide additional details (configs, logs, etc) if you really need to reproduce this, but this should be a fairly straight forward fix. My only solution so far is to restart the Tdarr server.

**Comment by HaveAGitGat** [comment]
This should already be covered. Tdarr uses `socket.io` between the server and nodes which supposedly has several built-in methods of checking the connection is live. I'll check to see if there are some additional settings.

**Comment by mike10010100** [comment]
I'm experiencing the same error, but in a slightly different situation, in my setup, I have a healthcheck set up via docker-compose to mark tdarr worker nodes as unhealthy if, for example, they lose the ability to use my nvidia GPUs for transcodes. A separate container then reaps the unhealthy containers and restarts them.

Normally, this process doesn't result in any issues, but occasionally my "host" node has the same set of errors.

My workaround for this has been to implement a health check in the "host" node via docker-compose:

```
 healthcheck:
      test: ["CMD-SHELL", "! tail -n 10 /app/logs/Tdarr_Server_Log.txt | grep -q 'Node registration error'"]
      interval: 60s
      retries: 5
      start_period: 600s
      timeout: 10s
```

This properly restarts the host node whenever it begins to log these errors.

However, I'd prefer to have a more robust solution that wouldn't require the host node to then re-scan it's DB (a time-consuming process).

Please let me know if there's more logging I can provide, the only logs I have so far is the same as above.

**Comment by HaveAGitGat** [comment]
In 2.00.19 released today each Node has a unique ID so this error should not happen anymore. nodeID is now nodeName. Reopen if needed thanks.

**Comment by UndercoverPervert** [comment]
![image](https://user-images.githubusercontent.com/32446791/219981572-c1fa3bba-dca0-473b-919e-666b97da0349.png)
It now shifts the blame to the node until it is restarted, at which point it successfully registers but the timed out node remains in the UI as a duplicate name, even when ignoring that, it is simpler to restart the host container as opposed to restarting multiple nodes on different machines.

**Comment by HaveAGitGat** [comment]
Thanks, do you have the server/node log when then happens?  When the node disconnects it should give a log such as `Node nodeID deregistered` on the server. On the node it should give `Node disconnected & deregistered`

Seems like there's some sort of `socket.io` bug happening in your environment whereby the socket connection is closed on the node but not on the server.

**Comment by UndercoverPervert** [comment]
Node:
```
[2023-02-19T21:35:34.153] [ERROR] Tdarr_Node - Node connection error to :192.168.1.151:8266
[2023-02-19T21:35:34.153] [ERROR] Tdarr_Node - Error: Node registration error: - nodeID 'pZ6eLPWQe' is already taken 
     when trying to register nodeName Tower
     Please restart the Node to generate a new nodeID
    at Socket.onpacket (/snapshot/app/node_modules/socket.io-client/build/cjs/socket.js:481:29)
    at Manager.<anonymous> (/snapshot/app/node_modules/@socket.io/component-emitter/index.js:143:20)
    at /snapshot/app/node_modules/socket.io-client/build/cjs/manager.js:240:18
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  data: undefined
}
```
Server:
```
[2023-02-19T21:35:34.153] [WARN] Tdarr_Server - Warning: nodeName Tower is being used by multiple Nodes, it's recommended to use a different nodeName for each node.
[2023-02-19T21:35:34.153] [ERROR] Tdarr_Server - Node registration error: - nodeID 'pZ6eLPWQe' is already taken 
     when trying to register nodeName Tower
     Please restart the Node to generate a new nodeID
```

The logs on linux appear to be truncated to 1MB, on a Windows node with a longer log there was no "deregistered" notification, just these same errors repeating for each node every 10 seconds, for 9 hours until I restarted the host.
It began once again during file transfers, the gigabit connection was maxed only to then be throttled by the dram-less SSDs (and later accelerated again when the cache is full and data is written directly to drives), as I previously mentioned the system can and does become unresponsive due to the SSDs. This specific node runs on the same server as the host, in the same docker environment, although it does use the server's LAN IP instead of a docker network (since the dockers are configured as bridge per the unraid template you provide) so it could have still been caused by the maxed out connection.

**Comment by charlie1135** [comment]
I have an issue similar to UndercoverPervert, with the notifications to restart the node, but, it reconnects and continues on.  It then terminates the transcodes in process and starts new ones.
```
[2023-05-16T13:53:10.943] [ERROR] Tdarr_Node - Node connection error to :192.168.1.70:8266
[2023-05-16T13:53:10.943] [ERROR] Tdarr_Node - Error: Node registration error: - nodeID 't76Bz6qlo' is already taken
     when trying to register nodeName Thinkpad [ID=t76Bz6qlo] [Address=::ffff:172.17.0.1] [PID=13716]
     Please restart the Node to generate a new nodeID
    at Socket.onpacket (C:\snapshot\node\node_modules\socket.io-client\build\cjs\socket.js:481:29)
    at Manager.<anonymous> (C:\snapshot\node\node_modules\@socket.io\component-emitter\index.js:143:20)
    at C:\snapshot\node\node_modules\socket.io-client\build\cjs\manager.js:240:18
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  data: undefined
}
[2023-05-16T13:53:19.913] [INFO] Tdarr_Node - Node connected & registered
```

**Comment by HaveAGitGat** [comment]
I've removed some dependencies in 2.00.22 just released which may fix this. Reopen if needed thanks.

**Comment by ArabCoders** [comment]
@HaveAGitGat Sadly this issue still here it somethings i noticed

### the tdarr_server instance become laggy after that the nodes keep getting disconnected and reconnected. logs at the time as following

```log
[2023-08-10T00:25:08.047] [ERROR] Tdarr_Server - Error during polling worker limits from node "vDXEGBdrT"

[2023-08-10T00:25:08.047] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'scheduleEnabled')

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20916

at _0x1fef18 (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:4880)

at Object.next (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:3098)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:2560

at new Promise (<anonymous>)

at __awaiter (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:1920)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20306

at Layer.handle [as handle_request] (/app/Tdarr_Server/node_modules/express/lib/router/layer.js:95:5)

at next (/app/Tdarr_Server/node_modules/express/lib/router/route.js:144:13)

at Route.dispatch (/app/Tdarr_Server/node_modules/express/lib/router/route.js:114:3)

[2023-08-10T00:25:08.048] [ERROR] Tdarr_Server - Error during polling worker limits from node "5aZz7FJuM"

[2023-08-10T00:25:08.048] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'scheduleEnabled')

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20916

at _0x1fef18 (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:4880)

at Object.next (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:3098)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:2560

at new Promise (<anonymous>)

at __awaiter (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:1920)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20306

at Layer.handle [as handle_request] (/app/Tdarr_Server/node_modules/express/lib/router/layer.js:95:5)

at next (/app/Tdarr_Server/node_modules/express/lib/router/route.js:144:13)

at Route.dispatch (/app/Tdarr_Server/node_modules/express/lib/router/route.js:114:3)

[2023-08-10T00:25:08.052] [ERROR] Tdarr_Server - Error during polling worker limits from node "vDXEGBdrT"

[2023-08-10T00:25:08.052] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'scheduleEnabled')

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20916

at _0x1fef18 (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:4880)

at Object.next (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:3098)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:2560

at new Promise (<anonymous>)

at __awaiter (/app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:1920)

at /app/Tdarr_Server/srcug/api/nodeRelay/nodeRelay.js:1:20306

at Layer.handle [as handle_request] (/app/Tdarr_Server/node_modules/express/lib/router/layer.js:95:5)

at next (/app/Tdarr_Server/node_modules/express/lib/router/route.js:144:13)

at Route.dispatch (/app/Tdarr_Server/node_modules/express/lib/router/route.js:114:3)

[2023-08-10T00:25:08.196] [INFO] Tdarr_Server - Node gaia_intel_node [ID=5aZz7FJuM] [Address=10.0.0.17] [PID=215] registered

[2023-08-10T00:25:08.197] [INFO] Tdarr_Server - Node INvidia-3090 [ID=vDXEGBdrT] [Address=127.0.0.1] [PID=231] registered
```

### tdarr_nodes reports timeout issues

```log
[2023-08-10T00:07:21.663] [ERROR] Tdarr_Node - Worker narrow-nag disconnected. Pruning.
[2023-08-10T00:07:25.801] [DEBUG] Tdarr_Node - Polling worker response error:10003ms
[2023-08-10T00:07:25.801] [ERROR] Tdarr_Node - Error: timeout of 10000ms exceeded
    at createError (/app/Tdarr_Node/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/app/Tdarr_Node/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/app/Tdarr_Node/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 31
    },
    method: 'post',
    url: 'http://10.0.0.3:8266/api/v2/poll-worker-limits',
    data: '{"data":{"nodeID":"5aZz7FJuM"}}'
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v2/poll-worker-limits',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '10.0.0.3',
      port: '8266',
      nativeProtocols: [Object],
      pathname: '/api/v2/poll-worker-limits'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 31,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 31,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/v2/poll-worker-limits HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 31\r\n' +
        'Host: 10.0.0.3:8266\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v2/poll-worker-limits',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '10.0.0.3',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'http://10.0.0.3:8266/api/v2/poll-worker-limits',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[2023-08-10T00:07:31.663] [ERROR] Tdarr_Node - Worker which-wasp disconnected. Pruning.
[2023-08-10T00:07:31.663] [ERROR] Tdarr_Node - Worker cold-carp disconnected. Pruning.
[2023-08-10T00:07:31.663] [ERROR] Tdarr_Node - Worker misty-mice disconnected. Pruning.
```

Not sure why that is happening. every other docker container on the same server working fine, except that tdarr lags and after a while they resume working

**Comment by HaveAGitGat** [comment]
Thanks I guess what is is happening is the websocket between node and server is dropping so the server unregisters the node, then the node worker limits request fails with `scheduleEnabled` being a secondary error.

I've updated the error so it will just show:

`Error during polling worker limits from node "aaaaaa". The node is not registered.`

In terms of what causes this not too sure. Do you have your Tdarr app data on an HDD? Could be that high disk activity is causing things to slow down so maybe try running on an SSD if possible. I think someone mentioned a similar issue to me a while ago and they discovered it was due to their firewall so perhaps check that if you can.

You can maybe also try checking `http://0.0.0.0/api/v2/debug-vars/text` in a browser and it will give some debug info. You can check `serverLagDiffs` for example mine shows 

```
  "serverLagDiffs": [
    1,
    13,
    12,
    14,
    1,
    2,
    2,
    10,
    1,
    14,
    0,
```

This means that at maximum the server is 14 milliseconds behind in processing, perhaps yours is higher.

**Comment by ArabCoders** [comment]
> This means that at maximum the server is 14 milliseconds behind in processing, perhaps yours is higher.

i have this 
```
  "serverLagDiffs": [
    0,
    -1,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    -1,
    0,
    131063,
    -1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    -1,
    0,
    108197
  ],
```
not sure why the numbers are high, the servers and nodes are (1 internal node and external intel 13th gen gpu) both are connected via 1G LAN connection. the server specs which running the tdarr server is

![image](https://github.com/HaveAGitGat/Tdarr/assets/1621552/cfe2541e-8e25-49da-9e1c-05f18e72a3c6)

both nodes are using GPU for transcodes docker stats for tdarr server `tdarr   5.21%   17.81GiB / 62.09GiB   28.69%    872MB / 824MB     933MB / 782MB     8789`

**Comment by ArabCoders** [comment]
@HaveAGitGat There also seems to be a memory leak, this is a metrics based on 24hr window 

![image](https://github.com/HaveAGitGat/Tdarr/assets/1621552/b06831a5-75b4-4f4e-a060-22cbeb242eec)

**Comment by HaveAGitGat** [comment]
Is it on 2.00.25? Does it drop down if you restart the container?

![86CD43C3-7B23-468D-A6D3-17194984246E](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3b3eaabb-f3b2-4950-b81b-134dcf8218c9)

This is mine for the last 3 days which has been holding quite steady so I wouldn’t be surprised if that issue is related to the initial one, would make sense.

**Comment by ArabCoders** [comment]
> Is it on 2.00.25? Does it drop down if you restart the container?
> 
> ![86CD43C3-7B23-468D-A6D3-17194984246E](https://user-images.githubusercontent.com/43864057/260318517-3b3eaabb-f3b2-4950-b81b-134dcf8218c9.jpeg)
> 
> This is mine for the last 3 days which has been holding quite steady so I wouldn’t be surprised if that issue is related to the initial one, would make sense.

Indeed restarting it and shutting down the internal node and relying on just external one seems to keep the memory in check not sure if this relates to this issue at hand.

![image](https://github.com/HaveAGitGat/Tdarr/assets/1621552/432e15a4-2e15-4146-bd38-2f3cf205874f)

i am not sure if it worth it to move tdarr the server to another node and have it act as purely just a server, the other node which is intel based does not seems to have the leaking problem

**Comment by HaveAGitGat** [comment]
Ok next time it happens maybe try opening a terminal in the container and run `ps aux` and we can see which process is using the memory. My setup is with both Linux internal node and windows external node.

**Comment by ArabCoders** [comment]
> Ok next time it happens maybe try opening a terminal in the container and run `ps aux` and we can see which process is using the memory. My setup is with both Linux internal node and windows external node.

Np once i started the internal node the memory started growing so i assume it's relates to it.

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        3732  0.0  0.0   7244  3456 pts/0    Ss   21:51   0:00 bash
root        3768  0.0  0.0   8896  3072 pts/0    R+   21:52   0:00  \_ ps axufww
root           1  0.0  0.0    208     0 ?        Ss   20:41   0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root          15  0.0  0.0    212     0 ?        S    20:41   0:00 s6-supervise s6-linux-init-shutdownd
root          16  0.0  0.0    200     0 ?        Ss   20:41   0:00  \_ /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
root          37  0.0  0.0    212     0 ?        S    20:41   0:00 s6-supervise s6rc-oneshot-runner
root          46  0.0  0.0    188     0 ?        Ss   20:41   0:00  \_ /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --
root          38  0.0  0.0    212     0 ?        S    20:41   0:00 s6-supervise s6rc-fdholder
root         229  0.0  0.0    212     0 ?        S    20:42   0:00 s6-supervise tdarr_node
abc          231  0.2  0.1 993672 80760 ?        Ssl  20:42   0:11  \_ Tdarr_Node
abc         3254  0.5  0.1 943996 78560 ?        Sl   21:49   0:01      \_ Tdarr_Node
abc         3392  0.0  0.0 597364 43632 ?        Sl   21:49   0:00      |   \_ /usr/bin/node --max-old-space-size=16384 /app/Tdarr_Node/srcug/workers/worker2.js
abc         3408 17.2  0.9 6883412 591184 ?      Sl   21:49   0:31      |       \_ tdarr-ffmpeg -c:v h264_cuvid -i /pool/media/tv/Show Title (1997)/Season 03/Show Title (1997) - S03E10 - Amends [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD.mkv -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 3098k -minrate 2168k -maxrate 4027k -bufsize 6197k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /pool/downloads/converted/Show Title (1997) - S03E10 - Amends [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD-TdarrCacheFile-gbbEYX8_T.mkv
abc         3349  0.3  0.0 654748 61004 ?        Sl   21:49   0:00      \_ Tdarr_Node
abc         3558  0.0  0.0 597364 43808 ?        Sl   21:49   0:00      |   \_ /usr/bin/node --max-old-space-size=16384 /app/Tdarr_Node/srcug/workers/worker2.js
abc         3570 17.1  0.9 6883552 590236 ?      Sl   21:49   0:30      |       \_ tdarr-ffmpeg -c:v h264_cuvid -i /pool/media/tv/Show Title (1997)/Season 03/Show Title (1997) - S03E09 - The Wish [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD.mkv -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 3561k -minrate 2492k -maxrate 4629k -bufsize 7123k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /pool/downloads/converted/Show Title (1997) - S03E09 - The Wish [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD-TdarrCacheFile-w9x3mIqxc.mkv
abc         3488  0.3  0.0 671388 61936 ?        Sl   21:49   0:00      \_ Tdarr_Node
abc         3660  0.0  0.0 597364 43640 ?        Sl   21:49   0:00          \_ /usr/bin/node --max-old-space-size=16384 /app/Tdarr_Node/srcug/workers/worker2.js
abc         3667 16.8  0.9 6883108 590816 ?      Sl   21:49   0:28              \_ tdarr-ffmpeg -c:v h264_cuvid -i /pool/media/tv/Show Title (1997)/Season 03/Show Title (1997) - S03E08 - Lover's Walk [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD.mkv -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 3200k -minrate 2240k -maxrate 4160k -bufsize 6400k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 /pool/downloads/converted/Show Title (1997) - S03E08 - Lover's Walk [Amazon.WEB-DL] [WEBDL-1080p] [h264 EAC3 8bit]-TrollHD-TdarrCacheFile-6wemGydEg.mkv
root         230  0.0  0.0    212     0 ?        S    20:42   0:00 s6-supervise tdarr_server
abc          232  7.9  0.3 12361060 248776 ?     Ssl  20:42   5:33  \_ Tdarr_Server
```

**Comment by HaveAGitGat** [comment]
Yes the memory will grow with the internal node as it’s running FFmpeg which in your info is using 3x 590MB RAM and then the workers use 40-70MB RAM each.

**Comment by ArabCoders** [comment]
> Yes the memory will grow with the internal node as it’s running FFmpeg which in your info is using 3x 590MB RAM and then the workers use 40-70MB RAM each.

Thanks. i have separated the server from the encoder node on same server just to be able to better track the usage. i'll hopefully report back tomorrow with the results. 

![image](https://github.com/HaveAGitGat/Tdarr/assets/1621552/11a0a271-d064-46bc-a17c-5288c75ef97e)

**Comment by Bokaii** [comment]
Hi, I have similiar issues as @ArabCoders, specifically related to tdarr_node reporting timeouts constantly and my Tdarr instance becomes unresponsive for a while. When checking http://0.0.0.0:8265/api/v2/debug-vars/text I found this:

`"serverLagDiffs": [
    36801,
    1,
    0,
    0,
    1,
    -1,
    36444,
    1,
    0,
    1,
    1,
    1,
    36160,
    1,
    1,
    1,
    0,
    0,
    36979,
    1,
    0,
    0,
    0,
    0,
    36432,
    1,
    1,
    0,
    0,
    0
  ],`

What more can I do to troubleshoot?
