### ISSUE TITLE
Tdaar on Ubuntu

### ISSUE THREAD

**Issue by galdorf** [HaveAGitGat/Tdarr#727]
Tdarr does not right out of the box it is shipped with outdated ffmpeg versions which cause issues when using updated plugins with users that hardware encode using newer versions of ffmpeg on different platforms the fix i found was to point the node config file "ffmpegPath":"/usr/bin/ffmpeg"
you would have to prior install ffmpeg before hand.

Better fix is to use updater and download newest stable version into those folders you should look into fixing that.

**Comment by HaveAGitGat** [comment]
Just testing 2.00.19 which has updated FFmpeg versions

**Comment by HaveAGitGat** [comment]
You can try 2.00.19 with update ffmpeg here:
https://docs.tdarr.io/docs/releases/pre-releases

**Comment by HaveAGitGat** [comment]
2.00.19 released today has newer versions.
