### ISSUE TITLE
Encoding Pause / Resume across update

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#73]
I'm not 100% sure if this is possible - but unraid manages to pause / resume during a parity check / rebuild so I assume it has a chance.

I just got to thinking with the amount of updates - each time we lose the progress in the encode, when you have multiple encodes running that wastes a lot of CPU cycles.  Would be a nice touch to allow the encodes to resume across e.g. a docker update.  If possible!

Thanks.

**Comment by HaveAGitGat** [comment]
I looked into this a few months ago with HBBatchBeast and I couldn’t get it to work so not sure if it’s possible. Will leave this open in case anyone has any ideas.

**Comment by HaveAGitGat** [comment]
https://github.com/HaveAGitGat/Tdarr/issues/103

**Comment by HaveAGitGat** [comment]
Seems this isn't possible without a modified/custom version of HandBrake.
