### ISSUE TITLE
Add Av1 support (update Handbrake to V1.6)

### ISSUE THREAD

**Issue by Nova849** [HaveAGitGat/Tdarr#731]
**Is your feature request related to a problem? Please describe.**
I would like to start converting my library to Av1. Handbrakes' new version allows this and works great.

**Describe the solution you'd like**
Ability to CPU encode Av1. Support for Intel hardware to do this would also be fantastic as this is my end goal. 

**Describe alternatives you've considered**

**Additional context**
I would just like to be able to go to create a plugin and have support to click on the Av1 option in the handbrake dropdown. 
Support later for Intel GPUs with the hardware encoder would also be fantastic although last I heard there are still a few things that need to come down the Linux pipeline before that happens.

**Comment by HaveAGitGat** [comment]
Currently trying 1.61 in the dev container, will see how it goes

**Comment by simeononsecurity** [comment]
I'll second this as a need. AV1 is a key feature that I'm sure the people want. 
Anyone with a 4000 series gpu or intel gpu want this.

**Comment by simeononsecurity** [comment]
@HaveAGitGat The public dev container hasn't been pushed to in a year. Any chance you can make it available for public testing?
https://hub.docker.com/layers/haveagitgat/tdarr/dev/images/sha256-f0620a172a747f99a50e1812edf303a52d392575fe26c7214230cfff7b3dcec3?context=explore

**Comment by HaveAGitGat** [comment]
Dev container is in tdarr_acc (acceptance) 🙂 Same with tdarr_node_acc

https://hub.docker.com/r/haveagitgat/tdarr_acc/tags


Try it out if you like. Will remove the one you mentioned as not used.

**Comment by HaveAGitGat** [comment]
`svt_av1` and `svt_av1_10bit` encoders seem to be working okay.

**Comment by HaveAGitGat** [comment]
2.00.19 released
