### ISSUE TITLE
Tdarr Causes Panic

### ISSUE THREAD

**Issue by sree-86** [HaveAGitGat/Tdarr#732]
**Describe the bug**
1. Tdarr Node creates several processes as seen under Activity Manager. Also, when the Tdarr application terminal is closed, Tdarr Node does not quit. It runs in the background.
2. I believe Tdarr Node causes kernel panic because that is the only application I have installed since the past two days and I don't run any other program in the background.

**To Reproduce**
1. Start Tdarr Node on M1 MacBook Air.
2. Several Tdarr Node processes are created and there is a kernel panic after a few hours.

**Expected behavior**
Tdarr Node should not create many processes and should not cause kernel panic.

**Screenshots**
<img width="1140" alt="Screenshot 2023-01-23 at 10 54 02 PM" src="https://user-images.githubusercontent.com/16274512/214209039-2a8cfd96-f9f1-462f-9635-f47ff056d243.png">

- Tdarr Node Config:

{
  "nodeID": "mac-amd64",
  "serverIP": "[IP Address]",
  "serverPort": "[Port]",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "[Path]",
      "node": "[Path]"
    },
    {
      "server": "[Path]",
      "node": "[Path]"
    }
  ],
  "platform_arch": "darwin_x64_docker_false",
  "logLevel": "INFO"
}

Tdarr Log:

[2023-01-23T07:02:01.492] [INFO] Tdarr_Node - [Path]/configs/Tdarr_Node_Config.json ->> STARTED TDARR NODE
[2023-01-23T07:02:01.500] [INFO] Tdarr_Node - {
  nodeID: 'mac-amd64',
  serverIP: '[IP Address]',
  serverPort: '[Port]',
  handbrakePath: '',
  ffmpegPath: '',
  mkvpropeditPath: '',
  pathTranslators: [
    {
      server: '[Path]',
      node: '[Path]'
    },
    {
      server: '[Path]',
      node: '[Path]'
    }
  ],
  platform_arch: 'darwin_x64_docker_false',
  logLevel: 'INFO'
}
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - version: 2.00.18
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - darwin_arm64_docker_false
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - Starting Tdarr_Node
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - Preparing environment
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - Path translator: Checking Node path: [Path]/Videos
[2023-01-23T07:02:01.533] [INFO] Tdarr_Node - Updating plugins
[2023-01-23T07:02:01.550] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: [Path]/Videos
[2023-01-23T07:02:01.550] [INFO] Tdarr_Node - Path translator: Checking Node path: [Path]/Tdarr_Updater/Cache
[2023-01-23T07:02:01.561] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: [Path]/Tdarr_Updater/Cache
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - handbrakePath:/usr/local/bin/HandBrakeCLI
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - ffmpegPath:[Path]/Tdarr_Node/node_modules/@ffmpeg-installer/darwin-arm64/ffmpeg
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2023-01-23T07:02:01.582] [ERROR] Tdarr_Node - Binary test 1: handbrakePath not working
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-01-23T07:02:01.582] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-01-23T07:02:01.712] [INFO] Tdarr_Node - Cloning plugins
[2023-01-23T07:02:01.723] [INFO] Tdarr_Node - Node connected & registered
[2023-01-23T07:02:02.038] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-23T07:02:05.279] [INFO] Tdarr_Node - [3568]Plugin update finished
[2023-01-23T08:02:01.555] [INFO] Tdarr_Node - Updating plugins
[2023-01-23T08:02:01.905] [INFO] Tdarr_Node - Cloning plugins
[2023-01-23T08:02:02.657] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-23T08:02:06.174] [INFO] Tdarr_Node - [4270]Plugin update finished
[2023-01-23T09:02:01.594] [INFO] Tdarr_Node - Updating plugins
[2023-01-23T09:02:01.956] [INFO] Tdarr_Node - Cloning plugins
[2023-01-23T09:02:02.376] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-23T09:02:05.695] [INFO] Tdarr_Node - [3740]Plugin update finished
[2023-01-23T10:02:01.671] [INFO] Tdarr_Node - Updating plugins
[2023-01-23T10:02:02.086] [INFO] Tdarr_Node - Cloning plugins
[2023-01-23T10:02:02.932] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-23T10:02:06.463] [INFO] Tdarr_Node - [4378]Plugin update finished -->> MAC KERNEL PANIC HERE
[2023-01-23T17:41:16.585] [INFO] Tdarr_Node - [Path]/configs/Tdarr_Node_Config.json

 - OS: MacOS 13.1
 - Tdarr Node Version2.00.18

Mac Log:

panic(cpu 4 caller 0xfffffe002d461790): watchdog timeout: no checkins from watchdogd in 90 seconds (923 total checkins since monitoring last enabled)
Debugger message: panic
Memory ID: 0xff
OS release type: User
OS version: 22C65
Kernel version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
Fileset Kernelcache UUID: ADB288150AFF2B26A022D2179A26F30C
Kernel UUID: D43063DF-7FAB-3E39-9807-2FC6A0C7F76A
Boot session UUID: 3852352A-5502-4AF9-A0D9-F97BFB06BF29
iBoot version: iBoot-8419.60.44
secure boot?: YES
roots installed: 0
Paniclog version: 14
KernelCache slide: 0x00000000246b0000
KernelCache base:  0xfffffe002b6b4000
Kernel slide:      0x00000000258f4000
Kernel text base:  0xfffffe002c8f8000
Kernel text exec slide: 0x00000000259dc000
Kernel text exec base:  0xfffffe002c9e0000
mach_absolute_time: 0xab54d53aa1
Epoch Time:        sec       usec
  Boot    : 0x63cea92e 0x0006abae
  Sleep   : 0x63cf18a7 0x0002e5bc
  Wake    : 0x63cf1b82 0x000469d4
  Calendar: 0x63cf3fe5 0x000b2745

Zone info:
  Zone map: 0xfffffe10147dc000 - 0xfffffe30147dc000
  . VM    : 0xfffffe10147dc000 - 0xfffffe14e14a8000
  . RO    : 0xfffffe14e14a8000 - 0xfffffe167ae40000
  . GEN0  : 0xfffffe167ae40000 - 0xfffffe1b47b0c000
  . GEN1  : 0xfffffe1b47b0c000 - 0xfffffe20147d8000
  . GEN2  : 0xfffffe20147d8000 - 0xfffffe24e14a4000
  . GEN3  : 0xfffffe24e14a4000 - 0xfffffe29ae170000
  . DATA  : 0xfffffe29ae170000 - 0xfffffe30147dc000
  Metadata: 0xfffffe8ff51e8000 - 0xfffffe8ffd1e8000
  Bitmaps : 0xfffffe8ffd1e8000 - 0xfffffe8fffdec000

CORE 0 recently retired instr at 0xfffffe002cb9bd78
CORE 1 recently retired instr at 0xfffffe002cb9bd78
CORE 2 recently retired instr at 0xfffffe002cb9bd78
CORE 3 recently retired instr at 0xfffffe002cb9bd78
CORE 4 recently retired instr at 0xfffffe002cb9a678
CORE 5 recently retired instr at 0xfffffe002cb9bd78
CORE 6 recently retired instr at 0xfffffe002cb9bd78
CORE 7 recently retired instr at 0xfffffe002cb9bd78
TPIDRx_ELy = {1: 0xfffffe29adf30838  0: 0x0000000000000004  0ro: 0x0000000000000000 }
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 0: PC=0xfffffe002ca7bc18, LR=0xfffffe002ca7bc18, FP=0xfffffe8ff3d8ff00
CORE 1: PC=0xfffffe002ca7bc18, LR=0xfffffe002ca7bc18, FP=0xfffffe8ff3d3bf00
CORE 2: PC=0xfffffe002cb97324, LR=0xfffffe002cb97320, FP=0xfffffe8ff3d53e90
CORE 3: PC=0xfffffe002ca7bc1c, LR=0xfffffe002ca7bc18, FP=0xfffffe8ff430bf00
CORE 4 is the one that panicked. Check the full backtrace for details.
CORE 5: PC=0xfffffe002cb43880, LR=0xfffffe002cb43860, FP=0xfffffe3d92443dc0
CORE 6: PC=0xfffffe002ca7bc1c, LR=0xfffffe002ca7bc18, FP=0xfffffe3d9313ff00
CORE 7: PC=0xfffffe002ca7bc1c, LR=0xfffffe002ca7bc18, FP=0xfffffe3d90d33f00
Compressor Info: 8% of compressed pages limit (OK) and 5% of segments limit (OK) with 2 swapfiles and OK swap space
Total cpu_usage: 40969071
Thread task pri cpu_usage
0xfffffe29ae090838 kernel_task 91 2864517
0xfffffe29adf30838 kernel_task 91 4748876
0xfffffe29ad3f9030 corebrightnessd 37 0
0xfffffe29ad103010 syslogd 4 0
0xfffffe29adc6d828 kernel_task 0 916105

Panicked task 0xfffffe24e1441660: 0 pages, 483 threads: pid 0: kernel_task
Panicked thread: 0xfffffe29adf30838, backtrace: 0xfffffe8ff47c3850, tid: 1548
		  lr: 0xfffffe002ca3ebf0  fp: 0xfffffe8ff47c38c0
		  lr: 0xfffffe002ca3e998  fp: 0xfffffe8ff47c3940
		  lr: 0xfffffe002cba2804  fp: 0xfffffe8ff47c3960
		  lr: 0xfffffe002cb9426c  fp: 0xfffffe8ff47c39d0
		  lr: 0xfffffe002cb91b70  fp: 0xfffffe8ff47c3a90
		  lr: 0xfffffe002c9e77f8  fp: 0xfffffe8ff47c3aa0
		  lr: 0xfffffe002ca3e324  fp: 0xfffffe8ff47c3e50
		  lr: 0xfffffe002d282a44  fp: 0xfffffe8ff47c3e70
		  lr: 0xfffffe002d461790  fp: 0xfffffe8ff47c3ec0
		  lr: 0xfffffe002d460964  fp: 0xfffffe8ff47c3f00
		  lr: 0xfffffe002d45df94  fp: 0xfffffe8ff47c3f20
		  lr: 0xfffffe002dcaa190  fp: 0xfffffe8ff47c3fb0
		  lr: 0xfffffe002d1b4698  fp: 0xfffffe8ff47c3fc0
		  lr: 0xfffffe002cb94e84  fp: 0xfffffe8ff47c3fe0
		  lr: 0xfffffe002c9e786c  fp: 0xfffffe8ff47c3ff0
		  lr: 0xfffffe002cc15568  fp: 0xfffffe3d9287ba40
		  lr: 0xfffffe002cc15568  fp: 0xfffffe3d9287baa0
		  lr: 0xfffffe002cc1b4d4  fp: 0xfffffe3d9287bc40
		  lr: 0xfffffe002cc1aa54  fp: 0xfffffe3d9287bcb0
		  lr: 0xfffffe002cc1a914  fp: 0xfffffe3d9287bcd0
		  lr: 0xfffffe002f86d67c  fp: 0xfffffe3d9287bd40
		  lr: 0xfffffe002cc74f30  fp: 0xfffffe3d9287bdc0
		  lr: 0xfffffe002d012abc  fp: 0xfffffe3d9287be90
		  lr: 0xfffffe002cada864  fp: 0xfffffe3d9287bea0
		  lr: 0xfffffe002cb318b4  fp: 0xfffffe3d9287bf20
		  lr: 0xfffffe002c9f0e98  fp: 0x0000000000000000
      Kernel Extensions in backtrace:
         com.apple.driver.AppleARMWatchdogTimer(1.0)[F9C14BA5-D791-362B-ADCC-9FA6782CB310]@0xfffffe002d45ca00->0xfffffe002d4617b7
            dependency: com.apple.driver.AppleARMPlatform(1.0.2)[00A0000C-A4BD-3590-A973-61FA2E8A1D63]@0xfffffe002d40e490->0xfffffe002d45c9ff
         com.apple.driver.AppleInterruptController(1.0d1)[4A885501-DCC9-3C79-B55D-FDC31BE006E9]@0xfffffe002dca7250->0xfffffe002dcaaf67
            dependency: com.apple.driver.AppleARMPlatform(1.0.2)[00A0000C-A4BD-3590-A973-61FA2E8A1D63]@0xfffffe002d40e490->0xfffffe002d45c9ff
         com.apple.filesystems.smbfs(5.0)[9526C583-7D55-31AA-92CF-5F9E47F16370]@0xfffffe002f8470e0->0xfffffe002f8b049b
            dependency: com.apple.kec.corecrypto(12.0)[6D943893-92EB-38E2-AE0C-87D96EE68BBE]@0xfffffe002f74a840->0xfffffe002f79327f
            dependency: com.apple.kext.triggers(1.0)[D791F1E1-AA0B-31BE-8183-1E66D371BDB0]@0xfffffe002f8ba4b0->0xfffffe002f8bcd9b

last started kext at 441051957480: com.apple.filesystems.smbfs	5.0 (addr 0xfffffe002beb03d0, size 77739)
loaded kexts:
com.apple.filesystems.smbfs	5.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTopCaseHIDEventDriver	6000.22
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	200.4
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.SEPHibernation	1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.ApplePMP	1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.AppleSerialShim	1
com.apple.filesystems.nfs	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	2142.61.2
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	627.40.1
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AudioDMAController-T8103	220.1
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.AppleTAS5770LAmp	600.99
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleAVE2	640.4.1
com.apple.driver.AppleCS42L83Audio	600.99
com.apple.driver.AppleJPEGDriver	5.2.6
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleAVD	617
com.apple.AGXG13G	227.2.45
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleT8101	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	198.40.3
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	403
com.apple.kec.InvalidateHmac	1
com.apple.kec.Compression	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.driverkit.serial	6.0.0
com.apple.iokit.IOAVBFamily	1120.2
com.apple.plugin.IOgPTPPlugin	1110.13
com.apple.driver.AppleHIDKeyboard	231
com.apple.driver.AppleActuatorDriver	6400.44
com.apple.driver.AppleMultitouchDriver	6400.44
com.apple.driver.AppleHSBluetoothDriver	6000.22
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.AppleAOPAudio	200.45
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleHIDTransportSPI	6400.40
com.apple.driver.AppleHIDTransport	6400.40
com.apple.driver.AppleInputDeviceSupport	6400.40
com.apple.nke.ppp	1.9
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleSART	1
com.apple.driver.AppleSPU	1
com.apple.driver.AppleBSDKextStarter	3
com.apple.kext.triggers	1.0
com.apple.driver.IOHIDPowerSource	1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleSyntheticGameController	10.3.5
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.AGXFirmwareKextG13GRTBuddy	227.2.45
com.apple.AGXFirmwareKextRTBuddy64	227.2.45
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.driver.AppleCSEmbeddedAudio	600.99
com.apple.driver.AppleEmbeddedAudio	600.99
com.apple.iokit.AppleARMIISAudio	200.8
com.apple.driver.AppleH13CameraInterface	7.202.0
com.apple.driver.AppleH10PearlCameraInterface	17.0.8
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.ApplePMGR	1
com.apple.driver.AppleH11ANEInterface	6.201.0
com.apple.iokit.IOGPUFamily	65.0.22
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.81
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.13.0
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T8103	720.1
com.apple.driver.AppleEmbeddedAudioLibs	200.5
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOTimeSyncFamily	1110.13
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	597
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	547
com.apple.iokit.IOUSBMassStorageDriver	232
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	476
com.apple.iokit.IOSCSIArchitectureModelFamily	476
com.apple.driver.AppleRSMChannel	1
com.apple.iokit.IORSMFamily	1
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	200.2
com.apple.driver.AppleAudioClockLibs	200.5
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	334.0.1
com.apple.driver.IODARTFamily	1
com.apple.driver.FairPlayIOKit	68.19.0
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.iokit.IOStorageFamily	2.1
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.security.AppleImage4	5.0.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

** Stackshot Succeeded ** Bytes Traced 406232 (Uncompressed 989776) **

**Comment by HaveAGitGat** [comment]
Please try 2.00.20 and reopen if need, ty
