### ISSUE TITLE
Tdarr incorrectly interprets comma in plugin variable while building ffmpeg command.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#733]
**Describe the bug**
Tdarr incorrectly interprets a comma that is contained within a plugin variable when setting up an ffmpeg command, which means the resulting command is malformed and fails. There does not appear to be a way of escaping the character so that it is rendered as part of the command rather than interpreted. The comma is necessary to initialise some hardware devices (especially intel qsv on windows, where the iGPU is secondary and not connected to a monitor).

**To Reproduce**
Include a comma within the response.preset variable as part of the command. Example:

```
response.preset += `-init_hw_device qsv=intel,child_device=1 -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv`
```
results in the command being rendered as

```
C:/tdarr/ffmpeg/ffmpeg.exe -init_hw_device qsv=intel -i input.mkv child_device=1 -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv output.mkv
```

with the hardware initialisation being split around the input file rather than being placed before it as it should be, and the encoding and filter options are omitted completely. 

**Expected behavior**
The correctly formatted command which works in the terminal should be:

```
./ffmpeg.exe -init_hw_device qsv=intel,child_device=1 -hwaccel qsv -hwaccel_output_format qsv -c:v h264_qsv -i input.mkv -c:v hevc_qsv -preset faster -global_quality 19 -b_strategy 1 -c:a
 copy -c:s copy output.mkv
```

**Please provide the following information:**
Worker error log example: https://pastebin.com/9uKBFPN4

 - OS: This node is i5-13500 on win11. UHD 770 graphics on cpu but Nvidia 1060 also installed.
 - Server is running in docker container on ubuntu 22.04 LTS
 - Version  2.00.18

**Comment by HaveAGitGat** [comment]
Use `<io>` to split the input and output args. Should work as expected then.

**Comment by caiusseverus** [comment]
Yep that does the trick. Thanks for your help.

**Comment by HaveAGitGat** [comment]
Great glad it worked :)
