### ISSUE TITLE
Queue items not visible whilst library paused

### ISSUE THREAD

**Issue by ConfusedTA** [HaveAGitGat/Tdarr#735]
I've now got a schedule set up so that it's only transcoding during the day, when I'm producing electricity via solar (in a vague attempt to save a little money on energy costs).

I've noticed after setting this up that I can see the count of files in the queue, but not what the files are, when it's not within the scheduled times:

![image](https://user-images.githubusercontent.com/3897846/217053714-88c987d2-c565-4327-9916-3d29e4d1ef54.png)

As soon as the node fires up, the contents of the queue appear again:

![image](https://user-images.githubusercontent.com/3897846/217053991-5190290c-4d49-415c-b9a3-21e03f6c0fbd.png)

A minor thing in the grand scheme, but if this could be sorted out, it would be appreciated :)

**Comment by HaveAGitGat** [comment]
Hi :), what shows up when clicking the yellow 'Warning: Info on queue counts' button? Should be some info in there to do with this.

**Comment by ConfusedTA** [comment]
Yes, I see there's an explanation as to why it is doing what it's doing, and I guessed that was possibly why, but I'm wondering if there's the possibility to see the queued files. (I'd not thought of clicking on the yellow warnings... _lesson to self: click on more stuff that doesn't necessarily look clickable!_)

The reason for asking might be, for example, that I want to prioritise a specific file and turn on processing outside of my scheduled hours (_maybe the default language is Spanish, and I'm British, so still think it's 150 years ago when the British Empire ruled the world so haven't bothered to think it a priority to learn any other languages... anyway, I digress, there may be **a** reason I want to process this file_).

As I said, it is a minor thing overall, but wanted to mention it in case I'd missed a setting somewhere that already does what I would like and I'm being a derp and not seeing it :)

**Comment by HaveAGitGat** [comment]
If you go on the search tab then you can bump files from there:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/24d9d26a-0b5c-4531-af1a-a61728840525)

The UI reflects the worker queues so by making the files visible there'd it would interfere with the worker queue system (and potentially make it more confusing as some people may wonder why files are showing up in the queue but workers aren't taking them). Maybe can do it in future if there's more of a need for it but will close for now.

**Comment by rlively** [comment]
@HaveAGitGat I just ran across this and wanted to note that I thought it was counter-intuitive as well that all of the files dropped out of the queue. They are still in a queue somewhere and pop back in when the scheduled time rolls around, but there's no visibility to what files will be processed when it's enabled. Could it show up in the queue with a status column to show "Inactive" or something similar so we could see the queue and interact with it and then use the status to not interfere with the worker queue system?
