### ISSUE TITLE
Rename based on codec plugin - error for ep. numbers 264, 265

### ISSUE THREAD

**Issue by ljo123** [HaveAGitGat/Tdarr#736]
**Describe the bug**
For tv series with high episode numbers, the rename based on codec plugin mis-interprets the episode number for episodes 264 and 265 as being codec tags.

**To Reproduce**
 Transcode a file named something like "Testfile S01E264 WEBDL-1080p.mkv" with either "Rename based on codec" or "Rename based on codec and resolution" plugins enabled.

**Expected behavior**
Plugin filename output shouldn't be affected by episode number.

**Additional context**
I think to fix, the plugin needs to be more specific in checking the name, excluding E264 and E265.

**Comment by HaveAGitGat** [comment]
Not sure I've ever watched a show with more than 30 episodes in a season let alone 264 :). Interesting problem, not sure what the best solution would be for this.

**Comment by ljo123** [comment]
Anime series! I think just ignoring the number if its preceded by an E would fix it.
