### ISSUE TITLE
Conversion of mp4 -> mkv produces very bad quality.

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#737]
**Describe the bug**
After conversion, the resulting file is of much poorer quality

**To Reproduce**
Take the mp4 file below and convert it to HECV mkv file. Observe that the mkv file, while smaller, has much poorer quality. This may very well be a config error on my side. I've been using Tdarr for a while now and mostly the converted files have the same or very similar quality. These videos, from a class I'm taking, are smaller to start with but convert badly.

**Expected behavior**
I expected a smaller file with a similar resolution/quality.

The files are too big to attach but you can get them here:

[01-installing-tsc.mp4](https://cloud.defariahome.com/index.php/s/CgoSk2gg4xHGkac) <- original file of good quality
[01-installing-tsc.mkv](https://cloud.defariahome.com/index.php/s/aEEsGyDYAS6fnZg) <- converted file of bad quality

**Note**: The mkv file will not play properly through my NextCloud instance. Download it to view it instead.

**Comment by HaveAGitGat** [comment]
Could you upload the job report please as I'm not sure which transcode settings you're using.

**Comment by adefaria** [comment]
[wwz7_NERH-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10702352/wwz7_NERH-log.txt)

**Comment by HaveAGitGat** [comment]
That's the health check log, make sure to select the last transcode log on the left side.

**Comment by adefaria** [comment]
Sorry. The transcode one said "not required". Not sure why. Regenerating...

Here's a new one. 

[ix-ha-dQR-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10712171/ix-ha-dQR-log.txt)

**Comment by adefaria** [comment]
Any news on this?

**Comment by HaveAGitGat** [comment]
To increase/decrease quality you'd need to adjust the bitrate (or other transcode settings) in the migz plugin, those settings are just the defaults he set. The container mp4/mkv doesn't have anything to do with quality. Plugin issues can be put here https://github.com/HaveAGitGat/Tdarr_Plugins/issues
