### ISSUE TITLE
Progress Display Issue

### ISSUE THREAD

**Issue by Dart2112** [HaveAGitGat/Tdarr#738]
**Describe the bug**
Progress of FFMPEG transcodes is not showing in the Web UI

**To Reproduce**
The bug has started since the latest version update. I am transcoding using the Tdarr_Plugin_075b_FFMPEG_HEVC_Generic_Video_Audio_Only plugin

**Expected behavior**
I'd expect the UI to give me accurate progress, ETA and compression ratios. These three bits of information seem to have broken

**Screenshots**

![2023-02-13_22-50](https://user-images.githubusercontent.com/8944036/218456171-a83713a1-bb02-4089-8d42-2f1e1bdb6f77.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

[Configs.zip](https://github.com/HaveAGitGat/Tdarr/files/10722114/Configs.zip)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

[Logs.zip](https://github.com/HaveAGitGat/Tdarr/files/10722179/Logs.zip)

 - OS: Docker tdarr:latest
 - Browser: chrome
 - Version: 2.00.19

**Additional context**

I've tried clearing browser data as I know that it can have an impact. The issue also occurs on my phone (also chrome)

**Comment by Dart2112** [comment]
Some extra context. I have another plugin (Tdarr_Plugin_x7ab_Remove_Subs) which displays correctly.

**Comment by HaveAGitGat** [comment]
Thanks, do you have the job report for a file this happens with?

https://docs.tdarr.io/docs/other/job-reports

I'm assuming this is do with an issue with mediaInfo has slightly changed the duration data type in some cases.

**Comment by Dart2112** [comment]
I don't have full reporting from FFMPEG enabled but can enable it and get a transcode going if you want. 
Here is a finished job report for a file that didn't show progress.
[3qZYZ9Xw3-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10729257/3qZYZ9Xw3-log.txt)

**Comment by HaveAGitGat** [comment]
Thanks, yeah Duration is now `"Duration":"01:15:38.560000000"` which is causing the issue. Just building the fix atm.

**Comment by HaveAGitGat** [comment]
Would you mind giving `haveagitgat/tdarr_acc:dev_2.00.19_2023_02_14T15_19_30z` a quick try. Percentage should now work on those types of files. Thanks.

**Comment by Dart2112** [comment]
Works perfectly, thank you very much

**Comment by HaveAGitGat** [comment]
Great, thanks will release the update

**Comment by HaveAGitGat** [comment]
Released
