### ISSUE TITLE
Filter by Modified Date

### ISSUE THREAD

**Issue by Tailslide** [HaveAGitGat/Tdarr#741]
Not sure if this is a plugin issue or a tdarr issue so I opened it both places.. please close whatever doesn't apply.

I see there is a 'hold' feature but I'd instead like to filter by age from file modified date (like only convert if 30 days old or older)

I tried making a plugin but I'm not sure this is possible since the plugins are javascript and file doesn't seem to contain lastModified?

**Comment by HaveAGitGat** [comment]
Will respond on the plugin one thanks.
