### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by bcurran3** [HaveAGitGat/Tdarr#743]
Please add a LICENSE file so that use and distribution is clearly and legally defined.

**Comment by HaveAGitGat** [comment]
Will do thanks

**Comment by HaveAGitGat** [comment]
Added here:
https://home.tdarr.io/eula

**Comment by bcurran3** [comment]
Thanks.

Please clarify for me if:
> Reproduce, copy, distribute, resell or otherwise use the Software for any commercial purpose
is only related to commercial purposes; i.e. are non-commercial uses allowed to copy and distribute for free?

REFERENCE: I'm packing it for the Chocolatey Community Repository and specifically want to know if I can include the binary (preferred as it's immutable) in the package or am forced to link to it for download (not preferred as installs will fail when the version chagnes).

**Comment by HaveAGitGat** [comment]
Oh interesting yeah that’s fine. There are some other people doing similar things for QNAP and Kubernetes.

Could I be added as a maintainer?

**Comment by bcurran3** [comment]
Great.

Sure thing. Just let me know your Chocolatey ID and I'll add you. I'll pass it to you if you prefer.

**Comment by HaveAGitGat** [comment]
Sorry missed this but my choc ID is `haveagitgat`. I haven't ever handled a chocolatey package so not too sure what I'd be doing but the current package seems to work nicely. Not sure if there's a way to pipe the Tdarr_Updater output to the terminal while it's installing stuff.

**Comment by bcurran3** [comment]
Just send you the maintainer request for it as well as HBBatchBeast.

The package is pretty easy to update. They way I've got it setup you just need to update the version in the nuspec file, overwrite the .zip file, pack, and push. If you need any help, just ask.

> Not sure if there's a way to pipe the Tdarr_Updater output to the terminal while it's installing stuff.

I'm lost on this statement. Is this something you want done in the Chocolatey package?

**Comment by HaveAGitGat** [comment]
Ok will look into that thanks.

> I'm lost on this statement. Is this something you want done in the Chocolatey package?

Yeah will try and see if I can do it at some point. At the moment it shows this when the Tdarr Updater is running:
![image](https://user-images.githubusercontent.com/43864057/236670810-1312a94d-e7cf-4087-8f18-26711384df22.png)


So maybe would be good if it shows the usual console output when the updater is running:
![image](https://user-images.githubusercontent.com/43864057/236670879-94d316ba-e891-46f3-aca1-9c8021f81124.png)
