### ISSUE TITLE
Windows worker connects but doesn't take jobs

### ISSUE THREAD

**Issue by DuzAwe** [HaveAGitGat/Tdarr#744]
Windows worker connects but doesn't take jobs. At one point it was alternating doing one on the local and then when that was don removing to the windows node. But it's inconsistent. Everything was working until I updated.

[Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10813055/Server-log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/10813058/Tdarr_Node_Log.txt)
[Tdarr_Updater_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/10813060/Tdarr_Updater_Log.txt)

**Comment by HaveAGitGat** [comment]
Server log:

`[2023-02-23T11:30:34.358] [ERROR] Tdarr_Server - Worker V2zP2SGLq requesting item. Staged file limit of 3 reached. Please take action on those files or increase the staged file limit in the 'Staging Section'`

Please check the staged files and take action on them. Reopen if needed thanks.

**Comment by DuzAwe** [comment]
Stage limit 100 and its still the same each worker is set to only take 1 job.

**Comment by HaveAGitGat** [comment]
Perhaps try entering something new in the stage limit like 99 just to force update it because from the server logs the limit is 3 not 100.

**Comment by DuzAwe** [comment]
Sorry I mean to say I changed it and it still didn't send things to my window node. Ill grab a bunch of files and get some more testing done.

**Comment by DuzAwe** [comment]
I restarted the docker and it all seems to be back to normal.
