### ISSUE TITLE
[hevc_nvenc @ 000001580c1fb7c0] No capable devices found

### ISSUE THREAD

**Issue by Stuke00** [HaveAGitGat/Tdarr#745]
I keep getting this error using the built in Migz Nvidia plugin.  I have an Nvidia GTX 1650 GDDR 6 with Turing Cores so my card should be supported.

**Comment by HaveAGitGat** [comment]
Please post the job report and reopen if needed thanks. Not sure what OS you're on or if you're using Docker etc etc.
https://docs.tdarr.io/docs/other/job-reports/

**Comment by Stuke00** [comment]
Sure, sorry about that.  The node is running on Windows with all the Nvidia drivers installed.  

[wS6qkdg5_qN-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10871166/wS6qkdg5_qN-log.txt)

**Comment by HaveAGitGat** [comment]
Thanks are you able to try running it on this file?

https://samples.tdarr.io/api/v1/samples/sample__1080__libx264__aac__30s__video.mkv

Also try leaving the `ffmpegPath` blank in the Node config file so it will use the FFmpeg binary that Tdarr comes with. Perhaps that will work.

**Comment by Stuke00** [comment]
Interesting, changing the FFMPEG path seems to have fixed it.  It processed that sample file just fine and other files now too.

**Comment by HaveAGitGat** [comment]
Thanks for the update, glad it's working.
