### ISSUE TITLE
Better handling of node buttons

### ISSUE THREAD

**Issue by Extremity** [HaveAGitGat/Tdarr#746]
Just a few quick suggestions that I think would result in a much better UX:

1) When on the main page, in the "Nodes" section with the 'buttons' for each connected node at the top-right, color the nodes when paused. Taking the current color and shifting it slightly towards red would be perfect. This way I can see their status at a glance.

2) A right click menu on these buttons would also be a huge improvement. When I need to manage multiple nodes it would be so much easier if I could right click each to at least pause/unpause them.

I don't really think it's necessary to include anything else as this is just a feature request. I know these are minor/insignificant changes in the grand scheme of things, but little quality of life adjustments like these take a tiny time investment and really do add up over time.

**Comment by HaveAGitGat** [comment]
![image](https://user-images.githubusercontent.com/43864057/221938112-56ced4a9-bda2-4141-8053-1d38a54b30b8.png)
![image](https://user-images.githubusercontent.com/43864057/221938312-67a73cc1-8b92-4b68-af62-7ca85a4bfb7b.png)

Added both

**Comment by HaveAGitGat** [comment]
2.00.20 released
