### ISSUE TITLE
After transcoding 0MB file size

### ISSUE THREAD

**Issue by HexRebuilt** [HaveAGitGat/Tdarr#747]
Hi

**Describe the bug**
I'm not able to complete any transcoding of the files 

**To Reproduce**
After buiding a docker with GPU enabled, let it run on a test folder.

**Expected behavior**
Having the files being transcoded to h.265 and reduce the space occupied on the drive

**Screenshots**
ongoing transcoding on the gpu side:
![image](https://user-images.githubusercontent.com/32871843/222188533-1f060ea3-25dd-49cb-933e-044571594fdd.png)
I tried several profiles to encode the files with no results.
![image](https://user-images.githubusercontent.com/32871843/222191185-0688738f-2178-45b8-b7ac-553f00f40a8e.png)

**Please provide the following information:**
- Config files :
[tdarr-configs.zip](https://github.com/HaveAGitGat/Tdarr/files/10862814/tdarr-configs.zip)

- Log files :
[tdarr-logs.zip](https://github.com/HaveAGitGat/Tdarr/files/10862823/tdarr-logs.zip)

-Worker error 
[u1APUT7NhIA-log.txt](https://github.com/HaveAGitGat/Tdarr/files/10862748/u1APUT7NhIA-log.txt)

 - OS: ubuntu
 - Browser chrome, safari
 - GPU: quadro P400

**Comment by HaveAGitGat** [comment]
Reopen if needed thanks

**Comment by HexRebuilt** [comment]
thanks a lot. i'll check on the permissions. right now the user associated as a owner of the files is the same running tdarr so i'll check more if i can rw a text file inside the folders
