### ISSUE TITLE
Node Tags matched to plugins/transcode steps

### ISSUE THREAD

**Issue by Aesir** [HaveAGitGat/Tdarr#748]
**Is your feature request related to a problem? Please describe.**
I have a Windows node and some plugins are unusable because they require Linux, but my Windows node is my fastest computer. It would be really nice to just tag certain steps Linux-only and have them taken by a Linux node when available. 

I also had to run on a slow, saturated WiFi connection for a while. It would have been really nice to limit the tasks on the WiFi-connected nodes to things that would be CPU-bound rather than network-bound (e.g. the actual video transcode) and let the data heavy but CPU light tasks be handled by a local node. The Healthcheck/Transcode worker divide helped with this, but felt really limited. 

Not all nodes have the same power/speed and I don't want them spinning for 8-10 hours on a single transcode, only to potentially lose it because the power flickered or router rebooted, but I don't mind them doing steps that only take them an hour while saving faster nodes for the big tasks. 

**Describe the solution you'd like**
This could definitely absorb some of the other node enhancement requests currently open. Allow the user to tag nodes and then allow the user to whitelist and/or blacklist tags for individual plugins/transcode steps. Ideally the user could chose whether to use whitelisted, blacklisted, or any tags. From my above examples, I might create Windows, Linux, Slow, Fast, Local, and WiFi tags.

**Describe alternatives you've considered**
The only alternative I've found is to create extra libraries and turn Process Library on and off along with Pausing and Unpausing certain nodes. It works, kind of, but it's extremely painful and requires constantly resetting all of the libraries while also not allowing you to run nodes in parallel. Beyond that I could just use a single local node, but at that point I might as well just use Handbrake or ffmpeg directly. 

---

These aren't issues that users are going to run into all of the time, but I think it really opens up a lot of options to let plugin developers use OS-specific tools more often (e.g. grep, chown) and let users with substandard hardware setups take better advantage of what they do have. I also think that power users could see some pretty big advantages from directing certain nodes to ideal tasks.

**Comment by zackpollard** [comment]
I actually just came here to request the same thing, I discussed it in the discord the other day. The way I worked around this currently is that anything that is CPU bound happens in a GPU worker, then my remote nodes only have GPU workers. This obviously only works if you don't do GPU transcoding, but it sounds like you do it all on CPU. Basically, I tricked tdarr into believing that the work is for a GPU worker by adding `-c:v hevc_vaapi -c:v libx265` to my ffmpeg configuration. Tdarr will see the hevc_vaapi and request a GPU worker, but when the actual encode happens, the libx265 will override the previous argument as it is later in the command. Hope this helps until this feature is hopefully added :smile:

**Comment by HaveAGitGat** [comment]
Yeah will work on this after the next release. 

Main thing is it would be up to the user to have a valid setup so that there are available nodes which match the plugin tags.

Think I'd follow the same system as GitHub Actions.

For example, the Node has to include all the tags of the plugin. 

```
const node1Tags = ['a', 'b', 'c']

// would run on node1
const plugin1Tags = ['a', 'b']

// would run on node1
const plugin2Tags = ['a', 'b', 'c']

// would not run on node1
const plugin3Tags = ['a', 'b', 'd']
```

Not sure how the worker types would fit in with this as don't really want to have a new type.

**Comment by zackpollard** [comment]
Sounds good to me, you could switch internally to use tags for the GPU jobs, so anything that requires GPU automatically gets tagged with GPU, and the GPU workers are just nodes with a GPU tag automatically. Avoids having extra complexity internally for you and normal users don't need to understand the tagging system if they don't want to, as it'll all be applied automatically.

**Comment by HaveAGitGat** [comment]
Yeah true that would work quite nicely.

**Comment by Aesir** [comment]
Rather than GPU directly as the tags, I would use the GPU capabilities options as the tags. Otherwise, this sounds great.

**Comment by HaveAGitGat** [comment]
@Aesir sorry not too sure what you mean. Mind expanding?

**Comment by Aesir** [comment]
I'm coming at this from the standpoint that tagging could be used to streamline a lot of the different backend systems on a server, which might be different from the view you're taking. 

So basically, rather than having a `GPU` tag, I'm saying you should have the tags focused on capabilities and have those tags get assigned to the "GPU" set of worker processes. This gives the user a little more control over where exactly something happens rather than having the server guess (you can still get the same nice default behavior through the default tag set). 

Essentially this
![image](https://user-images.githubusercontent.com/447759/222997585-9bd1d7e3-75c8-446a-9829-1c11011e02f4.png)
becomes a set of tags `nvenc`, `qsv`, `vaapi`, and `videotoolbox` with that set of tags assigned to GPU worker processes by default.[^1]  This should allow a lot of streamlining of the node/worker selection logic down to making sure the sets of tags match up and maybe popping a warning up on the UI if no workers satisfy a plugin's set of tags. 

This could also future-proof tdarr a bit. If, for example, peripherals specifically for AI become commonplace and people want to use them for upsampling, it's just adding another worker pool and tagging it appropriately rather than having to go in and add another set of logic for a new pool. 

[^1]: I would have a basic and advanced split in the UI here with, basic looking like it does now, and advanced letting you assign tags to worker types (which also applies them as tags on the node level). An additional set of tags would be assigned on the node level. The tags actually applied to a node would be the union of Node Tags (e.g. `Linux`), CPU Worker Tags (e.g. `FastTranscode`), GPU Worker Tags (e.g. `nvenc`), etc. Plugins then can have a set of tags as requirements for their Nodes/Workers, e.g. `Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only` would require the `nvenc` tag on a node and an open `nvenc`-tagged worker on that node to run.

**Comment by ionred** [comment]
@HaveAGitGat just checking my understanding here before accidentally putting in a duplicate request. 

This issue/request would handle a situation where you have multiple systems with different hardware that all need different FFMPEG parameters based on that respective hardware? Is that correct?

Example for transcoding to HEVC 
System 1: Intel QSV only, via vaapi. 
System 2: AMD CPU/GPU using standard profile
System 3: Intel CPU/NVIDIA GPU using cuda

**Comment by Aesir** [comment]
The way I explained it in my request, it would **not** cover that situation. You could set it up so that you have different libraries with different settings and only certain systems could process each library with the request I wrote, but not do it directly. 

I would really question why you'd want to set up your Tdarr this way though. I know that using the hardware you have is slightly faster, but GPU transcoding tends to give inferior results compared to CPU transcoding and isn't that much faster unless you have multiple GPUs in a box. If you just used CPU transcoding for all 3 systems you'd get consistent results of a higher quality across all 3 machines without being much slower than it would be with a GPU-based setup. Unless you're doing hundreds of blue-rays at once I doubt you'd notice without really paying attention to timers.

**Comment by ionred** [comment]
I get your point, but just having gone through most of a retranscode of my entire library of 12k items to appropriate bitrates and codecs, it definitely takes time. Even if I was going the all cpu route, I’d prefer use Intel QSV (where possible) but that isn’t always available - such as when running on an AMD cpu.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HaveAGitGat** [comment]
@ionred no you shouldn't need this for that. You can use the 'Check Node Hardware Encoder' flow plugin and then do custom arguments for each situation, for example:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5e2637fa-ef1f-4f3f-8727-6cba94b5a159)

**Comment by HaveAGitGat** [comment]
You can also use `Check Flow Variable` and input `{{{args.nodeHardwareType}}}` which will check this select box value (`Any` will be `-`):

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/ddecf1b2-8f98-4cd2-a57f-55ce1fff3419)

**Comment by HaveAGitGat** [comment]
I've now implemented this for the next version, just testing it out now. Here's how it works.

For now there are 2 types of plugin which allow using the tags system:
```
Requeue
Worker Type
```

`Worker Type` automatically checks the current worker matches the required worker type and node tags, if no match then it requeues the item in the staging section for other workers:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0e112a09-281b-43af-af95-d86961db708b)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/8de93a3b-4907-4de0-abf7-1511bfb7a643)

You set the Node tags in the Node options panel:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/fa51350d-dfe9-4450-83fe-608817ee9181)

So here a CPU worker picks up the item, the tags don't match so it requeues the item:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bc00a96a-06e7-4c8d-9096-e97c8ba6a2e5)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/fbe07bdf-d53f-4e14-8589-42c249945f50)


The `Requeue` plugin allows your to force requeue an item with specific tags.

So now it's possible to have multiple different worker types and nodes working on the same flow.

You can try the system using these:

```
haveagitgat/tdarr_acc:dev_2.20.01_2024_06_04T07_41_42z
haveagitgat/tdarr_node_acc:dev_2.20.01_2024_06_04T07_41_42z
```

New plugins have been merged but won't be possible to use unless you use Tdarr `2.20.01` (prod not released yet)

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/657

**Comment by HaveAGitGat** [comment]
2.20.01 released

**Comment by Darkatek7** [comment]
SO how will i be able to aacomplish this in my scenario?
![image](https://github.com/user-attachments/assets/7c616797-f219-4250-94b1-234b641d5ca3)
![image](https://github.com/user-attachments/assets/08f8fc98-5a05-4419-b0fe-5499391a0fbc)
