### ISSUE TITLE
vmalloc error

### ISSUE THREAD

**Issue by Renegade605** [HaveAGitGat/Tdarr#751]
**Describe the bug**
Full system lockup; hard reset required.

Start of errors in syslog:
```
Mar  9 07:50:47 Global-Dynamics kernel: tdarr-ffmpeg: vmalloc error: size 34359493648, exceeds total pages, mode:0xcc0(GFP_KERNEL), nodemask=(null),cpuset=f4c80627fd7cdc0d1e0ec602a1d2b1112d036896019ad53a2970547a55c7c2c5,mems_allowed=0
Mar  9 07:50:47 Global-Dynamics kernel: CPU: 22 PID: 9399 Comm: tdarr-ffmpeg Tainted: P        W  O      5.19.17-Unraid #2
Mar  9 07:50:47 Global-Dynamics kernel: Hardware name: Supermicro Super Server/X10SRL-F, BIOS 2.0 12/17/2015
```

**To Reproduce**
Steps to reproduce the behavior: _unknown_

**Please provide the following information:**
 - OS: Unraid v6.11.5
 - Tdarr Docker v2.00.19

[Tdarr_Node_Config.txt](https://github.com/HaveAGitGat/Tdarr/files/10937634/Tdarr_Node_Config.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/10937637/Tdarr_Node_Log.txt)
[syslog-192.168.0.1.log](https://github.com/HaveAGitGat/Tdarr/files/10937638/syslog-192.168.0.1.log)

**Comment by HaveAGitGat** [comment]
ty for the logs. This an ffmpeg issue (Tdarr uses Jellyfin ffmpeg https://github.com/jellyfin/jellyfin-ffmpeg) so not sure I can help with that but a quick google just seems to point to not having enough memory for the content being transcoded. What source type of file are you transcoding? 4K and 8K can use a lot of RAM etc

**Comment by Renegade605** [comment]
Thanks for the update.

Is this VRAM or system RAM?

I do have 4K in the list but they're almost always already HEVC so the GPU worker shouldn't have to touch them.

I do have the container limited to 8GB RAM cause I found it had a tendency to suck it back if it was allowed to use more, but I could probably fine tune that amount. I had read that tdarr doesn't tend to respect running at low priority and I don't want it to affect other containers that are running.

**Comment by HaveAGitGat** [comment]
Think it's RAM but not 100% sure.

Yeah perhaps monitor the ffmpeg process while it's running to see how much RAM it's using. It might have short spikes of increased RAM which hit the limit you set.

**Comment by HaveAGitGat** [comment]
Feel free to open an issue here if you have the same issue in future ty:
https://github.com/jellyfin/jellyfin-ffmpeg/issues
