### ISSUE TITLE
Need a way to re-queue items automatically

### ISSUE THREAD

**Issue by Tailslide** [HaveAGitGat/Tdarr#752]
**Is your feature request related to a problem? Please describe.**
I would like to only transcode items after a certain amount of time has passed. I made a plugin that prevents the file from getting processed if the modified stamp is in the last X amount of time but then it goes to status "Not Required" and never gets processed again unless I manually re-queue it from the UI.

**Describe the solution you'd like**
Any one of these would solve my issue and be useful to others I think:
1. An option to automatically queue files at a user defined interval based on criteria (like codec h264, status "not required")
2. Alternatively another status instead of not required, like re-queue later that the plugin can set.
3. An option so files can get filtered from being added to the database based on modified stamp.

**Describe alternatives you've considered**
I tried looking at the Tdarr api but don't see an easy way to use it to requeue the files.

**Comment by supersnellehenk** [comment]
There's a 'hold' option in the library settings that can hold an item in a separate queue for X amount of seconds before they get thrown into the transcode queue. Wouldn't that suffice?

**Comment by Tailslide** [comment]
That delays based on when they go into the queue not on the modified stamp which are two different things (think dealing with a large backlog of files).   Assuming I have no backlog and I convert my 30 day delay into seconds and it accepts a number this large and nothing bad happens to the hold queue if the container gets restarted it might work?

**Comment by HaveAGitGat** [comment]
Quick solution would be to use the api to read through all files and then requeue the ones which are older than your specified date. Can then have it running on a loop daily or something.

**Comment by HaveAGitGat** [comment]
On my phone atm sorry but would be something like this 

```
const filesResponse = await request(host)
  .post('/api/v2/cruddb')
  .send({
    data: {
      collection: 'FileJSONDB',
      mode: 'getAll',
    },
  })
  .set('Content-Type', 'application/json')
  .set('Accept', 'application/json');

const files = filesResponse.body;

const thirtyDaysAgo = Date.now() - (30 * 24 * 60 * 60 * 1000); // 30 days in milliseconds

for (const file of files) {
  if (file.TranscodeDecisionMaker === “Not required” && file.statSync.mtimeMs < thirtyDaysAgo) {
    console.log(`${file.path} is older than 30 days.`);
    // Make a POST request to update the file's TranscodeDecisionMaker to 'Queued'
    const updateResponse = await request(host)
      .post('/api/v2/cruddb')
      .send({
        data: {
          collection: 'FileJSONDB',
          mode: 'update',
          docID: file._id,
          obj: {
            TranscodeDecisionMaker: 'Queued',
          },
        },
      })
      .set('Content-Type', 'application/json')
      .set('Accept', 'application/json');

    console.log(`Updated ${file._id}: ${updateResponse.body}`);
  }
}

```

**Comment by Tailslide** [comment]
Thanks that should get me there!

**Comment by Routhinator** [comment]
I'd like to reopen this. Same request, but for automatically cancelled jobs for stalled worker detection. Files didn't fail processing because a worker stalled, the worker did - and reprocessing these always succeeds, however currently only if I go and manually tend the queue. There are cases where automatic re-queue of a file is necessary.

I'm feeling the pain of this right now because of a ghost in my worker that's causing a stall, possibly something with GPU time slicing, that's on me - but it has surely highlighted this issue for me @HaveAGitGat

**Comment by PilaScat** [comment]
> I'd like to reopen this. Same request, but for automatically cancelled jobs for stalled worker detection. Files didn't fail processing because a worker stalled, the worker did - and reprocessing these always succeeds, however currently only if I go and manually tend the queue. There are cases where automatic re-queue of a file is necessary.
> 
> I'm feeling the pain of this right now because of a ghost in my worker that's causing a stall, possibly something with GPU time slicing, that's on me - but it has surely highlighted this issue for me [@HaveAGitGat](https://github.com/HaveAGitGat)

I need this as well

**Comment by djbacon** [comment]
> I'd like to reopen this. Same request, but for automatically cancelled jobs for stalled worker detection. Files didn't fail processing because a worker stalled, the worker did - and reprocessing these always succeeds, however currently only if I go and manually tend the queue. There are cases where automatic re-queue of a file is necessary.
> 
> I'm feeling the pain of this right now because of a ghost in my worker that's causing a stall, possibly something with GPU time slicing, that's on me - but it has surely highlighted this issue for me [@HaveAGitGat](https://github.com/HaveAGitGat)

Yes, this would be a nice feature.
