### ISSUE TITLE
Support for debian/ubuntu system custom CA Certificates

### ISSUE THREAD

**Issue by erasedhammer99** [HaveAGitGat/Tdarr#753]
**Is your feature request related to a problem? Please describe.**
Currently, if I have TLS inspection configured on my firewall, tdarr does not pull from system trusted CA Certificates and fails to connect to tdarr.io and backblaze. I am running Debian 11, my ca-certificates file is located at /etc/ssl/certs/ca-certificates.crt
From a security perspective, servers in a network should be inspected and not have to be bypassed. 

**Describe the solution you'd like**
For the linux updater, please include the function to check server certificates against system trusted certificates in /etc/ssl/certs/ca-certificates.crt for HTTPs connections. Or add config option to specify ca-certificates path for  updater.

**Comment by HaveAGitGat** [comment]
Think this can be set using env variable:
`export NODE_EXTRA_CA_CERTS=[your CA certificate file path]`
