### ISSUE TITLE
No output file produced

### ISSUE THREAD

**Issue by Nova849** [HaveAGitGat/Tdarr#755]
**Describe the bug**
When I try to run a Node on my windows machine it says no output file has been produced. I have the unraid server version of Tdarr and the Tdarr worker. The worker is happily plugging away so I am wondering if I have something misconfigured. I had this working when I was going from 264 to 265. But now that I want to convert to Av1, I can't get the windows node to reach the server. I can create files and delete files from the mapped drive but the Tdarr node can't seem to do it. I can see files changing in the mapped drive as the unraid docker worker continues to execute. Even tried refollowing space invader ones tutorial on YT again and that put me in the same boat. 

**To Reproduce**
I am running a custom transcoder plugin so I am not sure it's perfectly reproducible. 

**Expected behavior**
Need it to create the file and work through the library on the windows node. 

**Screenshots**
The node log would be the screenshot. Can supply SS's if you need something specific. 

 - OS: For the server, it's on Unraid, the node is a Windows machine.
 - Browser Chrome
 - Version 2.00.20

**Additional context**
[I_43KO1lL-log.txt](https://github.com/HaveAGitGa
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11084535/Tdarr_Node_Log.txt)
[Tdarr_Updater_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11084536/Tdarr_Updater_Log.txt)
t/Tdarr/files/11084534/I_43KO1lL-log.txt)

I am using a handbrake preset that I created in the plugin creator. I saw this in the documentation (https://docs.tdarr.io/docs/library-setup/transcode-options/handbrake-presets) and I was wondering if whatever this page is mentioning is the root of my issue. I can't seem to wrap my head around what exactly it's trying to say.

**Comment by HaveAGitGat** [comment]
Please post job report: 
https://docs.tdarr.io/docs/other/job-reports/

**Comment by Nova849** [comment]
[I_43KO1lL-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11086148/I_43KO1lL-log.txt)

**Comment by HaveAGitGat** [comment]
Ty, ps not sure what kind of formatting you're trying to do but doesn't seem right:
![image](https://user-images.githubusercontent.com/43864057/228314805-12aedadc-72df-463f-bc14-abfe6705f828.png)
![image](https://user-images.githubusercontent.com/43864057/228314874-ed6571ee-9552-4192-8595-b032d877bbfc.png)

**Comment by HaveAGitGat** [comment]
Seems the preset `Super HQ 2160p60 4K AV1 Surround` you're trying to use isn't supported (HandBrake changes the names around sometimes). Go onto the help tab and into the handbrake terminal and type `--preset-list` then `Run` to see preset list. Reopen if needed ty.

**Comment by Nova849** [comment]
I found "Super HQ 2160p60 4K AV1 Surround" in the server under "--preset-list" but it's not in the node list when the error spits out. Is there a way to get this preset into the node? I feel like they should be the same since they are running the same version and it's a native preset in regular handbrake.

**Comment by HaveAGitGat** [comment]
Think the Node is using 1.5.1 (updated for next release) so quick solution is to download 1.6.1 here https://handbrake.fr/downloads2.php and replace the HandBrakeCLI.exe in the Tdarr_Node assets folder or set the `handbrakePath` path in the Tdarr_Node_Config.json

**Comment by Nova849** [comment]
@HaveAGitGat That fixed it, thank you for the help. I really appreciate the quick responses to all our issues. Also, keep up the amazing work! Love the software!!!

**Comment by HaveAGitGat** [comment]
Ty :) pleased it’s working
