### ISSUE TITLE
GPU workers to do *certain* CPU tasks

### ISSUE THREAD

**Issue by Renegade605** [HaveAGitGat/Tdarr#756]
**Is your feature request related to a problem? Please describe.**
Certain subtitle codecs cause Nvidia GPU & FFMPEG plugin to error out. They can be removed in advance via 'remove streams by specified property' plugin. However, when using separate CPU/GPU nodes, the files can be queued to the GPU node before passing through the CPU node, and the process still errors out.

**Describe the solution you'd like**
Mark certain steps in the plugin stack to be CPU tasks that run on GPU workers instead. This can ensure that the problem streams are removed from the file before the GPU transcode, without allowing the GPU worker to run *all* the CPU tasks.

**Describe alternatives you've considered**
I first considered that if a file errors on one type of node, allow it to run on the other type and then retry. (ie. GPU node throws error, run the file on CPU node, retry on GPU node: no error.) However, the above is a much cleaner solution imo.

**Additional context**
Problem subtitles that brought this to my attention are codec_tag_string: tx3g present in some MP4 files.

**Comment by HaveAGitGat** [comment]
2.00.20 has an option in library settings to force plugins to be processed sequentially which would fix your issue. Can use the prerelease if you like https://docs.tdarr.io/docs/releases/changing-version

haveagitgat/tdarr_acc:dev_2.00.20_2023_03_28T20_53_04z

**Comment by HaveAGitGat** [comment]
Other ideas are sort of covered by https://github.com/HaveAGitGat/Tdarr/issues/748 so will close this ty

**Comment by HaveAGitGat** [comment]
Will be possible in next version, can try dev version here: https://github.com/HaveAGitGat/Tdarr/issues/748#issuecomment-2146710875
