### ISSUE TITLE
Check if Original Source File Exists

### ISSUE THREAD

**Issue by Renegade605** [HaveAGitGat/Tdarr#757]
**Is your feature request related to a problem? Please describe.**
When using Sonarr, multiple different versions of an episode can be downloaded in quick succession when it first airs. If the version that Tdarr is working on is replaced during the transcode process, it will dump the output file in the directory leaving two versions of the same episode (Sonarr only tracks the existence of one file at a time, so will not manage/delete one of them).

**Describe the solution you'd like**
At each step in the plugin stack (including between job accepted / copying), check if the original source file still exists. If it does not, abandon the job and delete the cache file(s), expecting the new version to be queued at some point. 

This may be desirable behaviour in general, as if a file is deleted for any reason we are unlikely to want a transcoded version to appear on its own later. 

**Describe alternatives you've considered**
Tried putting the output files in a different folder and calling the Sonarr API to import them. Unfortunately, the API exposes only the 'automatic import' which often takes no action as the output file is the same quality and therefore 'not an upgrade for existing' (Sonarr's terminology). 

Even if it did expose manual importing or there was another way to force import, this would just lead to another race condition where a better quality file is replaced by the transcode output of a lower quality one.

**Comment by HaveAGitGat** [comment]
You could use this option to hold the files for say 24 hours to get around this issue:
![image](https://user-images.githubusercontent.com/43864057/229025332-53b49f91-3b7b-4610-acf3-02d44e2023ae.png)

Could also add a plugin to the top of the plugin stack which checks if the original file still exists (the plugin stack is cyclic so would check between plugin runs)
