### ISSUE TITLE
Hardware transcoding is not possible

### ISSUE THREAD

**Issue by cykcoco** [HaveAGitGat/Tdarr#758]
OS：unraid 6.11.5
CPU:12900K
docker tdarr server2.00.19
vainfo from docker:
"# /bin/bash
root@c40ecf40a488:/# vainfo
Trying display: wayland
error: XDG_RUNTIME_DIR not set in the environment.
Trying display: x11
error: can't connect to X server!
Trying display: drm
libva info: VA-API version 1.16.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.16 (libva 2.16.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.6.4 (aca8ee0)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointEncSlice
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSlice
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointEncSlice
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
”
ls /dev/dr from docker:
"root@c40ecf40a488:/# ls /dev/dri
card0  renderD128"
Although docker has driven iGPU, it is not used when transcoding.iGPU is doesn't work.
I will attach pictures and logs, hope there is a solution. Thank you！
[logs.txt](https://github.com/HaveAGitGat/Tdarr/files/11118151/logs.txt)
![CPU GPU LOAD](https://user-images.githubusercontent.com/96184463/229022740-c68fc5ee-8442-4325-9437-794da00f98cb.png)
![Transcoding interface](https://user-images.githubusercontent.com/96184463/229022899-60fda61b-bfbf-4272-b18c-920dc3712723.png)
![Transcoding settings](https://user-images.githubusercontent.com/96184463/229022911-f16fa364-6ee5-47e1-bfcd-937fbaa9d7a4.png)
[Transcoding logs.txt](https://github.com/HaveAGitGat/Tdarr/files/11118166/Transcoding.logs.txt)

**Comment by HaveAGitGat** [comment]
Hello, which plugin are you using? Make sure to use a plugin which utilizes qsv/vaapi such as `Tdarr_Plugin_bsh1_Boosh_FFMPEG_QSV_HEVC`

![image](https://user-images.githubusercontent.com/43864057/229024415-16f16e09-c75b-4a2f-9643-37e8f444b169.png)

**Comment by cykcoco** [comment]
Thanks for the reminder, I didn't notice that the plugin also needs to be manually added inside the execution sequence. I'll test right away

**Comment by HaveAGitGat** [comment]
Yeah the default plugin just uses CPU (the other one is NVENC) so for QSV you have to add a qsv/vaapi plugin specifically.

Reopen if needed thanks.

**Comment by cykcoco** [comment]
> 是的，默认插件只使用 CPU（另一个是 NVENC），因此对于 QSV，您必须专门添加一个 QSV/vaapi 插件。
> 
> 如果需要，请重新打开，谢谢。

Good news and bad news
On my other 10th server（10400）, QSV worked fine and output correctly.But on my 12th server（12900K）, QSV does not work properly and will report an error. Only vaapi is available.The same plugin is used
I will send you a log of the error(from 12900K server）.
plugin1:"Tdarr_Plugin_bsh1_Boosh_FFMPEG_QSV_HEVC"  Only the 10th is available,The 12th will report an error
plugin1:"Tdarr_Plugin_Mthr_VaapiHEVCTranscode" The 12th can be used，There is no test on the 10th, but I guess it is okay
By the way, QSV is more efficient than VAAPI. Both the transcoding rate and the compression volume are stronger than QSV

**Comment by HaveAGitGat** [comment]
You could potentially try the 2.00.20 pre-release version as it may fix your issue:

`docker pull haveagitgat/tdarr_acc:latest`

https://docs.tdarr.io/docs/releases/changing-version#pre-releases
