### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by wuast94** [HaveAGitGat/Tdarr#759]
**Describe the bug**
After last update container wont start with log message: s6-overlay-suexec: fatal: can only run as pid 1

**To Reproduce**
Just updated the container

**Expected behavior**
Should just start as normal 

**Screenshots**
-

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Config.zip](https://github.com/HaveAGitGat/Tdarr/files/11140615/Tdarr_Config.zip)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
no logs written

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
Container doesent start 

 - OS: Unraid Docker
 - Version 2.00.20

**Additional context**

**Comment by HaveAGitGat** [comment]
Hi, perhaps try this: https://community.home-assistant.io/t/s6-overlay-suexec-fatal-can-only-run-as-pid-1/426969/3

**Comment by HaveAGitGat** [comment]
https://community.home-assistant.io/t/s6-overlay-suexec-fatal-can-only-run-as-pid-1/426969/3
https://www.home-assistant.io/blog/2022/06/01/release-20226/#breaking-changes

So the comment there points to this
: 
```
Home Assistant Container
If you run Home Assistant Container in Docker (e.g., using Portainer, Docker (Compose), QNAP, and others), please make sure you are not specifying an init process.

This can be an init configuration option in your Docker management tools or Docker Compose, or the --init command line flag on the raw Docker command. These should NOT be set, as Home Assistant ships with the S6 init system.

While you are at it, make sure you also do not set a cmd or entrypoint. Setting these are not breaking, however, you should not set them.

([@pvizeli](https://github.com/pvizeli) - [#72425](https://github.com/home-assistant/core/pull/72425)) ([documentation](https://www.home-assistant.io/installation))
```


Reopen if needed ty
