### ISSUE TITLE
Filter to skip file extension

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#763]
**Is your feature request related to a problem? Please describe.**
I have a llibraries counting over 50k files total
Those libraries contain s some old .avi and some .ts that i would like to transcode to mp4 or mkv BUT i don't want to touch all other files.
There is a filter "at scan level", that i cant use because i want all files to be queued for health check
There are two filters "at transcode queue level" but are on resolution or codec  that i can't use because i want to queue for transcode based on file extension.

**Describe the solution you'd like**
I think a filter is needed that would allow adding to health check queue but skip transcode queue, based on file extension.

**Comment by HaveAGitGat** [comment]
Hi I've added plugin `Tdarr_Plugin_00td_filter_by_file_property`.

So can do something like this:

![image](https://user-images.githubusercontent.com/43864057/230446683-03169e74-90fe-48fe-b21e-335f45294536.png)

Hope that helps.

**Comment by Kedryn** [comment]
Yep, but this means that all files get queued and processed by that plugin.
Instead, i'm asking for a filter to skip the queue entirely, if not needed.

**Comment by HaveAGitGat** [comment]
Hmm yeah the above would practically be the same but just take longer.

Perhaps can add functionality to add your own custom logic for the queue filter.

**Comment by HaveAGitGat** [comment]
Added for next version:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/ab08d74d-c878-4930-8091-be4bbe8e96ee)
