### ISSUE TITLE
Tdarr should copy multiple files in parallel (from cache to destination)

### ISSUE THREAD

**Issue by kafisatz** [HaveAGitGat/Tdarr#769]
**Is your feature request related to a problem? Please describe.**
Copying files is slow.
As far as I can tell Tdarr is only copying one file at a time.

**Describe the solution you'd like**
Tdarr should copy multiple files in parallel (from cache to destination)

I am converting flac to mp3. Each resulting file is about 10MB of size. Tdarr takes about 1 second to move a file from the cache to the destination.

**Describe alternatives you've considered**
My NAS is connected via 10GbE to my Tdarr node and should reach about 400 MB/s.
A quick test from another client (on 1GbE) shows that I should easily be able to copy about 7 mp3 files (of 10MB) per second.

**Additional context**

<img width="813" alt="tdarr" src="https://user-images.githubusercontent.com/15026865/233108730-eada8055-780c-4c86-b18e-485767b6d835.png">

**Comment by HaveAGitGat** [comment]
With Tdarr Flows the worker itself does the file manipulation so will happen in parallel depending on how many workers you have:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0382c52e-0cda-4b58-afa9-6ae466c2f308)

**Comment by HaveAGitGat** [comment]
Beta released the other day, feel free to reopen if you have any issues.
