### ISSUE TITLE
[request] image optimization

### ISSUE THREAD

**Issue by hbednar** [HaveAGitGat/Tdarr#770]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can you add support for image optimization, the below tool would be an option to use.

GUI:
https://github.com/flozz/yoga-image-optimizer

CLI:
https://github.com/wanadev/yoga

**Describe alternatives you've considered**

**Additional context**

**Comment by HaveAGitGat** [comment]
I think this should be possible using this method:
https://github.com/HaveAGitGat/Tdarr/issues/498#issuecomment-1458609599
