### ISSUE TITLE
Cache folder issue between two windows machine

### ISSUE THREAD

**Issue by cleverchimp** [HaveAGitGat/Tdarr#771]
My understanding is the cache (local D drive on tdarr server) have to be the same folder for all nodes. I can access the path from the nodes computer but I'm getting this error :

[2023-05-02T09:46:10.204] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, access 'D:/Transcode'

at Object.accessSync (fs.js:228:3)

at Object.accessSync (pkg/prelude/bootstrap.js:1474:34)

at _0x540c46 (C:\snapshot\node\srcug\workers\worker1.js:1:51990)

at C:\snapshot\node\srcug\workers\worker1.js:1:53743

at _0xbd8e34 (C:\snapshot\node\srcug\workers\worker1.js:1:12805)

at [Object.next](https://object.next/) (C:\snapshot\node\srcug\workers\worker1.js:1:11044)

at C:\snapshot\node\srcug\workers\worker1.js:1:10521

at new Promise (<anonymous>)

at __awaiter (C:\snapshot\node\srcug\workers\worker1.js:1:9867)

at preProcessFile (C:\snapshot\node\srcug\workers\worker1.js:1:51403) {

errno: -4058,

syscall: 'access',

code: 'ENOENT',

path: 'D:/Transcode'

}

Below is the JSON config :

{

"server": "//Plex",

"node": "T:/"

}

],

"logLevel": "INFO",

"priority": -1

}

**Comment by cleverchimp** [comment]
I believe it is a bug, changing the cache to network path works.

**Comment by supersnellehenk** [comment]
Cache is meant to be shared between server & node. So switching it to a network path and it suddenly working is to be expected.

**Comment by HaveAGitGat** [comment]
@supersnellehenk I think they mean they have `D:/Transcode` mapped on the node. @cleverchimp this is usually some sort of permissions issue, try checking the user you're running the Node as. Make sure not to run as admin.

**Comment by Shadowknite** [comment]
I believe the issue is how they are mapping the cache folder. `D:\transcode` on the server when the node config file says the server path is `//Plex` and on the node the path is mapped to `T:/`

the config file that they posted for reference
```
{

"server": "//Plex",

"node": "T:/"

}
```

**Comment by cleverchimp** [comment]
On the serve

> @supersnellehenk I think they mean they have `D:/Transcode` mapped on the node. @cleverchimp this is usually some sort of permissions issue, try checking the user you're running the Node as. Make sure not to run as admin.

Might be, on the Tdarr server, I am using a local admin account while on the node computer I'm using MSN account with admin privilege.

**Comment by cleverchimp** [comment]
> I believe the issue is how they are mapping the cache folder. `D:\transcode` on the server when the node config file says the server path is `//Plex` and on the node the path is mapped to `T:/`
> 
> the config file that they posted for reference
> 
> ```
> {
> 
> "server": "//Plex",
> 
> "node": "T:/"
> 
> }
> ```

I mapped the transcode folder on the Tdarr server (a local SSD drive - //PLEX) on the node computer (T:/), I can access the folder just fine from the node computer.

**Comment by FrankR-7** [comment]
Hi, I have a similar issue to this one, but I can't really find how to relate the solution to my case. Anyone mind giving [this Reddit post](https://www.reddit.com/r/Tdarr/comments/137787p/help_path_translators_on_remote_node/) a quick look and lend a hand?

**Comment by HaveAGitGat** [comment]
Makes most sense to me to have it on the NAS, that way if you add another PC/Node at a later date then you don't need to keep your local server/PC on all the time.

Although if you have one node and want fastest read/write performance then would make sense to put the cache on the same location as the Node so less copying over network.
