### ISSUE TITLE
[request] Store statistics when using output folder

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr#772]
**Is your feature request related to a problem? Please describe.**
"Transcode: Success/Not required (0)" count will stay at 0 when using the Output folder option for library's. 

**Describe the solution you'd like**
Keep track of the transcoded files/statistics when using the Output folder option.

**Comment by molly78** [comment]
I second this. It’s a bug for sure as if you use the output folder option to transcode into a different folder nothing is logged :-(

**Comment by HaveAGitGat** [comment]
Thanks, are you able to provide able to provide a job report? 

https://docs.tdarr.io/docs/other/job-reports/

Output folder stats were working fine when I ran it a minute ago:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/f79bb43b-5276-41a5-9fd4-6cebe9a7a224)

**Comment by moostmartijn** [comment]
This is actually the bug... There is no job report to be found when using the output folder. 

I can give some more info about my setup:

I download to an SSD (Volume2) with the following folders: 
<img width="883" alt="Schermafbeelding 2023-06-16 om 10 32 08" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/57e3aa86-7009-48d6-8b19-a498d7768d2a">

Radarr picks up the nzb in the corresponding watchfolder, Sabnzbd download the movie and when it's done it is placed in the Tdarr -> Sonarr folder. Tdarr picks up the movie and starts transcoding. After the transcoding is done it is placed in the Usenet -> Complete -> Sonarr folder and Radarr will import it and place it in the media folder (Volume1)

After all this is done, there are no job reports or statistics to be found.

Please let me know if you need more info.

**Comment by moostmartijn** [comment]
Some extra info:

The only files that are logged are the ones that don't need transcoding ('Not required' Transcode status). The other files (most of them) that are transcoded are not logged in the 'Transcode: Success/Not required' tab.

**Comment by molly78** [comment]
> Thanks, are you able to provide able to provide a job report?
> 
> https://docs.tdarr.io/docs/other/job-reports/
> 
> Output folder stats were working fine when I ran it a minute ago: ![


Ok I caught it on a screen record, finally!

‘it’s only on the library that transcodes to a different output folder

After processing the file, it shows up in the transcoded queue for about 3 seconds then disappears

it also now doesn’t show up when I download the csv of the queue results

and I just updated to the latest version yesterday

thanks!

**Comment by HaveAGitGat** [comment]
The output folder is a bit of a PIA atm as it goes against how Tdarr was originally designed to operate. With Tdarr Flows you can choose what you'd like to happen. So in the following scenario the new file will appear in the transcode success table.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/965f6578-53ed-4c5a-86e1-7f23c47daa32)

Whereas with this setup the original file will appear in the transcode success table.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d9b6a8ef-6e7d-4c60-aca2-51dcf3cf3c3b)

**Comment by HaveAGitGat** [comment]
Tdarr Flows beta has been out for a while and seems to be working okay so please have a go at using it instead of the output folder option. At some point in the future the output folder option will be removed - as I mentioned before it causes some issues with how it integrates into everything atm so have been streamlining things in Flows.
