### ISSUE TITLE
[request] Delete empty folders after moving from original location to output folder

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr#773]
**Is your feature request related to a problem? Please describe.**
In the original location of the library Tdarr looks for files, I'm stuck with a lot of empty folders when using the Output folder option.

**Describe the solution you'd like**
Delete empty folder after moving file from original library location to final output folder location

**Describe alternatives you've considered**
Right now I'm using a bash script as a cron jon to remove empty folders.

**Comment by HaveAGitGat** [comment]
Will move this under here thanks:
https://github.com/HaveAGitGat/Tdarr/issues/85
