### ISSUE TITLE
[request] Move extra files when using the output folder option

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr#774]
**Is your feature request related to a problem? Please describe.**
Tdarr is now only moving the transcoded video file when using the Output folder option. You have to manually copy extra files to the output folder location if you want them. 

**Describe the solution you'd like**
An option to move extra files to the final output folder location such as .srt, .nfo, etc. 

**Additional context**
Radarr has this option the import extra files:
<img width="658" alt="Schermafbeelding 2023-05-03 om 10 38 50" src="https://user-images.githubusercontent.com/31592734/235869334-3ee2cbb2-aa31-4b93-a902-05164d007f2f.png">

**Comment by HaveAGitGat** [comment]
Will also move this under here ty:
https://github.com/HaveAGitGat/Tdarr/issues/85
