### ISSUE TITLE
mkvpropedit error - Unable to locate libboost_filesystem.so.1.74.0

### ISSUE THREAD

**Issue by pieman3000** [HaveAGitGat/Tdarr#775]
**Describe the bug**
Warning message appears in log when mkvpropedit plugin is run.

Warning message is:

/usr/bin/mkvpropedit: error while loading shared libraries: libboost_filesystem.so.1.74.0: cannot open shared object file: No such file or directory

**To Reproduce**

Run a stack with this plugin
[V8hPwN_9B.js.txt](https://github.com/HaveAGitGat/Tdarr/files/11405171/V8hPwN_9B.js.txt)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/948361/236428009-0a8c2ced-5103-4b60-af56-72fc1f908df2.png)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Config.json.txt](https://github.com/HaveAGitGat/Tdarr/files/11405155/Tdarr_Server_Config.json.txt)
[Tdarr_Node_Config.json.txt](https://github.com/HaveAGitGat/Tdarr/files/11405156/Tdarr_Node_Config.json.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11405163/Tdarr_Node_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Docker
 - Browser Chrome
 - Version 2.00.20

**Additional context**

**Comment by HaveAGitGat** [comment]
Try running `sudo apt-get install mkvtoolnix` to install mkvpropedit. Reopen if needed thanks.
