### ISSUE TITLE
Not Saving what files have been transcoded

### ISSUE THREAD

**Issue by Jessomadic** [HaveAGitGat/Tdarr#776]
**Describe the bug**
Tdarr will rescan when it launches and sometimes readd all the files it finds to the Que regardless if it has processed them already and attempt to process them all again

**To Reproduce**
I'm not 100% sure but it seems to happen when my Computer that Tdarr is running on has Tdarr running and the server is restarted.

**Expected behavior**
That it should save in a db a list of all processed files and compare names to know exactly what it has processed in the past

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
- 
[Tdarr_Node_Config - Copy.txt](https://github.com/HaveAGitGat/Tdarr/files/11413693/Tdarr_Node_Config.-.Copy.txt)
[Tdarr_Server_Config - Copy.txt](https://github.com/HaveAGitGat/Tdarr/files/11413694/Tdarr_Server_Config.-.Copy.txt)
[Tdarr_Updater_Config - Copy.txt](https://github.com/HaveAGitGat/Tdarr/files/11413695/Tdarr_Updater_Config.-.Copy.txt)

Changed to .txt as Github will not allow me to upload json files

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11413696/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11413697/Tdarr_Server_Log.txt)

[Tdarr_Updater_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11413699/Tdarr_Updater_Log.txt)

 - OS: Windows 11 Pro
 - Browser: Chrome

**Comment by Jessomadic** [comment]
![image](https://user-images.githubusercontent.com/35648348/236653030-8970f044-542a-4599-b611-f7ffd1bb2fb9.png)
 I was down to about 100ish files left to process and now it's added all of them

**Comment by HaveAGitGat** [comment]
Typically this happens because the library location isn't available when Tdarr starts up so it detects the files as missing and removes them. The location then becomes available so it scans the files again. Likewise if Tdarr is running and the library location disconnects and reconnects whilst having the folder watcher enabled. So make sure the location is available before starting Tdarr.

**Comment by Jessomadic** [comment]
Other than turning off folder watch is there any other way to avoid this happening?
