### ISSUE TITLE
Files transcode multiple times simultaneously

### ISSUE THREAD

**Issue by Renegade605** [HaveAGitGat/Tdarr#778]
**Describe the bug**
Since 2.00.20 update, some files won't process correctly.

They show up in the CPU processing node, filling all available CPU transcode slots and processing simultaneously. They also show up in GPU processing node, but then disappear without doing anything. When the CPU node is finished, it starts processing the same file again from the beginning of the plugin stack. The files **do not** get added to the staging section while this is happening.

This behaviour repeats indefinitely, until the temporary directory is out of disk space, at which point the job fails. Tdarr does not clean up the cache files made during this process.

There is no record of the job or it's logs or why it failed when clicking on 'Report' in the failed transcodes tab. It's like nothing ever happened as far as Tdarr is concerned.

**To Reproduce**
Unsure. Doesn't seem to be consistent which files it happens with. Requeuing a file that did this might do it again, or might work fine.

**Expected behavior**
Proper transcode, or at least logs of what happened.

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/a342a65e-1d2f-4c4d-a2a6-966a994fd6ba)
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/6c593115-bbc7-458c-9759-7a54ebbc6d73)
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/2a037e70-d7ab-4394-ad28-cc40c603c5b4)
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/5d5fdb08-6b04-4e8c-914b-c6742326a800)
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/081f138a-f202-45be-963b-be0635c7a94b)

**Please provide the following information:**
- Config files
-- Server
```json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.0.2",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "CHOWN_ON_START": false
}
```
-- Node
```json
{
  "nodeID": "EDI",
  "nodeName": "EDI",
  "serverIP": "192.168.0.2",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "platform_arch": "linux_x64_docker_true"
}
```

- Log files
[Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11464926/Server-log.txt)
[EDI-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11464925/EDI-log.txt)
[Global-Dynamics-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11464927/Global-Dynamics-log.txt)

- Worker error
None?

 - OS: Unraid 6.11.5
 - Browser: Chrome 112.0.5615.138
 - Version: 2.00.20

**Comment by HaveAGitGat** [comment]
Hi, which container are you using? There was a small patch to 2.00.20 so make sure to use container `docker pull ghcr.io/haveagitgat/tdarr:2.00.20.1` or `latest`. But perhaps your issue is unrelated.

**Comment by Renegade605** [comment]
Not sure if it had already updated, but Sunday morning is scheduled updates so it's definitely on latest now, and the issue persists.

**Comment by Renegade605** [comment]
Just an added note, the logs not showing up in job history seems to be an issue whether the job suffers this error or not.
![image](https://github.com/HaveAGitGat/Tdarr/assets/5857062/6e17bb88-7ba7-46dc-8c00-b9fd3fee12a8)

**Comment by HaveAGitGat** [comment]
Thanks will take a look at this tomorrow

**Comment by Mordrin90** [comment]
@HaveAGitGat I ran into the same thing earlier today. I've been working on adding addtional nodes after purchasing the pro version a week back - I've been updating nodes and needed to start fresh after noticing the staging queue was 30+ pages. So I requeued them and rebooted the server - I've got the same issue, allot of nodes are running the same file on each worker. Some workers on some nodes seem to be running normally. No error logs. Can provide more info if I can have confirmed what might be helpful.
As above I forced undated the docker running the server to confirm latest version is being run.

**Comment by HaveAGitGat** [comment]
Thanks, had a look into this back when I mentioned and didn’t couldn’t replicate the issue so will have another look with this info. For now could try using 2.00.19

**Comment by Mordrin90** [comment]
@HaveAGitGat All good, once it finished off trying to encode the same few files on multiple workers it appears to have moved on and the staging queue is back to normal. I will stay on the current prod version as rolling back the server and 20 something nodes would be too much of a hassle. I have logs that point to no output file for all workers of a file but for the last one that finishrd it last - worked without error and moved the file. I'm on the side of user error with making changes/reboots on the fly.

**Comment by Renegade605** [comment]
@Mordrin90 are you using the new option to force plugin steps to be executed in order? I am and maybe it's relevant.

I never got to test it without that enabled as the server made it through the backlog of errored transcodes after enough tries over several weeks. Not sure when I'll see the issue again.

**Comment by Mordrin90** [comment]
@Renegade605 if it's the option called "Process Plugins Sequentially" then no. Didn't even see it until you asked.
Unsure if such an option would be a benefit in what I'm doing (h264-h265). I'd suggest just clearing out the staging queue if you have it happen again. I set the staging queue to requeue transcode and once done performed a reboot of the server. Once it all came back online it finished off what files it was running which included duplicates on allot of workers/nodes and error out on all but 1. Once it finished that it moved on to the newly created staging queue. It's run overnight for thr past 6 hours as per normal.

**Comment by HaveAGitGat** [comment]
Ok thanks for the update @Mordrin90

**Comment by HaveAGitGat** [comment]
Reopen if needed thanks.
