### ISSUE TITLE
how to use ffmpeg

### ISSUE THREAD

**Issue by kenpachizero** [HaveAGitGat/Tdarr#780]
Hi all, 
I am new to this and trying to make a plugin to run "ffmpeg custom arguments" this command:
ffmpeg -i input.mp4 -c:v libaom-av1 -r 30 -vf "scale=1920:-1" -c:a libopus -ar 16000 -b:a 160k output.mkv 

in the documentation it says this:
When using FFmpeg, you need to separate the input and output parameters with <io>. FFmpeg Examples:
-r 1< io >-r 24
< io >-sn -c:v copy -c:a copy
< io >-c:v lib265 -crf 23 -ac 6 -c:a aac -preset veryfast
< io >-map 0 -c copy -c:v libx265 -c:a aac
-c:v h264_cuvid<io>-c:v hevc_nvenc -preset slow -c:a copy
Please see the following for help with creating FFmpeg commands:
https://opensource.com/article/17/6/ffmpeg-convert-media-file-formats

To me that is super confusing and unclear what i have to do, my assumption is my command would now be:
< io >-c:v libaom-av1 -r 30 -vf "scale=1920:-1" -c:a libopus -ar 16000 -b:a 160k output.mkv 
or
< io >-c:v libaom-av1
< io >-r 30 
< io >-vf "scale=1920:-1"
< io >-c:a libopus
< io >-ar 16000 
< io >-b:a 160k 
< io >output.mkv 

if would be good if there was an example that directly compares to a ffmpeg command to help make sense of that.

sorry had to make < io >  with space because if i put that in there without it disappears

**Comment by HaveAGitGat** [comment]
FFmpeg itself is separated into input and output arguments, with the input arguments coming before the input file and the output arguments coming after. Tdarr handles the input and output files, so with your command you simply just need to state the input and output argments separated by `<io>`.

So the command you'd enter would just be 

`<io> -c:v libaom-av1 -r 30 -vf "scale=1920:-1" -c:a libopus -ar 16000 -b:a 160k `

**Comment by kenpachizero** [comment]
thank you
