### ISSUE TITLE
Unraid Tdarr won't work after container restart. 

### ISSUE THREAD

**Issue by issacboil** [HaveAGitGat/Tdarr#781]
**Describe the bug**
After I reboot the container or the host, tdarr just gets stuck in a endless bootloop and won't work until I delete the container and create a new container. 

**To Reproduce**
- Reboot the Container or host.

**Expected behavior**
It should reboot and come back up normally. 

**Screenshots**
![Screenshot 2023-05-20 182003](https://github.com/HaveAGitGat/Tdarr/assets/40278713/4f4b1042-bcfb-4fb3-9c99-f9e762a4f701)
![Screenshot 2023-05-20 182011](https://github.com/HaveAGitGat/Tdarr/assets/40278713/12d5ff41-cbac-4005-8e23-22c3317b9811)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
I can provide them if needed, but don't have them atm due to having to reinstall the container for the 5th time today. 
- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**
I am running the Tdarr Container that includes the Tdarr Node.

**Comment by HaveAGitGat** [comment]
Please post the full logs not just screenshots thanks

**Comment by issacboil** [comment]
I swapped separated the Node and Server yesterday but now I run into the same issue after a reboot of the containers and host. I have attached the logs. 
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11525161/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/11525163/Tdarr_Server_Log.txt)

**Comment by HaveAGitGat** [comment]
Reopen if you still have this issue on 2.00.25 thanks, a lot has changed since then.
