### ISSUE TITLE
Delete Sync for Output Folder

### ISSUE THREAD

**Issue by antgiant** [HaveAGitGat/Tdarr#782]
**Is your feature request related to a problem? Please describe.**
I use an output folder for my transcodes. When I delete the source file I would like the transcoded file to be deleted too.

**Describe the solution you'd like**
I would like for transcoded files to be automatically deleted from the output folder when the source file is deleted.

**Describe alternatives you've considered**
An export of deleted source files would also work as it could easily be modified to list transcoded files for delete.
The only other way I have been able to come up with so far is some custom coded script.

**Additional context**
I have a "main" Plex server with a duplicate "travel" Plex server. When I delete files from the "main" server I would like them to also be automatically deleted from the "travel" server.

**Comment by HaveAGitGat** [comment]
In Tdarr the output file is not linked with the input file so not possible to do this. You could do this with a simple shell/js/python script which reads both folders and keeps them in sync. There are also applications such as freefilesync which can do this but Tdarr is not for folder synchronization scenarios atm.
