### ISSUE TITLE
[request] Reorder (or Delete) Default Subtitle Track Based off Description (Sign & Song)

### ISSUE THREAD

**Issue by pchang388** [HaveAGitGat/Tdarr#783]
**Is your feature request related to a problem? Please describe.**
I often have anime that comes with "Sign & Songs" subtitles as default. From what I can tell, this subtitle track only contains subtitles for the songs in the episode and do not provide dialogue subtitles. This is pretty useless to me personally as I don't really care about what the intro/outro songs are saying.

Example:
<img width="453" alt="Screenshot 2023-05-23 at 11 28 19 AM" src="https://github.com/HaveAGitGat/Tdarr/assets/51681873/72ddc17a-01e8-4a97-83ca-f76d5af181d5">

**Describe the solution you'd like**
I would like a way to do the following:
- Be able to set the default subtitle track based on language and description (or lack of), i.e. I want to be able to set as default another subtitle track that is in English but is not "Sign|Song".
- If above is not possible, optionally removing any subtitles with "Sign|Song" or similar (if other subtitle tracks in the target language exist - i.e. so you won't remove it if it's the only subtitle in the target language) and setting a new default subtitle track based on Language (I want english and it can auto-select the next subtitle track that is in English and make it default)

**Describe alternatives you've considered**
So far from what I can tell, there is no community plugin to do this feature after my few hours of searching on google/online. Closest I found was this which is similar but opposite of what I want: https://www.reddit.com/r/Tdarr/comments/109yg5s/set_subtitles_as_forced_if_named_signs_songs/
 - The links are dead in that thread so I am unable to tell what exactly was done

**Additional context**
Using Latest Docker Image of Tdarr, version: `2.00.20 `

**Comment by HaveAGitGat** [comment]
Please open plugin related issues here thanks: https://github.com/HaveAGitGat/Tdarr_Plugins/issues
