### ISSUE TITLE
Option to skip Healthchek or Transcode queues for each library

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#786]
Is your feature request related to a problem? Please describe.
I have some libraries that i want to healthcheck only
and few others that i would go with a Transcode without Healtchecks
So items wont get added to queue if i don't want to transcode them.

Describe the solution you'd like
A couple of options, under "process library" with something like
"Do Healthchecks"
"Do Transcoding"
Either "Do" or "Skip Queue" would be fine.

Describe alternatives you've considered
No alternative found.

**Comment by HaveAGitGat** [comment]
Added for next version: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/a1fc4d00-9274-4be7-9ad2-38d7a262dc94)
