### ISSUE TITLE
Option to copy Transcode options

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#787]
**Is your feature request related to a problem? Please describe.**
when i find a better option/plugin to transcode a library, i have to copy each option/plugins by hand in each other library i have

**Describe the solution you'd like**
A way do update/overwrite Trascoding options of a libray, copying them from another library

**Comment by HaveAGitGat** [comment]
Could try using the duplicate library option in case you haven't already:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/32ce6c23-e6c2-4f70-a2d7-d4d255e57ba2)

**Comment by Kedryn** [comment]
I know that, but let me explain better
i have like 20 libraries with thousand of files each
When i find a better plugin, or a better setting, i have to change every  Transcoding stack of every library

That option you mentioned is to duplicate settings for a NEW library. It's of no help for existing ones.

**Comment by dbensmith** [comment]
> Could try using the duplicate library option in case you haven't already: ![image](https://user-images.githubusercontent.com/43864057/240988292-32ce6c23-e6c2-4f70-a2d7-d4d255e57ba2.png)

Hi @HaveAGitGat, thank you so much for writing and maintaining Tdarr!

I tried duplicating two libraries today so I could keep the transcoding options, but the transcoding options were not preserved and instead reset to default (v2.00.25).

So that proposed solution might not be working right now regardless of other factors.

**Comment by HaveAGitGat** [comment]
Tdarr is moving to Flows which is on a separate tab so you can create/update a single flow and reuse them across multiple libraries. You can also import/export. Will solve this issue:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dddfb8b2-46e3-4c4a-b010-5de6ec098282)

**Comment by HaveAGitGat** [comment]
Beta released the other day so should be working fine.
