### ISSUE TITLE
Option to define how often the plugins are updated

### ISSUE THREAD

**Issue by anym001** [HaveAGitGat/Tdarr#788]
**Is your feature request related to a problem? Please describe.**
There is no real problem, but my NVME is loaded with unnecessary write accesses, because the plugins are updated every hour. 

**Describe the solution you'd like**
Global option where you can define how often the plugins are updated. (Possibly Cron?)

**Describe alternatives you've considered**
No alternatives

**Additional context**
Screenshot attached
![Bildschirmfoto_2023-05-26_07-14-23](https://github.com/HaveAGitGat/Tdarr/assets/109074292/96042fa5-54b2-495c-880c-62a22e76a781)

**Comment by HaveAGitGat** [comment]
Will probably use this:
https://www.npmjs.com/package/node-cron

**Comment by HaveAGitGat** [comment]
2.00.22 released

**Comment by anym001** [comment]
Where exactly can this setting be found?

**Comment by HaveAGitGat** [comment]
FYI in the 2.15.01 plugins are only downloaded when needed (by default it checks every hour but you can still use `cronPluginUpdate` to change the frequency of the checks) but I'd say this option isn't really needed anymore:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6b5cb5de-8fd0-4a95-ac31-9240f67067c1)

**Comment by anym001** [comment]
@HaveAGitGat Oh nice, thank you!
