### ISSUE TITLE
Need a way to run as a service and/or launch on start (Windows)

### ISSUE THREAD

**Issue by strich** [HaveAGitGat/Tdarr#789]
Tdarr seems to have no built in service or script to launch on boot in Windows. Nor have any of the various closed issues work arounds worked well. It really needs something to make this process easier.

**Comment by HaveAGitGat** [comment]
Can try using NSSM or PM2 for this.

So would [download](https://nssm.cc/download) and then run:
```
./nssm.exe install tdarr
./nssm.exe start tdarr

// status
./nssm.exe status tdarr

// stop
./nssm.exe stop tdarr
```

But yeah would be a good to have a built in solution, same for system tray icon. There a few npm libraries that do this but most seem to have not been updated in years so a bit weary of using them.

Interestingly you can also pin CPU cores using NSSM which is of use to some.

**Comment by HaveAGitGat** [comment]
2.00.22 has an option to run in tray:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d795a0b9-fdd3-499f-ad07-feeffe06c5fa)

It also contains a small text file with how to run on startup:

```
Please see:
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

Press the Windows logo key  + R, type shell:startup, then select OK. This opens the Startup folder.

Create a Tdarr Tray shortcut and copy and paste the shortcut into the Startup folder.
```

**Comment by strich** [comment]
This tray app seems to open a window on start up that I have to manually close. It should simply start in the tray without any visual to the user.

**Comment by HaveAGitGat** [comment]
Next update has an option to toggle if the window should show on start.
