### ISSUE TITLE
Transcoded files getting stuck at 100%

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#79]
My files pass the health check, but for some reason the transcode processes get stuck at 100%.

Edit: The first plugin in my stack is Tdarr_Plugin_nc7x_Drawmonster_No_Title_Meta, which is what the files seem to get stuck on.

**Comment by HaveAGitGat** [comment]
@theg00s3 

Thanks for opening an issue. Do the files error out at all and go into the Transcode error tab?

Also have you given it a few minutes after it reaches 100%? The new file is moved to the original folder which can take some time depending on how fast your HDD is.

Anything in the logs when it happens?

**Comment by theg00s3** [comment]
The files don't error out. They just stay at 100% permanently. There's nothing in the logs about it.

Potentially (but unlikely to be) related, quite a few of my files have gone to the transcoding error / cancelled tab with this as their last line when you click the "i" :
`video:157788kB audio:19348kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.326172%`

**Comment by HaveAGitGat** [comment]
What I’d suggest you do is:

1. Create a library that only has 1 file in it.
2. Scan the library as normal.
3. Go onto the Logs tab, delete the logs, and then enable Verbose logs.
4. Run a transcode worker on that 1 file.
5. When it gets stuck, go back to the logs tab and click Load, paste the results here.

**Comment by theg00s3** [comment]
I think I'll have to wait until the rest of my files successfully transcode, as I just tried isolating one file, but it actually worked.

**Comment by theg00s3** [comment]
Nothing's getting stuck now, so I'm gonna close this issue

**Comment by HaveAGitGat** [comment]
@theg00s3 glad to hear it!
