### ISSUE TITLE
Tdarr maxes out CPU/Ram

### ISSUE THREAD

**Issue by Remataklan** [HaveAGitGat/Tdarr#790]
Hello

I would like to start with that im an absolute newb in regards with NAS/Tdarr/docker and such.
On the advise of a friend i installed Tdarr on my synology 923+ using a step-by-step guide found online. The program works fine but Tdarr maxes out both the NAS' CPU and Ram.
I was advised to use a script somewhere...somehow to limit docker usage of cpu/ram. But for the life of it - i dont know where or how to implement such a script. Ive been searching online for 2 weeks now with no success. Either i dont understand what im supposed to do or I cant find anything regarding my setup.
edit: included is a screenshot of a message i always get when trying to limit the cpu via pontainer.

![Screenshot (17)](https://github.com/HaveAGitGat/Tdarr/assets/134976287/4eb9bbdd-c2ce-4abd-be47-675956a69df6)

Is there anyone who can guide me on what to do or refer to me to a source that can help?

Any help is very much appreciated.

Docker version 20.10.3-1308
DSM: 7.1.1-42962 U5
Tdarr: 2.00.20

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaveAGitGat** [comment]
Seems this might not be possible on Synology: https://www.synoforum.com/threads/cpu-limiting.9473/ or have you heard differently?

ChatGPT:

The "NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler" error message is often seen in Docker environments when trying to limit CPU usage, and it means that the Completely Fair Scheduler (CFS) is not available in your Linux kernel.

CFS is a process scheduling algorithm in the Linux kernel and is needed to enforce CPU limits. It allows you to limit the CPU usage of a container to a specific value, ensuring that a single container cannot monopolize the CPU resources of the entire system. This feature is usually enabled by default in many modern Linux distributions.

If your Synology NAS device is running a version of the Linux kernel that does not support the CFS scheduler, it might not be possible to limit CPU usage for Docker containers directly through Docker's CPU limit settings.

**Comment by tyhawk** [comment]
I don't have CPU problems, but Tdarr 2.20.00 is eating my ram regularly. I'm running it in a LXC container (on Proxmox) that has 4 GB RAM. At irregular intervals, Tdarr consumes all available memory and locks up the entire container, forcing me to reboot it. 
My collection isn't that massive (I think). Some stats:
Transcode queue (746)
Transcode: Success/Not required (18110)
Transcode: Error/Cancelled (2)
Health check queue (16369)
Health check: Healthy (2493)
Health check: Error/Cancelled (0)

Not sure it's the same issue as @Remataklan is having, so if you want I can create a new issue for this problem.

**Comment by HaveAGitGat** [comment]
@tyhawk are you able to check the server memory graph at the bottom of the stats page? `Heap used` is the memory in use by the main Tdarr Server process. Just to see if it's that or something else.

**Comment by HaveAGitGat** [comment]
@tyhawk perhaps it's the folder watcher? Can use a lot of ram if you have lots of files, try enabling this if you haven't already in library source: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bc285dbc-77ad-45b6-97a0-67b154a9735b)

**Comment by Remataklan** [comment]
> @tyhawk perhaps it's the folder watcher? Can use a lot of ram if you have lots of files, try enabling this if you haven't already in library source: ![image](https://user-images.githubusercontent.com/43864057/244143501-bc285dbc-77ad-45b6-97a0-67b154a9735b.png)

Hello

Sorry for the late reply - work has keeping me busy. I tried that too. Disabling/enabling it wont work. I ran 2 tests with various settings and my NAS clogs up each time after a few hours. I had to do a reset just to get back in the system.

So for now i disabled Tdarr.

**Comment by HaveAGitGat** [comment]
Ok thanks. From the screenshot I'm not able to see the memory usage of each process. Are you able to list it with memory so can see what's using lots?

**Comment by tyhawk** [comment]
> @tyhawk perhaps it's the folder watcher? Can use a lot of ram if you have lots of files, try enabling this if you haven't already in library source: ![image](https://user-images.githubusercontent.com/43864057/244143501-bc285dbc-77ad-45b6-97a0-67b154a9735b.png)

I can try. I ned to check if it works at all because all my media is on NFS shares and are not part of the disk of the Tdarr server.

I tuned one scaln down from 30 seconds to 3600. That seems to make the memory consumption less and lock-ups less frequent.

The moments the server seems to have the most issues is when I add over 10 mediafiles. My most common Library settings are: 
* _Folder watch settings_ 3600
* _Hold files after scanning?_ 4500

I  will keep you posted.

**Comment by tyhawk** [comment]
After changing the file scanner settings I figured a reboot would take me to a clean situation and would be the best method to use to evaluate the changes. It also allowed me to really take a look at RAM consumption compared to container behaviour.

![image](https://github.com/HaveAGitGat/Tdarr/assets/3992974/85e7dba9-323e-4b25-81d7-f43a0946e9f3)

What I notice is that as soon as Tdartr is reading the database at startup, memory consumption begins. The dip in the graph is caused by the reboot (duh).

The stats graph is now showing 4 GB of server memory and less memory usage.
![image](https://github.com/HaveAGitGat/Tdarr/assets/3992974/75d8091c-daeb-407e-b0af-be631c3823a6)

I will need to see how this works out, but so far so good for now.

**Comment by HaveAGitGat** [comment]
@tyhawk yeah you're right about the DB being in memory. This is done due to all the queues and sorting that goes on. If it wasn't in memory and you have a lot of files then it could take several minutes+ every time a file moves around. Also makes searching the DB very fast. But yeah this comes at the cost of RAM so not ideal if you have a lot of files which contain a lot of streams.

With regards to the folder watcher, Tdarr uses https://github.com/paulmillr/chokidar . So I assume that in order to detect file changes it keeps file info in RAM. How many total files (not just media files) do you have in your libraries?

**Comment by tyhawk** [comment]
@HaveAGitGat Viva `find /mnt/media -type f | wc -l` :-)

99934 total. That's media files, images, nfo-files, etc etc. Dumping the entire database in memory should indeed explain the memory usage. Adding to that (when finding new media) will tip the scales. Silly though that scanning after the server has been up for a few hours (of processing) has a bigger chance of freezing up the system (in my experience).

It does of course mean that the bigger your collection, the larger your RAM has to be. The only way to bring that down is using an output folder and pre-process all the files you wish to add to your colelction in stead of working on a (large) collection of media files directly?

**Comment by Remataklan** [comment]
> @HaveAGitGat Viva `find /mnt/media -type f | wc -l` :-)
> 
> 99934 total. That's media files, images, nfo-files, etc etc. Dumping the entire database in memory should indeed explain the memory usage. Adding to that (when finding new media) will tip the scales. Silly though that scanning after the server has been up for a few hours (of processing) has a bigger chance of freezing up the system (in my experience).
> 
> It does of course mean that the bigger your collection, the larger your RAM has to be. The only way to bring that down is using an output folder and pre-process all the files you wish to add to your colelction in stead of working on a (large) collection of media files directly?

Does this also explain the amount of CPU rescources used?

**Comment by HaveAGitGat** [comment]
@tyhawk if you can please try `haveagitgat/tdarr_node_acc:dev_2.00.21_2023_06_16T09_28_13z` and `haveagitgat/tdarr_node_acc:dev_2.00.21_2023_06_16T09_28_13z`

I've updated the NodeJS runtime from 14 to 18 which has memory improvements so can start with that and go from there if you still have issues.

**Comment by tyhawk** [comment]
At first glance memory usage seems slightly lower (3 GB vs 2.6 GB) with the server running and no processing or scanning.
![image](https://github.com/HaveAGitGat/Tdarr/assets/3992974/16811ddb-af30-4913-8041-713750d46514)
I increased memory to 6GB on the server and that now seems to prevent Tdarr to consume 4GB and locking up.

I will test some more with the dev images and see what else I can find.

**Comment by firasdib** [comment]
I'm testing the latest image on my end. I'll check the data in grafana after a few days. I have non of the folder monitoring enabled, and explicitly use the API to scan specific files.

**Comment by HaveAGitGat** [comment]
Thanks 👍

**Comment by firasdib** [comment]
Judging by the following graph, there seems to have been a decent improvement on my end. I still another method for managing the db/data would reduce it to <100mb, but this is an improvement nonetheless! 

![Screenshot 2023-06-20 at 09 43 13](https://github.com/HaveAGitGat/Tdarr/assets/1335165/2b39e9a4-b55e-409c-9b5b-6fbdccf9e791)

**Comment by tyhawk** [comment]
I'm seeing a 10-20% reduction in memory usage, so this is definately an improvement. I've ran about 10-15 different files through my queue without issues, so this version is okay as far as I can tell.

**Comment by HaveAGitGat** [comment]
I've added a new dev image which uses about 50% less RAM when storing file info.

With 3000 test files memory went from 5.099 MB to 2.496MB

You can see info on this by going to `http://localhost:8265/api/v2/debug-vars/text` in a browser and checking `Memory DB`.

Will get it down a bit more tomorrow.

docker pull haveagitgat/tdarr_acc:dev_2.00.21_2023_06_21T08_53_37z
docker pull haveagitgat/tdarr_node_acc:dev_2.00.21_2023_06_21T08_53_37z

**Comment by supersnellehenk** [comment]
Kinda hijacking, could create another issue if need be.

How about making binaries without NodeJS prepackaged for Docker setups? The images are quite large (~1,2GB pull for the server) and the server & node don’t share the NodeJS. I can imagine building them without NodeJS, then basing the Dockerfiles on NodeJS could cut down sizes or at least updates a lot.

**Comment by tyhawk** [comment]
> I've added a new dev image which uses about 50% less RAM when storing file info.
> 
> With 3000 test files memory went from 5.099 MB to 2.496MB
> 
> You can see info on this by going to `http://localhost:8265/api/v2/debug-vars/text` in a browser and checking `Memory DB`.
> 
> Will get it down a bit more tomorrow.
> 
> docker pull haveagitgat/tdarr_acc:dev_2.00.21_2023_06_21T08_53_37z docker pull haveagitgat/tdarr_node_acc:dev_2.00.21_2023_06_21T08_53_37z

I've rolled out the new image (without rebooting the server) and it seems to be using more memory with my database after startup than before with the previous acc/dev-build.
![image](https://github.com/HaveAGitGat/Tdarr/assets/3992974/4d318c99-66f8-47be-8fb3-34b66d4c1a73)

**Comment by HaveAGitGat** [comment]
@tyhawk thanks for trying, sorry forgot to mention the memory reductions only apply when your files are rescanned as the data was pruned at that point. Are you able to post what you see at `http://localhost:8265/api/v2/debug-vars/text`?  Just the first part, should look something like this:

```
    "table": [
      {
        "name": "Memory DB",
        "MB": 0.0702171,
        "procTime": 1
      },
      {
        "name": "Main",
        "MB": 0.00409126,
        "procTime": 0
      },
      {
        "name": "Files to add to DB",
        "MB": 0,
        "procTime": 0
      },
      {
        "name": "File scanner data store",
        "MB": 0,
        "procTime": 0
      },
      {
        "name": "Client DB files",
        "MB": 0.004076,
        "procTime": 0
      },
      {
        "name": "Folder watchers",
        "MB": 0,
        "procTime": 0
      },
      {
        "name": "Staged files",
        "MB": 0.0000038147,
        "procTime": 0
      },
      {
        "name": "Total",
        "MB": 0.0783881747,
        "procTime": 1
      }
    ]
```

**Comment by HaveAGitGat** [comment]
@supersnellehenk could maybe do that but would prefer not to have more build variations as increases overhead. Could maybe keep ffmpeg and ffprobe out of the Tdarr binary (extract it during the build process) which would reduce size by ~200MB.

I think there's around 2GB of stuff in the container that may not be needed so will run some jobs today to see if can remove them.

**Comment by tyhawk** [comment]
> http://localhost:8265/api/v2/debug-vars/text

Here you go:
```
    {
  "table": {
    "table": [
      {
        "name": "Memory DB",
        "MB": 39.4712,
        "procTime": 58578
      },
      {
        "name": "Main",
        "MB": 37.1673,
        "procTime": 41459
      },
      {
        "name": "Files to add to DB",
        "MB": 0,
        "procTime": 0
      },
      {
        "name": "File scanner data store",
        "MB": 0,
        "procTime": 0
      },
      {
        "name": "Client DB files",
        "MB": 37.1672,
        "procTime": 41673
      },
      {
        "name": "Folder watchers",
        "MB": 0.00169945,
        "procTime": 1
      },
      {
        "name": "Staged files",
        "MB": 0.0000038147,
        "procTime": 0
      },
      {
        "name": "Total",
        "MB": 113.8074032647,
        "procTime": 141711
      }
    ]
  },
```
So I do I understand you correctly? I need to _Requeue all items (transcode)_ for all of my libraries to trigger pruning the data? Or just _Scan (Fresh)_?

**Comment by HaveAGitGat** [comment]
Thanks, interesting that the ram used by the DB seems quite low so must be something else. Used method from here but not sure how accurate it is https://stackoverflow.com/a/11900218

And yes running scan fresh will do it 👍

**Comment by HaveAGitGat** [comment]
@tyhawk just to check, what does `Process Mem` say on the Tdarr tab when the container is using 2.5GB?

**Comment by tyhawk** [comment]
On the (LXC) server itself:
```
# free -m
               total        used        free      shared  buff/cache   available
Mem:            6144        2687        2948           0         508        3456
Swap:              0           0           0
```
Stats:
![image](https://github.com/HaveAGitGat/Tdarr/assets/3992974/fab6e529-7afc-46f8-8446-13a59bcf08ef)

I'l see if I can do a refresh soon, but it would mean my entire collection is reprocessed. That will take 1-2 weeks based on the number of nodes and the size of my libraries because even though transcoding is not needed, all files will need to loop through the checks.

**Comment by tyhawk** [comment]
Not sure if it is a bug in de 2.00.21 containers, but the node built into the server-container is configured to run (only) health checks in my setup. Eventhough that is still the case and the node is active and connectted, it's not running any health check jobs. I haven't been able to figure out why not.

**Comment by firasdib** [comment]
I'm going to test out image `haveagitgat/tdarr_acc:dev_2.00.21_2023_06_21T08_53_37z` for the new couple of days and see how that goes. Overall, memory consumption seems a lot better.

**Comment by HaveAGitGat** [comment]
Seems to be an issue/bug when packaging the binary for Linux as Windows doesn't have this issue. I've opened an issue on pkg https://github.com/vercel/pkg/issues/1956

So for some reason on linux the binary uses 3x the RAM as running from source.

**Comment by HaveAGitGat** [comment]
I’ve built the Docker images without pkg and @firasdib reported RAM usage went from 1.15GB to 163MB so will use that method for the next release


Can try here: haveagitgat/tdarr_acc:dev_2.00.21_2023_07_07T09_11_11z & haveagitgat/tdarr_node_acc:dev_2.00.21_2023_07_07T09_11_11z

**Comment by firasdib** [comment]
@HaveAGitGat The whole tdarr container (which for me, runs server+one node) runs at ~230MB right now, which is a stark improvement to the previous 1.6GB. Great work!

**Comment by macgregor** [comment]
Currently experiencing what I think is this issue on a RPi Kubernetes deployment. It is limited to 2 gigs of ram and 2 CPU cores. Start up is slow and fails with just my movie library if I lower Ram much, and won't start at all now that I added my TV lib (don't have file counts handy but it's about a 1 TB library). If it gets past start up it's fine though, otherwise it's an infinite startup loop with a stack trace from the file scanner. Don't have great resource utilization metrics, but def seems to be memory bottlenecked.


I tried to use the acceptance test build as it sounds promising, but looks like they are only x64 images, not arm. Not asking for them necessarily, just wanted to give an extra data point for the issue and vote for it's priority.


Great tool, keep up the good work!

**Comment by HaveAGitGat** [comment]
Worked on a lot of changes which I’ve been testing this week:

This image should have significantly reduced RAM usage:

tdarr_acc:dev_2.00.21_2023_07_21T09_55_57z


tdarr_node_acc:dev_2.00.21_2023_07_21T09_55_57z

Will release once I get the arm builds working.

**Comment by HaveAGitGat** [comment]
2.00.22 released. Reopen if needed thanks.
