### ISSUE TITLE
Remote Node won't properly execute plugin made with custom handbrake preset

### ISSUE THREAD

**Issue by newzj82** [HaveAGitGat/Tdarr#792]
Plugins created with custom handbrake preset use local file path for preset .json file and remote node cannot access that path.

Reproduce by creating custom handbrake preset and creating a plugin to use that preset using the custom arguments option.

If plugin is created using the remote node .json file location it will error and cancel on host server node but will run on remote node

**Comment by newzj82** [comment]
Server running tdarr is Linux, remote node is Windows.
--preset-import-file "/file/on/server/custpreset.json" -Z "custpreset" only exists in Linux file structure and cannot be replicated on Windows node.

Maybe having separate plugin stack per node would help?

Temporary workaround is to run node in Linux VM on Windows and copy preset .json to duplicate file location in VM

**Comment by HaveAGitGat** [comment]
https://docs.tdarr.io/docs/library-setup/transcode-options/handbrake-presets

So you can add a path translator in the node config json to translate the handbrake path. Re-open if needed thanks.

**Comment by newzj82** [comment]
I followed the guide you linked. 
I have the json files in /mnt/m2/plexo.json
I have copies of them locally on the windows computer in C:/json/plexo.json
And also a network share pointing directly at /mnt/m2 labeled V:/

In the node config file i have server: "/mnt/m2"
And I've tried node: "V:/" and node: "C:/json/" 

It still gives the error unless i have the plugin point to the local file on the node

My paths
pathTranslators: [
    { server: '/bigstorage/MOVIE/Movies', node: 'Y:/' },
    { server: '/bigstorage/TV', node: 'Z:/' },
    { server: '/mnt/8tb/tv', node: 'X:/' },
    { server: '/mnt/m2', node: 'C:/json/' },
    { server: '/mnt/m2/tdarr', node: 'W:/' }

**Comment by newzj82** [comment]
I moved the json files on the server and updated the plugins to
/mnt/m2/json so that maybe me pathing /mnt/m2/tdarr and /mnt/m2 was causing
issues. After a reboot it's still sending --preset-import-file
/mnt/m2/json/plexo.json to the remote node. So it's not translating the
path for the remote node.

**Comment by newzj82** [comment]
Path
"pathTranslators": [
    {
      "server": "/bigstorage/MOVIE/Movies",
      "node": "Y:/"
    },
    {
      "server": "/bigstorage/TV",
      "node": "Z:/"
    },
    {
      "server": "/mnt/8tb/tv",
      "node": "X:/"
    },
    {
      "server": "/mnt/m2/json",
      "node": "C:/json/"
    },
    {
      "server": "/mnt/m2/tdarr",
      "node": "W:/"
    }

Error

:"C:/Users/j-ped/Downloads/Tdarr_Updater/Tdarr_Node/assets/app/HandBrakeCLI.exe
-i Z:/Dark/Season 1/Dark - S01E01 - Secrets.mkv -o W:/Dark - S01E01 -
Secrets-TdarrCacheFile-8oUmW6oYq.mkv --preset-import-file
/mnt/m2/json/Plexo900.json -Z Plexo900"}

**Comment by newzj82** [comment]
I tested.
It's pathing the cache location fine.
I copied the .json files to cache in a folder called json and updated the
plugins

It still sent --preset-import-file /mnt/m2/tdarr/json/plexo.json
To the remote node that can access that cache path without issue.

I think the issue is the server isn't sending the updated path to the
remote node

**Comment by newzj82** [comment]
Contents of plugin. https://pastebin.com/iyDznB2n

Complete report. https://pastebin.com/Dkm7vQpf

**Comment by HaveAGitGat** [comment]
The raw plugin text isn't translated, you need to create a plugin input and put it in there:

E.g. add this to the details section of your plugin:

```
    Inputs: [
        {
            name: 'arguments',
            type: 'string',
            defaultValue: '--preset-import-file "/mnt/m2/tdarr/json/Plexo.json" -Z "Plexo"',
            inputUI: {
                type: 'text',
            },
            tooltip: `-`
        },
    ],
```

Then the input will appear the in the plugin stack UI with that default value.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dc2b66ee-06aa-4c75-8809-faa182ecac3e)

**Comment by newzj82** [comment]
Thank you. That plug-in was made with the built in plug-in creator. Will it
be updated to include those lines in a future update?

**Comment by HaveAGitGat** [comment]
Possibly, I suppose the issue is that some people may have written plugins that include hard-coded paths that they wouldn't expect to be translated. Probably a small set of users but needs to be considered.

**Comment by newzj82** [comment]
`const details = () => ({
          id: "7Q0rwj337",
          Name: "larger than 720",
          Type: "Video",
          Operation: "Transcode",
          Description: "all larger than 720, no matter size",
          Version: "",
          Link: "",
      	  Inputs: [
              {
                  name: 'arguments',
                  type: 'string',
                  defaultValue: '--preset-import-file "/mnt/m2/tdarr/json/Plexo.json" -Z "Plexo"',
                  inputUI: {
                      type: 'text',
                  },
                  tooltip: `-`
              },
    ],
      });

 // eslint-disable-next-line no-unused-vars
    const plugin = (file, librarySettings, inputs, otherArguments) => {
    const importFresh = require('import-fresh');
    const library = importFresh('../methods/library.js');

        //Must return this object at some point
        const response = {
           processFile : false,
           preset : '',
           container : '.mkv',
           handbrakeMode : false,
           ffmpegMode : true,
           reQueueAfter : true,
           infoLog : '',
      
        }

        response.infoLog += "" + library.filters.filterByResolution(file,"include","1080p,4KUHD,DCI4K,8KUHD,Other").note
      
        if((true &&library.filters.filterByResolution(file,"include","1080p,4KUHD,DCI4K,8KUHD,Other").outcome === true) || file.forceProcessing === true){
            response.preset = '--preset-import-file "/mnt/m2/tdarr/json/Plexo.json" -Z "Plexo"'
            response.container = '.mkv'
            response.handbrakeMode = true
            response.ffmpegMode = false
            response.processFile = true
            response.infoLog +=  "File is being transcoded using custom arguments \n"
            return response
           }else{
            response.infoLog += "File is being transcoded using custom arguments \n"
            return response
           }
      }

module.exports.details = details;
module.exports.plugin = plugin;`

i tried that but it gave the same error. Did i put it in the correct place?

**Comment by newzj82** [comment]
plugin updated https://pastebin.com/XpbWkcv5
i added those lines. hopefully in the correct location.
its throwing a different error now?
log https://pastebin.com/VtFqnwpj

**Comment by sloke123** [comment]
I'm having the same issue. Both PCs are on Windows.
