### ISSUE TITLE
Plugin selection based on node's capability #2

### ISSUE THREAD

**Issue by Jinra** [HaveAGitGat/Tdarr#793]
**Is your feature request related to a problem? Please describe.**

This is directly related to @Starker3 and @Blackpaw 's requests here https://github.com/HaveAGitGat/Tdarr/issues/504, but since that issue is closed out, I'm creating a new one. I am trying to use QSV and NVENC in the same plugin stack, but keep running into an issue whenever a QSV node hits the NVENC plugin (NVENC plugin is higher priority) where it says `Won't process: requireGPU:nvenc` and will drop the job for that node, the opposite happens to NVENC nodes when the QSV plugin is higher on priority

**Describe the solution you'd like**
It would be great to have a feature to decode multiple GPU encoder types (QSV + NVENC) on different nodes using the same plugin stack for the library. In the original issue, it was suggested to have a CPU and GPU plugin stack, but I think this is a bit different since QSV acts as a GPU encoder

**Describe alternatives you've considered**
I tried using only NVENC or QSV exclusively, but that obviously cuts down on my transcoding capabilities by a large margin.

**Additional context**
n/a

**Comment by HaveAGitGat** [comment]
Make sure to disable this option `Process Plugins Sequentially`:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/312ef4ee-c3a0-4a77-a23c-bd7ff68e7abe)

Will allow the worker to jump ahead to the plugin that it can do.

Reopen if needed thanks.
