### ISSUE TITLE
Allow server-side defaults and allow seeding node options (specifically GPU/CPU counts)

### ISSUE THREAD

**Issue by ChipWolf** [HaveAGitGat/Tdarr#794]
**Is your feature request related to a problem? Please describe.**
My nodes are ephemeral containers running within a cluster, the node names are randomly generated on start, there may be any number of nodes running depending on availability - setting static names is not feasible.

When a new node is spawned, I need to manually set the CPU/GPU counts for transcoding & health checking on each node's options in the server UI.

**Describe the solution you'd like**
The ability to configure global CPU/GPU default counts for transcoding/health checks in the server options that would apply to all new nodes & ideally a node config option _(bonus points for an environment variable too)_ to override the default so the node can inform capabilities to the server rather than relying on additional user input.

**Comment by HaveAGitGat** [comment]
This might be possible already if you're running the same number of workers on all nodes.

The nodeID is random (randomly generated every time the node starts up) and the nodeName is what the server uses to save the node config. So if you set 2 nodes with the same nodeName (through env var or the node json config) then when the nodes start up they'll have the same worker limits and config.

I actually just fixed a bug where if 2 nodes have the same nodeName, you can control both nodes live using one node panel - this might be a feature to some.

But yeah would be good to be able to use env vars to set the node limits.

**Comment by HaveAGitGat** [comment]
As this is for a specific use case that won't be used by many I've just kept it to env variables:

So can set the following env vars on the node:

`transcodegpuWorkers`
`transcodecpuWorkers`
`healthcheckgpuWorkers`
`healthcheckcpuWorkers`

E.g `transcodegpuWorkers=2` will start the node with 2 of those workers. Added for next version.

**Comment by HaveAGitGat** [comment]
2.21.01 released
