### ISSUE TITLE
Add support  nvidia Jetson Xavier NX

### ISSUE THREAD

**Issue by cHaos91** [HaveAGitGat/Tdarr#796]
Mini Clusters are becoming more common and be able to use this clusters as nodes for Tdarr would be nice as they are low power for their performance capable of doing  2160p30 (2) | 1080p60 (6) | 1080p30 (14).

This would scale very good for small clusters with low power usage.

If possible could we create a Docker container for nvidia Jetson Xavier NX with support for hardware encoding on the GPU.

**Comment by supersnellehenk** [comment]
As a reference, this got asked in #646 as well. The difficulty is there's no plugins for them and they need their own version of ffmpeg compiled with GStreamer.

**Comment by HaveAGitGat** [comment]
Yeah please see https://github.com/jellyfin/jellyfin-ffmpeg/issues/87, so perhaps will be possible for them to include it at some point but will need to wait until then.
