### ISSUE TITLE
A lot of node timeouts

### ISSUE THREAD

**Issue by Pascal51882** [HaveAGitGat/Tdarr#798]
**Describe the bug**
I get many random node timeouts. I did not find the problem.
At the beginning it worked fine for a few weeks. After some updates I saw more and more timeouts.
I recreated the Node already with no luck. 

Which usefull logs or config can I provide?

 - OS: Server on Unraid, Node on Windows 10
 - Browser [e.g. chrome, ]

Node Log:
``[2023-06-16T18:50:23.949] [DEBUG] Tdarr_Node - Polling worker response error:10000ms
[2023-06-16T18:50:23.950] [ERROR] Tdarr_Node - Error: timeout of 10000ms exceeded
    at createError (C:\snapshot\node\node_modules\axios\lib\core\createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (C:\snapshot\node\node_modules\axios\lib\adapters\http.js:369:16)
    at RedirectableRequest.emit (events.js:400:28)
    at Timeout.<anonymous> (C:\snapshot\node\node_modules\follow-redirects\index.js:169:12)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 31
    },
    method: 'post',
    url: 'http://192.168.178.200:8266/api/v2/poll-worker-limits',
    data: '{"data":{"nodeID":"nkyICDek3"}}'
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v2/poll-worker-limits',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.178.200',
      port: '8266',
      nativeProtocols: [Object],
      pathname: '/api/v2/poll-worker-limits'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 31,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /api/v2/poll-worker-limits HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 31\r\n' +
        'Host: 192.168.178.200:8266\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v2/poll-worker-limits',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.178.200',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.178.200:8266/api/v2/poll-worker-limits',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}``

**Comment by HaveAGitGat** [comment]
Haven’t had this issue personally but please try these links if you get time as have some updates : https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.00.21/win32_x64/Tdarr_Node_2023_06_16T09_42_40z.zip & https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.00.21/win32_x64/Tdarr_Server_2023_06_16T09_42_40z.zip

**Comment by HaveAGitGat** [comment]
Will move this under here https://github.com/HaveAGitGat/Tdarr/issues/726 as somewhat related thanks
