### ISSUE TITLE
Fallback to cpu transcoding if GPU transcoding fails

### ISSUE THREAD

**Issue by depeo10** [HaveAGitGat/Tdarr#799]
**Is your feature request related to a problem? Please describe.**
I want a way of forcing CPU encoding instead of GPU encoding for failed gpu transcodes.

**Describe the solution you'd like**
About 5% of my transcodes fails on AMDGPU with a kernel error.,  it would be great If those files could be "marked" for CPU transcoding only, and then be requeued. (fails with drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!

 GPU transcodes fails for different reasons also, for example if the source is anything other than h264)

**Comment by HaveAGitGat** [comment]
At what point does it fail? Right at the beginning?

**Comment by HaveAGitGat** [comment]
The default flows encode plugin will auto detect gpu. You could also do something like this:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3e1f5864-7247-45d2-b2bf-0fa8b935ed2f)

So this would try gpu, then if error it would then use cpu.

You can also attempt this method with any of the classic plugins.
