### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by nagelm** [HaveAGitGat/Tdarr#8]
Howdy, I've been looking for a project like this to let loose on my library. Will check back when I get a bit of free time.

A suggestion:
Some older 4K TVs (confirmed for various Samsung TVs on the Plex forums - I have a KS8000), do not like too many streams on in an mkv. If there are more than ~20 elements (including video/audios/subs) playback starts buffering/glitching. Removing superfluous elements (using mkvtoolnix) and I find the same UHD file at the same high bitrate plays flawlessly. 

Would love to be able to strip out subtitles at the same time as doing a pass for audio/video.

**Comment by HaveAGitGat** [comment]
@nagelm 

Thanks for taking a look at the project. Would you mind filling in this plugin request form?

```
Video transcode requirements: (E.g convert using H265 using HandBrake's 'H.265 MKV 1080p30' preset. Specify an FFmpeg command if you're wanting to use that.)

Video audio track requirements:  (E.g add 192Kbit AAC if track doesn't exist)

Subtitles: (Keep/Remove)

Title meta-data or other: (Keep/Remove)

Output container: (Same as original/MP4/MKV etc)

Any other comments:
```

Thanks!

**Comment by marshalleq** [comment]
Hopefully I’m allowed to make a request too:

Encode Video to HEVC/x265 Medium QF23
Don’t touch anything else.
(Us audio folk don’t like compressing audio). :D
I’d like to leave subtitles and chapters intact as they’re useful.
Output to mkv.

Sorry to hijack - but it’s a good opportunity! ;)

So this reduces the size of the Video but not the Audio, mostly that's enough.  The exception is when it's HD Audio, I personally am happy at the DTS / AC3 kind of space.  So we could convert those I suppose (second priority).

Thanks.

**Comment by HaveAGitGat** [comment]
@nagelm 

Please re-open if required.
