### ISSUE TITLE
Is it possible to use Tdarr with the nvidia offload feature?

### ISSUE THREAD

**Issue by Jorman** [HaveAGitGat/Tdarr#800]
Hi, I just discovered this project, I like the idea!
On a nas on the local network I have all the media library and would like to convert it by taking advantage of my laptop which uses an nvidia card.
However, I have Arch installed and the access to the nvidia card is via prime-run, so:
```
#!/bin/bash
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```
I think that is the only way to access the nvidia card, otherwise the integrated video card is used.
I tried installing Tdarr server and node on the laptop (without using docker) but I can't do transcoding using the nvidia card.
Do you know a way to take advantage of the nvidia card when it is not integrated in the pc but available as a second video card?

Thanks

Jo

**Comment by HaveAGitGat** [comment]
Can specify the device in ffmpeg command using this: https://arstech.net/choose-gpu-in-ffmpeg/

So in the plugin you could add a condition such as 

```
if(process.env.nodeName === 'laptopNodeName'){
// specify device to be use
}

```

**Comment by HaveAGitGat** [comment]
Currently working on a plugin which auto-detects GPU here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/423/files

On multi GPU devices the idea is to prioritize Nvidia else fallback to QSV. Will handle this stuff there.
