### ISSUE TITLE
Invalid Runtime name NVIDIA

### ISSUE THREAD

**Issue by ccfman2004** [HaveAGitGat/Tdarr#801]
**Describe the bug**
My tdarr nodes disappeared and when trying to reinstall them Docker gives me an error:

docker: Error response from daemon: unknown or invalid runtime name: NVIDIA.

**To Reproduce**

**Expected behavior**
Docker container to successfully install

**Screenshots**

<img width="1185" alt="Screen Shot 2023-06-17 at 4 57 34 PM" src="https://github.com/HaveAGitGat/Tdarr/assets/79392/391124f7-84c8-4b82-8aad-b4ed3ed0f25b">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

Tdarr_Node_Config.json

{
  "nodeID": "GTX1080",
  "nodeName": "GTX1080",
  "serverIP": "10.0.0.121",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "platform_arch": "linux_x64_docker_true",
  "nodeIP": "10.0.0.121",
  "nodePort": "8267"
}

Tdarr_Server_Config.json

{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "10.0.0.122",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true
}

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Unraid 6.12.0
 - Version: 2.00.21

**Additional context**

**Comment by HaveAGitGat** [comment]
Please see https://github.com/HaveAGitGat/Tdarr/issues/797
