### ISSUE TITLE
Feature: Option to mass bump files

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#802]
**Is your feature request related to a problem? Please describe.**
Mass bump option similar to skip option

@Ian-Aurgnet

**Comment by pokemonfirer** [comment]
when needing to add many files to "bump" status for example when trying to get thru small easily transcoded files you have to add them one by one sometimes this can be in the 100's of files having a way to just put something like 480p in the resolution filter and hit bump all would make things a lot easier and save a ton of clicks and time

**Comment by HaveAGitGat** [comment]
2.00.22 released
