### ISSUE TITLE
Output files to root of output folder

### ISSUE THREAD

**Issue by Ulrar** [HaveAGitGat/Tdarr#804]
**Is your feature request related to a problem? Please describe.**
Hi,

Related to [this post](https://www.reddit.com/r/sonarr/comments/14iln5c/unable_to_parse_download_automatic_import_is_not/), it's not tdarr's fault IMHO but Sonarr is failing to import my files because they're in subfolders.

**Describe the solution you'd like**
When using the output folder option, an option to get tdarr to output the file at the root of that folder instead of replicating the source's relative path would be great. I understand why it would when outputting to the source library of course, but when output folder is enabled IMHO it should just output in said folder directly.

**Describe alternatives you've considered**
For now I just run `mv outputfolder/*/*/* outputfolder/ && rmdir outputfolder/*/* && rmdir outputfolder/*/` periodically, which works fine but is annoying. Could be a cron but that's still not ideal

Thanks !

**Comment by HaveAGitGat** [comment]
I've added an option to the Tdarr Flows copy to dir flow plugin for this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/09096287-0d80-44a0-806e-99d714fb0d36)

So would just need to enable this option:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bec0f04a-a767-444d-97c1-84fc38f940ee)

Still in alpha but will be handled that way.

**Comment by HaveAGitGat** [comment]
Beta released the other day so should be working fine.
