### ISSUE TITLE
Automatically reset in limbo files after time

### ISSUE THREAD

**Issue by wieluk** [HaveAGitGat/Tdarr#805]
**Is your feature request related to a problem? Please describe.**
My Computer is a node for tdarr and when I turn it off it sometimes leaves files in limbo.

**Describe the solution you'd like**
I would like to be able to automatically reset the in limbo files.

**Describe alternatives you've considered**
Maybe doing it via api

**Comment by kramttocs** [comment]
This would be nice. I have my running as services so it would be nice to have them restart automatically/eventually if I restart my machine.

**Comment by tuxmeister** [comment]
I am currently working on automating node spin-up/down via Home Assistant Agent actions + NodeRED and an API endpoint to re-queue all Limbo files would be very nice! (per Library would be extra nice). Hopefully, more endpoints coming soon, like pause/un-pause node, not sure if this already exists and I missed it in the API reference somehow.

**Comment by HaveAGitGat** [comment]
Added for next version 2.17.01. In limbo files will be auto re-queued after 5 mins.

@tuxmeister API related stuff here: https://tdarr.readme.io/reference/post_update-node

Can also just press F12 in browser and check the network tab requests so you can re-use any stuff you're doing in the UI.

Example of pausing nodes here:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/input/inputFile/1.0.0/index.ts#L75
