### ISSUE TITLE
Tdarr Hanging immediately after starting (100% cpu/memory usage) 

### ISSUE THREAD

**Issue by NJKA001** [HaveAGitGat/Tdarr#806]
Running tdarr in docker hangs immediately after starting with the cpu and memory pegged at around 100%. I cannot connect to tdarr UI at all, and have to kill the machine.

If I delete all the files in /server/Tdarr/*, restart, and set up all the libraries again everything works. That is until after some successful transcodes have been completed. If I then restart tdarr. Same behaviour 100% cpu and memory.

Seeing "TransportError: xhr poll error" and "ECONNREFUSED" errors in the logs.

Tried re-installing the tdarr docker image with the same results. Checked file permissions are ok. 

 - OS: Proxmox lxc container running Alpine linux.  
 - Tdarr Version : 2.00.21

tdarr logs and config attached
[tdarr.zip](https://github.com/HaveAGitGat/Tdarr/files/11948823/tdarr.zip)

**Comment by NJKA001** [comment]
This happens when the lxc container is allocated 2GB. If I increase the memory allocation to 4GB the problem goes away. Memory usage is peeking at startup around 2.8GB, then settles to around 1.9GB. Never known a program to be so memory hungry when idling.

**Comment by HaveAGitGat** [comment]
Hi thanks for opening a post, how many files have you scanned? Tdarr uses a RAM DB so can typically use 1GB ram per 10,000-100,000 files depending on how much stream data the files have. The next update has some improvements for it.

In the current release here it is on Windows with an assortment of 3,300 files using 138.4MB which seems reasonable:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5d8a40cb-cdd2-4ee1-94e3-9e8e6bf75478)

I'm currently investigating a RAM issue on Linux which is causing the RAM to be higher there. For some reason when the binary is built the RAM usage increases a lot (128MB to 426MB). Tdarr uses Vercel PKG for this so I'll need to ask them.

**Comment by HaveAGitGat** [comment]
Please see here https://github.com/HaveAGitGat/Tdarr/issues/790#issuecomment-1625973530
