### ISSUE TITLE
Consistent docker versioning scheme (tags)

### ISSUE THREAD

**Issue by stavros-k** [HaveAGitGat/Tdarr#809]
**Is your feature request related to a problem? Please describe.**

I'd like to request docker all tags to have the same versioning scheme.
For example tag 2.00.21 have "3 numbers" but 2.00.20.1 have "4 numbers"
Making it difficult to create automations to pickup newer versions and open Pull Requests.

**Describe the solution you'd like**

Please consider adding `.0` on non "patch" releases.

Thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by HaveAGitGat** [comment]
I'll keep it to 3 numbers (2 dots) in future.
