### ISSUE TITLE
Remux to MKV throws errors on MKV files

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#81]
I created a plugin by clicking container and then create plugin in the plugin creator. However, for all of my mkv files, "☒Plugin error! {} " is what appears when you click the "i" in the error/cancelled tab.

**Comment by HaveAGitGat** [comment]
What did you put in the plugin creator box?

**Comment by theg00s3** [comment]
I left it as is (mkv)

**Comment by HaveAGitGat** [comment]
Did you make sure to select the ‘Local’ plugin checkbox when adding the plugin?

**Comment by theg00s3** [comment]
yes

**Comment by HaveAGitGat** [comment]
Are you able to send a screenshot of your plugin stack?

**Comment by theg00s3** [comment]
![image](https://user-images.githubusercontent.com/18522748/69616323-85877600-108a-11ea-9c4d-7f3b4e00dfa3.png)

**Comment by HaveAGitGat** [comment]
Thanks, seems fine from that. 

Leave it off for now and I’ll have a look. I just created an mkv remux plugin like yours and it worked fine so will need to do some digging.

**Comment by theg00s3** [comment]
I tried creating a new plugin by doing the same thing, and it still just appears as "☒Plugin error! {} "

**Comment by marshalleq** [comment]
Just passing through and am interested in your stack and the new plugin creation - why do you need plugin stack 2 when you've got the same thing in plugin stack4?  I would have thought if there was a case where it was needed it would be last (ie the case where it didn't need to encode but for some reason wasn't already in mkv).

**Comment by HaveAGitGat** [comment]
@marshalleq that's the right way to do it. If the remux plugin was put at the bottom then if a file was in hevc but not mkv, it would not get remuxed.  Your logic would be correct if the transcode plugin had a filter inside of it, but it doesn't. I'm working on that.

@theg00s3 are you able to double check the container read/write permissions?

**Comment by marshalleq** [comment]
So that means the priority 4 item that says the output is mkv is incorrect I assume?

**Comment by theg00s3** [comment]
@HaveAGitGat the permissions are correct

**Comment by HaveAGitGat** [comment]
@marshalleq no it’s correct.

If for example the file is h264 and in an mp4 container, it will never get to the 4th plugin because of the 3rd plugin filter.

So you need the remux plugin above the filter, which he has done.

**Comment by marshalleq** [comment]
OK cool.

**Comment by HaveAGitGat** [comment]
Still not sure what could be causing this. Haven’t been able to recreate it myself and haven’t had any other reports of it. 

The next update has a new way of reading plugins so hopefully that solves the issue for you 👍

**Comment by theg00s3** [comment]
By next update do you mean v1.008 or v1.007X?

**Comment by HaveAGitGat** [comment]
@theg00s3 sorry I mean 1.008. I had to throw a quick update up today as the cache cleaner was incorrectly working for some people.

**Comment by theg00s3** [comment]
Just in case, I tried updating the version of ffmpeg in the docker, but that didn't fix it. However, updating ffmpeg did fix my issue where files would fully transcode and then move to the error tab.

**Comment by HaveAGitGat** [comment]
@theg00s3 I found the issue. Typo in the remux container plugin printer.

If you go into your Tdarr/Plugins/Local folder and open the plugin, search for 'reponse' near the bottom. Change it to 'response' and it should start working.

![image](https://user-images.githubusercontent.com/43864057/69890560-5ec97980-12ee-11ea-80e6-e999990622c6.png)

So it only causes an error if the file is already in the desired container. Fixed for the next updated.

**Comment by theg00s3** [comment]
Now it's a different error. 
The initial command is /home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -i '/home/Tdarr/Media/media.mkv' undefined '/home/Tdarr/Media/cache/media-TdarrCacheFile-GtCQkq9S.mkv'  
and the error is 
"Unable to find a suitable output format for 'undefined'
undefined: Invalid argument"

**Comment by theg00s3** [comment]
I think I might have found the reason for the error. My remux plugins are missing the"response.processFile = false;" line

**Comment by HaveAGitGat** [comment]
Great, this has been fixed in 1.008
