### ISSUE TITLE
Tdarr is not cleaning up after itself resulting in running out of disk space

### ISSUE THREAD

**Issue by douglasparker** [HaveAGitGat/Tdarr#812]
**Describe the bug**
I am running Tdarr in a docker container and it doesn't seem to be cleaning up after itself.

Upon investigation, I've found that `/app/Tdarr_Node` is filling up with media and is never cleaned up. This will continue until the server runs out of disk space.

I have to either `docker exec` into the container and remove them manually or stop the container and prune it.

**To Reproduce**
Run Tdarr in a docker container using `ghcr.io/haveagitgat/tdarr:latest`

**Expected behavior**
Tdarr should clean these files up after it is done processing.

**Screenshots**
n/a

**docker-compose.yml**
```docker
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    network_mode: host
    environment:
      - TZ=Etc/UTC
      - PUID=999
      - PGID=995
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=Local
    volumes:
      - ./tdarr/bin:/app/server
      - ./tdarr/conf:/app/configs
      - ./tdarr/logs:/app/logs
      - /mnt/media:/media
      - /transcode:/transcode
    restart: unless-stopped
```

**Comment by HaveAGitGat** [comment]
In the UI library settings what have you set as the transcode cache?

**Comment by douglasparker** [comment]
> In the UI library settings what have you set as the transcode cache?

I have it set to `/transcode` in each library.

**Comment by HaveAGitGat** [comment]
Ok thanks, yeah probably related to that. Reopen if needed
