### ISSUE TITLE
No QSV Plugin can utilize Intel ARC on UNRAID

### ISSUE THREAD

**Issue by adamgwaps** [HaveAGitGat/Tdarr#813]
**Is your feature request related to a problem? Please describe.**
I used a custom [Kernel](https://github.com/thor2002ro/unraid_kernel) for Intel ARC support on UNRAID it works flawlessly on Jellyfin but it seems to not work out of the box on all available plugin without modification (it will work on boosh if you modify the encoder)

**Describe the solution you'd like**
Update the available plugin to support Intel ARC QSV (add a configurable option to use a certain encoder)

**Describe alternatives you've considered**
As of now an alternative is to passthrough the intel arc to a windows VM and use the "Tdarr_Plugin_ER01_Transcode audio and video with HW (PC and Mac)" Plugin, it works flawlessly but it would be better to handle everything on the docker level to conserve CPU and RAM

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
Are you referring to `av1_qsv` or `hevc_qsv`? 

Try the new all in one `Tdarr_Plugin_00td_action_transcode` plugin, we can modify it if needed.

**Comment by HaveAGitGat** [comment]
Please try using Tdarr Flows as the 'Set Video Encoder' plugin has an option for this:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/190efc09-9589-4a00-a1b4-f28cf21fc115)

Reopen if needed thanks.
