### ISSUE TITLE
2.00.22 Docker Slow in Unraid

### ISSUE THREAD

**Issue by Nick2Smith** [HaveAGitGat/Tdarr#816]
Transcoder takes a long time so scan files that are already transcoded, keeps saying "scanning" or "Getting new task" for a minute or more per file. 

**To Reproduce**
Re-queue files that have been transcoded

**Expected behavior**
Files are scanned quickly and moved to transcoded

Moving back to 2.00.21 fixed this issue.

**Comment by HaveAGitGat** [comment]
Hi if you check the job report it's most likely because it's running mkvpropedit on the file to ensure the file stream data is up to date. FFmpeg often doesn't update this data when it processes a file so mkvpropedit edit updates the info which is then used by plugins to process files correctly. I can add an option to disable it but it means files might not be processed optimally.

**Comment by daj102** [comment]
Is that a new option in 22, @HaveAGitGat ??  I run tdarr and tdarr-node in Docker on an Ubuntu server ... I've just updated to 22 and I see the same delays.  Whenever a task is sent to the node container (on the same server), I now see a minute or two of delay; the last line in the log is this:

2023-07-31T10:58:43.318Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Fetching plugin data from server

It is a large file (15GB) that is stored on another server ... but it used to be able to check the file very quickly (~10secs) and realize that nothing is required (this file has been processed by Tdarr before).  Now it seems that it is doing a comprehensive check of the file, which takes a while, before deciding to skip.  Does that match up to your mkvpropedit theory?

**Comment by daj102** [comment]
> Is that a new feature in 22, @HaveAGitGat ?? I run tdarr and tdarr-node in Docker on an Ubuntu server ... I've just updated to 22 and I see the same delays. Whenever a task is sent to the node container (on the same server), I now see a minute or two of delay; the last line in the log is this:
> 
> 2023-07-31T10:58:43.318Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Fetching plugin data from server
> 
> It is a large file (15GB) that is stored on another server ... but it used to be able to check the file very quickly (~10secs) and realize that nothing is required (this file has been processed by Tdarr before). Now it seems that it is doing a comprehensive check of the file, which takes a while, before deciding to skip. Does that match up to your mkvpropedit theory?

Actually, the worker just updated and this seems like it hasn't even loaded the file yet:

`
2023-07-31T10:58:43.318Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Fetching plugin data from server
2023-07-31T11:04:02.464Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Scanning original library file
2023-07-31T11:04:02.465Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:{
2023-07-31T11:04:02.465Z "exifToolScan": true,
2023-07-31T11:04:02.465Z "mediaInfoScan": false,
2023-07-31T11:04:02.465Z "closedCaptionScan": false
2023-07-31T11:04:02.465Z }
2023-07-31T11:04:02.466Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Updating file properties using mkvpropedit
2023-07-31T11:04:04.470Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Updated file properties using mkvpropedit
2023-07-31T11:04:04.471Z DlBPwFDDH:Node[MainNode]:Worker[old-oryx]:Requesting Tdarr Server to scan file
`

6 minutes just to get plugin data?

**Comment by HaveAGitGat** [comment]
For me it wasn’t taking that long but I’ll do a release tomorrow with an option to toggle whether mkvpropedit should run on a file (default will be it being disabled so processing speed will be similar to before).

It was added back in 2.00.19 back in February but wasn’t working properly, now that it’s working properly it just takes a long time which is not ideal.

Thanks @daj102 I’ll check that too. No changes were made to that section either so it seems to be something related to either removing pkg dependency or going from NodeJS14 to NodeJS18.

**Comment by b-reich** [comment]
![image](https://github.com/HaveAGitGat/Tdarr/assets/1573025/c68f1c20-e739-434c-ad42-80a7fffac85b)
This was a 1,5GB File

**Comment by dj-chalky** [comment]
I'm getting this on Windows as well, GPU workers were still hanging after over an hour. 

'Downgraded' to 2.00.21 and all is well again

**Comment by daj102** [comment]
> I'm getting this on Windows as well, GPU workers were still hanging after over an hour.
> 
> 'Downgraded' to 2.00.21 and all is well again

I just changed my docker compose file to force 2.00.21 and I see the same thing; videos are flying through the queue again now.

**Comment by HaveAGitGat** [comment]
I've just release 2.00.23 which has a setting on Options tab to specify whether to run mkvpropedit before plugins. Default is 'disabled'.

@daj102 it was actually running mkvpropedit at that point, not getting plugin data. Issue is mkvpropedit was blocking the log updates so update to 2.00.23 and should be fine.

**Comment by daj102** [comment]
> I've just release 2.00.23 which has a setting on Options tab to specify whether to run mkvpropedit before plugins. Default is 'disabled'.
> 
> @daj102 it was actually running mkvpropedit at that point, not getting plugin data. Issue is mkvpropedit was blocking the log updates so update to 2.00.23 and should be fine.

Updated to 23, cleared library and ran a Fresh scan - the files are going through at a fast pace again.  Thank you!

**Comment by HaveAGitGat** [comment]
Great 🙂 glad it’s working

**Comment by b-reich** [comment]
@HaveAGitGat I am at 2.00.24.
Its still slow.

<img width="348" alt="grafik" src="https://github.com/HaveAGitGat/Tdarr/assets/1573025/28560280-ba42-4551-b96c-4a674fb77f8b">
<img width="1075" alt="grafik" src="https://github.com/HaveAGitGat/Tdarr/assets/1573025/9bd5a6d6-aa93-4610-b512-e11bb95d7318">

**Comment by HaveAGitGat** [comment]
Please post the job report if you are having issues. Also make sure to disable the option before a worker starts. If you disable it after the worker starts then the change won’t be applied until the worker begins the next file.

**Comment by b-reich** [comment]
The option was never activated at any time
<img width="1023" alt="grafik" src="https://github.com/HaveAGitGat/Tdarr/assets/1573025/8cb6b70d-701b-45ce-8322-91a176f50586">

**Comment by HaveAGitGat** [comment]
Thanks, this is unrelated to that option or mkvpropedit.

If you look at the lot timestamp you can see that this is to do with npm installing dependencies. If you check the terminal where Tdarr is running (or unraid container logs) then there’s additional npm output that might have more info (npm produces this separately from an internal process).

Does the container have internet access? Might be that it’s blocked or really slow.

**Comment by b-reich** [comment]
Should working fine the internet access. Also wget github.com works fine inside the container
<img width="685" alt="grafik" src="https://github.com/HaveAGitGat/Tdarr/assets/1573025/5ed9c175-adde-4426-b59b-c229a2ac7bfe">

**Comment by HaveAGitGat** [comment]
If you scroll up to the time when the dependency installation ran then you should see output like this:

```

2023-08-04T11:10:28.303] [INFO] Tdarr_Node - The following external module needs to be installed for a plugin:import-fresh
[2023-08-04T11:10:28.769] [INFO] Tdarr_Server - [3780ms]Plugin update finished
npm WARN saveError ENOENT: no such file or directory, open '/app/Tdarr_Node/assets/app/plugins/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/app/Tdarr_Node/assets/app/plugins/package.json'
npm WARN plugins No description
npm WARN plugins No repository field.
npm WARN plugins No README data
npm WARN plugins No license field.

+ import-fresh@3.3.0
added 4 packages from 1 contributor and audited 4 packages in 0.767s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

So check if there’s an error there or something like that.

**Comment by b-reich** [comment]
@HaveAGitGat ahh I screw up the Docker IPv6 config...
Sorry for bother you. Have great Weekend!

**Comment by HaveAGitGat** [comment]
Great thanks for the update. Enjoy your weekend 👍

**Comment by ArabCoders** [comment]
@HaveAGitGat The option for running mkvpropedit on each plugin is great, i would appreciate it if there was an extra option run mkvpropedit before the the plugins execution and then only run if the plugin requested a transcode, right now it's run for many times if there are many files to go thru. i personally only have 5 plugin and thats mkvpropedit x5 even though i only have 2 that should trigger it.

Thank you.
