### ISSUE TITLE
Tdarr 2.00.22 fails to transcode videos

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#817]
**Describe the bug**
Updated to 2.00.22 and now it fails to transcode videos. Oddly the report only has a health report. Even more odd is that the screen has all green checkmarks:

![2023-07-31@10:15:37](https://github.com/HaveAGitGat/Tdarr/assets/2692127/06b9cbf1-cb0f-420e-a3f3-2092847ef555)

And yet it's marked as a transcode error.

**To Reproduce**
Install 2.00.22. Try to transcode a file.

**Expected behavior**
Transcodes to work as before.

[00LWrfcMA-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12217583/00LWrfcMA-log.txt)

Additional testing yields:

[handbrake.log](https://github.com/HaveAGitGat/Tdarr/files/12217774/handbrake.log)

If I remove `--scan` then the handbrake completes. Not familiar enough with the plugin system to figure out how to modify it to remove `--scan`. Also, the HandBrakeCLI command minus the `--scan` running on my Ubuntu desktop (where my Tdarr Node runs to take advantage of my Nvidia card) is not using the Nvidia card (nothing in `nvtop(1)` even though I see options for HandBrake NVENC 264 Configurable.

Reverting to the previous version of Tdarr for now...

 - OS: Synology (Docker)
 - Version 2.00.22

**Comment by dj-chalky** [comment]
I'm getting exactly the same on Windows

**Comment by HaveAGitGat** [comment]
Hi thanks for the report. The report itself is fine, `{"workerType":"healthcheckgpu"}` indicates it's coming from a health check worker so the rest of the logs are as expected with the --scan command.

Where is it saying that the transcode failed? Is it in the transcode error tab?

Please try 2.00.23 just released and let me know if you have the same issue thanks.

**Comment by HaveAGitGat** [comment]
There are quite a few files in there, takes about 30 seconds for me when starting up.

Are you able to try `docker pull haveagitgat/tdarr_acc:dev_2.00.24_2023_08_02T13_46_07z`, this will do a chown of your server data the on the first startup and then save the `puid` and `pgid` in `/app/server` and will only rechown if you change the puid or pgid in future. So should be a lot quicker as it persists between restarts and image updates.

**Comment by adefaria** [comment]
With 2.00.24 (dev) I updated the Tdarr Server and it seemed to work. Additionally, I can see those puid and pgid files:

```
Jupiter:docker exec -it tdarr_server cat /app/server/puid
1000
Jupiter:docker exec -it tdarr_server cat /app/server/pgid
1000
Jupiter:
```

I thought the problem might be that I use docker run in the script I've posted before (I can repost it if you want to see it). Since the container is removed then docker run is used to pull the new image and create the container that the /app/server/(puid|pgid) files would not be there and thus the chown happens again for me each time. But they seem to be surviving and that's good.

I was a little confused about how to get the matching Tdarr Node but figured it out. A video came along and it transcoded with no error. Good job!

**Comment by HaveAGitGat** [comment]
Thanks. This shouldn't be a problem for the node as the node /app data doesn't have many files in (excluding the node_modules folder which is ignored by the chown. Was the node taking a long time for you?

**Comment by adefaria** [comment]
It was a problem in that I was originally docker pulling from the wrong repository and getting the Tdarr Server on my Tdarr Node. It was only then that I figured out I needed to docker pull from haveagitgat/tdarr_node_acc (I was stupidly pulling from tdarr_acc). Once I straightened that out the Tdarr Node came up, did a few chowns then registered.

**Comment by HaveAGitGat** [comment]
Ah I see, glad you got there in the end. Will put these changes into latest today.

**Comment by adefaria** [comment]
I think I need to reopen this one. I thought it was working when I was using `haveagitgat/tdarr_acc:dev_2.00.24_2023_08_02T13_46_07z`. Then you updated it to the latest so I switched to `haveagitgat/tdarr:latest` and it started failing with:

[THUONmre8-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12256010/THUONmre8-log.txt)

Suspiciously it says Permissions error.

Reverting back to `haveagitgat/tdarr_acc:dev_2.00.24_2023_08_02T13_46_07z` (cause it was working) I get:

[9CCsRTavv-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12256045/9CCsRTavv-log.txt)

BTW is CHOWN_ON_START valid anymore or should I just get rid of it? I currently have it set to "false".

**Comment by HaveAGitGat** [comment]
The variable is `CHOWN_ON_STARTUP`. 

Those logs are practically the same with the same error (which is expected as haveagitgat/tdarr_acc:dev_2.00.24_2023_08_02T13_46_07z and haveagitgat/tdarr:latest are almost exactly the same).

You said it was working for you before but then you mentioned you `figured it out` with how to do some Node mappings. Which mappings did you use as I think that has caused the issue? You shouldn't need any mappings for the Node data . I have a test Node running with 99:100 permissions (different to the build 1000:1000 perms) which has been working fine.

**Comment by adefaria** [comment]
Sorry - CHOWN_ON_STARTUP. Do I need it or not?

I did nothing with Node as in the JavaScript thingy. My problem was that you told me to docker pull from haveagitgat/tdarr_acc:dev_2.00.24_2023_08_02T13_46_07z But that's for the Tdarr Server right? I didn't really change anything about the Tdarr Node and the two didn't like each other. Something about not being on the right version. It took me a while to realize that I had to change my Tdarr Node setup to pull from haveagitgat/tdarr_node_acc:dev_2.00.24_2023_08_02T13_46_07z. After that, I thought it was working.

Here are the scripts I'm using to create the Tdarr Server (run on my Synology) and my Tdarr Node (run on Earth, my Ubuntu Desktop with the Nvidia card):

tdarr_server script:

```
#!/bin/bash
mediaFolder=/Videos
host=$(hostname)
chown=false
#chown=true

# Test versions
docker_image=haveagitgat/tdarr_acc
docker_image_version=dev_2.00.24_2023_08_02T13_46_07z

# Production versions
#docker_image=haveagitgat/tdarr
#docker_image_version=latest

docker_container_name=tdarr_server

# Stop any running containers
docker container stop $docker_container_name > /dev/null 2>&1

# Remove any old docker container
docker container rm -f $docker_container_name > /dev/null 2>&1

# Recreate new docker container
docker run -d \
  -v $mediaFolder:$mediaFolder \
  -v /System/Cache/:/tmp \
  -v /docker/tdarr/:/app/server \
  -v /docker/tdarr/:/app/configs \
  -v /docker/tdarr/:/app/logs \
  -e PUID=1000 \
  -e PGID=1000 \
  -e "serverIP=0.0.0.0" \
  -e "webUIPort=8265" \
  -e "serverPort=8266" \
  -e "TZ=America/Los_Angeles" \
  -e "CHOWN_ON_STARTUP=$chown" \
  --network="bridge" \
  -p 8265:8265 \
  -p 8266:8266 \
  --log-opt max-size=10m \
  --log-opt max-file=5 \
  --name $docker_container_name \
  $docker_image:$docker_image_version

# With the container created start tdarr_server
echo "Starting tdarr_server on $host"
docker container start $docker_container_name

# This is needed to set the restart option
docker update --restart=unless-stopped $docker_container_name
```

tdarr_node script. Ignore the part about Mars. That's a Macbook running Ubuntu but since it doesn't have an Nvidia card I've never got it working correclty.

```
#!/bin/bash

serverIP=192.168.86.31
nodeIP=$(ip address | grep 192.168 | cut -c10-22)
host=$(hostname)
mediaFolder=/Videos
chown=false

# Testing versions
docker_image=haveagitgat/tdarr_node_acc
docker_image_version=dev_2.00.24_2023_08_02T13_46_07z

# Production versions
#docker_image=haveagitgat/tdarr_node
#docker_image_version=latest

docker_container_name=tdarr_node

# This just creates a pretty name for host with the first letter capitalized
Host=$(echo ${host:0:1} | tr [:lower:] [:upper:])$(echo ${host:1}   | tr [:upper:] [:lower:])

# Stop any running container
docker stop $docker_container_name > /dev/null 2>&1

# Remove any old tdarr_node container
docker container rm -f $docker_container_name > /dev/null 2>&1

# Create docker container
# This version does not add the NVIDIA stuff. I had a problem trying to
# create a docker container with Nvidia support for Mars but not for Earth.
# Seems the MacBook is not "CUDA cabable" but rather simulates CUDA using
# the CPU. This makes it very slow. It also makes it so we cannot specify
# Nvidia stuff here.
if [ "$host" = "mars" ]; then
  echo "Running docker container for Mars with no Nvidia support"
  docker run -d \
    -v $mediaFolder:$mediaFolder\
    -v /docker/:/tmp \
    -v /docker/tdarr:/app/server \
    -v /docker/tdarr/$host:/app/configs \
    -v /docker/tdarr/$host:/app/logs \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "nodeName=$Host" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -e "TZ=America/Los_Angeles" \
    -e "CHOWN_ON_STARTUP=$chown" \
    -p 8268:8268 \
    --network bridge \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name $docker_container_name \
    $docker_image:$docker_image_version
else
  echo "Running docker container for Earth with Nvidia support"
  docker run -d \
    -v $mediaFolder:$mediaFolder\
    -v /System/Cache/:/tmp \
    -v /docker/tdarr:/app/server \
    -v /docker/tdarr/$host:/app/configs \
    -v /docker/tdarr/$host:/app/logs \
    -e PUID=1000 \
    -e PGID=1000 \
    -e "nodeName=$Host" \
    -e "nodeIP=$nodeIP" \
    -e "nodePort=8268" \
    -e "serverIP=$serverIP" \
    -e "serverPort=8266" \
    -e "TZ=America/Los_Angeles" \
    -e "CHOWN_ON_STARTUP=$chown" \
    -e "NVIDIA_DRIVER_CAPABILITIES=all" \
    -e "NVIDIA_VISIBLE_DEVICES=all" \
    -p 8268:8268 \
    --device=/dev/dri:/dev/dri \
    --network bridge \
    --gpus=all \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --name $docker_container_name \
    $docker_image:$docker_image_version
  fi

# With the container created start tdarr_node_acc
echo "Starting $docker_container_name on $host"
docker start $docker_container_name

# This is needed to set the restart option
echo "Updating restart"
docker update --restart=always $docker_container_name
```

**Comment by HaveAGitGat** [comment]
Leave CHOWN_ON_STARTUP set to true and retry. You shouldn't need to disable it else you'll get permission errors.

**Comment by adefaria** [comment]
I think that's done it. I even set the tag to latest and all seems OK now. Start-up is a lot quicker. Good job!

I was thinking that with the new puid and pgid files that the CHOWN_ON_STARTUP was no longer needed. I guess it is.

**Comment by HaveAGitGat** [comment]
Ok thanks for the update. Yeah it should do a quick chown of some files on startup (after the one-off /app/server chown). One of the things with Docker is that the ownership on any unmapped files/folders resets when you restart or update a container. 

So in this instance if you chown /app/Tdarr_Node and then restart the container, the ownership of /app/Tdarr_Node will reset so  need to chown it again.

**Comment by adefaria** [comment]
I know a little about docker from an admin perspective so I may be a little like a fish out of water WRT docker dev issues. But wouldn't placing this in some required volume mount (mapped files/folders?) and have its owner survive docker container restarts?

**Comment by HaveAGitGat** [comment]
How long is it taking for you now? Should take barely any time at all as there are under 100 files or so that need to be chowned.

Moving the application data into a mapped folder would be a bad idea because there are 30,000+ files which would take a long time to copy over and any copy interruption or meddling would break things. Doing that also defeats the purpose of having a packaged application in Docker (almost) ready to go. In that instance you might as well not use Docker and just setup the app on the host system instead.

**Comment by adefaria** [comment]
I'm not sure if you mean something different by the term "mapped folder" but I don't understand why any "copy over" would need to be done. What I'm referring to is a docker volume mount like those given with -v to the docker run command. I mount my media folder (/Videos) to the Tdarr Server container with `-v /Videos:/Videos`. My media is 18 TB big. Surely no copy of 18Tb has happened as my Synology NAS would be full. 

What I'm asking for is couldn't whatever needs to be chowned be kept on a directory somewhere on the server running the docker container and mounted to the container via -v? Then the chown wouldn't need to be redone at all since the container would see the same directory it saw the last container run and the permissions should not have changed.

Perhaps there is something that prevents this that I'm unaware of.
