### ISSUE TITLE
A few minor improvements for windows users

### ISSUE THREAD

**Issue by klepp0906** [HaveAGitGat/Tdarr#818]
**Is your feature request related to a problem? Please describe.**
Having a tray icon is preferred and helpful for a lot of us using windows, so thanks for that.   Unfortunately the current implementation is less than ideal.  It requires us to have two tray icons, and every time the machine boots and said processes start, it opens two log windows that must be closed.

**Describe the solution you'd like**
It would be great if two things could be implemented.  Together or otherwise.  First a simple option to disable the opening of the logs window(s) upon startup.  Second an option to combine server & node into a single tray icon for those of us running on the same machine. 

**Describe alternatives you've considered**
The only workaround I have considered is sloppy and also non ideal.  I'm a new user so I could be incorrect, but it appears that starting the non-tray executable does not present said log window.   Unfortunately this comes at a cost of also not having it available in the tray.  In the interim I'm mulling over starting server_tray via the startup folder (as intended) and starting node (non-tray) via scheduled task at startup.  This only presents 1 log window instead of two, and leaves me with 1 tray icon instead of two.   Unfortunately it makes shutting down tdarr if needed also much more janky as I cant simply close the tray icon which is preferred and most user friendly of course.

its my understanding there are some docker builds that combine server and node into one, but i dont docker :P  maybe some day lol.

**Additional context**
Just a big thanks regardless, something you guys probably dont get nearly enough of.

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue. I've added an option in next version for toggling showing window on startup. In terms of starting both together, it's sometime useful to be able to close/restart the Node without closing/restarting the Server or vice versa. Won't be a priority for now but will add it in future if I have time.

**Comment by klepp0906** [comment]
Huge thank you.  I did/do realize a scenario could present in which one may want or need to be closed relative to the other.  How does the docker version with the single icon handle that?  (im wholly unfamiliar with docker)

I was thinking by default it would close both, but an option could be placed in the context menu to close and/or restart node vs server or something along those lines.

either way, I appreciate it.  wasnt sure if this would be acted on, let alone this fast.  in this demographic, sometimes windows users have to take what they can get :p

**Comment by tpcr** [comment]
I updated, Do not see the option to show/hide Tdarr tray window on start.
Where can I find it, or do I need to add to the config?

**Comment by HaveAGitGat** [comment]
Right click on the tray icon to toggle show/hide on start.

**Comment by anderconsu** [comment]
> Right click on the tray icon to toggle show/hide on start.

Is there an option to not launch the web ui on startup? I can't seem to find it
