### ISSUE TITLE
Filter only works on files where the video stream is 0:0

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#82]
I've noticed that the filter only works if the video stream is 0:0. Unfortunately, quite a few of my files don't have the video stream at 0:0. I've tried searching for a possible solution using ffprobe, but I don't see one. However, mediainfo can also export in json and shows the video stream first, no matter what "ID" it has

**Comment by HaveAGitGat** [comment]
Ah, use the re-order streams community  plugin 👍 Put it at the top of your plugin stack.

**Comment by theg00s3** [comment]
Thanks
