### ISSUE TITLE
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'

### ISSUE THREAD

**Issue by Fribb** [HaveAGitGat/Tdarr#820]
While I already posted on Issue #795 I think this isn't necessarily related to the mentioned issue but could possibly be the same source.

**Describe the bug**
I get the error message `Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'` and `Failed to inject frame into filter network: Function not implemented` when Tdarr is trying to do a thorough health check.

**To Reproduce**
In my case, it is just trying to do a health check on a particular file.

**Expected behavior**
The health check is running through.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
- [Tdarr_Server_Config.txt](https://github.com/HaveAGitGat/Tdarr/files/12258883/Tdarr_Server_Config.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
- [Qpgf5GJA7-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12258856/Qpgf5GJA7-log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
see worker log

Tdarr file Data: 
[data.txt](https://github.com/HaveAGitGat/Tdarr/files/12258902/data.txt)

 - OS: Docker (Unraid 6.12.2)
 - Browser: Chrome 115.0.5790.111
 - Version 2.00.24

**Comment by HaveAGitGat** [comment]
Hi , this seems different as the ffmpeg process has started and made some progress. Have you tried it without `-extra_hw_frames 10` which you set in the Node panel options? Worth a try

**Comment by Fribb** [comment]
> Hi , this seems different as the ffmpeg process has started and made some progress. Have you tried it without `-extra_hw_frames 10` which you set in the Node panel options? Worth a try

Just tried it and the issue is still present.

**Comment by HaveAGitGat** [comment]
Thanks I ran this exact command in the tdarr container and it worked fine for me. You can try it on the test file in the container:

`tdarr-ffmpeg -stats -v error -hwaccel nvdec -hwaccel_output_format cuda -extra_hw_frames 10 -i "/app/Tdarr_Server/assets/app/testfiles/h264-CC.mkv" -f null -max_muxing_queue_size 9999 "/app/Tdarr_Server/assets/app/testfiles/h264-CC2.mkv"`

Maybe try that and see if it works for you. If it works then would mean it's an issue with the other file you were health checking.

**Comment by Fribb** [comment]
That this is specific for those files, I wouldn't really want to rule out either because my other health checks are working fine too.

However, those files that are affected were successfully transcoded by Tdarr and failed in the health check. and the message being `Failed to inject frame into filter network: Function not implemented` and "Function not implemented" is what made me wonder why this happens. Maybe those particular files are running in an FFmpeg issue, that the other files do not? 

I will try to replace those files and let them transcode again and see if that addresses the issue or has some other result.

**Comment by Fribb** [comment]
I tried to replace the files but the same issue happened with them again so it is either a general issue with those files or something in relation to FFmpeg as well. Could I send you one of the files over at discord so that you might take a look and maybe be able to tell more about it?

**Comment by Fribb** [comment]
I did some further inspection on those files and it had severe colour discrepancies (red blood was actually purple). I replaced those files with a different version which would then run through the health checks without issues.

If those colour discrepancies are in connection with that issue (or maybe even the cause of it), I can't say but I would assume that this issue is just a problem with the file itself and some encoding issue.

Therefore I will close the issue.

**Comment by r-silver1** [comment]
> Hi , this seems different as the ffmpeg process has started and made some progress. Have you tried it without `-extra_hw_frames 10` which you set in the Node panel options? Worth a try

I'm actually not using your package but this extra_hw_frames flag fixed the same issue for me (I'm transcoding)

Thanks!
