### ISSUE TITLE
Disabling browser autostart

### ISSUE THREAD

**Issue by bulletproof2k** [HaveAGitGat/Tdarr#823]
I would like the Tdar to start with the start of the system, but I don't want it to be in the tray. If there is this possibility, tell me how to enable it. I would also like to remove the appearing window with logs.

**Comment by bulletproof2k** [comment]
How do I find this version?

**Comment by bulletproof2k** [comment]
> 2.00.25 has option in the tray to hide the window on start. If you don’t want to use the tray you can just run the executable that does not have ‘_Tray’ in. Add a shortcut to that in your startup folder 👍

 How do I find this version?

**Comment by HaveAGitGat** [comment]
Run Tdarr_Updater 

https://docs.tdarr.io/docs/installation/windows-linux-macos 

or download manually here https://f000.backblazeb2.com/file/tdarrs/versions.json

**Comment by bulletproof2k** [comment]
> Run Tdarr_Updater
> 
> https://docs.tdarr.io/docs/installation/windows-linux-macos
> 
> or download manually here https://f000.backblazeb2.com/file/tdarrs/versions.json

In this version, autorun is not disabled, the browser continues to open itself after launching the exe file.

**Comment by HaveAGitGat** [comment]
The window and browser are separate options. If you open the Tdarr_Server config in the configs folder you can disable the browser opening. I will move this option into the options tab in future
