### ISSUE TITLE
API call to start a new scan

### ISSUE THREAD

**Issue by doesntfazer** [HaveAGitGat/Tdarr#824]
**Describe the solution you'd like**
Maybe I'm doing something wrong but it doesn't look like there is an API call that can start the scan (find new) function of the program.
I've checked for a cruddb object, and Maybe I'm missing something, but I see nothing involving starting a new scan.
**Additional context**
I'm working on an external program that adds additional functionality to the scanning behavior. At the moment I use selenium to press the button via virtual browser. I would prefer to use an API call for consistency sake. 
https://github.com/doesntfazer/tdarrscanner/tree/main
This is the program I'm working on.

**Comment by HaveAGitGat** [comment]
Check the network request when you click the scan files button:

```
const body = {
  data: {
    scanConfig: {
      dbID: "zu3_uK7S0", 
      arrayOrPath: "Z:/Source",
      mode: "scanFindNew"
    }
  }
};

const url = 'http://localhost:8266/api/v2/scan-files';

fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(body)
})
.then(res => res.json())
.then(data => console.log(data))
.catch(error => console.error(error));
```

dbID is the libraryId which you can see in browser url:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3a96ccef-3e6c-4dfb-aa90-69c61152bee5)
