### ISSUE TITLE
Cant download and unzip plugins (community and local)

### ISSUE THREAD

**Issue by szym1998** [HaveAGitGat/Tdarr#826]
No plugins are visible in UI I get following errors

[2023-08-15T20:31:27.286] [ERROR] Tdarr_Server - Error: Invalid or unsupported zip format. No END header found
    at readMainHeader (/app/Tdarr_Server/node_modules/adm-zip/zipFile.js:101:32)
    at new module.exports (/app/Tdarr_Server/node_modules/adm-zip/zipFile.js:19:9)
    at new module.exports (/app/Tdarr_Server/node_modules/adm-zip/adm-zip.js:62:18)
    at /app/Tdarr_Server/srcug/commonModules/updatePluginThread.js:1:8400
    at _0xa47078 (/app/Tdarr_Server/srcug/commonModules/updatePluginThread.js:1:5610)
    at Object.next (/app/Tdarr_Server/srcug/commonModules/updatePluginThread.js:1:3833)
    at _0x5471cb (/app/Tdarr_Server/srcug/commonModules/updatePluginThread.js:1:2822)
[2023-08-15T20:31:28.014] [INFO] Tdarr_Server - Cache cleaner start
[2023-08-15T20:31:28.015] [INFO] Tdarr_Server - Cache cleaner end
[2023-08-15T20:31:29.289] [ERROR] Tdarr_Server - Plugin unzip failed!

**To Reproduce**
I run docker in a lxc contriner on proxmox maybe this is the issue 

**Expected behavior**
Plugins visible in UI

**Screenshots**
<img width="580" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/18391903/e95b3f5d-1ed1-488f-b04a-5da202d34d62">

<img width="280" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/18391903/0b35656f-92b7-4e7c-9bde-c83b7db4b9ac">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Config.json.pdf](https://github.com/HaveAGitGat/Tdarr/files/12352543/Tdarr_Server_Config.json.pdf)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12352537/Tdarr_Server_Log.txt)

 - OS: Debian lxc docker on proxmox VE 8
 - Browser no browser i think

**Comment by HaveAGitGat** [comment]
Is this some sort of container network config issue?

The plugin update just downloads this https://github.com/HaveAGitGat/Tdarr_Plugins
and puts it in the Plugins folder you showed.

**Comment by HaveAGitGat** [comment]
Also update to 2.00.25

**Comment by szym1998** [comment]
I run latest before but downgraded to lower version to see if this will help. It will not...

"Is this some sort of container network config issue?" How would I check this? Other containers run properly and ping the internet I also have a vpn docker that connects to expressvpn and this works good

**Comment by szym1998** [comment]
this is my docker compose

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/London
      - PUID=0
      - PGID=0
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=MyInternalNode
      - NODE_TLS_REJECT_UNAUTHORIZED=0  # Added this line
    volumes:
      - /var/lib/docker/volumes/tdarr/_data/server:/app/server
      - /var/lib/docker/volumes/tdarr/_data/configs:/app/configs
      - /var/lib/docker/volumes/tdarr/_data/logs:/app/logs
      - /docker/sabnzbd/:/media
      - /docker/tdarr/cache/:/temp

**Comment by szym1998** [comment]
Yup i can confirm its a network issue. It works when i add     network_mode: "host"  now i need to find out what's wrong in my docker network.

Thanks.
