### ISSUE TITLE
hundreds and hundreds (and hundreds!!) of powershell forks

### ISSUE THREAD

**Issue by robvanhooren** [HaveAGitGat/Tdarr#827]
**Describe the bug**

tdarr_server (_tray.exe) spawns hundreds and hundreds and hundreds of powershell.exe children

**To Reproduce**

1./
run v2.00.25 server & local node on windows10 x64 (native, not docker)

2./
observe system death after tens upon tens of gigabytes of RAM vanish over time due to hordes of runaway children

all are: 

`powershell.exe -NoProfile -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -   
`
(paired with instances of "Console Window Host")

if done while system is still usable, doing "c:\> taskkill /f /im powershell.exe /t" seems to return the system to some sort of a usable state

**Expected behavior**

expected = don't let tdarr do that  ¯\\\_(ツ)\_/¯ 

**Screenshots**

_(attached)_

**Please provide the following information:**
- Config files  _(attached)_

- Log files  _(attached)_

-Worker error  _n/a_

 - OS: node & server are win10x64 2H22 build 19045.3324
 - OS: client is macos v12.6.1
 - Browser is macos chrome 115.0.5790.170 x86_64
 - Version tdarr is 2.00.25
 

**Additional context**

_n/a_

**Comment by robvanhooren** [comment]
taskmgr screenshots

<img width="833" alt="Screen Shot 2023-08-18 at 05 39 58" src="https://github.com/HaveAGitGat/Tdarr/assets/30581164/6b9309f9-1317-41c5-bc77-f72c3de4345a">

<img width="824" alt="Screen Shot 2023-08-18 at 05 40 13" src="https://github.com/HaveAGitGat/Tdarr/assets/30581164/4b819ecc-ff03-40dd-b1c8-74bcddd71c45">

**Comment by robvanhooren** [comment]
server & node configs (w/ .txt extn postfixed for upload)

[Tdarr_Server_Config.json.txt](https://github.com/HaveAGitGat/Tdarr/files/12380913/Tdarr_Server_Config.json.txt)

[Tdarr_Node_Config.json.txt](https://github.com/HaveAGitGat/Tdarr/files/12380914/Tdarr_Node_Config.json.txt)

**Comment by robvanhooren** [comment]
server & node log files 

[Tdarr_Server_Log-REDACTED.txt](https://github.com/HaveAGitGat/Tdarr/files/12380962/Tdarr_Server_Log-REDACTED.txt)

[Tdarr_Node_Log-REDACTED.txt](https://github.com/HaveAGitGat/Tdarr/files/12380963/Tdarr_Node_Log-REDACTED.txt)

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue, this is not expected behaviour. I think this is called by a dependency `systeminformation` or `os-utils` and seems that for some reason it's not closing whatever it's using to gather cpu/mem stats. On my spare relatively slow laptop this console/powershell stuff flashes up for a split second then disappears (I assume that's how it is for most people).  I'll see if I can improve this or use a different depedency.

**Comment by HaveAGitGat** [comment]
Please try https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.10.01/win32_x64/Tdarr_Server_2023_08_28T10_15_20z.zip

Made some changes which should hopefully fix this thanks.

**Comment by robvanhooren** [comment]
I will later tonightcheers,R.Typogaphical errors courtesy of iPhone. On Aug 28, 2023, at 1:51 PM, HaveAGitGat ***@***.***> wrote:﻿
Please try 2.10.02 just released, reopen if needed thanks.
