### ISSUE TITLE
When starting multiple workers, the jobs starts to loop

### ISSUE THREAD

**Issue by raysv** [HaveAGitGat/Tdarr#828]
When starting multilple workers within a short periode of time, tdarr starts looping the jobs, one worker "steals" the job from another, and they get cancled after a while with the error another worker is allready working on it.

This also applies to health check workers and not only transcode.

**Comment by HaveAGitGat** [comment]
Please try 2.10.02 just released, reopen if needed thanks.

**Comment by raysv** [comment]
Same problem in 2.10.02, tried adding 5 healcheck workers, and the same file gets bounced around between the workers.
