### ISSUE TITLE
Add compression  (size difference) as a sortable  percentage column to the Transcode Success table

### ISSUE THREAD

**Issue by kramttocs** [HaveAGitGat/Tdarr#829]
Would be great to have a percentage column that we could sort by alongside the new and old sizes that exist currently in the Transcode Success table (tab).

Percentage would be like that shown during transcoding that shows the percentage of the new file compared to the original.

**Comment by HaveAGitGat** [comment]
@kramttocs might be better to do your second point in flows, something like this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/1c00f2a7-3ec9-42b3-a4a1-2ca432ff4668)

**Comment by HaveAGitGat** [comment]
Added for next version
