### ISSUE TITLE
Can't use QSV on my QNAP TVS-h874-i7 (12th gen)

### ISSUE THREAD

**Issue by neofleo** [HaveAGitGat/Tdarr#831]
**Describe the bug**
Seems thats Tdarr isn't using QSV as I want because CPU is used at 90% with 4 transcode and got like 9 FPS on each.

**To Reproduce**
Just installed and configured Tdarr following theses tutorial for Docker : 
https://www.youtube.com/watch?v=U6UMjTlwrxs
https://www.youtube.com/watch?v=JFvkJeDQRBQ
Kicked the NVIDIA part of the docker run : 

`docker run -ti \
    -v /share/ZFS20_DATA/Container/tdarr/server:/app/server \
    -v /share/ZFS20_DATA/Container/tdarr/configs:/app/configs \
    -v /share/ZFS20_DATA/Container/tdarr/logs:/app/logs \
    -v /share/ZFS19_DATA/Plex\ Media\ Server:/media \
    -v /share/ZFS20_DATA/Container/tdarr/transcode:/temp \
    -e "serverIP=192.168.1.158" \
    -e "serverPort=8266" \
    -e "webUIPort=8265" \
    -e "internalNode=true" \
    -e "inContainer=true" \
    -e "nodeName=MyInternalNode" \
    --network bridge \
    -p 8265:8265 \
    -p 8266:8266 \
    -e "TZ=Europe/Paris" \
    -e PUID=1000 \
    -e PGID=100 \
    --device=/dev/dri:/dev/dri \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    ghcr.io/haveagitgat/tdarr

&

docker run -ti \
    -v /share/ZFS20_DATA/Container/tdarr/configs:/app/configs \
    -v /share/ZFS20_DATA/Container/tdarr/configs:/app/logs \
    -v /share/ZFS19_DATA/Plex\ Media\ Server:/media \
    -v /share/ZFS20_DATA/Container/tdarr/transcode:/temp \
    -e "nodeName=MyExternalNode" \
    -e "serverIP=192.168.1.158" \
    -e "serverPort=8266" \
    -e "inContainer=true" \
    --network bridge \
    -p 8268:8268 \
    -e "TZ=Europe/Paris" \
    -e PUID=1000 \
    -e PGID=100 \
    --device=/dev/dri:/dev/dri \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    ghcr.io/haveagitgat/tdarr_node`

**Expected behavior**
Use GPU not CPU and get like 100 FPS

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/94976508/c2a8cc1c-8768-4020-a983-29b0d3f0cd89)
![image](https://github.com/HaveAGitGat/Tdarr/assets/94976508/54c5e479-f2b8-434b-b436-6d8b1a109e12)

**Please provide the following information:**
- Config files : 
[config.zip](https://github.com/HaveAGitGat/Tdarr/files/12444081/config.zip)

- Log files : 
[logs.zip](https://github.com/HaveAGitGat/Tdarr/files/12444080/logs.zip)

-Worker error : no special errors except if I want to use a QSV plugin, it fails

 - OS: QuTS hero h5.0.1
 - Browser: Firefox
 - Version: 2.00.25

**Additional context**
no

**Comment by HaveAGitGat** [comment]
Which plugins are you using? It's in the job report: https://docs.tdarr.io/docs/other/job-reports

**Comment by neofleo** [comment]
I've used 4 plugins :
Tdarr_Plugin_ER01_Transcode audio and video with HW (PC and Mac)
Tdarr_Plugin_Mthr_VaapiHEVCTranscode
Tdarr_Plugin_bsh1_Boosh_FFMPEG_QSV_HEVC
Tdarr_Plugin_drdd_standardise_all_in_one

Same problem I think Tdarr can't use i915 on my QNAP because I've installed Tdarr on a dedicated server with the same i7 and working all fine.

**Comment by HaveAGitGat** [comment]
Does this work?

```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'
```

**Comment by HaveAGitGat** [comment]
Alternatively can open a terminal in the tdarr container and run:

`ffmpeg -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -f null /dev/null`

Would need to play around with things until that command runs but yeah not too sure about how qnap handles this. Reopen if needed.
