### ISSUE TITLE
Error when checking duplicates

### ISSUE THREAD

**Issue by neofleo** [HaveAGitGat/Tdarr#832]
**Describe the bug**
When I want to scan and delete duplicates, I load just 10 pages of duplicates since I know that I got a looooooooooooot more duplicates and don't even want to delete, I got an error when trying to.

**To Reproduce**
Fresh install and scanning a "Movie" folder that is mounted using :
`sudo sshfs -o allow_other SSHUSER@100.95.78.23:/share/ZFS19_DATA/Plex\ Media\ Server/ /NAS`

**Expected behavior**
Full scan and delete working

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/94976508/3b1dc975-fa83-4c2d-a00d-3a4f9937f116)
![image](https://github.com/HaveAGitGat/Tdarr/assets/94976508/7217c3e6-d57a-4301-8d1e-360e972a16da)

**Please provide the following information:**
- Config & Logs files : [tdarrfiles.zip](https://github.com/HaveAGitGat/Tdarr/files/12446937/tdarrfiles.zip)

 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 2.00.25

**Comment by HaveAGitGat** [comment]
Thanks added a better error message for this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/32ebc6d1-b92b-424c-b6a8-7a28bbf83842)

**Comment by HaveAGitGat** [comment]
Feel free to reopen if the error message does not help solve the issue.
