### ISSUE TITLE
CPU usage when idle

### ISSUE THREAD

**Issue by modem7** [HaveAGitGat/Tdarr#834]
**Describe the bug**
CPU usage when idle is higher than expected.

**To Reproduce**
![image](https://github.com/HaveAGitGat/Tdarr/assets/4349962/9a20a5ef-a3e8-4067-84d7-d96d835f35de)

**Expected behavior**
Low CPU usage when idle

**Please provide the following information:**
- Config files
[Configs.zip](https://github.com/HaveAGitGat/Tdarr/files/12451797/Configs.zip)

- Log files
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12451790/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12451791/Tdarr_Node_Log.txt)

 - OS: Ubuntu
 - Browser:  Vivaldi
 - Version: 2.10.01 [26th August 2023]

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue. Is this the node or server container? Does the stats tab cpu graph show the same thing? This is my tdarr container idling at around 1% or so.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/14d4e135-614d-49b1-80dc-db1032441602)

**Comment by HaveAGitGat** [comment]
Please try 2.10.02 just released, reopen if needed thanks.
