### ISSUE TITLE
Use Apprise for notifications

### ISSUE THREAD

**Issue by derpindialer** [HaveAGitGat/Tdarr#836]
**Is your feature request related to a problem? Please describe.**
As somebody who doesn't use Discord, it would be awesome to send notifications to Apprise so I can send notifications anywhere I wish.

**Describe the solution you'd like**
Please make a way to use Apprise for notifications.

**Describe alternatives you've considered**
I want to use Telegram, but think Apprise would be easier to implement maybe? (I'm not a coder, so don't know what would be easy or difficult)

**Additional context**
I think the above explains it.

**Comment by HaveAGitGat** [comment]
Will move this under here thanks:
https://github.com/HaveAGitGat/Tdarr/issues/171

**Comment by HaveAGitGat** [comment]
Apprise added to Docker image in 2.18.01 just released, with "Apprise" flow plugin added too.

**Comment by psyciknz** [comment]
> Apprise added to Docker image in 2.18.01 just released, with "Apprise" flow plugin added too.

Any documentation update to show how to use it?  The only field under notifications is for "discord"

**Comment by Intecancoder** [comment]
I know it has been like 8 months, but for anyone searching this. Apprise can be config the using the guide in caronc/apprise. For telegram, it would be:
tgram://bottoken/ChatID
tgram://bottoken/ChatID1/ChatID2/ChatIDN
