### ISSUE TITLE
Flow Related: Replace file failed, deleting original and processed File

### ISSUE THREAD

**Issue by phoenixaus** [HaveAGitGat/Tdarr#837]
**Describe the bug**
Flow appeared to work correctly and encoding was processing as normal. The Last step is replace file, however the below error was generated and both the original and processed files were deleted.

**To Reproduce**
run the same flow again

**Expected behavior**
Expected the original to be overwritten by the processed file

**Screenshots**
copy of the flow is available at [https://1drv.ms/t/s!ApvToVPkk9FHgoMaFNzHqX0TJbFk-w?e=FJvfO2](url)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

```
-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
[2023-08-29T17:06:35.947] [ERROR] Tdarr_Node - Error: EXDEV: cross-device link not permitted, rename '/temp/tdarr-worker-dear-degus-ts-1693278495039/tempFile_1693278936645.mkv' -> '/Videos/Test/Avengers Endgame (2019).mkv.tmp'
    at Object.renameSync (node:fs:1042:3)
    at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/file/replaceOriginalFile/1.0.0/index.js:106:20
    at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/file/replaceOriginalFile/1.0.0/index.js:33:23)
    at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/file/replaceOriginalFile/1.0.0/index.js:14:53)
    at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/file/replaceOriginalFile/1.0.0/index.js:5:58) {
  errno: -18,
  syscall: 'rename',
  code: 'EXDEV',
  path: '/temp/tdarr-worker-dear-degus-ts-1693278495039/tempFile_1693278936645.mkv',
  dest: '/Videos/Test/Avengers Endgame (2019).mkv.tmp'
}
```

 - OS: Docker
 - Browser: [Chome]
 - Version [e.g. 2.00.00]

**Additional context**
Version 20.10.01

**Comment by HaveAGitGat** [comment]
Thanks, fixed so it does the original file deletion after move from cache to library:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/444/files#diff-fbd2b6b859fcab3c25cd7e08ec162fe3510a5cda7c3dbf685b8557f0deb8c8a6R77

Other issue here is that `cross-device link not permitted` so will add some more ways of trying to move the file else it's a permission issue.

**Comment by phoenixaus** [comment]
Thanks @HaveAGitGat , by the way really like the way flows work!!

**Comment by HaveAGitGat** [comment]
Thanks :)
