### ISSUE TITLE
Add Confirmation When Deleting Flows

### ISSUE THREAD

**Issue by RaboonTheBaboon** [HaveAGitGat/Tdarr#838]
**Is your feature request related to a problem? Please describe.**
When clicking Delete on a flow, it's an immediate action.
So a fair amount of effort could be wiped with a mis-click on a button rather close to "Duplicate".

**Describe the solution you'd like**
When clicking "Delete Flow" add a popup / popover "Are You Sure" Yes / No to confirm the action please.

**Describe alternatives you've considered**
Being less cackhanded.

**Additional context**
When clicking Delete on other elements in Tdarr, we're offered a confirmation, so this is expected / learned behaviour.
Flows looks brill by the way. Great work.

**Comment by HaveAGitGat** [comment]
Added thanks :)
