### ISSUE TITLE
Auto Accept Successful Transcodes set per library

### ISSUE THREAD

**Issue by kramttocs** [HaveAGitGat/Tdarr#839]
Could the Auto Accept Successful Transcodes be set per library?
I would prefer keeping it in the main Staging section vs at the library setting level but would like to have child checkboxes for each library.

**Comment by HaveAGitGat** [comment]
Looking to handle this with flows. For example: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3a7e55ea-cfc6-425f-84c2-0da77be9c33e)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5853007e-d135-4ee5-8165-bf5865d44e0f)

So can use the `Check Flow Variable` plugin to check the library id (which you can see in the url bar when browsing that library).
