### ISSUE TITLE
Tdarr_Plugin_075a_FFMPEG_HEVC_Generic Fails to convert with menu and data streams

### ISSUE THREAD

**Issue by clifford64** [HaveAGitGat/Tdarr#84]
The Tdarr_Plugin_075a_FFMPEG_HEVC_Generic fails to convert movies which have menu streams included in the video files. It also fails with other random streams. I had one that had a subtitle stream called Text.

**Comment by clifford64** [comment]
I also tried a plugin that removes metadata, but that did not seem to work.

**Comment by clifford64** [comment]
I was able to manually convert the file by running the below
ffmpeg -i INPUT.mp4 -c:v libx265 -c:a copy -c:s copy -map_chapters -1 OUTPUT.mkv

In theory, this should transcode to HEVC, copy audio tracks, copy subtitle tracks, and remove metadata/other streams.

**Comment by clifford64** [comment]
I was able to get it working by creating my own ffmpeg plugin using the below
,-c:v libx265 -c:a copy -c:s? copy

I am pretty sure this skips metadata.

**Comment by HaveAGitGat** [comment]
Yeah that should do the job.

FFmpeg can’t handle some audio/subs/data streams in certain containers but I didn’t want to purposefully remove them.

I’ll make some other plugins which have those parts omitted.
