### ISSUE TITLE
FLOWS: Add labels to decision based plugins. 

### ISSUE THREAD

**Issue by SC8198** [HaveAGitGat/Tdarr#841]
**Is your feature request related to a problem? Please describe.**
No, just some feedback

**Describe the solution you'd like**
Add a Yes or No label to the plugins that decide certain variables.

**Describe alternatives you've considered**
Could also be arrows or similar. Could also be a check mark or a X

**Additional context**
![image](https://github.com/HaveAGitGat/Tdarr/assets/104422567/8520d387-8240-495d-a473-069c30e69473)

**Comment by SC8198** [comment]
I just saw that there is other Plugins that have more than 2 options. So maybe just add the numbers on the flow chart modules? Whatever is more streamlined.

**Comment by HaveAGitGat** [comment]
Hi, think it would crowd up the UI quite a lot having all the output numbers. You can double click on a plugin to see what each output does.

**Comment by SC8198** [comment]
fair and understandable
