### ISSUE TITLE
Flow issue with Tdarr_Plugin_bsh1_Boosh_FFMPEG_QSV_HEVC 

### ISSUE THREAD

**Issue by marc-mendoza** [HaveAGitGat/Tdarr#843]
**Describe the bug**
Plugin throws error "cannot read properties of undefined (reading '0')" when running on Flow. Plugin works on a plugin stack.

**To Reproduce**
Use the plugin Tdarr_Plugin_bsh1_Boosh_FFMPEG_QSV_HEVC to transcode any file.

**Expected behavior**
Plugin works as it does when used on a plugin stack.

**Screenshots**

**Please provide the following information:**

Exported Flow:
[data.txt](https://github.com/HaveAGitGat/Tdarr/files/12527447/data.txt)

Truncated Error Log:
[KXiPMLePM-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12527443/KXiPMLePM-log.txt)

Full Error Log:
[KXiPMLePM-log(1).txt](https://github.com/HaveAGitGat/Tdarr/files/12527456/KXiPMLePM-log.1.txt)

**Additional context**

**Comment by HaveAGitGat** [comment]
Thanks this should be fixed with this change:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/459

So restart node and server or wait for hourly plugin update and should work fine
