### ISSUE TITLE
Flow: Compare File Size - Add optional "close enough"

### ISSUE THREAD

**Issue by Rycochet** [HaveAGitGat/Tdarr#844]
**Is your feature request related to a problem? Please describe.**

I'm wanting to change the file container if needed, and optional re-encode if it's in the wrong format - then finally check it's not grown *too much* - so if it gets up to 5% larger I don't mind, but doubling would be a problem etc.

**Describe the solution you'd like**

An option (default empty) to allow an increase in size, either absolute (`1m` / `250k`) or relative (`5%`), with either an extra output (new version) or allowing the "same size" to use this.

**Describe alternatives you've considered**

Going over the same file multiple times to change container, then to update the audio, then to re-encode the video (which is the only one that makes this into a potential problem) - this would probably be relevant with sending to a separate flow for each section, although this does mean multiple passes and replacements of the same file :-/

**Additional context**

My current (playing) flow:

![image](https://github.com/HaveAGitGat/Tdarr/assets/290714/730f7fcc-9530-46de-ab3f-40d82e1eced5)

**Comment by HaveAGitGat** [comment]
The `Tdarr_Plugin_a9he_New_file_size_check` classic plugin does this already as you can use % bounds for the new file size

**Comment by Kedryn** [comment]
Or the new Flow plugin Compare File Size Ratio 
Can't wait for the file duration too

**Comment by HaveAGitGat** [comment]
Updated `Compare File Size Ratio` with 3 outputs which should do what you're after
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d9d57367-ce0d-40d5-998e-604e79013302)

Reopen if needed.

@Kedryn I'll try do that soon
