### ISSUE TITLE
UI: drop down menus in Tdarr>Staging Section>Actions don't work in Safari

### ISSUE THREAD

**Issue by doughaas** [HaveAGitGat/Tdarr#845]
Bug: Drop down menus don't work

**To Reproduce**
open safari
Navigate to Tdarr instance
Scroll down to Staging Section
click cogwheel in Action column
Nothing happens

**Expected behavior**
drop down menu should show option to requeue

![Screenshot 2023-09-07 at 4 31 17 PM](https://github.com/HaveAGitGat/Tdarr/assets/3875923/2ac5d5b1-db6a-4abf-a1e2-7c2baa5addba)

 - OS: macOS Ventura 13.5.1
 - Browser safari 16.6 
 - Version 2.11.01

**Additional context**
menus work on Firefox

**Comment by HaveAGitGat** [comment]
Thanks, working fine on Chrome and Firefox so just Safari which has this. Safari always has quirks like this so wouldn't say it's a fully supported browser but will fix this when I have some hardware for it.

**Comment by HaveAGitGat** [comment]
Fixed for next version
