### ISSUE TITLE
multi lang VFF or VFQ

### ISSUE THREAD

**Issue by foXaCe** [HaveAGitGat/Tdarr#847]
Good morning,

Is there a way to detect if it is fr or frq?
I would like to keep only the fr 🤷

![image](https://github.com/HaveAGitGat/Tdarr/assets/290678/c680ebbe-c6b3-43f9-bcfa-8933d9fa9781)

**Comment by HaveAGitGat** [comment]
Hi, I've added flow plugin `Remove Stream By Property`:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/498

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5ea8e6c1-38c4-4604-8e37-ec255b8b1f4b)

In this case I think you set the inputs like this:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/453b51d4-8b2e-4f6c-a713-2958c5618fc3)

Then in logs it will show what it's removing (different example):

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5b35b588-6558-4f3b-895b-81e0dd931a98)

You can see the tream info when you click on the filename on the Tdarr tab:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6ee72463-828f-40e7-97ec-a349cb9d1a24)

**Comment by foXaCe** [comment]
thank you for this

2023-10-09T13:24:18.240] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'length')
    at hash (/app/Tdarr_Server/node_modules/string-hash/index.js:5:18)
    at Object.getById (/app/Tdarr_Server/srcug/db/_memoryDB.js:1:2525)
    at Object.getById (/app/Tdarr_Server/srcug/db/crudNewDBBE.js:1:7854)
    at /app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:5366
    at k (/app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:3552)
    at Object.next (/app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:2647)
    at /app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:2301
    at new Promise (<anonymous>)
    at __awaiter (/app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:2017)
    at addFlowToStateHandler (/app/Tdarr_Server/srcug/api/nodeRelay/getFlowPlugins.js:1:5183)


🤔

**Comment by HaveAGitGat** [comment]
I suspect you have no flow selected or something like that. Make sure the flow is selected in the library settings.

**Comment by HaveAGitGat** [comment]
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/22216fea-05e2-4147-828d-7b2e13790e9c)

**Comment by foXaCe** [comment]
lol yes sorry 😪😪

now i have this bug

1

2023-10-09T19:57:47.231Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:[Step W03] [C2] [Remove ENG/VFQ and Full sub] Running Community plugin: 1.0.0: ffmpegCommandRorderStreams: Reorder Streams

2

2023-10-09T19:57:47.232Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Scanning original library file

3

2023-10-09T19:57:47.232Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:{

4

2023-10-09T19:57:47.232Z "exifToolScan": true,

5

2023-10-09T19:57:47.232Z "mediaInfoScan": false,

6

2023-10-09T19:57:47.232Z "closedCaptionScan": false

7

2023-10-09T19:57:47.232Z }

8

2023-10-09T19:57:47.233Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Loading source file: /data/media/tv/The Changeling (2023)/Season 01/The Changeling (2023) - S01E04 - The Wise Ones [WEBDL-2160p][DV HDR10][AC3 5.1][FR][10bit][h265][FR]-FW.mkv

9

2023-10-09T19:57:47.233Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Scanning source file: /data/media/tv/The Changeling (2023)/Season 01/The Changeling (2023) - S01E04 - The Wise Ones [WEBDL-2160p][DV HDR10][AC3 5.1][FR][10bit][h265][FR]-FW.mkv

10

2023-10-09T19:57:47.234Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Scan types: {

11

2023-10-09T19:57:47.234Z "exifToolScan": true,

12

2023-10-09T19:57:47.234Z "mediaInfoScan": false,

13

2023-10-09T19:57:47.234Z "closedCaptionScan": false

14

2023-10-09T19:57:47.234Z }

15

2023-10-09T19:57:47.234Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Using cached scan results

16

2023-10-09T19:57:47.234Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Loaded plugin inputs: {

17

2023-10-09T19:57:47.234Z "processOrder": "codecs,channels,languages,streamTypes",

18

2023-10-09T19:57:47.234Z "languages": "",

19

2023-10-09T19:57:47.234Z "channels": "7.1,5.1,2,1",

20

2023-10-09T19:57:47.234Z "codecs": "",

21

2023-10-09T19:57:47.234Z "streamTypes": "video,audio,subtitle"

22

2023-10-09T19:57:47.234Z }

23

2023-10-09T19:57:47.235Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:[-error-]

24

2023-10-09T19:57:47.235Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:TypeError: Cannot read properties of undefined (reading 'streams')

25

2023-10-09T19:57:47.236Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:"Cannot read properties of undefined (reading 'streams')"

26

2023-10-09T19:57:47.236Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:"TypeError: Cannot read properties of undefined (reading 'streams')\n at Object.plugin (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/ffmpegCommand/ffmpegCommandRorderStreams/1.0.0/index.js:77:74)\n at a.<anonymous> (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:17264)\n at k (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:2416)\n at Object.next (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:1493)\n at h (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:944)"

27

2023-10-09T19:57:47.236Z Ar30mAAqZ:Node[Node Name]:Worker[old-otter]:Flow has failed

**Comment by HaveAGitGat** [comment]
What is your flow? You need to put the ‘Begin Command’ plugin at the start when using the FFmpeg command plugin like re-order streams

**Comment by foXaCe** [comment]
Ah OK. I don't know much about flow

I simply want to remove all audio and subtitles other than fr
and make a reorder

**Comment by foXaCe** [comment]
do you have a template json ?

**Comment by foXaCe** [comment]
{
  "name": "Keep Only FR",
  "description": "Keep Only FR",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "ohAzGFtKi",
      "position": {
        "x": 585.7447571727887,
        "y": -65.26795870863589
      }
    },
    {
      "name": "Begin Command",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "5xPJjKCxf",
      "position": {
        "x": 586.1376682242919,
        "y": -256.6496414067848
      }
    },
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "qNCVxyavt",
      "position": {
        "x": 587.1335212671282,
        "y": -339.9073505217323
      }
    },
    {
      "name": "Begin Command",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "GFwo0VSZ3",
      "position": {
        "x": 371.2069188391339,
        "y": -446.9340776322065
      }
    },
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "inputsDB": {},
      "id": "smAYYQdPOy",
      "position": {
        "x": 371.426544725069,
        "y": -543.280649209044
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_MC93_MigzImageRemoval",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_MC93_MigzImageRemoval"
      },
      "id": "4Ps8N92T81",
      "position": {
        "x": -53.90363001018267,
        "y": -167.15632371050572
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_MC93_Migz3CleanAudio",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz3CleanAudio",
        "language": "fre,und",
        "commentary": "true",
        "tag_language": "fre",
        "tag_title": "true"
      },
      "id": "OA-hH_6Sgr",
      "position": {
        "x": 168.7110788292972,
        "y": -163.08388975391858
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_MC93_Migz4CleanSubs",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz4CleanSubs",
        "language": "fre,und",
        "commentary": "true",
        "tag_language": "fre"
      },
      "id": "s0fmA_NGEx",
      "position": {
        "x": 168.7110788292972,
        "y": -63.083889753918584
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_MC93_Migz2CleanTitle",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz2CleanTitle",
        "clean_audio": "true",
        "clean_subtitles": "true"
      },
      "id": "MSpIn6FKi3",
      "position": {
        "x": 169.37140191051424,
        "y": 54.3642401707377
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_a9he_New_file_size_check",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_a9he_New_file_size_check"
      },
      "id": "ul8Al2pYVJ",
      "position": {
        "x": 169.5674537557842,
        "y": 179.53899017145147
      }
    },
    {
      "name": "Run Classic Transcode Plugin: Tdarr_Plugin_goof1_URL_Plex_Refresh",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_goof1_URL_Plex_Refresh",
        "Plex_Url": "192.168.1.60",
        "Plex_Token": "eP94Zhw4TnTpnkaZs7bo",
        "Library_Key": "2"
      },
      "id": "_QxpG9MJF53",
      "position": {
        "x": 168.7110788292972,
        "y": 306.942987819036
      }
    },
    {
      "name": "Replace Original File",
      "sourceRepo": "Community",
      "pluginName": "replaceOriginalFile",
      "version": "1.0.0",
      "inputsDB": {},
      "id": "Hkai0dmSd",
      "position": {
        "x": 368.7110788292972,
        "y": 436.9161102460814
      }
    },
    {
      "name": "Remove Stream By Property",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandRemoveStreamByProperty",
      "version": "1.0.0",
      "id": "7CvXLBAgk",
      "position": {
        "x": 812.1854040550775,
        "y": 113.41421927797737
      },
      "inputsDB": {
        "valuesToRemove": "vfq,Full,Complets,FRQ,vq",
        "propertyToCheck": "tags.title"
      }
    },
    {
      "name": "Begin Command",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "fPpK75eZS",
      "position": {
        "x": 584.6071107289929,
        "y": 31.676616744692694
      }
    },
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "Q0KpVJq5a",
      "position": {
        "x": 810.4888314609714,
        "y": 176.81130533898042
      }
    },
    {
      "name": "Reorder Streams",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandRorderStreams",
      "version": "1.0.0",
      "id": "OygmggIL_",
      "position": {
        "x": 371.39119758776087,
        "y": -337.66039987578006
      },
      "inputsDB": {
        "languages": "fre"
      }
    },
    {
      "name": "Remove Data Streams",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandRemoveDataStreams",
      "version": "1.0.0",
      "id": "1T5T9KvPn",
      "position": {
        "x": 587.1034012505934,
        "y": -157.5693899651539
      }
    }
  ],
  "flowEdges": [
    {
      "source": "4Ps8N92T81",
      "sourceHandle": "1",
      "target": "OA-hH_6Sgr",
      "targetHandle": null,
      "id": "xAUgf9WszP"
    },
    {
      "source": "OA-hH_6Sgr",
      "sourceHandle": "1",
      "target": "s0fmA_NGEx",
      "targetHandle": null,
      "id": "IZb5GD4yW6"
    },
    {
      "source": "ul8Al2pYVJ",
      "sourceHandle": "1",
      "target": "_QxpG9MJF53",
      "targetHandle": null,
      "id": "LHVcBQ84EN0"
    },
    {
      "source": "_QxpG9MJF53",
      "sourceHandle": "1",
      "target": "Hkai0dmSd",
      "targetHandle": null,
      "id": "8w1GPmBCJFQ"
    },
    {
      "source": "fPpK75eZS",
      "sourceHandle": "1",
      "target": "7CvXLBAgk",
      "targetHandle": null,
      "id": "eUAs8Bova"
    },
    {
      "source": "s0fmA_NGEx",
      "sourceHandle": "1",
      "target": "fPpK75eZS",
      "targetHandle": null,
      "id": "wmJ4GY1qE"
    },
    {
      "source": "7CvXLBAgk",
      "sourceHandle": "1",
      "target": "Q0KpVJq5a",
      "targetHandle": null,
      "id": "oLVV3eXZe"
    },
    {
      "source": "Q0KpVJq5a",
      "sourceHandle": "1",
      "target": "MSpIn6FKi3",
      "targetHandle": null,
      "id": "-ZkUKJDd8"
    },
    {
      "source": "smAYYQdPOy",
      "sourceHandle": "1",
      "target": "GFwo0VSZ3",
      "targetHandle": null,
      "id": "IO0mFJLKn"
    },
    {
      "source": "GFwo0VSZ3",
      "sourceHandle": "1",
      "target": "OygmggIL_",
      "targetHandle": null,
      "id": "WsjsTEd5T"
    },
    {
      "source": "OygmggIL_",
      "sourceHandle": "1",
      "target": "qNCVxyavt",
      "targetHandle": null,
      "id": "2kcfU1w7X"
    },
    {
      "source": "qNCVxyavt",
      "sourceHandle": "1",
      "target": "5xPJjKCxf",
      "targetHandle": null,
      "id": "2V6MVk-4F"
    },
    {
      "source": "5xPJjKCxf",
      "sourceHandle": "1",
      "target": "1T5T9KvPn",
      "targetHandle": null,
      "id": "ylejZeham"
    },
    {
      "source": "1T5T9KvPn",
      "sourceHandle": "1",
      "target": "ohAzGFtKi",
      "targetHandle": null,
      "id": "_30oxmx3S"
    },
    {
      "source": "ohAzGFtKi",
      "sourceHandle": "1",
      "target": "4Ps8N92T81",
      "targetHandle": null,
      "id": "vYp8J8EGO"
    },
    {
      "source": "MSpIn6FKi3",
      "sourceHandle": "1",
      "target": "ul8Al2pYVJ",
      "targetHandle": null,
      "id": "KC68iSt7G"
    }
  ]
}

**Comment by foXaCe** [comment]
thank you for the work

I created a flow that works, I think we can do better but it works

**Comment by HaveAGitGat** [comment]
Glad it's working for you. FYI you can connect the ffmpeg command plugins directly together like this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9f00cf4d-d64e-4bd9-8553-00e8c80d7b73)

**Comment by foXaCe** [comment]
thanks you for the tips
