### ISSUE TITLE
Multiselect in Staging

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#848]
**Is your feature request related to a problem? Please describe.**
When the stagin list is pretty long, we can select an action  for the entire list, or act on one file at a time. 
With the new multibutton, the processing of a single file is even longer than when we had all buttons visible and not like a menu list.
Right now, for example, i have to skip like 50 episodes, and that will take a lot of time, and it's prone to errors (the row isn't always in sync with it's buttons, when we have already chosen actions not yet completed for rows that are higher than the one we are working on)

**Describe the solution you'd like**
Let us multiselect (ie: a checkbox on each file) then choose an action for all selected files.

**Comment by HaveAGitGat** [comment]
You effectively do  multiselect by using the filters: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/63f64b8e-e37e-41dc-aee0-1ac673f42bf9)

Can maybe add row multi select using checkboxes in future but not priority right now ty.
