### ISSUE TITLE
Option to toggle keeping folder structure in output folder (and other output folder related requests)

### ISSUE THREAD

**Issue by HaveAGitGat** [HaveAGitGat/Tdarr#85]
A simple toggle to choose to keep the source directory structure or just save files without any and go directly to the output folder would be perfect.

**Comment by HaveAGitGat** [comment]
https://github.com/HaveAGitGat/Tdarr/issues/1

**Comment by HaveAGitGat** [comment]
Current output folder method will be scrapped.

Post processing plugins will be used instead to achieve this:
https://github.com/HaveAGitGat/Tdarr/issues/136

**Comment by BillyTheKid9588** [comment]
Hi,

Is there any existing post processing plug in that achieves this?

I couldn't see anything that would do this.

Thanks

**Comment by HaveAGitGat** [comment]
Added in Tdarr Flows:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/5a1e7725-06a6-46e6-9590-dfac514bfeef)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6edb6770-3db0-49d4-8ce7-84fda30ad4a7)

**Comment by HaveAGitGat** [comment]
Beta released the other day, feel free to reopen if you have any issues.
