### ISSUE TITLE
[Output Display] Font not embedded when using Tray mode

### ISSUE THREAD

**Issue by LanceMcCarthy** [HaveAGitGat/Tdarr#851]
### Description

The opening character of output is invalid, see the following screenshot, I call out the specific unknown character code (I suspect it's supposed to be an angle bracket?).

![image](https://github.com/HaveAGitGat/Tdarr/assets/3520532/bedb01f0-0a15-4b7b-bd09-f51c56b9d086)

Generally speaking, this happens when there is a character code that is not available in the currently used font/font family. Typically a problem when the expected ttf is not being included in the output assets/build artifacts.

If this were a .NET project, you would right-click on the .ttf file inside the Solution Explorer and select Properties. Then set the Build Action to "Copy always", but I'm afraid I not able to give you a head start for this project as I'm not familiar with its source code.

Maybe it needs to be included in the public/static/media folder? I did see the main.css has a bunch of font families defined:

![image](https://github.com/HaveAGitGat/Tdarr/assets/3520532/4b492ec1-8335-49e9-8269-0c4d14d7b155)

## Behavior

**To Reproduce**
Run the tray app (server or node) on Windows 11.

**Expected behavior**
All the characters in the output text would render correctly

## Log & Config Info

- Config files - only relevant info from the config is `"platform_arch": "win32_x64_docker_false"`
- Log files - character encoding warnings do not appear in the app log
- Worker error - No errors

## Environment

 - OS: `Windows 11`
 - Browser: `n/a`
 - Version: `2.11.01`

**Comment by HaveAGitGat** [comment]
I'm assuming it's just the color data from the logs which isn't interpreted by gioui correctly, will try stripping it out.

**Comment by LanceMcCarthy** [comment]
If it's at the risk of losing the line color, then I'd just keep it there... I'm a HUGE  fan of color in CLI output, as you can see in one of my apps => https://github.com/LanceMcCarthy/RemixDownloader#console-app---automatic-bulk-downloader 😂

**Comment by HaveAGitGat** [comment]
Ah nice. The colors you see in the tray are added manually with gioui by parsing the string for 'ERROR', 'WARN' etc so trimming the first few characters from each line shouldn't affect anything.

**Comment by HaveAGitGat** [comment]
Fixed for next version.
