### ISSUE TITLE
Path mapping failing when subdirectory matches another root directory

### ISSUE THREAD

**Issue by cemtaylor** [HaveAGitGat/Tdarr#852]
**Describe the bug**
It appears that whatever replacement is done when mapping paths between linux hosts and windows hosts is not properly checking that the replacement is happening at the beginning of the path. This results in a path that looks like this:
`u06n05w2D:Node[gaius]:Worker[fussy-fawn]:Loading source file: Z:/media/movies/The Batman (2022)/The Batman 2022 Remux-2160p.mkv`
Becoming this when fed through to a windows node:
`Scanning source file: Z:/mediaZ:/movies/The Batman (2022)/The Batman 2022 Remux-2160p.mkv`

I believe this is happening as I have maps of /media -> Z:/media and /movies -> Z:/movies - so the replacement is happening twice replacing Z:/mediaZ:/movies/RestOfPath/

**To Reproduce**
Configure a unix host to share out /media and /movies, nest a movies directory under /media (/media/movies/movie name/movie.mkv) and map these to a windows host.

**Expected behavior**
The replacement should (assuming this is a simple regex used here) check that the replacement is happening at the start of the line (the match should use ^).

**Screenshots**
N/A

**Please provide the following information:**
Node Config:
  "pathTranslators": [
    {
      "server": "/tv",
      "node": "Z:/tv"
    },
    {
      "server": "/4ktv",
      "node": "Y:/tv"
    },
    {
      "server": "/movies",
      "node": "Z:/movies"
    },
    {
      "server": "/4kmovies",
      "node": "Y:/movies"
    },
    {
      "server": "/media",
      "node": "Z:/media"
    },
    {
      "server": "/temp",
      "node": "Y:/transcode"
    }
  ],

- Version 2.11.01

**Comment by HaveAGitGat** [comment]
Thanks will look into this. Think there was a scenario in the past where the translation not only happens at the beginning but also in the middle of a string so if you have lots of overlapping paths/translators like this then could cause issues.

**Comment by HaveAGitGat** [comment]
Upon further inspection the the replacement should be happening at only the start but the flow system has some new fields which aren't included in this so the translation can happen at any point in the string.

Fix will be in next update.

**Comment by HaveAGitGat** [comment]
2.12.01 released, feel free to reopen if you still have an issue thanks
