### ISSUE TITLE
Better estimates for 2-pass encoding

### ISSUE THREAD

**Issue by AroundThisWorldAgain** [HaveAGitGat/Tdarr#854]
**Is your feature request related to a problem? Please describe.**
2-pass (or more if audio tracks need to be encoded) encoding estimates aren't accurate.  2 main issues:

- The % complete is % of the current pass.  So it goes 0-100, 0-100
- The time estimates are very low on pass 1 and very high on passes > 1 (e.g. pass 2 is at 3%, but it's already taken 30 minutes, so tdarr calculates 16 hours instead of 29 minutes)

**Describe the solution you'd like**
Accurate info is obviously impossible since we don't know how long each pass will take, but assuming 1/N % for each pass would give much better numbers for both % & time

**Comment by HaveAGitGat** [comment]
This would a case of updating the ffmpeg parser here:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/bb73fe6c4d7fa222720b24f50701da528bfe0d26/FlowPluginsTs/FlowHelpers/1.0.0/cliParsers.ts#L106

Will have a go at it if I get some time but feel free to poke around. That code is for Tdarr Flows so would need to run your plugin in a flow.

**Comment by HaveAGitGat** [comment]
Working as expected for me. You didn't mention what way you're running this. If you run in it in Tdarr Flows then works as expected as each pass is a different execution:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/b7c182a6-6288-4962-8b06-a19927bce3e3)


Pass 1 `-c:v libx265 -preset veryfast -pass 1 -f null`:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/c3f253dc-b969-4f6e-a5f9-4842a3afad27)

Pass 2 `-c:v libx265 -preset veryfast -pass 2`:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/923c83fb-6f17-4c10-98ed-b600bbe92914)

**Comment by AroundThisWorldAgain** [comment]
I'm running both passes in Handbrake as a single operation in a flow

**Comment by HaveAGitGat** [comment]
Updated here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/529/files
