### ISSUE TITLE
Link speed drops to 50mbps

### ISSUE THREAD

**Issue by AlexWhitehouse** [HaveAGitGat/Tdarr#856]
**Describe the bug**
I currently have a Windows machine that I run the Tdarr server and node from which has a transcode cache for Tdarr locally. I have my movie library on a separate TrueNAS box. When I run an iperf3 test before and after I start the server and node I have a 100mbps+ connection speed. When I run the server and node on my Windows machine I get a hard cap at 50mbps as shown in the screenshots (although when checking I don't see any time where the bandwidth goes above 10mbps) which is shown in an iperf3 test where I get a max transfer speed of 10mbps between the two machines.

I then ran an iperf3 test from another machine to both the Windows machine and the TrueNAS machine and see a connection of over 100mbps to both independently. It appears as though after starting the server and node, the connection between the Windows machine and the TrueNAS machine deteriorates? 

Anyone know the reason for this?

**To Reproduce**
Run iperf3 test between machines before and after running the Tdarr server/node

**Expected behavior**
Tdarr uses the entire bandwidth available rather than capping at 50mbps

**Screenshots**
After starting Tdarr server and node. This shows the data transfer from the TrueNAS machine (where the libraries are held) being capped at 50mbps
![image](https://github.com/HaveAGitGat/Tdarr/assets/13820559/a085cff5-108c-4d07-983a-5efbb87a10b1)

Running an iperf3 test whilst the Tdarr server/node is running
![image](https://github.com/HaveAGitGat/Tdarr/assets/13820559/a0a06937-8001-4bd6-a64f-318b4a08e3f3)

Running an iperf3 test whilst the server/node are not running
![image](https://github.com/HaveAGitGat/Tdarr/assets/13820559/b5356315-1f9c-471d-b167-7e9b99482b6e)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows
 - Browser Chrome
 - Version 2.11.01

**Additional context**

**Comment by HaveAGitGat** [comment]
Haven't had any other reports of this happening over the last few years so I assume there's something going on locally with your setup but not too sure what sorry. Tdarr doesn't do any network configuration changes or anything like that. Is this maybe a windows power mode issue? E.g. if windows is in low power mode it may throttle cpu/network which reduces speeds? Something like that?

**Comment by HaveAGitGat** [comment]
Running with a rubbish old Windows node on wireless to a linux server is giving me 150Mb/s:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/30e26429-ff5e-4118-950d-ef7d296b3dc7)

So perhaps is some sort of firewall issue. Maybe worth asking on the Truenas forum. Can reopen if any developments.
