### ISSUE TITLE
Database optimisation screen/job

### ISSUE THREAD

**Issue by modem7** [HaveAGitGat/Tdarr#859]
Unsure if Tdarr already does this in the background, but the ability to trigger a database optimisation/vacuum would be very useful for larger libraries (especially if doing a full scan).

Similar functionality exists in Plex:
![image](https://github.com/HaveAGitGat/Tdarr/assets/4349962/27a586bf-e7e2-4528-add9-7f6f6c974c34)

I've noticed that in my latest full scan (around 14,000) items, the healthcheck and hold numbers  aren't updating regularly (it does during normal operation, I'm mostly doing it as an edge case due to redoing my Tdarr workflow, so wanted to make sure every item in the library is processed with the new workflow). 

Unsure if this is a DB issue, or just because there's a lot of items being processed, but the healthcheck workers are mostly sitting at "awaiting new task": 

![image](https://github.com/HaveAGitGat/Tdarr/assets/4349962/bc82be57-928b-4724-9f70-d12e3912451a)

![image](https://github.com/HaveAGitGat/Tdarr/assets/4349962/be96d95d-506e-4a47-a6ec-ff3cb34a91b5)

If this is more DB related, then the above may help with keeping things running optimally. 

If it's more storage/IOPS/throughput related, then so be it, not much can be done for that!

**Comment by HaveAGitGat** [comment]
I think it's could be related to the stats updating process depending on how many streams the files have.

I've made a dev update so the stats updating runs less often (there's a button to run it manually if needed).

I've also added some endpoint/function performance monitoring on the stats page, have a try here:

`haveagitgat/tdarr_acc:dev_2.12.01_2023_09_26T18_31_32z`

Check these 3 things:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d292eed2-3ed0-43c4-8443-c9203fe4a67e)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/e13d3e6e-e0f9-416d-bfd3-5d45d069690f)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/fa5e0efa-3d8a-41f9-a35d-62589c6f8331)

Hopefully the change I made fixes the issue for you else will be interesting if you can anything that's taking a very long time.

For example with a few thousand files it takes about 41ms to get a new task in my case:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/131bc6ba-6237-4d7f-ab33-3da1d1e7984a)

**Comment by HaveAGitGat** [comment]
2.13.01 released, reopen if needed thanks.
