### ISSUE TITLE
FLOWS transcode plugin does not use hardware

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#861]
**Describe the bug**
In my flow, i use the Set Encoder to force scaling of an already HEVC to a lower resolution:

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/f7555ad0-a2ca-4cbe-8dd6-8fa143c76a30)
![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/804f028e-cf0e-4e09-b887-58533233b5fb)

The resulting command does NOT use QSV even if it's run on a QSV capabe node:

`Preset: | -y -i //172.16.0.190/Storage/media/movies_transcoding/La bambola assassina 3 (1991) [tmdb-11187]/La bambola assassina 3 (1991) [tmdb-11187][WEBDL-2160p][HDR10][EAC3 2.0][x265].mkv -map 0:0 -c:0 libx265 -crf 21 -preset slow -vf scale=1920:-2 -pix_fmt:v:0 p010le -profile:v:0 main10 -map 0:1 -c:1 copy -map 0:2 -c:2 copy -map 0:3 -c:3 copy -map 0:4 -c:4 copy -map 0:5 -c:5 copy //172.16.0.190/transcoding_temp/movies_transcoding/tdarr-workDir-node-cF6EFUBTy-worker-low-loris-ts-1695732227413/1695732230010/La bambola assassina 3 (1991) [tmdb-11187][WEBDL-2160p][HDR10][EAC3 2.0][x265].mkv
`

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/dd24cdbb-f0de-48f0-97b6-cac0b8a4eb37)
It's doing 1 fps on an 11th intel i5

**To Reproduce**
as per screenshot

**Expected behavior**
Use the QSV as other plugin i wrote, does

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Unraid
 - Browser chrome
 - Version 2.12.01

**Comment by HaveAGitGat** [comment]
Hi, working fine my side with UHD 620 chip on i8250U. Which processor are you using?

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dc1eece3-9fd8-4757-9ab6-8cd70218a155)

Try running the following which is effectively the test that is run here to detect devices: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/hardwareUtils.ts#L176

```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'

```

**Comment by Kedryn** [comment]
It's not consistent. For example, right now i have a scaling from 2016p (2840x2076) to 1080p of an HEVC  file.

```2023-09-27T21:16:04.691Z dhk3yRWa4:Node[smo105test]:Worker[hot-hogget]:{"cliArgs":["-y","-i","//172.16.0.190/Storage/media/movies_transcoding/La bambola assassina 3 (1991) [tmdb-11187]/La bambola assassina 3 (1991) [tmdb-11187][WEBDL-2160p][HDR10][EAC3 2.0][x265].mkv","-map","0:0","-c:0","libx265","-crf","21","-preset","slow","-vf","scale=1920:-2","-pix_fmt:v:0","p010le","-profile:v:0","main10","-map","0:1","-c:1","copy","-map","0:2","-c:2","copy","-map","0:3","-c:3","copy","-map","0:4","-c:4","copy","-map","0:5","-c:5","copy","//172.16.0.190/transcoding_temp/movies_transcoding/tdarr-workDir-node-oQedsMnBV-worker-hot-hogget-ts-1695842158758/1695842161341/La bambola assassina 3 (1991) [tmdb-11187][WEBDL-2160p][HDR10][EAC3 2.0][x265].mkv"],"outputFilePath":"//172.16.0.190/transcoding_temp/movies_transcoding/tdarr-workDir-node-oQedsMnBV-worker-hot-hogget-ts-1695842158758/1695842161341/La bambola assassina 3 (1991) [tmdb-11187][WEBDL-2160p][HDR10][EAC3 2.0][x265].mkv"}```

It's running on a I7 10th gen, configured as QSV,  since 13h (and is at 56%), but there is no sign of either decoding or encoding via hardware. The same node, usually encode via QSV without problems, using my plugins thats check if the node is QSV capable then add the relatitve parametrs. Maybe it's not the transcoding, but the scaling flow plugin, that is not using or stripping the hardware parameters?
This is what the node is doing. First line with flow plugins, second line with my own plugin

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/28524a01-9d05-4a86-81ab-92e294a2c809)

**Comment by HaveAGitGat** [comment]
Post a job report if possible as would need to see the details. Also did you try running the command I mentioned?

```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'
```

Run that and see if it exits successfully.

**Comment by madkatz01** [comment]
I am having a similar issue - the flow transcode plugin will not use hardware encoding (works fine with classic plugins). 

Node is on Windows. Set to GPU encode with nvenc specified. 

Flow is set for hardware transcode/decode. But the ffmpeg command still uses xlib265 and somehow Tdarr starts the "GPU transcode" with CPU use only. Confused on how that even goes through since I have the node set to only nvenc. 

I think the plugin would be more helpful if we could force the hardware selection type to ffmpeg? Since we know this works from the classic plugins.

**Comment by HaveAGitGat** [comment]
The flows system uses a slightly different system to the old system so the hardware select for nvenc that you mentioned won't do anything in the flow as I'm trying to move away from workers requeueing items for other workers to do .

If you could please try the command I mentioned above then that would help as it's what's used to test if qsv hardware encoding is available and it's working fine for myself and some others I've checked with so will need to update the command so it works in your scenario. It's just a simple docker command.

```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'
```

**Comment by HaveAGitGat** [comment]
I've added an option so you can select the hardwareType:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/8e1cacb4-fe7d-4640-a73a-d14531a6cd05)

But yeah ideally would like to find out why the auto option isn't working for you.

**Comment by Kedryn** [comment]
[OIwItn0JVrQ-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12783234/OIwItn0JVrQ-log.txt)

Again, this was an encoding only for scaling, and was done as CPU on a QSV node
![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/304fb20c-9fba-409b-a215-bfa2f49446a2)

BTW, is this the right way to change resolution? A set encoder then a set video resolution?

**Comment by HaveAGitGat** [comment]
Can see in the logs that you haven’t selected/saved the qsv option. It’s still showing auto:

loris]:Loaded plugin inputs: {
2023-10-02T15:27:38.827Z   "outputCodec": "hevc",
2023-10-02T15:27:38.827Z   "ffmpegPreset": "slow",
2023-10-02T15:27:38.827Z   "ffmpegQuality": "23",
2023-10-02T15:27:38.827Z   "hardwareEncoding": "true",
2023-10-02T15:27:38.827Z   "hardwareType": "auto",
2023-10-02T15:27:38.827Z   "hardwareDecoding": "true",
2023-10-02T15:27:38.827Z   "forceEncoding": "true"
2023-10-02T15:27:38.827Z }

> if i choose QSV and the node does not have it, it wont go to that one, or it will use CPU ?

No it will only auto detect if you choose auto.


If you specify a hardware type it will try to force use that hardware encoder which will fail if the hardware is not available.

**Comment by Kedryn** [comment]
> The flows system uses a slightly different system to the old system so the hardware select for nvenc that you mentioned won't do anything in the flow as I'm trying to move away from workers requeueing items for other workers to do .
> 
> If you could please try the command I mentioned above then that would help as it's what's used to test if qsv hardware encoding is available and it's working fine for myself and some others I've checked with so will need to update the command so it works in your scenario. It's just a simple docker command.
> 
> ```
> docker run \
>     --device=/dev/dri:/dev/dri \
>     ghcr.io/haveagitgat/tdarr_node:latest \
>     /bin/bash -e \
>     -c 'ffmpeg \
>             -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
>             -c:v:0 hevc_qsv \
>             -f null /dev/null'
> ```

I'm running Tdar on Unraid with windows node,
not sure on where to run that command

**Comment by Kedryn** [comment]
> Can see in the logs that you haven’t selected/saved the qsv option. It’s still showing auto:
> 
> loris]:Loaded plugin inputs: { 2023-10-02T15:27:38.827Z "outputCodec": "hevc", 2023-10-02T15:27:38.827Z "ffmpegPreset": "slow", 2023-10-02T15:27:38.827Z "ffmpegQuality": "23", 2023-10-02T15:27:38.827Z "hardwareEncoding": "true", 2023-10-02T15:27:38.827Z "hardwareType": "auto", 2023-10-02T15:27:38.827Z "hardwareDecoding": "true", 2023-10-02T15:27:38.827Z "forceEncoding": "true" 2023-10-02T15:27:38.827Z }
> 
> > if i choose QSV and the node does not have it, it wont go to that one, or it will use CPU ?
> 
> No it will only auto detect if you choose auto.
> 
> If you specify a hardware type it will try to force use that hardware encoder which will fail if the hardware is not available.

yep, haven't modified my flow yet

i'll do it this evening

**Comment by Kedryn** [comment]
[3x98Hql0k9-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12791338/3x98Hql0k9-log.txt)
This is a node with a  Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz,  Model 142 Stepping 12
As you can see, the check checkNodeHardwareEncoder for hevc_qsv returned false

**Comment by Kedryn** [comment]
also this
![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/6843055b-715c-49e4-8bb4-98516e39fee0)
[UOea-Au1p-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12796685/UOea-Au1p-log.txt)

This time was another node, QSV enabled, but it was not detected again

**Comment by HaveAGitGat** [comment]
@Kedryn in both those logs you still have `"hardwareEncoding": "false"` in the `Set Video Encoder` plugin. You'd need to enable it.

I've updated the detection logging so you can see what command is being run to detect if the hardware encoder is enabled:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/492

e.g. the qsv command is:

`ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -f null /dev/null`

which is failing on your machine. So try running the command in cmd to see if you get the same result.

**Comment by Kedryn** [comment]
> @Kedryn in both those logs you still have `"hardwareEncoding": "false"` in the `Set Video Encoder` plugin. You'd need to enable it.
> 
> I've updated the detection logging so you can see what command is being run to detect if the hardware encoder is enabled:
> 
> [HaveAGitGat/Tdarr_Plugins#492](https://github.com/HaveAGitGat/Tdarr_Plugins/pull/492)
> 
> e.g. the qsv command is:
> 
> `ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -f null /dev/null`
> 
> which is failing on your machine. So try running the command in cmd to see if you get the same result.


You see that is set to auto because this is my flow:

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/331be350-8152-470c-a7a0-2c650d270857)

The problem is that the "Check Node QSV" does not work like "Auto" in the Encoder.
If the QSV is detected, it goes left where the hardware encoding is enabled and QSV is selected.
But it is not detected, so it goes to the right and use "Auto" for CPU (there is no CPU option, so i used AUTO)
Yet, the CPU has QSV.

This is the left encoder (QSV):

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/c181de17-fb31-444d-9a16-cdbf9bb6b1c6)

This is the right one (CPU):

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/bc2c4453-8547-41d6-b902-07e05da7ca70)

**Comment by HaveAGitGat** [comment]
If you click 'Update plugins' on the plugins tab and run it again then check the logs you can see more info on how it's trying to detect the hardware encoder.

And ok yeah that's right. `auto` won't do anything in that case as it depends on `hardwareEncoding` being `true` so that's fine. Both the `Check Node Hardware Encoder` and `Set Video Encoder` are both running the same code to check what's available so will show up in logs for both.

**Comment by Kedryn** [comment]
[zzHuL2Ae2-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12809075/zzHuL2Ae2-log.txt)

**Comment by HaveAGitGat** [comment]
Hi thanks, you can see the command here which is being run and is failing:

```
C:/Users/MC Retail/Desktop/Tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -f null /dev/null
Encoder hevc_qsv is disabled
```

I've verified this is working on an i7-9850H processor on Windows. What command do you normally use to run qsv transcodes? Also what specific processor model are you using? There are some 10th gen models which don't support qsv hevc transcoding.

**Comment by Kedryn** [comment]
> Hi thanks, you can see the command here which is being run and is failing:
> 
> ```
> C:/Users/MC Retail/Desktop/Tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -f null /dev/null
> Encoder hevc_qsv is disabled
> ```
> 
> I've verified this is working on an i7-9850H processor on Windows. What command do you normally use to run qsv transcodes? Also what specific processor model are you using? There are some 10th gen models which don't support qsv hevc transcoding.

i use 
-c:v hevc_qsv -load_plugin hevc_hw

for specific processor, i'll be back later, but remember that all my 3 pc with 10th and 11th gen Intel, works with qsv with my plugin. But there is no "detect" in it. I simply set QSV in the node, and the plugin adds relevant parameters in the ffmpeg command.

Anyway i'll try your test manually in those nodes to check the result.

**Comment by HaveAGitGat** [comment]
Ok thanks, seems 10th gen needs to have the `-load_plugin` argument.

Should be fixed here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/495

Reopen if needed.

**Comment by Kedryn** [comment]
Sorry for reopening this but everything seemed to work for days, until now:

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/4650021e-5d78-49a7-8095-c01e9ed7968a)

I went to that node and tried the command to check QSV (got it from the logs):

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/181f9ed1-c7ba-4ebe-9c78-c113a61addb1)

From what i can see, besides the 2 warnings, the command worked fine, but the logs for the plugin that checks hardware, repoted that it didn't detect QSV:

```2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:Checking for encoder hevc_qsv with command:
2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:C:/Users/MC Retail/Desktop/Tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg.exe -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 -c:v hevc_qsv -load_plugin hevc_hw -f null /dev/null
2023-10-09T14:59:06.153Z b0k2aBtyT:Node[smo105test]:Worker[brief-bug]:Encoder hevc_qsv is disabled```

**Comment by Kedryn** [comment]
I can't reopen this issue, going to open a new one
