### ISSUE TITLE
Review system is missing a "skip"

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#862]
I think that, in the "Review" system, we could use a "Skip" option to exit the flow. For exampe, i use the "review" plugin when the transcoded file is bigger than the original. Review, as is now, only give me the option to keep going (and maybe replacin the original file) or requeue.

**Comment by cbrherms** [comment]
I am in the same situation here, and using review for the same reason also.  Just caught a file that was 4 times larger after transcode and now wondering what to do with it...

**Comment by HaveAGitGat** [comment]
I’ll add that in. In the mean time you can requeue and then skip.

**Comment by HaveAGitGat** [comment]
2.13.01 released
