### ISSUE TITLE
Flows: conditional node capability

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#864]
A Flow plugin that check node hardware support (QSV, CPU, etc.)

**Comment by HaveAGitGat** [comment]
Added here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/480

**Comment by HaveAGitGat** [comment]
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bcdbe8b4-64c1-466b-81dc-59f1df37e355)

CPU will always be available so no need to check that unless I'm missing something.
