### ISSUE TITLE
Flow: compare file size ratio

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#865]
Can the new plugin be modified with 3 exits (ok, bigger, smaller) instead of only 2 (ok, or outside range)?
So we can try transcoding with different parameters if it's bigger, and skip if it's lower (usually damaged)?

**Comment by HaveAGitGat** [comment]
If you're looking to see if a file is bigger, smaller or same then you need to use the `Compare File Size` flow plugin.

**Comment by Kedryn** [comment]
Yep, but i was thinking about "bigger than a %" and "smaller than a %" like the Tdarr_Plugin_a9he_New_file_size_check

**Comment by HaveAGitGat** [comment]
Added a new version of the plugin here which has 3 outputs:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/486

So you'll need to add the new version in the sidebar
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/529aba47-2502-4a74-a145-954ff96a9dcc)

**Comment by smailpouri** [comment]
I'm unsure where the "Check File Size Ratio" plugin should be placed in the flow. Should it be placed before or after the transcode process, or perhaps somewhere else? I'm just not clear on when this plugin should check the file. 

Here's my current flow for reference:

```
> Input File 
> H264?
   > [ Y ] > Check Resolution > Handbrake Transcode > Replace Original File
   > [ N ] > Check Resolution > Check Overall Bitrate > Handbrake Transcode by Resolution Choice > Replace Original File
```
