### ISSUE TITLE
FLOWS processing files within the injest over and over

### ISSUE THREAD

**Issue by Tyrael2713** [HaveAGitGat/Tdarr#866]
**Describe the bug**
my workflow leaves the original files untranscoded files within the ingest directory (for seeding) this results in them getting processed over and over

**To Reproduce**
1 make an ingest directory and have transcoded files moved to another directory (which leaves the original un-transcoded files in the ingest directory)

**Expected behavior**
if a file has been processed by the flow once it should not be reprocessed again

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/13772519/57bce2b8-ff7a-4b4d-8f5e-cf57233fc464)
![image](https://github.com/HaveAGitGat/Tdarr/assets/13772519/0c676ef6-7510-4476-a739-79a6bd41731f)

**Please provide the following information:**
- Config files/Log files [config-logs.gz](https://github.com/HaveAGitGat/Tdarr/files/12777957/config-logs.gz)

 - OS: unraid
 - Browser chrome
 - Version 2.12.01

**Additional context**
the goal is to leave an untranscoded copy in the directory it was pulled from while getting a transcoded copy moved to a new directory

**Comment by HaveAGitGat** [comment]
Hi, thanks. When using the plugin stack system with an output file what happens is the original file is added to a collection in the database to prevent it being re-processed.

So possible solution in this case is 1 plugin to check file has been processed and another plugin to add file to processed database collection at end of flow?

**Comment by HaveAGitGat** [comment]
Other solution is to use to the “set original file” after your last plugin. Then at the end, the original file will remain in the database and will go into the transcode success/not required table

**Comment by Tyrael2713** [comment]
thanks the set original file solution is working just fine and is a good solution thanks
closing ticket
