### ISSUE TITLE
File not considered broken on health check

### ISSUE THREAD

**Issue by mitzsch** [HaveAGitGat/Tdarr#867]
**Describe the bug**
I have an hevc encoded file that I know of that is broken, but the health check operation considers it as "healthy". The logs also show the broken state => `:[hevc @ 0x5581ae17a500] The cu_qp_delta 34 is outside the valid range [-32, 31].` but the file is still considered healthy. I have not found a way to change the "what is broken" algorithm. 

**To Reproduce**
Run a file that produces a cu_qp_delta error, it will be categorized as "healthy" even though the file is broken.

**Expected behavior**
Consider cu_qp_delta errors as broken.

**Screenshots**
Error message =>
![image](https://github.com/HaveAGitGat/Tdarr/assets/43502191/cf926d8c-9862-49b6-af18-eae3a9617455)

health check => 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43502191/b3562059-b50a-4cff-a9ad-cc3de9c27b54)

**Please provide the following information:**

 - OS: [Ubuntu LTS 22.04 server]
 - Browser [Chrome]
 - Version [2.12.01]

Logs are not necessary I guess...

Thanks!

**Comment by HaveAGitGat** [comment]
Updated for next version ty
