### ISSUE TITLE
Some newly-added files not detected automatically or through manual scan

### ISSUE THREAD

**Issue by dimaTrinh** [HaveAGitGat/Tdarr#869]
**Describe the bug**
Some, but not all, newly-added files just don't get detected through a manual scan. I do not have Folder Watch set up since my storage is in a NAS, and my Tdarr node is running in a docker on a different server.

**To Reproduce**
Trigger Scan (Find New) or Scan (Fresh)

**Expected behavior**
Expect the scanner to pick up all files in the folder

**Screenshots**
Files in my folder: 
<img width="592" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/43079118/d160aec4-7bd9-4846-9a76-2c03762cdc3c">
Files that got picked up and transcoded:
<img width="1701" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/43079118/b5fc7c2c-28ae-4c51-b56d-2ce85db7fa4b">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Tdarr Node Config:
```
{
  "nodeName": "BEST_NODE_EVER",
  "serverIP": "[IP]",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": ""
}
```
Tdarr Server Config: 
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "[IP]",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""
}
```
- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12807392/Server-log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
No errors

 - OS: [e.g. Linux] 
 Linux (Debian 11)
 Brave
 - Version [e.g. 2.00.00]
2.13.01

**Additional context**

**Comment by HaveAGitGat** [comment]
Hi, try enable verbose logs on the logs tab then rerun the scan. Then post the server log if needed thanks

**Comment by HaveAGitGat** [comment]
If using a network drive then can disable this to use disk polling instead of file system events:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/aac98358-d571-4257-9b5a-6e4bc5d9e96b)

Perhaps before you accidentally changed the scanner container settings or something like that. Feel free to reopen if you have the problem again thanks.

**Comment by dimaTrinh** [comment]
> If using a network drive then can disable this to use disk polling instead of file system events:
> 
> ![image](https://user-images.githubusercontent.com/43864057/272774713-aac98358-d571-4257-9b5a-6e4bc5d9e96b.png)
> 
> Perhaps before you accidentally changed the scanner container settings or something like that. Feel free to reopen if you have the problem again thanks.

Disk polling works! Thank you for the help
