### ISSUE TITLE
3rd GPU not choosen even on heavy load on GPU0 and 1

### ISSUE THREAD

**Issue by magickarle** [HaveAGitGat/Tdarr#870]
**Describe the bug**
Using Tdarr_Plugin_MC93_Migz1FFMPEG, the GPU assignment should be spread over all GPU based on least GPU utilization.
GPU 0 and 1 gets assigned task but not GPU 2

**To Reproduce**
install 3 GPU.
use plugin 

**Expected behavior**
I would have expected to have all tasks spread evenly on 3 gpus

**Screenshots**
nvidia-smi
Fri Oct  6 11:30:55 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070        On  | 00000000:00:10.0 Off |                  N/A |
| 31%   54C    P2              45W / 200W |   6410MiB / 12282MiB |     35%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Quadro RTX 4000                On  | 00000000:00:1B.0 Off |                  N/A |
| 35%   63C    P0              45W / 125W |   4197MiB /  8192MiB |     22%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Quadro RTX 4000                On  | 00000000:00:1C.0 Off |                  N/A |
| 30%   50C    P8              16W / 125W |      3MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      5475      C   tdarr-ffmpeg                                740MiB |
|    0   N/A  N/A      5702      C   tdarr-ffmpeg                                740MiB |
|    0   N/A  N/A      5907      C   tdarr-ffmpeg                                740MiB |
|    0   N/A  N/A      6065      C   tdarr-ffmpeg                                740MiB |
|    0   N/A  N/A      6238      C   tdarr-ffmpeg                                740MiB |
|    0   N/A  N/A      6371      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      6505      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      6654      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      6815      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7070      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7216      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7360      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7514      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7691      C   tdarr-ffmpeg                                264MiB |
|    0   N/A  N/A      7863      C   tdarr-ffmpeg                                264MiB |
|    1   N/A  N/A      6371      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      6505      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      6654      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      6815      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7070      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7216      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7360      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7514      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7691      C   tdarr-ffmpeg                                418MiB |
|    1   N/A  N/A      7863      C   tdarr-ffmpeg                                418MiB |
+---------------------------------------------------------------------------------------+

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
root@d1fd8232c5a5:/# cat /app/configs/Tdarr_Node_Config.json
{
  "nodeName": "MyInternalNode",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": ""
}root@d1fd8232c5a5:/# cat /app/configs/Tdarr_Server_Config.json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
I don't have any logs showing errors on GPU 2
-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
no failed item

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]
image: ghcr.io/haveagitgat/tdarr:latest
tdarr ver 2.13.01

**Comment by magickarle** [comment]
I've created a second internal node (part of the same server as the tdarr server) and assigned GPU0.
I assigned GPU1 to the first internal node.
This way i can control them independently.

But i though the filter would have done it on its own...
Let me know if you need logs or something else.

**Comment by HaveAGitGat** [comment]
Hi you can check this plugin here: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_MC93_Migz1FFMPEG.js

It's not designed to spread over multiple GPUs. Using this flow plugin should do this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/818b628e-e059-476c-bccf-11f4b66a0a60)
