### ISSUE TITLE
Very low fps encoding

### ISSUE THREAD

**Issue by magickarle** [HaveAGitGat/Tdarr#871]
**Describe the bug**
I have RTX 4070, 2x quatro 4000.
They are PCI pass through proxmox to a VM having docker.
One thing I find weird: the fps stays the same either I set 1 or 25 GPU for transcoding. I see the task piling up in the nvidia-smi.
Tdarr server and node is hosted on it.
I have 2 other nodes not affected by this (ubuntu on RTX 3080 and laptop with RTX 3050 Ti.

**To Reproduce**
Not sure... I guess have my kind of setup?

**Expected behavior**
I would have expected in the 300-400 on each GPU.

**Screenshots**
<img width="1148" alt="tdarr01" src="https://github.com/HaveAGitGat/Tdarr/assets/18073624/3e7d8fb0-a3bd-499a-9ba2-ba53e5a99196">
<img width="548" alt="tdarr01_nvidia" src="https://github.com/HaveAGitGat/Tdarr/assets/18073624/73e9a425-9cdf-40c6-a884-10f06df86712">
<img width="639" alt="tdarr02_nvidia" src="https://github.com/HaveAGitGat/Tdarr/assets/18073624/2dbc45c4-cb55-4c59-a3f4-bbe8b802a838">
<img width="1118" alt="tdarr02" src="https://github.com/HaveAGitGat/Tdarr/assets/18073624/826d7cd8-e5a0-42d5-97d9-84bce84813cc">

**Please provide the following information:**
root@d1fd8232c5a5:/# cat /app/configs/Tdarr_Node_Config.json
{
"nodeName": "MyInternalNode",
"serverIP": "0.0.0.0",
"serverPort": "8266",
"handbrakePath": "",
"ffmpegPath": "",
"mkvpropeditPath": "",
"pathTranslators": [
{
"server": "",
"node": ""
}
],
"logLevel": "INFO",
"priority": -1,
"cronPluginUpdate": ""
}root@d1fd8232c5a5:/# cat /app/configs/Tdarr_Server_Config.json
{
"serverPort": "8266",
"webUIPort": "8265",
"serverIP": "0.0.0.0",
"handbrakePath": "",
"ffmpegPath": "",
"logLevel": "INFO",
"mkvpropeditPath": "",
"ccextractorPath": "",
"openBrowser": true,
"cronPluginUpdate": ""

image: ghcr.io/haveagitgat/tdarr:latest
tdarr ver 2.13.01

**Comment by HaveAGitGat** [comment]
Hi not sure I understand your question correctly but he number of workers does not increase the number of fps. Depending on your settings a single GPU worker will use 50-100% of the GPU so launching more workers won't increase fps if a single worker is already using 100%. In that case when you launch more GPU workers the GPU processing will be split across the workers so the overall fps will stay the same. The most effective way to use multiple GPUs is to create a separate Tdarr Node container for each GPU or you can try using this flow plugin which attempts to auto detect lowest used GPU: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9b6caafd-1547-44c6-a8bc-f10589a40b3c)

**Comment by magickarle** [comment]
Well my question is why am I getting low fps with those cards.
I'm not throttling on temperature, network usage is low, storage usage low.

**Comment by HaveAGitGat** [comment]
For some reason the encoder usage is only around 28%. For me it's using 100% with 2 workers or 80% with one worker:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/bd028b21-3d6f-4869-9cf7-e6955b1224da)

So this maybe seems like a driver issue or some other external issue from the Tdarr container?

Do you have any sort of power saving feature or something like that running?

**Comment by magickarle** [comment]
Not that I'm aware.
It's a headless server running on cli.

**Comment by magickarle** [comment]
Oh and I've tested outside of docker with jellyfin's ffmeg ver6. Same.thing. Usage is between 15-30%

So I guess my issue is not with tdarr.
But if someone has an RTX 4070 or quatro 4000, can you tell me transcoding from h264 to h265, doest it utilize at 100% ?
