### ISSUE TITLE
Date column

### ISSUE THREAD

**Issue by bgktmxg** [HaveAGitGat/Tdarr#874]
**Is your feature request related to a problem? Please describe.**
I'm often scrolling through my 'success' column just checking over everything and making sure its working okay. Its difficult to see at a glance what day each item was transcoded

**Describe the solution you'd like**
I would like a date column added to the headings.

**Additional context**
Wouldn't necessarily need to have it's own column. The date could be added to the right hand side of the timestamp.

![image](https://github.com/HaveAGitGat/Tdarr/assets/51685078/069afc1c-bc4b-4141-ba4a-c7d51f96a8e2)

**Comment by HaveAGitGat** [comment]
Added for next version
