### ISSUE TITLE
Nodes should check for write permission when starting

### ISSUE THREAD

**Issue by cemtaylor** [HaveAGitGat/Tdarr#876]
**Is your feature request related to a problem? Please describe.**
I've had a few nodes that had incorrect credentials set up that allowed only read access to the shared media locations, however when running jobs the node will always fail when it attempts to replace the original file as it does not have write access

**Describe the solution you'd like**
On startup, nodes should check that they have write permission in any directory (perhaps including subdirectories) in their config - this could be optional to avoid breaking existing instances, or simply be noted as warnings instead of outright errors in the log.

**Describe alternatives you've considered**
Alternative would be update the move/replace plugins to indicate that there are insufficient permissions when the move/replace fails. This is undesirable however as it would allow the node to keep running and failing jobs unnecessarily.

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
The nodes already do some access checks on startup:

```
[2023-10-11T01:57:30.545] [INFO] Tdarr_Node - Path translator: Checking Node path: Z:/
[2023-10-11T01:57:30.776] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: Z:/
```

I don't think it's really practical for nodes to go through every folder and subfolder on their shared locations to check write permission as there could be thousands or even millions of directories potentially with different permissions.

Could potentially add an option on the input file flow plugin which checks if the node can access/write to the original file directory:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/input/inputFile/1.0.0/index.ts

**Comment by cemtaylor** [comment]
Yeah that seems reasonable, my only concern would be that there's nothing to stop the node from continuing to take transcodes and immediately fail them, filling up the failed transcode log

**Comment by HaveAGitGat** [comment]
Added these changes to the input file flow plow plugin:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/f63c09d1-745a-4429-aaf3-1746eeb3d3c9)
