### ISSUE TITLE
Flows Beta - No new IDs generated when duplicating a flow

### ISSUE THREAD

**Issue by 4WaYDp** [HaveAGitGat/Tdarr#877]
**Describe the bug**
When duplicating a Flow the ID of each element gets copied. These should be new unique IDs else you get strange behavior when using Go To Flow.

**To Reproduce**
Duplicate a flow. When you compare the export of the original and the duplicated flow you see that each element has the same ID, these should be regenerated. 

**Expected behavior**
Each element in every flow should have a unique ID, I guess. With duplicate IDs the Go To Flow ends up going to the wrong Flow.

**Please provide the following information:**
I'm using the latest docker beta.

**Additional context**
I know it's a beta release; just trying to help.

**Comment by HaveAGitGat** [comment]
Not sure I understand. The `Go To Flow` plugin goes to a specific flow based on its flow ID. You can see the ID of the flow in the url bar when browsing each flow. When duplicating a flow, a new flow ID is given.

The IDs of each flow plugin are copied when duplicating a flow but these are unrelated to the `Go To Flow` plugin.

**Comment by HaveAGitGat** [comment]
Just as a check I used this flow:

```
{
  "name": "Basic HEVC Video Flow 2",
  "description": "Basic HEVC Video Flow 2",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "pE6rU7gkW",
      "position": {
        "x": 620.1622577616137,
        "y": 270.86028612470574
      }
    },
    {
      "name": "Start",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "4Swd6qzvc",
      "position": {
        "x": 474.222948401615,
        "y": 430.64086141518646
      }
    },
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "450g167D8",
      "position": {
        "x": 478.2585019517992,
        "y": 608.4361089500504
      }
    },
    {
      "name": "Set Video Encoder",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandSetVideoEncoder",
      "version": "1.0.0",
      "id": "O5ORgCt42",
      "position": {
        "x": 475.1669476010695,
        "y": 521.1005455391422
      }
    },
    {
      "name": "Go To Flow",
      "sourceRepo": "Community",
      "pluginName": "goToFlow",
      "version": "1.0.0",
      "id": "yx7EfVMoF",
      "position": {
        "x": 724.8839816243687,
        "y": 755.4263549504572
      },
      "inputsDB": {
        "flowId": "Smb70pElO"
      }
    }
  ],
  "flowEdges": [
    {
      "source": "4Swd6qzvc",
      "sourceHandle": "1",
      "target": "O5ORgCt42",
      "targetHandle": null,
      "id": "kOY0iUXMG"
    },
    {
      "source": "pE6rU7gkW",
      "sourceHandle": "1",
      "target": "4Swd6qzvc",
      "targetHandle": null,
      "id": "O76tiPVJ3"
    },
    {
      "source": "450g167D8",
      "sourceHandle": "1",
      "target": "yx7EfVMoF",
      "targetHandle": null,
      "id": "IQScdHYoH"
    },
    {
      "source": "O5ORgCt42",
      "sourceHandle": "1",
      "target": "450g167D8",
      "targetHandle": null,
      "id": "vFEFeeP9u"
    }
  ]
}
```

This goes to this flow:

```
{
  "name": "Flow 2",
  "description": "Flow 2",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "FXqpmonEs",
      "position": {
        "x": 525.59375,
        "y": 197
      }
    },
    {
      "name": "Send Web Request 123",
      "sourceRepo": "Community",
      "pluginName": "webRequest",
      "version": "1.0.0",
      "id": "wgyaK87om",
      "position": {
        "x": 526.640625,
        "y": 310.5
      },
      "inputsDB": {
        "requestUrl": "http://example.com"
      }
    },
    {
      "name": "Require Review",
      "sourceRepo": "Community",
      "pluginName": "requireReview",
      "version": "1.0.0",
      "id": "XAmiv0XKo",
      "position": {
        "x": 526.9737373664635,
        "y": 432.9000159413323
      }
    }
  ],
  "flowEdges": [
    {
      "source": "FXqpmonEs",
      "sourceHandle": "1",
      "target": "wgyaK87om",
      "targetHandle": null,
      "id": "Fc3LONnDf"
    },
    {
      "source": "wgyaK87om",
      "sourceHandle": "1",
      "target": "XAmiv0XKo",
      "targetHandle": null,
      "id": "GV15pvklv"
    }
  ]
}
```

I then duplicated the second flow so have this:
```
{
  "name": "Flow 2 (duplicate)",
  "description": "Flow 2 (duplicate)",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "FXqpmonEs",
      "position": {
        "x": 525.59375,
        "y": 197
      }
    },
    {
      "name": "Send Web Request 456",
      "sourceRepo": "Community",
      "pluginName": "webRequest",
      "version": "1.0.0",
      "id": "wgyaK87om",
      "position": {
        "x": 526.640625,
        "y": 310.5
      },
      "inputsDB": {
        "requestUrl": "http://example.com"
      }
    },
    {
      "name": "Require Review",
      "sourceRepo": "Community",
      "pluginName": "requireReview",
      "version": "1.0.0",
      "id": "XAmiv0XKo",
      "position": {
        "x": 526.5536752015317,
        "y": 391.22160641649543
      }
    }
  ],
  "flowEdges": [
    {
      "source": "FXqpmonEs",
      "sourceHandle": "1",
      "target": "wgyaK87om",
      "targetHandle": null,
      "id": "Fc3LONnDf"
    },
    {
      "source": "wgyaK87om",
      "sourceHandle": "1",
      "target": "XAmiv0XKo",
      "targetHandle": null,
      "id": "GV15pvklv"
    }
  ]
}
```

And can see it still goes to the 123 flow:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/843d6338-8547-4123-a524-93797c766880)

**Comment by 4WaYDp** [comment]
You are right, the Go to Flow redirected to the right (duplicated) Flow but the plugins of the original Flow were executed.
I tried exporting/importing the duplicated JSON but got the same behavior. When I manually changed all IDs within the duplicated JSON, just changing one character, the duplicated Flow worked correctly.

**Comment by 4WaYDp** [comment]
To be clear: I duplicated a flow and in the duplicate I changed some plugin variables and names. Executing the new flow tuned out to execute the plugins from the original flow. 

So yeah, my OP was incorrect in assuming this was a Go to Flow problem. This is a problem duplicating a flow.

**Comment by HaveAGitGat** [comment]
Hi sorry I still don't know what you mean. I created this flow:
```
{
  "name": "Basic HEVC Video Flow 2",
  "description": "Basic HEVC Video Flow 2",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "pE6rU7gkW",
      "position": {
        "x": 620.1622577616137,
        "y": 270.86028612470574
      }
    },
    {
      "name": "Start",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandStart",
      "version": "1.0.0",
      "id": "4Swd6qzvc",
      "position": {
        "x": 480.31680234468786,
        "y": 416.71205240244853
      }
    },
    {
      "name": "Execute",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandExecute",
      "version": "1.0.0",
      "id": "450g167D8",
      "position": {
        "x": 478.2585019517992,
        "y": 608.4361089500504
      }
    },
    {
      "name": "Set Video Encoder",
      "sourceRepo": "Community",
      "pluginName": "ffmpegCommandSetVideoEncoder",
      "version": "1.0.0",
      "id": "O5ORgCt42",
      "position": {
        "x": 479.5197004175501,
        "y": 517.6183432859577
      }
    },
    {
      "name": "Go To Flow",
      "sourceRepo": "Community",
      "pluginName": "goToFlow",
      "version": "1.0.0",
      "id": "CeFTG7d5s",
      "position": {
        "x": 664.2723224245976,
        "y": 742.607119110093
      },
      "inputsDB": {
        "flowId": "0HiKnztsv"
      }
    }
  ],
  "flowEdges": [
    {
      "source": "4Swd6qzvc",
      "sourceHandle": "1",
      "target": "O5ORgCt42",
      "targetHandle": null,
      "id": "kOY0iUXMG"
    },
    {
      "source": "pE6rU7gkW",
      "sourceHandle": "1",
      "target": "4Swd6qzvc",
      "targetHandle": null,
      "id": "O76tiPVJ3"
    },
    {
      "source": "O5ORgCt42",
      "sourceHandle": "1",
      "target": "450g167D8",
      "targetHandle": null,
      "id": "vFEFeeP9u"
    },
    {
      "source": "450g167D8",
      "sourceHandle": "1",
      "target": "CeFTG7d5s",
      "targetHandle": null,
      "id": "NRStfffk1"
    }
  ]
}
```

I then made it go to this flow:
```
{
  "name": "Flow 2",
  "description": "Flow 2",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "FXqpmonEs",
      "position": {
        "x": 525.59375,
        "y": 197
      }
    },
    {
      "name": "Send Web Request 123",
      "sourceRepo": "Community",
      "pluginName": "webRequest",
      "version": "1.0.0",
      "id": "wgyaK87om",
      "position": {
        "x": 526.640625,
        "y": 310.5
      },
      "inputsDB": {
        "requestUrl": "http://example.com"
      }
    },
    {
      "name": "Require Review",
      "sourceRepo": "Community",
      "pluginName": "requireReview",
      "version": "1.0.0",
      "id": "XAmiv0XKo",
      "position": {
        "x": 526.9737373664635,
        "y": 432.9000159413323
      }
    }
  ],
  "flowEdges": [
    {
      "source": "FXqpmonEs",
      "sourceHandle": "1",
      "target": "wgyaK87om",
      "targetHandle": null,
      "id": "Fc3LONnDf"
    },
    {
      "source": "wgyaK87om",
      "sourceHandle": "1",
      "target": "XAmiv0XKo",
      "targetHandle": null,
      "id": "GV15pvklv"
    }
  ]
}
```

I then duplicated the 2nd flow:


```
{
  "name": "Flow 2 (duplicate)",
  "description": "Flow 2 (duplicate)",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "FXqpmonEs",
      "position": {
        "x": 525.59375,
        "y": 197
      }
    },
    {
      "name": "Send Web Request 456",
      "sourceRepo": "Community",
      "pluginName": "webRequest",
      "version": "1.0.0",
      "id": "wgyaK87om",
      "position": {
        "x": 526.640625,
        "y": 310.5
      },
      "inputsDB": {
        "requestUrl": "http://example.com"
      }
    },
    {
      "name": "Require Review",
      "sourceRepo": "Community",
      "pluginName": "requireReview",
      "version": "1.0.0",
      "id": "XAmiv0XKo",
      "position": {
        "x": 526.9737373664635,
        "y": 432.9000159413323
      }
    }
  ],
  "flowEdges": [
    {
      "source": "FXqpmonEs",
      "sourceHandle": "1",
      "target": "wgyaK87om",
      "targetHandle": null,
      "id": "Fc3LONnDf"
    },
    {
      "source": "wgyaK87om",
      "sourceHandle": "1",
      "target": "XAmiv0XKo",
      "targetHandle": null,
      "id": "GV15pvklv"
    }
  ]
}
```

I then updated the first flow to go to the new flow:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0e48a42a-3dc1-4f0e-a2e4-378b2afc0edf)

I then run a worker and can see it runs the first flow and then the duplicated flow that I modified with `456`:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/e7c45d2e-461b-4700-9de6-10584b98ed50)

So all is working as expected from what I can see.

If you are able to provide the flows you created then I can try them out thanks.

**Comment by 4WaYDp** [comment]
So my first flow does stuff and selects a Go to Flow:
[Process_New_Files.json](https://github.com/HaveAGitGat/Tdarr/files/12885045/Process_New_Files.json)
Expected behavior is Go to Flow sonarr (duplicate), this works:
[sonarr_(duplicate).json](https://github.com/HaveAGitGat/Tdarr/files/12885051/sonarr_.duplicate.json)
But the plugins of sonarr (original) get executed:
[sonarr_(original).json](https://github.com/HaveAGitGat/Tdarr/files/12885059/sonarr_.original.json)

So as a test I renamed the plugin  `Transcode audio (192kbs)` to `Transcode audio (TEST)` in the duplicate. Expected behavior is that Transcode audio (TEST) should be executed but instead `Transcode audio (192kbs)` gets executed, same happens with the `Transcode video 720p` plugin (should be `Transcode video TEST`):

![Schermafdruk van 2023-10-12 18-19-07](https://github.com/HaveAGitGat/Tdarr/assets/66798820/24a93edf-2de4-4d85-b86d-f5a1a3893a39)

Have you also tested with Classic Plugins? There are a few (Classic-) plugins that I modified/wrote myself (the audio filters), could I have done something wrong/stupid with those?

**Comment by HaveAGitGat** [comment]
Yes that's expected behavior.  The flow ID and the name are `separate`. When you click an option on `Go To Flow` dropdown, it's selecting a specific flow ID to execute, not flow name. So renaming a flow like that is just changing the name, not the flow ID which is what the `Go To Flow` is using. You can see the specific flowIDs in your templates e.g. `"flowId": "v1PN4A6WL"`.

If it was done using name then it would be very inconvenient for many reasons including you'd need to update the `Go To Flow` plugins every time you make a slight adjustment to the flow name it's going to.

I've updated the dropdown for next version so it shows the flow ID as well as name.
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/d64d2f5a-d4df-4085-a2fc-b7230fe229bf)

**Comment by HaveAGitGat** [comment]
As I mentioned previously `You can see the ID of the flow in the url bar when browsing each flow.`. When you are renaming a flow, that ID it not changing. So the `Go To Flow` is still going to the same flow ID that was originally selected. Hope that helps.
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/76808d16-d873-45e7-b467-58512edb3acd)

**Comment by andrew-kennedy** [comment]
I'm having the same problem, I duplicated several flows and modified each duplicate slightly, and used go to flow between each to be able to set up a pipeline of said flows. However, whenever go to flow executes it only re-executes the first flow. All of the IDs of the various flows are correct on paper, and yet only the first flow executes. I've attached 3 of the flows in order, with their IDs so you can see the relationships:

[Remove data change container flow.json](https://github.com/HaveAGitGat/Tdarr/files/12902718/Remove.data.change.container.flow.json) with ID `ePvz2xdK6`
[Basic AV1 Flow.json](https://github.com/HaveAGitGat/Tdarr/files/12902719/Basic.AV1.Flow.json) with ID `MoqsBfAPJ`
[Lover Quality AV1 Flow.json](https://github.com/HaveAGitGat/Tdarr/files/12902720/Lover.Quality.AV1.Flow.json) with ID `rGR_J6Gld`.

**Comment by HaveAGitGat** [comment]
Do you have a job report for that? 
https://docs.tdarr.io/docs/other/job-reports

**Comment by HaveAGitGat** [comment]
Also to confirm the `Remove data change container flow` is the starting flow right?

**Comment by HaveAGitGat** [comment]
Ok was finally able to reproduce this.

Steps to reproduce:

- Create flow 1.
- Duplicate flow 1 creating flow 2.
- In flow 1, use 'Go To Flow' pointing to flow 2.
- Flow 1 will loop.

Will work on a solution.

**Comment by HaveAGitGat** [comment]
Fix is in these if you'd like to try:
```
tdarr_acc:dev_2.13.01_2023_10_18T07_36_43z
tdarr_node_acc:dev_2.13.01_2023_10_18T07_36_43z
```

**Comment by HaveAGitGat** [comment]
2.14.01 released.
