### ISSUE TITLE
Request: Prevent erroring nodes from filling queue with jobs in "Limbo" and halting all other nodes

### ISSUE THREAD

**Issue by AroundThisWorldAgain** [HaveAGitGat/Tdarr#878]
I have set up multiple computers to encode files from the same NAS, but have been running into the same thing every 1-2 days.

One of the computers will drop its network connection, for whatever reason, the network drive will disconnect, and as they're Macs it won't automatically reconnect when it gets its connection back a few moments later (trying to solve this, but off-topic).  The consequence is that within ≈15 minutes the Tdarr staging section is filled with jobs in "Limbo", and the other computers stop encoding as well.

Preferred would be to disconnect the node if it keeps erroring and/or to clean up jobs in "Limbo".

**Comment by HaveAGitGat** [comment]
Will move under here:
https://github.com/HaveAGitGat/Tdarr/issues/805

**Comment by AroundThisWorldAgain** [comment]
FWIW I don't think just requeuing limbo'd jobs as suggested by #805 would be sufficient in this case as the bad node would just keep requeuing them.
