### ISSUE TITLE
 radarr, sonarr notify not working

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#879]
**Describe the bug**
Since you added the radarr/sonarr notification only to the flow, i converted all my classic plugins to flow (via your tool).

SInce then im not able to produce ANY output, the classic plugins itself worked flawlessly.

Also the radarr/sonarr notify is not working. (error in logs)

I upload the flow here.

**it says user canceld it, i didnt cancel anything, i was just watching it**, also i watched the file grow in the output directory, (blablafile.tmp)

**To Reproduce**
Use my flow.

**Logs**
[data.txt](https://github.com/HaveAGitGat/Tdarr/files/12881903/data.txt)
[5e1koyRlU-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12881904/5e1koyRlU-log.txt)
[SuZ3Z2_qD8-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12881906/SuZ3Z2_qD8-log.txt)
[o7hXIRw9J-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12881908/o7hXIRw9J-log.txt)

**Expected behavior**
I expect it to work like the classic plugins.

**Please provide the following information:**

 - OS: [e.g. Linux]
Unraid Version: 6.12.4  Docker, latest

 - Browser Chrome latest

**Comment by supersnellehenk** [comment]
I can't find anything related to the flow version of the notifyRadarrOrSonarr plugin, I do notice that your flow has `http://Radarr:7878` while the classic plugin has `http://Radar:7878`.

Can't comment on the 'user cancelled worker'.

**Comment by CurlyFlow** [comment]
Ive got a new error:

25 2023-10-12T19:37:36.732Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:Refreshing Sonarr...

26 2023-10-12T19:37:36.733Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:[-error-]

27 2023-10-12T19:37:36.734Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:TypeError: Cannot read properties of undefined (reading 'series')

28 2023-10-12T19:37:36.735Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:"Cannot read properties of undefined (reading 'series')"

29 2023-10-12T19:37:36.736Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:"TypeError: Cannot read properties of undefined (reading 'series')\n at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:144:42\n at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:33:23)\n at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:14:53)\n at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:5:58)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

30 2023-10-12T19:37:36.738Z _zjKx8CmE:Node[MyInternalNode]:Worker[jovial-jay]:Flow has failed

I dont knwo if its possible but the standard port for sonarr is wrong, its not 7878 its 8989, just a minor thing, but would be good if it can be changed.

[_zjKx8CmE-log.txt]XXX

**Comment by supersnellehenk** [comment]
Yeah I believe Sonarr has changed its API response since some recent version.

The flow is used for both Radarr & Sonarr, it just provides the Radarr port as an example.

**Comment by supersnellehenk** [comment]
It's meant for separate Movies/TV Show flows, not in the same one. 

Yeah I'd have to recheck the code for the wrong API response, not sure why the file isn't passed to it. But HGG made the flow version, I didn't.

**Comment by supersnellehenk** [comment]
Ah that's what you mean. Not sure as I believe it just shows the default values.

**Comment by HaveAGitGat** [comment]
Please try this again, should be working now.

@supersnellehenk think the original plugin you posted has a bug in it:

` const seriesId = (await series.json()).data.series.id;`

should be

` const seriesId = (await series.json()).series.id;`

Fixed the flow plugin here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/509/files

**Comment by HaveAGitGat** [comment]
I'm not sure what you mean by `creates more folders per transcode`. If you're referring to the cache folders, then yes a temp folder is created for each plugin to prevent file conflicts between plugins.

**Comment by supersnellehenk** [comment]
@CurlyFlow what Radarr version are you on? I'm on `5.1.0.8172` and the API structure hasn't changed from what I know.

**Comment by supersnellehenk** [comment]
Most run Radarr/Sonarr on nightly instead of latest. But the API hasn't changed since I made the plugin like a year ago. https://radarr.video/docs/api/#/Parse/get_api_v3_parse

**Comment by lemystere** [comment]
Hello @HaveAGitGat I think the problem of @CurlyFlow is because the API request [/api/v3/parse](https://radarr.video/docs/api/#/Parse/get_api_v3_parse) is linked to the original file name BEFORE renaming it with the media managment of Radarr or anything else of course. This behaviour is different in Sonarr because the API request take the name after renaming it.  

I think the way to bypass this problem require to search for a correspondance with the request API [/api/v3/movie](https://radarr.video/docs/api/#/Movie/get_api_v3_movie).

**Comment by supersnellehenk** [comment]
The code is originally written by me, the parse endpoints function fine with the original filename for both Radarr and Sonarr. Using the new filename wouldn't work as they don't have any reference to said new file, which is what the plugin solves.

**Comment by supersnellehenk** [comment]
Haven't seen that myself, always used the filename shown in the files tab which works 100% of the time for me.

**Comment by supersnellehenk** [comment]
Idk what DE is, but could you try my way to manually verify the API at least works? That would narrow it down to either a Radarr issue or a plugin issue.

> A way to manually verify what Radarr returns would be running `curl -i -H "X-api-key: APIKEY" "http://192.168.1.1:7878/api/v3/parse?title=FILENAME"` where you'd encode the filename using [urlencoder.org](https://urlencoder.org)

**Comment by CurlyFlow** [comment]
root@Unraid-Server:~# curl -i -H "X-api-key: c457fead5f41479c8e2243f830ea3488" "http://radarr:radarr@192.168.0.110:7878/api/v3/parse?titleRed%20White%20and%20Royal%20Blue%20%5BDE%2BEN%5D%20WEBDL-1080p.mkv""
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Dec 2023 19:53:34 GMT
Server: Kestrel
Cache-Control: no-cache, no-store
Expires: -1
Pragma: no-cache
Transfer-Encoding: chunked
X-Application-Version: 5.1.3.8246

{
  "title": "Red White and Royal Blue [DE+EN] WEBDL-1080p.mkv",
  "customFormatScore": 0

[EAHABtURR8d-log.txt]XXX

**Comment by supersnellehenk** [comment]
That's the entire response you got? That would indicate Radarr couldn't match the filename you provided to an entry within Radarr, so the plugin isn't the issue in that case.

**Comment by CurlyFlow** [comment]
yes, u see mp4 vs mkv, but even if changed, nothing

<img width="748" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/43281991/90febcf1-9656-41d6-b052-f52ee19083a9">

root@Unraid-Server:~# curl -i -H "X-api-key: c457fead5f41479c8e2243f830ea3488" "http://radarr:radarr@192.168.0.110:7878/api/v3/parse?title=XXX.mp4"
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Dec 2023 20:01:57 GMT
Server: Kestrel
Cache-Control: no-cache, no-store
Expires: -1
Pragma: no-cache
Transfer-Encoding: chunked
X-Application-Version: 5.1.3.8246

{
  "title": "XXX.mp4",
  "customFormatScore": 0

**Comment by supersnellehenk** [comment]
Not sure why it isn't matching that filename to the movie, all I could see as a variable between my and your system is the version, as I'm running nightly with version 5.2.4.8323, but it has worked flawlessly before.

Do all failed files have something in common in their filenames? Like are they all multilanguage? I tried the exact same filename and movie in my Radarr instance and I got a proper response.

**Comment by CurlyFlow** [comment]
LOL now i know what you mean...

i have no idea what that means (just use original title????)


}root@Unraid-Server:~#curl -i -H "X-api-key: c457fead5f41479c8e2243f830ea3488" "http://radarr:radarr@192.168.0.110:7878/api/v3/parse?title=XXX.mkv"
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 07 Dec 2023 20:20:56 GMT
Server: Kestrel
Cache-Control: no-cache, no-store
Expires: -1
Pragma: no-cache
Transfer-Encoding: chunked
X-Application-Version: 5.1.3.8246

XXXX

**Comment by supersnellehenk** [comment]
All I could really recommend at this point is to try running trace logs, see if that shows anything. https://wiki.servarr.com/radarr/troubleshooting#logging-and-log-files But it's definitely a Radarr issue, not a plugin issue in my opinion.

**Comment by supersnellehenk** [comment]
That has been added last week, try updating the plugins and rerunning the file?

**Comment by CurlyFlow** [comment]
I clicked update plugins, sync plugins and then restartet docker.

I cant understand this all. Ive provided all logs, shouldnt someone understand what the problem is from them? like @HaveAGitGat 

It seems like this problem has something to do with the move error (where it tries to move file, fails and then after some more trys its working. (already posted servival times here)

i dont really want to provide all those "private" informations here forever.... 

[2023-11-30T07:14:35.572] [ERROR] Tdarr_Node - TypeError: Cannot read properties of undefined (reading 'movieFile')
    at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:127:42
    at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:33:23)
    at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:14:53)
    at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-11-30T07:22:31.066] [ERROR] Tdarr_Node - TypeError: Cannot read properties of undefined (reading 'movieFile')
    at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:127:42
    at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:33:23)
    at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:14:53)
    at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/tools/notifyRadarrOrSonarr/1.0.0/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-11-30T07:22:37.276] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, access 'XXXXmkv'
    at Object.accessSync (node:fs:262:3)
    at c (/app/Tdarr_Node/srcug/workers/worker1.js:1:38272)
    at /app/Tdarr_Node/srcug/workers/worker1.js:1:38611
    at k (/app/Tdarr_Node/srcug/workers/worker1.js:1:9669)
    at Object.next (/app/Tdarr_Node/srcug/workers/worker1.js:1:8711)
    at /app/Tdarr_Node/srcug/workers/worker1.js:1:8365
    at new Promise (<anonymous>)
    at __awaiter (/app/Tdarr_Node/srcug/workers/worker1.js:1:8086)
    at preProcessFile (/app/Tdarr_Node/srcug/workers/worker1.js:1:37855)
    at /app/Tdarr_Node/srcug/workers/worker1.js:1:47347 {
  errno: -2,
  syscall: 'access',
  code: 'ENOENT',
  path: 'XXXmkv'
}
[2023-11-30T07:57:14.691] [INFO] Tdarr_Node - Downloading plugins from server

root@Unraid-Server:XXX# ls
XXX.mp4

again its looking for mkv instead of mp4?

**Comment by supersnellehenk** [comment]
The ENOENT error isn't from the Notify plugin, but it could be part of the problem. Could you share the entire job report from that file?

**Comment by CurlyFlow** [comment]
Thats the latest... if someone wants, a dev can get access to my machine to look it up? Its unraid btw.

[pkRl_X4am-log.txt]XXX
