### ISSUE TITLE
Suggestion: Don't queue health checks when a library has them turned off

### ISSUE THREAD

**Issue by AroundThisWorldAgain** [HaveAGitGat/Tdarr#880]
I turned off health checks for all my libraries because the quick ones don't appear to do anything useful and the thorough ones consume faaaarrrrrrr too many resources IMO.   An extra 10-20% CPU time to catch the <1% of files that have errors isn't worth it.  The encoding process would catch those anyway at a significantly cheaper overall cost.

But even turned off, every file still gets queued twice.  Once when scanning and once when done encoding.  And I have to manually go click "skip all" all the time.

It'd be nice if it would just not enqueue health checks when neither checkbox is selected on the library settings.

**Comment by HaveAGitGat** [comment]
Next version already has this option

**Comment by AroundThisWorldAgain** [comment]
Where?  I'm on 2.13.01
