### ISSUE TITLE
Node error timeout of 10000ms exceeded happening daily

### ISSUE THREAD

**Issue by jackfalveyiv** [HaveAGitGat/Tdarr#881]
**Describe the bug**
I schedule Tdarr to run from 6AM - 12PM daily.  When I check the queue every morning, anything acquired after the scheduled transcoding time reads as 'Transcode Failed'.  Upon a reboot of the server and node dockers, then a requeue of the content, everything transcodes successfully.  I think there is some kind of connection issue. 

**To Reproduce**
Allowed Tdarr to run on my scheduled interval.  

**Expected behavior**
Tdarr to continue running on the schedule I have had set for years and successfully transcode the content.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: https://docs.tdarr.io/docs/other/job-reports
- I can get this tomorrow if the content fails again, but it has since been cleared. 

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
I can get this tomorrow if the content fails again, but it has since been cleared. 

 - OS: UNRAiD
 - Browser: Chrome & Safari
 - Version 2.13.01

**Additional context**

My mover runs at 3AM daily and all other content processing is paused between 2AM And 6AM daily.  

I did find the page linked below with similar issues, but I couldn't find a solution to my problem there:
https://github.com/HaveAGitGat/Tdarr/issues/726

Thanks in advance.

[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12894271/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12894272/Tdarr_Node_Log.txt)
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/12894277/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/12894278/Tdarr_Server_Config.json)

**Comment by jackfalveyiv** [comment]
I should also mention, this only started happening a few days ago without any warning.  I have not changed my workflow nor the network these docker images live on (custom docker network in my server).

**Comment by jackfalveyiv** [comment]
This may be a problem with docker autostart order and nothing to do with Tdarr.  On 6.12.4 I'm using the Folders plugin, and whenever these two particular dockers are added to a folder they only will boot in order of Node/Server instead of Server/Node.  Testing this evening to see if that's the solution and will update here.  It certainly would make sense.

**Comment by HaveAGitGat** [comment]
Ok thanks. I've also increased the timeout to 30 seconds for next version.

**Comment by HaveAGitGat** [comment]
Feel free to update if it's Tdarr related and I'll look further thanks.
