### ISSUE TITLE
Feature: pause on low disk space 

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#883]
**Is your feature request related to a problem? Please describe.**
I would like a plugin/flow which checks if there is xx GB enough space in the transcode (cache) directory. If not, pause, if there is continue. 

I dont need it to stop the transcode if its already doing it, it would be enough if i could set it as first step in the quene. So it would do maybe one more after space is full, which would be no problem. You understand what i mean?

**Describe the solution you'd like**
I had it happen that my filesystem is not able to copy the files fast enough so they would keep piling up until space is out, which results in all other transcodes to fail. (and create alot of pressure on file system also)

**Describe alternatives you've considered**
I changed transcodes to 2, but still it might happen.

**Comment by HaveAGitGat** [comment]
Will move under this thanks:
https://github.com/HaveAGitGat/Tdarr/issues/703
