### ISSUE TITLE
Replace original files FLOW moves files to cache instead of the array (unraid).. cache not enabled

### ISSUE THREAD

**Issue by raysv** [HaveAGitGat/Tdarr#885]
**Describe the bug**
When using Tdarr server in a unraid docker, and then running a windows node also inside same unraid server, but as a vm.  The shares are then shared with the node as smb shares. 

When the "Replace original file" flows then run, it actually creates the strucutre and the file on the cache drive, even though cache is disabled for the shares.  So manually have to move all transcoded files into the directories after.

This only happends when using FLOWS, running classic plugins it works as intended.

**To Reproduce**
Transcode a file on a windows node with the mapped up drives as smb shares. 

**Expected behavior**
To move the original file back into the share on the array, not on the cache drive. 

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

Node running windows vm inside unraid (newest version)
Server running unraid docker. 

**Additional context**

**Comment by HaveAGitGat** [comment]
Please post job report:
https://docs.tdarr.io/docs/other/job-reports

**Comment by raysv** [comment]
It does make sense since flows doing a atomic move, so if your temp dirctory is on the cache drive and you export the library useing /mnt/user with samba, unraid will create the files on the cache instead of the array when the file is moved.

Superschnellhenk did put me on the track for a workaround on discord, and that is exporting /mnt/user0/movies instead, then the flow manages to keep cache out of it :)

**Comment by raysv** [comment]
Not directly, but still an effect of something that has changed in tdarr vs old plugins vs flows that people have to be aware of :) I wasn't aware of this at the time of writting this bug post though, or how to fix it! So since it worked on old plugins, but not with flow, I then concluded with tdarr bug hehe :D

**Comment by frasderp** [comment]
I have the same issue. I have a very basic plugin stack (just rearranging streams, cleaning up subs etc), works ok as a plugin stack, but using Flows gives the error in the OP (errors while copying the final file, seems to copy the tmp file fine, but can't delete the original).

**Comment by HaveAGitGat** [comment]
I've just updated the flow pluging copy/move operations (4 different methods) so they're the same as what the plugin stack used.

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/542

Click `Update community plugins` on the plugins tab and  hopefully should now work.

**Comment by trumpet7347** [comment]
I finally got the chance to test the updated flow plugin, and unfortunatly I am reciving the same error I reported in #910, here is the job report and the server error.

Job Report: https://pastebin.com/edit/E1T3qDVP

Node Error:
```
Tdarr_Node - Error: Failed to move file

at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileMoveOrCopy.js:323:32

at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileMoveOrCopy.js:33:23)

at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileMoveOrCopy.js:14:53)

at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileMoveOrCopy.js:5:58)
```

**Comment by HaveAGitGat** [comment]
Thanks, these were the changes:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/fileMoveOrCopy.ts

So it now attempts 2 different ways of moving the file and if those don't work then it tries 2 different ways of copying so not sure how many more ways I should add. Seems your filesystem is incorrectly reporting something.

From the logs, it seems the second move operation completes successfully but then the size of the new file is reported as 0 bytes.

`:After move/copy, destination file of size 0 does not match cache file of size 584192328`.

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/fileMoveOrCopy.ts#L95

I could maybe add a delay so the file system has more time to update but that seems like an unusual solution.

When this happens are you able to check that the new `.tmp` file exists? For example `/media/tv/film.mkv.tmp`

**Comment by HaveAGitGat** [comment]
@trumpet7347 I've disabled mvdir in disable_mvdir branch. Can you go to the options tab in Tdarr and put this in Community Plugins Repository:

https://github.com/HaveAGitGat/Tdarr_Plugins/archive/disable_mvdir.zip

Then run plugin update on the plugins tab and reprocess your file and see if it works.

Then change it back to: 
https://github.com/HaveAGitGat/Tdarr_Plugins/archive/master.zip

**Comment by trumpet7347** [comment]
sorry, I have been out of town the last few days, I will give it a try this weekend when I have some time

**Comment by trumpet7347** [comment]
I updated the plugin repository to the link you have above, and there was no error on the file transfer, but it looks like the node processed the file multiple times instead of stopping once it was finished, below are two screenshots showing the already completed file, as well as the one that is currently getting processed by the node. I have also linked the job report for the completed job
![image](https://github.com/HaveAGitGat/Tdarr/assets/4286108/0e3ce7ab-0431-4f2d-bfe9-5a4817aa3a52)
![image](https://github.com/HaveAGitGat/Tdarr/assets/4286108/bea6a823-be78-4be8-94bd-7888ffdda9a2)

Job Report: https://pastebin.com/W8n9QTDi

**Comment by HaveAGitGat** [comment]
@trumpet7347 correct me if I’m wrong but those should be different files as Tdarr can’t have a specific file in its DB more than once. So a specific file can only appear once across the transcode tabs and once across the healthcheck tabs. I can’t see the filepaths in your screenshots to verify this though

**Comment by HaveAGitGat** [comment]
@trumpet7347 I can see the file sizes in the screenshots are different though so if you check the filepaths it should show those are different files

**Comment by trumpet7347** [comment]
You are correct, I made a backup folder so I could make testing a little easier, but I incorrectly put it in the media folder that tdarr was watching. I went ahead and canceled the job that was currently running, it was working on the backup file I made, not the media file. Comparing the two it looks like the file in the actual media folder was processed successfully.

**Comment by HaveAGitGat** [comment]
Ok great thanks for the update, I think I'll merge those changes then as `mvdir` is what is causing issues.

**Comment by HaveAGitGat** [comment]
Merged changes here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/549

Will close this as seems resolved, thanks for the help.

**Comment by trumpet7347** [comment]
Tested it with latest and it worked as expected, thank you for your awesome work @HaveAGitGat!

**Comment by HaveAGitGat** [comment]
Great :) no problem

**Comment by tomshomelab** [comment]
im also getting the same error; 

`After move/copy, destination file of size 0 does not match cache file of size`

im using flows and the "replaceOriginalFile" plugin

i know the mount points are correct / have not been changed. tdarr uses; 
- in docker tdarr uses; ` - /Transcoding_Temp:/temp` 
- in `fstab` to mount to the transcode location which i can access and edit from the VM that tdarr is running in i use the following command; `//192.168.0.11/Transcoding_Temp/ /Transcoding_Temp cifs username=USERNAME,password=PASSWORD,vers=3.0,mfsymlinks,uid=nobody,file_mode=0777,dir_mode=0777,noperm 0 0` 
- i can see that new edits and temp folders are made with todays date in the transcode location so i know that some data can be written, its not a permissions error. 

[l-pMSoYyzA-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13917981/l-pMSoYyzA-log.txt)

**Comment by RateThePaladin** [comment]
Same issue here, I'm getting this move error:

`File move error: {"errno":-18,"code":"EXDEV","syscall":"rename","path":"/temp/tdarr-workDir-node-GjEXPnakg-worker-back-bear-ts-1710527373841/1710527377312/sXXeXX XXXX.mkv","dest":"/mnt/media/Destination/Show/Season XX/sXXeXX XXXX.mkv.tmp"}`

Followed by the same 0 size error:

`Worker[back-bear]:After move/copy, destination file of size 0 does not match cache file of size 345795500`

Even stranger, after the second move method is attempted, this error appears:

`Worker[back-bear]:After move/copy, destination file of size 345795500 does match cache file of size 345795500`

**Comment by phyzical** [comment]
i have been facing this too with unraid.

my current workaround is to add a review step if the copy fails so its easier to "retry" the copy.

But running the "new permissions" on the media share /transcode cache usually unsticks it all. idk why some folders just start complaining about perms `ls -lah` reports no differences before or after so i think its a smb + unraid thing
 
![image](https://github.com/HaveAGitGat/Tdarr/assets/5182053/dcb054a9-7ba7-47cd-bc08-e67bf0a78e42)
