### ISSUE TITLE
Healtcheck in Flows doesn't save Flow logs

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#888]
I'm doing an Healtcheck "on flow error" before ending the flow.
In the error log i've found only the Healtcheck logs, and not the flow's one. 

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/cc850b40-7693-4e69-bef3-772ab656e8b0)

**Comment by HaveAGitGat** [comment]
Reopen in https://github.com/HaveAGitGat/Tdarr_Plugins if still having trouble

**Comment by HaveAGitGat** [comment]
e.g. showing up for me: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/06c6c671-6d5c-43b3-a51d-6fe340c84250)

**Comment by Kedryn** [comment]
I found out that it was doing transcoding, but was logging healtchecks under the "Trasconde: Errors/Cancelled". No transcodes were logged, and most of the movies were not transcoded at all.
Then, suddendly, it stopped logging altogether. The report page of new transcodes were empty.

i did a restart of the docker, but still no reports

![image](https://github.com/HaveAGitGat/Tdarr/assets/12759632/c2a4de0f-d39a-490b-a53f-a0715bde0884)

**Comment by Kedryn** [comment]
maybe a flag on those plugins to not exit in error? :)

**Comment by HaveAGitGat** [comment]
You need to use `Reset Flow Error` if you're not wanting the file to go into the 'Transcode Error' table after the flow has finished.

Not sure which plugin you are using but if it's the `Send Web Request` plugin you can see the code here:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/tools/webRequest/1.0.0/index.ts

There is no logic in that which tells the plugin to exit process on error. An error causes it to follow the error output path.
