### ISSUE TITLE
PIUD & GIUD not working as expected docker-compose

### ISSUE THREAD

**Issue by dagint** [HaveAGitGat/Tdarr#889]
**Describe the bug**
Using docker compose and specifying PIUD & GIUD values the resulting contains run as root and are not honoring the env set  This was previously working fine in >2.00.x  after upgrading to 2.13.01 it is no longer working correctly.  Happens with the server as well as the nodes.

**To Reproduce**
``` docker-compose.yml
version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:2.13.01
    restart: unless-stopped
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      #- 8267:8267 # node port. It should be mapped on this container because
                  # the node container use the network from the main container
    environment:
      - TZ=America/New_York
      - PUID=99
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - internalNode=true
    volumes:
      - /share/tdarr/server:/app/server
      - /share/tdarr/configs:/app/configs
      - /share/tdarr/logs:/app/logs
      - /share/media:/media
      - /share/tdarr/cache:/cache
      ```

**Expected behavior**
Expect container would run with the proper uid and guid defined in env vars

**Screenshots**
# docker exec -it tdarr /bin/bash                                        
root@5050ec189116:/# id
uid=0(root) gid=0(root) groups=0(root)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**
It's failing to get appropriate permissions to the storage locations

**Comment by HaveAGitGat** [comment]
Check the server/node container output on startup, it tells you more info. 

Post here if needed.

**Comment by dagint** [comment]
I'm likely doing something incorrectly.  It's weird it will make it through a portion of the conversion but eventually error on one of the

**Comment by dagint** [comment]
From one of the nodes.  When I'm inside of the running container I'm able to read/write successfully to the mount but when it writes it it writes it as root.  Very strange.  Again this worked fine in version 2.00.18.2  Only a problem since upgrading

```> docker exec -it tdarr-node /bin/bash
root@79014b55a3d3:/# ls /media/recordings/Dateline\ NBC/Season\ 31/Dateline\ NBC\ \(1992\)\ -\ S31E37\ -\ Page\ Turner*
'/media/recordings/Dateline NBC/Season 31/Dateline NBC (1992) - S31E37 - Page Turner.ts'  '/media/recordings/Dateline NBC/Season 31/Dateline NBC (1992) - S31E37 - Page Turner.ts.test'
root@79014b55a3d3:/# ls -la /media/recordings/Dateline\ NBC/Season\ 31/Dateline\ NBC\ \(1992\)\ -\ S31E37\ -\ Page\ Turner*
-rwxrwxrwx 1 abc  users 3239915484 Sep 22 23:02 '/media/recordings/Dateline NBC/Season 31/Dateline NBC (1992) - S31E37 - Page Turner.ts'
-rwxr-xr-x 1 root root  3239915484 Oct 16 12:30 '/media/recordings/Dateline NBC/Season 31/Dateline NBC (1992) - S31E37 - Page Turner.ts.test'
root@79014b55a3d3:/# rm /media/recordings/Dateline\ NBC/Season\ 31/Dateline\ NBC\ \(1992\)\ -\ S31E37\ -\ Page\ Turner.ts.test 
ls -lah /media/recordings/Dateline\ NBC/Season\ 31/Dateline\ NBC\ \(1992\)\ -\ S31E37\ -\ Page\ Turner.ts 
-rwxrwxrwx 1 abc users 3.1G Sep 22 23:02 '/media/recordings/Dateline NBC/Season 31/Dateline NBC (1992) - S31E37 - Page Turner.ts'
root@79014b55a3d3:/media/recordings/Dateline NBC/Season 31# touch test
root@79014b55a3d3:/media/recordings/Dateline NBC/Season 31# ls -lah test
-rw-r--r-- 1 root root 0 Oct 16 13:03 test
root@79014b55a3d3:/media/recordings/Dateline NBC/Season 31# rm test
root@79014b55a3d3:/media/recordings/Dateline NBC/Season 31# ls -lah test
ls: cannot access 'test': No such file or directory```

**Comment by dagint** [comment]
I reset my filesystem permissions and seems to be working as expected.  sorry for the noise

**Comment by HaveAGitGat** [comment]
Thanks for the update, pleased you found a solution.
