### ISSUE TITLE
Audio handbrake arguments

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#89]
I have a folder which contains FLAC files and I would like to convert them to MP3 (as high quality as possible). What would the argument be and how would I set that up in tdarr?

**Comment by HaveAGitGat** [comment]
Hi martin, go into the plugin creator and set up a filter to exclude mp3 codec.

Then set an FFmpeg custom transcode action. Your plugin summary should look like this:

![image](https://user-images.githubusercontent.com/43864057/70060558-aac03b00-15da-11ea-8c25-8e10b56054e8.png)

So the command being used is

>, -c:v copy -b:a 320k

Don't forget the comma at the beginning. The bitrate is 320kbs. Change if needed.

**Comment by HaveAGitGat** [comment]
Actually a better way is using this command:
>, -f mp3

Works well on some files I tested.

**Comment by HaveAGitGat** [comment]
Feel free to re-open if you still need help
