### ISSUE TITLE
Subtitles extract should be copied along with transcoded video

### ISSUE THREAD

**Issue by dimaTrinh** [HaveAGitGat/Tdarr#890]
**Is your feature request related to a problem? Please describe.**
I use the plugin to extract subtitles from videos. I also have a setup where I want to copy video files to an output folder after they are done transcoding. However, the subtitles files are not being copied together with the transcoded video, only the video is.

**Describe the solution you'd like**
I wish that all output of the program (including the extracted subtitles) were copied along with the transcoded video.

**Describe alternatives you've considered**
I have just been manually copying files myself.

**Additional context**

**Comment by HaveAGitGat** [comment]
Moved here ty:
https://github.com/HaveAGitGat/Tdarr_Plugins/issues/513
