### ISSUE TITLE
Transcode TRUEHD 7.1 Atmos to EAC-3 7.1 or AC3 7.1 Atmos (FFMPEG)

### ISSUE THREAD

**Issue by LimesKey** [HaveAGitGat/Tdarr#891]
**Is your feature request related to a problem? Please describe.**
This probably has already been talked about and discussed a while ago and this is not exactly related to Tdarr, but I wanted to know if there were any new developments to the EAC-3 encoder. None of my streaming devices support TrueHD audio and I would like to play video files that only have TrueHD 7.1 Atmos audio, and still have that great quality and 7.1 atmos surround. 

**Describe the solution you'd like**
This is actually more a FFMPEG or Handbreak feature request, but I would like to make sure that nothing like this already exists within Tdarr's supported encoding programs. Currently with FFMPEG I get `[eac3 @ 0x563491453b80] Specified channel layout '7.1' is not supported` or something similar to that when I attempt to transcode TrueHD 7.1 (or higher) to EAC-3 7.1. Does Handbreak work instead? If so, how would I get it setup / what custom arguments do I need?

**Additional context**
I apologize that this may not directly relate to Tdarr and I also apologize if this has been discussed many times before (I tried googling).

**Comment by supersnellehenk** [comment]
Ffmpeg doesn't have support for 7.1 (E)AC3. Nor can it maintain Atmos data when creating a new track, as the Dolby Atmos encoder is proprietary. 

As far as I'm aware no program supports the 7.1 layout for those codecs. Hope that helps.

**Comment by janngobble** [comment]
> Ffmpeg doesn't have support for 7.1 (E)AC3. Nor can it maintain Atmos data when creating a new track, as the Dolby Atmos encoder is proprietary.
> 
> As far as I'm aware no program supports the 7.1 layout for those codecs. Hope that helps.

I know this was almost a year ago, but FFMPEG7 can maintain Atmos audio data in m4v files. TrueHD can also be maintained if you use "-strict -2" as an encoding option.  Works great here! 

Though it does NOT support EAC 7.1. It CAN however, down mix that to EAC 5.1 (obv losing the channel info for 2 channels)

cc: @LimesKey

**Comment by ValeZAA** [comment]
>FFMPEG7 can maintain Atmos audio data in m4v files. TrueHD can also be maintained if you use "-strict -2" as an encoding option

Not with Atmos.
