### ISSUE TITLE
Question about optimal flow structure

### ISSUE THREAD

**Issue by andrew-kennedy** [HaveAGitGat/Tdarr#892]
I'm working on setting up a series of flows that do a few things:

First, I want to clean up input files (lets assume `.mp4` files for now) and remux them into mkvs with only 1 video and audio stream.

Then, if the video stream is an h264 stream, I want to attempt to transcode into AV1 with a specific quality setting, but progressively lowering the quality if after the first transcode the file size is too far outside some threshold. 

If after several transcode attempts there is no way to achieve the file size threshold within the range of quality options that I allow, I want to basically replace the original `mp4` with the remuxed file (discarding any successful transcodes), and mark the flow as complete so no further attempts are made to transcode that remuxed file on subsequent scans.

### Here are the problems I've run into:

I thought I could structure this where each lower quality setting transcode is a separate flow that I delegate to after doing file size ratio checks against the input to any given transcode flow, but the issue is that when I fail these checks I want to be able to begin the next flow using the *remuxed* `.mkv` file as the input, but "set original file" flow plugin will use the _starting_ file which is often an mp4 or something. 

I thought doing "replace original file" after I do the remuxing would lead to _that_ file becoming the one that subsequent "Set original file" plugins would set the working file back to, but that doesn't seem to be the case. Is there some other flow technique I could use to achieve my desired outcome?

**Comment by HaveAGitGat** [comment]
When you remux a file in your case the container changes so the 'Set Original File' will be going back to the original file (which in this case is now deleted), not the new file that's been created.

Would it not be worth doing the transcoding part first and then the remux afterwards? Then you'd be able to achieve what you're after.

**Comment by andrew-kennedy** [comment]
I ended up trying to flip the order first and that seems to have done it, thanks! Might be worth adding a caveat to the set original file docs as I spent a lot of time setting up the original flow before learning it wouldn't work in that order.

**Comment by HaveAGitGat** [comment]
Thanks I've updated the description here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/521
Will look at other solutions in future such as maybe a plugin to jump back 1,2 or 3 files etc
