### ISSUE TITLE
Constant Node Timeouts at poll-worker-limits

### ISSUE THREAD

**Issue by koffiefw** [HaveAGitGat/Tdarr#893]
**Describe the bug**
Nodes consistently timing out at poll-worker-limits. Sometimes nodes will process healthchecks and transcoding, but if they do it is only one every few minutes. Nodes also become unresponsive to adding CPU or GPU workers. If I try to navigate to `http://localhost:8265/api/v2/debug-vars/text` that also times out and typically seems to lock the server up.

**To Reproduce**
Start server on Windows 10 machine. Wait for database to fully load. Start node on same Windows machine, which connects fine but may or may not start processing but instantly starts throwing timeouts. Start node on separate Windows 11 machine, which also connects and instantly throws the same timeout error.

**Expected behavior**
Nodes connect and begin processing normally, and quickly.

**Screenshots**
N/A

**Please provide the following information:**

[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13048486/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13048517/Tdarr_Server_Log.txt)

 - OS: Windows 10 Server and Node, Windows 11 Node 
 - Browser: Firefox
 - Version: 2.13.01

**Comment by HaveAGitGat** [comment]
Just released 2.14.01 which increases the timeout limit so perhaps give it a try thanks

**Comment by koffiefw** [comment]
Was able to update to 2.14.02, and the problem persists.

[2023-10-29T15:17:36.188] [DEBUG] Tdarr_Node - Polling worker response error:30001ms
[2023-10-29T15:17:36.189] [ERROR] Tdarr_Node - Error: timeout of 30000ms exceeded
    at createError (C:\Tdarr_Updater\Tdarr_Node\node_modules\axios\lib\core\createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (C:\Tdarr_Updater\Tdarr_Node\node_modules\axios\lib\adapters\http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (C:\Tdarr_Updater\Tdarr_Node\node_modules\follow-redirects\index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 31
    },
    method: 'post',
    url: 'http://0.0.0.0:8266/api/v2/poll-worker-limits',
    data: '{"data":{"nodeID":"ohR4-D_-s"}}'
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v2/poll-worker-limits',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '0.0.0.0',
      port: '8266',
      nativeProtocols: [Object],
      pathname: '/api/v2/poll-worker-limits'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 31,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 31,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/v2/poll-worker-limits HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 31\r\n' +
        'Host: 0.0.0.0:8266\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v2/poll-worker-limits',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'http://0.0.0.0:8266/api/v2/poll-worker-limits',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by p2bauer** [comment]
Was anyone able to figure out a solution to this issue?  I have a linux node which is experiencing the exact same issue, constant reconnections which causes the node to fail polling /api/v2/poll-worker-limits because the node name is no longer registered...

**Comment by HaveAGitGat** [comment]
Seems like an issue to do with the websockets:

```
2023-12-02T20:00:25.299] [ERROR] Tdarr_Node - Error: timeout
    at Timeout.<anonymous> (/app/Tdarr_Node/node_modules/socket.io-client/build/cjs/manager.js:173:38)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

So the websocket connection between server and node drops which then causes the node to disconnect/deregister. 

```
[2023-12-02T20:00:31.360] [WARN] Tdarr_Server - Node MyExternalNode deregistered
[2023-12-02T20:00:31.371] [ERROR] Tdarr_Server - alterWorkerLimit error
[2023-12-02T20:00:31.408] [ERROR] Tdarr_Server - Error during polling worker limits from node "I2wKu8jxt". The node is not registered.
```

Think someone in the past this was caused by someone's firewall interfering but may be unrelated here. Tricky error to debug, will need to look into the socket-io debug steps.

**Comment by HaveAGitGat** [comment]
This may have been caused by the node plugins downloader blocking up the rest of the node. In 2.20.01 just released I've moved that to a separate thread so should fix this if that's what caused it. Feel free to re-open if still having the issue.

**Comment by julianrinaldi** [comment]
I'm on 2.20.01 and have the same issue. It's a new install which I just made yesterday so I can't say if it was happening before.

`[2024-06-13T12:07:34.211] [DEBUG] Tdarr_Node - Polling worker response error:30006ms
[2024-06-13T12:07:34.211] [ERROR] Tdarr_Node - Error: timeout of 30000ms exceeded
    at createError (/home/julianrinaldi/tdarr/Tdarr_Node/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/home/julianrinaldi/tdarr/Tdarr_Node/node_modules/axios/lib/adapters/http.js:369:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/home/julianrinaldi/tdarr/Tdarr_Node/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'x-api-key': '',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 31
    },
    method: 'post',
    url: 'http://0.0.0.0:8266/api/v2/poll-worker-limits',
    data: '{"data":{"nodeID":"5CUgiAY4s"}}'
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v2/poll-worker-limits',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '0.0.0.0',
      port: '8266',
      nativeProtocols: [Object],
      pathname: '/api/v2/poll-worker-limits'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 31,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 31,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/v2/poll-worker-limits HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'x-api-key: \r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 31\r\n' +
        'Host: 0.0.0.0:8266\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v2/poll-worker-limits',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'http://0.0.0.0:8266/api/v2/poll-worker-limits',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
`

**Comment by mckellar11** [comment]
I'm getting this in 2025

**Comment by catduckgnaf** [comment]
> I'm getting this in 2025

Have you found a fix?

**Comment by HaveAGitGat** [comment]
Is the server at high load? If your Tdarr server is on the same machine that you’re transcoding on then can cause this if cpu is overloaded at 100%

**Comment by catduckgnaf** [comment]
> Is the server at high load? If your Tdarr server is on the same machine that you’re transcoding on then can cause this if cpu is overloaded at 100%

Thank you for replying. To anyone else who runs into this issue it my GPU I have confirmed is partially failing. The GPU works, but it can't use HW Encoding anymore. So the GPU can do CPU tasks, but when it comes time to encode, it causes the server to go crazy. I didn't notice the CPU even going high, but the second it did, tdarr crashed and cpu overload was  back to normal and nowhere close to 100%.
