### ISSUE TITLE
Using Tdarr part of a video scraping process

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#894]
I currently have a scraper (Python) that downloads videos. Then periodically I use Tdarr to go through the entire archive to convert to H265.

I am wondering how I would be able to perhaps merge the process? I looked at the docs/API and it seems like that isn't really feasible right now? I'm trying to essentially have a self-contained version of Tdarr within Python, such as a module that would allow me to import Tdarr, set the parameters in the script, then whenever I call that function of conversion, it can just fire up Tdarr to do the process. This way I can convert every video I download immediately instead of doing do in bulk every so often.

Any help would be appreciated.

**Comment by HaveAGitGat** [comment]
Hi, Tdarr has a folder watch option in the library settings so should just pick up when there's a new file and process it

Could also use the API to trigger a scan (find new) every time a new file is downloaded but that isn't needed as the folder watch option should do what you're after.

There's not a way to import it into a Python script as a dependency.
