### ISSUE TITLE
Keep files even if not everything is successfull.

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#896]
**Is your feature request related to a problem? Please describe.**
I have some files where i cant successfull run the whole flow.

I connected them if they fail to keep going, but tdarr currently discards everything anyways.

**Describe the solution you'd like**
I would like an option to just say, what ever comes out of it, keep it.

**Comment by supersnellehenk** [comment]
You can output any error from a block into 'Reset flow error' which would do what you want I believe

**Comment by HaveAGitGat** [comment]
Yes, mentioned in the flow error tutorial templates, take a look if you haven't already:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/66ad300c-a1ba-4443-b9b8-67b015706b02)

**Comment by HaveAGitGat** [comment]
@CurlyFlow why would you want to keep the file if it's failed? Often if ffmpeg fails on a file it won't produce anything.

And in that case you can not use 'Reset Flow Error' and continue as normal. The rest of the flow will continue and then at the end the item will be put into the transcode error table in the UI.

Or you can use the 'Copy To Directory' plugin to copy the failed file wherever you'd like.

Best to post your flow (you can export it on the flows tab).

**Comment by HaveAGitGat** [comment]
@CurlyFlow thanks, the logic for that plugin is mostly fine but suppose depends on how much the filename is changed as if it's changed too much then Radarr won't recognise the new file.

I've made a small change to the plugin here so it sends the original filename to radarr/sonarr, so hopefully it should work for you:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/557

But yeah it's quick picky. For example I tried putting the exact movie name in request sent to Radarr and it didn't work, but when putting the gibberish sample filename sample.x264.ac3.mkv it worked.

**Comment by supersnellehenk** [comment]
> Cant you get an id from radarr and use that?

That's exactly what the plugin is trying to do, based off of the original filename. For updating I believe you have to click update, then sync.

**Comment by HaveAGitGat** [comment]
@CurlyFlow it's worth just testing the Radarr API directly. Seems it still can't deal with the file you're giving it (perhaps that specific file is not in Radarr db)

For example add ip, api key and run the following command in a terminal:

```
curl -X GET "http://192.168.1.1:7878/api/v3/parse?title=test.mkv" \
     -H "Content-Type: application/json" \
     -H "X-Api-Key: xxx" \
     -H "Accept: application/json"
```

The title needs to be url encoded (can use https://www.urlencoder.org/) so for you it should be:

```
curl -X GET "http://192.168.1.1:7878/api/v3/parse?title=The%20XXX%20%282023%29%20%7Bimdb-tt123456789%7D%2FThe%20XXX%20%5BDE%2BEN%5D%20Remux-2160p.mp4" \
     -H "Content-Type: application/json" \
     -H "X-Api-Key: xxx" \
     -H "Accept: application/json"
```

It should give response with file info but in your case I assume the response is

```
{
  "title": "xyz",
  "customFormatScore": 0
}
```

Which means it can't find the file.

**Comment by HaveAGitGat** [comment]
@CurlyFlow sorry what do you mean `ORIGINAL FILENAME`, is that a variable?
