### ISSUE TITLE
multiple file copy fails then successfull, why?

### ISSUE THREAD

**Issue by CurlyFlow** [HaveAGitGat/Tdarr#897]
**Describe the bug**

Yeah ive noticed that the first 1-2 copys always fail, why? What is he tryin to do? Why does it work in the end? Does it create unneccessary file copies?

 OR "is that normal"?

17 2023-10-27T10:25:02.643Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:File has changed, replacing original file

18 2023-10-27T10:25:02.644Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:{"currentPath":"/temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX","newPath":"/mnt/user/XXX","newPathTmp":"/mnt/user/XXX.tmp"}

19 2023-10-27T10:25:04.646Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Attempt 1: Moving file from /temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX to /mnt/user/XXX.tmp

20 2023-10-27T10:25:04.648Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Failed to move file from /temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX to /mnt/user/XXX.tmp

21 2023-10-27T10:25:04.650Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX","dest":"/mnt/user/XXX.tmp"}

22 2023-10-27T10:25:04.651Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:{"errno":-2,"code":"ENOENT","syscall":"stat","path":"/mnt/user/XXX.tmp"}

23 2023-10-27T10:25:04.652Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:**Attempt 1 failed**: Moving file from /temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX to /mnt/user/XXX.tmp

24 2023-10-27T10:25:04.652Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Attempt 2: Moving file from /temp/tdarr-workDir-node-CP1GhkmOa-worker-recent-rat-ts-1698393362296/1698395000839/XXX XXX to /mnt/user/XXX.tmp

25 2023-10-27T10:29:40.950Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Deleting original file:/mnt/user/XXX

26 2023-10-27T10:29:44.956Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Attempt 1: Moving file from /mnt/user/XXX.tmp to /mnt/user/XXX

27 2023-10-27T10:29:44.959Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Plugin run complete

28 2023-10-27T10:29:44.961Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:{"_id":"/mnt/user/XXX","outputNumber":1,"variables":{"flowFailed":false}}

29 2023-10-27T10:29:44.963Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:No next plugin

30 2023-10-27T10:29:44.965Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Requesting Tdarr Server to scan file

31 2023-10-27T10:29:46.967Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Scan complete

32 2023-10-27T10:29:46.969Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Old size: 16.737235073931515

33 2023-10-27T10:29:46.970Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:New size: 17.156269926577806

34 2023-10-27T10:29:46.971Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:Size difference: -0.41903485264629126

35 2023-10-27T10:29:48.974Z 4LXGY5vOa:Node[MyInternalNode]:Worker[recent-rat]:File processing complete

**To Reproduce**
start

**Expected behavior**
i expect that copies dont fail.

**Please provide the following information:**

- Job reports: https://docs.tdarr.io/docs/other/job-reports
[4LXGY5vOa-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13186827/4LXGY5vOa-log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 Unraid Version 6.12.4

My mount is a mergefs mount, im not using a cache drive.

**Additional context**
If you need more details, tell me what u want

**Comment by HaveAGitGat** [comment]
Hi it's just running this here: 
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/fileUtils.ts#L45

So it tries to move with `gracefulfs` and then tries to move with `mvdir`.
