### ISSUE TITLE
Feature Request - Encoded Stats

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#9]
Thinking about it, it would be nice to have a running tally of what you had, what you've done and whats left to do.  For me I just want my whole library in HEVC.  So knowing how much I've personally converted, e.g. each day, by week etc would be quite motivating.

**Comment by HaveAGitGat** [comment]
Think we talked about this a while ago but the stats page shows this. 09 adds history graphs to show how much has been done.
