### ISSUE TITLE
Tdarr node docker tag latest is not keeping track with Tdarr server docker tag latest

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#900]
This has happened a few times so I'm reporting it as a bug. Several times now Tdarr server has updated and complained that the Tdarr node has not been updated. If I docker pull latest I do not get the corresponding Tdarr node for Tdarr server. I have to update it by version number tag. Both server and node latest tags should be kept in sync.

When Tdarr server updates pull the latest for both server and node and they will not be the same version.

Keep the latest tag in sync

**Comment by HaveAGitGat** [comment]
Hi this a local issue issue with your Docker application.

You can see here that Server and Node latest is the same version:

https://hub.docker.com/r/haveagitgat/tdarr/tags
https://hub.docker.com/r/haveagitgat/tdarr_node/tags

The images are released within a minute or 2 of eachother. Same with the images on GitHub. Maybe try those:

https://github.com/HaveAGitGat/Tdarr/pkgs/container/tdarr

But yeah issue between your Docker and the registry, not something I can do anything about.

Maybe try suggestions here:
https://stackoverflow.com/questions/56286929/docker-pull-wouldnt-pull-latest-image-from-remote

**Comment by adefaria** [comment]
Ah it may be that I'm using docker run in my script to recreate the container. According to that link: "docker run (not docker pull) search first in your local registry on your machine. If there is the image with the tag latest, the search is satisfied and terminated. If the image with the given tag is not available in your local registry, then docker will search in a remote registry like docker hub or your own". So next time I'll try removing the image and container then doing docker run.

Should I switch to not use docker run? would this solve #815 ?

**Comment by HaveAGitGat** [comment]
If using Docker run the best to use `docker run --pull=always` to always get latest. Might solve the other issue

**Comment by adefaria** [comment]
I guess that's an option. Synology has this new Container Manager that tells me when docker images need updating. And it will update them almost automatically (still have to click an update button twice). For most of my docker images, it pulls the new image and recreates the container. However, for the Tdarr server, the restarting of the new container never puts up the Web UI (see #815) which is why I still have my script that uses docker run. I'm thinking that if abandon the docker run and instead just create the Tdarr server container like all my other docker containers, then perhaps the Synology Contain Manager press-update-button-twice would result in a successful running the the Tdarr server container. Tdarr server is the only docker container of the 7 or so docker containers I run that fails to restart.
