### ISSUE TITLE
Eliminate popup

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#901]
When in the Tdarr web interface and selecting various things like Requeue transcode or Transcode success the browser pops up a dialog that must be acknowledged. I'm wondering why this confirmation dialog is necessary. Surely it could just click through to where you are trying to go.

**Comment by HaveAGitGat** [comment]
Hi do you have a screenshot?

**Comment by HaveAGitGat** [comment]
The confirmation was requested by a few people a few years ago. It's typically when applying changes to lots of files. Don't want to accidentally requeue or skip 100k files etc. 

If it's showing for you when just doing a single file action then let me know.

**Comment by adefaria** [comment]
Here's a shot of the popup dialog:
![2023-11-01@07:32:51](https://github.com/HaveAGitGat/Tdarr/assets/2692127/3318f9f5-7433-46e9-bccd-8d88897d5b31)

Note the white bounding box - that's new. Didn't used to happen before.

After confirming:

![2023-11-01@07:33:11](https://github.com/HaveAGitGat/Tdarr/assets/2692127/31bbba34-e6f4-4419-a158-b011719466e0)

I think when a lot of files are being processed a little dialog is displayed. Perhaps put a cancel button on there? Not a biggy really.

**Comment by HaveAGitGat** [comment]
Thanks I've removed that for next version

**Comment by adefaria** [comment]
While that popup is now removed, there is another place where it still pops up. If you select Transcode success as in the above you'll be presented with a screen that lists all that qualify as transcode success. Similarly with Queued, etc. If I then select Requeue Transcode I still get the popup.

**Comment by HaveAGitGat** [comment]
Yes it’s meant to be there. Like I said, it’s an action being applied to lots of files so confirmation is a good practice.
