### ISSUE TITLE
Healtcheck always fails the first time after transcode.

### ISSUE THREAD

**Issue by yeyeoke** [HaveAGitGat/Tdarr#903]
**Describe the bug**
Healthchecks after transcodes almost always "fails". They get added to the tab "Transcode Error/Canceled".
If I reque the health check it completes successfully and the report states that everything finished successfully. 

**To Reproduce**
I have no idea to be honest. 

**Expected behavior**
A successful health check should not show up as failed. 

**Screenshots**
<img width="1076" alt="Skärmavbild 2023-11-04 kl  11 54 33" src="https://github.com/HaveAGitGat/Tdarr/assets/12892950/c8fd9ddd-4311-4ca7-aabb-bdbef9235fbf">
<img width="1106" alt="Skärmavbild 2023-11-04 kl  11 44 42" src="https://github.com/HaveAGitGat/Tdarr/assets/12892950/d612f4ae-d76a-4c01-b6b0-ce2d107303eb">
<img width="920" alt="Skärmavbild 2023-11-04 kl  11 45 01" src="https://github.com/HaveAGitGat/Tdarr/assets/12892950/3e61d276-e851-4ae6-a0c2-c7f7b426599e">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
- 
**Tdarr_Node_Config.json**

{
  "nodeID": "UBU-Media",
  "nodeName": "UBU-Media",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "platform_arch": "linux_x64_docker_true"
}

**Tdarr_Server_Config.json**

{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""
}

- Job reports: https://docs.tdarr.io/docs/other/job-reports

[8ci3lmeSZ-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13256386/8ci3lmeSZ-log.txt)
[vsnYbXGmjr5-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13256387/vsnYbXGmjr5-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13256392/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13256393/Tdarr_Server_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

No errors. 

 - OS: Linux
 - Browser: Safari
 - Version: 2.14.01

**Additional context**
Tdarr is in a docker container on Host 1, the media is stored on Host 2 and shared over NFS.

**Comment by HaveAGitGat** [comment]
Hi this happens when FFprobe fails to scan the new file after it's been moved to the library so seems maybe something else is using/scanning the new file?

If you run a health check in a flow then you can add a wait which might prevent this issue.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/cbfa1a4a-0432-4407-9388-843f9c6549c1)

I've updated for next version so it goes into the health check queue even if ffprobe fails after the new file move.
