### ISSUE TITLE
Way to limit Tdarr CPU Usage on Windows

### ISSUE THREAD

**Issue by adamgwaps** [HaveAGitGat/Tdarr#906]
When transcoding with Intel ARC i found out that using all available CPU(current default settings) 32 vs using only 4-8 on ryzen 5950x yields to almost the same fps with only around +/- 5% loss

An option in the app to pick how many CPU will be used.

before this can be achieved using task manager then modifying the affinity, but it seems it does not work with tdarr_tray because it is spawning new process each time there is a new transcode.

**Comment by HaveAGitGat** [comment]
Hi there is not a simple cross platform way to do this. You can try using this option in the node panel for reducing process priority:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/c6b2caa2-4700-4a5b-9b92-10295b758e16)

Best way to do this is to use Docker (available on Windows too) and then pin the cores available to the container. More info here:
https://docs.docker.com/config/containers/resource_constraints/#cpu
