### ISSUE TITLE
LD_LIBRARY_PATH prevents vaapi encoding

### ISSUE THREAD

**Issue by gelse** [HaveAGitGat/Tdarr#907]
**Describe the bug**
h264 encoding via VAAPI in dockerized environment does not work and throws an error:
```
[AVHWDeviceContext @ 0x5612596f1580] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x5612596f1580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
No device available for decoder: device type vaapi needed for codec h264.
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:0 -> #0:1 (aac (native) -> vorbis (libvorbis))
Device setup failed for decoder on input stream #0:1 : Input/output error
```

**To Reproduce**
Start the tdarr-node container.
```
docker run --rm -d \
  -v /root/docker/tdarr-node/configs:/app/configs \
  -v /root/docker/tdarr-node/logs:/app/logs \
  -v /mnt/storage7:/storage7 \
  --name tdarr-node \
  --device /dev/dri:/dev/dri \
  -e TZ=Europe/Vienna \
  -e PUID=1000 \
  -e PGID=1000 \
  -e UMASK_SET=002 \
  -e nodeName=MainNode \
  -e serverIP=tdarr \
  -e serverPort=8266 \
  -e ffmpegVersion=6 \
  -e inContainer=true \
  ghcr.io/haveagitgat/tdarr_node:latest
```
Either: give the container any h264 encoding that uses vaapi
Or attach to it and run ffmpeg manually:
```
docker run -ti tdarr-node /bin/bash
ffmpeg \
    -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 \
    -hwaccel_output_format vaapi \
    -i /storage7/.myfiles/_tmp/input.mp4 \
    -c:v:0 h264_vaapi \
    /storage7/.myfiles/_tmp/sample-out.mkv
```

Additional info:
during testing i found out that it works, if i overwrite the [CMD] and execute ffmpeg. That lead to experimenting around, which resulted in the following:

when i attach as described above, then `unset LD_LIBRARY_PATH` and THEN execute the ffmpeg command, i get the message
```
libva: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed
```
but the encoding works just fine, and in a speed that i expect - including the GPU working (found via intel gpu tools on the host).

**Expected behavior**
GPU encoding works.

**Please provide the following information:**
- Config files _irrelevant in this scenario_

- Job reports: _irrelevant in this scenario_

- Log files _i think irrelevant, but can be provided on request_

- Worker error _ffmpeg error, see above_ 
```
[AVHWDeviceContext @ 0x5612596f1580] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x5612596f1580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
No device available for decoder: device type vaapi needed for codec h264.
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:0 -> #0:1 (aac (native) -> vorbis (libvorbis))
Device setup failed for decoder on input stream #0:1 : Input/output error
```

 - OS: Linux / docker
 - Browser _irrelevant_
 - Version ghcr.io/haveagitgat/tdarr_node:8cd0053ccaad

**Additional information**
I am not sure why the LD_LIBRARY_PATH is preventing ffmpeg to work, it somehow indicates that there are duplicate libraries in the container, i think ? And i am not yet sure as to how to workaround this problem - if i find a workaround, i will update this.

Also - if you need any further information, please let me know.

**Comment by gelse** [comment]
Update:

i did a bit of further research and found https://github.com/HaveAGitGat/Tdarr/issues/258

it seems that if i do
```
export LIBVA_DRIVER_NAME=i965
```
it works as well.

That would mean it is a duplicate, but still exists in v2.
And i would consider it a bug.

**Comment by gelse** [comment]
short update:

specifying 
```
LIBVA_DRIVER_NAME=i965
LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri/
```
as environment variables for the container is not sufficient, as the container still lacks the `i965-va-driver-shaders` package which needs to be manually installed. which is not optimal, as it of course is broken again each time the container gets recreated.

**Comment by HaveAGitGat** [comment]
Thanks will look into adding this

**Comment by HaveAGitGat** [comment]
Will move this under here: https://github.com/HaveAGitGat/Tdarr/issues/902
