### ISSUE TITLE
Load balancing across nodes can easily lead to workers sitting idle.

### ISSUE THREAD

**Issue by instinkt900** [HaveAGitGat/Tdarr#908]
**Describe the bug**
I have 2 worker nodes. One with a GPU one without. I have a plugin stack that first transcodes video files into a given codec using nvenc and the a loudness normalization step that is CPU work. If I allow my GPU node to do CPU work, the CPU node will sit idle because as the GPU node finishes the encoding it immediately picks up the CPU work and does the loudness pass.
If I restrict the GPU node to GPU work then it behaves as expected, completing the nvenc pass and then only picking up new GPU work and the CPU node then takes over and handles the loudness pass. But this now means that when the GPU work is done (since its much faster than the loudness normalization) it will now sit idle while the CPU node finishes off all the pending tasks.

**To Reproduce**
As described above. Have a GPU and a CPU only node and a plugin stack that contains GPU and CPU work. Notice the work is not evenly distributed across the nodes.

**Expected behavior**
I would have expected the GPU node to prioritize GPU work since it's a specialty task so it would burn through all the GPU tasks at first and then when there's nothing else to do, it can pick up the remaining CPU work.

**Screenshots**

**Please provide the following information:**
I can provide these but they're basically bog standard.

**Additional context**
The two plugins I'm using are `Migz-Transcode Using NVIDIA GPU & FFMPEG` and `2 Pass Loudnorm Volume Normalization` if that helps.

**Comment by supersnellehenk** [comment]
There's not really load balancing in the way you describe it, it's just workers waiting for jobs being available. You could add a CPU worker to your GPU node and it'll also do the CPU task, but it might do it at the same time as the GPU task is being ran in the GPU worker on that same node.

**Comment by HaveAGitGat** [comment]
Yeah adding a CPU worker to your 'GPU' node would would solve this.

**Comment by instinkt900** [comment]
No. As stated in the original post, having the GPU node have CPU workers results in the CPU node sitting idle because the GPU work finishes on the GPU node, then the GPU node then picks up the available CPU work, rather than it going to the CPU node and it picking up more GPU work.

**Comment by supersnellehenk** [comment]
You mean with 'Allow GPU workers to do CPU tasks' disabled on the GPU node? With it enabled then the GPU worker itself will do the CPU tasks, with it disabled it should pop it back into the cache waiting for a CPU worker.

**Comment by instinkt900** [comment]
Oh I see. My apologies. I haven't been able to try that yet. Will give it a go.
