### ISSUE TITLE
Flow Set Video Encoder quality

### ISSUE THREAD

**Issue by Ulrar** [HaveAGitGat/Tdarr#909]
Hi,

Just taking a look at flows now that it's in beta, and I see that the Set Video Encoder one requires you to choose a preset and a quality.

In my classic library setting, I just leave the bitrate_cutoff empty. I may have it wrong but I believe that means it doesn't enforce any kind of limit and just converts from x264 to hevc as is. The resulting files have been 50% smaller on average and looking pretty good so I don't want to change it.

Is there a way to keep that behavior with flows (besides invoking the classic plugin) ? I realize it's just a beta and maybe it's just not implemented yet, I'm just eager because I'd like to use the resolution to issue #804 which requires me to move to flows.

Also as a bonus question, how do I delete a flow step ? I dropped a few on there to have a look at them but I can't figure out how to remove them.

Thanks

**Comment by HaveAGitGat** [comment]
Hi, please check this:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/cb4727f6-4a57-4a60-a838-a448a6ecb4ee)

Or you can right click to delete a plugin:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6751ac8c-0bd0-4f25-a096-41a7b93e7d1b)



There is not yet a way to do the same thing in flows without the classic plugin as that plugin uses half the source file bitrate (not yet a flow plugin to do that but maybe in future)

**Comment by Ulrar** [comment]
> Hi, please check this: ![image](https://user-images.githubusercontent.com/43864057/282394266-cb4727f6-4a57-4a60-a838-a448a6ecb4ee.png)
> 
> Or you can right click to delete a plugin: ![image](https://user-images.githubusercontent.com/43864057/282394564-6751ac8c-0bd0-4f25-a096-41a7b93e7d1b.png)
> 

Right, that's why I couldn't figure it out, no backspace / right click on phones. I'll break out the laptop, thanks

> There is not yet a way to do the same thing in flows without the classic plugin as that plugin uses half the source file bitrate (not yet a flow plugin to do that but maybe in future)

So there's no equivalent settings that can be used ? It'd be great to have, the files resulting from the classic flow plug-in look great
