### ISSUE TITLE
Replace Original File Reporting Failure to Move file from temp directory even though file was sucesfully moved

### ISSUE THREAD

**Issue by trumpet7347** [HaveAGitGat/Tdarr#910]
**Describe the bug**
After transcoding the file, and attempting to moving the file in the temp directory back to the main library, the file gets successfully copied, but Tdarr reports that it fails.

**To Reproduce**
Steps to reproduce the behavior: Transcode a file in any version after 2.0.25

**Expected behavior**
The file should get moved to the library folder and replace the original file

**Screenshots**
Here is a screen shot after the transcoding process has taken place, showing that the file has been moved to the correct folder

![2023-11-12_11-02-45](https://github.com/HaveAGitGat/Tdarr/assets/4286108/878377b6-ce02-4dba-a7cc-1c496b0554ae)

**Please provide the following information:**
- Server Config
`{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""
}`

- Node Config
`
{
  "nodeID": "node1",
  "nodeName": "node1",
  "serverIP": "192.168.50.119",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "DEBUG",
  "priority": -1,
  "cronPluginUpdate": "",
  "platform_arch": "linux_x64_docker_true"
}
`
- Job reports: https://pastebin.com/5cmcJ8fj

- Node Log File Error
`
[2023-11-12T04:41:16.172] [ERROR] Tdarr_Node - Error: Failed to move file from /temp/tdarr-workDir-node-ZXAQ66-jn-worker-plush-pike-ts-1699759083017/1699759092153/XXXXXX.mkv to /media/tv/XXXXXX/Season 1/XXXXXX.mkv.tmp, check errors above
    at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileUtils.js:140:31
    at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileUtils.js:33:23)
    at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileUtils.js:14:53)
    at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/FlowHelpers/1.0.0/fileUtils.js:5:58)
`

 - OS: Docker inside Linux
 - Browser Firefox
 - Version 2.10.01 or Greater

**Comment by HaveAGitGat** [comment]
Hi, if you use a the plugin stack then should work as it did before. I see you're using a flow it's running this code which for some reason causes some issues for some people even though it's mostly just the native copy + a different fallback method: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/fileUtils.ts#L45

**Comment by trumpet7347** [comment]
Swapping back to the plugin stack was one of the troubleshooting steps I took, unfortunately that process is also reporting a failure for me, it does however successfully copy the file from the temp directory back into the media folder. However I did observe in this instance though that instead of just going to the error tab of the Status panel, it will stay in the staging queue with a "Copy Failed" status, this is to be expected, but since the transocded file was successfully moved to the library, the temp directory is empty, and when you select the option to "Retry Copy", the file that was successfully moved to the library gets deleted, causing a total loss in the file

In the screens shot you can see that I have set the library to use the Plugin Stack instead of the flow, but the Job still reports a failure. I have also included the job report and the error from the tdarr server log file

![image](https://github.com/HaveAGitGat/Tdarr/assets/4286108/520ca61f-0087-435c-9ae5-1598e5ed0515)

Job Report: https://pastebin.com/ncG5waKh

Server Log Error:
```
[2023-11-13T15:37:37.089] [ERROR] Tdarr_Server - [Error: ENOENT: no such file or directory, lstat '/media/tv/XXXXXXX/Season 1/XXXXXXX-TdarrCacheFile-Y6LNwQObYu.mkv'] {

errno: -2,

code: 'ENOENT',

syscall: 'lstat',

path: '/media/tv/XXXXXXX/Season 1/XXXXXXXTdarrCacheFile-Y6LNwQObYu.mkv'

}

[2023-11-13T15:37:37.138] [ERROR] Tdarr_Server - stderr: {

}
```

**Comment by HaveAGitGat** [comment]
Will move this under here, check the latest comment: https://github.com/HaveAGitGat/Tdarr/issues/885
