### ISSUE TITLE
Tdarr can not detect audio attached to a video file

### ISSUE THREAD

**Issue by CptAXT** [HaveAGitGat/Tdarr#911]
I have scanned several different folders on only a handful of files have had their audio file detected most I can not see any audio even though video file does have audio.  This is causing a problem since I am trying to convert the audio format from FLAC to ACC or AC3 and none of the plugins are working, I am guessing they are not working since Tdarr can not see the audio file.

**Comment by HaveAGitGat** [comment]
Hi please paste the file info here:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/c57d7c0b-dedd-4e94-8fdd-c0011eb62f35)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/84f9c7c8-16ea-4ded-af90-5eccfaa2bd35)

**Comment by HaveAGitGat** [comment]
Reopen if needed
