### ISSUE TITLE
tdarr docs out of date

### ISSUE THREAD

**Issue by carlos-443-diaz** [HaveAGitGat/Tdarr#913]
I spent far too long troubleshooting and reading your docs which are incorrect.

I finally was reading the init script for the worker node to find out that in the example linked below, the setting internalNode=true is missing for the worker.

https://docs.tdarr.io/docs/installation/docker/run-compose#compose

**Comment by HaveAGitGat** [comment]
Hi thanks for opening an issue. Sorry I'm not sure I understand your question, none of the settings there apply to workers, they are for the server and node. The `internalNode` variable does not apply to the `tdarr_node` container, it's only for the `tdarr` container. So you don't need to use `internalNode` for the nodes.

Hope that helps. If still having trouble then let me know thanks.
