### ISSUE TITLE
Advanced Transcoding Integration for Plex Library Management with Emphasis on AV1 Format

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#914]
#### **Summary**
This proposal introduces enhancements for Tdarr, Radarr, and Sonarr, aimed at improving integration and management of media files for Plex, with a special focus on the transcoding process and efficient library updates. The adoption of the AV1 format by Plex serves as a primary trigger for this proposal.

---

#### **Detailed Features**

**On Tdarr's Side:**

1. **Source Directory Enhancement:**
   - Implement an option under the "source" directory in Tdarr's interface.
   - Indicate the inclusion of a Plex 'tbp/' folder and a '.plexignore' file.
   - Set `/[root folder]/` as the source, with Tdarr processing files in `/[root_folder]/tbp`, and moving them to `/[root folder]/` after transcoding.

2. **AV1 Plugin Addition:**
   - Introduce a specific AV1 plugin to Tdarr, simplifying the transcoding process for users and embracing the latest video encoding standards.

---

**On Radarr/Sonarr's Side:**

3. **New 'Transcoding' Tab in Settings:**
   - Add a "Transcoding" tab within the Settings menu of Radarr and Sonarr, focusing on streamlined transcoding workflows.

4. **Transcoding Settings Page Enhancements:**
   - Feature a tickbox for creating a 'tbp' folder and a '.plexignore' file in the root directory.
   - Facilitate the handling of files destined for transcoding and protect against misclassification by Radarr and Sonarr.

5. **Integrated Workflow and Automation:**
   - Configure Radarr and Sonarr to recognize `/[root folder]/tbp` as a temporary storage for files awaiting Tdarr transcoding.
   - Ensure these systems update their libraries to reflect file presence in both directories, and automate Plex library updates post-transcoding.

---

#### **Collaboration and Flexibility:**

- The enhancements proposed can be independently implemented by Tdarr, Radarr, or Sonarr. 
- Even if only one party adopts these changes, the new setup will still offer benefits and can be utilized effectively.
- However, as part of a collaborative community, synchronized adoption would greatly enhance user experience and operational efficiency.

#### **Benefits:**
- Provides a more streamlined process for managing and transcoding media files, especially with the AV1 format.
- Reduces manual intervention and error in media file handling.
- Enhances user experience through a unified, automated workflow.

#### **Suggested Implementation Timeline:**
- Development and beta testing over 3-6 months.
- Full deployment and integration within 6-12 months, subject to feedback and testing results.

---

**Comment by supersnellehenk** [comment]
I'm not sure what the addition of a plexignore file and an additional folder would do, since Tdarr does all its processing in the cache directory of the library anyways? So only the end result gets put back in the media library.

**Comment by HaveAGitGat** [comment]
Hi, thanks for the suggestion. I'm not really sure this has any need on Tdarr's side. As snell says, the transcoding is done in the Tdarr transcode cache and using the flows system you can do whatever you like with the file afterwards. The flow plugin 'Set Video Encoder' has an option for AV1 encoding, not sure if you've tried that.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/91800713-463e-4788-8c69-b512f19a350c)
