### ISSUE TITLE
Option to not remove files from libraries when media root path inaccessible

### ISSUE THREAD

**Issue by ReeKorl** [HaveAGitGat/Tdarr#915]
**Is your feature request related to a problem? Please describe.**
A recent brief network outage caused a loss of connectivity between the media device and the Tdarr Server. Consequently, the server detected a change in every library (which use UNC network paths), rescanned detecting no files at all, and removed the entirety of every library. 

**Describe the solution you'd like**
Ideally a config option, either globally or per library, to not remove files from the DB if the library's root path is not accessible.

**Describe alternatives you've considered**
Don't see any way around this with the current config options, other than disabling and not being able to use the "Folder Watch" option in the libraries. Also thought about getting my monitoring software to make Tdarr failsafe by killing the server process when the remote path was inaccessible/network instability detected, but this felt like overengineering the issue and had potential for DB corruption anyway.

**Comment by HaveAGitGat** [comment]
Hi which Tdarr version were you using for this? Thanks

**Comment by HaveAGitGat** [comment]
They way Tdarr works is it checks if any of the paths in the file path are accessible. If the file is `not` accessible but one of it's parents folder `is` then it will remove the file and vice versa.

For example, with filepath:

`/media/movies/action/test.mkv`

It will check if any these are available:

`/media`
`/media/movies`
`/media/movies/action`

If filepath not accessible and parent accessible then file is removed from Tdarr database.

**Comment by ReeKorl** [comment]
I was running 2.15.01, have just taken this opportunity to update to 2.16.01 though. Library sources are all in the form:

\\hogbrisnasprd01\media\video\foo\bar

Looking at the server logs, there's a huge amount of entries in the space of about a minute around the time of the outage as follows:

[2023-11-26T00:37:34.773] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'
[2023-11-26T00:37:34.779] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'
[2023-11-26T00:37:34.813] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'
[2023-11-26T00:37:34.818] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'
[2023-11-26T00:37:34.828] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'
[2023-11-26T00:37:34.832] [ERROR] Tdarr_Server - error: Error: UNKNOWN: unknown error, stat '\\hogbrisnasprd01\media\'

After further checks, it turns out it wasn't a network outage, there was an unscheduled restart of the NAS. Looks like something maybe went wrong with the path detection code in Tdarr, maybe there's something weird with the way Synology devices respond during restarts that caused things to go screwey?

Want to do some tests on a clean install/small library, can you advise how to turn on more verbose logging?

**Comment by HaveAGitGat** [comment]
Not too sure but you can enable verbose logs on the logs tab in Tdarr, perhaps more info there in future

**Comment by HaveAGitGat** [comment]
Tdarr folder watch uses [chokidar](https://github.com/paulmillr/chokidar) which is used in many products such as [Microsoft's Visual Studio Code](https://github.com/microsoft/vscode), [gulp](https://github.com/gulpjs/gulp/), [karma](https://karma-runner.github.io/), [PM2](https://github.com/Unitech/PM2), [browserify](http://browserify.org/), [webpack](https://webpack.github.io/), [BrowserSync](https://www.browsersync.io/) so it seems it's not designed for the situations your server is being put through. Not much I can do about that as it's supposedly the best folder watch library out there. I'd suggest enabling the `Run an hourly Scan` option which is independent of the the folder watcher and is equivalent to you clicking the Scan (Find new)` button and was added for scenarios like this.
