### ISSUE TITLE
Clarification on flow charts

### ISSUE THREAD

**Issue by niklas2233** [HaveAGitGat/Tdarr#916]
**Is your feature request related to a problem? Please describe.**
kind of but probably only for me lol. Well the problem that im facing is that when i made a flow chart i wanted to make it check what codec the file was so i added the "checkVideoCodec" plugin but when i was trying to choice the output i was met with option 1 or 2
Now i assume that 1 is left and 2 is right but it would be nice if it said "Left: File has codec" and "Right: File does not have codec"

**Describe the solution you'd like**
change the output to left or right instead of 1 and 2. Or if you want to get really fance make it say 1 or 2 when you hover over the output in the flow chart
Maybe you plan on adding more outputs and then i might be useful to use the hover feature instead

**Describe alternatives you've considered**
Hoping that 1 is left and right is 2

**Comment by HaveAGitGat** [comment]
Hi if you double click on the plugin you can see the outputs:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/7adcab04-2f49-4af9-9876-5b5f7c70a9c9)


![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3a3f0eb3-d7ce-483b-9d33-e10073f7fc1d)
