### ISSUE TITLE
Node auto update when server is updated

### ISSUE THREAD

**Issue by erviker** [HaveAGitGat/Tdarr#917]
Node auto update when server is updated to new version.

 i'm running the server in docker with auto update from "Watchtower" on one server and 5 nodes(windows). its mostly just cogging along on its own but especially now that versions updated this fast its becoming a bit of chore to check if the server has updated and then update the nodes

is there a way to nodes to auto update them self to the server version?

**Comment by HaveAGitGat** [comment]
Not an option to do that atm but will be in next version.
