### ISSUE TITLE
Duplicate library with same source folder won't process (with different plugins)

### ISSUE THREAD

**Issue by ejalal** [HaveAGitGat/Tdarr#919]
**Is your feature request related to a problem? Please describe.**
Currently, I process my libraries for audio and video transcodes with different plugins, but sometimes the result of audio transcode produces a bigger file size, sometimes it's the video transcode that produces a bigger one... and the end result produces a smaller file without indicating if any individual transcode (audio or video) had to be cancelled.

I ended up running a first transcode with video only, and reschedule all one again for audio only. The problem with this is that I need to do all transcode again and again if new files are added to my library (sonarr/radarr)

The other option is to duplicate the libraries, one with video transcode plugins, and a duplicate one (same source folder) for audio transcode only... this is ideal as each library will keep track of what's being transcoded or not and refresh itself with new/changed files regularly, but this doesn't seem to work as tdarr refuses to schedule the files from the duplicate lib for transcode (nothing happens)

**Describe the solution you'd like**
Tdarr to allow duplicate libraries with same source folder to be transcoded. And it's our responsability to set different plugins for transcode.

**Describe alternatives you've considered**

**Additional context**

**Comment by ejalal** [comment]
I reated a symlink of the source folder with a different name as a workaround and it looks like it solves my problem

**Comment by HaveAGitGat** [comment]
Can do it that way but may cause strange results if 2 workers process the 2 ‘files’ at the same time.

**Comment by ejalal** [comment]
This seems to work as expected so far, as long as I accept the transcodes manually, worst case could be that one file must be processed again by one or the other lib transcode queue for audio or video as both queues will prevent same transcode type twice (based on transcode stop filters)
