### ISSUE TITLE
Tdarr Unraid Docker

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#92]
Hi there,

I am installing Tdarr on an unraid server in Docker. Can you tell me what the mapping should be set to for the following. Cheers

![image](https://user-images.githubusercontent.com/8785775/70358680-cdb84c80-1871-11ea-8e3d-c272c5e04b07.png)

**Comment by HaveAGitGat** [comment]
Hello, you can map those wherever you like. Most people put the appdata and TdarrDB inside /mnt/user/appdata

The media library is wherever your media is. The cache is wherever you want the transcode cache to be. Example here:

https://camo.githubusercontent.com/fd5d836688cd9f6fd2cb9550dc517d721c44093c/68747470733a2f2f636f64696e672e66726962627461737469632e6e65742f77702d636f6e74656e742f75706c6f6164732f323031392f31312f756e5241494453657474696e67732d312e706e67

**Comment by HaveAGitGat** [comment]
Feel free to re-open if you still need help
