### ISSUE TITLE
When transcoding certains files, Worker stops with : CUDA_ERROR_NOT_INITIALIZED.

### ISSUE THREAD

**Issue by Moses-Tumu** [HaveAGitGat/Tdarr#920]
**Describe the bug**
This only happens on specific files, while most of the others work with no problem.
When transcoding, before it even start doing it's thing, It will stop and the output error will be : `Error while opening decoder for input stream #0:0 : Generic error in an external library`
and above there will be : `cu->cuInit(0) failed -> CUDA_ERROR_NOT_INITIALIZED: initialization error`

**To Reproduce**
Transcodes files in some specific folder

**Expected behavior**
Transcode successfully

**Screenshots**
<img width="1095" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/18294870/28931fad-a3b5-4068-bcb8-15cf6c463e1b">

**Please provide the following information:**
```
2023-12-02T03:25:02.894Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:[Step W07] [C2] Worker [-error-]
2023-12-02T03:25:02.895Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:Error encountered when processing /temp/She's the Man (2006) WEBDL-1080p - h264 AAC-TdarrCacheFile-5V90ewAvR.mp4
2023-12-02T03:25:02.895Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:[1/2] Trying to delete errored cache file /temp/She's the Man (2006) WEBDL-1080p - h264 AAC-TdarrCacheFile-6GBcglJYy0.mkv
2023-12-02T03:25:02.896Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:Subworker exited null
2023-12-02T03:25:04.925Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:[2/2] Delete success
2023-12-02T03:25:04.926Z 4gjeWusp2EX:Node[GTX1070-AC]:Worker[idle-imago]:Updating transcode stats
```
Here is two files that had the issue.
[worker-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13537061/worker-log.txt)
[worker-log-file2.txt](https://github.com/HaveAGitGat/Tdarr/files/13537084/worker-log-file2.txt)

```
Command:
tdarr-ffmpeg -c:v h264_cuvid -i "/temp/She's the Man (2006) WEBDL-1080p - h264 AAC-TdarrCacheFile-5V90ewAvR.mp4" -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 2748k -minrate 1923k -maxrate 3572k -bufsize 5497k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 "/temp/She's the Man (2006) WEBDL-1080p - h264 AAC-TdarrCacheFile-6GBcglJYy0.mkv"
```

 - OS: Unraid 6.12.4
 - Tdarr Version: 2.14.02
 - GPU: GTX 1070
 - CPU: Risen 5 5800X

**Additional context**
As said above, this will only happen with certain files. As of writing, I have 1270 successfully and 700 with errors. At some point I thought it was the same as the issue #895  but I only had 2 going on and even with 1 the error still happened.

If you need additional info, I can provide them.

Thanks in advance.

**Comment by HaveAGitGat** [comment]
If you requeue the files do they still error? It may be that FFmpeg can't handle the files you're trying to process with those arguments. Unfortunately it just gives `generic error` so not too much to go on.

**Comment by Moses-Tumu** [comment]
I tried it, and It still gives this error. It might be something with the files, I will try to isolate the folder with another library and see if it still happens

**Comment by HaveAGitGat** [comment]
Yeah also make sure GPU drivers are up to date but yeah might be that can't handle those files with GPU encoding so perhaps try with CPU encoding. You could create a flow like this which tries GPU then if that fails try CPU encoding

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/02851bd9-9c87-4051-b787-a50570c9aa08)
