### ISSUE TITLE
AV1

### ISSUE THREAD

**Issue by martinkeat** [HaveAGitGat/Tdarr#921]
Firstly, sorry for raising this as a bug report, its more of a lack of info report/ lack of knowledge report.

I have had Tdarr in a container on unraid since you started developing it (yup, im one of them). I've installed an ARC 380 Intel GPU and would like to utilise it with the container to transcode to AV1.

Do you have an existing guide, or can you direct me. Cheers

Martin

**Comment by HaveAGitGat** [comment]
Hi :) if you check the 'Set Video Encoder' flow plugin you should see AV1 available:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/585453f8-5246-461f-9a23-b6214e21eba9)

Let me know if you don't see it.

**Comment by martinkeat** [comment]
Yup. Got it. Now if we can only get unraid to update the kernel to 6.2 with native Intel Arc support, that'd be great..............tumbleweed blows by.

**Comment by unRAIDmonster** [comment]
Consider this guide on unraid.monster https://unraid.monster/showthread.php?tid=88 Requires a 16 core processor and Nvidia RTX 4050-RTX 4090 There may be other videocards that come later that will support this method as well, but as of now the 4090 is the highest card.

**Comment by dennix85** [comment]
The arc a310 for 99 bucks beats the shit out of the 4090
Nvidia cards are good for live streaming but for archival purposes they sucks
I don't touch media with my 4090
I solely use arc gpu's for this purposes
