### ISSUE TITLE
When cancelling worker initiated via a flow plugin ffmpeg continues running in the background

### ISSUE THREAD

**Issue by Rezer** [HaveAGitGat/Tdarr#928]
**Describe the bug**
When a library is configured to use flows rather than classic plugin stacks, cancelling a worker will remove the task from the UI and allow other tasks to begin processing, but tdarr-ffmpeg keeps running in the background and utilizing the same amount of system resources as if the task were still running.

**To Reproduce**
Create the default "Basic HEVC Video Flow".  Set your library to use the flow, and queue a video for transcoding.  Once ffmpeg begins working on the transcode, open the worker info and click "cancel item".  The task is removed from the UI, but CPU utilization stays maxed out.  Running top will show tdarr-ffmpeg is still running, and if another task is started there will be multiple tdarr-ffmpeg processes.

Repeat the above with the library configured to use classic plugins and the tdarr-ffmpeg process does not continue running.

**Expected behavior**
I expect the tdarr-ffmpeg process to be aborted when cancelling a task regardless of how the plugins are configured.

**Screenshots**
About 60 seconds after cancelling (configured to only use 6 out of 8 cores):
![image](https://github.com/HaveAGitGat/Tdarr/assets/1910199/e4f23531-e839-4c71-aae4-4af26618ddba)

- Config files
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13591093/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13591094/Tdarr_Server_Config.json)
Library config: [Library.json](https://github.com/HaveAGitGat/Tdarr/files/13591136/Library.json)
Flow config: [Flow.json](https://github.com/HaveAGitGat/Tdarr/files/13591137/Flow.json)

- Job reports:
Job report from failure: [flow-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13591031/flow-log.txt)
Job report when it's behaving (only switched library from flow to default classic plugin stack, requeued same video) [classic-plugin-stack-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13591034/classic-plugin-stack-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13591140/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13591141/Tdarr_Server_Log.txt)

- Worker error
In either case it just says item was cancelled by user, as expected.

 - OS: TrueNAS SCALE docker image
 - Browser: Firefox
 - Version: 2.16.0.1

**Additional context**
This is on a fresh docker install on TrueNAS SCALE using the 2.16.0.1 image pulled from the Truecharts repo.  The container info is listed as:

docker.io/haveagitgat/tdarr@sha256:a99b336cff141ebca7be6a1740c1ec4438f9927780c00da5ca11acfffd0c7cac

I tried completely clearing the config, logs, and server folders and doing the minimum necessary to get a test transcode running, the behavior was unchanged.

**Comment by HaveAGitGat** [comment]
Hi, fixed here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/569/files#diff-ac8a3ba2d60e8de7e760b38442b7fa4538c0f23b9e99bb69cebab05105054c58

Update your plugins on the plugins tab and should work fine.

**Comment by Rezer** [comment]
Can confirm that took care of it on my end, thanks!

**Comment by HaveAGitGat** [comment]
Great :)
