### ISSUE TITLE
Error with MP4

### ISSUE THREAD

**Issue by Nonobis** [HaveAGitGat/Tdarr#93]
Hello,

I am trying to convert mp4, i have this error on all MP4.
Could you help me ?

Plugins used : 
 - Custom plugin for encoding all track in AAC
 - Tdarr_Plugin_d5d3_iiDrakeii_FFMPEG_NVENC_Tiered_MKV

Error :

/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -c:v h264_cuvid -i '/home/Tdarr/media/movies/Jumanji.mp4' -c:v hevc_nvenc -pix_fmt p010le -rc:v vbr_hq -qmin 0 -cq:v 31 -preset slow -c:a copy -c:s copy '/home/Tdarr/cache/Jumanji-TdarrCacheFile-IGd0sZhhx.mkv'

ffmpeg version N-47683-g0e8eb07980-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2018 the FFmpeg developers

built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516

configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg

libavutil 56. 24.101 / 56. 24.101

libavcodec 58. 42.100 / 58. 42.100

libavformat 58. 24.100 / 58. 24.100

libavdevice 58. 6.101 / 58. 6.101

libavfilter 7. 46.101 / 7. 46.101

libswscale 5. 4.100 / 5. 4.100

libswresample 3. 4.100 / 3. 4.100

libpostproc 55. 4.100 / 55. 4.100

**Unrecognized option 'rc:v'.

Error splitting the argument list: Option not found**

**Comment by HaveAGitGat** [comment]
Hello, which platform are you on? Docker/UnRaid?

**Comment by HaveAGitGat** [comment]
Make sure to turn the NVENC switch ‘ON’ in the Options tab in Tdarr.

**Comment by Nonobis** [comment]
i am on ubuntu server, tdarr is running on Docker

**Comment by HaveAGitGat** [comment]
Did you see my second message? Did turning NVENC on solve the issue?

**Comment by Nonobis** [comment]
My server has crashed yesterday (OS disk HSD ...) so i am currently installing & configuring UnRaid. I will retry with LinuxServer Nvidia for drivers and switch on NVENC settings.... Thanks .. will tell in a few days :) Thks

**Comment by Nonobis** [comment]
ok ..  i have installed unraid with nvidia linuxserver docker. I have activated nvec settings .

Now error is a new one ?

Command:

/home/Tdarr/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg -c:v h264_cuvid -i '/home/Tdarr/Media/movies/Bienvenue à bord.mp4' -c:v hevc_nvenc -pix_fmt p010le -rc:v vbr_hq -qmin 0 -cq:v 32 -preset slow -c:a copy -c:s copy '/home/Tdarr/cache/Bienvenue à bord-TdarrCacheFile-lPdITCZsJ.mkv'

ffmpeg version 3.4.5 Copyright (c) 2000-2018 the FFmpeg developers

built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

configuration: --prefix=/home/z/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/z/ffmpeg_build/include --extra-ldflags=-L/home/z/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/z/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree

libavutil 55. 78.100 / 55. 78.100

libavcodec 57.107.100 / 57.107.100

libavformat 57. 83.100 / 57. 83.100

libavdevice 57. 10.100 / 57. 10.100

libavfilter 6.107.100 / 6.107.100

libswscale 4. 8.100 / 4. 8.100

libswresample 2. 9.100 / 2. 9.100

libpostproc 54. 7.100 / 54. 7.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/Tdarr/Media/movies/Bienvenue à bord.mp4':

Metadata:

major_brand : isom

minor_version : 512

compatible_brands: isomiso2avc1mp41

encoder : Lavf57.83.100

Duration: 01:30:58.60, start: 0.000000, bitrate: 31329 kb/s

Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 31228 kb/s, 25 fps, 25 tbr, 10000k tbn, 0.07 tbc (default)

Metadata:

handler_name : VideoHandler

Stream #0:1(fre): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 95 kb/s (default)

Metadata:

handler_name : SoundHandler

Stream #0:2(fre): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)

Metadata:

handler_name : SubtitleHandler

Cannot load libnvcuvid.so.1

[h264_cuvid @ 0x55d643a14740] Failed loading nvcuvid.

Stream mapping:

Stream #0:0 -> #0:0 (h264 (h264_cuvid) -> hevc (hevc_nvenc))

Stream #0:1 -> #0:1 (copy)

Stream #0:2 -> #0:2 (copy)

Error while opening decoder for input stream #0:0 : Unknown error occurred

**Comment by HaveAGitGat** [comment]
Yeah seems like a new error with the nvenc decoder. I didn’t make this plugin so you might have to do some testing with some nvenc settings and see what works.

**Comment by Nonobis** [comment]
ok, thansk for your time.
I will try to make a custom plugin with the plugin creator or by code ..

**Comment by HaveAGitGat** [comment]
Perhaps try the updated plugin, the creator made some changes 👍

**Comment by HaveAGitGat** [comment]
Please reopen if needed
