### ISSUE TITLE
Hitting rescan made the file disappear from Tdarr

### ISSUE THREAD

**Issue by NicoLeOca** [HaveAGitGat/Tdarr#930]
Hi,
I am setting up Tdarr for the first time and the last few days figuring out what feature does what.
I have an issue with one plugin (Tdarr_Plugin_scha_rename_based_on_codec_schadi), not doing its job as expected.
(side note: another renaming plugin works just fine for me)
I changed the settings of this plugin and wanted Tdarr to reprocess a couple of file (and hopefully rename it).

I went to the Seach tab and hit rescan on specific files.
They just disappeared from Tdarr.
I then went to refresh the library and Tdarr finds all the other files but this ones.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13623393/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13623394/Tdarr_Server_Config.json)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13623410/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13623411/Tdarr_Node_Log.txt)

 - OS: Ubuntu 20.04.6 LTS
 - Browser Firefox
 - Version 120.0.1

**Comment by HaveAGitGat** [comment]
Thanks, fixed for next version.
