### ISSUE TITLE
[ISSUE] Hi i've an error on transcoding 

### ISSUE THREAD

**Issue by TheDestr0yer** [HaveAGitGat/Tdarr#931]
Hi I am having an error in transcoding an entire TV series , seems to be a format error , how can I fix it ?

This is the log: https://pastebin.com/raw/nLgpZBiU

**Comment by HaveAGitGat** [comment]
The report contains the following error:

`Subtitle codec 94213 is not supported`

This means the codec is not supported in the desired file container.
You can remove this subtitle codec by using the following plugin:

`Tdarr_Plugin_MC93_Migz1Remux`

And set the force_conform option to 'true'.
