### ISSUE TITLE
Health check errors when using move/copy to folder (flows)

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr#932]
**Describe the bug**
The end of my current flow looks like this:
<img width="1353" alt="Schermafbeelding 2023-12-16 om 21 06 54" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/24f4f187-8917-40a7-8b39-46fe7157f2d8">

At the end of the flow the original file is copied to another directory and afterwards the original file is deleted with the parent folder. 

Tdarr ALWAYS does a health check after the transcoding has finished. Because it can't find the file the health check will error. 

**I tried to add a health check into the flow think that it would replace the health check after the transcode, but this wasn't true**

I also tried to disable health checks for the libraries which are using the flow, but they will be kept in the health check queue until the health checks are enabled again in the library setting. **So now I'm just not sure what I have to do with this problem so I created this issue, hoping there is a solution or workaround so there won't be any errors.**

**To Reproduce**
Use the Move/Copy to directory plugin in flows with a delete file (and folder) plugin at the end. 

**Expected behavior**
Health checks success instead of error. 

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[configs.zip](https://github.com/HaveAGitGat/Tdarr/files/13693849/configs.zip)

- Job reports: https://docs.tdarr.io/docs/other/job-reports
[kMRbMwfZCo1-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13693850/kMRbMwfZCo1-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[logs.zip](https://github.com/HaveAGitGat/Tdarr/files/13693851/logs.zip)

 - OS: Linux (Synology NAS)
 - Browser: Chrome
 - Version: 2.17.01

**Comment by HaveAGitGat** [comment]
>I also tried to disable health checks for the libraries which are using the flow, but they will be kept in the health check queue until the health checks are enabled again in the library setting

Hi sorry I'm not sure what you mean by this. If you disable the library health checks then they should not be in the queue:

Example:

Health checks enabled for both library 1 and 2:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/963507b0-0068-4415-8dc5-481a603c4273)

Health checks enabled for library 1 and disabled for library 2:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/8bf2e9fe-705b-4335-bf80-fa5dcd6df0e6)

If you have some screenshots of this for you then can look into it thanks.

**Comment by moostmartijn** [comment]
I disabled the library health checks, and they're indeed not in the Health check queue showed in your screenshot, but I use Homepage (https://github.com/gethomepage/homepage), and when I have the Health Checks disabled, the queue on the Homepage Tdarr integration will build up. (in the screenshot it's 0 at this moment (Wachtrij in the picture) because I enabled the health checks) When I enable the Health Checks for the library again, all the transcoded files will do a Health Check and ofcourse they will all fail. So they're somehow in some kind of queue. 

<img width="574" alt="Schermafbeelding 2023-12-18 om 08 32 37" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/89193e67-afdb-4017-9bf1-8fe56981a312">

**Comment by HaveAGitGat** [comment]
Homepage widget needs a slight change so it shows the same as what you see in the Tdarr UI

https://github.com/gethomepage/homepage/pull/2492/files

**Comment by moostmartijn** [comment]
> Homepage widget needs a slight change so it shows the same as what you see in the Tdarr UI
> 
> https://github.com/gethomepage/homepage/pull/2492/files

@HaveAGitGat 
I am on the latest Homepage version (v0.8.7) and the Tdarr widget should show the same as Tdarr UI as you mentioned, but unfortunately it does not. 

I have Health Checks disabled in all my library's, but the Tdarr widget still shows a queue. (if I enable the health checks for my library's it would try to process all the health checks)
<img width="575" alt="Schermafbeelding 2024-02-02 om 20 59 10" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/581159a3-6a08-4fdd-8120-93766d4ad5bd">
<img width="1374" alt="Schermafbeelding 2024-02-02 om 20 59 23" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/c0fc75e1-642d-48c6-8219-d46ccc7cda22">
<img width="692" alt="Schermafbeelding 2024-02-02 om 21 01 52" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/9338fdee-4e75-4d67-85a9-9ce95aab377b">
<img width="688" alt="Schermafbeelding 2024-02-02 om 21 01 43" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/281be737-420e-4865-9e98-bcc9dcdaab53">

(screenshots taken at the same time)

Am I missing something?
