### ISSUE TITLE
Does the transcode cache still need to be shared?

### ISSUE THREAD

**Issue by brayrobert201** [HaveAGitGat/Tdarr#933]
**Is your feature request related to a problem? Please describe.**
Copying from the transcode cache to the library now seems to be done by the node, rather than by the server.

The biggest reason I could see for having a shared temp directory was that the server was handing out tasks (which remains true) and more importantly, was copying the finished product back to the library.

This adds extra complexity to the setup by adding an extra shared filesystem that needs to be configured and connected to. Especially when the library itself is on a separate server to the tdarr devices.

**Describe the solution you'd like**
Allow nodes to use their own transcode cache

This would involve jobs started by X node needing to complete on X node, but overall this seems like a minor thing. Especially for simpler transcode setups (EG: Ones with fewer steps that might need to be handled by a larger farm. I'm OK with stuff remaining in the queue longer if it allows each node to only need to care about the library location)

The server should be able to check the file out on the library once the final transfer has completed. The node is already responsible for sanityh checking that the copy happened successfully.

**Describe alternatives you've considered**
None, really. Anything else (like ceph or gluster so that the server has the ability check some details itself) just increases the complexity of this.

**Additional context**
If this can't be done, I'd like to look at going back to having the server handle the final check and move as it did before.

At least that would bring back serial data transfers and decrease the IOPS, rather than have multiple nodes do their own writes in parallel.

**Comment by HaveAGitGat** [comment]
Gave a breakdown here on how the current system is more efficient:
https://github.com/HaveAGitGat/Tdarr/issues/286#issuecomment-767598515

Would spend a lot more time copying files back and forth from server to node with your suggestion. So it's a case of convenience vs performance.

**Comment by HaveAGitGat** [comment]
Will move this under this issue as is duplicate:
https://github.com/HaveAGitGat/Tdarr/issues/945

**Comment by HaveAGitGat** [comment]
2.27.01 just released adds a new node type 'unmapped' nodes, more info here: https://docs.tdarr.io/docs/nodes/nodes#unmapped
