### ISSUE TITLE
Bump ffmpeg to 6.1

### ISSUE THREAD

**Issue by hskrtich** [HaveAGitGat/Tdarr#934]
**Describe the solution you'd like**
There are a number of updates to the new version of ffmpeg 6.1 that I would love to be able to use!

**Describe alternatives you've considered**
I might be able to manually install a newer ffmpeg version.

**Comment by HaveAGitGat** [comment]
Latest Jellyfin ffmpeg is [6.0.1-1](https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v6.0.1-1) so will bump when new version released.

**Comment by hskrtich** [comment]
Just for anyone else looking for this, it looks like jellyfin ffmpeg wont bump to 6.1 as they are waiting to bump directly to ffmpeg 7
https://github.com/jellyfin/jellyfin-ffmpeg/issues/306#issuecomment-1827451422
