### ISSUE TITLE
Missing Binary: Npm

### ISSUE THREAD

**Issue by ghost** [HaveAGitGat/Tdarr#937]
So hey I am using github codespace and trying to make a discord.js server. But it is saying that npm is missing 
How do I solve this...

**Comment by supersnellehenk** [comment]
Seems this issue is unrelated to Tdarr, but install Node.JS on your system :)

**Comment by Einzi0** [comment]
Ah I'm sorry I opened the issue in the wrong repo

**Comment by HaveAGitGat** [comment]
xD, hope you solved your issue elsewhere.
