### ISSUE TITLE
Shorter cache (temp) working folder and file name or ability to set it manually

### ISSUE THREAD

**Issue by testdasi** [HaveAGitGat/Tdarr#938]
**Is your feature request related to a problem? Please describe.**
When using Tdarr with a Windows node, the path length limit in Windows can cause "file not found" or similar errors if the path length is longer than 255 characters. The new flow-based working folder naming convention makes this more likely to cause issue because they are way too long.

For example:
- Working folder name (61): tdarr-workDir-node-L1p-M631w-worker-evil-eel-ts-1703476631926
- Subfolder (13): 1703476634588
- File name: actual name of file

That is 75 characters wasted just for the folder and sub folder names. Adding path mapping and I'm down to less than 150 characters for file name, which is not much.
To be honest, I don't see the benefit of having "tdarr-workDir-node" AND "evil-eel-ts" AND random number. It's really overdoing it.

**Describe the solution you'd like**
2 potential solutions:
- Ability to set manual working folder name and and working file name. This would be ideal if there's an option to add random text generator.
- Use shorter automatic names e.g. use 8-character alphanumeric random names, no need random number on parent working folder name, etc.

**Describe alternatives you've considered**
Manually rename files that are too long, transcode and then rename it back. Shouldn't need to do this.

**Comment by quadcom** [comment]
Just a note on this issue, it is limited to Windows 10 as Windows 11 has an updated version of explorer that supports up to 32k chars.

**Comment by HaveAGitGat** [comment]
In next version 2.27.01 there will be shorter cache folder names eg. `tdarr-workDir2-L1p-M631w` (28)

**Comment by HaveAGitGat** [comment]
2.27.01 released with shorter cache folder names
