### ISSUE TITLE
New Columns, Sorting, and Column Show/Hide

### ISSUE THREAD

**Issue by ionred** [HaveAGitGat/Tdarr#940]
I'd like to request that new columns (and the associated sorting options) be added to list 

Number of Streams (for each type, video, audio, subtitles)
Audio Codec, 
Audio Channels,
Audio Bitrate
First Subtitle Language

Obviously there are a lot of columns existing so the ability to toggle/show-hide specific columns would need to be likely roped into this request, too. 

My use case is my entire library is already in HEVC but a good deal of it needs to be changed for audio codecs, bitrate, or channel reduction reasons. I also have a few files with multiple subtitle streams or subtitles in the wrong language I plan on stripping out with various plugins.

**Comment by HaveAGitGat** [comment]
Which section do you mean? On the search tab? It already shows some info on streams:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/db648e1b-eac9-4f31-9fe6-1a34860c4561)

Might not be ideal with audio as some videos come with 10+ audio/sub streams which can clutter up the UI a fair bit.

**Comment by HaveAGitGat** [comment]
I'd say this info is already available and can be shown/hidden but let me know if it's not showing for you:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/69a65e16-b38b-43a0-bc62-75545a45661f)
