### ISSUE TITLE
Have a single License reference

### ISSUE THREAD

**Issue by camilosampedro** [HaveAGitGat/Tdarr#941]
First of all, thank you for working on this project. I've been running it in some personal setups and it's great

**Is your feature request related to a problem? Please describe.**
I see different information about the license of the project:

- The homepage has a license that looks a bit restrictive: https://home.tdarr.io/eula
- The repository shows that the project uses an ISC license, with is much more permissive: https://github.com/HaveAGitGat/Tdarr/blob/e67afc73532ba01939d67a720c09900a1e1ae898/package.json#L12
- In the AUR, the configs say that it's a package under the GPL3 license: https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=tdarr

**Describe the solution you'd like**
Synchronize at least the package.json and the website, to make clear to users what is the permitted use of this software.

**Describe alternatives you've considered**
Adding a LICENSE file to the repository, and link everything there ?

**Additional context**
I'm thinking to add support to install this software using Nix, and having a clear license would help organize it better: https://github.com/NixOS/nixpkgs/issues/273459

**Comment by BhasherBEL** [comment]
Indeed, adding a LICENSE file would make it clearer for everyone. This projects _seems_ open-source, while the website says something else, but mentions to closed-source (https://github.com/HaveAGitGat/Tdarr/pull/392) have been removed commits after commits (https://github.com/HaveAGitGat/Tdarr/commit/2701306a2d65dd9dbacab29659b96ed981ea73bf, https://github.com/HaveAGitGat/Tdarr/commit/43baf2ec19efef692b05ca2b8508b72ffd5c77b8, https://github.com/HaveAGitGat/Tdarr/commit/0300c77dd0278d519df6209fc24e9b6f89b4851b).

**Comment by HaveAGitGat** [comment]
It's a bit of a mix as yes the core is closed-source but all the plugins are open source. I'm no lawyer but will have a look into some licensing agreements updates as would not be against it being used in `nixpkgs`.

**Comment by HaveAGitGat** [comment]
I've updated the license here: 

https://github.com/HaveAGitGat/Tdarr/blob/master/LICENSE.md

Pointed the website to it too as you suggested: https://home.tdarr.io/eula

I have no issue with the existing distributors that I know of (Unraid, Truecharts, Chocolatey, ElfHosted, Artifacthub, Qnap, AUR) and can be added to NixOS or can email support@tdarr.io for confirmation. Ty.

**Comment by camilosampedro** [comment]
Thank you for updating the license information
