### ISSUE TITLE
[Question] Is possible to cancel the encoding if the final estimated size is much larger than the initial file?

### ISSUE THREAD

**Issue by Jorman** [HaveAGitGat/Tdarr#943]
Hi, Tdarr is new for me and I'm getting used to using it, I'm doing some testing and I like how it works.
Watching it work I have a question, is there any way to abort the conversion of a file if the estimated final size is larger than the original file? During operation I happen to see that the final size will be 200% and more, maybe I'm wrong but under these circumstances, shouldn't I move on to the next file? Does it make sense to keep converting the whole file? I happen to see these values when the file is 6% converted and going on with the percentage the final estimated size is not much different

Thanks for the program

J

**Comment by HaveAGitGat** [comment]
You can use the `New file size check` classic plugin or the `Compare File Size Ratio` flow plugin to check the size of the file after it's been processing but yes ending the transcoding early once size threshold has been met is still to-do.

**Comment by Jorman** [comment]
Ok, thank you for the information.
Do you plan to insert this function or make no sense for you?

**Comment by HaveAGitGat** [comment]
In Tdarr flows we can do it by modifying this code:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/cliUtils.ts#L123

So during processing if the new file is larger than the original we can exist the thread with an error.

**Comment by HaveAGitGat** [comment]
I'll move this under here as same thing:
https://github.com/HaveAGitGat/Tdarr/issues/571

**Comment by HaveAGitGat** [comment]
Added with flow plugin `Compare File Size Ratio Live`. Click `Update community plugins` on the classic plugins tab or will auto update within an hour or so.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6a9d81e6-5160-462f-bccc-edb6bd737fb8)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0cffff4d-dac7-47d1-a6de-bda993f12739)

Can compare between either the estimated file size or the current file size of the output file.

```
  Compare either the estimated final size or current output size to the input size and 
  give an error if estimated final size or current size surpasses the threshold %.

  Works with 'FfmpegCommand', 'HandBrake Custom Arguments', 'Run Classic Transcode' and other flow plugins 
  that output a file.

  Can be placed anywhere before a plugin which outputs a new file.
```
