### ISSUE TITLE
Change file move step from Server to Node to allow local (to each node) transcode directory vs shared

### ISSUE THREAD

**Issue by texasdaddy** [HaveAGitGat/Tdarr#945]
Current process and methodology as I understand it:

1. Nodes use a shared transcode directory that the server is aware of.
2. All nodes must use this shared directory as the server performs the final file move and rename process.
3. The idea as stated in other requests is to minimize wasted time and bandwidth if a transcode were to fail.

If the final move and rename process were moved to the nodes:

1. A directory mapping could be used on the nodes to allow them to write the transcodes directly to their local file system.
2. The additional steps of the flow or transcode stack would then be performed on the local file system as opposed to over the network.

For example, with a 10 GB file these are the following issues to be resolved with our plugin stack: objects within the container are out of order, needs to be remuxed into a different container, has unwanted audio, has unwanted subtitles, and will be transcoded into x265. We are affectively downloading and uploading the file to the temp shared path 5 times.  With a 50% file reduction between the removed audio and transcode (basic estimates) we are looking at moving 80-90 GB of data.  If the node were handling the file move, there would be a single 10 GB download as the fist step reordered the objects, then a 5 GB final version to upload back to the source.  This would be a drastic improvement in network utilization and potentially allow for faster transcodes where user's hardware capability exceeds their network speeds.

**Comment by HaveAGitGat** [comment]
Sure I have thought of some implementation of this, will add when possible.

**Comment by texasdaddy** [comment]
An alternate option would be to have each node use their own local temp directory to encode into then have a shared mapped “processed” directory that the nodes would write their final processed file into so you don’t have to give the nodes write access to the media storage. Only the server would require it. This would effectively produce the same result and minimize share access risks. Sent from my iPhoneOn Mar 2, 2024, at 12:30 PM, RASG ***@***.***> wrote:﻿
yeah, tdarr is a great tool, but moving the file around is the worst

**Comment by HaveAGitGat** [comment]
Gave an example here of how the current implementation can be more efficient and quicker:
https://github.com/HaveAGitGat/Tdarr/issues/286#issuecomment-767598515

Adding this is still on the to-do though.

**Comment by pokemonfirer** [comment]
glad to see im not the only one who had a idea or use case like this also glad to have a dev willing to look into werid odd use cases for their software

**Comment by HaveAGitGat** [comment]
FYI I have tried this in latest version (2.18.02) and was it was working for me.

So the server and node still need access to the same source, but the node can now have it's own local cache. Just make sure library transcode cache is a valid path on the Node, can use path translators if using multiple nodes across various systems:

https://docs.tdarr.io/docs/installation/windows-linux-macos#path-translators

Worth a try.

This will break a plugin stack where multiple nodes work on the same file as the nodes can't access the same cache file.

**Comment by HaveAGitGat** [comment]
If the node cache is pointed towards a local folder it will not used the shared cache.

**Comment by HaveAGitGat** [comment]
Checked with `supersnellehenk` that this is working. Should work fine in 18.02 unless you're running classic plugins in your flow in which case is working for next version, can try here:

```
docker.io/haveagitgat/tdarr_acc:dev_2.19.01_2024_05_22T08_09_41z
docker.io/haveagitgat/tdarr_node_acc:dev_2.19.01_2024_05_22T08_09_41z

https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.19.01/linux_x64/Tdarr_Server_2024_05_22T08_09_41z.zip
https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.19.01/linux_x64/Tdarr_Node_2024_05_22T08_09_41z.zip
```

**Comment by HaveAGitGat** [comment]
2.19.01 released

**Comment by texasdaddy** [comment]
I guess I'm doing something horribly wrong with my deployment.  I've
updated to 2.19.01 and tried updating my "/temp" mappings from the network
share to a path local to each node, and all transcodes fail to copy back to
the appropriate media folder on completion.  I see the files re-encode into
the local directory and the plugin stack complete, but everything fails to
copy.

**Comment by abartov** [comment]
Same here, using 2.19.01. Copy failed with ENOENT, even though the file certainly exists and is copyable.

**Comment by ShawnHardwick** [comment]
I have Tdarr nodes running over VPN and they would benefit greatly from this. Not only from a bandwidth standpoint, but also because constant SMB traffic over moderate latency is terrible for performance. A single download and a single upload would improve performance.

**Comment by pokemonfirer** [comment]
> I have Tdarr nodes running over VPN and they would benefit greatly from this. Not only from a bandwidth standpoint, but also because constant SMB traffic over moderate latency is terrible for performance. A single download and a single upload would improve performance.

as someone whos hosting a node for someone in this setup i can say it works well also join the tdarr discord for more help

**Comment by HaveAGitGat** [comment]
2.27.01 just released adds a new node type 'unmapped' nodes, more info here: https://docs.tdarr.io/docs/nodes/nodes#unmapped
