### ISSUE TITLE
Ability to use MKVmerge for Remuxing instead of Ffmpeg

### ISSUE THREAD

**Issue by dhenry437** [HaveAGitGat/Tdarr#946]
**Is your feature request related to a problem? Please describe.**
I am experiencing an issue with certain HVEC MP4 files stuttering in plex, but not when playing in VLC as described [here](https://www.reddit.com/r/PleX/comments/r0hhkw/anything_encoded_with_hevc_main_10_video_stutters/). Using MKVmerge to remux the files to MKV fixes them (this [powershell script)](https://github.com/DistantWindow/PlexPals/blob/main/StutterFix/remux-inPlace.ps1), but if I remux using Tdarr's method of Ffmpeg, the stuttering remains.

**Describe the solution you'd like**
I would like to be able to use MKVmerge to remux. I'm not sure if I can call a shell command in a custom plugin and I imagine this would be a solution. Otherwise if Tdarr had a native way of using MKVmerge, I'd love to use that.

**Describe alternatives you've considered**
As mentioned above a plugin *might* be able to call a shell command, at the moment I'm finding it hard to get an answer to that.

**Comment by HaveAGitGat** [comment]
Can add a plugin to run binaries, will just need to reuse the code from here:
https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/CommunityFlowPlugins/tools/runMkvPropEdit/1.0.0/index.ts

**Comment by Maypul** [comment]
I would also love to see it. I'd like to use mkvmerge with custom commands and last week I was trying to find a way to do so which was not that successful.

**Comment by HaveAGitGat** [comment]
I've created this plugin here to allow running of other CLIs like mkvmerge:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/630

Hope that helps.
