### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by nicholus-h** [HaveAGitGat/Tdarr#947]
**Describe the bug**
Can't get the tdarr server to start at all. The web / GUI never comes up (site can't be reached).

**To Reproduce**
1. installed via portainer / docker compose. Used this [example compose file](https://docs.tdarr.io/docs/installation/docker/run-compose#compose), commented out the NVIDIA lines because they caused errors (have an Intel with QSV). My actual docker config is attached below as a text file.
2. compose the stack, attached to console (via portainer), lots of output as the server keeps attempting to restart. An example is attached as a text file.

**Expected behavior**
Web GUI to start up.

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: n/a

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error: n/a

 - OS: Linux (Ubuntu)
 - Browser chrome
 - Version - latest per GitHub

**Additional context**
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13883490/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13883491/Tdarr_Server_Config.json)

[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13883497/Tdarr_Node_Log.txt)
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/13883499/Tdarr_Server_Log.txt)
[Tdarr_Server_Console Output.txt](https://github.com/HaveAGitGat/Tdarr/files/13883937/Tdarr_Server_Console.Output.txt)

[dockercompose.txt](https://github.com/HaveAGitGat/Tdarr/files/13883512/dockercompose.txt)
[Tdarr_Server_Console Output.txt](https://github.com/HaveAGitGat/Tdarr/files/13883513/Tdarr_Server_Console.Output.txt)

**Comment by Jomack16** [comment]
Looks like a permissions issue: 
from Tdarr_Server_Console Output.txt
Error: EACCES: permission denied, mkdir '/app/server/Tdarr'

I am not too fluent in linux permissions or group syntax, but I think these lines might be messed up.
      - PUID=1000
      - PGID=$1000
      - UMASK_SET=002
At the very least, the $ in PGID value looks wrong.

**Comment by nicholus-h** [comment]
> Looks like a permissions issue: from Tdarr_Server_Console Output.txt Error: EACCES: permission denied, mkdir '/app/server/Tdarr'
> 
> I am not too fluent in linux permissions or group syntax, but I think these lines might be messed up in your dockercompose.txt. - PUID=1000 - PGID=$1000 - UMASK_SET=002 At the very least, the $ in PGID value looks wrong.

nailed it. thanks for helping my stupid ass.
