### ISSUE TITLE
Linux install instructions ?

### ISSUE THREAD

**Issue by Zixim** [HaveAGitGat/Tdarr#95]
This looks very promising.

Is there any change of maybe revisiting the Linux install wiki so that they actually work ?
I tried in a Debian 10 and got hopelessly stuck half-way through,
then tried a Ubuntu 18.04, and something is very wrong with the paths I think.

**Comment by Zixim** [comment]
I spent some time making this, for Debian 10 : 

### Install some dependencies, create user.
as root : 
```apt update && apt dist-upgrade
# apt install -y sudo gnupg apt-transport-https lsb-release handbrake-cli git-core p7zip-full
# adduser Tdarr --force-badname
# usermod -a -G sudo Tdarr
```
### Login as the newly created user.
Make directory where video files will reside.
`$ mkdir -p ~/media`

### Install MongoDB and run as a service  and at startup
```
$ wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
$ echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
$ sudo apt-get update && sudo apt-get install -y mongodb-org
$ sudo systemctl enable mongod.service
$ sudo systemctl start mongod
```
### Download and install NodeJS 8
```
$ wget -qO - https://deb.nodesource.com/setup_8.x | sudo bash -
$ sudo apt install -y nodejs
```
### Download and extract the relevant Tdarr Linux release archive ###
```
$ cd ~/
$ wget  https://github.com/HaveAGitGat/Tdarr/releases/download/v1.101-Beta/Tdarr-Linux-v1.101-Beta.7z
$ 7z x /home/Tdarr/Tdarr-Linux-v1.101-Beta.7z -o/home/
  *if prompted to overwrite select (A)lways
  *there will be an error : `ERROR: Can not delete output folder : No such file or directory : /home/Tdarr/bundle/programs/server/npm/node_modules/nodegit/vendor/libgit2/tests/resources/status/?`
    ...but never mind...
$ rm Tdarr-Linux-v1.101-Beta.7z
```
### Create service to run at startup ###
`$ sudo nano /etc/systemd/system/tdarr.service`
paste : 
```
[Unit]
Description=Tdarr - Audio/Video Library Analytics & Transcode/Remux Automation
Documentation=https://github.com/HaveAGitGat/Tdarr
After=mongod.service
Wants=mongod.service

[Service]
Environment=MONGO_URL=mongodb://localhost:27017/Tdarr
Environment=PORT=8265
Environment=ROOT_URL=http://localhost/
Type=simple
User=Tdarr
ExecStart=/usr/bin/node /home/Tdarr/bundle/main.js
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
Enable the newly created service to start at boot :
`$ sudo systemctl enable tdarr.service`
reboot
open browser to http://<ip-of-tdarr>:8265/

**Comment by Zixim** [comment]
@HaveAGitGat I referenced this in the wiki, hope that's OK with you?

**Comment by HaveAGitGat** [comment]
@Zixim yes that’s fine, appreciate it thanks.

**Comment by marshalleq** [comment]
Why don't we just incorporate the instructions?  I can do that if you like.

**Comment by pefman** [comment]
Followed these instructions on a buster install, but i am receiving the following error whenever i try to call the included ffmpeg.

/home/media/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory

**Comment by pefman** [comment]
> Followed these instructions on a buster install, but i am receiving the following error whenever i try to call the included ffmpeg.
> 
> /home/media/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory

solved by the following.

cd /tmp
wget http://www.sndio.org/sndio-1.2.0.tar.gz
tar -xf sndio-1.2.0.tar.gz
cd sndio-1.2.0
./configure
make
make install
ldconfig

tdarr should be able to read the necessary lib now

**Comment by pefman** [comment]
now getting the following... /home/media/Tdarr/bundle/programs/server/assets/app/ffmpeg/ffmpeg42/ffmpeg: error while loading shared libraries: libx265.so.179: cannot open shared object file: No such file or directory

trying to find a solution

**Comment by pefman** [comment]
if you are on buster you need to enable repository

deb http://debian.lth.se/debian/ sid main    
deb-src http://debian.lth.se/debian/ sid main
apt update
apt install libx265-179
then disable the repositories again and voila it should work.

DO NOT do an apt upgrade!

**Comment by Zixim** [comment]
I stopped trying to get Tdarr working on plain linux since release 102.
Docker seems to be the preferred way to install. 😞

**Comment by pefman** [comment]
> I stopped trying to get Tdarr working on plain linux (deb/buster) since release 102.
> Docker seems to be the preferred way to install.

I feel you! i got mine working finally it think. Docker is a good tool, but honestly i try to keep my server running with as little complexity as possible.

**Comment by Zixim** [comment]
I'm running a Proxmox server, Docker is not an elegant option in this case.
Usually manually running the dockerfile is all that you need to do to install onto Linux. Don't know why this isn't working with Tdarr.

**Comment by rtrevino70** [comment]
> if you are on buster you need to enable repository
> 
> deb http://debian.lth.se/debian/ sid main
> deb-src http://debian.lth.se/debian/ sid main
> apt update
> apt install libx265-179
> then disable the repositories again and voila it should work.
> 
> DO NOT do an apt upgrade!

Thnks!!  

now its working!

**Comment by deathbybandaid** [comment]
Getting Tdarr setup on Ubuntu 20.04 was a huge deal easier than on Debian 10 (Buster).

There were still a few dependencies I had to work out, but I've been running Tdarr for months in Proxmxox LXC.

Not only that, but WITH passthrough access to my Nvidia Quadro P2000 which is shared with Emby and Plex.

I will note, I made one tweak to the systemd service file

````
EnvironmentFile=/home/Tdarr/tdarr-env
````


tdarr-env
````
MONGO_URL=mongodb://localhost:27017/Tdarr
PORT=8265
ROOT_URL=http://localhost/
````


This made it more like a "config file", which to me feels better than `systemctl daemon-reload` if I want to make changes here.

**Comment by EricHupp** [comment]
If you are having trouble getting the previous .service file working here is one that I made in Ubuntu 18.04 
Basic info from deathbybandaid 

Install dir is /opt/Tdarr

vi /opt/Tdarr/tdarr.env or whichever editor you use.

MONGO_URL=mongodb://localhost:27017/Tdarr
PORT=8265
ROOT_URL=http://localhost/

save and quit 

vi /etc/systemd/system/tdarr.service

[Unit]
Description=Tdarr - Audio/Video Library Analytics & Transcode/Remux Automation
Documentation=https://github.com/HaveAGitGat/Tdarr
After=network.target


[Service]
EnvironmentFile=/opt/Tdarr/tdarr-env
#Environment=MONGO_URL=mongodb://localhost:27017/Tdarr
#Environment=PORT=8265
#Environment=ROOT_URL=http://localhost/
Type=simple
User=root
Group=root
ExecStart=/usr/bin/node /opt/Tdarr/bundle/main.js
Restart=on-failure

[Install]
WantedBy=multi-user.target

[Install]
WantedBy=multi-user.target

**Comment by kysersoze81** [comment]
I found that I needed to add 
deb http://deb.debian.org/debian/ oldstable main contrib
deb http://deb.debian.org/debian/ unstable main contrib
into /etc.apt.sources.list

Then run

```
apt update
apt install libx265-179
apt install libsndio6.1
```

Then go back and # out the unstable line from /etc/apt/sources.list

Then run
`
apt clean`

Debian Buster (10)  'also running as a Proxmox LXC

**Comment by Commissar0617** [comment]
Node.js 8.x LTS Carbon is no longer actively supported!

looks like they're on 12.0 now.
