### ISSUE TITLE
Please add optiong to accept % in Set video bitrate in Tdarr Flows(not just fixed bitrate)

### ISSUE THREAD

**Issue by adamgwaps** [HaveAGitGat/Tdarr#950]
Title says it all

**Comment by risb0r** [comment]
This would be nice to have!

**Comment by HaveAGitGat** [comment]
Could be added but main issue that sometimes/often (depending on the files you have) the video bitrate is not available so would need to decide what to do in that case

**Comment by risb0r** [comment]
Possible to have a fallback value in that case?

**Comment by HaveAGitGat** [comment]
Yeah could do it like that, some of the other plugins try to use the overall file bitrate so could fallback to that too.

**Comment by HaveAGitGat** [comment]
Added here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/623

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3c07cf69-3552-46e9-acb2-6d98b93e4b5c)


![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9c82e336-ffd7-4ee2-b71d-49e9d26a333d)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dffa6ee9-e682-4704-bb9f-f295ef038ccf)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/e4c1443e-1ca8-4285-ad3e-f97344b3f5df)
