### ISSUE TITLE
"Check If File Name Includes" Flow Shape ignores last term in certain situations

### ISSUE THREAD

**Issue by RobLaw0304** [HaveAGitGat/Tdarr#952]
**Describe the bug**
When many terms are specified, the last search term appears to be ignored

**To Reproduce**
Create checkFileNameIncludes in a flow and connect it to input file
Enter the following into the "Terms" box without quotes: "Special Victims Unit, Saturday Night Live, Wicked Tuna, Smallville, Shameless (US), The Simpsons, Life Below Zero, Bones (2005)"
Queue file named "Z:/Videos/TV Shows/Bones (2005) {imdb-tt0460627}/Season 04/Bones (2005) - S04E02 - Yanks in the U.K. 2 [AMZN WEBDL-1080p][EAC3 5.1][h265].mkv"
Observe that checkFileNameIncludes returns output 2
Change "Terms" box to this without quotes: "Special Victims Unit, Saturday Night Live, Wicked Tuna, Smallville, Shameless (US), The Simpsons, Life Below Zero, Bones (2005), "
requeue the same file
Observed that checkFileNameIncludes returns output 1

**Expected behavior**
checkFileNameIncludes should return output 1

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/13998314/Tdarr_Server_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports
[Incorrect Result.txt](https://github.com/HaveAGitGat/Tdarr/files/13998308/Incorrect.Result.txt)
[Workaround Result.txt](https://github.com/HaveAGitGat/Tdarr/files/13998309/Workaround.Result.txt)

 - OS: Linux Server, Windows Node
 - Browser Chrome
 - Version 2.17.01

**Additional context**
This error affected all similarly named files, it was not limited to just the examples shown. Adding the comma worked around the issue. Escaping the parentheses was ineffective as well.

**Comment by HaveAGitGat** [comment]
This is because there is a space before `Bones (2005)` in the filter, so the term it's checking is ` Bones (2005)`. 

I assume some people want to check for exact terms including spaces so that's why it doesn't auto remove them.
