### ISSUE TITLE
Error starting Cmd: fork/exec */runtime/Tdarr_Server_Runtime: no such file or directory

### ISSUE THREAD

**Issue by machiavelli8** [HaveAGitGat/Tdarr#953]
**Describe the bug**
After running Tdarr_Server I get error:
Error starting Cmd: fork/exec */runtime/Tdarr_Server_Runtime: no such file or directory

I installed nodejs, npm, and the other dependencies listed on the site.

**To Reproduce**
Run: `./Tdarr_Server`

**Expected behavior**
Expecting for it to start without issue.

**Screenshots**
N/A

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
```
{
  "serverPort": "38089",
  "webUIPort": "38088",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "/usr/bin/ffmpeg",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
}
```

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
```Loading...
/home/media/Tdarr_Server/Tdarr_Server
Running in console
Found Tdarr entry file:/home/media/Tdarr_Server/srcug/main.js
ExeDir:/home/media/Tdarr_Server
AppsDir:/home/media
IcoPath:/home/media/Tdarr_Server/assets/favicon.ico
NodeExePath:/home/media/Tdarr_Server/runtime/Tdarr_Server_Runtime
MainJsPath:/home/media/Tdarr_Server/srcug/main.js
LogLocation:/home/media/logs
ModuleName:Tdarr_Server
IsProd:true
IsTray:false
ExePath:/home/media/Tdarr_Server/Tdarr_Server
WebUIPort:8265
Error starting Cmd: fork/exec /home/media/Tdarr_Server/runtime/Tdarr_Server_Runtime: no such file or directory
```

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Raspberry Pi 4B+
```PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Additional context**
N/A

**Comment by HaveAGitGat** [comment]
Did you check the runtime exists at: `/home/media/Tdarr_Server/runtime/Tdarr_Server_Runtime` ?
Try giving it execution permission (this should be done automatically by Tdarr_Updater when you run that):

`chmod +x /home/media/Tdarr_Server/runtime/Tdarr_Server_Runtime`

**Comment by HaveAGitGat** [comment]
Re-open if needed thanks.
