### ISSUE TITLE
Tdarr doesn't see mounted folders (not what you think)

### ISSUE THREAD

**Issue by v-giannakopoulos** [HaveAGitGat/Tdarr#954]
**Describe the bug**
I use Synology DSM. I have 2 of them. They are both set up the same way. Same config. I am running Tdarr 2.17.01 in both of them. 

Through docker i have mounted 2 folders. In both DSMs the same and the same names. I have given to the image the highest privileges. On DSM1, everything works fine. No problems. On DSM2, When i set up a library, it does not see the mounts inside the mapped folders. I thought it was my fault. I logged in through SSH to the docker image and not only i can see the mounts mounted, i can also browse the files.

I am baffled. 

What can i check? where can i check? Any ideas or guidance would be greatly appreciated.

**Comment by HaveAGitGat** [comment]
Try enabling verbose logs on the logs tab and then run a fresh scan. Might be some useful info in there about what files it sees.

**Comment by v-giannakopoulos** [comment]
OK so i found what was wrong. I fixed it the wrong way because i don't know better but here is what i found:
* The folders are mounted
* The folders are not seen by Tdarr
* When I log in to the docker image, i can see the content (as root). 
* If i change the owner to the user within the docker, the issue goes away
* If i add "everyone" on the shared folder within synology, the user in the docker image can see as well
So what i would like to know, is how not to use "everyone" and what is the best practice way to give appropriate rights instead of down chown -R user

**Comment by HaveAGitGat** [comment]
You can see here there are PUID and PGID for the container:
https://docs.tdarr.io/docs/installation/docker/run-compose#run

```

-e PUID=1000 and -e PGID=1000 are Docker environment variables used when running Docker containers.

Specifically:

-e PUID=1000 sets the user id (UID) inside the container to 1000. This is often used to match the host user's UID if you want the container to write files that are owned by the same user on the host.
-e PGID=1000 similarly sets the group id (GID) inside the container to 1000, again often used to match the host user's primary GID for file permissions.
Setting these variables ensures the container runs as the specified user/group ID rather than root, for improved security. The values 1000 are just common defaults and can be customized as needed.
```
