### ISSUE TITLE
[Library] disabled because the Health Checks switch is OFF in the library settings

### ISSUE THREAD

**Issue by kramttocs** [HaveAGitGat/Tdarr#955]
Version 2.17.01. Server and node running on Windows 11

I have Health Checks turned off for one library and I get this Warning Message about the Queue

Warning: Some libraries are disabled from processing
Clicking it gives me: [my library name] disabled because the Health Checks switch is OFF in the library settings

It still processes though

**Comment by HaveAGitGat** [comment]
Just checking but might you have had 2 libraries with the same name? Did you try restarting Tdarr server process?

**Comment by kramttocs** [comment]
Welcome back!

I've restarted a few times since then but it is possible when testing I had a library I created and then deleted. So the library I think it is, may not be it.
Is there a file I could look at to see if it's a stick reference somewhere?

**Comment by HaveAGitGat** [comment]
:)

Could try checking the `Tdarr/DB2/LibrarySettingsJSONDB` folder to check if the old library is still hanging around. Each library is a separate file and you can see the name within the file.

**Comment by kramttocs** [comment]
Does look like it's anything in there.
If I go to that library and turn Health Checks on the message goes away (within 5 seconds) so it looks like it's correctly tied to it.

Of course when doing so all the Transcode queue items move to the health check item queue :)

**Comment by kramttocs** [comment]
Additionally, is there a way to remove the Info on queue counts warning?

![image](https://github.com/HaveAGitGat/Tdarr/assets/11565750/143324ed-8a19-4e70-9c88-593a39060e09)

**Comment by HaveAGitGat** [comment]
The queue counts warning shows if there are files in the queue but all of them have been disabled due to library settings options (e.g. schedule, setting process to off, disabling transcode/health check etc) or all of them are in the staging section. There's currently no way to disable the warning (it was added as some people were forgetting why their items weren't processing).

**Comment by kramttocs** [comment]
So it's showing as a matter of the erroneous first error? Am I understanding that correctly?
If you have a library with more files than your workers but you have the health check turned off for it, do you see the 'disabled from processing' message like I am?

![image](https://github.com/HaveAGitGat/Tdarr/assets/11565750/70250dff-b0c6-48b3-b0a2-c4e061db5599)

Does the 'Library 2' give us any clue? Even if the number started at 0, this library is in order 4 and was, I am sure, created after the other three.

![image](https://github.com/HaveAGitGat/Tdarr/assets/11565750/9711f34b-82ab-4e33-9afb-1d5cdb8d0d13)

**Comment by kramttocs** [comment]
I've never turned the relay feature on but if it would help in anyway, happy to do so.

**Comment by HaveAGitGat** [comment]
Reopen if still have the issue on `2.20.01` thanks
