### ISSUE TITLE
Allow multiple Values in 'Check Flow Variable'.

### ISSUE THREAD

**Issue by risb0r** [HaveAGitGat/Tdarr#958]
Issue
Unable to nominate numerous values for 'Check Flow Variable' flow block.

Goal
Enable comma separated values to be added to the value section to enable greater control without adding an unnecessary amount of flow blocks.

Troubleshooting
From the logfile;
It would appear that the correct library id is being utilised and/or referenced and would have likely been successful if it were a single value condition to meet.

`Variable args.librarySettings._id of value **Bmu55n2Pr** does not match condition == eZU21m8v4,6nerhMTQB,**Bmu55n2Pr**,ljDF5r_G9,ANCAuvSQJ,8y0WeTWSN,qDIVW9a3U,LFBa38mhq,lBY-fKDey,jRcoVtrd7`
Note: **stars don't exist, used for highlighting only**

![image](https://github.com/HaveAGitGat/Tdarr/assets/16470277/ebe6cd18-343a-4440-a208-e1d84b88a44a)
![image](https://github.com/HaveAGitGat/Tdarr/assets/16470277/ebe2935c-ad39-4fa9-9b06-ee79bfe2c47a)

**Comment by risb0r** [comment]
Somewhat resolved using custom variables, although this would be a nice feature.

**Comment by HaveAGitGat** [comment]
I see, I suppose you could also achieve this by connecting multiple `Check Flow Variable` flow plugins but that's a bit tedious. Will look into adding this.

**Comment by risb0r** [comment]
Yes, I did start doing that which became infuriating haha which is then when I started looking for alternative options and came across the custom variables.

**Comment by HaveAGitGat** [comment]
Sure can add this but suppose it only really makes sense for the `==` condition.

**Comment by HaveAGitGat** [comment]
Added here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/624/files#diff-6c455e4fc0afb4569f66a1e26829a05ac9a9fb1a9ae2db751aa5cbf89e9f1529
