### ISSUE TITLE
GPU doing CPU tasks, and vice versa

### ISSUE THREAD

**Issue by my95z34** [HaveAGitGat/Tdarr#959]
I just converted over to flows today. I'm having it rescan and attempt to convert files that had failed before. One thing I have noticed is that my GPU is doing all of the normal CPU tasks. And a current transcode that should be NVENC is being converted using the CPU. In the node options I do NOT have "Allow GPU workers to do CPU tasks" enabled, yet it's still doing them. Tasks such as reordering streams, cleaning audio, cleaning subtitles, etc.

My current flow: https://imgur.com/4sQU2GX

Node status: https://imgur.com/ZZOga23

Showing that it's doing the NVENC using the CPU: https://imgur.com/buQ4K2t

Copy of the log for a file transcoding on the CPU: https://hastebin.com/share/kucaretidu.swift

Any guidance as to what I have set up wrong here?

 - OS: Unraid (docker)
 - Browser: Chrome
 - Version 2.17.01

**Comment by my95z34** [comment]
After doing a little bit of research, it looks like there is no worker designation for flows like there is for plugins.  It just grabs the first available worker and runs.  Is that correct?

**Comment by HaveAGitGat** [comment]
Yes that's right, with flows it's the idea that there's logic in the flow that will give a CPU worker CPU related transcode args and a GPU worker GPU transcode related args. For example using the 'Encode Video' plugin has logic within it to do this. The classic plugins do not have this logic so might be the case that a CPU worker runs GPU args or vice versa. You can use the `Check Node Hardware Encoder` flow plugin so that when GPU hardware is available it will do GPU transcoding. Can also use the `Check Flow Variable` to check the worker type and act accordingly.

**Comment by my95z34** [comment]
> Yes that's right, with flows it's the idea that there's logic in the flow that will give a CPU worker CPU related transcode args and a GPU worker GPU transcode related args. For example using the 'Encode Video' plugin has logic within it to do this. The classic plugins do not have this logic so might be the case that a CPU worker runs GPU args or vice versa. You can use the `Check Node Hardware Encoder` flow plugin so that when GPU hardware is available it will do GPU transcoding. Can also use the `Check Flow Variable` to check the worker type and act accordingly.

I'm not sure I'm following. When I use classic plugins, are correctly using gpu and cpu workers. The cpu workers will do audio cleaning, subtitle cleaning, etc. And the gpu will only do transcoding. But when I set up the flows, no matter what I tried cpu and gpu would both do the same tasks. Cpu would be transcoding, even tho it was specified to be NVENC. And gpu would be doing subtitle and audio cleaning. It was just grabbing whatever worker was available, not caring about whether it was cpu or gpu.

I will look into the check node hardware encoder stuff when I get a chance. Could you elaborate on it?

**Comment by HaveAGitGat** [comment]
@CurlyFlow yes that will be added soon, the system is mostly in place under the hood already.

**Comment by HaveAGitGat** [comment]
This template has been added:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/9051148f-5247-4279-a9ec-306936522c13)

Let me know if you need any more help.

**Comment by my95z34** [comment]
@HaveAGitGat I appreciate that.  Just out of curiosity, how would I arrange that flow so that it would try to convert the video using NVENC, and if it fails, then try CPU, and if that fails, then just fail?  I'm having a mental block....

**Comment by my95z34** [comment]
> as far as i see he posted a flow already... (but didnt i tried)

The one that was just posted?  As far as I can tell, from my limited experience with flows, all that is doing is checking the worker type that is available and then transcoding using that worker.  There is no failure plan.

**Comment by HaveAGitGat** [comment]
@my95z34 you try the gpu transcode and then connect the error handle to the cpu plugin:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/12ac9b49-a0dd-4b1d-aaf5-0b6917df83a1)

<details>
  <summary>Flow Example</summary>
{
  "name": "Basic HEVC Video Flow",
  "description": "Basic HEVC Video Flow",
  "tags": "",
  "flowPlugins": [
    {
      "name": "Input File",
      "sourceRepo": "Community",
      "pluginName": "inputFile",
      "version": "1.0.0",
      "id": "pE6rU7gkW",
      "position": {
        "x": 758.5809635618224,
        "y": 117.19206188888086
      }
    },
    {
      "name": "Check if hevc",
      "sourceRepo": "Community",
      "pluginName": "checkVideoCodec",
      "version": "1.0.0",
      "id": "91b7IrsEc",
      "position": {
        "x": 672.4549563302081,
        "y": 253.11148102973914
      }
    },
    {
      "name": "Replace Original File",
      "sourceRepo": "Community",
      "pluginName": "replaceOriginalFile",
      "version": "1.0.0",
      "id": "4fkfOyR3l",
      "position": {
        "x": 820.4549563302082,
        "y": 742.2114810297393
      }
    },
    {
      "name": "Run Classic Transcode Plugin GPU",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "id": "cyhNCt1ih",
      "position": {
        "x": 386.9480559951306,
        "y": 423.3493807189681
      }
    },
    {
      "name": "Run Classic Transcode Plugin CPU",
      "sourceRepo": "Community",
      "pluginName": "runClassicTranscodePlugin",
      "version": "1.0.0",
      "id": "wtmaZzr3E",
      "position": {
        "x": 545.0613029173174,
        "y": 518.1139988993492
      },
      "inputsDB": {
        "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz1FFMPEG_CPU"
      }
    }
  ],
  "flowEdges": [
    {
      "source": "pE6rU7gkW",
      "sourceHandle": "1",
      "target": "91b7IrsEc",
      "targetHandle": null,
      "id": "HhF4rw2DZ"
    },
    {
      "source": "91b7IrsEc",
      "sourceHandle": "1",
      "target": "4fkfOyR3l",
      "targetHandle": null,
      "id": "W2nVG7ts5"
    },
    {
      "source": "91b7IrsEc",
      "sourceHandle": "2",
      "target": "cyhNCt1ih",
      "targetHandle": null,
      "id": "ZWX9rMuJZ"
    },
    {
      "source": "cyhNCt1ih",
      "sourceHandle": "1",
      "target": "4fkfOyR3l",
      "targetHandle": null,
      "id": "hLYGZziuF"
    },
    {
      "source": "cyhNCt1ih",
      "sourceHandle": "err1",
      "target": "wtmaZzr3E",
      "targetHandle": null,
      "id": "HpKUPIW52"
    },
    {
      "source": "wtmaZzr3E",
      "sourceHandle": "1",
      "target": "4fkfOyR3l",
      "targetHandle": null,
      "id": "FfJSMv1Je"
    }
  ]
}
</details>

**Comment by my95z34** [comment]
@HaveAGitGat  Using the flow you just shared, I'm still getting the weirdness where CPU is running the GPU transcode, and vice versa.

<img width="1097" alt="tdarr" src="https://github.com/HaveAGitGat/Tdarr/assets/3894231/a01a9907-7303-45eb-b254-e60cd810e514">

**Comment by my95z34** [comment]
> @HaveAGitGat Using the flow you just shared, I'm still getting the weirdness where CPU is running the GPU transcode, and vice versa.
> 
> <img alt="tdarr" width="1097" src="https://private-user-images.githubusercontent.com/3894231/329600366-a01a9907-7303-45eb-b254-e60cd810e514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDk3NDUsIm5iZiI6MTcxNTM0OTQ0NSwicGF0aCI6Ii8zODk0MjMxLzMyOTYwMDM2Ni1hMDFhOTkwNy03MzAzLTQ1ZWItYjI1NC1lNjBjZDgxMGU1MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTM1NzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdlZGU5NTg5OTUwNTQwOTRkYmYwMjIzZjVhZDUwN2FmYmFmNmY0NmY4ZWZiNmY1NTY0NDBlZTE3NjU3Nzg1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MBYFPg8QhgaOsgMkRKCY-lpvtD1TU29OfxuTTBm4C1Q">

Although, looking at the FPS, maybe it is using the GPU even though it says CPU, and whatnot.  I'm so damn confused, lol

**Comment by HaveAGitGat** [comment]
The flow in my last message is not for CPU/GPU worker differentiation, it was for your question of how to attempt a GPU transcode and then if that fails fallback to CPU transcoding. You need to use the flow further up for CPU/GPU worker differentiation.

**Comment by my95z34** [comment]
> The flow in my last message is not for CPU/GPU worker differentiation, it was for your question of how to attempt a GPU transcode and then if that fails fallback to CPU transcoding. You need to use the flow further up for CPU/GPU worker differentiation where the flow is checking the worker type at the beginning. You can combine both flows.

Oh, gotcha.

Well, I'm sorry to be so needy, but could you help me with that part? I guess I don't understand where the worker check would go, in relation to the failure line. I'm sorry! 🤦🏼‍♂️

**Comment by my95z34** [comment]
I guess my difficulty in understanding comes with how each step is performed.  Does one worker go down each step until completion, or does the flow evaluate each step individually and assign, potentially, a different worker at each step?

**Comment by TheChilliPL** [comment]
I have a similar problem. I really want my GPU to perform only video transcoding, and for my CPU to do everything else. That way it's way faster, cause instead of waiting 2 hours for my CPU to transcode a single video, it takes like 10 minutes. How can I do that with flow?

**Comment by HaveAGitGat** [comment]
Should much more straightforward to do this now. You can use the ‘Worker Type’ flow plugin before your gpu encoding blocks, set it to require a GPU worker, then use it again to require a CPU worker for your non-GPU stuff. That way you can have specific flow blocks run on specific worker types or nodes with the node tag system. Has been working very well for people I’ve had feedback from over the last 6 weeks or so.

**Comment by julienchabanon** [comment]
I have the same issue. Plugins works and uses my gpu but the flow does not. I tried several default flow template including the "new" default made in this thread. In my docker compose I only defined GPU workers. The flow want to use cpu everytime and if I disable cpu from the flow, transcode report says sit need a GPU and exit the task.

**Comment by HaveAGitGat** [comment]
@julienchabanon which plugins are you using? Check the job report https://docs.tdarr.io/docs/other/job-reports

It should tell you why it's not using GPU or can take a look if you want.
