### ISSUE TITLE
Multithread file copy

### ISSUE THREAD

**Issue by kramttocs** [HaveAGitGat/Tdarr#960]
I am transcoding a lot (200k) of small files so the CPU process is outpacing the file copy process. Would be nice to having multiple copies going at the same time. Admittedly, probably not a normal use case...

**Comment by supersnellehenk** [comment]
You can use Flows, where each worker will handle the copy on its own instead of the global staging section where the server does one at a time.

**Comment by kramttocs** [comment]
Interesting. This specific library is super simple so would likely be a good time to try Flows. Thanks
