### ISSUE TITLE
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'

### ISSUE THREAD

**Issue by flybrys** [HaveAGitGat/Tdarr#961]
**Describe the bug**
Some of my video files fail near the end of the transcode with "Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scale_0'".
This tends to happen around the 90ish % mark of the transcode on about 5% of my content.

**To Reproduce**
Use the "Boosh-Transcode using QSV GPU & FFMPEG" plug-in for QSV transcoding.

**Expected behavior**
I expect the transcode to complete successfully like the majority of my other files

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Server: 
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14134844/Tdarr_Server_Config.json)
Node:
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14134847/Tdarr_Node_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports
[0MWaODjK6Nk-log.txt](https://github.com/HaveAGitGat/Tdarr/files/14134862/0MWaODjK6Nk-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/14135009/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/14135016/Tdarr_Node_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
Not sure what this is asking for sorry.

 - OS: Linux (Using Docker container in Unraid from Apps)
 - Browser: Edge
 - Version 121.0.2277.83 

**Additional context**
CPU is i7-13700 (non-k)
I have had a look for similar issues but couldn't see anything directly similar. I could try deleting and redownloading these files however I'd prefer to make sure my set up is correct before doing so.
I am still using the classic plug-in stack

**Comment by Boosh1** [comment]
Possible this is in the wrong place but spotted it. There's a new version awaiting approval here - https://github.com/HaveAGitGat/Tdarr_Plugins/pull/584
Feel free to grab it and see if it works for you.

**Comment by flybrys** [comment]
@Boosh1 You're right, I didn't realise the plug-ins were in a separate repo. Let me know if I should close this and re-open in the plug-ins repo.

Not sure if it's the correct way to do it, but I copied and pasted the raw new code to replace the local copy of the plug-in and ran it again.

Very strange - The transcode runs and finishes, but still ends back in Error/Failed. However this time, all the Job Report History is deleted except for a health check which runs after the failure.

**Comment by HaveAGitGat** [comment]
Closing as boosh changes were merged last month.
