### ISSUE TITLE
windows server error 4066 EMFILE too many files open

### ISSUE THREAD

**Issue by feltz916** [HaveAGitGat/Tdarr#962]
**Describe the bug**
My server has been having problems doing most file operations. Copying files from my transcode cache, running mediainfo, etc. Getting the following errors:

[2024-02-06T21:23:51.349] [WARN] Tdarr_Server - FFprobe was unable to extract any data from this file:
[2024-02-06T21:23:51.945] [ERROR] Tdarr_Server - { result: 'error', error: {} }
[2024-02-06T21:23:52.222] [ERROR] Tdarr_Server - [Error: EMFILE: too many open files, open

[2024-02-06T21:25:20.844] [ERROR] Tdarr_Server - Error running MediaInfo 3
[2024-02-06T21:25:20.844] [ERROR] Tdarr_Server - EMFILE: too many open files, open

The thing that does not make sense, is that the transcodes are working correctly on the node client.

**To Reproduce**
Its been this way for awhile now, and not sure when it started.

**Expected behavior**
There should be no errors, and files should be copied.

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14189529/Tdarr_Server_Config.json)
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14189531/Tdarr_Node_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports
[MUMh1Gmff-log.txt](https://github.com/HaveAGitGat/Tdarr/files/14189553/MUMh1Gmff-log.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Server_Log.zip](https://github.com/HaveAGitGat/Tdarr/files/14189568/Tdarr_Server_Log.zip)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Windows 10
 - Browser Chrome
 - Version 2.17.01
- Storage : QNAP 

**Additional context**

**Comment by feltz916** [comment]
ended up being a authentication problem with my NAS, while running the server as administrator :(

**Comment by feltz916** [comment]
guess it wasn't related to auth, and its due to node.js and windows file io limits:
https://github.com/nodejs/node/issues/44832

**Comment by HaveAGitGat** [comment]
Have you tried running the Docker container on Windows? Might solve your issue

**Comment by feltz916** [comment]
yes i gave up on windows, and moved to a docker image.

**Comment by HaveAGitGat** [comment]
Ok thanks for the update, I haven't encountered this on Windows myself but can troubleshoot if needed in future by checking subprocesses in task manager on Windows and at what point the error occurs after starting up.
