### ISSUE TITLE
Docker - No capable devices found

### ISSUE THREAD

**Issue by HexRebuilt** [HaveAGitGat/Tdarr#964]
**Describe the bug**
I'm unable to use the GPU transcoding feature with an Nvidia P400. the logs says that No capable devices found, even if it should be capable of transcoding nvenc

**To Reproduce**

1. install ubuntu server 22.04
2. install nvidia drivers for the p400, docker and nvidia toolkit
3. add the shares from truenas, checking that the container can touch the files
4. try to transcode and pass the afternoon looking for a fix

**Expected behavior**
the transcoding should be flawless like with the a4000 

**Screenshots**
Log attatched for the transcodings
Faield transcode.
[Failedtranscoding.txt](https://github.com/HaveAGitGat/Tdarr/files/14223472/Failedtranscoding.txt)
FFmpec NVENC output
[FFmpeg_NVENC.txt](https://github.com/HaveAGitGat/Tdarr/files/14223480/FFmpeg_NVENC.txt)
Handbrake NVENC output
[Handbrake NVENC.txt](https://github.com/HaveAGitGat/Tdarr/files/14223500/Handbrake.NVENC.txt)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14223518/Tdarr_Node_Config.json)
[Tdarr_Server_Config.json](https://github.com/HaveAGitGat/Tdarr/files/14223519/Tdarr_Server_Config.json)

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
Log attatched for the transcodings
Faield transcode.
[Failedtranscoding.txt](https://github.com/HaveAGitGat/Tdarr/files/14223472/Failedtranscoding.txt)
FFmpec NVENC output
[FFmpeg_NVENC.txt](https://github.com/HaveAGitGat/Tdarr/files/14223480/FFmpeg_NVENC.txt)
Handbrake NVENC output
[Handbrake NVENC.txt](https://github.com/HaveAGitGat/Tdarr/files/14223500/Handbrake.NVENC.txt)
Server logs:
[Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/14223535/Server-log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: ubuntu server
 - Browser chrome
 - Version 2.17.01

**Additional context**
After some instabilities with Tdarr in another VM, were it was supposed to use both the p400 and A2000, i was not able to use either gpus for any work if the server was running. plex, steam or ollama were not able to access the gpu or files.

**Comment by HaveAGitGat** [comment]
Here are the arguments used:
```
-c:v h264_cuvid, -map 0 -c:v hevc_nvenc -cq:v 19 -b:v 6418k -minrate 4492k -maxrate 8343k -bufsize 12837k -spatial_aq:v 1 -rc-lookahead:v 32 -c:a copy -c:s copy -max_muxing_queue_size 9999 -pix_fmt p010le -bf 5 
```

Most likely due to the `-bf 5` argument. I don't thing the p400 supports bframes
