### ISSUE TITLE
No Tdarr Nodes detected.

### ISSUE THREAD

**Issue by JolleyMi800** [HaveAGitGat/Tdarr#966]
I was running into issues when using TDARR, so, I decided to uninstall it from Unraid and reinstall from scratch.
There is now only one Unraid app for TDARR that says Node included, there is not a sperate app that says TDARR Node.
How do I connect the node now that it says it there isn't one. Before there was a second Unraid app to install it from.

**Comment by finder39** [comment]
<img width="963" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/518673/88827cfa-c220-4703-bb4a-5c5b9d62d034">

Make sure you set Internal Node to true. By default it is false

**Comment by JolleyMi800** [comment]
Thank you!!! I feel absolutely stupid that I over looked that...

> <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/518673/305527724-88827cfa-c220-4703-bb4a-5c5b9d62d034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDcxODcsIm5iZiI6MTcwODE0Njg4NywicGF0aCI6Ii81MTg2NzMvMzA1NTI3NzI0LTg4ODI3Y2ZhLWMyMjAtNDcwMy1iYjRhLTVjNWI5ZDYyZDAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNTE0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTMzMTAzYTk1ZmY3MTBlNjI0NzRjNjgyNThhNjc2NmRlYTg0MDMxZDRhNTc2ZmVkM2MxMmE5Y2E1OTA3ZTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kK7zyLXAyjorlowVzblwXGukpOvfitO0XmKi2vB0-CY">
> Make sure you set Internal Node to true. By default it is false

**Comment by finder39** [comment]
All good! I installed this for the first time yesterday and ran into the same issue. Took me a bit to figure out 🙃
