### ISSUE TITLE
Have node responsible for the transcode perform the subsequent healthcheck following transcode

### ISSUE THREAD

**Issue by risb0r** [HaveAGitGat/Tdarr#967]
I'd like to see an option to have the node responsible for the transcode perform the health check/file check following the end of the job. This would be useful in situations where various nodes are working from the same rclone mount remotely however they don't all update immediately. 

My interim solution is to add a delay to my flow to allow time for the file to propagate across all mounts on all systems however sometimes it's still not enough notwithstanding adding upwards of 300second delays which causes a nuisance delay in processing the queue.

**Comment by HaveAGitGat** [comment]
You could also run a health check from within the flow which results in the same worker/node would processing it.

**Comment by risb0r** [comment]
Does this then negate any subsequent Healthchecks following a completed flow in this case.

**Comment by HaveAGitGat** [comment]
No the flows are their own separate thing atm, suppose could add an option on the health check flow plugin to update the queues/stats so then the non-flow health check system doesn't re-run it.

**Comment by HaveAGitGat** [comment]
Added for next version: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/647/files

So items which are checked as healthy in the flow will go into Health Check: Healthy table so don't need to recheck them.

**Comment by HaveAGitGat** [comment]
2.19.01 released
