### ISSUE TITLE
Add option to ignore case to checkFileExtension plugin

### ISSUE THREAD

**Issue by bluej007** [HaveAGitGat/Tdarr#969]
**Is your feature request related to a problem? Please describe.**
I use the checkFileExtension plugin in flows to handle file extensions differently, and the current plugin sees **mkv** and **MKV** as different extensions though they are the same.

**Describe the solution you'd like**
Add a toggle or checkbox option to this plugin so it'll ignore case.

**Comment by HaveAGitGat** [comment]
Updated here:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/622

Didn't add a toggle as Tdarr is cross-platform and on Windows it's not possible to have both a lower and upper case extension for the same file.
