### ISSUE TITLE
Don't allow silly folder paths

### ISSUE THREAD

**Issue by Zixim** [HaveAGitGat/Tdarr#97]
So whilst exploring the installation I managed to create this `transcode cache` path  : 
`/home/Tdarr/bundle/programs/server/Path to your transcode cache. Input a base folder and the folder browser below will show subfolders to navigate./`

```
root@tdarr:~# ls -lha '/home/Tdarr/bundle/programs/server/Path to your transcode cache. Input a base folder and the folder browser below will show subfolders to navigate./'
total 26M
drwxr-xr-x 2 Tdarr Tdarr   3 Dec  8 12:41  .
drwxr-xr-x 8 Tdarr Tdarr  22 Dec  8 12:41  ..
-rw-r--r-- 1 Tdarr Tdarr 26M Dec  8 12:52 'window - 0002-TdarrCacheFile-LsD_sRCB.mkv'
root@tdarr:~#
```
Perhaps a default value should be set, or at least a sanity-check should be performed ?

**Comment by HaveAGitGat** [comment]
@Zixim there should be a little notification under the source/cache/output paths when you enter an invalid folder.  It says:

“Invalid folder”

**Comment by Zixim** [comment]
well yes, the notification is there, but the wonky path gets saved & used regardless.
I guess it is no biggie, as long as Tdarr is in beta.

I just wanted to let you know.

**Comment by HaveAGitGat** [comment]
I don’t think this is an issue. None of the programs I use check this. Not even Plex. I just added a random folder ‘/ahjdkdjne’ to Plex and it went through fine and that application has been around for 10 years.

There may be times when it is not possible for Tdarr to validate a folder exists, but the folder exists (for example with some virtual machine/symlink/permission scenario). In this case the user should still be able to specify what seems to be an incorrect folder. Hence Plex and other programs allow this and it makes sense for Tdarr to allow it as well.

**Comment by Zixim** [comment]
well, a placeholder then ?

**Comment by HaveAGitGat** [comment]
Yes good idea 👍

**Comment by HaveAGitGat** [comment]
Placeholders added in 1.102
