### ISSUE TITLE
Rebooting Triggers Requeue

### ISSUE THREAD

**Issue by nichols89ben** [HaveAGitGat/Tdarr#971]
Second time this has happened this week, rebooting my system triggers a partial requeue of movie library ~1300 files. Restoring the json files from a day or so ago fixes it, but rebooting again today requeued them. Same library, same node, same docker container. Ive made flow edits, but the library remains the same as well as the saved history. 

 - linux, docker, version 2.17.01

[Server-log.txt](https://github.com/HaveAGitGat/Tdarr/files/14503783/Server-log.txt)

**Comment by andrasmaroy** [comment]
I've ran into a similar issue as well. I've recently requeued my whole library for transcoding resulting in a queue of ~4000 files, after the server restarted only a fraction of the files remained in the queue (~100), most is marked as transcode successful, but they only have a successful healthcheck done when looking at the report.

Regardless of the behaviour being the opposite of OP, this seems to me to be the same issue with the database.

**Comment by HaveAGitGat** [comment]
Could this be due to Tdarr starting up and scanning before network drive has fully connected? Causing files to be removed and then re-added?

**Comment by nichols89ben** [comment]
> Could this be due to Tdarr starting up and scanning before network drive has fully connected? Causing files to be removed and then re-added?

Its possible, my media drives are 2 20tb unified with mergerfs. However ive had the same set up for a little over a year without issues. I got tired of it requeuing so I just let it run through the chunk again. Didn't fix the root issue but it stopped it from requeuing after that for now.

**Comment by andrasmaroy** [comment]
> Could this be due to Tdarr starting up and scanning before network drive has fully connected? Causing files to be removed and then re-added?

I'm mounting media with nfs, so I don't think so.

**Comment by nichols89ben** [comment]
Hasn't happened again, will repost if it does

**Comment by nichols89ben** [comment]
Hasn't happened again, will repost if it does
