### ISSUE TITLE
Update docs page Plugins -> Flow Plugins -> Basics

### ISSUE THREAD

**Issue by JohnnyDeeee** [HaveAGitGat/Tdarr#974]
(i'm skipping the issue template as this is really simple and doesn't require much explanation)

Not sure if this is the right place but i couldn't find a specific repo for the docs hosted at https://docs.tdarr.io

The url underneath the text `Each plugin is passed an args object which you can see the interface for here:` is pointing to the wrong line.
This is the current url: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/interfaces/interfaces.ts#L92
I think it should be: https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/FlowPluginsTs/FlowHelpers/1.0.0/interfaces/interfaces.ts#L112-L170
Or even better, use a commit blob so it will never change (if that is preferred): https://github.com/HaveAGitGat/Tdarr_Plugins/blob/0cb9e75a53727d52cc5f3e44796cb6e7a5699403/FlowPluginsTs/FlowHelpers/1.0.0/interfaces/interfaces.ts#L112-L170

**Comment by HaveAGitGat** [comment]
Thanks, yeah would have been due to modifications, added permalink ty.
