### ISSUE TITLE
Copying File Stuck at 0 Bytes

### ISSUE THREAD

**Issue by dimaTrinh** [HaveAGitGat/Tdarr#978]
**Describe the bug**
After successful transcodes, files are not copied over to the output folder. 

**Expected behavior**
After transcoding, file is copied over to transcode output

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/43079118/920a0764-304a-43e4-a056-f07b9ede1d34)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43079118/aad166db-5666-4fc6-9a3b-e203c4117961)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43079118/7c652ea2-e870-4341-be11-70991d2ca720)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
```
2024-03-18T16:09:36.448Z Km6g-_r1V:Node[BEST_NODE_EVER]:Worker[loud-loon]:Successfully updated server with verdict: transcodeSuccess
2024-03-18T16:09:36.451Z Km6g-_r1V:[Step S02] Beginning move/copy operation
2024-03-18T16:09:36.451Z Km6g-_r1V:Calculating old and new sizes of the following files
2024-03-18T16:09:36.451Z Km6g-_r1V:/media/transcodeFolder/shogun.2024.s01e03.dv.hdr.2160p.web.h265-successfulcrab.mkv
2024-03-18T16:09:36.451Z Km6g-_r1V:/temp/shogun.2024.s01e03.dv.hdr.2160p.web.h265-successfulcrab-TdarrCacheFile-E3Sbu5LTn.mkv
2024-03-18T16:09:36.451Z Km6g-_r1V:Old size 5.875278073363006. New size 5.927393044345081
2024-03-18T16:09:36.451Z Km6g-_r1V:Folder to folder conversion is on
2024-03-18T16:09:36.451Z Km6g-_r1V:New file path /media/transcodeOutput/shogun.2024.s01e03.dv.hdr.2160p.web.h265-successfulcrab-TdarrCacheFile-wzWbxtwC-D.mkv
2024-03-18T16:09:36.451Z Km6g-_r1V:Ensuring output folder path exists /media/transcodeOutput
2024-03-18T16:09:38.452Z Km6g-_r1V:Spawning move thread
```

 - OS: Linux
 - Browser: Chrome
 - Version: 2.13.01

**Comment by supersnellehenk** [comment]
![Arc_HbK6JKNoZO](https://github.com/HaveAGitGat/Tdarr/assets/25726058/285fd7b5-0ebc-4936-a6c6-73f23f53acce)
One is copying, so I think your disks/network is just slow.

**Comment by dimaTrinh** [comment]
> ![Arc_HbK6JKNoZO](https://private-user-images.githubusercontent.com/25726058/313794806-285fd7b5-0ebc-4936-a6c6-73f23f53acce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODY3NDcsIm5iZiI6MTcxMDc4NjQ0NywicGF0aCI6Ii8yNTcyNjA1OC8zMTM3OTQ4MDYtMjg1ZmQ3YjUtMGViYy00OTM2LWE2YzYtNzNmMjNmNTNhY2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4MjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMzM2MWRkZWQzZGNjNWYwMjNkMzMxZjdkYmMzMDkxOGZkMjg5NzI3ZWEyZDNkOTIxMTM5ODZhMDEyNjE4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-sC8795wk1X4zNl0iYWwF1Gu3Ju7Pz7NdeuNUbISwlI) One is copying, so I think your disks/network is just slow.

It has been like this for over one night, and it has never happened like this before, so I think there is an issue here but no errors are being thrown :\

**Comment by HaveAGitGat** [comment]
@dimaTrinh have you tried restarting Tdarr server? It should retry the copy. Perhaps something caused the copy to hang.

**Comment by dimaTrinh** [comment]
> @dimaTrinh have you tried restarting Tdarr server? It should retry the copy. Perhaps something caused the copy to hang.

I tried restarting Tdarr server multiple times. Tried a fresh reinstall and restore using backup from Tdarr. Everything works well up until the copy part :(

**Comment by dimaTrinh** [comment]
> I also get alot of 0 byte files in my output directory... and sonarr is like yeah lets import that! (the checkbox for that file is ticked when manual import)
> 
> Im not quite sure when this happens, but i guess it happens when it try to work on a file which isnt there anymore... i try to find out more.

It's the same thing with me. I can see the files being fully transcoded in the temporary transcode folder, but the copying just do no go through and I am stuck with 0 byte files in my output folder

**Comment by supersnellehenk** [comment]
@CurlyFlow that job report indicates the file moved successfully to `/mnt/user/downloads/completed/Serien/Vikings.S03E04.Gezeichnet.German.DL.DTS.1080p.BluRay.AVC.REMUX-Black/black-avc-vikings.s03e04.mp4`, as the destination and cache file matched in size. Did you share the wrong job report?

**Comment by supersnellehenk** [comment]
I do notice the folder changes from `/mnt/user/downloads/neu/Serien` to `/mnt/user/downloads/completed/Serien`, have you checked that new path using a file browser? I'm not entirely sure of your path mappings, could you share those?

**Comment by supersnellehenk** [comment]
I don't really know what's happening, but from the node perspective the copy went okay. On the server side it is suddenly 0 bytes, so it sounds like either your IO is failing or there's a mapping issue.

**Comment by dimaTrinh** [comment]
> Okay, ive tested now for some days.
> 
> It doesnt seem to have anything to do with replace original file or move to directory.
> 
> For me it startet working 100% after i did my mappings different (before they were not wrong, but different).
> 
> **Currently everything happens under one share /mnt/user/name/ linked to /mnt/user/name/** so i just have one mapping for that instead of e.g. /mnt/user/name/new to /mnt/user/name/new
> 
> Atm im using **/mnt/user/name**/new/A **/mnt/user/name**/new/B **/mnt/user/name**/completed/A **/mnt/user/name**/completed/B **/mnt/user/name**/cache/tdarr
> 
> That seems to work just fine. ![image](https://private-user-images.githubusercontent.com/43281991/320848974-3c71f09b-2b8f-4cb8-8b5d-6f5cd374cb6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2ODYxNDMsIm5iZiI6MTcxMjY4NTg0MywicGF0aCI6Ii80MzI4MTk5MS8zMjA4NDg5NzQtM2M3MWYwOWItMmI4Zi00Y2I4LThiNWQtNmY1Y2QzNzRjYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE4MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NzM1MzMwMGI3OTc0ZjFlZWJiMjIxZjhhNGExOGI0NDYzNDFmZDhmZmIyMWFjZDY0ODU1OGJjOTk4MTJlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MR0Nsr7YByq8y4xeIbXv87d-qwm2_n5Uau5KxSA5yvc)
> 
> So probably a unraid quirk...

Thank you, this also worked for me :) I switch all my tdarr folders to belong to a different location, and it works normally now. Closing the issue
