### ISSUE TITLE
Dictate common local plugin path

### ISSUE THREAD

**Issue by nichols89ben** [HaveAGitGat/Tdarr#979]
Just a thought, it would be nice if you could specify a path for the local plugins like your able to add the path for the Community plugins repository. Reason, I run a few different docker instances for organization purposes and use the same custom plugins in each. I was making edits then copy/replacing them but I found a workaround to make a single plugin directory and bind mounted it to the local folder for plugins in each.

**Comment by HaveAGitGat** [comment]
It's the same:
https://github.com/HaveAGitGat/Tdarr_Plugins

When you set the `pluginsDir` env var it sets the location of both Community and Local plugins.

Other way is to use the `Sync plugins` button on the classic plugins tab which will sync the plugin changes to the Nodes. So hit that after each edit.

**Comment by nichols89ben** [comment]
Got it, so I can add pluginsDir=/shared/plugin/directory for each instance, it will look there for all the plugins?

**Comment by HaveAGitGat** [comment]
Yeah although that's just meant for dev purposes when working on new plugins. Might cause weird results with lots of nodes using it as they will be trying to update the same folder/files when the plugins update runs. 

Add a `.git` folder to the plugins folder to disable plugin updates which will fix the potential update conflicts but means you won't get the latest community plugin updates.
