### ISSUE TITLE
Space Saved inaccurate after a bad /etc/fstab config

### ISSUE THREAD

**Issue by arcreigh** [HaveAGitGat/Tdarr#981]
Made an error when setting up my /etc/fstab for my fileshares mounts. So after a reboot tdarr was aware of all the file locations but was unable to do anything as it could no longer see the files. This resulted in files being reported as 0 Bytes going through the transcode pipeline failing since they didn't exist to the perspective of the tdarr_server docker container and then skewing the results of the statistics. 

Each of these files instead of going to the failed transcodes section was sent to successful / not needed.
Is there any historical tracking in the DB / a way to manually set the Space Saved statistic back to an accurate number?

**Comment by HaveAGitGat** [comment]
Theres's no per-file history kept, it's just a single overall value and values per-library. You can edit the `sizeDiff` value in `server\Tdarr\DB2\StatisticsJSONDB` and `LibrarySettingsJSONDB`.
