### ISSUE TITLE
Flow "Review" vs Plugin Stack "Accept" behavior with "Auto accept successful transcodes"

### ISSUE THREAD

**Issue by coyodi** [HaveAGitGat/Tdarr#983]
**Is your feature request related to a problem? Please describe.**
Sometimes when adding new content/libraries I prefer to review transcodes before overwriting the old file, sometimes not. However, since I use a Flow for my Library Transcoding Decisions, I've noticed that the "Auto accept successful transcodes" option under Staging Section does not apply to Flows with a Require Review node. This option functions correctly while using a Plugin Stack.

**Describe the solution you'd like**
Ideally, I'd like for that checkbox to also respect the "Require Review" node. Auto-Accepting/Reviewing and adding content to the library when it is checked, and awaiting my Review/Acceptance when not checked.

**Describe alternatives you've considered**
Currently, I have to update my Flow each time I want to change this behavior which is not ideal. Even if a new node for "Request Accept" was added to the Flow menu, that'd be perfectly workable for my needs. :)

Thank you for the support!

**Comment by HaveAGitGat** [comment]
I guess wasn't sure whether to apply this behaviour but yes makes sense in that case. I've updated it for next version. Also added a pop-up with this info:

```
Auto accept successful transcodes:


Enabling this option will auto-accept successful transcodes waiting in the staging section.

If using Flows, it will auto accept items which have staging status "Review required" caused by the "Require Review" flow plugin.
```

**Comment by HaveAGitGat** [comment]
2.18.01 released
