### ISSUE TITLE
Unable to create a node on a second machine (Ubuntu)

### ISSUE THREAD

**Issue by malaki86** [HaveAGitGat/Tdarr#986]
It's easier if I start this over LOL

I cannot get the path translations to work, no matter what I've tried. Below are my path layouts, including the fstab for the shared folders. I have full access & permissions to both Unraid shared folders. The Tdarr server sees the node instantly.

Unraid v6.12.10 (Tdarr server latest stable runs in Docker):
  Docker:
    /tmp/tdarr : /temp  (transcode cache)
    /mnt/user : /media
  Shared:
    /mnt/user : /rootshare
    /tmp : /ramdriveshare

Ubuntu 22.04.4 (Tdarr node latest stable in Docker):
  Docker:
    /mnt/media : /media
    /mnt/tmp : /temp
  Path translation:
    { "server": "/mnt/media", "node": "/mnt/media"},
    { "server": "/temp","node": "/mnt/tmp"}
  Fstab:
    //192.168.1.5/rootshare /mnt/media cifs guest,uid=1000 0 0
    //192.168.1.5/ramdriveshare/tdarr /mnt/tmp cifs guest,uid=1000 0 0

Errors from log @ node startup:
[2024-04-21T14:02:51.316] [INFO] Tdarr_Node - Starting Tdarr_Node
[2024-04-21T14:02:51.316] [INFO] Tdarr_Node - Preparing environment
[2024-04-21T14:02:51.317] [INFO] Tdarr_Node - Path translator: Checking Node path: /mnt/media
[2024-04-21T14:02:51.330] [ERROR] Tdarr_Node - Path translator: Error: Node path cannot be accessed: /mnt/media
[2024-04-21T14:02:51.330] [INFO] Tdarr_Node - Path translator: Checking Node path: /mnt/tmp
[2024-04-21T14:02:51.335] [ERROR] Tdarr_Node - Path translator: Error: Node path cannot be accessed: /mnt/tmp

**Comment by HaveAGitGat** [comment]
Hi @malaki86, keep in mind the path translators are from the server and node perspective which in this case are running inside a Docker container. So neither can access `/mnt/media` as that's not available in the containers.

You don't need path translators in this case as the Docker mapping can take care of everything.

Server Docker mapping:
```
/mnt/user : /media
/tmp : /temp (transcode cache)
```

Shared:
```
/mnt/user : /rootshare
/tmp : /ramdriveshare
```

```
//192.168.1.5/rootshare /mnt/media cifs guest,uid=1000 0 0
//192.168.1.5/ramdriveshare /mnt/tmp cifs guest,uid=1000 0 0
```

Node Docker mapping:
```
/mnt/media : /media
/mnt/tmp :  /temp (transcode cache)
```

So both for both server and node `/media' and `/temp` are pointing to same location so no path translation needed.

**Comment by HaveAGitGat** [comment]
Let me know if you have any trouble.
