### ISSUE TITLE
Remote node toggle

### ISSUE THREAD

**Issue by pokemonfirer** [HaveAGitGat/Tdarr#987]
**Is your feature request related to a problem? Please describe.**
Poor performance when useing a remote node (aka WAN basied node)

**Describe the solution you'd like**
ideally by buffering of some form as a toggle to basically tell the node "hey your a remote node work slightly different" a possible way but that kinda breaks the normal operation would be telling the node to take the file and make a local copy work on it and send it back in chunks to the server

**Describe alternatives you've considered**
None that i can think of

**Additional context**
link from discord suggestion-descussion
https://discord.com/channels/623392507828371476/631120844550176768/1226141086309941289

**Comment by HaveAGitGat** [comment]
Will move this under here ty:
https://github.com/HaveAGitGat/Tdarr/issues/945
