### ISSUE TITLE
Helm Chart for Kubernetes Clusters

### ISSUE THREAD

**Issue by CaptainRedHat** [HaveAGitGat/Tdarr#990]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a working helm chart for easy installation and configuration on kubernetes clusters. This is especially helpful considering a lot of managed k8s solutions (AKS, EKS, GKE, etc.) support adding GPU nodes to the cluster.

**Describe the solution you'd like**
I'd like a helm chart that supports current (v1.26+) versions of kubernetes. My use case in particular would be installing the tdarr server on a Rancher RKE cluster running RKE k8s v1.27.10. The tdarr workers would be able to run either internal or external to the cluster. The workers within the cluster would work the same as other docker workers, where the hardware is passed through to the container. It would be up to the end user to manage external workers, but they would connect to the tdarr server through either a kubernetes ingress, a load balancer, or a node port.

**Describe alternatives you've considered**
I've tried some third party helm charts, but all of them are either out of date or don't function as intended. I've considered building my own helm chart, but I'm not familiar enough with Tdarr to know what all configuration items need to be set. 

**Additional context**
Kubernetes (k8s) is an orchestration tool for managing container based workloads.
Helm is effectively the industry standard for installing applications on kubernetes clusters. It's often referred to as a package manager for k8s.
Rancher is a management tool for deploying and managing k8s clusters. It's especially useful for managing k8s clusters in an on-premise datacenter.

I'd be happy to help test and debug the helm chart, but as I stated before, I simply don't know enough about Tdarr's architecture to build a widely-usable helm chart from the ground up.

**Comment by HaveAGitGat** [comment]
I haven't used Kubernetes or Helm charts so not familiar with this. The container variables can be found here though:
https://docs.tdarr.io/docs/installation/docker/run-compose

**Comment by HaveAGitGat** [comment]
What's the issue with the TrueCharts Helm Chart? https://artifacthub.io/packages/helm/truecharts/tdarr

It's kept up to date automatically e.g. https://github.com/truecharts/charts/pull/22137
