### ISSUE TITLE
Pass trough Dolby Vision metadata attributes from ffprobe

### ISSUE THREAD

**Issue by matthijsvrenswoude** [HaveAGitGat/Tdarr#992]
For a Dolby Vision specific transcoding plugin I am writing, I need to know if a file has Dolby Vision metadata. When running the ffprobe on a DV video file in CMD with the following command "ffprobe -v error -show_streams -show_format -show_data -print_format json -pretty filename", it has extra attributes which aren't available when in Tdarr.

The output on the DV file looks like this.
![ffprobe DV output](https://github.com/HaveAGitGat/Tdarr/assets/21951789/619a921f-c11d-4e45-9d91-9b63873560e3)

What I need is the previous-shown attributes: "extradata", "extradata_size" and most importantly all the data in "side_data_list" available in tdarr plugins.

And the tag "encoder" to also pass along.

See image below:

![Feature request](https://github.com/HaveAGitGat/Tdarr/assets/21951789/23064e7f-b0c3-4eaf-86a3-5534c5a42352)

**Comment by HaveAGitGat** [comment]
This has been added for next version, can try it now using:

```
docker.io/haveagitgat/tdarr_acc:dev_2.18.01_2024_05_09T08_07_55z
docker.io/haveagitgat/tdarr_node_acc:dev_2.18.01_2024_05_09T08_07_55z
```

**Comment by matthijsvrenswoude** [comment]
Do you by chance also have Windows tdarr_acc and Windows tdarr_node_acc? That would make it a lot easier for me to set up and verify.

**Comment by HaveAGitGat** [comment]
Yes can try here:

```
https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.18.01/win32_x64/Tdarr_Server_2024_05_10T05_59_19z.zip
https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.18.01/win32_x64/Tdarr_Node_2024_05_10T05_59_19z.zip
```

**Comment by matthijsvrenswoude** [comment]
Doesn't look like it worked.
![afbeelding](https://github.com/HaveAGitGat/Tdarr/assets/21951789/ac88b229-e85f-4445-a9e5-58a516776db0)

As you can see, only extradata has been added while the rest are still missing:

Still missing:
-  file.ffProbeData.streams[0].extradata_size
-  All attributes in file.ffProbeData.streams[0].side_data_list
-  file.ffProbeData.streams[0].tags.encoder
  
  
Here you have sample file of Dolby Vision content to help debug:
[Ill](https://we.tl/t-24bU9MJbkM?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05)

CMD command where the data is shown: "ffprobe -v error -show_streams -show_format -show_data -print_format json -pretty filename"

**Comment by HaveAGitGat** [comment]
The extra data was showing for me, I’ll try again.

**Comment by matthijsvrenswoude** [comment]
Okay, a bit of an update, I was further developing my plugin and currently I am using a temporary workaround, launching a separate cli with ffprobe to retrieve the data that I need until the the correct way has been implemented. 

Anyway, I just discovered something during development when I was processing from MKV to MP4 (This is basically the goal for my plugin, to fix DV playback on LG tv's, which don't support DV in MKV). When in MP4 the DV data is indeed shown by Tdarr, don't know why this makes sense since it should also be there in when in MKV format, but this should probably help you to figure out what is going on.
![afbeelding](https://github.com/HaveAGitGat/Tdarr/assets/21951789/b3e83ad5-0c08-4b17-a2ad-f532fb63da8c)

**Comment by HaveAGitGat** [comment]
Thanks, it's due to the ffprobe version you're using. You can set `ffprobePath` in the Server or Node config file for any custom ffprobe builds.

These packages should now be working:

```
https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.18.01/win32_x64/Tdarr_Server_2024_05_13T06_05_56z.zip
https://tdarrs.s3.us-west-000.backblazeb2.com/dev/versions/2.18.01/win32_x64/Tdarr_Node_2024_05_13T06_05_56z.zip
```

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/2ab4c6bc-d36f-41d3-af02-c0fc668d9970)

**Comment by matthijsvrenswoude** [comment]
Okay great, I will test it out,

Just to mention, my FFmpeg/FFprobe path variable was set to version 2024-05-06-git-96449cfeae-full_build-www.gyan.dev

**Comment by matthijsvrenswoude** [comment]
Great can confirm it now also works in MKV.
Thanks for the support.

![afbeelding](https://github.com/HaveAGitGat/Tdarr/assets/21951789/98a0dc12-55e7-48b6-9d58-c3b11d4315d3)

**Comment by HaveAGitGat** [comment]
FYI I had to disable this in latest version as in 2.18.01 it was causing RAM issues as for some files it returns a huge amount of data (20MB+). So best to run the command manually if needed.

**Comment by matthijsvrenswoude** [comment]
What type of data did it return? I know extradata can be quite a bit since it essentially can contain extra encoder info, so I don't mind if you would keep that out, that's also probably problem what you are observing, but side_data_list honestly isn't that much data, so I would appreciate it if you could keep that in.

For example, I have here a file that contains HDR10, Dolby Vision and HDR10+, so it basically worst case scenario, for file size.

![afbeelding](https://github.com/HaveAGitGat/Tdarr/assets/21951789/2c9f706f-aa46-4ca6-8309-60c6971bc021)

Do keep in mind 1 attribute is currently missing since ffmpeg currently doesn't support all attributes of HDR10+ yet, but It looks like this:
![afbeelding](https://github.com/HaveAGitGat/Tdarr/assets/21951789/e759a1d4-e9a3-41ba-aa5e-f4861589a927)

Cant imaging these 4 arrays in side_data_list will increase file size that drastically.

**Comment by HaveAGitGat** [comment]
Yeah it was a tonne of extra data gibberish:

```
"extradata":"\n00000000: 5b53 6372 6970 7420 496e 666f 5d0d 0a54  [Script Info]..T\n00000010: 6974 6c65 3a20 5b53 7562 7350 6c75 732b  itle: [SubsPlus+\n00000020: 5d0d 0a53 6372 6970 7454 7970 653a 2076  ]..ScriptType: v\n00000030: 342e 3030 2b0d 0a57 7261 7053 7479 6c65  4.00+..WrapStyle\n00000040: 3a20 300d 0a50 6c61 7952 6573 583a 2031  : 0..PlayResX: 1\n00000050: 3238 300d 0a50 6c61 7952 6573 593a 2037  280..PlayResY: 7\n00000060: 3230 0d0a 5363 616c 6564 426f 7264 6572  20..ScaledBorder\n00000070: 416e 6453 6861 646f 773a 2079 6573 0d0a  AndShadow: yes..\n00000080: 0d0a 5b56 342b 2053 7479 6c65 735d 0d0a  ..[V4+ Styles]..\n00000090: 466f 726d 6174 3a20 4e61 6d65 2c20 466f  Format: Name, Fo\n000000a0: 6e74 6e61 6d65 2c20 466f 6e74 7369 7a65  ntname, Fontsize\n000000b0: 2c20 5072 696d 6172 7943 6f6c 6f75 722c  , PrimaryColour,\n000000c0: 2053 6563 6f6e 6461 7279 436f 6c6f 7572   SecondaryColour\n000000d0: 2c20 4f75 746c 696e 6543 6f6c 6f75 722c  , OutlineColour,\n000000e0: 2042 6163 6b43 6f6c 6f75 722c 2042 6f6c   BackColour, Bol\n000000f0: 642c 2049 7461 6c69 632c 2055 6e64 6572  d, Italic, Under\n00000100: 6c69 6e65 2c20 5374 7269 6b65 4f75 742c  line, StrikeOut,\n00000110: 2053 6361 6c65 582c 2053 6361 6c65 592c   ScaleX, ScaleY,\n00000120: 2053 7061 6369 6e67 2c20 416e 676c 652c   Spacing, Angle,\n00000130: 2042 6f72 6465 7253 7479 6c65 2c20 4f75   BorderStyle, Ou\n00000140: 746c 696e 652c 2053 6861 646f 772c 2041  tline, Shadow, A\n00000150: 6c69 676e 6d65 6e74 2c20 4d61 7267 696e  lignment, Margin\n00000160: 4c2c 204d 6172 6769 6e52 2c20 4d61 7267  L, MarginR, Marg\n00000170: 696e 562c 2045 6e63 6f64 696e 670d 0a53  inV, Encoding..S\n00000180: 7479 6c65 3a20 5375 6274 6974 6c65 2c53  tyle: Subtitle,S\n00000190: 504f 7665 7272 6964 6546 2c35 302c 2648  POverrideF,50,&H\n000001a0: 3030 4646 4646 4646 2c26 4830 3046 4646  00FFFFFF,&H00FFF\n000001b0: 4646 462c 2648 3030 3030 3030 3030 2c26  FFF,&H00000000,&\n000001c0: 4841 3030 3030 3030 302c 2d31 2c30 2c30  HA0000000,-1,0,0\n000001d0: 2c30 2c31 3030 2c31 3030 2c30 2c30 2c31  ,0,100,100,0,0,1\n000001e0: 2c32 2e34 2c31 2c32 2c34 302c 3430 2c34  ,2.4,1,2,40,40,4\n000001f0: 302c 310d 0a53 7479 6c65 3a20 5375 6274  0,1..Style: Subt\n00000200: 6974 6c65 2d41 6c74 2c53 504f 7665 7272  itle-Alt,SPOverr\n00000210: 6964 6546 2c35 302c 2648 3030 4646 4646  ideF,50,&H00FFFF\n00000220: 4646 2c26 4830 
```

Sure will need to verify if any of the other fields give a lot of data.

**Comment by HaveAGitGat** [comment]
Added for next version

**Comment by HaveAGitGat** [comment]
FYI toggle has been added for this as it still causes issues for files with large amounts of extra data:
https://github.com/HaveAGitGat/Tdarr/issues/1181
