### ISSUE TITLE
Variables and how to use them

### ISSUE THREAD

**Issue by xstrex** [HaveAGitGat/Tdarr#993]
I've already asked this question on Discord & Reddit, and no one seems to know. How are variables used in Tdarr? 

On each library I set a variable called `type:` to the content name of the library. After the media is processed, it (should) be sorted based on `type:` then perform an additional action. But the type variable gets skipped every time, and I’ve got no idea why. Plus the documentation references an older, non-relevant use of variables that doesn’t match the UI. 

How should I be using variables? 

Unanswered post on discord (with pictures): https://discord.com/channels/623392507828371476/1227992929268928512

**Comment by Marnalas** [comment]
Hi, not sure what you have tried so far, so I'll try to be as thorough as I can in the hope than you can pick up the solution to your problem.

1. Set the variable on every library that is gonna use the flow.
<img width="644" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/11569431/fbb08a9a-70a9-43a9-82be-4c7c71011a45">

2. Use the "Check Flow Variable" from the list of Flow Plugins, using the help tooltip of each input to understand what's expected by the plugin.
![image](https://github.com/HaveAGitGat/Tdarr/assets/11569431/266cc0b1-83c7-4fe7-b041-aff01bdd033f)
![image](https://github.com/HaveAGitGat/Tdarr/assets/11569431/fbc773bf-b719-4763-8fa0-06e9213b5c07)
![image](https://github.com/HaveAGitGat/Tdarr/assets/11569431/d82cf1e9-dafb-4397-8504-c58f4cb8bfde)

3. Run a test and check the logs.
<img width="1025" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/11569431/bc64127b-ee90-4e44-a8e9-32f2cf084e6e">

**Comment by Marnalas** [comment]
Happy to help ;)

> I know from experience that documentation is usually the last thing to be updated, but this section could use a little better explanation imo.

Couldn't agree more. Especially since most of the time you need the brackets {{{}}} around the variable but in this specific case you don't :S It's confusing. But Flows are still kinda new.

**Comment by xstrex** [comment]
Eureka! It actually worked! Thank you so much; it's so frustrating when you try to do the thing what seams like the right way, then ask for help and get crickets. Anyways, this is exactly what I've expected to see, but never did!!
![image](https://github.com/HaveAGitGat/Tdarr/assets/12849470/3336af6a-95c5-4c1b-a2c8-9ee875405904)

Now the full flow I've designed actually gets called, awesome!
