### ISSUE TITLE
Partial Library Requeing All Files

### ISSUE THREAD

**Issue by nichols89ben** [HaveAGitGat/Tdarr#994]
Could this be due to Tdarr starting up and scanning before network drive has fully connected? Causing files to be removed and then re-added?

_Originally posted by @HaveAGitGat in https://github.com/HaveAGitGat/Tdarr/issues/971#issuecomment-2005580045_

Any chance we can look at this again? The issue triggered again and requeued around ~1000 files. While only ~286 or so had any "transcoding" causing success (due to a minor flow edit), tdarr copies the file to complete the flow which triggers my backups to see a new file (even though its the same), causing the drives to get clogged up and rewrite all the data. Not sure what event triggerd it, since its been ahwile, but it is likely drive specific as I use mergefs. 

Logs attached, google drive link to DB2 if needed
[nodelogs.zip](https://github.com/HaveAGitGat/Tdarr/files/15282470/nodelogs.zip)

https://drive.google.com/file/d/1PhiGHLpM1whaM0mV7ag4toM2OmTE-3OL/view?usp=sharing

edit-  After thinking about it more, I realized this is happening to movies only on a specific tdarr server/container and not TV shows. I have 3 tdarr docker instances, one for movies, one for TV and one for others. The issue keeps occurring on the Movie server and not any TV shows. However if it as drive specific, there are movies and shows on the same drive and the tdarr servers are launched via the same compose file.

**Comment by HaveAGitGat** [comment]
Have you tried disabling the folder watcher for that specific library and maybe just use the hourly scan? Like you say it could be something causing the drive or a directory to appear as unavailable then available causing the files to be removed and added.

**Comment by nichols89ben** [comment]
> Have you tried disabling the folder watcher for that specific library and maybe just use the hourly scan? Like you say it could be something causing the drive or a directory to appear as unavailable then available causing the files to be removed and added.

Thats what i thought and I can try that, but after thinking about it, it seems its instance specific since its only happening to movies, I havent see this happen with TV shows. To clarify, I have 2 Tdarr instances/containers, one handles TV Shows and the other movies, however the drives are blended with content with mergefs. If this was drive specific, wouldnt the tv shows in the other instances trigger a requeue as well?

**Comment by HaveAGitGat** [comment]
Could also try enabling verbose logs on the logs tab, then check the logs if/when the issue repeats. Should show why it's rescanning them.

**Comment by HaveAGitGat** [comment]
Do you use unraid? Someone on Discord mentioned they only have this issue when the unraid `mover` is running on their drive.

**Comment by HaveAGitGat** [comment]
I've added a confirmation popup for that in the next version: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/3adcec46-96d8-4be0-b864-3dca984f6cf2)

Update here if it happens again ty.

**Comment by nichols89ben** [comment]
> I've added a confirmation popup for that in the next version: ![image](https://private-user-images.githubusercontent.com/43864057/340639954-3adcec46-96d8-4be0-b864-3dca984f6cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTc3MTQsIm5iZiI6MTcxODcxNzQxNCwicGF0aCI6Ii80Mzg2NDA1Ny8zNDA2Mzk5NTQtM2FkY2VjNDYtOTZkOC00YmUwLWI4NjQtM2RjYTk4NGY2Y2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEzMzAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NmY3ZWI3ZmMwZDQxMmE4YWZmYjRkNzdhYTkzNTRhYmNjMGYxOTU2OTY1ODgwMmJiYjY4Y2MwYmM0OWY2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ziH8EaSmWDNuWL9y52BrZLqMtGM7byVfK_jReEEyc1g)
> 
> Update here if it happens again ty.

Thanks for looking at it again! You should open up sponsorship at some point on github

**Comment by HaveAGitGat** [comment]
Good idea, atm Tdarr Pro does the job https://home.tdarr.io/download/ but could add GitHub sponsorship too at some point

**Comment by nichols89ben** [comment]
> Do you use unraid? Someone on Discord mentioned they only have this issue when the unraid `mover` is running on their drive.

I still haven't pinpointed the problem yet, but it is related to the drives or start up sequence. Ive been having some motherboard trouble requiring a lot of rebooting with/without drives trying to fix another issue. I finally got it online about 4 hours ago and just noticed all of my Tdarr servers processing/requeued all items in all libraries. Im going to restore from backups and see if that puts everything back in place. I attached the logs from today, they start when the server came back online, not sure if it helps. Do you think there could be an option for a fail safe in the settings? If the server queue's such a large amount of items, require a user input of of to proceed with processing? Just a thought

[Archive.zip](https://github.com/user-attachments/files/16653188/Archive.zip)
