### ISSUE TITLE
Clear or remove entries from the staging area

### ISSUE THREAD

**Issue by begunfx** [HaveAGitGat/Tdarr#998]
**Is your feature request related to a problem? Please describe.**
It seems there is no easy way currently to remove entries in the "Staging Section" > "Staged Files"

**Describe the solution you'd like**
There should be an option for every entry to be able to remove it from the list as well as an option to clear the entire staging section.

**Describe alternatives you've considered**
Only alternative I found was in a reddit comment: "Other way is to delete the StagedJSONDB folder in the server data and restart Tdarr."

Not really a great alternative.  Especially if you only want to remove "select" files.

**Additional context**

**Comment by HaveAGitGat** [comment]
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/4b3031bd-866a-4e25-a82d-14b4a4445781)

Take an action on the file to remove it from there.

**Comment by HaveAGitGat** [comment]
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/dc095f42-64e6-4eec-b5d9-88f61a4b5a37)

Likewise this button to apply to all files.

**Comment by begunfx** [comment]
Requeueing doesn't remove the files from the staging area, it just adds them back to be processed.  Possibly a compromise to this would be the option to delete the source file and remove from queue.  Not everyone is linking directly to their media library to process files.  I for one am copying files into a separate folder to be processed.  I can't imagine I'm the only one who has a workflow this way.  It would be nice to have an option to delete from the staging area and if need be removes the source file.  I understand that if you have the automatic file detection active for a library then just removing something from the queue doesn't exactly work.   Just my 2 cents.  Thanks!

**Comment by HaveAGitGat** [comment]
All of the actions remove the item from the staging area and put them into either the `Transcode queue` or `Transcode: Success/Not required`.

If you're not wanting to requeue the files then why not just `Skip` them, will move them to `Not required` status.

Items are not meant to be handled in the staging area like that, processing needs to have some sort of outcome (success, error, cancelled etc).

Alternatively can create a flow which processes the file, copies to output directory and then deletes the original file which sounds like what you're after:

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/4ed67978-a6d6-4d28-9453-89ebd6cd2cd1)
